### PR TITLE
x-pack/filebeat/input/azureeventhub: Support partitionID in Azure eventhub input

### LINKED ISSUE #36907: Support partitionID in Azure eventhub input
**Describe the enhancement:**

Currently partitionID is not supported in Azure eventhub input. It's commented out in the code because Azure SDK apparently doesn't support it. See commented out code here: https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/azureeventhub/input.go#L197
and here: https://github.com/elastic/beats/blob/main/x-pack/filebeat/input/azureeventhub/eph.go#L77

Is this still the case?

As far as I can see partitionID is supported: https://github.com/Azure/azure-event-hubs-go

**Describe a specific use case for the enhancement or feature:**

PartitionID is very useful for downstream applications consuming eventhub data, we use MQTT topic strings in our partitionID and use this to route data.

### PR DESCRIPTION
**Pull request by bhapas**
## Proposed commit message

See Title

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #36907

### CODE REVIEW

**Comment by Martin-Kemp** [comment]
Hi @bhapas, I pulled this locally to test and it seems to fail with a segmentation violation:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x5574e0828827]

goroutine 154 [running]:
github.com/elastic/beats/v7/x-pack/filebeat/input/azureeventhub.(*azureInput).runWithEPH.func1({0x0?, 0xc000311620?}, 0x0?)
        github.com/elastic/beats/v7/x-pack/filebeat/input/azureeventhub/eph.go:77 +0x27
github.com/Azure/azure-event-hubs-go/v3/eph.(*EventProcessorHost).compositeHandlers.func1.1(0x1c?)
        github.com/Azure/azure-event-hubs-go/v3@v3.6.1/eph/eph.go:445 +0x7c
created by github.com/Azure/azure-event-hubs-go/v3/eph.(*EventProcessorHost).compositeHandlers.func1
        github.com/Azure/azure-event-hubs-go/v3@v3.6.1/eph/eph.go:443 +0x1f6
```

**Comment by bhapas** [comment]
@Martin-Kemp Microsoft recommends to migrate to use new library https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs/README.md.

Not sure if they added support in older library? The [Migration Guide](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs/migrationguide.md) seems to impact a lot of other places. So probably need to raise another issue to tackle this first and then come back to check/fix PartitionID part

**Comment by Martin-Kemp** [comment]
Ah okay thanks @bhapas, I was hoping there's an easy fix for partitionID.

**Comment by bhapas** [comment]
@Martin-Kemp We can still look at the [`Event` struct](https://github.com/Azure/azure-event-hubs-go/blob/07e5a11a61336dfb2c5d6276c0298bb4e2d38625/event.go#L48) if they are writing the PartitionKey on the Event that comes in. I can add a log line and can you test again?

**Comment by Martin-Kemp** [comment]
> @Martin-Kemp We can still look at the [Event struct](https://github.com/Azure/azure-event-hubs-go/blob/07e5a11a61336dfb2c5d6276c0298bb4e2d38625/event.go#L48) if they are writing the PartitionKey on the Event that comes in. I can add a log line and can you test again?

Sure, I'll be happy to test it.

**Comment by bhapas** [comment]
@Martin-Kemp Just pushed a commit and updated the base as well. Can you try testing these [log lines](https://github.com/elastic/beats/pull/36948/files#diff-17abe3badfe654525ae0b133360a1bc22ba2e66bace0f9682578e605d07f100cR78-R79)

**Comment by Martin-Kemp** [comment]
There's also the method GetPartitionInformation on a hub object: https://github.com/Azure/azure-event-hubs-go/blob/07e5a11a61336dfb2c5d6276c0298bb4e2d38625/hub.go#L524

Which could be useful. But doesn't look like eph uses this object.

**Comment by zmoog** [comment]
@bhapas, there's an [issue](https://github.com/elastic/beats/issues/33815) tracking the need to upgrade to the new Event Hub SDK; it is waiting for a team to prioritize it.

I found the `partitionID` part already commented out when I joined Elastic and started working on the Azure ecosystem, so I don't know the backstory here. I tried getting the `partitionID` in the past, but the old SDK does not support this metadata reliably. 

The new SDK brings significant changes to the Event Hub; it replaces EPH with another non-compatible API.

**Comment by bhapas** [comment]
> @bhapas, there's an [issue](https://github.com/elastic/beats/issues/33815) tracking the need to upgrade to the new Event Hub SDK; it is waiting for a team to prioritize it.
> 
> I found the `partitionID` part already commented out when I joined Elastic and started working on the Azure ecosystem, so I don't know the backstory here. I tried getting the `partitionID` in the past, but the old SDK does not support this metadata reliably.
> 
> The new SDK brings significant changes to the Event Hub; it replaces EPH with another non-compatible API.

@zmoog That probably answers why it is behaving so. But should the commented out line point to this issue so that it is easy for users to track it and not get lost with this?

**Comment by zmoog** [comment]
> That probably answers why it is behaving so. But should the commented out line point to this issue so that it is easy for users to track it and not get lost with this?

We can check if we're running the latest minor/patch release of the old SDK and try it. I'm happy to help [debugging](https://github.com/zmoog/public-notes/issues/28) with the input to see if we get the `partitionID` in the callback from EPH. 

If we fail, we can add a comment pointing to the tracking issue and a +1 on the SDK upgrade.

**Comment by Martin-Kemp** [comment]
>@Martin-Kemp Just pushed a commit and updated the base as well. Can you try testing these [log lines](https://github.com/elastic/beats/pull/36948/files#diff-17abe3badfe654525ae0b133360a1bc22ba2e66bace0f9682578e605d07f100cR78-R79)

This also crashes while trying to log:

```
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x55b3c24f4db2]

goroutine 133 [running]:
github.com/elastic/beats/v7/x-pack/filebeat/input/azureeventhub.(*azureInput).runWithEPH.func1({0x0?, 0x0?}, 0xc001231400)
        github.com/elastic/beats/v7/x-pack/filebeat/input/azureeventhub/eph.go:78 +0x52
github.com/Azure/azure-event-hubs-go/v3/eph.(*EventProcessorHost).compositeHandlers.func1.1(0xc001a7e900?)
        github.com/Azure/azure-event-hubs-go/v3@v3.3.15/eph/eph.go:441 +0x7c
created by github.com/Azure/azure-event-hubs-go/v3/eph.(*EventProcessorHost).compositeHandlers.func1
        github.com/Azure/azure-event-hubs-go/v3@v3.3.15/eph/eph.go:439 +0x1f6
```

**Comment by Martin-Kemp** [comment]
@zmoog @bhapas let me know if you need me to test anything.

**Comment by bhapas** [comment]
@Martin-Kemp https://github.com/Azure/azure-event-hubs-go/issues/274 might be talking about what we are trying here and it seems the new SDK client supports this

**Comment by zmoog** [comment]
Running the input in debug mode shows that both `e.PartitionKey` and `e.SystemProperties.PartitionKey` are `nil` for some non-obvious reasons:

CleanShot 2023-10-26 at 15 48 42@2x

I'll bump the old SDK to the latest version and try again.

**Comment by zmoog** [comment]
Unfortunately, after upgrading the current/old SDK to v3.6.1, I got the same result.

```shell
go get github.com/Azure/azure-event-hubs-go/v3@v3.6.1   
```

CleanShot 2023-10-26 at 16 10 23@2x

**Comment by Martin-Kemp** [comment]
Thanks for all the effort @zmoog.

**Comment by zmoog** [comment]
@Martin-Kemp, thank you for upvoting the SDK upgrade by commenting on the [tracking issue](https://github.com/elastic/beats/issues/33815)!

I'll bring the attention to the need to do this SDK upgrade.

**Comment by bhapas** [comment]
Closing this PR as this is not relevant anymore.

**Comment by Martin-Kemp** [comment]
I can confirm that the new SDK works. I tested this basic example: https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/messaging/azeventhubs/example_consuming_events_test.go
and followed this documentation: https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/messaging/azeventhubs#section-readme

I sent a message to an eventhub and specified the partitionKey then read the message and got the partitionKey:
```
Received message: Your message content, PartitionKey: %!d(string=your-partition-key), sequence number: 0, enqueued time: 2023-10-27 10:34:41.948 +0000 UTC
```
By the way, it turns out I was looking for PartitionKey, not PartitionID. But both should be available with the new SDK.

**Pull request closed without merging**
