### PR TITLE
Makefile parser to write a Markdown file of make commands and variables

### PR DESCRIPTION
**Pull request by sayden**
I have started this _simple_ script which has the purpose of writing a Markdown file with information about the Makefile.

Planned features for the markdown file are:
* Command name
* Command dependencies with other commands
* Variables that can be used with a command
* Attached comments to each command

I have seen that there's already a python file which does something similar (commands plus comments) but it wasn't working in my setup and the error it was giving wasn't really clear about how to proceed

### CODE REVIEW

**Comment by ruflin** [comment]
Long term we plan to move more and more parts of the Makefile and Python to Golang and Mage files. If the above is simple script we should get it in but not spend too much time on it. It comes down to if it's quicker to fix the python script or create a new Golang one. In any case, if we add the script, we should document on how to run it.

**Comment by sayden** [comment]
Thanks for the comments. I quickly did it because I really needed it for myself and I thought it would be helpful for newcomers too. It's gonna be simple enough, less than 200 loc and once it's finished (I think it just lacks like one hour or a couple more) it will have nice CLI and commented code.

Once it's finished, and you look at it, you're free to reject it if you consider it, no prob. I just don't wanted to "hide" it in my laptop :slightly_smiling_face:

**Comment by sayden** [comment]
I think this won't be necessary in the short term finally. Closing

**Comment by andrewkroh** [comment]
FYI: With `mage` you can do `mage -l` and `mage -h <target>`.

```
$ mage -l
Targets:
  build                 builds the Beat binary.
  buildGoDaemon         builds the go-daemon binary (use crossBuildGoDaemon).
  check                 runs fmt and update then returns an error if any modifications are found.
  clean                 cleans all generated files and build artifacts.
  config                generates both the short and reference configs.
  crossBuild            cross-builds the beat for all target platforms.
  crossBuildGoDaemon    cross-builds the go-daemon binary using Docker.
  dashboards            collects all the dashboards and generates index patterns.
  fields                generates a fields.yml and fields.go for each module.
  fmt                   formats source code and adds file headers.
  goIntegTest           executes the Go integration tests.
  goUnitTest            executes the Go unit tests.
  golangCrossBuild      build the Beat binary inside of the golang-builder.
  integTest             executes integration tests (it uses Docker to run the tests).
  package               packages the Beat for distribution.
  pythonIntegTest       executes the python system tests in the integration environment (Docker).
  pythonUnitTest        executes the python system tests.
  testPackages          tests the generated packages (i.e.
  unitTest              executes the unit tests.
  update                is an alias for running fields, dashboards, config.

$ mage -h package
mage package:

Package packages the Beat for distribution.
Use SNAPSHOT=true to build snapshots.
Use PLATFORMS to control the target platforms.
Use BEAT_VERSION_QUALIFIER to control the version qualifier.
````

**Pull request closed without merging**
