### PR TITLE
[DOCS] Add the `read_pipeline` cluster privilege to winlogbeat documentation

### PR DESCRIPTION
**Pull request by herrBez**
Add the "read_pipeline" privilege to the [Grant privileges and roles needed for publishing](https://www.elastic.co/guide/en/beats/winlogbeat/current/privileges-to-publish-events.html) documentation as reported in the [Grant access using API keys](https://www.elastic.co/guide/en/beats/winlogbeat/current/beats-api-keys.html).

## Proposed commit message

[Winlogbeat][Doc] Add `read_pipeline` cluster privilege to winlogbeat

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- https://github.com/elastic/beats/issues/39067

## Use cases

Adhere to the least privilege principles

### CODE REVIEW

**Comment by belimawr** [comment]
LGTM, however CI is failing, @herrBez could you take a look at this failure?

**Comment by herrBez** [comment]
Hi,

Thank you for the fast feedback. Maybe we need to extend the PR to add also the `auto_configure` permission to allow the users to dynamically update the mapping of the datastreams. Read more in the (internal) Slack discussions:
- https://elastic.slack.com/archives/C0D8SUKB2/p1711038886786539 
- https://elastic.slack.com/archives/C0D8ST60Y/p1711044591714479

About the build:
I have only the rights to view the Jenkins Job and I am not allowed to view the buildkite result.
The jenkins job is failing during a go install:
image

I hardly believe it has something to do with the change I introduced.

**Comment by ycombinator** [comment]
I also just noticed that this PR was originally targeting the `master` branch.  We have switched over to using the `main` branch now instead so I've re-targeted this PR to the `main` branch as well.

**Comment by herrBez** [comment]
Hi there,

The only failing check is:
image

I honestly don't know if and where I should put this ECS version. Can someone help me in figure out what it's needed here to fix the problem? (I don't have access to the buildkite agent logs).

**Review by andrewkroh — APPROVED** [review]

**Comment by herrBez** [comment]
Hi there,
I am not able to merge the change even though it has been approved, because the build is not successful. By looking at the errors I don't think they are related with the changes I did. Can someone help me in understand what I need to do to be able to merge the PR?

**Comment by andrewkroh** [comment]
@herrBez There appears to be an issue with the links.

https://buildkite.com/elastic/docs-build-pr/builds/73547#018f58b1-6108-49d9-9876-4753c957356f/54-1560

> INFO:build_docs:Bad cross-document links:
> INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/auditbeat/master/privileges-to-publish-events.html contains broken links to:
> INFO:build_docs:   - en/elasticsearch/reference/current/docs-index_.html#index-creation,action.auto_create_index
> INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/filebeat/master/privileges-to-publish-events.html contains broken links to:
> INFO:build_docs:   - en/elasticsearch/reference/current/docs-index_.html#index-creation,action.auto_create_index
> INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/functionbeat/master/privileges-to-publish-events.html contains broken links to:
> INFO:build_docs:   - en/elasticsearch/reference/current/docs-index_.html#index-creation,action.auto_create_index
> INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/heartbeat/master/privileges-to-publish-events.html contains broken links to:
> INFO:build_docs:   - en/elasticsearch/reference/current/docs-index_.html#index-creation,action.auto_create_index
> INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/metricbeat/master/privileges-to-publish-events.html contains broken links to:
> INFO:build_docs:   - en/elasticsearch/reference/current/docs-index_.html#index-creation,action.auto_create_index
> INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/packetbeat/master/privileges-to-publish-events.html contains broken links to:
> INFO:build_docs:   - en/elasticsearch/reference/current/docs-index_.html#index-creation,action.auto_create_index
> INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/winlogbeat/master/privileges-to-publish-events.html contains broken links to:
> INFO:build_docs:   - en/elasticsearch/reference/current/docs-index_.html#index-creation,action.auto_create_index

**Pull request merged**
