### PR TITLE
Revert #29031

### PR DESCRIPTION
**Pull request by ph**
This revert the code #29031 of the APM Instrumentation of the Elastic Agent.
To unblock the build of and the CI for other team. This would require
more investigation to really understand the problem.

Fixes https://github.com/elastic/fleet-server/issues/1129

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by ph** [comment]
@kvch Adding you to this PR as well, because when I've reverted the code for the instrumentation I had conflict with the configuration loading change.

**Comment by ph** [comment]
@michel-laterman I've fixed a linter issue from the diagnostic command, can you take a look at this specific part?

**Comment by ph** [comment]
@simitt fyi, I will check tomorrow with Stuart, but let's unblock people for now.

**Review by blakerouse — APPROVED** [review]
Tested this and it does fix the issue.

**Pull request merged**
