### PR TITLE
[packetbeat/protos/http] fix: non-standard http host format error and add extract host tests.

### LINKED ISSUE #36497: [packetbeat] panic when parsing HTTP host header with non-standard format
For confirmed bugs, please report:
- Version: 8.9.1
- Operating System: Linux
- Discuss Forum URL: https://discuss.elastic.co/t/bug-panic-when-packetbeat-parsing-http-host-header-with-non-standard-format/342258
- Steps to Reproduce: 
#### Summary:

Packetbeat(all version) encounters a panic when parsing HTTP requests that have a non-standard `Host` header. The issue occurs in the function `extractHostHeader` and manifests as an "index out of range" panic.

#### Steps to Reproduce:

1. Use Packetbeat to capture HTTP traffic.
2. Make an HTTP request where the `Host` header is of the form `:12345` (just a port number without the hostname).

#### Expected Result:

Packetbeat should handle non-standard `Host` headers gracefully, either by ignoring them or logging an error message.

#### Actual Result:

Packetbeat panics with "index out of range".
```
panic: runtime error: index out of range [0] with length 0

goroutine 130 [running]:
*****/protos/http.extractHostHeader({0xc01cf26ea8, 0x3})
        *****/protos/http/http.go:737 +0x21b
*****/protos/http.(*httpPlugin).newTransaction(0xc0000f4f70, 0xc0073d8c80, 0xc0    073d9180)
        *****/protos/http/http.go:541 +0xbff
*****/protos/http.(*httpPlugin).correlate(0xc0000f4f70, 0xc02930e9c0)
        *****/protos/http/http.go:483 +0x111
*****/protos/http.(*httpPlugin).handleHTTP(0xc0000f4f70, 0xc02930e9c0, 0xc0073d    9180, 0x7f1aef56cf18?, 0xa0?)
        *****/protos/http/http.go:442 +0x3fb
*****/protos/http.(*httpPlugin).messageComplete(...)
        *****/protos/http/http.go:233
```

### PR DESCRIPTION
**Pull request by moonD4rk**
## Proposed commit message

fix: non-standard http host format when packetbeat capture http request and add extract host test cases.
- Add test for `extractHostHeader` function

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

check and use `go test -v ./...`

## Related issues

- Close #36497

## Use cases
Packetbeat panic when HTTP requests that have a non-standard Host header. such as `:1234`

TestCase

``` go
func TestHttpParser_extractHostHeader(t *testing.T) {
	var testCases = []struct {
		host       string
		wantedHost string
		wantedPort int
	}{
		{":1234", "", 1234},
	}
	for _, tc := range testCases {
		host, port := extractHostHeader(tc.host)
		assert.Equal(t, tc.wantedHost, host)
		assert.Equal(t, tc.wantedPort, port)
	}
}
```
use `go test -v ./...`

before:
``` go
=== RUN   TestHttpParser_extractHostHeader
--- FAIL: TestHttpParser_extractHostHeader (0.00s)
panic: runtime error: index out of range [0] with length 0 [recovered]
	panic: runtime error: index out of range [0] with length 0
```
after:
```
=== RUN   TestHttpParser_extractHostHeader
--- PASS: TestHttpParser_extractHostHeader (0.00s)
PASS
```

### CODE REVIEW

**Comment by bhapas** [comment]
@moonD4rk 

Thank you for your contribution. Can you please sign the CLA agreement for contributors for CI to proceed running your change. - [Contributor Agreement](https://www.elastic.co/contributor-agreement)

**Comment by moonD4rk** [comment]
> @moonD4rk
> 
> Thank you for your contribution. Can you please sign the CLA agreement for contributors for CI to proceed running your change. - [Contributor Agreement](https://www.elastic.co/contributor-agreement)↳

Hi, I'm already signed and passed the CI test.

**Comment by bhapas** [comment]
Thanks @moonD4rk 
Can you add a changelog after https://github.com/elastic/beats/blob/1209bca121e23d20347224f5d4adf66b9b48f0bf/CHANGELOG-developer.next.asciidoc?plain=1#L88

**Pull request closed without merging**
