### PR TITLE
Update ecs version to 8.2

### PR DESCRIPTION
**Pull request by tetianakravchenko**
Signed-off-by: Tetiana Kravchenko <tetiana.kravchenko@elastic.co>

## What does this PR do?

Update ECS version to 8.2

## Why is it important?

To add fields added in ECS 8.2 available in beats version 8.2

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Relates https://github.com/elastic/beats/issues/30957

### CODE REVIEW

**Comment by ruflin** [comment]
If we keep adding all the new ECS fields for each release to all beats, the template size keeps growing even though a large portion of the fields are not used by some of the Beats. Instead Beats templates should only contain the fields from ECS which are actually used. 

This is not a new problem but this PR makes it more obvious by hitting issue. Can we please open an issue around updating ECS in Beats to have a further discussion.

My understanding is the background of this PR is because we need 1-2 new fields in ECS in one of the Beats. Lets add it manually there to get this unblocked and tackled the ECS version update separately.

**Comment by ebeahan** [comment]
Agree with @ruflin.

However, if the team does move forward with updating the top-level ECS fields here, please use the current Beats field definitions: https://github.com/elastic/ecs/blob/8.2/generated/beats/fields.ecs.yml. There was a brief period when the ECS 8.2 branch had a much larger number of fields, and, unfortunately, this appears to be when this PR was opened.

**Comment by ruflin** [comment]
Is there any feature currently needing this change? If not, I would rather first resolve this conversation here: https://github.com/elastic/ecs/issues/1869

**Comment by tetianakravchenko** [comment]
I will close this issue for now, till conversation https://github.com/elastic/ecs/issues/1869 will be resolved

**Pull request closed without merging**
