### PR TITLE
Fix renaming cloud metadata processor fields

### PR DESCRIPTION
**Pull request by jalaziz**
Clone the underlying metadata to allow renaming sub-fields under cloud
that are injected by the cloud metadata processor.

Without cloning the injected metadata, `rename` and possibly other processors fail to operate on the sub-fields of the injected `cloud` field.

Further details can be found in the community post: https://discuss.elastic.co/t/cannot-rename-sub-fields-of-cloud-metadata-added-via-add-cloud-metadata/201157.

### CODE REVIEW

**Comment by jalaziz** [comment]
Any chance of this getting reviewed soon?

**Comment by kaiyan-sheng** [comment]
Sorry for the delay. This looks good to me (besides the conflict).  @adriansr Could you take a look as well please?

**Comment by jalaziz** [comment]
Rebased to fix the conflict.

**Comment by andrewkroh** [comment]
jenkins, test this

**Comment by kaiyan-sheng** [comment]
jenkins, test this please

**Comment by jsoriano** [comment]
> LGTM. This probably also prevents a concurrent map modification panic.

Yep, https://github.com/elastic/beats/issues/17968 seems to be fixed by this. I have opened backports for 7.6 and 6.8 too.

**Pull request merged**
