### PR TITLE
[Metricbeat] In jolokia jmx mbean canonization the keys should be sorted first

### LINKED ISSUE #25630: [METRICBEAT] Jolokia JMX mBeanName.Canonicalize() fails to sort correctly the properties
Hey folks,

I noticed that the the Canonicalize method will sort the strings, but that has some edge cases:
https://github.com/elastic/beats/blob/afbdaa93ccc2d1a10adb7eed275840f3a66bf498/metricbeat/module/jolokia/jmx/config.go#L142

here:
https://github.com/elastic/beats/blob/afbdaa93ccc2d1a10adb7eed275840f3a66bf498/metricbeat/module/jolokia/jmx/config.go#L153

e.g. input "solr:dom1=jvm,name=used,name0=memory,name1=total"
the method returns "solr:dom1=jvm,name0=memory,name1=total,name=used" which is not very canonical

can i submit a pull request for this?
https://github.com/elastic/beats/blob/afbdaa93ccc2d1a10adb7eed275840f3a66bf498/metricbeat/module/jolokia/jmx/config.go#L156
I'd propose sorting only on the keys, then adding the correct values

best regards
atanas

### PR DESCRIPTION
**Pull request by Hacko-nPacko**
## What does this PR do?

This PR fixes https://github.com/elastic/beats/issues/25630
The mBeanName.Canonicalize(...) fails to sort the properties correctly if there're properties which are prefixes of other properties. e.g.; 

## Why is it important?

after the fix, the metricbeat will be able to parse the solr specific mbeans exposed under the "solr" domain, e.g.
solr:dom1=jvm,name=used,name0=memory,name1=total

## Checklist

the new test in `config_test - TestCanonicalizeMbeanName` should pass

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes #25630
- Relates #25630

### CODE REVIEW

**Comment by Hacko-nPacko** [comment]
Hey @jsoriano,
thanks for merging it

happy to help!

best
atanas

**Comment by jsoriano** [comment]
Hey @Hacko-nPacko, not so fast, I approved the PR but it hadn't been merged yet :) Could you please create it again?

**Comment by Hacko-nPacko** [comment]
@jsoriano sorry, my bad :)

**Comment by jsoriano** [comment]
@Hacko-nPacko there seems to be some linting problem with the files modified in this PR, could you run `mage update` from the `metricbeat` directory and commit the changes?

**Comment by Hacko-nPacko** [comment]
Hey @jsoriano 

i tried with 
$ mage update
$ make update
$ mage fmt

and still i have my repo clean:
Screenshot 2021-05-12 at 21 04 12


i also executed the same command in the root of the repo, same result.

is there a tutorial i can follow and get this fmt/linting through?

thanks
atanas

**Comment by Hacko-nPacko** [comment]
Hey,

frankly, i thought that this linter errors were because the files were updated on the master, so i rebased (can be seen with these 23 commits on this PR)


at this point i think it's too much noise on this PR and i'd suggest i make a new one?


best
atanas

**Comment by jsoriano** [comment]
@Hacko-nPacko let me try to fix it...

**Comment by jsoriano** [comment]
@Hacko-nPacko I have force-pushed to your branch your commits directly over master, I also run make update and found a couple of formatting issues, they should be solved now. Please double-check if I have missed some change.

**Comment by Hacko-nPacko** [comment]
Hey @jsoriano this is very good. 

Thanks a lot for your help!

**Pull request merged**
