### PR TITLE
Cherry-pick #21861 to 7.x: chore: delegate variant pushes to the right method

### PR DESCRIPTION
**Pull request by jsoriano**
Cherry-pick of PR #21861 and #21621 to 7.x branch. Original message: 

## What does this PR do?
It groups the conditions for pushing the docker image of each beat, because the logic for the variants is responsible of pushing or logging a warning if the image exists.

## Why is it important?
It won't push some of the images twice, also simplifying the IF/ELSE logic.

Apart from that, there are wrong image names after the addition of variants, like `filebeat-oss-oss`.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [x] Groovy file validated

## Related issues

- Caused by #21621

### CODE REVIEW

**Comment by jsoriano** [comment]
Trying to fix some issues with tag and push in 7.x branch. Like this one: https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fpackaging/detail/PR-23110/3/pipeline
```
[2020-12-14T18:11:52.857Z] + docker tag docker.elastic.co/beats/packetbeat:7.11.0-SNAPSHOT docker.elastic.co/observability-ci/packetbeat:pr-23110
[2020-12-14T18:11:52.857Z] Error response from daemon: No such image: docker.elastic.co/beats/packetbeat:7.11.0-SNAPSHOT script returned exit code 1
```

**Review by kaiyan-sheng — APPROVED** [review]

**Comment by jsoriano** [comment]
Cherry-picking https://github.com/elastic/beats/pull/21621 too as might be related.

**Comment by jsoriano** [comment]
Closing this in favour of https://github.com/elastic/beats/pull/23142, that includes some changes that were backported to 7.10, but not to 7.x.

**Pull request closed without merging**
