### PR TITLE
Backport 1.2.1 - Topbeat

### PR DESCRIPTION
**Pull request by andrewkroh**
Backport of #845 to 1.2 - Add username to Topbeat
Backport of #1128 to 1.2 - Change Cpu.Get() on Windows to not use floating point arithmetic

My second or third attempt at getting this into 1.x. :grin:

### CODE REVIEW

**Comment by andrewkroh** [comment]
jenkins, rebuild it

**Comment by andrewkroh** [comment]
jenkins, retest it

**Comment by andrewkroh** [comment]
jenkins, test it

**Comment by tsg** [comment]
Should add `proc.username` to `fields.yml`.

**Comment by tsg** [comment]
I'm merging this for testing.

**Comment by tsg** [comment]
Tested on OS X, Windows and Linux, all doing fine. Thank you @andrewkroh, third time's the charm :)

**Pull request merged**
