### PR TITLE
Add Azure Dashboard

### PR DESCRIPTION
**Pull request by sorantis**
These dashboards visualize metrics for Azure virtual machines, vm guest metrics, virtual machine scale sets.

metricbeat-azure-vm-overview
metricbeat-azure-vm-guestmetrics-overview
metricbeat-azure-vmss-overview

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
LGTM, just curious why in these dashboards, the _Filters_ section is different?

**Comment by kaiyan-sheng** [comment]
> > LGTM, just curious why in these dashboards, the _Filters_ section is different?
> 
> Mainly because the dashboards show different entities: VMSS consist of VMs, so in addition to Region and Resource Group the user might want to drill down to a particular VM in a VMSS and check metrics for it. For Guest metrics the use case is the same - show ASP.NET, SQL Server metrics for a particular VM instead of an aggregate.

Thanks for the explanation. For Compute VM Overview, will it be helpful to add VM name as a filter for user to drill down as well?

CI is not happy with the json file: 
```
2019-10-10T15:18:17.852Z	ERROR	instance/beat.go:886	Exiting: Failed to import dashboard: Failed to load directory /go/src/github.com/elastic/beats/x-pack/metricbeat/build/system-tests/run/test_xpack_base.Test.test_dashboards/kibana/7/dashboard:
  error loading /go/src/github.com/elastic/beats/x-pack/metricbeat/build/system-tests/run/test_xpack_base.Test.test_dashboards/kibana/7/dashboard/Metricbeat-azure-vm-guestmetrics-overview.json: returned 400 to import file: <nil>. Response: {"statusCode":400,"error":"Bad Request","message":"Document \"64930c20-eaa6-11e9-90ec-112a988266d5\" has property \"visualization\" which belongs to a more recent version of Kibana (7.3.1)."}
  error loading /go/src/github.com/elastic/beats/x-pack/metricbeat/build/system-tests/run/test_xpack_base.Test.test_dashboards/kibana/7/dashboard/Metricbeat-azure-vm-overview.json: returned 400 to import file: <nil>. Response: {"statusCode":400,"error":"Bad Request","message":"Document \"5031b220-eb61-11e9-90ec-112a988266d5\" has property \"visualization\" which belongs to a more recent version of Kibana (7.3.1)."}
  error loading /go/src/github.com/elastic/beats/x-pack/metricbeat/build/system-tests/run/test_xpack_base.Test.test_dashboards/kibana/7/dashboard/Metricbeat-azure-vmss-overview.json: returned 400 to import file: <nil>. Response: {"statusCode":400,"error":"Bad Request","message":"Document \"686bc990-ea92-11e9-90ec-112a988266d5\" has property \"visualization\" which belongs to a more recent version of Kibana (7.3.1)."}
Exiting: Failed to import dashboard: Failed to load directory /go/src/github.com/elastic/beats/x-pack/metricbeat/build/system-tests/run/test_xpack_base.Test.test_dashboards/kibana/7/dashboard:
  error loading /go/src/github.com/elastic/beats/x-pack/metricbeat/build/system-tests/run/test_xpack_base.Test.test_dashboards/kibana/7/dashboard/Metricbeat-azure-vm-guestmetrics-overview.json: returned 400 to import file: <nil>. Response: {"statusCode":400,"error":"Bad Request","message":"Document \"64930c20-eaa6-11e9-90ec-112a988266d5\" has property \"visualization\" which belongs to a more recent version of Kibana (7.3.1)."}
  error loading /go/src/github.com/elastic/beats/x-pack/metricbeat/build/system-tests/run/test_xpack_base.Test.test_dashboards/kibana/7/dashboard/Metricbeat-azure-vm-overview.json: returned 400 to import file: <nil>. Response: {"statusCode":400,"error":"Bad Request","message":"Document \"5031b220-eb61-11e9-90ec-112a988266d5\" has property \"visualization\" which belongs to a more recent version of Kibana (7.3.1)."}
  error loading /go/src/github.com/elastic/beats/x-pack/metricbeat/build/system-tests/run/test_xpack_base.Test.test_dashboards/kibana/7/dashboard/Metricbeat-azure-vmss-overview.json: returned 400 to import file: <nil>. Response: {"statusCode":400,"error":"Bad Request","message":"Document \"686bc990-ea92-11e9-90ec-112a988266d5\" has property \"visualization\" which belongs to a more recent version of Kibana (7.3.1)."}```

**Comment by sorantis** [comment]
> For Compute VM Overview, will it be helpful to add VM name as a filter for user to drill down as well?

Added a vm filter. 

Regarding the CI error, not sure how to approach solving it. I'm using metricbeat and stack v7.4.0 for exporting dashboards. Is there some incompatibility on the version level?

**Comment by sorantis** [comment]
jenkins test this

**Pull request merged**
