### PR TITLE
Added KrakenBeat

### PR DESCRIPTION
**Pull request by PPACI**
https://github.com/PPACI/krakenbeat[krakenbeat]:: Collect information on each transaction on the Kraken crypto platform.

### CODE REVIEW

**Comment by karmi** [comment]
Hi @PPACI, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/beats/pull/5393.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by PPACI** [comment]
@karmi : Done !

**Comment by kvch** [comment]
Thank you for your contribution! Could you please put your beat after kafkabeat? The list is sorted alphabetically.

**Comment by PPACI** [comment]
I'm sorry, i miss clicked when pasted my change

**Comment by kvch** [comment]
thanks!

**Pull request merged**
