### PR TITLE
added PGID field to Process struct to use the recent gosigar addition

### PR DESCRIPTION
**Pull request by nickivanov**
This time for metricbeat and updated field docs.

### CODE REVIEW

**Comment by ruflin** [comment]
It seems like still some updates on the system tests are needed: https://travis-ci.org/elastic/beats/jobs/143615788#L2408

Can you also update the CHANGELOG file with this change?

**Comment by nickivanov** [comment]
That's an old log, by the way.

**Comment by ruflin** [comment]
@nickivanov Any reason that you the PR's instead of just updating them?

**Comment by nickivanov** [comment]
@ruflin Sorry, I didn't understand the question.

**Comment by ruflin** [comment]
You close https://github.com/elastic/beats/pull/2004 and https://github.com/elastic/beats/pull/2010 and opened https://github.com/elastic/beats/pull/2021 Why not just updating the existing PR with the changes? Otherwise we loose all the comments / feedback every time a new one is opened.

**Comment by nickivanov** [comment]
Oh, sorry, I didn't realize I could update an existing pull request with new commits. Should I reopen #2004 then, and close the latest? You can probably tell I'm not very familiar with the workflow.

**Comment by ruflin** [comment]
No worries. Take the PR of the 3 which is best for you to continue :-) New commits will appear in the PR as soon as you push them to your branch. Let me know if you need some help.

**Comment by nickivanov** [comment]
OK then, I think I'll keep #2021 going forward and update it if it becomes necessary.

**Pull request closed without merging**
