### PR TITLE
Fix system process CPU ticks field mapping

### PR DESCRIPTION
**Pull request by andrewkroh**
Enabling `process.include_cpu_ticks: true` would cause an Elasticsearch mapping conflict because the `.ticks` fields for user and system were not defined in the fields.yml.

### CODE REVIEW

**Comment by ctindel** [comment]
Shouldn't we add some tests that expose the original issue to make sure this doesn't happen again?

**Comment by andrewkroh** [comment]
@ctindel I was thinking the same thing. I updated the test case for the process metricset. It ran the updated test case without the fix and it failed (e.g. `Exception: Key 'system.process.cpu.system.ticks' found in event is not documented!`).

**Comment by ctindel** [comment]
Well done!

**Comment by ctindel** [comment]
@andrewkroh do you know which point release this will ship in?

**Comment by ruflin** [comment]
@andrewkroh I did a rebase merge on this as it had 2 clean commits with description. But after merging I realised it would have been better as 1 commit because of the backport :-(

**Pull request merged**
