### PR TITLE
Update communitybeats.asciidoc

### PR DESCRIPTION
**Pull request by visasimbu**
## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by visasimbu** [comment]
Updated IIBBeat

**Comment by ChrsMark** [comment]
Hey @visasimbu thank you for adding this! Could you please sign the CLA?

**Comment by visasimbu** [comment]
@ChrsMark I have submitted documents. Kindly let me know for any concerns

**Comment by ChrsMark** [comment]
cla/check

**Comment by ChrsMark** [comment]
@visasimbu thank you, can you verify that it is signed with the same email you use in your github account? It seems that it is not signed yet and `visasimbu` GH username cannot be found in the signed users.

**Comment by visasimbu** [comment]
I have mentioned as visasimbu in Doc.

**Comment by ChrsMark** [comment]
Could you please try again and re-sign it, just in case it didn't work the last time?
Remember to use the same email that is registered in your Github account. Thank you and sorry for the back and forth.

**Comment by visasimbu** [comment]
@ChrsMark Are you fine with document to approve it ? Kindly let me know

**Comment by visasimbu** [comment]
@ChrsMark I have signed once again and uploaded a document. Please let me know for any concerns

**Comment by ChrsMark** [comment]
jenkins, test this again please

**Comment by visasimbu** [comment]
Hi Elastic/Beats Team,

Thanks for merging in master. Though I couldn't find "IIBBeat" in the
community beats page.

https://www.elastic.co/guide/en/beats/libbeat/current/community-beats.html

Thanks
Simbu

**Comment by ChrsMark** [comment]
Hi @visasimbu ! It will shown up in the docs (https://www.elastic.co/guide/en/beats/libbeat/master/community-beats.html) soon. Docs's page is being updated periodically.

**Comment by visasimbu** [comment]
@ChrsMark Hi Chris, It's a week passed. Usually how long it ll take to sync up with main "community beat" website.

**Comment by ChrsMark** [comment]
Hi! It's already on master's docs, see https://www.elastic.co/guide/en/beats/libbeat/master/community-beats.html.

**Comment by visasimbu** [comment]
@ChrsMark I have checked the given sites which has below banner at the top of the site. Also when I search in Google and I am landing in this website where I dot find my beat contribution.

Am I missing something here ?

https://www.elastic.co/guide/en/beats/libbeat/current/community-beats.html
 
You are looking at preliminary documentation for a future release. Not what you want? See the current release documentation.

**Comment by ChrsMark** [comment]
Yes it has landed in `7.8` (and beyond) documentation. When it was merged the future freeze had already happened so this is why it will be on `7.8`. Thanks!

**Pull request merged**
