### PR TITLE
[metricbeat] support basepath in beat module

### PR DESCRIPTION
**Pull request by stuartnelson3**
## What does this PR do?

Support `basepath` in the beat module, as per the documentation

## Why is it important?

This is expected behavior, and it's documented as being supported.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- closes https://github.com/elastic/beats/issues/28159

### CODE REVIEW

**Review by simitt — APPROVED** [review]
LGTM - but let's wait for someone from the agent team to review.

**Comment by sayden** [comment]
Hi :slightly_smiling_face: 

This is a screencapture from Wireshark of Beat module in the current state (master) without PR.

image

And this is my Beat config:

```yml
# Module: beat
# Docs: https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-beat.html

- module: beat
  basepath: "/processes/metricbeat-default"
  metricsets:
    - stats
    - state
  period: 10s
  hosts: ["http://localhost:5066"]
```

Are we talking about the same thing? Because it seems to me that it's working as expected :slightly_smiling_face:

**Comment by stuartnelson3** [comment]
That is what we're talking about, but it contradicts what I found when adding some logging (see https://github.com/elastic/beats/issues/28159), and the tests I wrote confirm the original behavior strips the basepath, as well.

Check your wireshark capture further, I'm guessing there are also requests sent to localhost:5066 and localhost:5066/state.

Once I implemented my changes, it was successfully scraping the basepath and no longer 404'ing.

**Review by sayden — APPROVED** [review]
Jeeezzz I was getting crazy because I really couldn't see anything wrong on wireshark but I now have seen in the code a second call.

My test wasn't trying that call because I was already getting the 404 so the code-path was unreachable. Just because I was lazy to setup an nginx.

Good catch! Thank you for the explanation and the contribution. I leave you the "honor" of merging :smile:

**Pull request merged**
