### PR TITLE
Add expected json for test files in filebeat system module

### PR DESCRIPTION
**Pull request by jsoriano**
There were some test files in system module without expected json file, generate and add them.

### CODE REVIEW

**Comment by ruflin** [comment]
Historically we only created the expected files for a few lines to check the output. Most files with more lines we didn't check. Should we generate the expected output for all our log files moving forward? What is the impact on the Github repo here?

**Comment by jsoriano** [comment]
Oh, I though someone forgot to add the expected json files, but I see now that there are much more test files without expected json. What was the purpouse of these files? Just for reference?

**Comment by jsoriano** [comment]
I have generated the expected json for all log files we have and they suppose tens of thousands of lines. Let's keep them as they are by now, they can be still used to cherry pick lines for expecific test cases.

**Comment by ruflin** [comment]
The files that are there without expected files are still used for the test but do the ingest part only and check that no error is returned. To keep the repository small and potentially have even load tests in the future I hope we could in the future also have test files on S3 or similar (I remember we discussed this in the past and you had some ideas around where to store the files).

**Comment by jsoriano** [comment]
Ok, makes sense, thanks

**Pull request closed without merging**
