### PR TITLE
Remove beta flag for Enterprise Search metricbeat module

### PR DESCRIPTION
**Pull request by richkuz**
We've been using this module internally for Stack monitoring since 8.2. I think we can remove the beta flag.

cc @aznick @carlosdelest @ioanatia

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by richkuz** [comment]
I'm pausing on this PR for a moment, awaiting further discussion with @ioanatia  on how we want to proceed in general with the Enterprise Search metricbeat module.

**Comment by richkuz** [comment]
Passing the baton to @carlosdelest . This PR is not urgent, but we should agree to cancel (defer) or merge it so it isn't lingering.

**Comment by carlosdelest** [comment]
@ioanatia , what will be our strategy for Metricbeat? I think it's going to be replaced by Agent eventually, but I guess we can make it GA. Any reason not to?

**Comment by carlosdelest** [comment]
@ioanatia , thoughts on this one?

**Comment by carlosdelest** [comment]
Closing as there is no potential benefit in getting metricbeat plugin GA.

**Pull request closed without merging**
