### PR TITLE
add process filters system.process metricset

### PR DESCRIPTION
**Pull request by urso**

### CODE REVIEW

**Comment by andrewkroh** [comment]
LGTM. Somewhere (I'm not sure where) this configuration option will need to be documented (we have lots of docs to fix up).

**Comment by monicasarbu** [comment]
LGTM

**Comment by urso** [comment]
Yeah, didn't find the place config options are documented.

**Comment by ruflin** [comment]
The config needs to be updated in `metricbeat/module/system/_beat/config.yml`.

**Comment by ruflin** [comment]
@urso Not too happy about the naming, as a `process` config inside the `process` metricset is somehow confusing. What about:

* selector
* process_filter

This brings up the general discussion again if we should replace everything by filters or have sometimes more efficient "methods". I initially had "selectors" in each configuration block that allowed to define which top level doc entries should be shipped (white listing). We removed this in favor of filtering. The pro is to have one unified experience and setup, the con is that it is sometimes less efficient and more complex to configure.

**Comment by urso** [comment]
@ruflin this is how my config looks like:

```
metricbeat.modules:
- module: system
  metricsets: ["cpu", "memory", "process"]
  enabled: true
  period: 1s
  processes: [ ... ]
```

Due to config being on module level naming it processes sounds quite reasonable to me. I don't see any stuttering.

**Comment by ruflin** [comment]
@urso Ok, lets go with "processes".

**Pull request merged**
