### PR TITLE
Docs: corrected gpg signing key for newer rhel systems

### PR DESCRIPTION
**Pull request by rwxd**
## Proposed commit message

On newer RHEL systems SHA1 keys are no longer supported: https://www.redhat.com/en/blog/rhel-security-sha-1-package-signatures-distrusted-rhel-9

related issue: elastic/elasticsearch#85876

Solution: [elastic/elasticsearch#85876 (comment)](https://github.com/elastic/elasticsearch/issues/85876#issuecomment-1733018142)

## Logs

[root@ap01 ~]# sudo rpm --import https://packages.elastic.co/GPG-KEY-elasticsearch
warning: Signature not supported. Hash algorithm SHA1 not available.
error: https://packages.elastic.co/GPG-KEY-elasticsearch: key 1 import failed.

### CODE REVIEW

**Review by cmacknz — APPROVED** [review]
Thanks!

**Comment by cmacknz** [comment]
You will need to sign the CLA before this can be merged.

**Comment by rwxd** [comment]
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [58ae66a](https://github.com/elastic/beats/commit/58ae66a6adf85c602e6a372600f1f3d0cdd871ce)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

I have tried to sign the Contributor Agreement for more than 5 times. But it doesn't seem to work.

**Comment by pierrehilbert** [comment]
It seems to be good now.

**Comment by cmacknz** [comment]
buildkite test it

**Comment by cmacknz** [comment]
run docs-build

**Pull request merged**
