### PR TITLE
[Heartbeat] Use prctl to ensure subprocesses are cleaned up on exit

### PR DESCRIPTION
**Pull request by andrewvc**
Fixes https://github.com/elastic/beats/issues/32363 by instructing the linux kernel to automatically kill node subprocesses if their parents die. In testing it appears chromium always dies as well, although I'm not entirely sure why. Either chrome sets the right flags itself, or the death signal propagates. Either way, in testing this works very solidly.

We don't have sufficient automated test infrastructure to write a good automated test here, so this will have to reply on manual testing.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

Run the below heartbeat inline yaml, this journey will hang for a long time, giving you chrome / node processes that last for a long while. Once it is started, run `pkill heartbeat` which should kill heartbeat and all subprocesses. On the `main` branch heartbeat and chromium will die, and `node` will persiste.

```yaml
- type: browser
  enabled: true
  id: Inline mem 3
  name: Inline mem3
  source:
    inline:
      script:
        step("load homepage", async () => {
            await page.goto('https://www.elastic.co');
        });
        step("hover over products menu", async () => {
            await page.hover('css=[data-nav-item=products]');
        });
        step("failme", async () => {
           await (new Promise(done => {
             setTimeout(done, 100000);
           }));
           await page.hover('css=[data-nav-item=notathingonpage]');
        });
  schedule: "@every 1m"
```

### CODE REVIEW

**Review by emilioalvap — APPROVED** [review]
LGTM, tested E2E with Fleet integrations.

**Comment by lucasfcosta** [comment]
@andrewvc I've E2E tested this PR and it still didn't kill the Node processes (I'm using an x64 Mac btw)

I tested it by updating my monitor so that it would run for a long time:

```yaml
heartbeat.monitors:
- type: browser
  id: exits-monitor-3
  name: exits-monitor-3
  schedule: '@every 10s'
  source:
    inline:
      script: |-
        step("second", async () => {
          await page.waitForTimeout(100_000)
          await page.goto('https://www.google.com');
        });
        step("second", async () => {
          await page.goto('https://www.bbc.co.uk');
        });
```

Then, I verified I did have node processes spawned by Heartbeat, killed Heartbeat, and verified whether there were any node processes hanging (see image below).

Screenshot 2022-08-04 at 11 20 14

Did I do anything wrong with regards to testing or should I open an issue for this?

**Comment by andrewvc** [comment]
@lucasfcosta sorry if it was unclear, but this is expected! This relies on linux specific behavior, so it won't work on other platforms. It's fine, however, in that synthetics only really needs to work on linux since it requires a linux container.

The meat of the PR is in https://github.com/elastic/beats/blob/main/x-pack/heartbeat/monitors/browser/synthexec/synthexec_linux.go , note the `_linux` which go uses to selectively compile only for the matching platform. I wish there was a cross-platform way, but this is a linux-specific syscall. I'm sure we could work it out for OSX, but it's probably not worth the complexity given that no actual user will run it that way.

**Comment by andrewvc** [comment]
The easiest way to test this, I should add, would be to check out the synthetics demo repo, modify https://github.com/elastic/synthetics-demo/blob/main/heartbeat/run.sh to set `LATEST_RELEASE_TAG` to `8.4.0-SNAPSHOT`. Then, you can try attaching a console to the container and killing heartbeat processes. 

I __think__ that should work. I tested it myself on my own linux WSL box.

**Comment by lucasfcosta** [comment]
@andrewvc indeed that solved the problem!

Here's the script I used to run it:

```sh
#!/bin/bash -e
LATEST_RELEASE_TAG="8.4.0-SNAPSHOT"
DOCKER_IMAGE=docker.elastic.co/beats/heartbeat:$LATEST_RELEASE_TAG
echo "Using docker image $DOCKER_IMAGE"
docker run \
  -it \
  --entrypoint=/bin/bash \
  --rm \
  --name=heartbeat \
  --user=heartbeat \
  --net=elastic-package-stack_default \
  --volume="/tmp/hb1.yml:/usr/share/heartbeat/heartbeat.yml:ro" \
  $DOCKER_IMAGE
```

Once I ran that script, I started heartbeat with `./heartbeat -e` and ran the commands shown below to list the process tree, kill Heartbeat, and check the process tree again.

Screenshot 2022-08-08 at 10 59 53

**Pull request merged**
