### PR TITLE
[Heartbeat] Use service.name not service_name in configs

### PR DESCRIPTION
**Pull request by andrewvc**
Using the nesting this way lets us handle future fields like
`service.environment` more cleanly if/when they become available.

See https://github.com/elastic/ecs/blob/master/rfcs/text/0002-rfc-environment.md
for the proposal to add service.environment

This is a follow-up to #19932 which has not yet been released, so this is not a breaking change.

CC @cyrille-leclerc who pointed out that this would be better.

### CODE REVIEW

**Comment by ph** [comment]
@andrewvc I don't think this is linked to Fleet so i've removed the team label, I've looked at the PR I think there are some debugger traces that you left in that PR.

**Comment by cyrille-leclerc** [comment]
Hello @andrewvc, 
Context: I am working on the standardisation of `service.environment` ([ECS - rfc-environment.md](https://github.com/elastic/ecs/blob/master/rfcs/text/0002-rfc-environment.md) )

* Do you think this change can make the 7.10 release?
* Does it make sense to later extend the `service.*` namespace of monitor definitions adding an `environment` field with a syntax that could look like `service.environment`. Example:

```yaml
# EXPERIMENT - NOT SUPPORT CONFIGURATION
heartbeat.monitors:
- type: http
  id: www-frontend-monitor
  name: Website Frontend Monitor
  service:
    name: www-frontend
    environment: production
  urls: ["https://www.my-ecommerce-company.com/status"]
  schedule: '@every 10s'
  check.response.status: 200
  timeout: 2s
- type: http
  id: www-frontend-monitor-staging
  name: Website Frontend Monitor - Staging
  service:
    name: www-frontend
    environment: staging
  urls: ["https://www.staging.my-ecommerce-company.com/status"]
  schedule: '@every 10s'
  check.response.status: 200
  timeout: 5s
```

**Comment by andrewvc** [comment]
@cyrille-leclerc apologies, this fell through the cracks. It won't make 7.10.0 but it can make 7.10.1. I 100% agree we should also add an environment field (that would go in 7.11.0)

I've created a separate issue for the env stuff here: https://github.com/elastic/uptime/issues/272

**Comment by cyrille-leclerc** [comment]
Many thanks @andrewvc

**Comment by andrewvc** [comment]
I've updated this PR to handle both `service_name` and `service.name`. Only `service.name` will be documented however

**Review by blakerouse — APPROVED** [review]
Looks good, like the fallback to old setting.

**Comment by cyrille-leclerc** [comment]
Thanks @andrewvc

**Pull request merged**
