### PR TITLE
[Filebeat] A New TiDB Module

### PR DESCRIPTION
**Pull request by SabaPing**
Please refer to [meta PR #27663](https://github.com/elastic/beats/pull/27663) first.

## What does this PR do?

Add a new `tidb` module to collect and parse logs from TiDB clusters.

This module has 2 filesets. ["log", "slowlog"].

- [TiDB (the "log" fileset)](https://github.com/pingcap/tidb)
- [Slow log](https://docs.pingcap.com/tidb/stable/identify-slow-queries)

As to log parsing, it follows two specifications:
- Normal logs: https://github.com/tikv/rfcs/blob/master/text/0018-unified-log-format.md
- Slow logs: https://docs.pingcap.com/tidb/stable/identify-slow-queries

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Meta #27663

### CODE REVIEW

**Comment by SabaPing** [comment]
I've spun most of filesets off and only kept two of them, to make PR easier to review.

**Comment by sayden** [comment]
Thank you for this work! I'll download the branch and help you with the cli commands required for the CI to go green.

**Comment by SabaPing** [comment]
Hi @sayden , could I ask how is the review process going?

**Comment by SabaPing** [comment]
Hi all, can I ask if there are any new updates?
Thanks!

**Comment by SabaPing** [comment]
Hi @sayden , no update for a long time. Could I ask if there are any new updates?
Thanks!

**Comment by SabaPing** [comment]
Hi @sayden ,
Knock knock, any updates 😭?

**Comment by SabaPing** [comment]
Knock knock~

**Comment by jlind23** [comment]
Closing this for now as it is outdated, but feel free to reopen it if needed.

**Pull request closed without merging**
