### PR TITLE
fix: use Debian 10 for mips, ppc, and s390x

### PR DESCRIPTION
**Pull request by kuisathaverat**
## What does this PR do?

It updates the golang-crossbuild Docker images used to build beats to Debian 10 for some architectures.

## Why is it important?

We have dropped support for Debian <9 on the golang crossbuildDocker images for the architectures mips, PPC, and s390x

depends on https://github.com/elastic/golang-crossbuild/pull/175

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by kuisathaverat** [comment]
there are a bunch of lint errors related to the new go-lint action, none of them are related to my changes

```
run golangci-lint
  Running [/home/runner/golangci-lint-1.44.2-linux-amd64/golangci-lint run --out-format=github-actions --new-from-patch=/tmp/tmp-16[24](https://github.com/elastic/beats/runs/6081927161?check_suite_focus=true#step:6:24)-t9F1iFL552ac/pull.patch --new=false --new-from-rev= --timeout=[30](https://github.com/elastic/beats/runs/6081927161?check_suite_focus=true#step:6:30)m --whole-files] in [] ...
  Error: import of package `github.com/pkg/errors` is blocked because the module is in the blocked modules list. `errors` and `fmt` are recommended modules. This package is deprecated, use `fmt.Errorf` with `%!w(MISSING)` instead. (gomodguard)
  Error: `assembleDarwinUniversal` is unused (deadcode)
  Error: use of `fmt.Println` forbidden by pattern `fmt.Print.*` (forbidigo)
  Error: use of `fmt.Println` forbidden by pattern `fmt.Print.*` (forbidigo)
  Error: use of `fmt.Println` forbidden by pattern `fmt.Print.*` (forbidigo)
  Error: string `darwin-arm64-debian10` has 2 occurrences, make it a constant (goconst)
  Error: string `linux/arm64` has 2 occurrences, make it a constant (goconst)
  Error: string `arm` has 3 occurrences, make it a constant (goconst)
  Error: string `arm64` has 2 occurrences, make it a constant (goconst)
  Error: string `armel` has 2 occurrences, make it a constant (goconst)
  Error: use of `fmt.Printf` forbidden by pattern `fmt.Print.*` (forbidigo)
  Error: S1012: should use `time.Since` instead of `time.Now().Sub` (gosimple)
  
  Error: issues found
```

**Review by ph — APPROVED** [review]
Lets ignore the linter errors here.

**Comment by ph** [comment]
Elastic agent's PR at https://github.com/elastic/elastic-agent/pull/345

**Comment by ph** [comment]
Added 8.2 as a target.

**Pull request merged**
