### PR TITLE
[Heartbeat] Fix packaging

### PR DESCRIPTION
**Pull request by andrewkroh**
## What does this PR do?

There were a few issues with the package target for x-pack/heartbeat.

- Update root Makefile to build packages for x-pack/heartbeat.
- Update packaging CI job.
- Magefile fixes (mostly with where the packaging spec was looking for files).

## Why is it important?

This should allow builds and packaging from x-pack/heartbeat to work as expected.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

This was a fast fix so please try it out yourself and examine the package contents.

### CODE REVIEW

**Comment by andrewkroh** [comment]
The packaging build passed, but I forgot a Makefile in x-pack/heartbeat so lint failed. I pushed an update so I think it should be good now.

**Comment by andrewkroh** [comment]
Looks better now. In a follow up I will add x-pack/heartbeat to the Jenkinfile so that it built and tested along with everything else.

**Comment by jsoriano** [comment]
This PR will need to be backported to 7.x along with #20549 when #20488 is merged.

**Comment by andrewvc** [comment]
backport here https://github.com/elastic/beats/pull/20638

**Pull request merged**
