### PR TITLE
Fix Elasticsearch behind Kerberos environment

### LINKED ISSUE #21838: [build][libbeat][python test] elasticsearch_kerberos.elastic cannot be started
### How to reproduce

```bash
cd libbeat
mage build test
````

### Stacktrace

```bash
09:34:23  + mage build test
09:34:31  >> build: Building libbeat
09:35:18  >> go test: Unit Testing
...
09:39:17  Building elasticsearch_kerberos.elastic
09:39:29  Service 'elasticsearch_kerberos.elastic' failed to build: The command '/bin/sh -c /scripts/installkdc.sh && /scripts/addprincs.sh' returned a non-zero code: 127
09:39:29  >> Building docker images again
09:39:29  elasticsearch uses an image, skipping
09:39:29  elasticsearch_monitoring uses an image, skipping
09:39:29  elasticsearchssl uses an image, skipping
09:39:29  logstash uses an image, skipping
09:39:29  Building redis
09:39:29  Building sredis
09:39:29  Building kafka
09:39:30  Building elasticsearch_kerberos.elastic
09:39:32  Service 'elasticsearch_kerberos.elastic' failed to build: The command '/bin/sh -c /scripts/installkdc.sh && /scripts/addprincs.sh' returned a non-zero code: 127
09:39:32  Error: running "docker-compose -p libbeat_8_0_0_be5c2902cd-snapshot build --force-rm --pull" failed with exit code 1
```

See https://beats-ci.elastic.co/job/Beats/job/beats/job/master/572/execution/node/2566/log/

### Files

https://github.com/elastic/beats/blob/master/testing/environments/docker/elasticsearch_kerberos/Dockerfile

### PR DESCRIPTION
**Pull request by kvch**
## What does this PR do?

This PR addresses the changes introduced in https://github.com/elastic/beats/issues/21838

## Why is it important?

ES behind Kerberos could not be tested.

## Checklist

~~- [ ] My code follows the style guidelines of this project~~
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-~~developer.next.asciidoc`.~~

## Related issues

Closes #21838

### CODE REVIEW

**Comment by v1v** [comment]
It seems the build got stalled when preparing the docker environment:
- see [here](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-22191/1/pipeline/#step-2737-log-99) for about 1 hour and still on-going.

maybe it's worth another kick off?

**Comment by kvch** [comment]
jenkins run tests

**Comment by kvch** [comment]
jenkins run tests

**Comment by andresrc** [comment]
jenkins run tests

**Comment by v1v** [comment]
jenkins run tests

**Comment by jlind23** [comment]
Backlog grooming - Closing this until further update.

**Pull request closed without merging**
