### PR TITLE
Set include_type_name to true when loading template to ES 6.7

### PR DESCRIPTION
**Pull request by kvch**
I haven't seen any deprecation warnings in the logs of ES when testing with ES 6.7.

### CODE REVIEW

**Comment by kvch** [comment]
Needs backport to 7.0 and 6.7

**Comment by kvch** [comment]
Failing test is unrelated.

**Comment by urso** [comment]
@jpountz @jtibshirani Can you confirm this is really what we want to do?

Beats do not have default json templates, but field definitions. The actual template is generated if needed. We have logic to generate templates that are compatible with ES <5.x, 6.x and 7.x.
When there is need to install a template, we first check the Elasticsearch version in use.
If the ES major version is 7, a typeless template is generated. If the ES major version is <7, we create a typed template. This means that a template is compatible to the ES version in use, and fully respects the default value of `include_type_name` (true in ES 6.7, false in ES 7.0).
Before this PR, we did just install the template without setting the HTTP parameter `include_type_name` at all. Actually we used to set `include_type_name`, but removed it, as we've been told that the presence of this parameter will trigger a deprecation warning, no matter what.
Now we've been told that we must set `include_type_name=true` when talking to ES 6.7, so to not trigger a deprecation warning.

(false== send parameter with value `false`, true == send parameter with value `true`, no == do not set parameter).

Before PR:
Beats6.7 -> ES 6.7: no
Beats7.0 -> ES 6.7: no
Beats6.7 -> ES 7.0: no
Beats7.0 -> ES 7.0: no

With merging this PR we will change behavior to:

Before PR:
Beats6.7 -> ES 6.7: true
Beats7.0 -> ES 6.7: true
Beats6.7 -> ES 7.0: no
Beats7.0 -> ES 7.0: no

Is this correct?

**Comment by jpountz** [comment]
> as we've been told that the presence of this parameter will trigger a deprecation warning, no matter what.

To clarify, _not_ using this parameter in 6.7 triggers a deprecation warning because we want to warn users that the create index, put/get mappings APIs change in 7.x. And then using it in 7.x triggers a deprecation warning because we want to warn users that this parameter will get removed in 8.0.

This change looks good to me. :+1:

**Comment by urso** [comment]
@jpountz Thank you

**Comment by jtibshirani** [comment]
This change looks good to me as well. Thanks to the beats team for the patience + multiple iterations on this.

**Pull request merged**
