### PR TITLE
Fix docker metrics discovery by converting port to int64

### PR DESCRIPTION
**Pull request by vjsamuel**
The metrics builder requires port number for being able to spin up metricbeat modules that poll. Kubernetes uses port as int64 and docker uses uint16 for the same. There needs to be a consistent notation of ports for us to be able to use them in the metrics builder.

### CODE REVIEW

**Comment by exekias** [comment]
I think it will be better to cast in the side reading this value, something similar to https://github.com/elastic/beats/blob/master/libbeat/processors/add_docker_metadata/add_docker_metadata.go#L248

That should avoid this error in future providers

**Comment by vjsamuel** [comment]
does it make sense to extract this method into a common location? Its being used in multiple places.

**Comment by exekias** [comment]
I would be ok with that, what do you think @andrewkroh?

**Comment by andrewkroh** [comment]
I'm good with moving [`tryToInt`](https://github.com/elastic/beats/blob/972fb3b6ec3dd0cf2dc60a7454900822682b593a/libbeat/processors/add_docker_metadata/add_docker_metadata.go#L248:6) to a location that supports reuse.

Without a description or a link to a bug report I'm having trouble understanding what this pull request fixes or what the root cause of the problem is. Can you please add more information to the description.

**Comment by vjsamuel** [comment]
@andrewkroh updated description. apologies for the lack of clarity. what would be a suitable place to place this method?

**Comment by andrewkroh** [comment]
> what would be a suitable place to place this method?

Thanks for adding the description. In common is good. I'm thinking instead of `int.go` it could be `coerce.go` because we also have a function named `tryToMapStr` that could be moved there in the future. It has been duplicated a few times.

**Comment by vjsamuel** [comment]
@andrewkroh @exekias i have done the renaming.

**Comment by andrewkroh** [comment]
jenkins, test it

**Comment by exekias** [comment]
I think there is no need for changelog, this was affecting unreleased code only

**Pull request merged**
