### PR TITLE
[Ingest Manager] Prevent uninstall failures on empty config

### PR DESCRIPTION
**Pull request by michalpristas**
## What does this PR do?

This PR checks upfront for inputs and outputs definition in a config. 
Program func which is called from uninstall fails on missing output which causes uninstall to fail. 

Also if no programs are there to be uninstalled we dont even instatiate uninstaller as a micro perf optimization 

## Why is it important?

Unistall working

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by ruflin** [comment]
What is the best way to add tests for these changes?

**Comment by michalpristas** [comment]
@ruflin  i would say e2e works great in this regards. this comes from e2e

**Review by blakerouse — APPROVED** [review]
Looks good.

**Review by mdelapenya — APPROVED** [review]

**Comment by mdelapenya** [comment]
@michalpristas e2e tests for 7.12.x is failing with same error. I think we should backport this change to 7.12 too.

**Pull request merged**
