### PR TITLE
Update version for the other members of the stack

### PR DESCRIPTION
**Pull request by tsg**

### CODE REVIEW

**Comment by ruflin** [comment]
I have a hard time to see how the Jenkins error is related to this change: 

```
make[1]: Entering directory `/home/jenkins/workspace/Beats-PR/src/github.com/elastic/beats/libbeat'
go vet ./...
outputs/logstash/transport.go:93: assignment copies lock value to c.tls: crypto/tls.Config contains sync.Once contains sync.Mutex
exit status 1
```

I also checked the 1.2 branch with `make check` and all looks good?!?

**Comment by tsg** [comment]
@andrewkroh  Do we run go 1.6 on Jenkins? That could explain the difference in `go vet`.

**Comment by tsg** [comment]
Strange, I actually get a different set of errors on `make check` on my computer:

```
make -C libbeat check || exit 1; make -C packetbeat check || exit 1; make -C topbeat check || exit 1; make -C filebeat check || exit 1; make -C winlogbeat check || exit 1;
go vet ./...
publisher/output.go:55: github.com/elastic/beats/libbeat/outputs.Options composite literal uses unkeyed fields
publisher/output.go:89: github.com/elastic/beats/libbeat/outputs.Options composite literal uses unkeyed fields
exit status 1
make[1]: *** [check] Error 1
make: *** [check] Error 1
```

**Comment by tsg** [comment]
In any case, can we get this one merged? It's clearly not related. I'll open a separate PR to fix the go vet issue that I get on my computer.

**Comment by tsg** [comment]
Created https://github.com/elastic/beats/pull/1224 against master.

**Comment by ruflin** [comment]
I couldn't reproduce it locally and also travis does make check I think. Probably different versions ...

**Comment by andrewkroh** [comment]
@tsg Yes, all of our Jenkins jobs have been updated to use Go 1.6. And I am going to update AppVeyor and TravisCI to Go 1.6 very soon.

**Comment by andrewkroh** [comment]
I'm adding `make check` to the `beats` job (master) in Jenkins. It was running only `make testsuite` where as the PR job was running both.

**Pull request merged**
