### PR TITLE
New FileBeat filesets for Cisco module

### PR DESCRIPTION
**Pull request by jhallqvist**
## What does this PR do?
Implements filesets for Cisco ACI, IOS-XR and WLC for the Cisco module.

## Why is it important?
Currently there are no filesets available to parse the above types of logs.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally
```bash
cd beats/x-pack/filebeat
GENERATE=true TESTING_FILEBEAT_MODULES=cisco mage -v pythonIntegTest
```

## Related issues

-

### CODE REVIEW

**Comment by jhallqvist** [comment]
> This pull request does not have a backport label. Could you fix it @jhallqvist? 🙏
> To fixup this pull request, you need to add the backport labels for the needed
> branches, such as:
> 
> * `backport-v./d./d./d` is the label to automatically backport to the `7./d` branch. `/d` is the digit
> 
> **NOTE**: `backport-skip` has been added to this pull request.

Which, as far as I can see, I cannot do since I seem to be lacking the required permissions to do so.

**Comment by jhallqvist** [comment]
Still relevant

**Comment by jlind23** [comment]
@elastic/security-external-integrations  what should we do with this PR?

**Comment by zez3** [comment]
I see(for WLC) it extracts only the mnemonic but does not parse the message further for Username, mac, IPs and other relevant data(reason, interface, ssid, AithSessionId,etc) which would help a lot the SIEM part of Elastic
Also I this this WLC parser is for the older generation of WLCs as the new one has a slight differen syslog format

**Comment by jhallqvist** [comment]
@zez3 - Quite correct. The WLC ingest was created for the older models of Cisco WLC and might be in need of a name change to reflect that. As for not parsing the message further then provided, the intention was that the community could add to it.
However since this pull request is almost a year old I must admit I consider this in a state of "take it or leave" it. I have done no active development or administration of Elastic Stack since about a month after this request was submitted and I do not have the time, nor the means, to develop this further presently.

**Comment by andrewkroh** [comment]
@jhallqvist Thanks for the contribution.

I think we can use this as the starting point for new Fleet integrations specifically for ACI, IOS-XR and WLC. When we create those we can use these pipelines and especially the sample logs.

**Pull request closed without merging**
