### PR TITLE
[Filebeat] Add Cloudflare R2 to provider list

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Now that Cloudflare R2 is out of closed beta, this adds their domain to the provider list to automatically detect and set the provider field.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have made corresponding change to the default configuration files
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by cmacknz** [comment]
The S3 input doesn't have a codeowner listed, and I see changes from both cloud monitoring and SEI in the history. Requesting review from those teams, and we should clarify who the codeowner for this module should be if we can.

**Comment by legoguy1000** [comment]
Can this be merged?

**Comment by cmacknz** [comment]
Can someone from @elastic/obs-cloud-monitoring approve if they want to support this?

**Review by kaiyan-sheng — APPROVED** [review]
LGTM

**Pull request merged**
