### PR TITLE
Change path for the Elastic agent on darwin to install in /usr/bin/ the

### PR DESCRIPTION
**Pull request by ph**
wrapper.

Previously the install subcommand was installing the elastic agent on
the /usr/local/bin. This path doesn't exist in a default macOS installation
and this path is not added to the $PATH by default.

This PR changes the behavior on darwin to install the elastic agent
wrapper into the /usr/bin directly.

Filebeat debian install their wrapper in /usr/bin/filebeat.

```
winterfell/tmp/o/l(:|✔) % tree
.
└── usr
    └── bin
        └── filebeat

2 directories, 1 file

```

Fixes: #22037

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

Install on fresh macOS vm, the install subcommand should succeed and run `elastic-agent` in a terminal should run.

## Related issues

-

### CODE REVIEW

**Comment by ph** [comment]
fyi @EricDavisX

**Comment by ph** [comment]
@ferullo that path exists by default on the os version you have tested? https://github.com/elastic/beats/issues/22037

**Comment by ferullo** [comment]
Yes, I checked my vanilla install macOS 10.13, 10.14, 10.15, and 11.0 VMs. `/usr/bin` is there on all versions.

Oddly, `/usr/local/bin/` is in `$PATH` but it isn't created after a default macOS install.

image

**Review by michalpristas — APPROVED** [review]
sounds reasonable, lgtm

**Comment by ph** [comment]
@blakerouse you are fine with this change?

**Comment by ph** [comment]
After discussing with @blakerouse this cannot work correctly because of SIP, it will prevent installing stuff in that directory.
I did the mistake of not testing it on macOS and would assume it just a normal path.

```
blake@Blakes-MacBook-Pro beats % sudo echo "/bin/bash" > /usr/bin/test
zsh: operation not permitted: /usr/bin/test
```

**Pull request closed without merging**
