### PR TITLE
Cherry-pick pull #11105 to 7.x

### PR DESCRIPTION
**Pull request by alakahakai**
Cherry-pick pull #11105 to 7.x:
 * Add on_failure handler for Zeek ingest pipelines.
 * Fix one field name error for notice and add an additional test case.

### CODE REVIEW

**Comment by alakahakai** [comment]
jenkins, test this

**Comment by kaiyan-sheng** [comment]
https://github.com/elastic/beats/pull/11130#issuecomment-470575655 maybe this is not needed as well.

**Comment by alakahakai** [comment]
> [#11130 (comment)](https://github.com/elastic/beats/pull/11130#issuecomment-470575655) maybe this is not needed as well.

That would be great. Thanks for the heads up.

**Comment by alakahakai** [comment]
batched merged

**Pull request closed without merging**
