### PR TITLE
Cherry-pick #23592 to 7.x: Add support for ARM64 Docker images for all Beats

### PR DESCRIPTION
**Pull request by kvch**
Cherry-pick of PR #23592 to 7.x branch. Original message: 

This PR adds support for building ARM64 Docker images for all Beats on ARM64 machines.

To limit what packages should be built I have added the new environment variable named `PACKAGES`. It expects a comma-separated list of packages types. Available options: rpm, deb, tgz, dmg, docker, zip. If nothing is specified all available package types are built for the given platform.

This PR relies on the newly added crossbuild image with the suffix `base-arm-debian9`. This image is automatically selected if the runtime of the builder machine is ARM64.

A possible enhancement to this solution is described in #23775.

### CODE REVIEW

**Review by michalpristas — APPROVED** [review]
backport looks ok

**Review by v1v — APPROVED** [review]

**Comment by kvch** [comment]
jenkins run tests

**Comment by kvch** [comment]
jenkins run tests

**Comment by kvch** [comment]
Tests have passed, so I am disabling CI to make sure packaging runs immediately.

**Comment by kvch** [comment]
All packaging jobs are passing.

**Pull request merged**
