### PR TITLE
Remove vendor directory from metricbeat

### PR DESCRIPTION
**Pull request by jsoriano**
Metricbeat has a vendor directory that contains dependencies also
included in the main vendor directory. Remove the directory from
Metricbeat to avoid inconsistencies or conflicts, specially with x-pack
Metricbeat.

### CODE REVIEW

**Comment by fearful-symmetry** [comment]
That is one huge diff.

**Comment by jsoriano** [comment]
> That is one huge diff.

It only removes files :slightly_smiling_face:

**Comment by jsoriano** [comment]
Issue in Jenkins is not related (https://github.com/elastic/beats/pull/14560), but I will wait to have a full metricbeat build running before merging this.

**Comment by jsoriano** [comment]
Issues in CI are not related to metricbeat, merging and backporting this.

**Pull request merged**
