### PR TITLE
add_cloud_metadata asynchronous initialization

### PR DESCRIPTION
**Pull request by adriansr**
Now that the add_cloud_metadata is enabled by default in all beats, we are losing 3 precious seconds every time a Beat is started outside a supported cloud environment.

This patch makes the cloud detection an asynchronous task so the Beat can start and only block if initialization is not completed at the time of the first enrichment.

Running in debug mode bypasses this parallelism as the processor needs to be initialized when its String() method is called.

### CODE REVIEW

**Comment by adriansr** [comment]
In my case it sits waiting on an ARP response for 169.254.169.254, which is used by most cloud providers as metadata service. Maybe a misconfiguration on my network?

**Comment by andrewkroh** [comment]
I'm not sure. But I see that the Tencent provider requires a DNS lookup so at any point it could be one of several causes so I think this is a great addition.

**Comment by adriansr** [comment]
jenkins, test this

**Comment by exekias** [comment]
Any plans to backport this? :pray:

**Comment by adriansr** [comment]
@andrewkroh @exekias care to have a final look at my last update?

**Pull request merged**
