### PR TITLE
probot: update stale dates

### PR DESCRIPTION
**Pull request by v1v**
## What does this PR do?

Update when to update to stale any issues or PRs. 
Ignore whether they are assigned to any given project.

## Why is it important?

Tidy up

## Checklist

https://github.com/probot/stale

### CODE REVIEW

**Review by jlind23 — APPROVED** [review]
Like it!

**Review by ruflin — COMMENTED** [review]
LGTM. I didn't realise we have this already in the repo and just need to adjust it. This means any future change to the days or messaging we can do directly ourselfs.

@jlind23 Lets work on the messaging. I think there we can do a lot to prevent "confusion" in the community.

**Comment by v1v** [comment]
Do you want me to merge this PR? or should I close it then you can discuss further before putting the action in place?

**Review by ruflin — COMMENTED** [review]
I wonder what happens after merging. I expect a lot of PRs and issue will be marked as stale and closed. @jlind23 I wonder if we should do first some manual triaging?

**Comment by jlind23** [comment]
@ruflin They will first be mark as stalled and only 30 days after they will be closed.
As soon as they are staled then we will triage them.

**Review by ruflin — APPROVED** [review]
Lets get it in then.

**Comment by jlind23** [comment]
@v1v do you know when it will be run?

**Pull request merged**
