### PR TITLE
Cherry-pick to 7.0: Change add_cloud_metadata to not overwrite cloud field (#11612)

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
* Change add_cloud_metadata to not overwrite cloud field
* Add overwrite flag for add_cloud_metadata
* Add test for cloud.provider: ec2

(cherry picked from commit 17edc90642d1f069525e7e91e36c0211143c38b4)

### CODE REVIEW

**Comment by exekias** [comment]
It seems this is broken, maybe there is a missing backport?

**Comment by exekias** [comment]
Please don't merge until 7.0 has been released :+1:

**Comment by kaiyan-sheng** [comment]
> It seems this is broken, maybe there is a missing backport?

Yeah I'm seeing this error other place too. I will look into it today.

**Comment by kaiyan-sheng** [comment]
> It seems this is broken, maybe there is a missing backport?

@exekias That was my bad, my mistake on resolving conflict. Now it's fixed.

**Pull request merged**
