### PR TITLE
Fix instance name in perfmon metricset

### PR DESCRIPTION
**Pull request by narph**
## What does this PR do?

Fix instance name in perfmon metricset by adding an additional check in `iswildcard` function if path contains `*`

## Why is it important?

Fixes instance name in perfmon metricset

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes https://github.com/elastic/beats/issues/22218

### CODE REVIEW

**Review by ChrsMark — COMMENTED** [review]
lgtm. Would it worth adding a unit test for this functionality?

**Comment by narph** [comment]
> lgtm. Would it worth adding a unit test for this functionality?

the other tests should cover it but I just added one as well, doesn't hurt.

**Review by ChrsMark — APPROVED** [review]

**Pull request merged**
