### PR TITLE
Adding cborbeat to community beats

### PR DESCRIPTION
**Pull request by toravir**
Signed-off-by: Ravi Raju <toravir@yahoo.com>

- Enhancement

## What does this PR do?

Adds new custom beat to the community of beats.

## Why is it important?

So that people who need this can benefit from it

## Checklist

- [x] My code follows the style guidelines of this project
- [NA] I have commented my code, particularly in hard-to-understand areas
- [NA] I have made corresponding changes to the documentation
- [NA] I have made corresponding change to the default configuration files
- [NA] I have added tests that prove my fix is effective or that my feature works
- [NA] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [x] None

## How to test this PR locally

This is just a doc update. testing is not applicable - except to see if the doc uses the correct tags.

## Related issues

None

## Use cases

NA

## Screenshots
NA

## Logs

NA

### CODE REVIEW

**Comment by toravir** [comment]
Just signed the Contributor agreement using this email.

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by bmorelli25** [comment]
@elasticmachine test this please

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Pull request merged**
