### PR TITLE
Fix panic on docker healthcheck collection

### PR DESCRIPTION
**Pull request by jsoriano**
Fix panic on docker healthcheck collection on dockers without healthchecks.

### CODE REVIEW

**Comment by jsoriano** [comment]
Yes, I will backport this.

**Comment by jsoriano** [comment]
jenkins, test this again

**Comment by ruflin** [comment]
Don't forget the open a PR for the failing test ;-)

**Comment by jsoriano** [comment]
> Don't forget the open a PR for the failing test ;-)

First one was a connectivity issue, second one was a `SIGQUIT` :thinking:

**Pull request merged**
