### PR TITLE
Fix PANW bad mapping of client/source and server/dest packets and bytes

### LINKED ISSUE #18522: PANW module is incorrectly mapping client/source and server/destination bytes and packets
For confirmed bugs, please report:
- Version: all
- Operating System: -
- Discuss Forum URL: https://discuss.elastic.co/t/panw-schema-bugs-in-bytes-sent-received-and-packets-sent-received/208090
- Steps to Reproduce:  -

Quoting from the discuss post:
> There are some inconsistencies in the way the bytes sent/received and packets sent/received are being mapped in the panw module for filebeat. According to ECS the traditional "bytes_sent" would be mapped to "client.bytes" and/or "source.bytes", and "bytes_received" would be mapped to "server.bytes" and/or "destination.bytes". "packets_sent" would be mapped to "client.packets" and/or "source.packets", and "packets_received" would be mapped to "server.packets" and/or "destination.packets". This is not how panw has been implemented.

PANW pipeline is mapping:

`Bytes sent` to client/destination bytes.
`Bytes received` to server/source bytes.
`Packets sent` to server/destination packets.
`Packets received` to client/source packets.

All of these mappings are wrong.

### PR DESCRIPTION
**Pull request by adriansr**
PANW pipeline was mapping:

Bytes sent to client/destination bytes.
Bytes received to server/source bytes.
Packets sent to server/destination packets.
Packets received to client/source packets.

All of these mappings are wrong.

The correct is:
Bytes sent to client/source bytes.
Bytes received to server/destination bytes.
Packets sent to client/source packets.
Packets received to server/destination packets.

Also adding some missing ECS mappings in the process.

Fixes #18522

### CODE REVIEW

**Comment by adriansr** [comment]
Reviewed all the mappings just in case something else was off. Didn't find any other mapping error, but a few fields that can now be mapped to ECS. Can move that to a separate PR if we're not comfortable labeling those as a bug and backporting to a bugfix.

**Comment by andrewkroh** [comment]
FYI @willemdh. Please let us know if you see any issues in this change.

**Comment by willemdh** [comment]
@adriansr @andrewkroh Thanks for fixing this finally. One more issue in the panw module ingest pipeline:

event.end seems to be calculated in the ingest pipeline:

```
      {
        "script" : {
          "if" : "ctx?.event?.duration != null",
          "params" : {
            "NANOS_IN_A_SECOND" : 1000000000
          },
          "source" : """long nanos = ctx['event']['duration'] * params.NANOS_IN_A_SECOND; ctx['event']['duration'] = nanos; def start = ctx.event?.start; if (start != null) {
   ctx.event['end'] = ZonedDateTime.parse(start).plusNanos(nanos);
}
""",
          "lang" : "painless"
        }
      },
```

/usr/share/filebeat/module/panw/panos/config/input.yml
```
        event.start: 35
        event.duration: 36
```

Can't post live events here, but these are the raw values of one of our logs:

Generated Time (mgmt plane): 2020/05/14 20:22:32
Generated Time (data plane): 2020/05/14 20:22:32
Start Time => 2020/05/14 20:22:11
Duration => 4

In Kibana:

event.start => May 14, 2020 @ 20:22:11.000
event.duration => 4,000,000,000
event.end => May 14, 2020 @ 20:22:15.000

`event.end` is actually already in the raw data field 2 (mgmt) or 7 (data), as the panw events are generated at the end of the session. 

The calculated event.end (May 14, 2020 @ 20:22:15.000) seems to be different from the actual session event end (2020/05/14 20:22:32)..., resulting in confusing differences....

Please verify this and fix this too.

Tx

**Comment by adriansr** [comment]
@willemdh I'm not sure I follow.

First, ECS recommends that `event.start + event.duration == event.end` (When both start and end are defined).

So our choices are either calculating event.end (current solution), or ignoring the provided duration.

To me, the generated times (data or mgmt) are not necessarily the same as `event.end`:
> event.end contains the date when the event ended or when the activity was last observed.

Those are more suited to `@timestamp`:
> This is the date/time extracted from the event, typically representing when the event was generated by the source.

Am I missing something? Maybe the PANW fields mean something different than what I understand?

**Comment by willemdh** [comment]
@adriansr Well our panw specialist pointed it out, I'll discuss it with him and let you know.

**Pull request merged**
