### PR TITLE
Kibana Dashboard for RabbitMQ module

### PR DESCRIPTION
**Pull request by amandahla**
I don't have much experience with RabbitMQ but I hope it helps.

### CODE REVIEW

**Comment by monicasarbu** [comment]
@amandahla Thank you for the dashboard. Can you please add a screenshot of the dashboard in the description of the PR? I would like to add it to our next blog post. Thanks in advance!

**Comment by amandahla** [comment]
Hi! I made a few changes and now it's like this (I have a small test environment) :

kibana-rabbitmq

**Comment by monicasarbu** [comment]
@amandahla Can you please rebase to master?

**Comment by amandahla** [comment]
Something went wrong in codecov/project :|

**Comment by monicasarbu** [comment]
Closing in favor of #4912

**Pull request closed without merging**
