### PR TITLE
Validate Source IP "LOCAL" or "Unknown" in Windows Security Logs

### LINKED ISSUE #19627: Winlogbeat Could not index event - "source.ip: 'LOCAL'" Not an IP String Literal
- Version: 7.8.0
- Operating System: Windows 10 v1909 Enterprise
- Discuss Forum URL: https://discuss.elastic.co/t/winlogbeat-could-not-index-event-to-elasticsearch-source-ip-local/239658
- Steps to Reproduce: Install Winlogbeat 7.8.0

I am seeing quite a lot of errors in Logstash for Winlogbeat events failing to index. The error indicates events are coming in with "source.ip: LOCAL" which is not a valid IP address. If for some reason the literal string for the IP address is being read as "LOCAL", the agent should convert this to "127.0.0.1" to prevent index failures. 

```
Jul 02 07:43:04 Logstash1 logstash[7790]: [2020-07-02T07:43:04,974][WARN ][logstash.outputs.elasticsearch][main][1b0d38a63ac70b958df647ae2a47badf4ac8161e6df5e7eb331817d2b52dfa28] Could not index event to Elasticsearch. {:status=>400, :action=>["index", {:_id=>nil, :_index=>"winlogbeat-7.8.0", :routing=>nil, :_type=>"_doc"}, #<LogStash::Event:0x5a7b7089>], :response=>{"index"=>{"_index"=>"winlogbeat-7.8.0-2020.07.02-000015", "_type"=>"_doc", "_id"=>"-nL7D3MB9q2MOx9CKDBo", "status"=>400, "error"=>{"type"=>"mapper_parsing_exception", "reason"=>"failed to parse field [source.ip] of type [ip] in document with id '-nL7D3MB9q2MOx9CKDBo'. Preview of field's value: 'LOCAL'", "caused_by"=>{"type"=>"illegal_argument_exception", "reason"=>"'LOCAL' is not an IP string literal."}}}}}
```

### PR DESCRIPTION
**Pull request by MakoWish**
## What does this PR do?

Some security events contain a source IP address of "LOCAL" or "Unknown" which are not valid IP addresses. This PR will correct the processing of events containing one of those values. 

## Why is it important?

This bug causes mapping exceptions and prevents these events from being ingested. 

## Checklist

- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

-fixes #19627

### CODE REVIEW

**Review by efd6 — COMMENTED** [review]
Thanks.

Are you able to provide events to exercise this in tests?

**Comment by MakoWish** [comment]
I unfortunately cannot provide EVTX files for this one, as the only record of this happening so far is from servers, and I do not have access to log into those servers. Since I have already made the changes to our Ingest Pipeline, I could provide the JSON of some of these documents in Elasticsearch for these events.

**Comment by MakoWish** [comment]
Scratch that. I was able to find a client with some of these. As with the other PR, these events do contain sensitive information. Please let me know how/where I can send them to you, and I will do that.

**Comment by MakoWish** [comment]
Attaching five scrubbed events of each where the source IP is either "LOCAL" or "Unknown". 
[source_ip_invalid.zip](https://github.com/elastic/beats/files/10440205/source_ip_invalid.zip)

**Comment by MakoWish** [comment]
Can we back-port this?

**Comment by efd6** [comment]
I've added the tests temporarily in the collection testdata. I want to flesh this out with a way to just drop XML files into inputs, but this is a bigger change, so I will do that separately.

**Review by efd6 — APPROVED** [review]
Thanks

**Pull request merged**
