### PR TITLE
fix float32 normalizeValue panic

### LINKED ISSUE #6128: Libbeat panic when float32 value returned in metricset
- Version: 
libbeat 7.0.0-alpha1 [72de9eddd42a7c688693b54c587778653d5ffecd]

- Operating System: 
Linux

- Steps to Reproduce: 
```
func (m *MetricSet) Fetch() (common.MapStr, error) {
  return common.MapStr{
    "value": float32(1),
  }, nil
}
```

Whats happening:
```
panic: interface conversion: interface {} is float32, not float64

goroutine 38 [running]:
github.com/elastic/beats/libbeat/common.normalizeValue(0x26aa620, 0x3ada1a0, 0xc42025fc10, 0x3, 0xa, 0x253f9f0, 0x25353d2, 0x26e0ae0, 0x25340d3, 0x2790a40)
	/home/ixtiyor/projects/golang/src/github.com/elastic/beats/libbeat/common/event.go:156 +0x2125
github.com/elastic/beats/libbeat/common.normalizeMap(0xc420298c00, 0xc42025fc10, 0x2, 0xa, 0x0, 0x0, 0x0, 0x0)
	/home/ixtiyor/projects/golang/src/github.com/elastic/beats/libbeat/common/event.go:47 +0x1c0
github.com/elastic/beats/libbeat/common.normalizeValue(0x29d5300, 0xc420298c00, 0xc42025fc10, 0x2, 0xa, 0x26c2ae0, 0xc420152e60, 0x0, 0x0, 0x0)
	/home/ixtiyor/projects/golang/src/github.com/elastic/beats/libbeat/common/event.go:162 +0x148c
github.com/elastic/beats/libbeat/common.normalizeMap(0xc420299020, 0xc42025fc10, 0x1, 0xa, 0x0, 0x0, 0x0, 0x0)
	/home/ixtiyor/projects/golang/src/github.com/elastic/beats/libbeat/common/event.go:47 +0x1c0
github.com/elastic/beats/libbeat/common.normalizeValue(0x29d5300, 0xc420299020, 0xc42025fc10, 0x1, 0xa, 0x29d5300, 0xc420299200, 0x0, 0x0, 0x0)
	/home/ixtiyor/projects/golang/src/github.com/elastic/beats/libbeat/common/event.go:162 +0x148c
github.com/elastic/beats/libbeat/common.normalizeMap(0xc420298f90, 0xc42025fc10, 0x0, 0xa, 0x0, 0x0, 0x0, 0x0)
	/home/ixtiyor/projects/golang/src/github.com/elastic/beats/libbeat/common/event.go:47 +0x1c0
```

### PR DESCRIPTION
**Pull request by iahmedov**
Closes #6128

### CODE REVIEW

**Comment by ruflin** [comment]
@iahmedov Thanks for the fix. Could you add a CHANGELOG entry?

@urso Could you have a quick look at this?

**Comment by ruflin** [comment]
jenkins, test it

**Comment by urso** [comment]
Nice. One. As changelogs are consumer by users, not developers let's rephrase the changelog to `fix panic when Events containing a float32 value are normalized.`

**Comment by ruflin** [comment]
jenkins, test it

**Comment by ruflin** [comment]
@iahmedov Thanks a lot for the fix.

**Pull request merged**
