### PR TITLE
[Metricbeat][elasticsearch] Use replica number in doc ID for shard metricset

### PR DESCRIPTION
**Pull request by miltonhultgren**
### Summary

In the `shard` metricset, we want to report one document per shard allocation status. If you have an index with 3 shards (primaries) and 3 replicas (per primary, 9 total) you should have 12 documents that describe if the shards are assigned or not. 

To achieve this we query the routing_table of the cluster state at `/_cluster/state/version,nodes,master_node,routing_table` and loop over each index, where each shard is an array of the primary and all the replicas for that primary:
```
[
 [primary, replica 1, replica 2, replica 3],
 [primary, replica 1, replica 2, replica 3],
 [primary, replica 1, replica 2, replica 3]
]
```

We create a custom document ID for each shard allocation with the function `generateHashForEvent` but in `main` this function doesn't account for the "id" of the replica so it only reports the first replica (ignoring the other 2 in this example). 

This PR adds the array iterator to the ID if it's a replica, making sure that we generate a document for each replica of the shard.

### How to test
Get the changes: `git fetch git@github.com:miltonhultgren/beats.git sm-shard-allocations:sm-shard-allocations && git switch sm-shard-allocations`

Start Elasticsearch, create an index like this:
```
PUT /some-index
{
  "settings": {
    "index": {
      "number_of_shards": 3,  
      "number_of_replicas": 3
    }
  }
}
```

Run Metricbeat with `xpack.enabled: true`. 

Run the following query to verify that you get 12 documents back, 3 for the assigned primaries and 9 for the unassigned replicas:
```
GET .monitoring-*/_search
{
  "size": 20,
  "_source": [
    "_id"
  ],
  "query": {
    "bool": {
      "filter": [
        {
          "bool": {
            "should": [
              {
                "term": {
                  "metricset.name": "shard"
                }
              }
            ]
          }
        },
        {
          "bool": {
            "should": [
              {
                "term": {
                  "elasticsearch.index.name": "some-index"
                }
              }
            ]
          }
        }
      ]
    }
  }
}
```

Such as:
```
    [
      {
        "_index": ".monitoring-es-8-2022.10.27",
        "_id": "TyApCSpKTZWwFWCqjmTxRg:YehnOz5cS2StYQ5C8ssG1Q:some-index:s0:p",
        "_score": 0,
        "_source": {}
      },
      {
        "_index": ".monitoring-es-8-2022.10.27",
        "_id": "TyApCSpKTZWwFWCqjmTxRg:_na:some-index:s0:r1",
        "_score": 0,
        "_source": {}
      },
      {
        "_index": ".monitoring-es-8-2022.10.27",
        "_id": "TyApCSpKTZWwFWCqjmTxRg:_na:some-index:s0:r2",
        "_score": 0,
        "_source": {}
      },
      {
        "_index": ".monitoring-es-8-2022.10.27",
        "_id": "TyApCSpKTZWwFWCqjmTxRg:_na:some-index:s0:r3",
        "_score": 0,
        "_source": {}
      },
      {
        "_index": ".monitoring-es-8-2022.10.27",
        "_id": "TyApCSpKTZWwFWCqjmTxRg:YehnOz5cS2StYQ5C8ssG1Q:some-index:s1:p",
        "_score": 0,
        "_source": {}
      },
      {
        "_index": ".monitoring-es-8-2022.10.27",
        "_id": "TyApCSpKTZWwFWCqjmTxRg:_na:some-index:s1:r1",
        "_score": 0,
        "_source": {}
      },
      {
        "_index": ".monitoring-es-8-2022.10.27",
        "_id": "TyApCSpKTZWwFWCqjmTxRg:_na:some-index:s1:r2",
        "_score": 0,
        "_source": {}
      },
      {
        "_index": ".monitoring-es-8-2022.10.27",
        "_id": "TyApCSpKTZWwFWCqjmTxRg:_na:some-index:s1:r3",
        "_score": 0,
        "_source": {}
      },
      {
        "_index": ".monitoring-es-8-2022.10.27",
        "_id": "TyApCSpKTZWwFWCqjmTxRg:YehnOz5cS2StYQ5C8ssG1Q:some-index:s2:p",
        "_score": 0,
        "_source": {}
      },
      {
        "_index": ".monitoring-es-8-2022.10.27",
        "_id": "TyApCSpKTZWwFWCqjmTxRg:_na:some-index:s2:r1",
        "_score": 0,
        "_source": {}
      },
      {
        "_index": ".monitoring-es-8-2022.10.27",
        "_id": "TyApCSpKTZWwFWCqjmTxRg:_na:some-index:s2:r2",
        "_score": 0,
        "_source": {}
      },
      {
        "_index": ".monitoring-es-8-2022.10.27",
        "_id": "TyApCSpKTZWwFWCqjmTxRg:_na:some-index:s2:r3",
        "_score": 0,
        "_source": {}
      }
    ]
```

### CODE REVIEW

**Review by crespocarlos — APPROVED** [review]
LGTM! I just don't understand why the CI has failed.

image

**Comment by miltonhultgren** [comment]
@crespocarlos It's a legit lint error, I was also confused but you can see the errors in the code diff (or at least I can), and it's because of rules added but they only do something like "lint-staged" so this is the first time this file is changed since then so I get to fix them yay

**Review by crespocarlos — APPROVED** [review]
LGTM! 🚀

**Pull request merged**
