### PR TITLE
Update cloud.google.com/go/pubsub and supporting libraries

### PR DESCRIPTION
**Pull request by andrewkroh**
## What does this PR do?

Moving from cloud.google.com/go/pubsub v1.3.1 to v1.17.1.

Updating via `go get cloud.google.com/go/pubsub`.

Relates #29352

## Why is it important?

Pull in bug fixes from third-party library.

## Checklist

- [x] My code follows the style guidelines of this project
~- [ ] I have commented my code, particularly in hard-to-understand areas~
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files~
~- [ ] I have added tests that prove my fix is effective or that my feature works~
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Relates #29352

### CODE REVIEW

**Review by efd6 — APPROVED** [review]

**Comment by andrewkroh** [comment]
I will backport this if I can confirm that it fixes the bug we are seeing in #29352.

**Comment by andrewkroh** [comment]
@Mergifyio backport 7.16

**Comment by andrewkroh** [comment]
@Mergifyio backport 8.0

**Comment by ruflin** [comment]
@Mergifyio backport 7.17

**Comment by ruflin** [comment]
@andrewkroh @efd6 This did go into 7.16 but not 7.17. I'm pretty sure it should also be in 7.17. Can you check that the following PR is merged if needed? https://github.com/elastic/beats/pull/29906

**Pull request merged**
