### PR TITLE
Improves audit pipeline

### PR DESCRIPTION
**Pull request by radoondas**
- unifies usage of 'space' grok pattern

### CODE REVIEW

**Comment by radoondas** [comment]
@andrewvc you are right. I missed that. Will fix in a minute. Thanks!

**Comment by radoondas** [comment]
@andrewvc I am not sure why the build fails. What else do I need to do? Thanks.

**Comment by jsoriano** [comment]
jenkins, test this again please

**Comment by jsoriano** [comment]
I guess failure was not related as it passed in travis, just in case I launched jenkins CI again.

@andrewvc could you take another look? Thanks!

**Pull request closed without merging**
