### PR TITLE
Extract version to separate package to prevent cyclic imports

### PR DESCRIPTION
**Pull request by ruflin**
This PR is to reduce the number of changes in https://github.com/elastic/beats/pull/3681 .

### CODE REVIEW

**Comment by tsg** [comment]
jenkins, package it

**Comment by ruflin** [comment]
Seems packaging worked: http://build-eu-00.elastic.co/view/Beats/job/beats-package-PR/82/ But need to push a new version as it conflicts with an other PR which was merged.

**Comment by ruflin** [comment]
jenkins, package it

**Comment by ruflin** [comment]
Packaging also went green: http://build-eu-00.elastic.co/view/Beats/job/beats-package-PR/83/

**Comment by andrewkroh** [comment]
@ruflin `python dev-tools/get_version` is broken.

**Comment by ruflin** [comment]
@andrewkroh opened https://github.com/elastic/beats/pull/3727 to fix it and assigned you as reviewer ;-)

**Pull request merged**
