### PR TITLE
[proposed Enhancement] Update monitoring-metricbeat.asciidoc

### PR DESCRIPTION
**Pull request by nagor**
## What does this PR do?

Minor fix in the configuration of Beats for monitoring.

## Why is it important?

The lack of cluster configuration is a bit misleading.

### CODE REVIEW

**Comment by nagor** [comment]
Signed contributor agreement

**Comment by bmorelli25** [comment]
Thanks, @nagor!

@elasticmachine, run elasticsearch-ci/docs

**Comment by bmorelli25** [comment]
rerun the tests

**Comment by bmorelli25** [comment]
jenkins rerun the tests please

**Review by dedemorton — APPROVED** [review]
Looks good to me! My apologies for the review delay. This got lost in my Inbox.

Thanks for your contribution!

**Comment by dedemorton** [comment]
Note that I will backport this PR to relevant branches after it's merged.

**Comment by chrisronline** [comment]
cc @sayden @ycombinator @andresrc

**Review by sayden — APPROVED** [review]

**Pull request merged**
