### PR TITLE
[Agent] Incorporate new ACK endpoint

### PR DESCRIPTION
**Pull request by michalpristas**
Used separate endpoint for ACKing actions. 

Requires: https://github.com/elastic/kibana/pull/54401
Requires: #15413

Fixes: #15414 

Draft until mentioned PRs are not in

### CODE REVIEW

**Comment by nchaulet** [comment]
@michalpristas the kibana PR has been merged

**Comment by michalpristas** [comment]
thanks @nchaulet

**Comment by michalpristas** [comment]
@ph this is ready for review, all prerequisites are in

**Comment by michalpristas** [comment]
Tested with latest kibana
Acking seems to work.
- ACK request does not fail
- Next checkin is without any action unless changed.

One thing i noticed thought that ACKs are not listed in agent `View` view. Is this expected @nchaulet ? Or am I missing something?

**Comment by nchaulet** [comment]
@michalpristas Yes this is expected for now

**Pull request merged**
