### PR TITLE
x-pack/elastic-agent/pkg/agent/transpiler: fix file name

### LINKED ISSUE #26200: [Elastic-Agent] Can't go get module
Here is the output when get this module use `go get`.
```bash
➜  ~ go get -u github.com/elastic/beats/v7
go: extracting github.com/elastic/beats/v7 v7.13.1
-> unzip /PATH/go/pkg/mod/cache/download/github.com/elastic/beats/v7/@v/v7.13.1.zip: malformed file path "x-pack/elastic-agent/pkg/agent/transpiler/utils..go": double dot
go get github.com/elastic/beats/v7: unzip /PATH/go/pkg/mod/cache/download/github.com/elastic/beats/v7/@v/v7.13.1.zip: malformed file path "x-pack/elastic-agent/pkg/agent/transpiler/utils..go": double dot
```

### PR DESCRIPTION
**Pull request by jonyhy96**
Signed-off-by: jonyhy96 <hy352144278@gmail.com>

## What does this PR do?

Fix #26200 

## Why is it important?

No one can go get this module if we don't fix this.

- Closes #26200

### CODE REVIEW

**Review by jsoriano — APPROVED** [review]
Hey @jonyhy96, good catch! Thanks for fixing it!

**Comment by jonyhy96** [comment]
@jsoriano Hi, sorry to disturb,i wonder when will this pr be merged?

**Comment by jsoriano** [comment]
@jonyhy96 thanks for the ping! It had fallen under my radar.

**Pull request merged**
