### PR TITLE
Cherry-pick enabled template loading by default

### PR DESCRIPTION
**Pull request by tsg**
This cherry picks the commit from #1135.

### CODE REVIEW

**Comment by tsg** [comment]
Looks like some of the newer tests need adjustments, looking into it.

**Comment by urso** [comment]
this PR assumes the template being available in run-path. Don't we need to update beats-packer too, in order to deal with different path's on different platforms?

**Comment by tsg** [comment]
@urso: that should be done here: https://github.com/elastic/beats/pull/1286/files#diff-141849ea38f520a55e33c98d82ffaf1cR36

**Comment by urso** [comment]
LGTM

**Comment by monicasarbu** [comment]
LGTM

**Comment by monicasarbu** [comment]
We decided to merge this one before the tests finish, so we can start building the new packages for 5.0.0-alpha1.

**Pull request merged**
