### PR TITLE
[Metricbeat] Decrease timeout time of compose.EnsureUp functions

### PR DESCRIPTION
**Pull request by sayden**
Refer [here](https://github.com/elastic/beats/issues/10876) for more info

### CODE REVIEW

**Comment by ruflin** [comment]
Why not change the default and overwrite the exceptions?

**Comment by sayden** [comment]
> Why not change the default and overwrite the exceptions?

After telling me this, I have realized that the `compose` package is actually ours (my bad, I thought it was the original one, I didn't checked imports). I'll change this in a commit and overwrite some exceptions like Kibana

**Comment by sayden** [comment]
Done. This was my initial idea, to detect which modules needed a higher timeout and why

**Comment by sayden** [comment]
jenkins, test this please
ES error again, https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/beat=metricbeat,label=linux-immutable/5818/console might be related with the timeout

**Comment by ruflin** [comment]
You didn't increase the timeout of Elasticsearch in this PR? Is that on purpose or is it already increased?

**Comment by sayden** [comment]
Actually I didn't increase it, I just left default time for all but Kibana and Logstash, but now that you mention it, I guess that ES need a slightly lower timeout than Kibana and Logstash to make those two work properly.

My idea was to keep triggering build in this branch before merging, just to check if the current timeouts were correct.

**Comment by sayden** [comment]
jenkins, test this please

**Comment by ruflin** [comment]
This should be rebased as soon as https://github.com/elastic/beats/pull/11230 is merged.

**Comment by sayden** [comment]
jenkins, test this please

**Comment by sayden** [comment]
jenkins, test this please

**Comment by sayden** [comment]
jenkins, test this please

**Comment by sayden** [comment]
@ruflin I think we are safe merging this. All tests are fine and the ones that have been failing were always unrelated to timeouts. WDYT?

**Comment by ruflin** [comment]
@sayden Overall SGTM. Would be great to get at least 1 full green build. Most PR's I approved recently were all green so I'm worried if this PR stays red, it might be related (can't see a reason at the moment that this should be true).

I think you should rebase on master again to get the "fixed" flaky tests in.

**Comment by sayden** [comment]
We are green @ruflin :smile: do you want to trigger jenkins once more?

**Comment by ruflin** [comment]
@sayden Let's get it in.

**Comment by sayden** [comment]
Thanks for the help @ruflin and @cachedout

**Pull request merged**
