### PR TITLE
Add note on docker container as a requirement for browser monitors

### PR DESCRIPTION
**Pull request by andrewvc**
We mention that you need the container in the synthetics guide, but not on this page, this is a bit cleaner.

### CODE REVIEW

**Review by EamonnTP — APPROVED** [review]
Looks good. Just one minor suggestion.

**Comment by dedemorton** [comment]
Is this PR intentionally based on 7.16?

**Comment by andrewvc** [comment]
@dedemorton nope! But I can just forward port it to 8.0. I made the mistake of trying to use the `edit` button on the docs site.

**Comment by dedemorton** [comment]
No worries! I've done that too. :-) Forward porting is fine, but I think that means you'll need to do it manually.

**Review by dedemorton — APPROVED** [review]

**Comment by andrewvc** [comment]
@Mergifyio backport master

**Comment by andrewvc** [comment]
@Mergifyio backport 8.0

**Comment by andrewvc** [comment]
@Mergifyio backport 7.17

**Pull request merged**
