### PR TITLE
[SM] Kibana mapping to remove extra fields

### PR DESCRIPTION
**Pull request by sayden**
Kibana Module: alpha version of the mappings rework.

### CODE REVIEW

**Comment by andresrc** [comment]
@sayden the changes include the 3 modules, is it intended or is it because of the change in base branch?

**Comment by andresrc** [comment]
should we merge this in the feature branch and test from there? @elastic/stack-monitoring

**Comment by chrisronline** [comment]
yea we should put all in the feature branch

**Comment by sayden** [comment]
Aaaand merging Kibana too.

**Pull request merged**
