### PR TITLE
Cherry-pick #18086 to 7.x: Fix metricbeat generator test to use mage test

### PR DESCRIPTION
**Pull request by blakerouse**
Cherry-pick of PR #18086 to 7.x branch. Original message: 

## What does this PR do?

Updates the generated custom metricbeat to use `mage test` instead of `make unit`.

## Why is it important?

So the generator tests pass.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

### CODE REVIEW

**Comment by andrewkroh** [comment]
I think there's a flaw with these tests. It looks like the test generates code from this PR's commit (as it should) but it always pulls in the generated Beat's vendor from "origin/master".

**Comment by blakerouse** [comment]
@andrewkroh Yes because of go mods the generated beat always uses `origin/master`. Maybe we should only run this test for master.

**Comment by andrewkroh** [comment]
It seems like we need a way to be able to test against the same code that's under test (populate the generated beat's vendor with commit under test). Otherwise you can never be confident that the merged changes are good. Even if we only test on master you'd still have this problem.

**Comment by blakerouse** [comment]
@andrewkroh being that issue still affects master, I am going to merge this so 7.x and master are the same in this regard.

**Pull request merged**
