### PR TITLE
Metricbeat dashboard for MSSQL transaction log metricset

### PR DESCRIPTION
**Pull request by sayden**
image

Just one thing is "missing". I think there's a bug in the PR of the transaction log because the backup time. It is recognized as `string` inside the index pattern while in the `fields.yml` file is a `date` https://github.com/elastic/beats/blob/master/x-pack/metricbeat/module/mssql/transaction_log/_meta/fields.yml#L45.

image

The value is correct, it's just that not backup have been done yet so the database returns its "zero value" but I think it will be nice that it has some formatting or something similar.

By the way, regarding the question about the _@ timestamp per 30 seconds` I did here https://github.com/elastic/beats/pull/10076#issuecomment-456007897 the answer was the visual builder. If you build the dashboard with the visual builder, it appears as _per 10 seconds_

### CODE REVIEW

**Comment by sayden** [comment]
@jsoriano Friendly reminder here :slightly_smiling_face:

**Comment by jsoriano** [comment]
> @jsoriano Friendly reminder here :slightly_smiling_face:

Oh sorry :slightly_frowning_face: 

It LGTM as is, only a couple of things in case you want to try.

If there are more useful things below, maybe it worths to make smaller graphs and put 3 on each row, so more info is shown in a view.

I see that 5 entries are shown in each graph, is it because there are only 5 entries or because it is showing only the top N in something?
It can be good to think ahead on how the dashboard will look like if there are lots of entries, you can for example decide if showing only the top N entries and/or order them by value, and you can also consider to add an option list controller to chose the elements to show.

**Comment by sayden** [comment]
No worries :smile: 

> I see that 5 entries are shown in each graph, is it because there are only 5 entries or because it is showing only the top N in something?

Very good point because, in fact, they are 5 by pure coincidence. I had 5 databases in the MSSQL instance but you can find many (I have even worked with one which had 450!). So the problem I see here is that a TopN doesn't necessarly solve the problem, as a user might want to look at the health of any database which is not in one of those 5.

Ideas, thoughts? I'm not super experienced with Kibana nor with Visual Builder but maybe it has something to deal with this scenario

> If there are more useful things below, maybe it worths to make smaller graphs and put 3 on each row, so more info is shown in a view.

When I did it like this it looked a bit narrow in my opinion because legend must be visible and it takes a lot of space. I checked placing legend in the botton but then you had 3 and 3 half small and narrow graphs on the screen, which is even worse than having 4 big graphs so I prefer to leave them like this in this case.

**Comment by jsoriano** [comment]
> No worries smile
> 
> > I see that 5 entries are shown in each graph, is it because there are only 5 entries or because it is showing only the top N in something?
> 
> Very good point because, in fact, they are 5 by pure coincidence. I had 5 databases in the MSSQL instance but you can find many (I have even worked with one which had 450!). So the problem I see here is that a TopN doesn't necessarly solve the problem, as a user might want to look at the health of any database which is not in one of those 5.
> 
> Ideas, thoughts? I'm not super experienced with Kibana nor with Visual Builder but maybe it has something to deal with this scenario
> 

For that was my last suggestion :slightly_smiling_face:  _you can also consider to add an option list controller to chose the elements to show._

> > If there are more useful things below, maybe it worths to make smaller graphs and put 3 on each row, so more info is shown in a view.
> 
> When I did it like this it looked a bit narrow in my opinion because legend must be visible and it takes a lot of space. I checked placing legend in the botton but then you had 3 and 3 half small and narrow graphs on the screen, which is even worse than having 4 big graphs so I prefer to leave them like this in this case.

:+1:

**Comment by sayden** [comment]
New version with the option list controller:

image

**Comment by sayden** [comment]
@jsoriano friendly reminder here. All good? :slightly_smiling_face:

**Comment by sayden** [comment]
Thanks @jsoriano We'll do a follow up

Error seems unrelated. Merging.

**Pull request merged**
