### PR TITLE
Cherry-pick #10592 to 6.x: Update and add missing descriptions to ETCD module

### PR DESCRIPTION
**Pull request by sayden**
Cherry-pick of PR #10592 to 6.x branch. Original message: 

Fixes https://github.com/elastic/beats/issues/10239 and adds some missing descriptions on:

* `leader.followers.counts.success`
* `leader.followers.counts.fail`
* `leader.leader`

### CODE REVIEW

**Comment by urso** [comment]
Please backport to 6.7 branch. 6.x will be removed.

**Comment by ruflin** [comment]
@sayden Could you try to adjust the branch this PR tragets? Github has now such a setting. I wonder if this works.

**Comment by urso** [comment]
I changed base to 6.7

**Comment by sayden** [comment]
jenkins, test this

**Comment by sayden** [comment]
jenkins, test this again, please

**Comment by sayden** [comment]
jenkins, test this again, please

**Comment by sayden** [comment]
Issue opened here https://github.com/elastic/beats/issues/10722

**Pull request merged**
