### PR TITLE
Implement basic testing for the kafka output module

### PR DESCRIPTION
**Pull request by Popsiclestick**
This PR is for https://github.com/elastic/beats/issues/10652

I've implemented the same TCP connection test found in the [elasticsearch output test](https://github.com/elastic/beats/blob/master/libbeat/outputs/elasticsearch/client.go#L632). This is a basic test. 

Example output below
```
:; go build && ./filebeat test output -c kafka-filebeat.yml
TLS... WARN Kafka output doesn't support TLS testing
Kafka: localhost:9092...
  parse host... OK
  dns lookup... OK
  addresses: ::1, 127.0.0.1
  dial up... OK
Kafka: 127.0.0.1:9092...
  parse host... OK
  dns lookup... OK
  addresses: 127.0.0.1
  dial up... OK
Kafka: 0.0.0.0:9092...
  parse host... OK
  dns lookup... OK
  addresses: 0.0.0.0
  dial up... OK
```
Note:
The test will function whether or not the kafka server requires TLS. I did look to implement the `transport.TestTLSDialer` as well. But the TLS config objects which are passed don't look to be standardized between outputs. Kafka morphs the original object to integrate with sarama. The kafka client only has access to `sarama.Config` which doesn't contain the original object to perform `tlscommon.LoadTLSConfig`. Though I am likely missing something.

I am happy to implement any recommendations.

### CODE REVIEW

**Comment by jsoriano** [comment]
@Popsiclestick this is looking good, thanks! Before merging this change you will have to sign the CLA.

To obtain the TLS configuration you may try to do the reverse operation of [`tlscommon.BuildModuleConfig`](https://github.com/elastic/beats/blob/d50168952396386673dc948dfb943da01c7852a1/libbeat/common/transport/tlscommon/tls_config.go#L70), with the TLS config stored in the sarama config object. But I am not sure if at this point all the information is available.

**Comment by jsoriano** [comment]
jenkins, test this

**Comment by Popsiclestick** [comment]
I signed it. Strange though, I had already signed the agreement last week. Not sure, but hopefully it works now.

**Comment by jsoriano** [comment]
@Popsiclestick sorry, it seems that there was some kind of problem with CLA checker, could you try to sign it again?

**Comment by Popsiclestick** [comment]
Signed again :)

**Comment by jsoriano** [comment]
@Popsiclestick right, it seems to be working now :tada:

Do you want to give another try to TLS config? If not I think this is ready to go, and TLS can be added later.

**Comment by Popsiclestick** [comment]
Wooh! @jsoriano

I think we should merge this in for now. If I get some more time in the future, I can look at trying to get TLS added later.

**Comment by jsoriano** [comment]
@Popsiclestick oh sorry, I almost forgot it! I think this change should have an entry in `CHANGELOG.next.asciidoc`, could you add it?

**Comment by Popsiclestick** [comment]
@jsoriano Everything look good now? 👍

**Comment by jsoriano** [comment]
jenkins, test this

**Comment by jsoriano** [comment]
@Popsiclestick looks good, thanks! I'll merge it when everything is green :slightly_smiling_face:

**Pull request merged**
