### PR TITLE
[Enhancement] Add RotateOnStartup feature flag for file output

### LINKED ISSUE #19150: Add rotateonstartup configuration for output.file
In our setup the apm server is running locally on the same host as the monitored application and is configured **output.file**. We do not want to loose recorded data because of the file rotation, only because the system is restarted several times in succession. 
Therefore we would appreciate the implementation of the feature **rotateonstartup** as it already exists for the logfiles (https://www.elastic.co/guide/en/apm/server/current/configuration-logging.html#_logging_files_rotateonstartup).
See also https://discuss.elastic.co/t/is-it-possible-to-disable-rotation-of-file-completely/235813 for the previous discussion.

### PR DESCRIPTION
**Pull request by gitck**
## What does this PR do?
File output can now be configured to disable file rotation on startup. This PR introduces the configuration option `rotate_on_startup` and configures the internally used FileRotator (rotator.go) accordingly.

## Why is it important?
To avoid file rotation on every startup.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist
- [ ] check whether the name of the added configuration option 'rotate_on_startup' conforms to guideline
- [ ] test that default behaviour has not changed, i.e. ouput file is rotated on every startup

## How to test this PR locally
Configure beat to file output. If configuration option `rotate_on_startup` is set to `false`, file may no longer be rotated on startup.

## Related issues
- Closes elastic/beats#19150

### CODE REVIEW

**Comment by gitck** [comment]
I already signed the CLA, but I have not yet received a confirmation.

**Comment by andrewkroh** [comment]
@gitck I think the issue is that the commits in the PR do not match the email address used to sign the CLA. You can see the email in the commits with https://patch-diff.githubusercontent.com/raw/elastic/beats/pull/19347.patch.

**Comment by fearful-symmetry** [comment]
Code looks good. We need to get the CLA figure out, and I think we need to rebuild the docs too.

**Comment by gitck** [comment]
@andrewkrow Thank you for the hint. I signed the CLA again with the matching email address. I hope this is working now, sorry for the inconvenience caused.

**Comment by andrewkroh** [comment]
jenkins, run tests

**Comment by gitck** [comment]
I am not sure how to proceed. Who is going to review this PR finally?

**Comment by fearful-symmetry** [comment]
@gitck Right now CI is still failing. Can you run `mage notice`, and `go mod tidy` ?

**Comment by gitck** [comment]
> @gitck Right now CI is still failing. Can you run `mage notice`, and `go mod tidy` ?

Trying to run `mage notice` in libbeat folder results in 'Unknown target specified: notice' message.  Running `mage -l` lists does not list _notice_ as target.
Please could you please explain what might be the cause of the build failure. I do not understand the failing check and what's causing it.

**Comment by gitck** [comment]
@fearful-symmetry Although the merge with master did not introduce any changes, `mage check` succeeded. But still some tests failed. Can you help me how to proceed?

**Comment by fearful-symmetry** [comment]
At least two of those test failures are probably unrelated. @andrewkroh can you confirm?

**Comment by andrewkroh** [comment]
jenkins, run tests

**Comment by andrewkroh** [comment]
The travis failures look unrelated. Jenkins needed to be triggered by someone in the elastic org for it to run, so I've started it.

**Comment by gitck** [comment]
> 
> 
> The travis failures look unrelated. Jenkins needed to be triggered by someone in the elastic org for it to run, so I've started it.

@andrew Thank you for your support, but who is able to fix the still failing steps in the build pipeline (https://beats-ci.elastic.co/job/Beats/job/beats/view/change-requests/job/PR-19347/)? I do not have any clue how to proceed, or how to get this PR finished - seems to be a long winding road :-(.

**Comment by fearful-symmetry** [comment]
@gitck can you rebase against master again?

**Comment by gitck** [comment]
It seems that I totally messed up the PR during rebasing. Any advice how to proceed? Otherwise I would close this PR and create a new one instead (is propably easier for me to do, than fixing it)

**Comment by fearful-symmetry** [comment]
Roll back your rebase, try a merge from master instead.

**Comment by gitck** [comment]
> Roll back your rebase, try a merge from master instead.

Please review and thank you for your help. (I'd like to see this little feature in production as soon as possible)

**Comment by gitck** [comment]
Please consider this PR for the next release and let me know if I have to take some additional action to finish it. PLEASE!

**Comment by gitck** [comment]
> Roll back your rebase, try a merge from master instead.

Please review/check this PR again?

**Comment by gitck** [comment]
How can I reopen this PR?

**Comment by fearful-symmetry** [comment]
@gitck so sorry about that. I assigned myself since otherwise I don't seem to get notifications. Can you rebase and try again. Also @urso can you look at this? It's a little outside what I normally do.

**Comment by gitck** [comment]
@fearful-symmetry sorry for the delay, merged again with remote master - thanks for reopening this PR

**Comment by fearful-symmetry** [comment]
This looks fine from my perspective, my only concern is the default setting of `true` since that could be considered a breaking change. I'd like someone who knows the output module a bit more to look at it.

**Comment by fearful-symmetry** [comment]
jenkins, test this

**Comment by gitck** [comment]
> This looks fine from my perspective, my only concern is the default setting of `true` since that could be considered a breaking change. I'd like someone who knows the output module a bit more to look at it.

'true' reflects the behaviour before my changes, i.e. rotation on startup is the 'default' behaviour (at it is now) and my changes does not change it

**Comment by fearful-symmetry** [comment]
Ah, okay, that makes sense. 

@urso can you take a quick look at this? Not familiar with the output modules.

**Review by urso — APPROVED** [review]

**Comment by fearful-symmetry** [comment]
Alright, tested, looks good to me.

**Comment by fearful-symmetry** [comment]
@gitck just one last thing I noticed. Can you add the new config option to `/libbeat/_meta/config/output-file.reference.yml.tmpl`?

**Comment by fearful-symmetry** [comment]
You'll need to re-run `mage update` after.

**Comment by gitck** [comment]
@fearful-symmetry I added the new config option to the mentioned file,
but I was not able to execute `mage update` since this is an unknown target (libbeats folder). In addition the exection of one test failed during the build (https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-19347/3/).
Please give me some advice on how to proceed.

> @gitck just one last thing I noticed. Can you add the new config option to `/libbeat/_meta/config/output-file.reference.yml.tmpl`?

**Comment by fearful-symmetry** [comment]
The fact that it's in `fileout.asciidoc` suggests that it was updated properly? I have no idea what's wrong with CI, it looks like an upstream issue?

**Comment by gitck** [comment]
How to proceed, any suggestion?

**Comment by fearful-symmetry** [comment]
You might need to merge from master, there could be some CI changes we're missing.

**Comment by fearful-symmetry** [comment]
Okay, now I'm seeing a few actual failures:
```
Error: some files are not up-to-date. Run 'make update' then review and commit the changes. Modified: [auditbeat/auditbeat.reference.yml]
```
You might need to run that from the root `beats` directory, or from individual directories.

**Comment by gitck** [comment]
Ok, thanks for the hint. Unfortunately, ist seems that there is a problem with my dev environment unser Windows. As already mentioned earlier, I receive 'Unknown target specified: update' message. Any idea why this is   not Wirkung, seems like a basic setup issue?

**Comment by fearful-symmetry** [comment]
I think you might need to do `mage update` (or `mage -l` to see if it's another target) in a given directory. That _should_ work on Windows.

**Comment by gitck** [comment]
Obviously it does not work in my case ☹️. I am going to try it again on a Linux machine.

**Comment by gitck** [comment]
Finally, I managed to execute `make update` and merged with master again which fixed the build issues. Thanks for your hints and patience.

**Comment by fearful-symmetry** [comment]
@urso should we backport this to 7.x?

**Pull request merged**
