### PR TITLE
Try to close HTTP connections and wait for completion on output reload/close

### PR DESCRIPTION
**Pull request by urso**

### CODE REVIEW

**Comment by ph** [comment]
I will take another look at this.

**Comment by urso** [comment]
@ph I think this is still an issue affecting the Agent we have to solve, right?

**Comment by ph** [comment]
Yes this is still an issue, let me remove myself and assign the beats team.

**Comment by ph** [comment]
I guess we could either merge this or wait for bigger refactoring?

**Comment by ycombinator** [comment]
@urso Now that https://github.com/elastic/beats/issues/11068 is merged, did you want to resurrect this PR here? Or if you want I can take a stab at it too. Just let me know which way you prefer to go!

**Pull request closed without merging**
