### PR TITLE
New protocol support: SMTP

### LINKED ISSUE #467: New protocol support: SMTP
Add SMTP protocol support.
### HELO/Envelope
- HELO/EHELO
- MAIL FROM
- RCPT TO
### DATA
- From
- To
- CC
- Date
- Subject
- Headers
- Message content
### Responses & Other commands
- 2xx/3xx/4xx/5xx response codes
- RSET, VRFY, NOOP, QUIT, etc

### PR DESCRIPTION
**Pull request by eloyekunle**
Copies over and continues from #5408 which was abandoned.

Closes #467
Closes #5408

### CODE REVIEW

**Comment by eloyekunle** [comment]
The failing test seems to be a flake.

**Comment by eloyekunle** [comment]
Is anyone looking at this?

**Comment by eloyekunle** [comment]
Alright, bye

**Comment by adriansr** [comment]
Hi @eloyekunle,

We're terribly sorry that we're doing a bad job at reviewing community PRs. Your contribution is really appreciated and we would like to have the chance to review and merge it into Beats. Can you please reopen?

**Comment by SHolzhauer** [comment]
@eloyekunle any change you could reopen this? We would love to have this functionality!

**Pull request closed without merging**
