### PR TITLE
Update aws fields.yml with cloud related ECS fields

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
This PR is to add missing cloud related ECS fields into `aws/_meta/fields.yml`.

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
@exekias Should we document these ECS fields for Metricbeat? I added this mainly for `import-beats` in package registry. If this is not needed for Metricbeat, I can move these fields into a separate `fields.epr.yml` file.

**Comment by exekias** [comment]
This is not needed in Metricbeat, as we have a common ecs fields.yml that gets into the template, it includes these fields.

That said, I wonder if we should start doing this to all integrations, so we avoid the issue when moving them into packages. Any thoughts @mtojek @ruflin?


btw, we would need to set `overwrite: true` on these to make sure they don't collide with the already defined ones in ECS. (probably this is why tests are failing)

**Comment by ruflin** [comment]
@exekias One additional benefit besides the migration is that it also allows to "overwrite" docs of the fields. The ECS definition is very generic and in the context of a service it can be described in much more details what it means in this context.

**Comment by kaiyan-sheng** [comment]
With @mtojek 's PR https://github.com/elastic/integrations/pull/7, I can move these ECS fields into `fields.epr.yml` for aws module. This approach is consistent with what we have for Filebeat as well. We can keep it this way till further conversation happens around what should we do to support EPR in Beats.

**Pull request merged**
