### PR TITLE
Cherry-pick #23736 to 7.x: [Elastic Agent] Add the ability to run the Fleet Server

### LINKED ISSUE #22686: [Elastic Agent] Embed Fleet Server as part of the Elastic Agent
Fleet-Server binary should be shipped as part of the Elastic Agent: https://github.com/elastic/fleet-server

### PR DESCRIPTION
**Pull request by blakerouse**
Cherry-pick of PR #23736 to 7.x branch. Original message: 

## What does this PR do?

Adds the ability for Fleet Server to be started by Elastic Agent.

This just adds the basics for Fleet Server to be ran by Elastic Agent. This does not handle the enrollment piece of starting Fleet Server to perform the enrollment for the running Elastic Agent parent. That work will be present in a follow up branch.

This provides enough for the Fleet Server to be started by the Elastic Agent and for the release manager build of Elastic Agent to include the Fleet Server.

The Fleet Server requires a custom output configuration for elasticsearch because Fleet Server requires custom permissions and connection information before Elastic Agent has even enrolled into Fleet. This can currently be set manually in the `fleet.yml` once the Elastic Agent is enrolled in the current Kibana.

```
id: d9abff40-60bf-11eb-96c5-a7508ca0826b
fleet:
  enabled: true
  access_api_key: RHRuQlJIY0JXd3N4Q3A3TmZRbW46RVpPbHp1czVRY21zVzJXQlYtZzZhZw==
  kibana:
    protocol: http
    host: localhost:5601
    hosts:
    - localhost:5601
    timeout: 5m0s
    ssl:
      verification_mode: none
      renegotiation: never
  reporting:
    threshold: 10000
    check_frequency_sec: 30
  agent:
    id: ""
  server:
    output:
      elasticsearch:
        hosts: '${ELASTICSEARCH_HOSTS:localhost:9200}'
        username: '${ELASTICSEARCH_USERNAME:elastic}'
        password: '${ELASTICSEARCH_PASSWORD:changeme}'
```

The follow up branch will handle writing the `fleet.server.output.elasticsearch` into the `fleet.yml`.

## Why is it important?

Needed so Elastic Agent can run the Fleet server.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #22686

## Logs

```
2021-01-28T09:14:23.382-0500    INFO    operation/operator.go:245       operation 'operation-install' skipped for fleet-server.8.0.0
2021-01-28T09:14:23.772-0500    INFO    log/reporter.go:40      2021-01-28T09:14:23-05:00: type: 'STATE': sub_type: 'STARTING' message: Application: fleet-server--8.0.0[d9abff40-60bf-11eb-96c5-a7508ca0826b]: State changed to STARTING: Starting
2021-01-28T09:14:23.780-0500    INFO    operation/monitoring.go:39      operator.handleStartSidecar: monitoring is not running and disabled, no action taken
2021-01-28T09:14:24.806-0500    INFO    log/reporter.go:40      2021-01-28T09:14:24-05:00: type: 'STATE': sub_type: 'STARTING' message: Application: fleet-server--8.0.0[d9abff40-60bf-11eb-96c5-a7508ca0826b]: State changed to STARTING: Waiting on default policy with Fleet Server integration
```

### CODE REVIEW

**Comment by michalpristas** [comment]
Please cherry pick #23843 into this backport before merging

**Comment by blakerouse** [comment]
Cherry-picked #23843 into this PR.

**Review by michalpristas — APPROVED** [review]
backport loooks ok, e2e seems broken

**Pull request merged**
