### PR TITLE
[Filebeat] Add message to register encode/decode debug logs

### PR DESCRIPTION
**Pull request by AndersonQ**
## What does this PR do?

Add message to the debug log indicating which encoder/decoder is being registered instead of only logging the error (nil or not) returned.

## Why is it important?

A log message `<nil>` is unclear.

## Checklist

- [x ] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Logs

Current behaviour
```
Jan 26, 2022 @ 07:03:24.636 | debug | <nil> | filebeat
```

After changes:

```
Jan 26, 2022 @ 07:03:24.636 | debug | registering encoder 'application/json': returned error: <nil> | filebeat
```

### CODE REVIEW

**Comment by jlind23** [comment]
@AndersonQ even if it's about improving readability it shouldn't be backported to 8.0 but rather stay in 8.2

**Review by cmacknz — APPROVED** [review]

**Comment by kvch** [comment]
jenkins run tests

**Comment by kvch** [comment]
I think it is ready to be merged.

**Pull request merged**
