### PR TITLE
Adding support for v1.25.0 k8s

### PR DESCRIPTION
**Pull request by gizas**
## What does this PR do?

Adds the new version of v1.25.0 in the list of the supported/tested versions.

Part of https://github.com/elastic/observability-dev/issues/2195

### CODE REVIEW

**Review by ChrsMark — APPROVED** [review]
WFG

**Comment by gizas** [comment]
Wait until kindest/node:v1.25.0 to be relased. Still in beta
https://hub.docker.com/r/kindest/node/tags?page=1&name=1.25

**Review by tetianakravchenko — APPROVED** [review]

**Pull request merged**
