### PR TITLE
[Elastic Agent] Fix sysv init files for deb/rpm installation

### LINKED ISSUE #22360: Elastic Agent fails to start using instructions for sysvinit systems
Elastic Agent fails to start on a sysvinit system when following the instructions for systems not based on systemd that can be found in the [getting started docs](https://www.elastic.co/guide/en/ingest-management/7.10/ingest-management-getting-started.html):

```
# service elastic-agent start
Error: unknown command "test" for "elastic-agent"
Run 'elastic-agent --help' for usage.
unknown command "test" for "elastic-agent"
   ...fail!
```

Same happens when `init.d` script is called directly:
```
# /etc/init.d/elastic-agent start
Error: unknown command "test" for "elastic-agent"
Run 'elastic-agent --help' for usage.
unknown command "test" for "elastic-agent"
   ...fail!
```

The problem seems to be that this script calls the subcommand `test config`, that is not available in Agent: https://github.com/elastic/beats/blob/61f7acd88f0f5c6b41c3a3f22cf4b3d4e2e5c5f8/dev-tools/packaging/templates/deb/init.sh.tmpl#L21

If this script is supposed to work, the test subcommand should be supported by Agent, or it shouldn't be called there. If only systemd is supported, the init script should be removed, and docs updated.

In principle all the Linux distributions supported by Agent, support systemd (see [support matrix](https://www.elastic.co/support/matrix#matrix_os)). Though SysV init can be used at least in Debian 9 and 10 (by installing the `sysvinit-core` package).

Reported in discuss: https://discuss.elastic.co/t/elastic-agent-init-script-calls-unavailable-test-command/253811

### LINKED ISSUE #22485: Agent goes to Offline status on reboot of Linux deb stand-alone agent enroll to Fleet
**Kibana version:**
Kibana: 7.10.0 BC5 cloud environment

**Elasticsearch version:**
Elasticsearch: 7.10.0 BC5 cloud environment

**Host OS and Browser version:**
Linux Debian 9 , All

**Original install method (e.g. download page, yum, from source, etc.):**
7.10.0 BC5 cloud environment from https://cloud.elastic.co

**Description**
Agent goes to Offline status on reboot of Linux deb stand-alone agent enroll to Fleet

**Preconditions**
1. 7.10.0 BC5 Kibana cloud environment(with commit 1796b5ec8fa1e60ccea63f2e5c25ccc665b92fdc) should be available.
2. Login into the above Kibana environment with 'elastic' superuser.
3. 7.10.0 BC5 Linux amd64.deb agent package should be downloaded and installed(on Linux Debian 9) from below location:
https://staging.elastic.co/7.10.0-b55684ff/downloads/beats/elastic-agent/elastic-agent-7.10.0-amd64.deb

**Steps to Reproduce**
1. Download the "elastic-agent-7.10.0-amd64.deb" package.
2. SSH to the endpoint and place the agent package on /home/zeus location on Debian 9 Linux machine.
3. Hit the command to get the root/admin permission: sudo su root
4. Run the command:   sudo dpkg -i elastic-agent-7.10.0-amd64.deb
5. Download elastic-agent.yml from Add agent ->Standalone mode on Agents tab in Kibana and add Kibana login username and password in outputs section of elastic-agent.yml (Modify ES_USERNAME and ES_PASSWORD in the outputs section of elastic-agent.yml to use your Elasticsearch credentials)
[elastic-agent_yml.zip](https://github.com/elastic/beats/files/5510426/elastic-agent_yml.zip)

6. Copy elastic-agent.yml file to /home/zeus on Linux Debian 9 machine
7. Then execute:  sudo cp /home/zeus/elastic-agent.yml /etc/elastic-agent/elastic-agent.yml
8. Run the following commands to run the standalone agent :- 
elastic-agent run

9. Execute the enroll command :-
sudo elastic-agent enroll https://d9dc24b9e27749e8af99cb8d590ca97f.europe-west1.gcp.cloud.es.io:9243 Y1RKaHJIVUJHcXBIMWZsU1dLTEI6cEtfakhXVTJScUctUmJhUENiRFlZQQ==

10. Execute the below command to enable the agent :-
systemctl enable elastic-agent

and observe that **error** is displayed in putty :-
```
Failed to reload daemon: The name org.freedesktop.PolicyKit1 was not provided by any .service files
update-rc.d: error: no runlevel symlinks to modify, aborting!
```

11. Execute the below command to start the agent :-
systemctl start elastic-agent

and observe that following **error** is displayed in putty but **agent comes in Online status and activity logs are displayed** :-
```
Failed to start elastic-agent.service: The name org.freedesktop.PolicyKit1 was not provided by any .service files
See system logs and 'systemctl status elastic-agent.service' for details.
```

12. Run the command 'sudo reboot' and observe that **agent goes to Offline status**. 

**Test data**
N/A

**Impacted Test case id**
https://elastic.testrail.io/index.php?/cases/view/34373

**Actual Result**
Agent goes to Offline status on reboot of Linux deb stand-alone agent enroll to Fleet

**Expected Result**
Agent should remain in Online status on reboot of Linux deb stand-alone agent enroll to Fleet

**What's working**
 - Issue is not occurring on stand-alone agent enroll to Fleet with Linux rpm

**What's not working**
 - N/A
 
**Screenshot**
1. Errors in putty on enabling and starting the agent: 
putty_error

2. Agent in Online status with activity logs on executing agent start command(before reboot):
Online_beforeReboot_latest

3. Agent in Offline status after reboot:
Offline_afterReboot

4. Linux Debian 9 machine VSphere Template:
Linux_Debian_9_template

**Logs**
N/A

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Fixes the sysv init files so it works on deb/rpm systems that use sysv and not systemd.

## Why is it important?

So deb/rpm work on sysv init systems.

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #22360
- Closes #22485

### CODE REVIEW

**Comment by ph** [comment]
Can we target 7.x and 7.10 so it goes in 7.10.1?

**Comment by ph** [comment]
@rahulgupta-qasource and @EricDavisX this solve the recent issues we found in debian9 or other based sysv system.

**Comment by blakerouse** [comment]
@ph will backport to 7.10

**Comment by EricDavisX** [comment]
it would be great to do the possibly minimal work to get the .rpm/.deb tests back running in the e2e-testing repo here https://github.com/elastic/e2e-testing/issues/379
 and we could use this chance to add in Debian9 (if the current Debian system under test doesn't have SysV)

**Review by michalpristas — APPROVED** [review]
LGTM

**Comment by rahulgupta-qasource** [comment]
Hi @EricDavisX /@ph

We are blocked to validate this ticket for 7.10.1 BC1 .rpm(on CentOS7 machine) and .deb(on Debian9 machine) packages on 7.10.1 BC1 Kibana cloud environment(deployed from [staging platform](https://staging.found.no)) due to bug [#22744](https://github.com/elastic/beats/issues/22744)

```
Build details:
Kibana Commit: 1d4cfde288ede0c4bc6277b4d589ca0cb96b231f
Build : 36050
7.10.1 BC1 Linux .rpm agent package link: https://staging.elastic.co/7.10.1-ce3b40e6/downloads/beats/elastic-agent/elastic-agent-7.10.1-x86_64.rpm
7.10.1 BC1 Linux .deb agent package link: https://staging.elastic.co/7.10.1-ce3b40e6/downloads/beats/elastic-agent/elastic-agent-7.10.1-amd64.deb
```

Once the above bug [#22744](https://github.com/elastic/beats/issues/22744) is fixed, we will validate this ticket.

**Comment by EricDavisX** [comment]
discussed with team we will target additional fixes in 7.11.0 and 7.10.2 - we are past the date for 7.10.1 fixes to routinely be discussed and since it is not functioning in 7.10 we aren't any worse than we were.  we can do a thorough testing run in 22744 in later cycle.

**Comment by vipulsrivastava-qasource** [comment]
Hi @EricDavisX

We have performed regression testing for Linux deb/rpm on 7.10.2 BC1 Kibana cloud build. Build details is as follows:

```
Platform: Staging
Version: 7.10.2
Commit: a0b7936
Build number: 36136
Artifact: https://staging.elastic.co/7.10.2-e6b2b8c2/summary-7.10.2.html
```

We have execute test cases under test plan execution :

- [Test Run for Linux .deb deploy of BC Agent/Endpoint with minimal sanity test](https://elastic.testrail.io/index.php?/runs/view/952&group_by=cases:section_id&group_order=asc)
- [Test Run for Linux .rpm deploy of BC Agent/Endpoint with minimal sanity test](https://elastic.testrail.io/index.php?/runs/view/955&group_by=cases:section_id&group_order=asc)

Please let us know if anything else is required to be covered. 

Thanks

**Pull request merged**
