### PR TITLE
fix productname in CrowdStrike module docs

### PR DESCRIPTION
**Pull request by DanRoscigno**
Product name in `crowdstrike` module should be CrowdStrike (uppercase `S`)

### CODE REVIEW

**Comment by DanRoscigno** [comment]
@tonymeehan , while I am in here:

Should:

This is the filebeat module for **the** CrowdStrike Falcon using the Falcon SIEM Connector.

be

This is the filebeat module for CrowdStrike Falcon using the Falcon SIEM Connector. (removing `the`)?

**Comment by andrewkroh** [comment]
@DanRoscigno Yeah, Dan, it would be good to fix that too. Thanks!

**Comment by DanRoscigno** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by DanRoscigno** [comment]
@andrewkroh I don't know what I did wrong.  `make check` passed on my laptop.

**Pull request merged**
