### PR TITLE
Fix alias and template setup order

### PR DESCRIPTION
**Pull request by urso**
There is the chance an index is not correctly managed by ILM, due to
setup order. This changes fixes the order.

### CODE REVIEW

**Comment by ruflin** [comment]
@urso You mention there is a chance that it is not correctly managed. But based on the code it seems that was always the case as the alias / index was always created before the template when a Beat was directly started?

I remember we had the same bug in the initial code of ILM but it got fixed before it was shipped in 6.x. So my assumption is the above affects all 7.x releases? I added a needs_backport label.

@simitt That is also my understanding.

**Comment by simitt** [comment]
@ruflin it looks I introduced this bug just recently https://github.com/elastic/beats/pull/11777/files#diff-a7b20900159263d87105489854d4d628R216, and I think this is only in master so far.

**Comment by simitt** [comment]
> I remember we had the same bug in the initial code of ILM but it got fixed before it was shipped in 6.x. 

@ruflin could you by any chance point to that fix? I'd like to follow along with those changes.

**Comment by urso** [comment]
Code 7.0 handles this correctly. This PR fixes a code regression and adds improves checks. Unfortunately python tests fail now, as index is setup correctly.

Need to do some more investigation in 7.0.

**Comment by ruflin** [comment]
@simitt Good news that it's only in master. Here is the PR for 6.6 but don't think it's relevant now that big part of the code changed: https://github.com/elastic/beats/pull/9617 More important is that we should have some tests to validate that it works correctly.

**Comment by simitt** [comment]
jenkins, test this

**Comment by urso** [comment]
There are a many changes in how we do setup and test in flight the recent days.
Closing this in favor of https://github.com/elastic/beats/pull/12132, that will include the fixe and also fixes a many related integration tests.

**Pull request closed without merging**
