### PR TITLE
rename duplicate prospector test

### PR DESCRIPTION
**Pull request by spacewander**
...and then update the broken one.

### CODE REVIEW

**Comment by ruflin** [comment]
@spacewander Thanks a lot for spotting this. I wonder why CI didn't complain about the duplicated method name?

**Comment by spacewander** [comment]
@ruflin I personally recommend to integrate [pyflakes](https://pypi.python.org/pypi/pyflakes) into python development process. It can do things more than syntax check.

**Comment by ruflin** [comment]
@spacewander Thanks for the recommendation. I will have a look. I would have expected python itself to complain :-)

**Comment by ruflin** [comment]
@spacewander It seems like appveyor is not happy with the change. I can have a closer look if you want?

**Comment by spacewander** [comment]
@ruflin Of course you can.

**Comment by ruflin** [comment]
It seems the test on windows fails, because we compare paths and on windows the paths have \ instead of /. Perhaps we could simplify the test and only watch for `Stopping harvester, closing file:`?

**Comment by spacewander** [comment]
@ruflin I have updated the pr and now all tests pass.

**Comment by ruflin** [comment]
Merged. @spacewander Thanks a lot for the fix.

**Pull request merged**
