### PR TITLE
[Ingest Manager] Agent atomic installer

### PR DESCRIPTION
**Pull request by michalpristas**
## What does this PR do?

This PR makes unpacking an "atomic" operation by unpacking to temporary location and then moving it to the correct place, this should solve some rare issues which manifests when agent got killed during installation of beats and results in half-unpacked archive to be understood as correct installation

I tested this change on darwin/linux/windows and using local e2e test suite. 

Fixes: https://github.com/elastic/beats/issues/21718

## Why is it important?

Makes agent more reliable

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by ph** [comment]
@ruflin OK to backport this to 7.10?

**Comment by ph** [comment]
Well, the `win32` thing seems like a a bug fix to me. :)

Should we have some delay/backoff in the subprocess?

**Comment by ph** [comment]
@michalpristas Can you link the issue for the bug in that PR description?

**Comment by michalpristas** [comment]
@ph we added sync when unpacking, which should get rid of `text file busy` and then this one together with flipped `enroll-install-restart` flow should help us get rid of issue described here: https://github.com/elastic/beats/issues/21718

**Comment by ph** [comment]
Thanks @michalpristas for the clarification, @ruflin I think its worth to have it shipped in 7.10.

**Review by blakerouse — APPROVED** [review]
Looks good to me.

**Pull request merged**
