### PR TITLE
Panic when using inline SSL certificate or key

### PR DESCRIPTION
**Pull request by ph**
When the key or certificate was smaller than 256bytes the system was
throwing a panic, the problem was generate by a debug message. Instead
of logging part of the keys or certificate in the log we are just
writing "inline".

Fixes: #23820

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by andrewkroh — APPROVED** [review]
LGTM

**Review by urso — APPROVED** [review]

**Comment by ph** [comment]
test this

**Comment by ph** [comment]
Jenkins test this please

**Comment by ph** [comment]
```
[2021-02-04T18:05:32.705Z] >> python test: Unit Testing
[2021-02-04T18:05:54.638Z] ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Windows\\Temp\\pip-uninstall-jpa670xd\\pip.exe'
[2021-02-04T18:05:54.638Z] Consider using the `--user` option or check the permissions.
[2021-02-04T18:05:54.638Z] 
````

I've pinged obs-robot to look at this issue, change in libbeat actually force a full CI suite so maybe it exist for some time?

**Comment by ph** [comment]
Jenkins test this

**Pull request merged**
