### PR TITLE
Correct the default filename of events-data

### PR DESCRIPTION
**Pull request by f1tz**
Change 'event-data' to 'events-data' in the document.

## Reference:
https://github.com/elastic/beats/blob/1bd39c5cf55eed1715a41133ef64c324fc83adca/libbeat/tests/system/beat/beat.py#L535
https://github.com/elastic/beats/blob/1bd39c5cf55eed1715a41133ef64c324fc83adca/libbeat/tests/integration/framework.go#L626

### CODE REVIEW

**Comment by pierrehilbert** [comment]
Thanks @f1tz for your contribution.
Could you please sign our CLA?

**Comment by belimawr** [comment]
> @belimawr as you worked on #38767, I think it might be a typo in the filename actually, not in the docs because all the config parameters have `event_data` in them.
> 
> What do you think we should fix here?

Yes, indeed it's a typo in the docs. I believe the only other file that needs updating is [libbeat/_meta/config/logging.reference.yml.tmpl](https://github.com/elastic/beats/blob/5a85598f4e4895c6ff1f0586d2a91230a4aba4e0/libbeat/_meta/config/logging.reference.yml.tmpl#L95), the other configuration files are generated from it.

**Comment by nimarezainia** [comment]
> > @belimawr as you worked on #38767, I think it might be a typo in the filename actually, not in the docs because all the config parameters have `event_data` in them.
> > What do you think we should fix here?
> 
> Yes, indeed it's a typo in the docs. I believe the only other file that needs updating is [libbeat/_meta/config/logging.reference.yml.tmpl](https://github.com/elastic/beats/blob/5a85598f4e4895c6ff1f0586d2a91230a4aba4e0/libbeat/_meta/config/logging.reference.yml.tmpl#L95), the other configuration files are generated from it.

@belimawr could you please open an issue with this detail so it can get addressed (fyi @kilfoyle )

**Comment by belimawr** [comment]
> @belimawr could you please open an issue with this detail so it can get addressed (fyi @kilfoyle )

@nimarezainia I believe this feature only documented here and in the Elastic-Agent standalone logging, so I just created the PR to fix it: https://github.com/elastic/ingest-docs/pull/1520

**Comment by nimarezainia** [comment]
> > @belimawr could you please open an issue with this detail so it can get addressed (fyi @kilfoyle )
> 
> @nimarezainia I believe this feature only documented here and in the Elastic-Agent standalone logging, so I just created the PR to fix it: [elastic/ingest-docs#1520](https://github.com/elastic/ingest-docs/pull/1520)

thank you much appreciated,

**Comment by rdner** [comment]
@f1tz could you please update https://github.com/elastic/beats/blob/5a85598f4e4895c6ff1f0586d2a91230a4aba4e0/libbeat/_meta/config/logging.reference.yml.tmpl#L95 and then run `make update` in the root of the repository.

This should update all the occurrences of this typo. Thanks!

**Review by gizas — APPROVED** [review]

**Pull request merged**
