### PR TITLE
[Metricbeat] Add more TCP states for socket_summary

### PR DESCRIPTION
**Pull request by shafferjohn**
Add more TCP states [(reference to rfc793)](https://tools.ietf.org/html/rfc793) in `socket_summary` for network debugging and alerting.

### CODE REVIEW

**Comment by fearful-symmetry** [comment]
jenkins, test this.

**Comment by exekias** [comment]
jenkins, test this please

**Comment by immon** [comment]
@exekias @andresrc I cannot see this PR merged into [7.6.0](https://github.com/elastic/beats/blame/v7.6.0/metricbeat/module/system/socket_summary/socket_summary.go) and to [7.10.0](https://github.com/elastic/beats/blame/v7.10.0/metricbeat/module/system/socket_summary/socket_summary.go). Has this functionality been ever released? Shouldn't we cherry-pick the PR to 7.x branch?

**Comment by exekias** [comment]
Hi @immon, I'm sorry, It seems this one slipped the backporting process. I have backported it now

**Comment by andresrc** [comment]
@fearful-symmetry can you check this change is also in the package? Thanks!

**Comment by fearful-symmetry** [comment]
@andresrc looks like these are all good in the integrations package.

**Pull request merged**
