### PR TITLE
feat: trigger packaging after a successful build on master

### PR DESCRIPTION
**Pull request by kuisathaverat**
## What does this PR do?

It adds a trigger to run the packaging job after a merge on the master branch.

## Why is it important?

This release fresh snapshots on every successful build.

### CODE REVIEW

**Comment by andrewkroh** [comment]
Does this job push any status messages to github?

**Comment by kuisathaverat** [comment]
no, it does not have any, yesterday I thought about it, is weird to put the comment and do not see a check, and it is difficult to find the job in a PR, so I think we should add a GitHub check.

**Comment by kuisathaverat** [comment]
@andrewkroh Do we want the same trigger for 7.x and 7.7?

**Comment by andrewkroh** [comment]
Yes, we'll want to have the packaging job running for 7.x and 7.7+. Thanks

**Pull request merged**
