### PR TITLE
Fix: Allow non-padded base64 data to be decoded by decode_base64_field

### LINKED ISSUE #27021: decode_base64_field doesn't allow to decode unpadded base64 strings
It seems that `decode_base64_field` is using `base64.StdEncoding.DecodeString` to decode the string, but that function only supports unpadded strings. There also is a `base64.RawStdEncoding.DecodeString` function, but this one only supports unpadded strings.

https://github.com/elastic/beats/pull/25817 tried to solve this by appending `=`-signs until the string was fully padded, but another solution could be to strip all the `=`-signs, and using `base64.RawStdEncoding.DecodeString`.

The use-case for this is to decode a JWT Authorisation header to extract the `user_id` field, like has been documented [here](https://medium.com/@guyromb/decode-jwt-traefik-access-logs-using-filebeat-95d935eb7c4f). This example is using a **script processor** to add the padding however, and this isn't available in all *beat projects.

Version: packetbeat-7.13.4 (but actually all the latest libbeat-projects)
Operating System: Ubuntu 20.04

### PR DESCRIPTION
**Pull request by michaelarnauts**
## What does this PR do?

This change allows decoding of any raw base64 input strings that were previously encoded without standard padding character (`=`).

By stripping the padding, we can use `base64.RawStdEncoding.DecodeString` to decode the base64 string. This is easier then appending the padding characters.

Another attempt to fix this has been made in #25817, but that PR has been closed.

## Why is it important?

When attempting to decode the payload (middle) section of a JWT token, it was discovered that the decode was failing, because padding characters are not included in a JWT token string. Padding is not required in base64, so it makes sense to allow to decode both unpadded and padded strings.

Currently, there is a workaround for some beats by appending the `=`-signs in a javascript processor, but that isn't available in all beats, and is a ugly workaround anyway. See https://medium.com/@guyromb/decode-jwt-traefik-access-logs-using-filebeat-95d935eb7c4f

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have made corresponding change to the default configuration files
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

Tests have been added that will test this behavior.

## Related issues
- Closes #27021
- Relates #25817

### CODE REVIEW

**Comment by michaelarnauts** [comment]
> x Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement):
> [0f25a96](https://github.com/elastic/beats/commit/0f25a9691a47d83d55a063e1eecfac5152fe3046)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

The CLA has been signed now.

**Comment by michaelarnauts** [comment]
Sure, I can fix the PR easily if somebody from the team could indicate if this is an accepted fix.

**Comment by jsoriano** [comment]
Hey  @michaelarnauts, thanks for your contribution!

I think the fix looks good, but not sure about the implications of decoding unpadded base64 data (if any), maybe @adriansr or @kvch can review or give their opinions? Thanks!

**Comment by adriansr** [comment]
I've moved the changelog entry from _Breaking Changes_ to _Added_ as I don't think anyone could have been taking advantage of the fact that this processor failed for non-padded strings. Also the documentation didn't make any claims regarding padding. For the same reason it's also not a bug fix.

**Comment by michaelarnauts** [comment]
> I've moved the changelog entry from _Breaking Changes_ to _Added_ as I don't think anyone could have been taking advantage of the fact that this processor failed for non-padded strings. Also the documentation didn't make any claims regarding padding. For the same reason it's also not a bug fix.

Sorry, I didn't mean to put it in a breaking change. 

Not sure if it should be called a feature though, especially since the docs didn't indicate that the base64 strings *should* be padded. I assumed it would support all variants. I don't know what the policy of backporting to a point release is, and if that depends if it's a bug or a feature :)

**Comment by kvch** [comment]
I would consider it a feature. With this change, Beats can process non-padded base64 data. :tada:

**Review by kvch — APPROVED** [review]

**Comment by kvch** [comment]
Failing tests are unrelated.

**Pull request merged**
