### PR TITLE
Remove ECS from aws dashboard names

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
AWS metricbeat modules are only in 7.0 and after, so there is no need to have `ECS` as suffix on dashboard names. This PR is to remove them and update the dashboard images.

### CODE REVIEW

**Comment by ruflin** [comment]
jenkins, test this

**Comment by kaiyan-sheng** [comment]
> LGTM
> 
> I assume this means you added the `ECS` postfix manually when you initially created these dashboards?

I don't think I added myself initially. It's more of when I came back from a vacation, all dashboards got `ECS` postfix on it 😬

**Comment by codingogre** [comment]
With ECS why are there so many cloud specific (AWS) visualizations?  Should be able to have lots of cross cutting visualizations with GCP, AWS, and Azure

**Comment by kaiyan-sheng** [comment]
> With ECS why are there so many cloud specific (AWS) visualizations? Should be able to have lots of cross cutting visualizations with GCP, AWS, and Azure

@codingogre That will be great to have after we have GCP Azure support in Metricbeat 👍 Right now these visualizations are just for individual services in AWS.

**Pull request merged**
