### PR TITLE
Libbeat add_kubernetes_metadata processor: Missing fields replicaset.name, etc. in fields.yml

### PR DESCRIPTION
**Pull request by alakahakai**
Address issue #11133: 
* Libbeat add_kubernetes_metadata processor: Add Kubernetes replica-set map to fields.yml

Now testing works

test_fileset_file_0_coredns (test_xpack_modules.XPackTest) ... ok
test_fileset_file_1_coredns (test_xpack_modules.XPackTest) ... ok

----------------------------------------------------------------------
Ran 2 tests in 3.653s

OK

### CODE REVIEW

**Comment by alakahakai** [comment]
> You mention in #11133 that replicaset.name is missing but here you introduce an object `replicaset`. Why not directly introduce the field?

There might be other fields that will be added by the processor. I am simply following the existing practice where it uses map for labels and other fields.

Regarding Why the CI test is not failing, I assume that it is not testing k8s deployment with anything or filebeat deployed as daemonset.

**Comment by alakahakai** [comment]
jenkins, test this

**Comment by alakahakai** [comment]
Because of time constraints, I am going to just add the missing replicaset.name field for now. But it must be worth looking into why the replicaset fields are missing.

**Comment by ruflin** [comment]
jenkins, test this

**Comment by alakahakai** [comment]
@ruflin Sure, thanks

**Comment by jsoriano** [comment]
Sorry, but I cannot follow :thinking:

`kubernetes.replicaset` fields are not created by anything in libbeat, they are only created by kubernetes `state_replicaset` metricset, and they are documented there, why are we adding this to all beats?

**Comment by alakahakai** [comment]
It is added by the libbeat add_kubernetes_metadata processor. Please take a look at the issue #11133

**Comment by alakahakai** [comment]
It seems to be added [here](https://github.com/elastic/beats/blob/master/libbeat/common/kubernetes/metadata.go) 
Looks like we need to add statefulset.name as well. metadata_test.go does not cover either one.

**Comment by jsoriano** [comment]
> It seems to be added [here](https://github.com/elastic/beats/blob/master/libbeat/common/kubernetes/metadata.go)
> Looks like we need to add statefulset.name and deployment.name as well. Also, metadata_test.go does not cover either one.

Oh I see, good catch.

But now these fields are defined in two places for metricbeat, should we remove them from the kubernetes metricsets?

**Comment by ruflin** [comment]
@jsoriano Looks like they are removed here? https://github.com/elastic/beats/pull/11134/files#diff-caf37f855a3380a66e838f4e45e7777dL7

**Comment by alakahakai** [comment]
@jsoriano Please let me know if the PR looks good to you. I do have another PR #11200 that are kinda blocked by this. Thanks!

**Comment by alakahakai** [comment]
I assume that this is fine to go now. Thanks.

**Pull request merged**
