### PR TITLE
[Metricbeat] [Azure] Fix monitor namespace empty string

### PR DESCRIPTION
**Pull request by ghost**
## Proposed commit message

`Metricnamespace` was always being sent to the Azure Monitor API in the following functions:
- `GetMetricDefinitions`
- `GetMetricValues`

The problem is that the Monitor API does not expect empty strings, if there is no namespace it should be sent as `nil`. This can cause unexpected behaviors. Conditionally sending it fixes this problem.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Relates elastic/beats#36181

### CODE REVIEW

**Review by shmsr — APPROVED** [review]

**Comment by zmoog** [comment]
Relates to https://github.com/elastic/beats/issues/36181

**Comment by gpop63** [comment]
From what I saw, all data streams that use the `monitor` metricset have always set a namespace, only the generic `monitor` data stream allows users to setup their own configs - which is where things can go wrong.

Without this fix it is indeed not working properly since a client could decide to not use any namespace but we still send `""` and Azure Monitor API will give 400 Bad Request.

**Comment by zmoog** [comment]
> Without this fix it is indeed not working properly since a client could decide to not use any namespace but we still send `""` and Azure Monitor API will give 400 Bad Request.

Yeah, I can see your point about _extending_ the Azure Monitor metricset; this would allow the metricset to support new use cases where users do not want to set a namespace.

However, this change only partially resolves the root problem creating https://github.com/elastic/beats/issues/36181. 

The issue https://github.com/elastic/beats/issues/36181 happens because a user made a mistake in writing the configuration, and a blank namespace value slipped into the request causing the status 400. Before this change, there was an implicit assumption the `namespace` was required. But this was not reflected in the config validator. 

If we change the metricset requirements and handle nil `namespace` values, we avoid the status 400 from happening. However, AFAIK, we have no guarantee the result will always be the same if users set the `namespace` value to nil by mistake again.

**Comment by zmoog** [comment]
So I think this is more of a "Add support for the blank namespace in the Azure Monitor metricset" than a "Fix X".

Fixing the error 400 is a (welcome) side-effect of this change. But we're not sure about what can happen when users unintentionally set `namespace` to blank.

**Comment by zmoog** [comment]
The change seems sounds, but I want to address potential problems.

@gpop63, are there risks in allowing empty namespaces, like increase in API costs or pulling too many records?

**Comment by gpop63** [comment]
These errors/behaviors would only happen with the generic `monitor` data stream. The namespace basically helps you narrow the specific resources you want to retrieve metrics from.

There might be cost differences when not using a namespace since the request will be broader and not targeting specific resources. The primary cost is related to the volume of data collected, rather than the use of a namespace.

**Comment by gpop63** [comment]
@zmoog From my point of view these are 2 different issues, this one is simply fixing the behavior of the metricset so it works just like before the SDK upgrade (1). Then, we can add additional checks/validation for the config to see if namespace is sent and/or formatted properly. I might be wrong or missing something.

(1) Before the SDK upgrade no namespaces were allowed, right?

**Comment by zmoog** [comment]
> (1) Before the SDK upgrade no namespaces were allowed, right?

From my testing, the older SDK version targeted an older API version that was tolerant of empty namespaces. It accepted empty values instead of sending "400 Bad Request" as a response.

**Comment by zmoog** [comment]
> this one is simply fixing the behavior of the metricset so it works just like before the SDK upgrade

| Namespace  | Old SDK | New SDK | 
| ---------- | ------- | ------- |
| With value | Ok      | Ok      |
| Empty      | Ok      | Error   |


What's the behaviour of the **Old SDK** version with an **empty** namespace? If it returns the same values as the **New SDK** with a `nil` value, I think we can merge this PR.

@gpop63, do you have time to give these scenarios a try?

**Comment by gpop63** [comment]
@zmoog just tested both SDKs

- Old SDK does not care if namespace is empty, no errors thrown and it fetched some metrics
- Exact same config with new SDK will throw this `Received invalid query parameter: [api-version, 2018-01-01],[metricnamespace, ]`

**Comment by zmoog** [comment]
> @zmoog just tested both SDKs
> 
> * With value they both work as expected
> * Old SDK does not care if namespace is empty, no errors thrown and it fetched some metrics
> * Empty namespace with new SDK will throw this `Received invalid query parameter: [api-version, 2018-01-01],[metricnamespace, ]`
> * With newer SDK if we send `nil`, it's basically the same thing as empty value with the older one

Okay.

I am primarily interested in the Old SDK vs. (New SDK + fix) behavior with an empty namespace; the fix allows the New SDK to run without errors.

Will these two return the same data?

**Review by zmoog — CHANGES_REQUESTED** [review]
We need to check the Old SDK vs. (New SDK + fix) behaviour with an empty namespace; the fix allows the New SDK to run without errors.

Will these two return the same data?

**Comment by gpop63** [comment]
@zmoog Yes, from my tests Old SDK vs New SDK (+fix) behave the exact same way with an empty namespace.

**Review by zmoog — APPROVED** [review]

**Pull request merged**
