### PR TITLE
update document to include a new community beat

### PR DESCRIPTION
**Pull request by kckecheng**
Add reference to a new beat named unitybeat, which is responsible for collecting performance metrics from Dell EMC Unity SAN storage array. Currently, overall storage processor usage, IOPS and bandwidth are supported by the beat.

### CODE REVIEW

**Comment by kvch** [comment]
jenkins test this

**Comment by kvch** [comment]
Do you mind preserving the alphabethical order of the list? Please move the Beat to the appropiate position.

**Comment by kckecheng** [comment]
> Do you mind preserving the alphabethical order of the list? Please move the Beat to the appropiate position.

Updated accordingly, thanks.

**Comment by ruflin** [comment]
jenkins, test this

**Pull request merged**
