### PR TITLE
Update communitybeats.asciidoc

### PR DESCRIPTION
**Pull request by sentient**
Add statsdbeat

### CODE REVIEW

**Comment by exekias** [comment]
Thanks for contributing this @sentient! Do you know our `graphite` module? I would say the concept is quite similar to this, would it make sense to have this as a Metricbeat module? // cc @jsoriano

**Comment by sentient** [comment]
@exekias , 
Jaime told me about the Graphite module. It probably could have also been implemented as a metricbeat module as well. Would a module implementation make it easier for others to use it? 

I don't know to much about modules yet. And how I can set \my own field definitions. When I have time I will read up on that a bit.

**Comment by ruflin** [comment]
@sentient Any chance to sign the CLA? https://www.elastic.co/contributor-agreement

For the module: The reason it would make easier is that it would be available to everyone that uses Metricbeat and not a second Beat would have be installed. The other part is that we would support it from our side if it makes it into Metricbeat.

**Comment by sentient** [comment]
CLA signed and submitted under the company 'NewYu, Inc.'

**Comment by ruflin** [comment]
@sentient Thank you. I sorted out the CLA thingy and from now all PR's should be directly go green.

**Pull request merged**
