### PR TITLE
[metricbeat]Add kubernetes controller dashboard

### PR DESCRIPTION
**Pull request by odacremolbap**
Kubernetes controller dashboard

### CODE REVIEW

**Comment by odacremolbap** [comment]
jenkins, test my dear

**Comment by odacremolbap** [comment]
jenkins, test please

**Comment by odacremolbap** [comment]
jenkins, test this

**Comment by exekias** [comment]
could you share a screenshot of this dashboard?

**Comment by odacremolbap** [comment]
this is the one I'll be including in docs

kubernetes-controllermanager

**Comment by odacremolbap** [comment]
note to self: gradients are not looking good, changing to rainbow

**Comment by sayden** [comment]
Tested locally
image

**Pull request merged**
