### PR TITLE
Backport to 6.x: Multiple doc changes (#7696 #7883 #7888 #7889 #7903 #7937 #7939 #7948 #7949 #7950)

### PR DESCRIPTION
**Pull request by dedemorton**
Cherry-picks the following doc PRs into the 6.x branch. Note that running `make update` resulted in some updates I wasn't expecting. Need someone to confirm that they are good for 6.x. Don't seem related the changes in cherry-picked PRs.

https://github.com/elastic/beats/pull/7696
https://github.com/elastic/beats/pull/7883
https://github.com/elastic/beats/pull/7888
https://github.com/elastic/beats/pull/7889
https://github.com/elastic/beats/pull/7903
https://github.com/elastic/beats/pull/7937
https://github.com/elastic/beats/pull/7939
https://github.com/elastic/beats/pull/7948
https://github.com/elastic/beats/pull/7949
https://github.com/elastic/beats/pull/7950

### CODE REVIEW

**Comment by jsoriano** [comment]
It LGTM, `make update` will be needed though.

**Comment by dedemorton** [comment]
@jsoriano I rebased and ran `make update` again. Can you take another look before I merge. Thanks!

**Comment by jsoriano** [comment]
@dedemorton test builds still fail due to `make update` needed :(

**Comment by dedemorton** [comment]
jenkins, please test this

**Comment by dedemorton** [comment]
jenkins, test this

**Comment by dedemorton** [comment]
When I run `make update` there are no files changed. I kicked off another build. If this one fails, maybe it'll be faster for me to close this and create a new PR with the cherry-picks.

**Comment by dedemorton** [comment]
This PR is messed up, so I've created another PR with the cherrypicks here: https://github.com/elastic/beats/pull/8188

**Pull request closed without merging**
