### PR TITLE
Fix build tags in journald input

### PR DESCRIPTION
**Pull request by belimawr**
## Proposed commit message

See title

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Disruptive User Impact
None

~~## Author's Checklist~~

## How to test this PR locally

Build Filebeat by running: `GOOS=linux GOARCH=arm64 go build`

~~## Related issues~~
~~## Use cases~~
~~## Screenshots~~
~~## Logs~~

### CODE REVIEW

**Comment by belimawr** [comment]
Auto-merge is enabled

**Comment by mauri870** [comment]
@belimawr  Out of curiosity, what is the reasoning behind requiring cgo to build this? Mind adding it to the MR description? Thanks.

**Comment by VihasMakwana** [comment]
> @belimawr Out of curiosity, what is the reasoning behind requiring cgo to build this? Mind adding it to the MR description? Thanks.

@mauri870 I think Tiago has removed the `cgo` dependency in this PR 😅

**Comment by mauri870** [comment]
> > @belimawr Out of curiosity, what is the reasoning behind requiring cgo to build this? Mind adding it to the MR description? Thanks.
> 
> @mauri870 I think Tiago has removed the `cgo` dependency in this PR 😅

Thanks for pointing that out! 😅 I was actually curious about the reasoning behind the removal of the cgo dependency. Was it added by mistake initially, or was there a specific reason for its removal?

**Comment by belimawr** [comment]
> > > @belimawr Out of curiosity, what is the reasoning behind requiring cgo to build this? Mind adding it to the MR description? Thanks.
> > 
> > 
> > @mauri870 I think Tiago has removed the `cgo` dependency in this PR 😅
> 
> Thanks for pointing that out! 😅 I was actually curious about the reasoning behind the removal of the cgo dependency. Was it added by mistake initially, or was there a specific reason for its removal?

Yes, I removed the CGO build tag, CGO I not required to build Filebeat any more.

Not long ago (before https://github.com/elastic/beats/pull/40061 was merged) the journald input used `github.com/coreos/go-systemd/v22/sdjournal` that required CGO, hence Filebeat required CGO when build with the jouranld input (there were build tags to configure it, a simple `go build .` would not include the journald input).

Nowadays CGO is not needed any more, but some build tags were forgotten and that was not caught on CI. The AMD64 builds do not seem to be affected, only the ARM ones.

**Review by mauri870 — APPROVED** [review]

**Pull request merged**
