### PR TITLE
[Heartbeat] Remove synthetics support for ironbank

### PR DESCRIPTION
**Pull request by emilioalvap**
## What does this PR do?

Remove Synthetics support and files from ironbank build. 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## How to test this PR locally

Follow original PR to enable ironbank instructions: https://github.com/elastic/beats/pull/32954.

### CODE REVIEW

**Review by cmacknz — APPROVED** [review]

**Review by andrewvc — APPROVED** [review]
LGTM

**Review by pierrehilbert — APPROVED** [review]

**Comment by v1v** [comment]
I've just contributed to your PR and deleted some other files related to:
- https://github.com/elastic/beats/pull/32982
- https://github.com/elastic/beats/pull/32976
- https://github.com/elastic/beats/pull/32954

In addition, I triggered the package pipeline with the above-command, and there is an extra requirement to delete those artifacts from the Unified Release, let me put a PR for that.

I also included all the backport labels

**Pull request merged**
