### PR TITLE
Update aws-sdk-go to v1.51.14

### PR DESCRIPTION
**Pull request by michel-laterman**
Update github.com/aws/aws-sdk-go to v1.51.14

### CODE REVIEW

**Review by cmacknz — APPROVED** [review]

**Review by belimawr — APPROVED** [review]

**Comment by michel-laterman** [comment]
buildkite test this

**Comment by michel-laterman** [comment]
buildkite test this

**Comment by cmacknz** [comment]
Buildkite isn't the problem, we aren't fully switched over to buildkite yet. The jobs run but are informational only.

**Comment by michel-laterman** [comment]
Waiting for test failure to be addressed by https://github.com/elastic/beats/pull/38991

**Pull request merged**
