### PR TITLE
[Heartbeat] Separate http req per task

### PR DESCRIPTION
**Pull request by andrewvc**
This is an attempt to fix the race reported in #29580 by instantiating a separate http request per HTTP task. The theory being that the HTTP library modifies the headers and that the req object is not safe to share.

This has passed manual testing using `mode: all` against endpoints with multiple A records. 

Tests are not included here due to the tricky nature of testing here, but we will do so in a follow-up

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by andrewvc** [comment]
Gist of a stacktrace I captured when I repro'd it https://gist.github.com/andrewvc/977e17c7d9a2863c1432aa120e9c4ca0

**Comment by andrewvc** [comment]
Seems like https://github.com/elastic/beats/pull/27509 is what broke this after analysis

**Review by justinkambic — APPROVED** [review]
Tested this locally with repeatable results and it works well. Code seems fine.

LGTM.

**Comment by andrewvc** [comment]
@Mergifyio backport 7.16

**Pull request merged**
