### PR TITLE
Remove _meta/kibana.generated symlink

### PR DESCRIPTION
**Pull request by cwurm**
https://github.com/elastic/beats/pull/9546 introduced a symlink from `_meta/kibana.generated` to `build/kibana` so Auditbeat remains backwards compatible with the other Beats (Auditbeat is already using the first as a location for all its Kibana objects, while the other Beats are still using the latter).

This introduced a bug, where objects would be included in the dashboard ZIP file with the wrong path (https://github.com/elastic/beats/issues/9785).

One way of fixing this would have been to double down on symlinks and change just one line in `addFileToZip`. But with https://github.com/elastic/beats/pull/9842/ about to change all Beats to use the new `build/kibana` I thought it better to just remove the symlink capability altogether and instead if-else between the two possible locations based on whether they exist or not. https://github.com/elastic/beats/pull/9842/ will then change all of that - at least in `master` - once it's merged.

Fixes https://github.com/elastic/beats/issues/9785.

### CODE REVIEW

**Comment by andrewkroh** [comment]
@cwurm I was also looking at this and came to a similar solution (see [dashboards.patch](https://github.com/elastic/beats/files/2727904/dashboards.patch.txt)). But with few differences:

- include x-pack dashboards (like suricata)
- prefer the build/kibana
- error if neither exists

Do you want to incorporate some of this with your PR?

**Comment by cwurm** [comment]
@andrewkroh Thanks, definitely! I've pushed a new commit.

**Comment by ruflin** [comment]
@cwurm This should not have been merged. It seems this change caused the failure for the test_ml jobs. The error is:

```
2019-01-07T15:30:04.349Z	ERROR	instance/beat.go:907	Exiting: Error importing Kibana dashboards: fail to import the dashboards in Kibana: Error importing directory /go/src/github.com/elastic/beats/filebeat/_meta/kibana.generated: No directory /go/src/github.com/elastic/beats/filebeat/_meta/kibana.generated/6
```

I assume this will also affect the backports?

**Comment by cwurm** [comment]
@ruflin Ah you're right, sorry. Thanks for fixing it in master.

> I assume this will also affect the backports?

It shouldn't. In 6.x and 6.6 Filebeat is still using `_meta/kibana.generated`, so the test code works. Only in master did it change to `build/kibana`, but the test did not but was still working because of the symlink.

CI for 6.x and 6.6 look good for Filebeat.

**Pull request merged**
