### PR TITLE
[netflow]: disable event normalisation

### PR DESCRIPTION
**Pull request by pkoutsovasilis**
## Proposed commit message

This PR introduces the following:
* CustomTypeCodecs which essentially allows the input to define custom Marshal functions for any given type (PS: [this fix](https://github.com/elastic/go-structform/pull/46) was required). 
* Disable event normalisation for netflow input and define a custom Marshal function for net.IP (look below in the screenshots)
* Adds Kibana service in the docker-compose.yml provisioned for the needs of x-pack/filebeat integration tests
* Extend netflow integration test to install netflow Kibana package and thus prevent similar issues as [this one](https://github.com/elastic/beats/issues/38703). 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Disruptive User Impact

N/A 

## Author's Checklist

N/A 

## Related issues

- Closes https://github.com/elastic/beats/issues/37764

## Use cases

N/A

## Screenshots

CPU profile with event normalisation enabled:
with_normalisation

CPU profile with event normalisation disabled:
without_normalisation

As you can see between the two screenshots the "GenericEventConverter" and the respective CPU time are completely gone from the run with event normalisation disabled

## Logs

N/A

### CODE REVIEW

**Comment by pkoutsovasilis** [comment]
`filebeat: Win 2022 Unit Tests` are failing because of these https://github.com/elastic/beats/issues/40237, https://github.com/elastic/beats/issues/39756

**Review by andrewkroh — APPROVED** [review]
I applaud your conservative approach to avoid the possibility of disrupting other libbeat users with registration of a global net.IP encoder. Personally I probably would registered in globally 😄 , but this the new plumbing looks good.

**Comment by VihasMakwana** [comment]
> filebeat: Win 2022 Unit Tests are failing because of these https://github.com/elastic/beats/issues/40237, https://github.com/elastic/beats/issues/39756

@pkoutsovasilis I've merged the test case fix PR. Can you merge main and retry?

**Comment by pkoutsovasilis** [comment]
> > filebeat: Win 2022 Unit Tests are failing because of these #40237, #39756
> 
> @pkoutsovasilis I've merged the test case fix PR. Can you merge main and retry?

ty @VihasMakwana for the fix. Indeed I can see that the previously failed CI steps are now resolved

**Comment by cmacknz** [comment]
FYI @faec since I see this touching some of the early event encoding hooks.

**Comment by pkoutsovasilis** [comment]
@cmacknz @faec 👋 next week I am on PTO, so would it be possible to have this reviewed today and thus I will be able to provide fixes to your comments or merge this if you don't have any comments?

**Comment by pierrehilbert** [comment]
@cmacknz is out today but it should be possible for @faec to have a look here.

**Comment by pkoutsovasilis** [comment]
@pierrehilbert gentle reminder 🙂

**Review by faec — CHANGES_REQUESTED** [review]
I have some big-picture concerns about how this affects pipeline encoding, if I'm misunderstanding something maybe you can explain the choices:

- As far as the queue API, early encoding should be a black box. We shouldn't be adding new parameters to `EncoderFactory`. The queue doesn't need to know anything about how the output is encoding its data.
- Early encoding is _not_ supported by non-ES outputs (yet). I'm not sure the intended scope of your changes, but anything that latches onto the early encoding mechanism will only be visible in the Elasticsearch output. (If this is _supposed_ to only affect the ES output, then the functional change should be in the ES output and its encoder only, it shouldn't leak parameters into the encoding interface that may be used by other outputs.
- It looks like this is being done so the input knows how to properly emit more data types as valid json? In that case, unsupported field types should be removed in the input before the event's `Publish` call. If there's a good reason this isn't possible we could think about doing it in `pipeline.client`, but it should probably still be before processor handling since processors should be able to access affected fields.

**Comment by pkoutsovasilis** [comment]
@faec given that I have seen the queue code and how tightly coupled it is with the queue.Encoder considering this as a black box is kinda blurry to me. However, I can coop with the notion do not intervene with it, it a queue internal encoder that isn't meant for public API consumption

**Comment by faec** [comment]
To be clear, I wasn't saying this PR should be deleted, just that it needs changes. The encoder should be a black box to the queue (the encoder/factory types are just providing a way to construct an opaque callback owned by the output), but that doesn't mean you can't make changes that affect encoding, just that the queue interfaces aren't where the hooks should go.

**Pull request closed without merging**
