### PR TITLE
Packetbeat, mysql proto, add \r to trim SQLs captured from app runnin…

### PR DESCRIPTION
**Pull request by timesking**
Packetbeat
Mysql proto

add \r to trim SQLs captured from app running on Windows server. Otherwise method extracted including \r, which is problem. e.g. "SELECT\r\n\t1".

### CODE REVIEW

**Comment by karmi** [comment]
Hi @timesking, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/beats/pull/5572.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by timesking** [comment]
@karmi I added that email now.

**Comment by ruflin** [comment]
@timesking Thanks for the contribution. It would be great to have some tests to verify this change.

**Comment by timesking** [comment]
@ruflin I saw mysql_test.go including some pcap binary data. Do you mean add a test in that file, also use pcap as input data?

**Comment by ruflin** [comment]
@timesking Whatever works best. But I think @urso is probably better to comment here.

**Comment by urso** [comment]
Change looks reasonable.

Please add a system test to [packetbeat/tests/system](https://github.com/elastic/beats/tree/master/packetbeat/tests/system).

Also add a changelog entry to Changelog.asciidoc

**Comment by timesking** [comment]
@urso Sure, I will learn how to add that python test case.

**Comment by timesking** [comment]
@urso All passed.

**Comment by ruflin** [comment]
jenkins, test it

**Comment by urso** [comment]
@timesking The tests are fine. I checked failures and non are related to your PR.

can you also add a Changelog entry (to Changelog.asciidoc) about fixing newlines on windows? Also rebase before doing so, so not to have merge conflicts on the changelog file.

**Comment by timesking** [comment]
@urso the changeslog has been added, and all changes rebased on master

**Comment by ruflin** [comment]
@timesking I can't see the changelog entry. Did it get lost during rebasing? Can you rebase on master again?

**Comment by timesking** [comment]
@ruflin Sorry for that, I rebased again, fixed missing changelog

**Comment by urso** [comment]
Merged. Thanks for contributing the fix!

**Pull request merged**
