### PR TITLE
Cherry-pick #10593 to 7.0: Fix waiting for new events

### PR DESCRIPTION
**Pull request by kvch**
Cherry-pick of PR #10593 to 7.0 branch. Original message: 

- [x] Adding more syscalls to the whitelist in `libbeat`
 I have removed the seccomp policy of `journalbeat`. Four new syscalls has been added to the common policy instead: `fstatfs`, `getrlimit`, `ppoll` and `splice`.
- [x] Eliminate possible deadlock when closing the client
- [x] Previously, `journalbeat` was unable to read new entries from the journal after it has been started. Now it is fixed, and the reader code is much simpler now.
- [x] updated vendored `github.com/coreos/go-systemd/sdjournal` to latest release (no changes)

### CODE REVIEW

**Comment by ph** [comment]
This will need a rebase, the failures doesn't seems related to this PR intend.

I see a docker issues with metricbeat and also on windows.

**Comment by ph** [comment]
One thing that I wonder here, right now we do define a set of seccomp permission that are valid for all the beats maybe we should leave it to the beats to define the list of syscall it should allow. On the other hand we want to merge Journalbeat into Filebeat so maybe it's not necessary.

**Comment by kvch** [comment]
At first I added a custom seccomp policy to Journalbeat, but as Andrew Kroh pointed out, these syscalls do not do anything special. So it is simpler to add them to the common list.

**Comment by kvch** [comment]
Failing tests are unrelated.

**Pull request merged**
