### PR TITLE
[Ingest Manager] Make TestFleetGateway tests faster

### PR DESCRIPTION
**Pull request by michalpristas**
## What does this PR do?

The reason for failures might be that when CI is overloaded spinning up goroutines may take some time. so i reduced them where it was possible. 

Other change here is in timeouts and sleep times. Reduced to fraction of seconds. I've been running this on darwin/linux env and execution of this test set went down from `4.x` seconds to `0.7` seconds.

When i executed in a CPU restricted VM it went down from `9-10` seconds to `3`. 

Not great but code wise i dont think there's anything wrong with the test it just take time which might result in timeouts when VM is restricted on resources.

## Why is it important?

Testing

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Review by ph — APPROVED** [review]
I think you have a good point here @michalpristas  have you run the test multiple times on CI?
Change looks good to me, but I haven't run that in a loop, in the failure job it was clearly a timeout of the test?

**Comment by michalpristas** [comment]
@ph i want to have multiple runs to make sure as repro is not that simple

**Comment by michalpristas** [comment]
Jenkins test this please

**Review by ph — APPROVED** [review]
changes LGTM,

**Pull request merged**
