### PR TITLE
[DOCS] Clarify required privileges for Beats users

### PR DESCRIPTION
**Pull request by dedemorton**
Updates security docs to show more restrictive roles and clarify the division of responsibilities across different roles. Also changed organization because the duplication for each user goal made the content harder to read.

The docs look like this when built:

Updated 7/17: 

image

### CODE REVIEW

**Comment by dedemorton** [comment]
Fixes doc issues identified in https://github.com/elastic/beats/issues/10241

**Comment by urso** [comment]
TBH, I find the tables a little confusing, as it looks like that the setup role depends on other roles for example. I don't think we can roles depend on other roles, which makes it look like we cram roles and user configs together in a table. But if you are new to the stack, you might not be aware that you have to create a setup role and apply a many roles to the admin user.

How about splitting up the document into roles and users as I did in my testing. We guide the user to always create a number of good roles, like `beats_monitoring` (btw. we have no filebeat_system role, but a beats_system role I think), `filebeat_setup`, `filebeat_writer`, `filebeat_reader`. How about including screenshots or ES API calls for people who want to automatize this step?

The `filebeat_writer` is indeed somewhat special, and would require different settings based on use case. In my tests I found 3 variations of the writer role:
1. `beats_writer`: required for writing with beats default settings and ILM enabled
2. `beats_indexer`: variant of `beats_writer` with trimmed down permissions and better separation of responsibilites.
3. `beats_index_writer`: required for writing with beats default settings and ILM disabled

Once we have the roles, we talk about users scenarios/responsibilities specifically and which roles they would need (as a combination of roles need to be assigned).
1. admin user requires roles: filebeat_setup, kibana_user, and beats_admin (if CM is used). Not sure about ingest_admin role
2. Users wanting to index will need the filebeat_writer role only. If users are allowed to see monitoring info, they will also need the beats_system role?
3. Users allowed to maintain dashboards and visualizations need: filebeat_reader, kibana_user
4. Users only allows to consume data via Kibana or ES, but not modify anything will need: filebeat_reader, kibana_dashboard_only_user

Again we can provide screenshots/API calls for the later.

Hmm... thinking about it, it's a little duplicate info, but this would split the process into actually required steps as they need to be executed by the user (mix doc and tutorial style?). Having screenshots/scripts also streamlines the experience, as users will not have to learn about ES security in detail in beforehand, assuming we can provide best practices and easy getting started experience. WDYT?

**Comment by urso** [comment]
Sorry, got carryed away a little :)

The changes here are definitely and improvement and we should get them in nowish.

I only have 2 remarks:
1. read privilege on `filebeat-*` should not be required on setup role. We already have manage
2. In the writer special case role set `setup.ilm.enabled: true` or `false`. This depends on the original setup routine. The default is `auto`, which means we don't know if it's enabled or disabled for sure. If something changes in the cluster the wrong index might be used. Doing some more testing, I can confirm that the minimzed permissions use case still requires `create_index` if ILM is disabled.

**Comment by dedemorton** [comment]
@urso Your first point is valid. If I had my way, I would simply list the privileges that are required and leave it up to the user to create/use whatever roles they want. But that's complicated because we want users to use pre-built roles, when possible. However, we don't have pre-built roles that encompass all privileges needed for Beats. Meanwhile some features, like central management, check for a specific role rather than privilege. So I've settled on a compromise.

I'll tweak the wording a bit to make it clear that the user needs to create roles + assign some pre-built roles to get the full set of privileges needed for Beats, but I'd like to keep the reference-style format because it's easier to scan (important for experienced users and readers who prefer to skim). Reference content is also easier to keep up-to-date. Documenting every possible scenario (and including screen shots) can be very time consuming to maintain over time as we add support for new features.

For users who want step-by-step instructions, it would be nice to have a tutorial that walks them through a typical scenario (maybe with variations for ILM and no ILM).

It's worth nothing here, though, that we already have a basic tutorial in the stack overview that covers security (the example used is Metricbeat): https://www.elastic.co/guide/en/elastic-stack-overview/current/security-getting-started.html. This tutorial is a follow-up to the basic tutorial that we provide here: https://www.elastic.co/guide/en/elastic-stack-get-started/current/get-started-elastic-stack.html. You'll notice that the tutorial is already stale because it assumes daily indices (was written before ILM became the default for basic). But then, of course, OSS users *will* be using daily indices. As you can see, scenario-based docs get very complicated to write and maintain when the defaults are dependent on which distribution you've installed.

**Comment by dedemorton** [comment]
@urso Re your comment:
> read privilege on filebeat-* should not be required on setup role. We already have manage

When I run `./filebeat setup --machine-learning -e` with `manage` but not `read` on `filebeat-*`, I get:

```
Rhodas-MBP:filebeat-7.2.0-darwin-x86_64$ ./filebeat setup --machine-learning
Exiting: 1 error: Error setting up ML for apache_ecs: 5 errors: [security_exception] Cannot create datafeed [datafeed-filebeat-apache_ecs-access-visitor_rate_ecs] because user filebeat_setup lacks permissions on the indices: {"filebeat-*":{"indices:data/read/search":false}}; [security_exception] Cannot create datafeed [datafeed-filebeat-apache_ecs-access-status_code_rate_ecs] because user filebeat_setup lacks permissions on the indices: {"filebeat-*":{"indices:data/read/search":false}}; [security_exception] Cannot create datafeed [datafeed-filebeat-apache_ecs-access-source_ip_url_count_ecs] because user filebeat_setup lacks permissions on the indices: {"filebeat-*":{"indices:data/read/search":false}}; [security_exception] Cannot create datafeed [datafeed-filebeat-apache_ecs-access-source_ip_request_rate_ecs] because user filebeat_setup lacks permissions on the indices: {"filebeat-*":{"indices:data/read/search":false}}; [security_exception] Cannot create datafeed [datafeed-filebeat-apache_ecs-access-low_request_rate_ecs] because user filebeat_setup lacks permissions on the indices: {"filebeat-*":{"indices:data/read/search":false}}

When I add `read` on `filebeat-*`, I get:

Rhodas-MBP:filebeat-7.2.0-darwin-x86_64$ ./filebeat setup --machine-learning
Loaded machine learning job configurations
Rhodas-MBP:filebeat-7.2.0-darwin-x86_64$
```

**Comment by urso** [comment]
> When I run ./filebeat setup --machine-learning -e with manage but not read on filebeat-*, I get:

Oh, right, I had ML disabled, cause I did run into some other issues with it. In this case `read` is required. It's funny, though, as read is a subset of manage. I wonder where this is enforced.

**Pull request merged**
