### PR TITLE
Include missing reference to syslog processor docs

### PR DESCRIPTION
**Pull request by taylor-swanson**
## What does this PR do?

Including missing reference to syslog processor documentation.

## Why is it important?

Link to syslog processor was missing from processors list. 

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- [x] I have made corresponding changes to the documentation
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by andrewkroh** [comment]
run elasticsearch-ci/docs

**Comment by taylor-swanson** [comment]
The docs are failing to build because of this:
```
INFO:build_docs:asciidoctor: WARNING: invalid reference: http-endpoint
```

This error, at least, is coming from `functionbeat` and it's due to `http-endpoint` not being included. I don't really know a good way to fix this, any suggestions?

**Comment by dedemorton** [comment]
So just to confirm...since Functionbeat is deployed to a serverless environment, the syslog processor is not relevant, correct?

**Comment by andrewkroh** [comment]
> So just to confirm...since Functionbeat is deployed to a serverless environment, the syslog processor is not relevant, correct?

The syslog processor was included in a common file that I believe is used by functionbeat. This means that it will be present is Functionbeat along with all the other processors listed in this file.

https://github.com/elastic/beats/blob/376a87f3bbd8628807f98c977ed01fd424fd60fa/libbeat/cmd/instance/imports_common.go#L42

**Comment by dedemorton** [comment]
To fix the doc error, you need to do one of the following:

* Conditionally remove the section about metrics [here](https://github.com/elastic/beats/blob/main/libbeat/processors/syslog/docs/syslog.asciidoc#metrics) (that is, if this configuration is NOT supported by Functionbeat).  I can push a commit if this is how you want to proceed.

* Get the docs about the HTTP Endpoint building by adding an include statement to the file here: https://github.com/elastic/beats/blob/main/x-pack/functionbeat/docs/configuring-howto.asciidoc. Again, I can help you out. Just need to know which approach makes sense. I don't understand how the HTTP Endpoint config works with functions deployed in a serverless environment, but it does seem to be in the functionbeat.reference.yml, so I'm confused about whether we need to include the config details in the Functionbeat docs.

**Comment by dedemorton** [comment]
@taylor-swanson Spoke with Andrew offline and we decided to conditionally exclude the section causing the error. I hope you don't mind me pushing to your fork. The change should fix the doc build issue.

**Review by andrewkroh — APPROVED** [review]

**Comment by andrewkroh** [comment]
@Mergifyio update

**Pull request merged**
