### PR TITLE
[Metricbeat]Fix container reference pattern at docker module

### PR DESCRIPTION
**Pull request by odacremolbap**
Revisiting docker module as there are some other reference pattern that could be pushing wrong data when multiple _items_ are iterated.

ref: https://github.com/elastic/beats/pull/14825
issue: https://github.com/elastic/beats/issues/14893

### CODE REVIEW

**Comment by odacremolbap** [comment]
thanks @mtojek 

I'll try to find time to improve this in the next days before next code freeze.

**Comment by odacremolbap** [comment]
jenkins test this, please

**Comment by odacremolbap** [comment]
@mtojek may I ask for your review again?

converted all occurrences found f the loop pattern to:
- a safe pattern, allowing references to the original object when read only structures are used
- an efficient usage, avoiding to create lots of new objects at every fetch iteration

**Comment by mtojek** [comment]
_(not blocking off course)_

I'm not convinced if such optimization level is required as it impacts readability. The source starts looking like a C code...

**Comment by odacremolbap** [comment]
> I'm not convinced if such optimization level is required as it impacts readability. The source starts looking like a C code...

I ack your concern.

I'm not aware of complaints on performance, all this changes came from a different issue related to references to the loop variable being incorrectly used. If you think the tradeoff between performance and readability is unbalanced I'm happy to go back to using the loop values instead of the c-like index of the array.

Waiting for your opinions
@mtojek @exekias

**Comment by odacremolbap** [comment]
closing, if using arguments by value there is no need to change anything

**Pull request closed without merging**
