### PR TITLE
[gcp/billing] always quote table name identifier

### PR DESCRIPTION
**Pull request by endorama**
## What does this PR do?

Extract query generation and use quoted identifiers when querying BigQuery from GCP Billing module.

## Why is it important?

When users specify a table name containing special characters (not `A-Z a-z _`) the query would fail.

This is because the code is using an Unquoted identifier for the table name that may contain only a limited characters set.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ] This change wrap the entire identifier, this is the expected usage from my understanding. Is it?

## Related issues

- Closes https://github.com/elastic/beats/issues/26855

### CODE REVIEW

**Comment by endorama** [comment]
@kaiyan-sheng does this change require an entry in the `CHANGELOG`? (Feels like yes but worth checking)

**Comment by kaiyan-sheng** [comment]
> @kaiyan-sheng does this change require an entry in the `CHANGELOG`? (Feels like yes but worth checking)

Yep I think this deserves a changelog entry under bugs.

**Comment by endorama** [comment]
@kaiyan-sheng May you guide me in doing that? Which file should I edit? Which version will this bugfix be part of?

**Comment by kaiyan-sheng** [comment]
@endorama Of course! So changelog for new features and bug fixes you think should be exposed to users will go into `beats/CHANGELOG.next.asciidoc`. Since this is a bug fix in Metricbeat, the changelog entry will go in here: https://github.com/elastic/beats/blame/master/CHANGELOG.next.asciidoc#L412

**Review by kaiyan-sheng — APPROVED** [review]
I tested this PR and it works with my gcp billing account. But the table name doesn't contain special characters.

**Comment by endorama** [comment]
@kaiyan-sheng CHANGELOG updated. I was wondering if this change should be backported to `7.x`?

**Comment by kaiyan-sheng** [comment]
@endorama LGTM. Thanks for the fix! Yes this will need to be backported into 7.x and also 7.14 branch since it's a bug fix.

**Pull request merged**
