### PR TITLE
Feature: F5 ASM filebeat module

### PR DESCRIPTION
**Pull request by hazcod**
Enhancement

## What does this PR do?
This adds the f5/asm fileset, which parses ASM logs for F5.

## Why is it important?
F5 WAF logs are important in a SIEM scenario.

## Checklist
- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- closes https://github.com/elastic/beats/issues/20800

### CODE REVIEW

**Comment by hazcod** [comment]
Jenkins test this please.

**Comment by P1llus** [comment]
After some discussion with @hazcod I will be helping out with a few commits to fix some conflicts and prepare some documentation + testing of the module, I will mark this as ready for review when the preparations are done.

**Review by P1llus — APPROVED** [review]
Approving to kick off CI/CD process

**Comment by P1llus** [comment]
jenkins test please

**Comment by P1llus** [comment]
@hazcod I quickly looked through this module and there is a few things that is still needed for this.

Currently I could not find any documentation matching the format in the test logs, is this a custom format configured? I saw in the documentation for ASM that there is a remote syslog option, which seems to use a different format than this.

Would you be able to maybe add some more test data? Maybe some different actions (allow, deny, detect, prevent etc)?

**Comment by hazcod** [comment]
👍🏻

**Comment by andrewkroh** [comment]
Thanks for your time on this @hazcod. We're working on migrating the existing modules into [Fleet](https://www.elastic.co/guide/en/fleet/current/fleet-overview.html). And we want to create new modules as Fleet integrations rather than Filebeat modules. I've created an issue to track adding your contribution as a Fleet integration in https://github.com/elastic/integrations/issues/976. So I'm going to close this PR as our intent is to migrate/recreate it in elastic/integrations.

If you are interested in contributing there, we have a guide at https://github.com/elastic/integrations/blob/master/CONTRIBUTING.md.

**Pull request closed without merging**
