### PR TITLE
ironbank: move to ubi9

### PR DESCRIPTION
**Pull request by v1v**
> ⚠️ when merged then there are some changes required in the Unified Release, there is already an open PR, and a link to this one should be visible within this PR. Backports are also required. This is a chicken/egg, so DRA will fail until changes are in both systems.

https://github.com/elastic/beats/pull/36797 partially changed the `ubi` version to `ubi9` but there were some other changes required in the packaging itself and the base docker images.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by pazone — APPROVED** [review]

**Comment by v1v** [comment]
I managed to reproduce the issue locally:

```
=> [internal] load metadata for registry.access.redhat.com/ubi9/ubi-minimal:9.2                                                                                                                                                                0.0s
 => [internal] load metadata for docker.io/arm64v8/ubuntu:20.04                                                                                                                                                                                 1.4s
 => CACHED [stage-1  1/12] FROM registry.access.redhat.com/ubi9/ubi-minimal:9.2                                                                                                                                                                 0.0s
 => CACHED [home 1/3] FROM docker.io/arm64v8/ubuntu:20.04@sha256:a80d11b67ef30474bcccab048020ee25aee659c4caaca70794867deba5d392b6                                                                                                               0.0s
 => => resolve docker.io/arm64v8/ubuntu:20.04@sha256:a80d11b67ef30474bcccab048020ee25aee659c4caaca70794867deba5d392b6                                                                                                                           0.0s
 => [internal] load build context                                                                                                                                                                                                               3.3s
 => => transferring context: 173.79MB                                                                                                                                                                                                           3.2s
 => [stage-1  2/12] RUN microdnf -y update &&     microdnf install findutils shadow-utils &&     microdnf clean all                                                                                                                           574.4s
 => => #  Reinstalling:      0 packages                                                                                                                                                                                                             
 => => #  Upgrading:         0 packages                                                                                                                                                                                                             
 => => #  Obsoleting:        0 packages                                                                                                                                                                                                             
 => => #  Removing:          0 packages                                                                                                                                                                                                             
 => => #  Downgrading:       0 packages                                                                                                                                                                                                             
 => => # Is this ok [y/N]:                                                                                                                                                                                                                          
 => [home 2/3] COPY beat /usr/share/filebeat                                                                                                                                                                                                    0.6s
 => [home 3/3] RUN mkdir -p /usr/share/filebeat/data /usr/share/filebeat/logs &&     chown -R root:root /usr/share/filebeat &&     find /usr/share/filebeat -type d -exec chmod 0755 {} ; &&     find /usr/share/filebeat -type f -exec chmod   2.8s

```

using:

```bash
$ PLATFORMS=linux/arm64 PACKAGES=docker mage package
```

For some reason there is a downgrade and it's prompting for a confirmation `is this ok [y/N]:`

**Comment by v1v** [comment]
Artifacts have been uploaded to the relevant Google bucket:

image

```bash
$ gsutil ls gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/                                    
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-aarch64.rpm
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-aarch64.rpm.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-amd64.deb
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-amd64.deb.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-arm64.deb
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-arm64.deb.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-darwin-aarch64.tar.gz
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-darwin-aarch64.tar.gz.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-darwin-x86_64.tar.gz
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-darwin-x86_64.tar.gz.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-linux-amd64.docker.tar.gz
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-linux-amd64.docker.tar.gz.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-linux-arm64.docker.tar.gz
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-linux-arm64.docker.tar.gz.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-linux-arm64.tar.gz
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-linux-arm64.tar.gz.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-linux-x86_64.tar.gz
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-linux-x86_64.tar.gz.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-windows-x86_64.zip
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-windows-x86_64.zip.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-x86_64.rpm
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-8.12.0-SNAPSHOT-x86_64.rpm.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-ironbank-8.12.0-SNAPSHOT-docker-build-context.tar.gz
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-ironbank-8.12.0-SNAPSHOT-docker-build-context.tar.gz.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-aarch64.rpm
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-aarch64.rpm.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-amd64.deb
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-amd64.deb.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-arm64.deb
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-arm64.deb.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-darwin-aarch64.tar.gz
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-darwin-aarch64.tar.gz.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-darwin-x86_64.tar.gz
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-darwin-x86_64.tar.gz.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-linux-amd64.docker.tar.gz
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-linux-amd64.docker.tar.gz.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-linux-arm64.docker.tar.gz
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-linux-arm64.docker.tar.gz.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-linux-arm64.tar.gz
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-linux-arm64.tar.gz.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-linux-x86_64.tar.gz
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-linux-x86_64.tar.gz.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-windows-x86_64.zip
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-windows-x86_64.zip.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-x86_64.rpm
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-oss-8.12.0-SNAPSHOT-x86_64.rpm.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-ubi9-8.12.0-SNAPSHOT-linux-amd64.docker.tar.gz
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-ubi9-8.12.0-SNAPSHOT-linux-amd64.docker.tar.gz.sha512
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-ubi9-8.12.0-SNAPSHOT-linux-arm64.docker.tar.gz
gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-ubi9-8.12.0-SNAPSHOT-linux-arm64.docker.tar.gz.sha512
```


```
$ gsutil cp gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-ubi9-8.12.0-SNAPSHOT-linux-amd64.docker.tar.gz .

Copying gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-ubi9-8.12.0-SNAPSHOT-linux-amd64.docker.tar.gz...
| [1 files][109.2 MiB/109.2 MiB]                                                

$ tar xvzf filebeat-ubi9-8.12.0-SNAPSHOT-linux-amd64.docker.tar.gz
$ grep -R ubi9
./repositories:{"docker.elastic.co/beats/filebeat-ubi9":{"8.12.0-SNAPSHOT":"4321910b89d206d4047a48ad67b1e89ca73b66fd9343dbeb8737ac674c0cf239"}}
...
```

```bash
$ gsutil cp gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-ironbank-8.12.0-SNAPSHOT-docker-build-context.tar.gz .
trarCopying gs://beats-ci-artifacts/beats/pull-requests/pr-37017/filebeat/filebeat-ironbank-8.12.0-SNAPSHOT-docker-build-context.tar.gz...
/ [1 files][  8.8 KiB/  8.8 KiB]                                                
Operation completed over 1 objects/8.8 KiB.         
$ tar xvzf filebeat-ironbank-8.12.0-SNAPSHOT-docker-build-context.tar.gz 
x Dockerfile
x LICENSE
x README.md
x hardening_manifest.yaml
$ grep -R ubi9
./Dockerfile:ARG BASE_IMAGE=redhat/ubi/ubi9
./hardening_manifest.yaml:  BASE_IMAGE: "redhat/ubi/ubi9"
```

**Review by pierrehilbert — APPROVED** [review]
Thx @v1v

**Pull request merged**
