### PR TITLE
[x-pack/filebeat/module/cisco] Fix pipline for nexus type

### PR DESCRIPTION
**Pull request by mib1185**
## What does this PR do?
Add a missing blank before the payload is extracted from the message
This can also be back ported into 7.17 (_if it is allowed_)?

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

- setup filebeat to use the cisco module with the nexus fileset enabled

/etc/filebeat/modules.d/cisco.yml

```yaml
- module: cisco
  nexus:
    var.syslog_host: 0.0.0.0
    var.syslog_port: 9506
    var.debug: true
```

- start filebeat in forground with enabled debug

```
filebeat -e -d "*"
```

- simulate cisco nexus syslog message

```
echo -n "$(date +'%Y %b %d %H:%M:%S') Berlin: %ETHPORT-5-IF_HARDWARE: Interface Ethernet1/9, hardware type changed to QSA" | nc -s x.x.x.x -u localhost 9506
```

result prior this PR
```
[...]
2022-10-18T15:13:08.053+0200    WARN    [processor.javascript]  console/console.go:52   linear_select trying entry 5
2022-10-18T15:13:08.053+0200    DEBUG   [processor.javascript]  console/console.go:48   dissect   OK: HEADER#5:0008 field:message
2022-10-18T15:13:08.053+0200    DEBUG   [processor.javascript]  console/console.go:48           expr: <<%{hfld14->} %{hfld15->} %{hfld16->} %{hfld17->} %{timezone}: %%{hfld19}-%{severity}-%{messageid}:%{payload}>>
2022-10-18T15:13:08.053+0200    DEBUG   [processor.javascript]  console/console.go:48          input: <<2022 Oct 18 15:13:08 Berlin: %ETHPORT-5-IF_HARDWARE: Interface Ethernet1/9, hardware type changed to QSA>>
2022-10-18T15:13:08.053+0200    WARN    [processor.javascript]  console/console.go:52   linear_select matched entry 5
2022-10-18T15:13:08.053+0200    INFO    [processor.javascript]  console/console.go:50   msgid_select: matched key=IF_HARDWARE
2022-10-18T15:13:08.053+0200    DEBUG   [processor.javascript]  console/console.go:48   dissect fail: MESSAGE#224:IF_SFP_WARNING field:nwparser.payload
2022-10-18T15:13:08.053+0200    DEBUG   [processor.javascript]  console/console.go:48           expr: <<Interface %{interface}, %{event_description}>>
2022-10-18T15:13:08.053+0200    DEBUG   [processor.javascript]  console/console.go:48          input: << Interface Ethernet1/9, hardware type changed to QSA>>
```

result now
```
[...]
2022-10-18T16:24:18.797+0200    WARN    [processor.javascript]  console/console.go:52   linear_select trying entry 5
2022-10-18T16:24:18.797+0200    DEBUG   [processor.javascript]  console/console.go:48   dissect   OK: HEADER#5:0008 field:message
2022-10-18T16:24:18.798+0200    DEBUG   [processor.javascript]  console/console.go:48           expr: <<%{hfld14->} %{hfld15->} %{hfld16->} %{hfld17->} %{timezone}: %%{hfld19}-%{severity}-%{messageid}: %{payload}>>
2022-10-18T16:24:18.798+0200    DEBUG   [processor.javascript]  console/console.go:48          input: <<2022 Oct 18 16:24:18 Berlin: %ETHPORT-5-IF_HARDWARE: Interface Ethernet1/9, hardware type changed to QSA>>
2022-10-18T16:24:18.798+0200    WARN    [processor.javascript]  console/console.go:52   linear_select matched entry 5
2022-10-18T16:24:18.798+0200    INFO    [processor.javascript]  console/console.go:50   msgid_select: matched key=IF_HARDWARE
2022-10-18T16:24:18.798+0200    DEBUG   [processor.javascript]  console/console.go:48   dissect   OK: MESSAGE#224:IF_SFP_WARNING field:nwparser.payload
2022-10-18T16:24:18.798+0200    DEBUG   [processor.javascript]  console/console.go:48           expr: <<Interface %{interface}, %{event_description}>>
2022-10-18T16:24:18.798+0200    DEBUG   [processor.javascript]  console/console.go:48          input: <<Interface Ethernet1/9, hardware type changed to QSA>>

```

## Related issues

-

### CODE REVIEW

**Comment by mib1185** [comment]
Hi @efd6 I've already signed the cla via the the docusign link above. Not sure if something is missing or I have to do any further steps?

**Comment by efd6** [comment]
I can see your GH handle in the CLA checker, so can you check that the author email address matches the email that you used to sign the CLA?

**Comment by mib1185** [comment]
sorry my bad ... have repushed the commit with the correct user/mail author

**Comment by efd6** [comment]
@mib1185 This looks OK to me, but we don't have any test inputs to run against. Are you able to provide some sanitised log lines that we could include in testing?

**Comment by mib1185** [comment]
@efd6 sure, will collect some data and provide them soon

**Comment by mib1185** [comment]
here some example data including syslog priority tag at the beginning
```
<181>2022 Oct 17 10:27:35 Berlin: %NOHMS-2-NOHMS_ENV_FEX_ONLINE: FEX-105 On-line
<181>2022 Oct 17 10:27:36 Berlin: %PFMA-2-FEX_PS_FOUND: Fex 105 Power Supply 1 found (Serial number )
<181>2022 Oct 17 10:27:37 Berlin: %PFMA-2-FEX_PS_FOUND: Fex 105 Power Supply 2 found (Serial number )
<181>2022 Oct 17 10:27:38 Berlin: %PFMA-2-FEX_STATUS: Fex 105 is online
<182>2022 Oct 17 14:00:07 Berlin: %ETHPORT-5-IF_DOWN_LINK_FAILURE: Interface Ethernet100/1/17 is down (Link failure)
<182>2022 Oct 18 10:32:04 Berlin: %VSHD-5-VSHD_SYSLOG_CONFIG_I: Configured from vty by XXXX on a.b.c.d@pts/0
<182>2022 Oct 19 11:28:06 Berlin: %ETHPORT-5-IF_DOWN_LINK_FAILURE: Interface Ethernet100/1/29 is down (Link failure)
<182>2022 Oct 19 11:28:08 Berlin: %ETHPORT-5-IF_DOWN_ADMIN_DOWN: Interface Ethernet100/1/29 is down (Administratively down)
<182>2022 Oct 19 11:33:57 Berlin: %ETHPORT-5-IF_ADMIN_UP: Interface Ethernet100/1/29 is admin up .
<182>2022 Oct 19 11:34:01 Berlin: %ETHPORT-5-SPEED: Interface Ethernet100/1/29, operational speed changed to 100 Mbps
<182>2022 Oct 19 11:34:01 Berlin: %ETHPORT-5-IF_DUPLEX: Interface Ethernet100/1/29, operational duplex mode changed to Full
<182>2022 Oct 19 11:34:01 Berlin: %ETHPORT-5-IF_RX_FLOW_CONTROL: Interface Ethernet100/1/29, operational Receive Flow Control state changed to off
<182>2022 Oct 19 11:34:01 Berlin: %ETHPORT-5-IF_TX_FLOW_CONTROL: Interface Ethernet100/1/29, operational Transmit Flow Control state changed to on
<187>2022 Oct 19 11:34:01 Berlin: %ETHPORT-3-IF_UP: Interface Ethernet100/1/29 is up in mode access

```

**Comment by efd6** [comment]
Thanks. It's not clear to me how the change here impacts on the documents that will end up being ingested by ES; the payload section of the lines are not retained as separate parts to be added as fields so the removal of the space prefix has not effect. For example the first line above ends up as this 
```
{
    "@timestamp": "2022-10-17T12:27:35.000Z",
    "event.code": "NOHMS_ENV_FEX_ONLINE",
    "event.dataset": "cisco.nexus",
    "event.module": "cisco",
    "event.original": "<181>2022 Oct 17 10:27:35 Berlin: %NOHMS-2-NOHMS_ENV_FEX_ONLINE: FEX-105 On-line",
    "event.timezone": "Berlin",
    "fileset.name": "nexus",
    "input.type": "log",
    "log.level": "2",
    "log.offset": 0,
    "log.syslog.facility.code": 22,
    "log.syslog.priority": 181,
    "log.syslog.severity.code": 5,
    "observer.product": "Nexus",
    "observer.type": "Switches",
    "observer.vendor": "Cisco",
    "related.hosts": [
        "NOHMS"
    ],
    "rsa.internal.event_desc": "FEX ONLINE",
    "rsa.internal.messageid": "NOHMS_ENV_FEX_ONLINE",
    "rsa.misc.device_name": "FEX-105",
    "rsa.misc.event_source": "NOHMS",
    "rsa.misc.severity": "2",
    "rsa.time.event_time": "2022-10-17T12:27:35.000Z",
    "rsa.time.timezone": "Berlin",
    "service.type": "cisco",
    "tags": [
        "cisco.nexus",
        "forwarded"
    ]
}
```
There are other issues that are obvious here that are pre-existing, for example `"related.hosts": ["NOHMS"]` which is obviously incorrect. However the nexus fileset is [exprimental](https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-module-cisco.html#_nexus_fileset_settings) so these issues may not be fixed. That said, I don't have any objection to the change here. It would be helpful to know whether the issue that this is intended to fix impacts you and how.

**Comment by mib1185** [comment]
i guess you take the perfect example event to explain the experimental state 😆 

in my case, when looking at the example event (_from inital post_):
`2022 Oct 19 11:34:01 Berlin: %ETHPORT-5-IF_HARDWARE: Interface Ethernet1/9, hardware type changed to QSA`

prior this change, the event gets flaged with `dissect_parsing_error` and some fileds are not parsed into `rsa` section (_like the interface name_). Now the parsing is OK and the interface name appears at `rsa.network.interface`

**Comment by efd6** [comment]
Yeah, fair enough. I just tested the samples that were in the bundle and commented on the first in the list. This is the event from the issue event reposted after the fix:
```
{
    "@timestamp": "2022-10-19T13:34:01.000Z",
    "event.code": "IF_HARDWARE",
    "event.dataset": "cisco.nexus",
    "event.module": "cisco",
    "event.original": "<181>2022 Oct 19 11:34:01 Berlin: %ETHPORT-5-IF_HARDWARE: Interface Ethernet1/9, hardware type changed to QSA",
    "event.timezone": "Berlin",
    "fileset.name": "nexus",
    "input.type": "log",
    "log.level": "5",
    "log.offset": 0,
    "log.syslog.facility.code": 22,
    "log.syslog.priority": 181,
    "log.syslog.severity.code": 5,
    "network.interface.name": "Ethernet1/9",
    "observer.product": "Nexus",
    "observer.type": "Switches",
    "observer.vendor": "Cisco",
    "related.hosts": [
        "ETHPORT"
    ],
    "rsa.internal.event_desc": "hardware type changed to QSA",
    "rsa.internal.messageid": "IF_HARDWARE",
    "rsa.misc.event_source": "ETHPORT",
    "rsa.misc.severity": "5",
    "rsa.network.interface": "Ethernet1/9",
    "rsa.time.event_time": "2022-10-19T13:34:01.000Z",
    "rsa.time.timezone": "Berlin",
    "service.type": "cisco",
    "tags": [
        "cisco.nexus",
        "forwarded"
    ]
}
```
Note that there is still an issue with `related.hosts`.

Are you able to add the test events (the original and the bundle in https://github.com/elastic/beats/pull/33385#issuecomment-1284226370) and run the test generation or would you like me to add those?

**Comment by mib1185** [comment]
I'm not sure where the key `related.hosts` comes from, but in my tests it never appears 🤔 
Unfortunatelly, I'm not familiar with Go, so I would gladly accept your offer to add the tests 🙂

**Review by efd6 — APPROVED** [review]
Thank you

**Pull request merged**
