### PR TITLE
typos

### PR DESCRIPTION
**Pull request by marnikvde**
added spaces

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
Thanks for contributing @marnikvde ! Could you sign the CLA for this PR please?

**Comment by marnikvde** [comment]
done

**Comment by kaiyan-sheng** [comment]
Thanks!! Actually this file is generated by a python script. Could you actually make the change in `https://github.com/elastic/beats/blob/master/metricbeat/module/kafka/_meta/docs.asciidoc` and then run `mage fmt update` under beats/metricbeat please?

**Comment by kaiyan-sheng** [comment]
@marnikvde Hello! I just saw this PR is created based on 7.6 branch. Is it OK if I create a new PR based on master branch to fix this? Then I can cherrypick it to 7.6 afterwards.

**Comment by kaiyan-sheng** [comment]
Replacing this PR by https://github.com/elastic/beats/pull/16772. Thanks @marnikvde !

**Pull request closed without merging**
