### PR TITLE
Cherry-pick #10429 to 6.x: Add rpm packaging rebase

### PR DESCRIPTION
**Pull request by tsg**
Cherry-pick of PR #10429 to 6.x branch. Original message: 

This takes over the code from #9092 and rebases it on top of master.

This adds support for programmatically reading the list of RPM packages. The previous version was using exec (called the rpm binary), but we'd like to keep Auditbeat exec free, because execs are currently blocked by seccomp, as a security feature.

Using the model from Journalbeat, the new code uses dlopen get the relevant C functions and calls them using CGo. This means that librpm is not a hard dependency, but only for when this functionality is needed.

### CODE REVIEW

**Comment by urso** [comment]
Please backport to 6.7 branch. 6.x will be removed.

**Comment by urso** [comment]
I changed base to 6.7

**Comment by tsg** [comment]
jenkins, test this

**Comment by tsg** [comment]
I reopened this as #10623, because weird things happened after changing the base, and I want to make sure it's clean.

**Pull request closed without merging**
