### PR TITLE
Allow space or time sync character before timestamp

### LINKED ISSUE #13269: filebeat syslog input: permit space after <PRI>
**Describe the enhancement:**

Netgear switches send a space between the `<PRI>` and the timestamp fields in a syslog message.  This is a violation of the standard, but it would be easy to accept.

Test case, based on packet captured using tcpdump from GS724Tv4:

```
echo -ne "<13> Aug 16 12:25:24 10.12.255.2-1 TRAPMGR[53034492]: traputil.c(696) 135956 %% Link Up: g5.\000" | nc -w0 -u localhost 5514
```

Current results:

```
  "message": "<13> Aug 16 12:25:24 10.12.255.2-1 TRAPMGR[53034492]: traputil.c(696) 135956 %% Link Up: g5.\u0000",
```

If the space was skipped, then the priority/facility, timestamp, program/pid could all be parsed.

(Aside: the messages also include a trailing null.  This could also be stripped, but I don't object to retaining it)

**Describe a specific use case for the enhancement or feature:**

Networks with Netgear switches.

### PR DESCRIPTION
**Pull request by candlerb**
Fixes elastic/beats#13269

### CODE REVIEW

**Comment by jsoriano** [comment]
ok to test

**Comment by urso** [comment]
Hi, unfortunately this PR hasn't been reviewed yet by us. Maybe you can rebase it on top of master?

@ph can you please have a look?

**Comment by candlerb** [comment]
Rebased on top of master.

Note: the output from ragel makes a lot of trivial changes, like reordering of states. I am using ragel 6.10-1 from Ubuntu 18.04 repositories.

**Comment by candlerb** [comment]
Added entry to `CHANGELOG.asciidoc` squashed into the same commit.

**Pull request merged**
