### PR TITLE
Update to Golang 1.7

### PR DESCRIPTION
**Pull request by ruflin**
Closes https://github.com/elastic/beats/issues/2055

### CODE REVIEW

**Comment by andrewkroh** [comment]
jenkins, package it

**Comment by andrewkroh** [comment]
@ruflin Once you update the SHA, ask Jenkins to package it again.

> WARNING: 1 computed checksum did NOT match

**Comment by ruflin** [comment]
jenkins, package it

**Comment by ruflin** [comment]
There seem to be some more issues. See http://build-eu-00.elastic.co/job/beats-package-PR/17/console

**Comment by andrewkroh** [comment]
> Undefined symbols for architecture x86_64:
  "_SecCertificateCopyNormalizedIssuerContent", referenced from:

[`SecCertificateCopyNormalizedIssuerContent`](https://developer.apple.com/library/mac/documentation/Security/Reference/certifkeytrustservices/index.html#//apple_ref/c/func/SecCertificateCopyNormalizedSubjectContent) was added in OSX 10.7 but the compiler we use is from 10.6.

The [Dockerfile](https://github.com/elastic/beats/blob/master/dev-tools/packer/docker/xgo-image/base/Dockerfile#L34) shows that it is using an OSX 10.6 SDK. The upstream xgo project is using a 10.11 SDK version. https://github.com/karalabe/xgo/blob/master/docker/base/Dockerfile#L42-L44

**Comment by ruflin** [comment]
Closing in favor of https://github.com/elastic/beats/pull/2306

**Pull request closed without merging**
