### PR TITLE
Support analysis of packets from pflog(4)

### PR DESCRIPTION
**Pull request by jasperla**
pflog(4) is the logging interface of pf(4), as used on OpenBSD, FreeBSD and Darwin. I've verified with tcpdump that packetbeat sees the same data.

### CODE REVIEW

**Comment by urso** [comment]
Interesting. Haven't tested this yet, but what's the payload of pflog?

Anything we need to add to packetbeat docs?

**Comment by jasperla** [comment]
I don't think there are any docs to update; as I don't see any of the others layers documented at the [interfaces](https://www.elastic.co/guide/en/beats/packetbeat/1.2/configuration-interfaces.html) page currently.

As for the payload, does [this](http://man.openbsd.org/OpenBSD-current/man4/pflog.4) help? Essentially you can instruct the firewall (pf) to route packets that match your rules to the pflogN device.

**Comment by urso** [comment]
Finally managed to test this on freebsd.

Advantage is, one can freely configure filters in kernel (even multiple devices). Might be an alternative for `any` device on OS X (only for advanced users though - don’t mess with your firewall). Disadvantages is pflog payload is IP layer, ethernet (Mac addresses) is missing.

Additional limitation:

- one must use `... log (all)` to get all packets
- When using `block log (all)` (very interesting use-case) limitation is we will never receive a response. Due to packetbeat designed to handle transactions, not just packets, a number of application layer analyzers might not send an event, as no response will ever be seen (e.g. http module). Some modules still send unfinished transaction on timeout (e.g. memcache)
- When using `block log (all)`, we depend on transaction timeouts (set to very low values).

At the moment better solution for forwarding firewall block-events is by relying on pflog and tcpdump to write events to text files and rely on filebeat forwarding these logs. Even better, write custom beat reading pf events from /dev/pf instead of relying on pflogd forwarding to virtual network device (e.g. see pftop).

Thoughts?

**Comment by jasperla** [comment]
Yeah, I was thinking of something similar and was actually reading pftop code earlier today. The problems with talking straight to pflog(4) are also evidenced by DNS for example where you'll see the request section, but no response.

I'd say close this PR and label it a failed experiment.

**Comment by urso** [comment]
Actually having pflog is still interesting (as you are pretty flexible regarding filtering). E.g. using pflog with `pass log ...` filter still does the trick.

For example the `any` device as used by packetbeat to collect packets from all devices will not work on *BSD. Using pflog might be an okish workaround (`any` device removes one MAC address from packet due to merging packets from all devices).

At least having pflog limitation documented in source code I'd still would like to merge this (even if this doesn't match your use-case).

**Comment by urso** [comment]
another use-case coming to mind: Disable all protocol analyzers in packetbeat (maybe keep ICMP enabled) and use flows-support in packetbeat to collect number of packets/bytes/connections being received on blocked ports/devices/ips...

**Comment by jasperla** [comment]
Alright; could you file the PR for the docs or shall I write something up?

**Comment by urso** [comment]
Would be nice if you add a short comment to NewDecoder. in decoder.go (As you noticed we don't have much documentation about interfaces yet). With *BDS users interested in beats+pflog I'd treat it as a hardcore-feature :)

**Comment by urso** [comment]
@jasperla Wonder if limitation in gopacket or pflog. While I can sniff with tcpdump running with packetbeat I get

```
2016/04/14 16:40:40.783801 decoder.go:162: INFO packet decode failed with: Invalid (too small) IP header length (0 < 5)
```

Looks like payload is missing.

**Comment by urso** [comment]
@jasperla you still interested in adding pflog support? Due to it not working properly for me when testing (might be mistake though), I'm tempted to the the PR for being in the void for so long.

**Comment by jasperla** [comment]
Hi @urso. I'm still interested, though due to obvious lack of time I don't know when I can look into this again. I'm fine with closing it for now.

**Comment by urso** [comment]
OK, will close for now. Thanks.

**Pull request closed without merging**
