### PR TITLE
Fix hard coded beats name

### PR DESCRIPTION
**Pull request by Alsheh**

### CODE REVIEW

**Comment by ruflin** [comment]
@exekias I wonder if metricbeat was set here on purpose as the code will not work with all Beats I think.

**Comment by ruflin** [comment]
@Alsheh Any chance you could open this PR against master instead and we can backport from there? Could you also sign the CLA? https://www.elastic.co/contributor-agreement

**Comment by dedemorton** [comment]
@Alsheh I'd be happy to close this PR and make the change, but I want to make sure you have an opportunity to sign the CLA before I do that. If not, I will move this forward for you. Thanks for your contribution.

**Comment by dedemorton** [comment]
Replaced by #11905 

@Alsheh FYI that I've implemented this change in a different PR. Thanks again for submitting this change.

**Pull request closed without merging**
