### PR TITLE
x-pack/auditbeat/module/system/socket: get full length path and arg from /proc when not available from kprobe

### LINKED ISSUE #24667: Auditbeat: socket reports truncated process name
Auditbeat's system/socket dataset can return truncated process names in two scenarios:

1. When the table of running processes its bootstrapped during startup, the "comm" field of `/proc/<pid>/stat` is used as the process name. This value is truncated to 15 chars by the kernel (TASK_COMM_LEN=16).

To align with the rest of the `system/socket` code, the filename extracted from the executable path should be used.

Example document:
```json
{
    "@timestamp": "2021-03-22T08:57:10.558Z",
    "process": {
      "pid": 21830,
      "name": "elastic-endpoin",
      "args": [
        "/opt/Elastic/Endpoint/elastic-endpoint",
        "run"
      ],
      "executable": "/opt/Elastic/Endpoint/elastic-endpoint",
      "created": "2021-03-04T14:05:55.860Z"
    },
   [...]
}
```

2. When an `execve` event is received, the length of the executable path and program arguments is limited to 128 characters each. When path is truncated, the wrong process name will be extracted from it.

As a suggestion, we could detect this truncation and do an alternative enrichment from `/proc/<pid>/`.

### PR DESCRIPTION
**Pull request by efd6**
## What does this PR do?

This uses path and arg information from /proc in cases where the kprobe details are truncated.

## Why is it important?

Currently filepaths, executable names and argument lists may be truncated due to kernel limitations.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

No specific recommendation.

## How to test this PR locally

Standard testing on linux.

## Related issues

- Fixes #24667 

## Use cases

N/A

## Screenshots

N/A

## Logs

N/A

### CODE REVIEW

**Comment by efd6** [comment]
@adriansr I'm wondering if we could (in a separate PR) also add container ID enrichment here to address #22238. To avoid unwanted work on non-containerised systems we would check during init whether we are in a container and only try to get the ID if we are. This should alleviate the timing issues with deferring the enrichment until later without too much additional cost in the general case.

**Comment by adriansr** [comment]
@efd6 I think it's worth to investigate the container ID enrichment in a separate PR, as you said.  I think there's a few issues to solve, afaik the `add_process_metadata` processor won't react well to having a pre-populated `container.id` field (it will either overwrite it or fail completely).

**Review by adriansr — APPROVED** [review]
LGTM

**Comment by kesslerm** [comment]
Is there any chance this can be backported to the 7.x series, too? Many customers will not be in a position to upgrade immediately to the 8.x series.

**Comment by efd6** [comment]
@kesslerm Started.

**Pull request merged**
