### PR TITLE
Remove x-pack code from OSS filebeat.

### LINKED ISSUE #40293: OSS filebeat harvester_test.go should not depend on Elastic-licensed code
There a depguard lint rule failing because we have OSS test code depending on Elastic-licensed code from the x-pack/ directory. Due to licensing, dependencies are only allowed in the opposite direction. The code in question is test code so it doesn't taint any of our OSS release artifacts. Nonetheless, we should fix it (perhaps by moving the helper code from x-pack to oss).

> filebeat/input/filestream/internal/input-logfile/harvester_test.go:36:2: import 'github.com/elastic/beats/v7/x-pack/dockerlogbeat/pipelinemock' is not allowed from list 'apache-licensed-code': Apache 2.0 licensed code cannot depend on Elastic licensed code (x-pack/). (depguard)

Related

- https://github.com/elastic/beats/issues/38719
- https://github.com/elastic/beats/pull/40132#issuecomment-2234162445

### PR DESCRIPTION
**Pull request by vinit-chauhan**
## Proposed commit message

```
To fix the failing linter rule that requires OSS code to not depend on x-pack
code, this change removes the dependency on x-pack/dockerlogbeat/pipelinemock
from the Filebeat filestream input. It does this by creating a mock client
that is local to filestream test code ("A little copying is better than a
little dependency").

Fixes #40293
```

Remove x-pack code from OSS filebeat.

This PR creates a `MockPipelineConnector` and `MockClient` interface in the libbeat to drop the x-pack dependency in OSS code. 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes #40293

### CODE REVIEW

**Comment by vinit-chauhan** [comment]
Hey @andrzej-stencel  - I'm always happy to contribute to Elastic. :)

The reason for not moving the code as-is is, that this code is used only in the `harvestor_test.go` file for the OSS codebase. But if you want I can update the PR to move the x-pack code to OSS.

For the points you mentioned, 
- Renaming package to `mock`: The x-pack code mocks functionality by implementing the libbeat features, that's the reason why I think the OSS version should move to libbeat. Additionally, there's already a package containing mocks named `mock`, so I moved it there all to a single place.
- `MockBeatClient` -> `MockClient`: I think the original author of the code added `MockBeat` because they mocked the libbeat's `Client` interface outside of the libbeat codebase, and now the code is in beats, I think adding `Beats` is redundant. 
- `MockPipelineConnector` -> `MockPipeline`: I have implemented the Pipeline interface whereas the original code implements `PipelineConnector` interface which is a wrapper to the `Pipeline` interface.  
- `GetAllEvents` and `HasConnectedClients`: Those 2 are additional methods added on top of PipelineConnector and used by the tests they have written.

interfaces used: 
- https://github.com/elastic/beats/blob/main/libbeat/beat/pipeline.go

That is the explanation for the changes I have made. Let me know your thoughts.

**Comment by AndersonQ** [comment]
@vinit-chauhan given the limited usage of this new mock and that `mock.New` is a mockbeat and nothing else. Perhaps the best would be to move your mock code to `filebeat/input/filestream/internal/input-logfile/harvester_test.go`. There are already other mocks there, so it makes sense to have this one there as well.

**Comment by vinit-chauhan** [comment]
Hey @AndersonQ - wouldn't that cause the same issue? 
If someone decides to use mockbeat in let's say metricbeat, then they'll have to re-write it or reference the filebeat code in metricbeat. 

So, I think it's better to keep the libbeat mocks in libbeat, so that we don't cross reference others.

But, let me know what you think, I'll update accordingly. :)

**Comment by AndersonQ** [comment]
Oh, I meant moving just the mock you created and keeping the mockbeat where it is

**Comment by vinit-chauhan** [comment]
Oh I see, it makes sense then!

**Comment by leehinman** [comment]
sorry for missing this.  I like @AndersonQ suggestion.

**Comment by andrzej-stencel** [comment]
Sorry for the delay, sounds good to me :+1:

**Comment by pierrehilbert** [comment]
run docs-build

**Comment by vinit-chauhan** [comment]
Hey team - Apologies for the delay. I have moved the mock to the `harvestor_test` file as per our discussion. 

Let me know if you require anything else.

**Review by andrewkroh — APPROVED** [review]

**Review by leehinman — APPROVED** [review]

**Review by AndersonQ — APPROVED** [review]

**Comment by ycombinator** [comment]
run docs-build

**Pull request merged**
