### PR TITLE
[Enhancement] add output kafka support for zstd

### PR DESCRIPTION
**Pull request by gwy1995**
## Proposed commit message

add output kafka support for zstd
## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by pierrehilbert** [comment]
Hello @gwy1995 
Thanks for your contribution.
Could you please sign our CLA?

**Comment by gwy1995** [comment]
> Hello @gwy1995 Thanks for your contribution. Could you please sign our CLA?

I have signed it for three times , but it still shows as unsigned in this issue. What should I do ?

**Comment by pierrehilbert** [comment]
Did you sign it with the same email than your github account?

**Comment by gwy1995** [comment]
> Did you sign it with the same email than your github account?

yes, I have sign it today and yesterday for more than three times.

**Comment by faec** [comment]
Hi @gwy1995, we can try figuring out where the CLA checker is having trouble, but another issue I notice is that you removed Elastic's [sarama fork](https://github.com/elastic/sarama) and replaced it with an older (downgraded) upstream version. (See the readme in the fork for details.) The fork includes fixes for serious issues, so any changes to the sarama version should either update the fork's base version, or update to a mainline version that includes the fixes we need.

**Comment by gwy1995** [comment]
> Hi @gwy1995, we can try figuring out where the CLA checker is having trouble, but another issue I notice is that you removed Elastic's [sarama fork](https://github.com/elastic/sarama) and replaced it with an older (downgraded) upstream version. (See the readme in the fork for details.) The fork includes fixes for serious issues, so any changes to the sarama version should either update the fork's base version, or update to a mainline version that includes the fixes we need.

Thanks for reminding me of this. I have rolled back the sarama version. 
I found that the elastic version of sarama has merged the changes required by zstd, so just add one line of configuration. I wrote the details in the comments.Please take another look

**Comment by leehinman** [comment]
looks good.  Any chance you could add a test case to https://github.com/elastic/beats/blob/42dc965a50853c282ef4407683711e1cf5b3bbb8/libbeat/outputs/kafka/kafka_integration_test.go#L57 ?

**Comment by gwy1995** [comment]
> looks good. Any chance you could add a test case to
> 
> https://github.com/elastic/beats/blob/42dc965a50853c282ef4407683711e1cf5b3bbb8/libbeat/outputs/kafka/kafka_integration_test.go#L57
> 
> ?

I add a test case. But I don't know why it didn't pass CI. I have tested it in the local environment.

**Review by leehinman — APPROVED** [review]

**Comment by pierrehilbert** [comment]
@gwy1995 Could you please retry to sign the CLA?
This is a mandatory step to be able to merge your PR.

**Comment by gwy1995** [comment]
> @gwy1995 Could you please retry to sign the CLA? This is a mandatory step to be able to merge your PR.

hi, I finally successfully signed the CLA

**Review by mauri870 — APPROVED** [review]

**Comment by pierrehilbert** [comment]
We have a failing test @gwy1995 


```
=== Failed
--
  | === FAIL: libbeat/outputs/kafka TestKafkaPublish/run_test(13):_publish_message_with_zstd_compression_to_test_topic (0.00s)
  | kafka_integration_test.go:278: unknown/unsupported kafka version '2.2.2' accessing 'version'

```

**Comment by gwy1995** [comment]
> We have a failing test @gwy1995
> 
> ```
> === Failed
> --
>   | === FAIL: libbeat/outputs/kafka TestKafkaPublish/run_test(13):_publish_message_with_zstd_compression_to_test_topic (0.00s)
>   | kafka_integration_test.go:278: unknown/unsupported kafka version '2.2.2' accessing 'version'
> ```

I have changed version, could you please test again

**Comment by gwy1995** [comment]
> > We have a failing test @gwy1995
> > ```
> > === Failed
> > --
> >   | === FAIL: libbeat/outputs/kafka TestKafkaPublish/run_test(13):_publish_message_with_zstd_compression_to_test_topic (0.00s)
> >   | kafka_integration_test.go:278: unknown/unsupported kafka version '2.2.2' accessing 'version'
> > ```
> 
> I have changed version, could you please test again

tests are passed?

**Comment by pierrehilbert** [comment]
run docs-build

**Comment by pierrehilbert** [comment]
Looks good to go! 
Thanks for your contribution

**Pull request merged**
