### PR TITLE
FreeTDS Plugin for Packetbeat [WIP]

### PR DESCRIPTION
**Pull request by sudhindrasajjal**
FreeTDS plugin for Unix/Linux to communicate with a Microsoft SQL Server.

### CODE REVIEW

**Comment by ruflin** [comment]
@sudhindrasajjal To fix the linting issue, I recommend you to run `make fmt` and it should do the rest for you.

**Comment by Budman17r** [comment]
Awesome Happy to see this up here.

**Comment by tsg** [comment]
Same issue here, you need to resync with master to get rid of the notice errors.

**Comment by sudhindrasajjal** [comment]
@ruflin I am facing an issue with the system test for this plugin. Locally on my machine, it successfully passes all the tests but fails to create an output directory here.

```
if [ true = true ]; then \
	 make fast-system-tests; \
fi
make[1]: Entering directory '/home/sudhindras/src/github.com/elastic/src/github.com/elastic/beats/packetbeat'
. /home/sudhindras/src/github.com/elastic/src/github.com/elastic/beats/packetbeat/build/python-env/bin/activate; nosetests -w tests/system --processes=4 --process-timeout=90
...................................................................................................................................................................
----------------------------------------------------------------------
Ran 163 tests in 44.288s

OK
```

**Pull request closed without merging**
