### PR TITLE
Add dashboard string_replacements config

### PR DESCRIPTION
**Pull request by tommas1988**
<Enhancement>

## What does this PR do?
This PR add dashboard `string_replacements` config, which can be used to replace content, like title or id, in dashboard and its references configuration.

## Why is it important?
With this configuration, we can setup multiple same dashboards not only differ with host name, but also other aspects. Such as different services deploy on a single machine and want same dashboard to display running information.

## Checklist

- [ x] My code follows the style guidelines of this project
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
- [ x] I have made corresponding changes to the documentation
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by tommas1988** [comment]
> This pull request doesn't have a `Team:<team>` label.

how to add a label

**Comment by tommas1988** [comment]
need to merge the current master branch to pass the unit test?

**Comment by tommas1988** [comment]
> This pull request does not have a backport label. Could you fix it @tommas1988? 
> To fixup this pull request, you need to add the backport labels for the needed
> branches, such as:
> 
> * `backport-v./d./d./d` is the label to automatically backport to the `7./d` branch. `/d` is the digit
> 
> **NOTE**: `backport-skip` has been added to this pull request.

Sorry I don`t know how to add a label for PR. Could you please give me some guide to add labels for PR? @jsoriano

**Comment by rdner** [comment]
@tommas1988 The title says "backport" from where are you backporting? Was this change initially made to 8.*?

**Comment by rdner** [comment]
mergify update

**Comment by rdner** [comment]
@tommas1988 well, it's not a backport then. The title is confusing. It's just a change to the current `main` which is supposed to be backported to 7.* later.

Please merge the current `main` to your PR, or rebase on top. I'll run the tests and we'll merge it if it passed.

**Comment by rdner** [comment]
@tommas1988 unfortunately, your changes affected the files that had some linting issues. We enabled our linter recently and it inspect only the files affected by PRs. Could you please fix them?

**Review by rdner — APPROVED** [review]

**Comment by rdner** [comment]
Okay, I'll merge it without fixing the linter issues, it can be addressed later.

**Pull request merged**
