### PR TITLE
I made a new beat

### PR DESCRIPTION
**Pull request by yedamao**
Mcqbeat can monitor queues in memcaheq.

### CODE REVIEW

**Comment by tsg** [comment]
Thanks @yedamao for the new Beat! Can you sign the CLA, please, so we can merge this PR?

I also wonder if this would make sense to be (also) a Metricbeat module. At the first sight, it seems to fit Metricbeat pretty good.

**Comment by yedamao** [comment]
@tsg I have signed the CLA and opened a new PR #3597。
Maybe I should read the doc of Metricbeat。

**Comment by tsg** [comment]
Thanks, closing in favor of #3597.

**Comment by ruflin** [comment]
+1 on metricbeat module. Here is the dev guide: https://www.elastic.co/guide/en/beats/metricbeat/current/creating-metricbeat-module.html

**Pull request closed without merging**
