### PR TITLE
Add RFC5424 format support for syslog input 

### LINKED ISSUE #6872: Syslog input to support RFC5424
The current implementation of the parser only support [RFC3164](https://tools.ietf.org/html/rfc3164), some newer system uses [RFC5424](https://tools.ietf.org/html/rfc5424). It's just a matter of adding new state machines to the Ragel parser and add new tests for it.

We have to investigate if we can detect it on the fly OR we make it a user configurable settings.

Lets make sure we add integration test for this all list with one major producer.

### PR DESCRIPTION
**Pull request by WPH95**
## What does this PR do?
Reopen from #20246
Resolves #6872 
Add RFC5424 format support for syslog input

## Why is it important?

Syslog input only support rfc3164, btw rfc3164 is obsoleted by [rfc5424](https://tools.ietf.org/html/rfc5424)   

More and more software is using rfc5424 instead of rfc3164.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [x] Syslog
  - [x] inputs config support RFC5424
  - [x] detect format automatically
- [x] Ragel
  - [x] HEADER
    - [x] PRI
    - [x] VERSION
    - [x] TIMESTAMP
    - [x] HOSTNAME
    - [x] APP-NAME
    - [x] PROCID
    - [x] MSGID
  - [x] STRUCTURED-DATA
    - [x] SD-ELEMENT
    - [x] SD-ID
    - [x] SD-PARAM
    - [x] Change Control
  - [x] MSG
- [x] TEST 
  - [x] all examples in RFC5424 document
  - [x] Some special boundary case tests

## Related issues
closes # #6872

### CODE REVIEW

**Comment by faec** [comment]
jenkins, run the tests please

**Comment by kvch** [comment]
jenkins run tests

**Comment by faec** [comment]
Thanks for the contribution, this looks great! Can you merge with the latest branch and re-push? It looks like your base used an older testing configuration that doesn't work with our current setup.

**Comment by WPH95** [comment]
> Thanks for the contribution, this looks great! Can you merge with the latest branch and re-push? It looks like your base used an older testing configuration that doesn't work with our current setup.

np, will rebase to lastest soon :) tks your review and reply

**Comment by faec** [comment]
jenkins run tests

**Review by andrewkroh — COMMENTED** [review]
Have you considered putting this parsing logic into a processor such users can parse both rfc3164 and rc5424 independent of the `input` type used? Like parsing syslog messages read from a file or taken from a kafka topic.

**Comment by WPH95** [comment]
> Have you considered putting this parsing logic into a processor such users can parse both rfc3164 and rc5424 independent of the `input` type used? Like parsing syslog messages read from a file or taken from a kafka topic.

make sense! 
I can move the logic to the processer in the next pr.
Personally, I don't really recommend doing it in this pr, which has enough work and spend a long time

**Comment by isuldor** [comment]
Hi, I understand this isn't a support thread, so feel totally free to ignore me. I'm happy to test this as I'm in the middle of building out a log ingest pipeline for a Checkpoint 80.40 firewall, which I suspect has the issue this PR aims to solve (although I could be wrong). About 90% of my logs are parsed successfully by the cef module. The other ~10% seem to not be parsed as filebeat shows this frequent error in journalctl:

`ERROR        [syslog]        syslog/input.go:239`        **can't parse event as syslog rfc3164**       ` {"message": "CEF:0|Check Point|VPN-1 & FireWall-1|Check Point|Log|Log|Unknown|act=Drop deviceDirection=1 rt=1614288900000 spt=443 dpt=59305 cs2Label=Rule Name cs2=redacted layer_name=Network layer_uuid=redacted match_id=37 parent_rule=0 rule_action=Drop rule_uid=redacted ifname=bond1.411 logid=0 loguid={0xredacted} origin=redacted originsicname=CN\\=redacted,O\\=redacted sequencenum=971 version=5 drop_reason=matched optimized drop dst=redacted product=VPN-1 & FireWall-1 proto=6 sgm_id=1_1 src=redacted\n"}`

After building filebeat from HEAD with this PR and using that binary as a drop in replacement, I'm not seeing any cef logs collected at all, while my other input modules continue working fine (syslog/panw). This is with filebeat 7.11 installed via the debian repo. I'm assuming I just missed something basic here.

Besides merging this PR into HEAD, running `make` in beats/filebeat and using the new `filebeat` binary, is there anything else I need to do to my install?

**Comment by faec** [comment]
Hi, just a followup to say that while I haven't had time to do a full line-by-line review yet, I think this looks good and we hope to merge it. Thank you for all the work that went into this, and I will follow up with more specific feedback soon :-)

**Review by faec — APPROVED** [review]
Thank you again, this PR was lovely to read :-)

**Pull request merged**
