### PR TITLE
feat: Add Hetzner Cloud to add_cloud_metadata

### PR DESCRIPTION
**Pull request by rajivshah3**
Please label this PR with one of the following labels, depending on the scope of your change:
- Enhancement

## What does this PR do?

Adds support for [Hetzner Cloud](https://www.hetzner.com/cloud) for the `add_cloud_metadata` processor. Because [Hetzner's metadata API](https://docs.hetzner.cloud/#server-metadata) returns information in YAML, it seems easier to make multiple, specific requests (similar to the approach for OpenStack Nova) rather than getting all of the metadata and parsing the YAML.

Additionally, this PR fixes the `exclude-functions` config for `(mapstr.M).Put` and `(mapstr.M).Delete`

## Why is it important?

`add_cloud_metadata` does not support Hetzner yet and it can be beneficial for companies that use Hetzner and Beats

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

N/A

## How to test this PR locally

- Run tests locally
- Compile Beats and use `add_cloud_metadata` on a Hetzner server

### CODE REVIEW

**Comment by rajivshah3** [comment]
> Meanwhile, may I ask you to fix the linter issues?

Hi @rdner, what would be the best way to handle an error from `result.metadata.Put` and `w.Write`? There seem to be similar situations with Tencent Cloud, OpenStack Nova, and Huawei Cloud, so I assume the linter wasn't picking these up at the time they were merged:

https://github.com/elastic/beats/blob/c7aacda512c6bf2a3542a59ac284a1ac8194746c/libbeat/processors/add_cloud_metadata/provider_tencent_cloud.go#L55

https://github.com/elastic/beats/blob/c7aacda512c6bf2a3542a59ac284a1ac8194746c/libbeat/processors/add_cloud_metadata/provider_openstack_nova.go#L68

https://github.com/elastic/beats/blob/c7aacda512c6bf2a3542a59ac284a1ac8194746c/libbeat/processors/add_cloud_metadata/provider_huawei_cloud.go#L72

Also, regarding the [usage of `github.com/pkg/errors`](https://github.com/elastic/beats/actions/runs/4998747340/jobs/8954467625?pr=35456#step:5:35), I don't think this was related to my change, but I'm happy to change to the recommended packages if desired. I wasn't sure whether I should increase the scope of this PR.

**Comment by rajivshah3** [comment]
If I understand correctly, shouldn't the linter actually ignore the `errcheck` rule for `(mapstr.M).Put`?

https://github.com/elastic/beats/blob/c7aacda512c6bf2a3542a59ac284a1ac8194746c/.golangci.yml#L75-L77

**Comment by rdner** [comment]
@rajivshah3 

> Hi @rdner, what would be the best way to handle an error from result.metadata.Put and w.Write?

If you think that we should know about these errors, we need to log them. The tricky part is to choose the right level. We don't want to spam the logs if the errors are not significant.

If you think an error is not important, it's enough to do something like:

```go
_ = w.Write()
```

Then the linter should stop complaining about unchecked errors.


> There seem to be similar situations with Tencent Cloud, OpenStack Nova, and Huawei Cloud, so I assume the linter wasn't picking these up at the time they were merged:

The linter might have been introduced after this code was merged, for the new code we're striving to avoid new linter issues.

> If I understand correctly, shouldn't the linter actually ignore the errcheck rule for (mapstr.M).Put?

You're right, that was the intent but the rules seem to be not working, maybe wrong formatting.

**Review by tommyers-elastic — APPROVED** [review]
LGTM

**Review by rdner — APPROVED** [review]

**Pull request merged**
