### PR TITLE
Change nats module server.id type from string to keyword

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
I ran into an error when running metricbeat `[elasticsearch] [2019-01-21T09:36:52,566][DEBUG][o.e.a.a.i.t.p.TransportPutIndexTemplateAction] [node-0] failed to put template [metricbeat-7.0.0]
[elasticsearch] org.elasticsearch.index.mapper.MapperParsingException: Failed to parse mapping [_doc]: No handler for type [string] declared on field [id]` and this PR will fix this issue.

### CODE REVIEW

**Comment by jsoriano** [comment]
> I wonder why CI did not catch this.

The test checking the template setup was temporary commented out in #9031 :confused:

**Comment by jsoriano** [comment]
Trying to re-enable this test...

**Comment by ruflin** [comment]
@jsoriano I already merged this PR as I hit issues in one of my other PR's too. @kaiyan-sheng Hope that is ok for you.

@jsoriano Can you rebase your other PR?

**Comment by jsoriano** [comment]
@ruflin updated with master, let's see if it goes green :crossed_fingers: :slightly_smiling_face:

**Pull request merged**
