### PR TITLE
Import updated ECS 1.0.0 go library.

### PR DESCRIPTION
**Pull request by webmat**
Note that this uses the `1.0` version branch and not a tag, currently.
The Go code generation was backported after v1.0.0 was cut.

We will likely tag again at the end of the docs migration (part 2 of https://github.com/elastic/dev/issues/1148).
We can use this tag when we get there.

### CODE REVIEW

**Comment by andrewkroh** [comment]
jenkins, test this

**Comment by webmat** [comment]
jenkins, test this

**Comment by ruflin** [comment]
jenkins, test this

**Comment by webmat** [comment]
Looks like Jenkins needed some convincing! All green now :-)

**Pull request merged**
