### PR TITLE
[CI] use try to avoid a global abort

### PR DESCRIPTION
**Pull request by v1v**
## What does this PR do?

Use try/catch to avoid setting the build to abort

## Why is it important?

I see several aborted builds recently and somehow I thing the catchError + timeout is not doing what it should be.

In addition a put https://beats-ci.elastic.co/computer/worker-c07c6107jyw0/ offline

### CODE REVIEW

**Review by mdelapenya — APPROVED** [review]

**Review by cachedout — APPROVED** [review]

**Review by kuisathaverat — APPROVED** [review]

**Comment by v1v** [comment]
For some reason the GitHub check was not updated but the build 6 worked like a charm:

image

**Pull request merged**
