### PR TITLE
[Ingest Manager] Do not compare err with custom type

### LINKED ISSUE #19976: [Elastic Agent] Panic error while enrolling an agent with a revoked token
## Runtime metadata
- Version: Latest 8.0.0-SNAPSHOT
- Operating System: Centos 7 Docker

## Steps to Reproduce: 
1. setup Fleet
1. Create a token
1. Start a Centos 7 docker container in the same network as Kibana, ES and package-registry
1. Install latests SNAPSHOT for the agent in the container (https://www.elastic.co/guide/en/ingest-management/current/elastic-agent-installation.html)
1. Use the already created token to enroll the agent, using the insecure flag, as Kibana runs on HTTP
1. Revoke the token in Kibana
1. Destroy the centos7 service
1. Start a Centos 7 docker container in the same network as Kibana, ES and package-registry
1. Install latests SNAPSHOT for the agent in the container (https://www.elastic.co/guide/en/ingest-management/current/elastic-agent-installation.html)
1. Use the already created token to enroll the agent, using the insecure flag, as Kibana runs on HTTP

#### Expected behavior
The agent is not enrolled with no panic errors on agent side

#### Actual behavior
The agent is not enrolled but panic errors are thrown on agent side. See the following stacktrace:

```stacktrace
The Elastic Agent is currently in BETA and should not be used in production
2020-07-16T06:33:30.445Z        DEBUG   kibana/client.go:170    Request method: POST, path: /api/ingest_manager/fleet/agents/enroll
panic: runtime error: comparing uncomparable type errors.agentError

goroutine 1 [running]:
github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/cmd.enroll(0xc00031ade0, 0xc000338c80, 0xc00031ae10, 0xc000275180, 0x2, 0x4, 0xcaff9d, 0x4)
        /go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/cmd/enroll.go:125 +0xac7
github.com/elastic/beats/v7/x-pack/elastic-agent/pkg/agent/cmd.newEnrollCommandWithArgs.func1(0xc000338c80, 0xc000275180, 0x2, 0x4)
        /go/src/github.com/elastic/beats/x-pack/elastic-agent/pkg/agent/cmd/enroll.go:36 +0x6d
github.com/spf13/cobra.(*Command).execute(0xc000338c80, 0xc0002750c0, 0x4, 0x4, 0xc000338c80, 0xc0002750c0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:766 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0xc000338500, 0x6, 0x6, 0xc00031ade0)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:852 +0x2ea
github.com/spf13/cobra.(*Command).Execute(...)
        /go/pkg/mod/github.com/spf13/cobra@v0.0.3/command.go:800
main.main()
        /go/src/github.com/elastic/beats/x-pack/elastic-agent/main.go:20 +0x138
```

## Related issues
- Discovered while testing https://github.com/elastic/e2e-testing/pull/149, more specifically this use case https://github.com/elastic/e2e-testing/blob/master/e2e/_suites/ingest-manager/features/fleet_mode_agent.feature#L43-L47

### PR DESCRIPTION
**Pull request by michalpristas**
## What does this PR do?

Fixes #19976 by using comparison from errors package instead of comparing custom types

## Why is it important?

Avoid panics

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

cc @ph

### CODE REVIEW

**Comment by mdelapenya** [comment]
Thanks for the fix! Do we have an ETA about when the 8.0.0-snapshot binary will be pushed to https://artifacts-api.elastic.co/v1/search/8.0.0-SNAPSHOT/elastic-agent?

It currently returns `https://snapshots.elastic.co/8.0.0-6a0038f5/downloads/beats/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-linux-x86_64.tar.gz`, but not sure if this is included.

**Comment by ph** [comment]
@mdelapenya they are usually built once a day, but there other jobs on beats-ci that build packages on every commits we should probably uses that instead of the snapshot created by the release manager?

**Comment by mdelapenya** [comment]
@ph I think this is a good idea, because it will bring more flexibility to the e2e tests. Otherwise we will depend on the release team for fixing stuff (which is also good in the sense that we could enhance it providing our feedback)

**Comment by ph** [comment]
@mdelapenya Since our project it really linked to the ingest manager, we should use more up to date artifact from Kibana too?

**Comment by mdelapenya** [comment]
If we are able to consume es, kibana and agent artifacts with more frequency, the best. I know we store docker images under the observability-ci namespace, not sure how they are created. @kuisathaverat I summon you! :)

**Comment by kuisathaverat** [comment]
AFAIK Kibans only push docker images with the Unified Release Snapshot job (URS) so only once a day. However, we are working on some kind of hot build and deploy of a Kibana PR, that could cover this need https://github.com/elastic/observability-robots/issues/7 If you need it, I could put it in my top priority

**Comment by ph** [comment]
@kuisathaverat I think this would be great because without recent new build I think we would have a lot of false positive. cc @EricDavisX @KseniaElastic

**Pull request merged**
