### PR TITLE
Update NATS dashboard

### PR DESCRIPTION
**Pull request by ChrsMark**
## What does this PR do?
This PR updates NATS dashboard with small improvements on currents visualisations and new ones to leverage new `connection` and `route` metricsets.

## Why is it important?
To update the module before the migration to package.

## Screenshot
metricbeat_nats_dashboard

Related to elastic/integrations#359

### CODE REVIEW

**Comment by jsoriano** [comment]
@ChrsMark dashboard looks good! only one thing. Are the "Timelines" visualizations showing counters continuously growing? Would it make sense to show the derivative instead?

**Comment by ChrsMark** [comment]
@jsoriano good point! I moved monotonically increasing metrics to TSVB to show the rates.

**Review by jsoriano — APPROVED** [review]
Thanks! LGTM, but failure in CI seems related.

**Comment by ChrsMark** [comment]
CI issue resolved after https://github.com/elastic/beats/pull/22684. Merging.

**Pull request merged**
