### PR TITLE
[Heartbeat] Add index sorting

### PR DESCRIPTION
**Pull request by andrewvc**
This patch changes the default sort order within the Heartbeat index template to be 'monitor.id', '@timestamp' in order to improve the performance of queries in https://github.com/elastic/kibana/pull/42933

See benchmarks in comment below

### CODE REVIEW

**Comment by andrewvc** [comment]
I've benchmarked this by creating a large (300MiB) index in heartbeat. Then, I reindexed the same exact documents using the reindex API into a new index with sorting applied. I then manually captured the queries used by the states index query and ran them. I made sure to clear the index caches before running the queries, as cached indices are fast. Sorting yielded improvements over both queries, especially where the cache was stale. 

|           |  Find Potential Matches |  Refine Potential Matches |
|-----------|-------------------------|---------------------------|
|  Unsorted |  651ms                  |  604ms                    |
| Sorted    |  419ms                  | 350ms                     |


Both queries were extremely fast when cached. However, for uptime, data is frequently uncached as new data is always coming in. The almost 50% perf improvement here is worth it.

**Comment by andrewvc** [comment]
Benchmarking this on the same branch as https://github.com/elastic/kibana/pull/47598/checks?check_run_id=252505426 I see all the advantages disappear. 

unsorted
988

sort simple (sort order monitor.id, @timestamp)
976

full sort 990 (sort order monitor.id, geo.location.name, monitor.ip, @timestamp)

**Comment by ruflin** [comment]
+1 on this. I remember working on a rally job for this about 2 years ago to see the actual effect on ingestion and query time. AFAIK there is also an impact on the ingest performance but as queries or run many more times I think it's worth it.

I'm good with getting this in but also would like to have a rally job for it to make sure if things change, we know. This should also allow us to try out different params and compare.

**Comment by andrewvc** [comment]
@ruflin well, I think I may have to close this given my comment just before yours. Fixing a query in the Uptime UI negated index sorting's perf gain :(.

I'll leave it open for a few days as I want to take another look at it before I do

**Comment by andrewvc** [comment]
Closing this for now, I may revive this if I can think of a way to bring back the perf.

**Comment by andrewvc** [comment]
Closing this experiment for now.

**Pull request closed without merging**
