### PR TITLE
Use a goformation fork to go around MAX_PATH limitation

### PR DESCRIPTION
**Pull request by ph**
The goformation library is pretty liberal with the lenght of the file it uses, this seems to mess up our windows CI because we reach the MAX_PATH limit.

Followup issue for moving back to original lib https://github.com/elastic/beats/issues/8857

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
can we add vendor/ into .gitignore?

**Comment by ph** [comment]
@kaiyan-sheng I understand the pain of having the dependencies in the project, there are also advantages. I think we could discuss that in another issue or with the issue discussing moving from govendor to another tool https://github.com/elastic/beats/issues/8070

**Comment by ph** [comment]
```
service_integration_windows_test.go:79: 
		Error Trace:	service_integration_windows_test.go:79
		Error:      	Not equal: 
		            	expected: 0x0
		            	actual  : 0x154
		Test:       	TestReadService
		Messages:   	PID of service Background Intelligent Transfer Service does not match
service_integration_windows_test.go:82: 
		Error Trace:	service_integration_windows_test.go:82
		Error:      	Not equal: 
		            	expected: "Stopped"
		            	actual  : "Running"
		            	
		            	Diff:
		            	--- Expected
		            	+++ Actual
		            	@@ -1 +1 @@
		            	-Stopped
		            	+Running
		Test:       	TestReadService
		Messages:   	State of service Background Intelligent Transfer Service does not match
``` 

I never seen the above fails before, I will trigger another CI run to see if its a flaky test or not and do a followup issue.

**Comment by ph** [comment]
jenkins test this please

**Pull request merged**
