### PR TITLE
Add append in docs

### PR DESCRIPTION
**Pull request by vinit-chauhan**
## What does this PR do?
This PR adds `append` processor to the elastic docs.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by vinit-chauhan** [comment]
@leehinman would you mind a quick review?

**Comment by belimawr** [comment]
run elasticsearch-ci/docs

**Review by belimawr — COMMENTED** [review]
On a quick glance it looks good to me, now it's just a matter of making sure CI is passing/the docs are building. I've triggered the build, let's wait for it.

**Comment by vinit-chauhan** [comment]
Hey @belimawr - Thanks for the review! 😄

**Comment by vinit-chauhan** [comment]
Hey @belimawr - it seems like elasticsearch/docs pipeline passed successfully. 

However, I'm not sure why it's failing for 2 of the checks thought. Maybe it's some permission issue in CI. Would you mind taking a look into it?

**Review by belimawr — APPROVED** [review]

**Comment by belimawr** [comment]
It was just some static code analysis failing, not relevant for a doc PR ;)

Thanks a lot for the contribution!

**Pull request merged**
