### PR TITLE
[docs] Add username and password to haproxy example

### PR DESCRIPTION
**Pull request by dedemorton**
Replaces elastic/beats#16324

### CODE REVIEW

**Comment by ycombinator** [comment]
Hey @dedemorton I think this PR is incomplete? I've created https://github.com/elastic/beats/pull/16776 to complete the change started in this PR.

**Comment by ycombinator** [comment]
Also, I see that there's a `needs_backport` label on this PR but it doesn't say which versions this PR will be going into. Could you please add the version labels so I can backport https://github.com/elastic/beats/pull/16776 to the same version branches? Thanks!

**Comment by dedemorton** [comment]
I think it was a timing issue because my branch had this change. Anyhow, I'm not sure which versions. I would assume 7.6 and 7.x? Does @ph know?

**Comment by ph** [comment]
I believe it's 7.x and 7.6?

**Comment by ycombinator** [comment]
Thanks @ph. I'll setup the backports for this PR and it's follow up: https://github.com/elastic/beats/pull/16776.

**Pull request merged**
