### PR TITLE
Add 0-1 scale for Metricbeat Docker percentage fields

### PR DESCRIPTION
**Pull request by kilfoyle**
This docs PR updates the various percentage fields on the Metricbeat [Docker fields](https://www.elastic.co/guide/en/beats/metricbeat/current/exported-fields-docker.html) page to indicate that the scale is 0 - 1, rather than 0 - 100.

I'm not set up to run the docs generation script, so I've updated both the Yaml source and the corresponding Asciidoc output.

Closes: https://github.com/elastic/beats/issues/12411

### CODE REVIEW

**Comment by kilfoyle** [comment]
check-docs CI check fails with: 
```
Error: some files are not up-to-date. Run 'make update' then review and commit the changes. Modified: [metricbeat/docs/fields.asciidoc
```

Would anyone with a Beats dev environment set up mind running `make update` so that this can pass CI?

**Review by beiske — APPROVED** [review]

**Comment by beiske** [comment]
Thank you @kilfoyle

**Comment by rdner** [comment]
@elastic/obs-infraobs-integrations can someone please have a look?

**Comment by pierrehilbert** [comment]
cc @lalit-satapathy

**Review by lalit-satapathy — APPROVED** [review]

**Pull request merged**
