### PR TITLE
[metricbeat] windows module remove Spanish from data.json

### PR DESCRIPTION
**Pull request by philippkahr**
I guess that should not be in Spanish.

### CODE REVIEW

**Comment by narph** [comment]
jenkins test this

**Comment by kaiyan-sheng** [comment]
Hello @philippkahr thanks for contributing. `data.json` is automatically generated by `TestData` function generally and this is probably generated on a machine that has Spanish. If you want to remove the Spanish part in `data.json`, I would actually rerun https://github.com/elastic/beats/blob/master/metricbeat/module/windows/service/service_integration_windows_test.go#L42 instead.

**Comment by ChrsMark** [comment]
@kaiyan-sheng I would say that this is not mandatory. How about accepting this so as to have a friendlier experience in the docs for non spanish speaking users? 

:es: :es: :es:

**Comment by kaiyan-sheng** [comment]
> @kaiyan-sheng I would say that this is not mandatory. How about accepting this so as to have a friendlier experience in the docs for non spanish speaking users?
> 
> 🇪🇸 🇪🇸 🇪🇸 🙂

Agree, definitely not mandatory. Since there is no activity on this PR for more than a month now, I will close it.

**Pull request closed without merging**
