### PR TITLE
Inject clock for docker watcher tests

### LINKED ISSUE #7906: [Libbeat] Flaky TestWatcherDie test
Link: https://beats-ci.elastic.co/job/elastic+beats+master+multijob-windows/beat=libbeat,label=windows/1331/console
Platform: Windows

Error
```
>> go test: Unit Testing
11:34:30 FAILURES:
11:34:30 Error: go test failed: 1 test failures
11:34:30 Package: github.com/elastic/beats/libbeat/common/docker
11:34:30 Test:    TestWatcherDie
11:34:30 assertions.go:247: 
11:34:30                           
11:34:30 	Error Trace:	watcher_test.go:385
11:34:30 	
11:34:30 	Error:      	Not equal: 
11:34:30 	
11:34:30 	            	expected: 1
11:34:30 	
11:34:30 	            	actual  : 0
11:34:31 	
11:34:31 	Test:       	TestWatcherDie
11:34:31 assertions.go:247: 
11:34:31                           
11:34:31 	Error Trace:	watcher_test.go:385
11:34:31 	
11:34:31 	Error:      	Not equal: 
11:34:31 	
11:34:31 	            	expected: 1
11:34:31 	
11:34:31 	            	actual  : 0
11:34:31 	
11:34:31 	Test:       	TestWatcherDie
11:34:31 assertions.go:247: 
11:34:31                           
11:34:31 	Error Trace:	watcher_test.go:385
11:34:31 	
11:34:31 	Error:      	Not equal: 
11:34:31 	
11:34:31 	            	expected: 1
11:34:31 	
11:34:31 	            	actual  : 0
11:34:31 	
11:34:31 	Test:       	TestWatcherDie
11:34:31 assertions.go:247: 
11:34:31                           
11:34:31 	Error Trace:	watcher_test.go:385
11:34:31 	
11:34:31 	Error:      	Not equal: 
11:34:31 	
11:34:31 	            	expected: 1
11:34:31 	
11:34:31 	            	actual  : 0
11:34:31 	
11:34:31 	Test:       	TestWatcherDie
11:34:31 ----
11:34:31 SUMMARY:
11:34:31   Fail:     1
11:34:31   Skip:     6
11:34:31   Pass:     788
11:34:31   Packages: 70
11:34:31   Duration: 33.5826022s
```

### PR DESCRIPTION
**Pull request by jsoriano**
Inject clock for docker watcher tests to avoid depending on timing.

Fix  #7906

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
Cool it's a draft!! So does the draft skip the continuous-integration/travis-ci/pr tests?

**Comment by jsoriano** [comment]
> Cool it's a draft!! So does the draft skip the continuous-integration/travis-ci/pr tests?

Yeah! giving a try to this new feature, it seems to trigger less things, I wonder how this is decided.

**Comment by ruflin** [comment]
Interesting idea with the clock interface. Let's see if it solves the flakiness issue.

**Comment by jsoriano** [comment]
Closing this by now, I will try to refactor the docker watcher to reuse the cache in libbeat.

**Pull request closed without merging**
