### PR TITLE
Fix for tests after `device...` field has been removed

### PR DESCRIPTION
**Pull request by narph**
## What does this PR do?

Fix for tests after `device...` field has been removed

## Why is it important?

Fix for tests after `device...` field has been removed

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Review by kaiyan-sheng — APPROVED** [review]
LGTM, thank you for fixing this!

**Review by jsoriano — APPROVED** [review]
Thanks!

**Comment by jsoriano** [comment]
Tests passed, not sure why "Lint" is marked as pending. Merging to fix builds.

**Comment by jsoriano** [comment]
Removing the field from 7.x too in https://github.com/elastic/beats/pull/25153.

**Pull request merged**
