### PR TITLE
[Heartbeat] Add retry logic for http check

### PR DESCRIPTION
**Pull request by lowryxiao**
## What does this PR do?

Add new parameter `max_retries` the same level as `max_redirects` to support retry logic for http check.

## Why is it important?
Currently, there's no retry logic for http check in Heartbeat.
However, there could be some http check failures happen if only a single http check in case:

the number of http check targets is huge;
there's a network jitter;
the target is not ready in the first round check.

## Checklist

- [*] My code follows the style guidelines of this project
- [*] I have commented my code, particularly in hard-to-understand areas
- [] I have made corresponding changes to the documentation
- [*] I have made corresponding change to the default configuration files
- [*] I have added tests that prove my fix is effective or that my feature works
- [] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues
https://github.com/elastic/beats/issues/24148

## Use cases

1. by default, the `max_retries` will be 0, like `max_redirects`, that means there's only a single http check happening without retries by default.
2. Heartbeat will try only 1 time if the target `http://127.0.0.1:80` is reachable whereas HB will try 3 times by total when the target is unreachable and `max_retries` is 2 from HB config like the following:
```
- type: http
  schedule: 36 * * * * * *
  hosts:
    - http://127.0.0.1:80
  check.request:
    method: GET
  check.response:
    status:
    - 200
    - 201
  timeout: 10s
  max_redirects: 2
  max_retries: 3
```

### CODE REVIEW

**Comment by andrewvc** [comment]
Thanks for the PR and apologies for the delay.

This is something we've wanted to tackle for a while, and now's as good a time as any to start a conversation around it. The TL;DR IMHO is that retries are a great feature to add, but I have questions, and I'm not sure that the form they're in here is something we'd want to 

My $0.02 is that we should strongly consider indexing the entirety of the failures as well as the last successful ping. Currently, in the Uptime UI, alerts are defined as N failures within a window of a certain length. Even for those who don't use this UI, accessing error values makes a lot of sense, and sliding windows are a great way to do alerting. Skimming the PR it looks like this only adds the number of retries that occurred, but does not include the specific error. The schema change here would mean you'd have to look at retries + errors to get an idea of how down something is, which is not efficient from an ES query perspective.

Today, heartbeat has a notion of a check having multiple parts, currently that's only used with `mode: any`, where multiple IPs are resolved via DNS. In this case we index a doc per IP, but they share a common `monitor.check_group` UUID value, which binds them together. The final event contains `summary.up` and `summary.down` summarizing how many events in check group succeeded / failed.

If we do a retry, I think it makes more sense to emit a whole new doc for the retry and have duplicates that may have different statuses.

That said, I'd like to hear more about your use case around network jitter / other things. I'd argue that the problem is not so much heartbeat but the alerting mechanism in play. Retrying can give a false sense that an endpoint is up if it is flapping. If it's up 75% of the time, you'll see a bunch of succeeding checks! If it's up 90% of the time (which is also terrible) it may be quite a while before 3 consecutive retries fail.

What makes more sense is to compute downtime as a sliding window over a spaced out series of checks. Where retries are helpful is in increasing the cadence of check when a possible outage is detected. If it's down once, it's worth checking a few more times to see if it's "really" down. More samples make more sense, where they otherwise might not be justifiable in terms of storage or cost. 

I'll end by leaving a final thought, retries have the potential to make heartbeat performance less predictable, since it can increase its utilization of resources precisely when you have an emergency (things are down). This worries me slightly.

Looking forward to hearing your thoughts on these points @lowryxiao

**Comment by lowryxiao** [comment]
@andrewvc Sorry for the delay.
First of all, my change is to add retry for these targets that the first check for them are failed. No retry happens if the first check is success.

As discussed in this topic at `discuss.elastic`: https://discuss.elastic.co/t/heartbeat-add-retry-logic-into-http-tcp-check/264328/4

Our use case is like this:
1. We have ~90K targets to monitor per minute as well as 90K metrics per min.
2. The network for most nodes are stable.

So, the simplest and the most efficiency way we could consider to cover those first check failed targets is to add retrying logic for them. Since there’ll be enormous meaningless checks happen if we check targets multiple times over a window no matter the targets checking are sucess or fail then count the percentage on all the check results.

These improvements are what I could think per your comments:
1. clarify the errors after add retry logic
2. identify the check_group block after add retry logic
3. emit a whole new doc for the retry

Please feel free to comment on my reply if I got misunderstanding or you have any other problems.
Thanks.

**Comment by lowryxiao** [comment]
Hi guys, any comments for this PR?
Thanks.:+1

**Comment by andrewvc** [comment]
Apologies for the delay @lowryxiao. In short, I think we should add retry logic to heartbeat including some of the changes you mentioned in your reply.

The important thing is that we keep the notion of check groups the same as today. What would make the most sense would be to have the retries happen within that same check group as new documents as you mentioned. Additionally, we could allow people to set a minimum number of retries. For ICMP checks I can see users wanting to, for instance, do a group of three pings every 10 minutes, or for synthetics checks to run the checks several times in a row to get more performance data.

The reason it's important to keep the check groups from overlapping is that a check group is intended to cover a given unit of time. In other words if your check runs every hour that check group should cover the geographic location that is being pinged from for that entire duration. That check group could very well contain multiple pings but that invariant of one check group per time box should be kept.

I would also like to get thoughts on this from others in the team, specifically @shahzad31 @justinkambic @paulb-elastic @drewpost and @dominiqueclarke @vigneshshanmugam and @jahtalab

**Comment by lowryxiao** [comment]
Hi guys, any progress for this PR?
Thanks.

**Comment by drewpost** [comment]
Hi @lowryxiao - I'm the product manager for Uptime. We're currently in the middle of several big changes to the product that are all interrelated. One is that we're adding an additional agent to run full synthetic checks from a browser which will introduce a new set of reasons why a test run can fail beyond simply timing out/returning a 5xx. The other big change is that we're moving to a new definition of monitor health. A big part of this work is the concept of automatic retries. If a test fails, we want to run an automatic retry before creating an "error" that would then trigger alerting logic.

This capability will be coming to the product but we have some other foundational bits that need to be finished first before we're ready to add in retry logic.

**Comment by lowryxiao** [comment]
@drewpost Thanks for the great sharing.
Sounds like these 2 features are both amazing, cannot wait to see them in the future.
pls let me know if anything I can contribute.

**Comment by NeilInnes** [comment]
@drewpost Sorry for bring up an old thread - but is there any news/progress on retrying HTTP failures?

**Comment by d44b** [comment]
@drewpost I'd like to bump it, it would be really useful. Does someone plan to implement this feature in Heartbeat sooner or later? If not, we will try to build our own image based on this PR :)

**Pull request closed without merging**
