### PR TITLE
[Filebeat] Add to Zeek Module

### PR DESCRIPTION
**Pull request by xander33**
- Added 30 filesets to the Zeek module
- Moved existing fields from module level `_meta/fields.yml` to `{fileset}/_meta/fields.yml`
- Minor additions to existing connection and ssl configurations

related issues: #12724  #11944

### CODE REVIEW

**Comment by alakahakai** [comment]
jenkins, test this

**Comment by alakahakai** [comment]
@xander33 Some files are not up-to-date. Can you run 'mage fmt update' on beats/x-pack/filebeat and beats/filebeat directory, then review and commit the changes again?

**Comment by alakahakai** [comment]
@xander33: Thanks for the contribution. From a brief glance, it looks good. We will do a more detailed review. BTW, is it possible for you to add the *.log-expected.json for the test files?

**Comment by alakahakai** [comment]
@xander33:

It seems that you don't have time to work on this PR anymore. Are you OK with us opening a new PR with your commits? Your commits will be kept so you are still credited for it. Thanks.

**Comment by hyperbaba** [comment]
So, this is moving forward? Good, smb logs are important for lateral movement detection

**Comment by xander33** [comment]
@alakahakai Yes my time has been limited lately. Go ahead and do what you need to do

**Comment by MarkSettleES** [comment]
@xander33, I'm not on the engineering team, but as someone at Elastic who focuses on our security analytics offerings and community, but thank you for your work on this proposed enhancement.

**Comment by alakahakai** [comment]
Created new PR [#14150](https://github.com/elastic/beats/pull/14150) to finish it up. Thanks to @xander33 for the contribution.

**Pull request closed without merging**
