### PR TITLE
Add state field for connection metricset from RabbitMQ module (#13697) #WIP

### PR DESCRIPTION
**Pull request by amandahla**
Add state field for connectino metricset. Still needs to test in real environment.

### CODE REVIEW

**Comment by exekias** [comment]
Thank you for opening this @amandahla! Can you please update `fields.yml` for `connection` metricset to accomodate this new field?

**Comment by andresrc** [comment]
Fixes https://github.com/elastic/beats/issues/13697

**Comment by odacremolbap** [comment]
Hi @amandahla 

this looks good, but I noticed some indentation at golden/JSON files that lead me to think you are manually editing them.

Would you mind to:
```bash
cd GOPATH/src/github.com/elastic/beats/metricbeat/module/rabbitmq/connection
go test  ./... -generate
```

that command should generate both JSON files with correct indentation.

**Comment by amandahla** [comment]
@odacremolbap done! :-)

**Pull request merged**
