### PR TITLE
Optimize memory allocations in the event processing pipeline

### PR DESCRIPTION
**Pull request by rdner**
Previously, every time some processors ran on an event we made a clone of the entire event for two reasons:

* this event could have some nested maps that are shared among multiple events.
* in case a processor fails to make a change it should be able to revert its partial changes.

This change added a new `EventEditor` wrapper that is used for collecting pending event changes in processors with an option to Apply or Reset them.

Additionally, this `EventEditor` takes care of the efficient memory management when making changes to an event by cloning only the nested maps that processors access or modify. Most of the processors just put new keys or delete existing keys on the root-level, so most of the time the nested maps in the event remain untouched and it does not require the whole event to be cloned.

This change also migrates the following processors to using the `EventEditor` instead of cloning whole events:

* [append](https://www.elastic.co/guide/en/beats/filebeat/current/append.html)
* [copy_fields](https://www.elastic.co/guide/en/beats/filebeat/current/copy-fields.html)
* [decode_base64_field](https://www.elastic.co/guide/en/beats/filebeat/current/decode-base64-field.html)
* [decompress_gzip_field](https://www.elastic.co/guide/en/beats/filebeat/current/decompress-gzip-field.html)
* [rename](https://www.elastic.co/guide/en/beats/filebeat/current/rename-fields.html)
* [replace](https://www.elastic.co/guide/en/beats/filebeat/current/replace-fields.html)
* [truncate_fields](https://www.elastic.co/guide/en/beats/filebeat/current/truncate-fields.html)
* [add_process_metadata](https://www.elastic.co/guide/en/beats/filebeat/current/add-process-metadata.html)
* [convert](https://www.elastic.co/guide/en/beats/filebeat/current/convert.html)
* [decode_csv_fields](https://www.elastic.co/guide/en/beats/filebeat/current/decode-csv-fields.html)
* [dissect](https://www.elastic.co/guide/en/beats/filebeat/current/dissect.html)
* [extract_array](https://www.elastic.co/guide/en/beats/filebeat/current/extract-array.html)
* [urldecode](https://www.elastic.co/guide/en/beats/filebeat/current/urldecode.html)

All the listed processors were making a backup/clone of the entire event in order to restore the event in case of failure.

### Before

```
336269333 ns/op 251485534 B/op 435076 allocs/op
```

mem-before-editor

### After

```
24894392 ns/op        21003350 B/op      36349 allocs/op
```

That's

```
~13,5 times less ns/op        ~11,97 times less B/op      ~11,96 times less allocs/op
```

mem-after-editor

**This clone is happening in the test itself, as you can see and does not contribute to the actual performance, all the clones in the processors are gone.**

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Related to https://github.com/elastic/beats/pull/36906

### CODE REVIEW

**Comment by StephanErb** [comment]
@rdner this looks super interesting. Do you plan to bring this to completion?

**Comment by rdner** [comment]
Hi @StephanErb I'm glad you find it interesting. This change is unlikely to land, so I'm closing this PR. 2 main reasons:

1. This change does not optimize our default configuration. This event cloning problem exists only if `fail_on_error` is set to `true` in the processors listed above. The default value is `false`. To our knowledge, it's not a common use-case for our customers.
2. This change introduces a lot of complexity for solving a problem that is not common. The `EventEditor` code is quite difficult to follow and it might affect stability in future releases.

cc @cmacknz if you have anything to add to this.

**Comment by StephanErb** [comment]
We are using `fail_on_error=False` widely as we would rather have events forwarded as-is then silently be dropped. I somewhat assumed this is what most users do and want... Is there an easy way to check how often this occurs?

**Comment by rdner** [comment]
@StephanErb `fail_on_error=False` means you're not affected by the performance problem solved here. As I mentioned in https://github.com/elastic/beats/pull/36958#issuecomment-2006942830 this PR addresses the `fail_on_error=True` case when there is a performance penalty.

**Comment by StephanErb** [comment]
Ah. I think what confused me here is the default config you talked about. It is set to True in some cases which would imply the default is slow, for example https://www.elastic.co/guide/en/beats/filebeat/current/rename-fields.html

**Comment by rdner** [comment]
@StephanErb thanks for pointing this out. If our team decides to move forward with this change, I'll re-open this PR.

**Comment by cmacknz** [comment]
> cc @cmacknz if you have anything to add to this.

Only that we have another set of performance optimizations coming that reduce memory usage at high throughput significantly. So even though we aren't proceeding with this change, we have still been working to improve performance.

**Pull request closed without merging**
