### PR TITLE
Test the tests

### PR DESCRIPTION
**Pull request by ruflin**
This temporary PR is to see which tests fail even if no changes were made.

### CODE REVIEW

**Comment by ruflin** [comment]
@urso @exekias @andrewkroh Goal is to get this green.

**Comment by andrewkroh** [comment]
I triggered all stages via https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-22086/build?delay=0sec.

**Comment by ruflin** [comment]
Of course this build had to go green :-) I triggered it again.

**Comment by urso** [comment]
Congratulations on another green build :P

The jenkinsfile runs tests selectively. You either have to touch files in each beats directory or set the [`runAllStages`](https://github.com/elastic/beats/blob/master/Jenkinsfile#L48) parameter to true.

**Comment by ruflin** [comment]
@urso I did, at least I checked the checkbox in Jenkins when rerunning the build. I basically checked all the boxes there :-) I assume that means, this build was indeed green!

**Comment by exekias** [comment]
🙈 Looking at latest PRs (without backports): https://github.com/elastic/beats/pulls?q=is%3Apr+is%3Aopen+-label%3Abackport+, it would seem like things are mostly green. So I wonder, this could be actually a good moment to enforce the need for green to merge to (at least) master more strongly.

**Pull request closed without merging**
