### PR TITLE
Use pytest instead of nosetests

### PR DESCRIPTION
**Pull request by jsoriano**
## What does this PR do?

Replaces nosetests with pytest.

## Why is it important?

Nosetests has been in maintenance mode for years, its last release was done in 2015. When evolving the testing framework for Python tests it would be better to do it based on a maintained test tool. It will stop working with Python 3.9.

For #15891     I am considering adding new features to the testing framework that could include to add some plugin for the test tool, it wouldn't make sense to implement code based on a discontinued tool.

Pytest is a complete and well maintained test tool, it is one of the tools recommended after cease of nose project and it can be used as a direct replacement.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works

## Author checklist

- [x] Interrupting tests with compose fails because compose tries to write to stderr and it is closed

## Related issues

- elastic/beats#15891
- elastic/beats#20384

### CODE REVIEW

**Comment by jsoriano** [comment]
Closing this by now.

**Comment by jsoriano** [comment]
We have talked internally about this and we think that it worths to continue migrating out of nosetests even if we don't have any other immediate benefit. So I will continue with this change.

**Comment by andresrc** [comment]
Can you create an issue focusing on the need to remove this because 3.9? Thanks!

**Comment by jsoriano** [comment]
> Can you create an issue focusing on the need to remove this because 3.9? Thanks!

Sure, issue about supporting python 3.9 created #20384.

**Comment by jsoriano** [comment]
jenkins run the tests please

**Comment by jsoriano** [comment]
jenkins run the tests please

**Comment by jsoriano** [comment]
jenkins run the tests please

**Comment by kuisathaverat** [comment]
nice!! after merge this, we could add the retries we have in the APM ITs https://github.com/elastic/apm-integration-testing/pull/866

**Pull request merged**
