### PR TITLE
[WIP] [Filebeat] Nagios log module

### PR DESCRIPTION
**Pull request by rverchere**
Add filebeat module to parse specific nagios log, with thid kind of data:

```
[1572296732] Warning: Check of service 'uptime' on host 'fake.lab.local' timed out after 20.015s!
[1572296732] wproc: Core Worker 12707: job 7913 (pid=2729): Dormant child reaped
[1572296845] EXTERNAL COMMAND: PROCESS_HOST_CHECK_RESULT;dc01.lab.local;1;down|
[1572296845] PASSIVE HOST CHECK: dc01.lab.local;0;PING OK - Packet loss = 0%, RTA = 0.49 ms
[1572296845] HOST NOTIFICATION: admin;dc01.lab.local;DOWN;notify-by-email-host;down
[1572296845] HOST ALERT: dc01.lab.local;DOWN;HARD;1;down
[1572296845] GLOBAL HOST EVENT HANDLER: dc01.lab.local;DOWN;HARD;1;event-browser-host
[1572296877] HOST NOTIFICATION: admin;dc01.lab.local;UP;notify-by-email-host;PING OK - Packet loss = 0%, RTA = 0.40 ms
[1572296877] HOST ALERT: dc01.lab.local;UP;HARD;1;PING OK - Packet loss = 0%, RTA = 0.40 ms
[1572296877] GLOBAL HOST EVENT HANDLER: dc01.lab.local;UP;HARD;1;event-browser-host
```

Grok patterns are defined here: https://github.com/logstash-plugins/logstash-patterns-core/blob/master/patterns/nagios

**Work In Progress:**

- [ ]  Handle all logs types
- [ ] Write documentation
- [ ] Add tests

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
jenkins, test this please

**Comment by willemdh** [comment]
Hello, I've been parsing Nagios Core logs for several years. Give me some time and I'll add my grok patterns, then we can compare. Had a quick look at your fields. Why do you insert *. log. * in fields? Imho it seems redundant and we could just use Nagios.service.name etc?

**Comment by rverchere** [comment]
@exekias done! But do not merge it yet, the work is still in progress!


> Hello, I've been parsing Nagios Core logs for several years. Give me some time and I'll add my grok patterns, then we can compare. Had a quick look at your fields. Why do you insert *. log. * in fields? Imho it seems redundant and we could just use Nagios.service.name etc?

Hi @willemdh thanks for your help! I did some nagios logging years ago using logstash and grok patterns. I wanted to understand how filebeat modules work, and nagios log is a good candidate for me. There are only 3 patterns yet, so I need to add more...
Concerning the fields, I just took example for others modules (apache2, kafka, etc.). If you think it should be changed, no problem!

**Comment by willemdh** [comment]
@rverchere 

> I just took example for others modules (apache2, kafka, etc.)

Hmm well imho the fields should be correlatable with data from other data sources. For example, we are using ingesting the following nagios data:
- Nagios Core logs
- Nagios XI Audit logs
- All Nagios objects inclusive their current state are also indexed every 5 minutes
- NSClient logs
- NCPA logs

Just an fyi, I'm also a Nagios MVP and I know Nagios inside out. 😄 (see https://www.nagios.com/mvp/)

All of the above have data which refers to nagios host names, nagios service names, states, statuss'es etc, so if each of the above would use their own sub filed under nagios.*, eg nagios.log.*, nagios.audit.*, nagios.config.*, etc it would be impossible to correlate this data.

SO, as a reference, this is my current filebeat pipeline for the Nagios Core logs:

```
  "filebeat-nagios-core" : {
    "description" : "Filebeat Nagios Core Pipeline",
    "processors" : [
      {
        "date_index_name" : {
          "field" : "@timestamp",
          "index_name_prefix" : "nagios-001-",
          "date_rounding" : "M",
          "index_name_format" : "8uuuu.MM"
        }
      },
      {
        "set" : {
          "field" : "pipeline",
          "value" : "filebeat-nagios-core"
        }
      },
      {
        "set" : {
          "field" : "event.original",
          "value" : "{{message}}"
        }
      },
      {
        "set" : {
          "field" : "event.created",
          "value" : "{{@timestamp}}"
        }
      },
      {
        "set" : {
          "field" : "event.module",
          "value" : "nagios"
        }
      },
      {
        "set" : {
          "field" : "event.dataset",
          "value" : "nagios.core"
        }
      },
      {
        "set" : {
          "field" : "service.name",
          "value" : "Nagios Core"
        }
      },
      {
        "set" : {
          "field" : "service.type",
          "value" : "Monitoring"
        }
      },
      {
        "grok" : {
          "field" : "message",
          "patterns" : [
            """\A\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>HOST) (?<event.action>ALERT): %{DATA:nagios.host.name};%{DATA:nagios.host.status};%{DATA:nagios.state};%{NUMBER:nagios.attempt};%{GREEDYDATA:nagios.output}""",
            """\A\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>HOST) (?<event.action>DOWNTIME ALERT): %{DATA:nagios.host.name};%{DATA:nagios.host.status}; %{GREEDYDATA:nagios.output}""",
            """\A\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>HOST) (?<event.action>FLAPPING ALERT): %{DATA:nagios.host.name};%{DATA:nagios.host.status}; %{GREEDYDATA:nagios.output}""",
            """\A\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>HOST) (?<event.action>NOTIFICATION): %{DATA:nagios.contact};%{DATA:nagios.host.name};%{DATA:nagios.host.status};%{DATA:nagios.handler};%{GREEDYDATA:nagios.output}""",
            """\A\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>SERVICE) (?<event.action>ALERT): %{DATA:nagios.host.name};%{DATA:nagios.service.name};%{DATA:nagios.service.status};%{DATA:nagios.state};%{NUMBER:nagios.attempt};%{GREEDYDATA:nagios.output}""",
            """\A\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>SERVICE) (?<event.action>DOWNTIME ALERT): %{DATA:nagios.host.name};%{DATA:nagios.service.name};%{DATA:nagios.service.status}; %{GREEDYDATA:nagios.output}""",
            """\A\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>SERVICE) (?<event.action>FLAPPING ALERT): %{DATA:nagios.host.name};%{DATA:nagios.service.name};%{DATA:nagios.service.status}; %{GREEDYDATA:nagios.output}""",
            """\A\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>SERVICE) (?<event.action>NOTIFICATION): %{DATA:nagios.contact};%{DATA:nagios.host.name};%{DATA:nagios.service.name};%{DATA:nagios.service.status};%{DATA:nagios.handler};%{GREEDYDATA:nagios.output}""",
            """\A\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>External command)%{SPACE}(?<event.level>error): %{DATA:error.message}""",
            """\A\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>wproc):%{SPACE}%{GREEDYDATA:error.message}""",
            """\A\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>CURRENT SERVICE STATE): %{DATA:nagios.host.name};%{DATA:nagios.service.name};%{DATA:nagios.service.status};%{DATA:nagios.state};%{NUMBER:nagios.attempt};%{GREEDYDATA:nagios.output}""",
            """\A\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>External command) (?<event.level>error):%{SPACE}%{GREEDYDATA:error.message}""",
            """\A\[%{NUMBER:nagios.timestamp_epoch}] (?<event.level>Error):%{SPACE}%{GREEDYDATA:error.message}""",
            """\A\[%{NUMBER:nagios.timestamp_epoch}] (?<event.level>Warning):%{SPACE}Check of service \'%{DATA:nagios.service.name}\' on host \'%{DATA:nagios.host.name}\' (?<event.kind>timed out) after %{GREEDYDATA:nagios.timeout}""",
            """\A\[%{NUMBER:nagios.timestamp_epoch}] (?<event.level>Warning):%{SPACE}%{GREEDYDATA:error.message}""",
            """\A\[%{NUMBER:nagios.timestamp_epoch}] (?<event.action>Auto-save of retention data) %{DATA:event.outcome}\.\Z"""
          ],
          "pattern_definitions" : {
            "NAGIOS_TYPE" : "(HOST ALERT|HOST DOWNTIME ALERT|HOST FLAPPING ALERT|HOST NOTIFICATION|SERVICE ALERT|SERVICE DOWNTIME ALERT|SERVICE FLAPPING ALERT|SERVICE NOTIFICATION|)"
          },
          "on_failure" : [
            {
              "set" : {
                "field" : "pipeline_error",
                "value" : "{{ _ingest.on_failure_message }}"
              }
            }
          ]
        }
      }
    ]
  }
}
```

Are you using Nagios Core or XI? Are you interested in the pipeline I'm using for Nagios XI audit logs too? Maybe we should start with focussing on the Core logs first. Please have a look at the above pipeline and let me know what you think? I'm open for discussion on anything.

**Comment by rverchere** [comment]
Hi @willemdh ,

thanks a lot for your pipelines!

For now I have the following patterns:

```
{
  "filebeat-8.0.0-nagios-core-pipeline" : {
    "description" : "Pipeline for parsing nagios core",
    "processors" : [
      {
        "grok" : {
          "ignore_missing" : true,
          "field" : "message",
          "patterns" : [
            "\\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>HOST) (?<event.action>ALERT): %{DATA:nagios.host.name};%{DATA:nagios.host.status};%{DATA:nagios.state};%{NUMBER:nagios.attempt};%{GREEDYDATA:nagios.output}",
            "\\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>HOST) (?<event.action>DOWNTIME ALERT): %{DATA:nagios.host.name};%{DATA:nagios.host.status}; %{GREEDYDATA:nagios.output}",
            "\\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>HOST) (?<event.action>FLAPPING ALERT): %{DATA:nagios.host.name};%{DATA:nagios.host.status}; %{GREEDYDATA:nagios.output}",
            "\\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>HOST) (?<event.action>NOTIFICATION): %{DATA:nagios.contact};%{DATA:nagios.host.name};%{DATA:nagios.host.status};%{DATA:nagios.handler};%{GREEDYDATA:nagios.output}",
            "\\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>SERVICE) (?<event.action>ALERT): %{DATA:nagios.host.name};%{DATA:nagios.service.name};%{DATA:nagios.service.status};%{DATA:nagios.state};%{NUMBER:nagios.attempt};%{GREEDYDATA:nagios.output}",
            "\\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>SERVICE) (?<event.action>DOWNTIME ALERT): %{DATA:nagios.host.name};%{DATA:nagios.service.name};%{DATA:nagios.service.status}; %{GREEDYDATA:nagios.output}",
            "\\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>SERVICE) (?<event.action>FLAPPING ALERT): %{DATA:nagios.host.name};%{DATA:nagios.service.name};%{DATA:nagios.service.status}; %{GREEDYDATA:nagios.output}",
            "\\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>SERVICE) (?<event.action>NOTIFICATION): %{DATA:nagios.contact};%{DATA:nagios.host.name};%{DATA:nagios.service.name};%{DATA:nagios.service.status};%{DATA:nagios.handler};%{GREEDYDATA:nagios.output}",
            "\\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>External command)%{SPACE}(?<event.level>error): %{DATA:error.message}",
            "\\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>wproc):%{SPACE}%{GREEDYDATA:error.message}",
            "\\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>CURRENT SERVICE STATE): %{DATA:nagios.host.name};%{DATA:nagios.service.name};%{DATA:nagios.service.status};%{DATA:nagios.state};%{NUMBER:nagios.attempt};%{GREEDYDATA:nagios.output}",
            "\\[%{NUMBER:nagios.timestamp_epoch}] (?<nagios.type>External command) (?<event.level>error):%{SPACE}%{GREEDYDATA:error.message}",
            "\\[%{NUMBER:nagios.timestamp_epoch}] (?<event.level>Error):%{SPACE}%{GREEDYDATA:error.message}",
            "\\[%{NUMBER:nagios.timestamp_epoch}] (?<event.level>Warning):%{SPACE}Check of service '%{DATA:nagios.service.name}' on host '%{DATA:nagios.host.name}' (?<event.kind>timed out) after %{GREEDYDATA:nagios.timeout}",
            "\\[%{NUMBER:nagios.timestamp_epoch}] (?<event.level>Warning):%{SPACE}%{GREEDYDATA:error.message}",
            "\\[%{NUMBER:nagios.timestamp_epoch}] (?<event.action>Auto-save of retention data) %{DATA:event.outcome}$"
          ],
          "pattern_definitions" : {
            "NAGIOS_TYPE" : "(HOST ALERT|HOST DOWNTIME ALERT|HOST FLAPPING ALERT|HOST NOTIFICATION|SERVICE ALERT|SERVICE DOWNTIME ALERT|SERVICE FLAPPING ALERT|SERVICE NOTIFICATION|)"
          }
        }
      },
      {
        "date" : {
          "field" : "nagios.timestamp_epoch",
          "target_field" : "@timestamp",
          "formats" : [
            "UNIX"
          ],
          "ignore_failure" : true
        }
      },
      {
        "remove" : {
          "field" : "nagios.timestamp_epoch"
        }
      }
    ],
    "on_failure" : [
      {
        "set" : {
          "field" : "error.message",
          "value" : "{{ _ingest.on_failure_message }}"
        }
      }
    ]
  }
}
```

**Comment by jsoriano** [comment]
@rverchere and @willemdh thanks for your work here!

The failure in CI seems to be caused by some outdated files, `mage fmt update` needs to be run both in `filebeat` and in `x-pack/filebeat`, so it updates the files for the new module in both distributions.

By the way, we are adding new modules in `x-pack/filebeat/module`, @rverchere would you mind to move the new module to `x-pack/filebeat/module/nagios`?

**Comment by rverchere** [comment]
Hi @jsoriano ,

Some busy time here, I'll check it "soon".

**Pull request closed without merging**
