### PR TITLE
libbeat: output ES urls at INFO log level

### PR DESCRIPTION
**Pull request by cyrilleverrier**
I found quite useful to display the list of ES's urls in the log file for sanity check purpose.

### CODE REVIEW

**Comment by ruflin** [comment]
Can you run `make fmt`? Travis does not seem to be happy with the formatting :-)

**Comment by cyrilleverrier** [comment]
@ruflin : fixed and branch is now rebased on top of master. Thanks for your review.

**Comment by ruflin** [comment]
jenkins, test it

**Comment by ruflin** [comment]
jenkins, retest it

**Comment by cyrilleverrier** [comment]
jenkins, test it

**Comment by tsg** [comment]
I ignored Jenkins as the failure couldn't be related

**Comment by cyrilleverrier** [comment]
@tsg and @ruflin : thanks again for merging

**Pull request merged**
