### PR TITLE
[Filebeat] kafka module - Add authentication message parsing (#32229)

### LINKED ISSUE #32229: Filebeat Kafka ingest pipeline can't parse authentication messages for SIEM
**Describe the enhancement:**

Filebeat Kafka ingest pipeline can't parse failed authentication message.
ECS fields important for SIEM like event.category, event.type, event.action, event.outcome and source.ip are missing.
Also geoip and asn data missing for source.ip

Failed authentication message should have fields:

- event.category = "authentication"
- event.type = "logon-failed"
- event.action = "start"
- event.outcome = "failure"
- source.ip

**Describe a specific use case for the enhancement or feature:**

Failed login
```
[2022-07-06 18:22:59,737] INFO [SocketServer listenerType=BROKER, nodeId=1] Failed authentication with /10.10.10.10 (SSL handshake failed) (org.apache.kafka.common.network.Selector)
```

**Steps to reproduce**

```
POST /_ingest/pipeline/filebeat-7.17.4-kafka-log-pipeline/_simulate
{
  "docs": [
    {
      "_source": {
        "@timestamp": "2022-07-06T18:22:59.737Z",
        "message": "[2022-07-06 18:22:59,737] INFO [SocketServer listenerType=BROKER, nodeId=1] Failed authentication with /10.10.10.10 (SSL handshake failed) (org.apache.kafka.common.network.Selector)"
      }
    }
  ]
}
```

Result
```
{
  "docs" : [
    {
      "doc" : {
        "_index" : "_index",
        "_type" : "_doc",
        "_id" : "_id",
        "_source" : {
          "@timestamp" : "2022-07-06T18:22:59.737Z",
          "log" : {
            "level" : "INFO"
          },
          "kafka" : {
            "log" : {
              "class" : "org.apache.kafka.common.network.Selector",
              "component" : "SocketServer listenerType=BROKER, nodeId=1"
            }
          },
          "message" : "Failed authentication with /10.10.10.10 (SSL handshake failed)",
          "event" : {
            "ingested" : "2022-07-06T15:37:04.326892129Z",
            "type" : "info",
            "created" : "2022-07-06T18:22:59.737Z",
            "kind" : "event"
          }
        },
        "_ingest" : {
          "_grok_match_index" : "0",
          "timestamp" : "2022-07-06T15:37:04.326892129Z"
        }
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by leweafan**
## What does this PR do?

Adds kafka authentication message parsing

## Why is it important?

Authentication messages important for SIEM

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes #32229

### CODE REVIEW

**Comment by leweafan** [comment]
Could someone please help with a review?

**Comment by leweafan** [comment]
Hello @endorama! Can I ask you to help with a review?

**Comment by leweafan** [comment]
@efd6 can you help with this PR?

**Comment by miltonhultgren** [comment]
@leweafan The changes in this PR are not cleanly applied to `main`, causing everyone in the repo to be required as a code reviewer. I will close this PR, please update your branch so that your changes are cleanly applied in relation to `main`, then open up a new PR!

**Pull request closed without merging**
