### PR TITLE
Cherry-pick #21454 to 7.x: Update Filebeat module expected logs files

### PR DESCRIPTION
**Pull request by andrewkroh**
Cherry-pick of PR #21454 to 7.x branch. Original message: 

## What does this PR do?

Elasticsearch added country_name to the list of default field for geo in https://github.com/elastic/elasticsearch/pull/62915. So the expected files needed updated.

## Why is it important?

Fixes broken Filebeat module.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Relates https://github.com/elastic/elasticsearch/pull/62915.

### CODE REVIEW

**Review by leehinman — APPROVED** [review]

**Comment by andrewkroh** [comment]
Some tests are failing with:

`2020-10-05T17:05:29.047-0200	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(elasticsearch(http://elasticsearch:9200)): Connection marked as failed because the onConnect callback failed: 1 error: Error loading pipeline for fileset osquery/result: couldn't load pipeline: couldn't load json. Error: 400 Bad Request: {"error":{"root_cause":[{"type":"parse_exception","reason":"processor [append] doesn't support one or more provided configuration parameters [allow_duplicates]","processor_type":"append"}],"type":"parse_exception","reason":"processor [append] doesn't support one or more provided configuration parameters [allow_duplicates]","processor_type":"append"},"status":400}. Response body: {"error":{"root_cause":[{"type":"parse_exception","reason":"processor [append] doesn't support one or more provided configuration parameters [allow_duplicates]","processor_type":"append"}],"type":"parse_exception","reason":"processor [append] doesn't support one or more provided configuration parameters [allow_duplicates]","processor_type":"append"},"status":400}`

Meanwhile this is passing locally for me with `docker.elastic.co/elasticsearch/elasticsearch:7.10.0-SNAPSHOT`                           (1c3379b7cf0a from 7 hours ago).

**Comment by andrewkroh** [comment]
run tests

**Comment by andrewkroh** [comment]
This is failing because https://github.com/elastic/elasticsearch/pull/63257 is not merged yet.

**Comment by andrewkroh** [comment]
run tests

**Comment by andrewkroh** [comment]
run  tests

**Comment by kaiyan-sheng** [comment]
Thank you for fixing this!

**Comment by andrewkroh** [comment]
The build is failing with errors like

`2020-10-07T10:48:29.658-0200	ERROR	[publisher_pipeline_output]	pipeline/output.go:154	Failed to connect to backoff(elasticsearch(http://elasticsearch:9200)): Connection marked as failed because the onConnect callback failed: 1 error: Error loading pipeline for fileset cyberark/corepas: couldn't load pipeline: couldn't load json. Error: 400 Bad Request: {"error":{"root_cause":[{"type":"script_exception","reason":"compile error","processor_type":"append","script_stack":["... ains(ctx?.host?.hostname server?.domain)) || ctx?. ...","                             ^---- HERE"],"script":"ctx?.host?.hostname != null && ctx.host?.hostname != '' && ((ctx?.related?.hosts instanceof List && !ctx?.related?.hosts.contains(ctx?.host?.hostname server?.domain)) || ctx?.related?.hosts != ctx?.host?.hostname server?.domain)","lang":"painless","position":{"offset":150,"start":125,"end":175}}],"type":"script_exception","reason":"compile error","processor_type":"append","script_stack":["... ains(ctx?.host?.hostname server?.domain)) || ctx?. ...","                             ^---- HERE"],"script":"ctx?.host?.hostname != null && ctx.host?.hostname != '' && ((ctx?.related?.hosts instanceof List && !ctx?.related?.hosts.contains(ctx?.host?.hostname server?.domain)) || ctx?.related?.hosts != ctx?.host?.hostname server?.domain)","lang":"painless","position":{"offset":150,"start":125,"end":175},"caused_by":{"type":"illegal_argument_exception","reason":"invalid sequence of tokens near ['server'].","caused_by":{"type":"no_viable_alt_exception","reason":null}}},"status":400}. Response body: {"error":{"root_cause":[{"type":"script_exception","reason":"compile error","processor_type":"append","script_stack":["... ains(ctx?.host?.hostname server?.domain)) || ctx?. ...","                             ^---- HERE"],"script":"ctx?.host?.hostname != null && ctx.host?.hostname != '' && ((ctx?.related?.hosts instanceof List && !ctx?.related?.hosts.contains(ctx?.host?.hostname server?.domain)) || ctx?.related?.hosts != ctx?.host?.hostname server?.domain)","lang":"painless","position":{"offset":150,"start":125,"end":175}}],"type":"script_exception","reason":"compile error","processor_type":"append","script_stack":["... ains(ctx?.host?.hostname server?.domain)) || ctx?. ...","                             ^---- HERE"],"script":"ctx?.host?.hostname != null && ctx.host?.hostname != '' && ((ctx?.related?.hosts instanceof List && !ctx?.related?.hosts.contains(ctx?.host?.hostname server?.domain)) || ctx?.related?.hosts != ctx?.host?.hostname server?.domain)","lang":"painless","position":{"offset":150,"start":125,"end":175},"caused_by":{"type":"illegal_argument_exception","reason":"invalid sequence of tokens near ['server'].","caused_by":{"type":"no_viable_alt_exception","reason":null}}},"status":400}`

**Comment by marc-gr** [comment]
Seems to be an error introduced in the last changes I did to some of the pipelines, will check if there are others and open a PR fixing it.

**Review by kaiyan-sheng — APPROVED** [review]
CI is green 👍

**Pull request merged**
