### PR TITLE
Update geoip data after change in ES snapshot

### PR DESCRIPTION
**Pull request by jsoriano**
And increase max compilation rate for scripts in pipeline in 
filebeat modules tests.

### CODE REVIEW

**Comment by jsoriano** [comment]
> Assuming this is something related to ES 7.5 and on, I guess this will need to have a 7.x and 7.5 port

I haven't seen this failing in 7.x branches, but yes, if the change in ES is backported we will have to regenerate files in these branches too.

**Comment by odacremolbap** [comment]
oh, sorry, I assumed from now on ES would change it's GeoIP output, and that _hypothetical_ 7.5.x, 7.6.x releases would need it.

probably I made up that scenario since 7.x is not failing.

thanks for explaining

**Comment by jsoriano** [comment]
Tests failed in jenkins because of:
```
Too many dynamic script compilations within, max: [1000/1m]; please use indexed, or scripts with parameters instead; this limit can be changed by the [script.max_compilations_rate] setting
```
This is not directly related to this change but I am going to increase this limit by now. There are plans to refactor the affected pipelines so this limit is not reached.

**Comment by ycombinator** [comment]
BTW, here's the change in ES that is causing the changes in GeoIP lookups: https://github.com/elastic/elasticsearch/pull/49308.

**Comment by ycombinator** [comment]
Travis CI is green and Jenkins CI failures are unrelated. Merging. Thanks for fixing @jsoriano!

**Pull request merged**
