### PR TITLE
[Filebeat] Fix of syslog parsing for Priority value <0> ( #11010 )

### PR DESCRIPTION
**Pull request by DebashisMondal**
Fix of #11010 in elastic/beat branch

### CODE REVIEW

**Comment by kvch** [comment]
I think this part also needs to be fixed: https://github.com/elastic/beats/blob/master/filebeat/input/syslog/syslog_rfc3164.rl#L10

**Comment by kvch** [comment]
@ph could you please review this fix?

**Comment by DebashisMondal** [comment]
> I think this part also needs to be fixed: https://github.com/elastic/beats/blob/master/filebeat/input/syslog/syslog_rfc3164.rl#L10

I have verified the above mentioned file. But I have not found anything to be fixed here.

I have verified my proposed fix locally. It is working. 

@kvch Thank you for requesting review

**Comment by DebashisMondal** [comment]
> I think this part also needs to be fixed: https://github.com/elastic/beats/blob/master/filebeat/input/syslog/syslog_rfc3164.rl#L10

I don't think any changes is required in this file.

I have locally verified the fix which is perfectly working. If any case the above need to be change then kindly let me know.

**Comment by kvch** [comment]
In the meantime could you please "sign" the CLA?

**Comment by DebashisMondal** [comment]
> In the meantime could you please "sign" the CLA?

I am able to sign this on Monday. Is it fine?

**Comment by ph** [comment]
Changes look good to me.

@DebashisMondal you only need to sign the CLA once and it will be valid for all the other PRs you are making. 

Can you also add an entry to the [changelog](https://github.com/elastic/beats/blob/master/CHANGELOG.next.asciidoc)?

**Comment by DebashisMondal** [comment]
@ph can I change the agreement type in future?
Yes, I will make an entry in changelog.

**Comment by kvch** [comment]
jenkins test this

**Comment by ph** [comment]
@DebashisMondal changing from what to what?

**Comment by DebashisMondal** [comment]
@ph in which changelog I have to change? In master or in 6.6 .
In which changelog file I have to change
  1. CHANGELOG-developer.asciidoc
  2. CHANGELOG-developer.next.asciidoc
  3. CHANGELOG.asciidoc
  4. CHANGELOG.next.asciidoc

Kindly let me know as I am contributing for the first time.

**Comment by kvch** [comment]
Please add the entry to CHANGELOG.next.asciidoc on master.

**Comment by DebashisMondal** [comment]
@kvch can you please verify the pull request for changelog? Why it gets failed during Integration. Can you please let me know as I am new to this. 

Thanks

**Comment by kvch** [comment]
Those issues are not related to your change. Do you mind adding the new changelog entry to this pull request?

**Comment by DebashisMondal** [comment]
@kvch, Actually I am not much more familiar with the pulls.
Basically in this pull request I have done the changes in 6.6 version but you suggested me to add the changelog in master, so for that reason I have made the changes with new pull request but somehow it fails.

If you don't mind can you add the changelog in behalf of me. If you have any suggestion kindly let me know.

**Comment by kvch** [comment]
Hm. That's interesting. I recall checking the base branch and it said master. I might dreamed that. Sorry about that.
Could you please open a new pull request to master which contains both this fix and the changelog entry? Our strategy is to open a PR to master and then backport the changes to the required versions.

**Comment by DebashisMondal** [comment]
@kvch Is it not possible to merge the changes from this pull request to the master. Is it mandatory to open pull request in master.

In addition before opening pull request I want to know why the chagelog regarding PR which I have mentioned here gets failed in Build. Can you tell me the reasons?

And one more thing in Changelog of master I observed that the pull request for the fix is referred in other cases. But if I open a new pull request in master then what will the reference for the fix (Bug reference or anything else?

**Comment by DebashisMondal** [comment]
@ph If changes looks good to you kindly approve the changes

**Comment by DebashisMondal** [comment]
> Changes look good to me.
> 
> @DebashisMondal you only need to sign the CLA once and it will be valid for all the other PRs you are making.
> 
> Can you also add an entry to the [changelog](https://github.com/elastic/beats/blob/master/CHANGELOG.next.asciidoc)?

**Comment by kvch** [comment]
You could change the base branch to master of this PR instead of opening a new one.

You changelog PR is failing because Travis failed to install the requiested dependencies of an unrelated job: https://travis-ci.org/elastic/beats/jobs/502463779#L420
It's nothing to worry about.

**Comment by DebashisMondal** [comment]
@kvch  when I am changing the base branch to master it is showing some conflicts, so what to do now?

**Comment by kvch** [comment]
You could rebase it. But I think it would be easier to apply the patch to master and force push this branch with that single commit.

**Comment by DebashisMondal** [comment]
@kvch In addition I want to know that when the review will be marked as completed by @ph. Is there any gap?

**Comment by ph** [comment]
I am approving the change for the file, but could you target the **master branch** and [rebase your PR on top of master](https://git-scm.com/docs/git-rebase) and include https://github.com/elastic/beats/pull/11107 as part of the same PR this make it easier to backport everything and make a cleaner history. If you have problem doing that, myself or @kvch could do it but we would have to do some trickery because we want to keep your authorship of the work.

**Comment by DebashisMondal** [comment]
@ph, Basically I committed the fix in version 6.6 but as suggested by @kvch when I am trying to rebase it to master branch I am getting some conflicts. I have changed the changelog in master branch #11107 .

Keeping my authorship, you (@ph and @kvch ) can do whatever is required.

And one more thing @ph, as you approving the changes kindly change the review status, it is still showing "Awaiting requested review from ph"

**Comment by kvch** [comment]
To eliminate the conflict, you could try to cherry-pick your commit on top of master.

Update your master branch. Make sure you don't have any unstaged changes, as resetting removes everything. You can skip this step, if your master branch is up to date with the master in this repo (`upstream` is this repo).

```
git fetch upstream
git checkout master
git reset --hard upstream/master
```

Cherry-pick this commit on top of a new branch.
```
git checkout -b fix-filebeat-syslog-priority
git cherry-pick 2b2794debb314bfe73d8ccd77190c2dc0e4bc5fc
git push origin fix-filebeat-syslog-priority
```

After you have pushed the branch, open a PR with the base branch master. Your new PR will be approved if it's opened for the correct base branch.

Let me know if you need further assistance.

**Comment by DebashisMondal** [comment]
@kvch can I also cherry-pick the commit of #11107 ?

**Comment by kvch** [comment]
Sure. That would be even better. :)

**Comment by DebashisMondal** [comment]
Actually I want to know @kvch that after opening new PR this PR will be valid or not?

**Comment by DebashisMondal** [comment]
@kvch I am getting below error during cherry-pick

[root@localhost beats]# git cherry-pick 2b2794debb314bfe73d8ccd77190c2dc0e4bc5fc
fatal: bad object 2b2794debb314bfe73d8ccd77190c2dc0e4bc5fc

**Comment by DebashisMondal** [comment]
@kvch  and @ph I have created a new pull request for master branch kindly look at this

**Comment by DebashisMondal** [comment]
@kvch  as #11288  is approved, So can I close this pull request?

**Comment by kvch** [comment]
Closing as #11288 has been opened.

**Pull request closed without merging**
