### PR TITLE
Update Auditbeat docs / fields / dashboards

### LINKED ISSUE #5947: Auditbeat getting started example is obsolete.
The example configuration in "getting started" appears to use the old Metricbeat-style syntax, including the `metricsets` key.

https://github.com/elastic/beats/blob/master/auditbeat/docs/getting-started.asciidoc#step-2-configure-beatname_uc

### PR DESCRIPTION
**Pull request by andrewkroh**
Update Auditbeat docs and add missing fields   f65f1ae
- Fixes #5947

Update Kibana 6 dashboards for new field names   114b5bc

 - Due to field name changes all Kibana objects needed an update.

Add 5.x Auditbeat dashboards

- I converted the 6.x dashboard to 5.x. (very time consuming)

### CODE REVIEW

**Comment by andrewkroh** [comment]
It probably doesn't matter if they are squashed. I don't think any of this will be back-ported.

**Comment by andrewkroh** [comment]
jenkins, test it

**Comment by ph** [comment]
jenkins test this please

**Comment by ph** [comment]
jenkins test this please

**Pull request merged**
