### PR TITLE
Add zfs beat

### PR DESCRIPTION
**Pull request by maireanu**
Querying ZFS Storage and Pool Status

### CODE REVIEW

**Comment by ruflin** [comment]
Great to see a zfsbeat. Could you sign the CLA @maireanu https://www.elastic.co/contributor-agreement ?

**Comment by ph** [comment]
@maireanu I wonder if we could make it a metricbeat module instead of a stand alone beat?

**Comment by maireanu** [comment]
> 
> 
> Great to see a zfsbeat. Could you sign the CLA @maireanu https://www.elastic.co/contributor-agreement ?

Did sign the CLA

**Comment by ruflin** [comment]
@maireanu Thanks for the contribution. +1 on the comment from @ph

**Comment by maireanu** [comment]
@ph I do not really think this is possible. But if you know a way, I can help you with that.

**Comment by ruflin** [comment]
@maireanu Can you elaborate on why you think it is not possible? Looking at https://github.com/maireanu/zfsbeat/blob/master/beater/zfsbeat.go#L51 it seems to be the typical periodic polling that Metricbeat does. It seems you have 3 different metricsets in there: `Zpool, Snapshot, Filesystem`. 

Here is a guide on how to create a metricbeat module: https://www.elastic.co/guide/en/beats/devguide/current/creating-metricbeat-module.html

**Comment by maireanu** [comment]
I was tinking form the container point of view.

**Comment by ruflin** [comment]
Metricbeat would have to be run in the same place as you run zfsbeat.

**Comment by maireanu** [comment]
Alright then, maybe I will give it a try and add it to the metric beat as a module.

**Comment by ph** [comment]
Thanks @maireanu for taking a look.

**Pull request merged**
