### PR TITLE
[WIP] packetbeat kafka protocol analyzer

### PR DESCRIPTION
**Pull request by urso**
This PR adds a kafka protocol analyzer to packetbeat.

TODO:

- [x] add documentation to docs
- [ ] add code documentation
- [ ] add fields.yml
- [x] default configuration
- [ ] minimal dashboard
- [ ] add tests with sample traces

### CODE REVIEW

**Comment by ruflin** [comment]
@urso As this one would be pretty nice to have in Packetbeat I wonder if perhaps someone else could take this one over? Perhaps @adriansr as he was doing quite a bit recently on Packetbeat?

**Comment by urso** [comment]
Rebased PR on top of master.

**Comment by urso** [comment]
Closing. No progress for some time. If there is still some interest, please contact us by commenting on this PR.

**Comment by JonBruchim** [comment]
Hi, just seen this PR.
I'd like to know whats the status of this PR, thanks!

**Pull request closed without merging**
