### PR TITLE
Correct typo

### PR DESCRIPTION
**Pull request by ritwik12**
multiline was spelled wrong

### CODE REVIEW

**Comment by ruflin** [comment]
jenkins, test this

**Comment by ritwik12** [comment]
It's just a simple typo correction, I don't know why is it failing. :(

**Comment by andrewkroh** [comment]
It's failing because the file you changed gets generated and checked in. The input is at

https://github.com/elastic/beats/blob/master/filebeat/_meta/common.p2.yml#L42

After fixing `filebeat/_meta/common.p2.yml` then running `make update` from within the filebeat dir will regenerate the config files. And CI should be happy. 👍 

The error from CI is "needs update". https://travis-ci.org/elastic/beats/jobs/402553451#L832

**Comment by andrewkroh** [comment]
But perhaps this was already fixed by https://github.com/elastic/beats/pull/7456?

**Comment by ruflin** [comment]
Yes, I think it's also fixed there. Will close the PR.

@ritwik12 Thanks for opening the PR, coincidence that it was fixed in 2 places at the same.

**Pull request closed without merging**
