### PR TITLE
Update version.asciidoc

### PR DESCRIPTION
**Pull request by v1v**
## What does this PR do?

7.17 was created a bit manually, so I don't know if those fields need to be updated

### CODE REVIEW

**Review by ruflin — COMMENTED** [review]
@andresrc When exactly does the doc branch have to be updated? I assume now is fine?

**Review by andresrc — APPROVED** [review]
yes, I think it's fine

**Comment by v1v** [comment]
Bumping the version required to change the auto-generated files, otherwise the `make check` goal will fail. That's the reason of those 100 files

**Review by cmacknz — APPROVED** [review]

**Pull request merged**
