### PR TITLE
metricbeat: add cluster_stats metricset into elasticsearch module

### PR DESCRIPTION
**Pull request by wangdisdu**
the `cluster_stats` include follow metrics:
- `cluster.stats.status`
- `cluster.stats.indices.count`
- `cluster.stats.indices.shards.total`
- `cluster.stats.indices.docs.count`
- `cluster.stats.indices.segments.count`
- `cluster.stats.nodes.count.total`
- `cluster.stats.nodes.jvm.mem.heap.used`
- `cluster.stats.nodes.jvm.mem.heap.max`
- `cluster.stats.nodes.fs.total.bytes`
- `cluster.stats.nodes.fs.free.bytes`
- `cluster.stats.nodes.fs.available.bytes`

### CODE REVIEW

**Comment by ruflin** [comment]
@wangdisdu Would you mind opening a more generic issue like "Metricbeat Elasticsearch module stats" to discuss on a more high level which metrics we should add to the module and which ones we shouldn't. I think we should make here a more high level decision.

**Comment by wangdisdu** [comment]
@ruflin Thanks for your reviewed. I have opened the issue [5965](https://github.com/elastic/beats/issues/5965) for this.

**Comment by ruflin** [comment]
@wangdisdu Time has come to move forward here. Are you still interested to work on this? If yes will have a detailed look at the PR.

**Comment by ruflin** [comment]
I'm closing this one as it has been stale for some time.

@wangdisdu I would still like to get these metrics into the module so please reopen if you find time.

**Pull request closed without merging**
