### PR TITLE
[Heartbeat] Allow to specify port ranges for tcp monitors 

### PR DESCRIPTION
**Pull request by shahzad31**
Fixes https://github.com/elastic/beats/issues/18613

User can specify port as ranges in tcp monitors, idea came out of this forum post 

https://discuss.elastic.co/t/heartbeat-tcp-port-ranges/232377

### CODE REVIEW

**Comment by andrewvc** [comment]
jenkins, test this

**Comment by andrewvc** [comment]
jenkins, retest this please

**Comment by shahzad31** [comment]
@andrewvc should we close this, as we discussed this might be abused by users.

**Comment by andrewvc** [comment]
Yep, closing.

**Pull request closed without merging**
