### PR TITLE
bugfix: fix a typo in libbeat/outputs/transport/client.go

### PR DESCRIPTION
**Pull request by moooofly**
I think there is a bug in https://github.com/elastic/beats/blob/master/libbeat/outputs/transport/client.go#L177

- original

```golang
func (c *Client) RemoteAddr() net.Addr {
	conn := c.getConn()
	if conn != nil {
		return c.conn.LocalAddr()
	}
	return nil
}
```

- update

```golang
func (c *Client) RemoteAddr() net.Addr {
	conn := c.getConn()
	if conn != nil {
		return c.conn.RemoteAddr()
	}
	return nil
}
```

### CODE REVIEW

**Comment by ph** [comment]
Jenkins test this please

**Comment by ph** [comment]
@moooofly Yup indeed it look like a typo, do you mind adding a changelog item to https://github.com/elastic/beats/blob/master/CHANGELOG.next.asciidoc ?

**Comment by moooofly** [comment]
@ph OK, I will do it.

**Comment by moooofly** [comment]
Is there something I can do? @ph 😃

**Comment by ph** [comment]
@moooofly merged thanks for the PR!

**Pull request merged**
