### PR TITLE
fix: use multiarch ARM Docker images on any architecture

### PR DESCRIPTION
**Pull request by kuisathaverat**
## What does this PR do?

Remove a workaround added to force to use ARM Docker images on ARM architectures to build ARM binaries.

## Why is it important?

This workaround is no longer need on the golang-crossbuild Docker images, we publish multiarch Docker images for the arm flavor.

## Checklist

- [X] My code follows the style guidelines of this project
- ~~[] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Author's Checklist

- [ ]

## How to test this PR locally

on an ARM64 machine run the command `PLATFORMS="linux/arm64" mage package` on any beat.

## Related issues

- Related to https://github.com/elastic/golang-crossbuild/issues/153

### CODE REVIEW

**Comment by kuisathaverat** [comment]
This requires Go 1.18.2, the main is still on 1.17.10

**Review by mdelapenya — APPROVED** [review]

**Pull request merged**
