### PR TITLE
[Filebeat] Check compatibility of field types in pythonIntegTest

### PR DESCRIPTION
**Pull request by leehinman**
## What does this PR do?
Makes sure the types documented in fields.yml is compatible
with the objects created when running the pythonIntegTest.

## Why is it important?
If the type of the data is incorrect you may not get the kind of
performance you expect, for example using string data type for a range
query.

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## How to test this PR locally
```
mage -v pythonIntegTest
```

### CODE REVIEW

**Comment by leehinman** [comment]
This results in errors like:
```
Exception: Documentation Errors:
Key 'fortinet.firewall.sessionid' found in event has incompatible type expected 'integer' got '<class 'str'>'!
Key 'fortinet.firewall.cat' found in event has incompatible type expected 'integer' got '<class 'str'>'!

Exception: Documentation Errors:
Key 'aws.cloudtrail.read_only' found in event has incompatible type expected 'keyword' got '<class 'bool'>'!

Exception: Documentation Errors:
Key 'source.port' found in event has incompatible type expected 'long' got '<class 'str'>'!
Key 'aws.elb.backend.http.response.status_code' found in event has incompatible type expected 'keyword' got '<class 'int'>'!
```

**Comment by leehinman** [comment]
Adding this check results in the following errors in Filebeat & Metricbeat.

# metricbeat
## uWSGI module outputs an event

    Exception: Documentation Errors:   
    Key 'uwsgi.status.worker.rss' found in event has incompatible type expected 'keyword' got '<class 'int'>'!

## php_fpm_pool metricset test

    Exception: Documentation Errors:
    Key 'php_fpm.pool.start_time' found in event has incompatible type expected 'date' got '<class 'int'>'!

## haproxy stat http metricset test

    Exception: Documentation Errors:
    Key 'haproxy.stat.agent.rise' found in event has incompatible type expected 'integer' got '<class 'str'>'!
    Key 'haproxy.stat.agent.fall' found in event has incompatible type expected 'integer' got '<class 'str'>'!
    Key 'haproxy.stat.agent.health' found in event has incompatible type expected 'integer' got '<class 'str'>'!
    Key 'haproxy.stat.agent.check.rise' found in event has incompatible type expected 'integer' got '<class 'str'>'!
    Key 'haproxy.stat.agent.check.health' found in event has incompatible type expected 'integer' got '<class 'str'>'!
    Key 'haproxy.stat.check.agent.last' found in event has incompatible type expected 'integer' got '<class 'str'>'!

## ceph metricsets tests

    Exception: Documentation Errors:
    Key 'ceph.monitor_health.store_stats.last_updated' found in event has incompatible type expected 'long' got '<class 'str'>'!

## test_enable_timeseries

    Exception: Documentation Errors:
    Key 'timeseries.instance' found in event has incompatible type expected 'keyword' got '<class 'int'>'!

# filebeat
## apache

    Exception: Documentation Errors:
    Key 'source.port' found in event has incompatible type expected 'long' got '<class 'str'>'!

## elasticsearch

    Exception: Documentation Errors:
    Key 'elasticsearch.gc.phase.cpu_time.real_sec' found in event has incompatible type expected 'float' got '<class 'str'>'!
    Key 'elasticsearch.gc.phase.cpu_time.sys_sec' found in event has incompatible type expected 'float' got '<class 'str'>'!
    Key 'elasticsearch.gc.phase.cpu_time.user_sec' found in event has incompatible type expected 'float' got '<class 'str'>'!
    Key 'elasticsearch.gc.phase.duration_sec' found in event has incompatible type expected 'float' got '<class 'str'>'!
    Key 'elasticsearch.gc.jvm_runtime_sec' found in event has incompatible type expected 'float' got '<class 'str'>'!
    Key 'elasticsearch.gc.old_gen.size_kb' found in event has incompatible type expected 'integer' got '<class 'str'>'!
    Key 'elasticsearch.gc.old_gen.used_kb' found in event has incompatible type expected 'integer' got '<class 'str'>'!
    Key 'elasticsearch.gc.heap.size_kb' found in event has incompatible type expected 'integer' got '<class 'str'>'!
    Key 'elasticsearch.gc.heap.used_kb' found in event has incompatible type expected 'integer' got '<class 'str'>'!
    Key 'process.pid' found in event has incompatible type expected 'long' got '<class 'str'>'!
    Key 'elasticsearch.server.gc.young.one' found in event has incompatible type expected 'long' got '<class 'str'>'!
    Key 'elasticsearch.server.gc.young.two' found in event has incompatible type expected 'long' got '<class 'str'>'!
    Key 'elasticsearch.slowlog.total_shards' found in event has incompatible type expected 'keyword' got '<class 'int'>'!
    Key 'elasticsearch.slowlog.total_hits' found in event has incompatible type expected 'keyword' got '<class 'int'>'!


## mysql

    Exception: Documentation Errors:
    Key 'mysql.slowlog.last_errno' found in event has incompatible type expected 'keyword' got '<class 'int'>'!
    Key 'mysql.slowlog.killed' found in event has incompatible type expected 'keyword' got '<class 'int'>'!
    Key 'mysql.thread_id' found in event has incompatible type expected 'long' got '<class 'str'>'!
    Key 'mysql.slowlog.log_slow_rate_limit' found in event has incompatible type expected 'keyword' got '<class 'int'>'!
    Key 'mysql.slowlog.tmp_disk_tables' found in event has incompatible type expected 'long' got '<class 'str'>'!


## nginx

    Exception: Documentation Errors:
    Key 'nginx.ingress_controller.upstream.port' found in event has incompatible type expected 'long' got '<class 'str'>'!
    Key 'destination.port' found in event has incompatible type expected 'long' got '<class 'str'>'!


## nats

    Exception: Documentation Errors:
    Key 'process.pid' found in event has incompatible type expected 'long' got '<class 'str'>'!


# x-pack/filebeat
## aws/cloudtrail

    Exception: Documentation Errors:
    Key 'aws.cloudtrail.read_only' found in event has incompatible type expected 'keyword' got '<class 'bool'>'!

## aws/ec2

    Exception: Documentation Errors:
    Key 'process.pid' found in event has incompatible type expected 'long' got '<class 'str'>'!


## aws/elb

    Exception: Documentation Errors:
    Key 'source.port' found in event has incompatible type expected 'long' got '<class 'str'>'!
    Key 'aws.elb.backend.http.response.status_code' found in event has incompatible type expected 'keyword' got '<class 'int'>'!

## aws/s3access

    Exception: Documentation Errors:
    Key 'event.duration' found in event has incompatible type expected 'long' got '<class 'str'>'!


## azure/signinlogs

    Exception: Documentation Errors:
    Key 'log.level' found in event has incompatible type expected 'keyword' got '<class 'int'>'!
    Key 'azure.signinlogs.properties.is_interactive' found in event has incompatible type expected 'keyword' got '<class 'bool'>'!
    Key 'azure.signinlogs.properties.status.error_code' found in event has incompatible type expected 'keyword' got '<class 'int'>'!

## cef/log

    Exception: Documentation Errors:
    Key 'event.id' found in event has incompatible type expected 'keyword' got '<class 'int'>'!
    Key 'checkpoint.event_count' found in event has incompatible type expected 'long' got '<class 'str'>'!
    Key 'cef.extensions.baseEventCount' found in event has incompatible type expected 'long' got '<class 'str'>'!
    Key 'event.severity' found in event has incompatible type expected 'long' got '<class 'str'>'!
    Key 'event.risk_score' found in event has incompatible type expected 'float' got '<class 'str'>'!

## checkpoint/firewall

    Exception: Documentation Errors:
    Key 'checkpoint.match_id' found in event has incompatible type expected 'integer' got '<class 'str'>'!
    Key 'checkpoint.parent_rule' found in event has incompatible type expected 'integer' got '<class 'str'>'!

## cisco/asa

    Exception: Documentation Errors:
    Key 'event.code' found in event has incompatible type expected 'keyword' got '<class 'int'>'!
    Key 'network.iana_number' found in event has incompatible type expected 'keyword' got '<class 'int'>'!

## cisco/ftd

    Exception: Documentation Errors:
    Key 'network.iana_number' found in event has incompatible type expected 'keyword' got '<class 'int'>'!
    Key 'event.code' found in event has incompatible type expected 'keyword' got '<class 'int'>'!

## cisco/ios

    Exception: Documentation Errors:
    Key 'igmp.type' found in event has incompatible type expected 'keyword' got '<class 'int'>'!

## crowdstrike/falcon

    Exception: Documentation Errors:
    Key 'crowdstrike.metadata.eventCreationTime' found in event has incompatible type expected 'date' got '<class 'int'>'!
    Key 'crowdstrike.event.StartTimestamp' found in event has incompatible type expected 'date' got '<class 'int'>'!
    Key 'crowdstrike.event.ProcessEndTime' found in event has incompatible type expected 'date' got '<class 'int'>'!

## fortinet/firewall

    Exception: Documentation Errors:
    Key 'fortinet.firewall.sessionid' found in event has incompatible type expected 'integer' got '<class 'str'>'!
    Key 'fortinet.firewall.cat' found in event has incompatible type expected 'integer' got '<class 'str'>'!

## googlecloud/firewall

    Exception: Documentation Errors:
    Key 'network.iana_number' found in event has incompatible type expected 'keyword' got '<class 'int'>'!

## ibmmq/errorlog

    Exception: Documentation Errors:
    Key 'process.pid' found in event has incompatible type expected 'long' got '<class 'str'>'!

## o365/audit

    Exception: Documentation Errors:
    Key 'o365.audit.RecordType' found in event has incompatible type expected 'keyword' got '<class 'int'>'!
    Key 'o365.audit.Version' found in event has incompatible type expected 'keyword' got '<class 'int'>'!
    Key 'o365.audit.UserType' found in event has incompatible type expected 'keyword' got '<class 'int'>'!
    Key 'o365.audit.AzureActiveDirectoryEventType' found in event has incompatible type expected 'keyword' got '<class 'int'>'!
    Key 'o365.audit.LogonType' found in event has incompatible type expected 'keyword' got '<class 'int'>'!
    Key 'o365.audit.ExternalAccess' found in event has incompatible type expected 'keyword' got '<class 'bool'>'!
    Key 'o365.audit.InternalLogonType' found in event has incompatible type expected 'keyword' got '<class 'int'>'!
    Key 'o365.audit.SensitiveInfoDetectionIsIncluded' found in event has incompatible type expected 'keyword' got '<class 'bool'>'!
    Key 'source.port' found in event has incompatible type expected 'long' got '<class 'str'>'!
    Key 'client.port' found in event has incompatible type expected 'long' got '<class 'str'>'!
    Key 'event.code' found in event has incompatible type expected 'keyword' got '<class 'int'>'!
    Key 'o365.audit.CustomUniqueId' found in event has incompatible type expected 'keyword' got '<class 'bool'>'!
    Key 'o365.audit.YammerNetworkId' found in event has incompatible type expected 'keyword' got '<class 'int'>'!
    Key 'o365.audit.ActorYammerUserId' found in event has incompatible type expected 'keyword' got '<class 'int'>'!

## suricata/eve

    Exception: Documentation Errors:
    Key 'suricata.eve.flow_id' found in event has incompatible type expected 'keyword' got '<class 'int'>'!

## zeek/dns

    Exception: Documentation Errors:
    Key 'dns.id' found in event has incompatible type expected 'keyword' got '<class 'int'>'!
    Key 'zeek.dns.trans_id' found in event has incompatible type expected 'keyword' got '<class 'int'>'!

# x-pack/metricbeat

No errors

# Example of how this happens
## s3access

The ingest pipeline has a grok pattern of:

    (?:-|%{NUMBER:aws.s3access.total_time:long})

And as expected in the expected.json file we get a number

    "aws.s3access.total_time": 7,

But then `event.duration` is mapped with a set processor like this:

    - set:
        if: "ctx?.aws?.s3access?.total_time != null"
        field: event.duration
        value: "{{aws.s3access.total_time}}"

This leads to event.duration being a string in the expected.json
file.

    "event.duration": "7",

Which doesn't match ECS which says that event.duration should have a
type of "long".

**Comment by webmat** [comment]
I agree with adding this check 👍 

For the most part, Elasticsearch smooths out some of these issues: sending a string that contains an integer or a float, when the mapping has it marked as an integer/float, will end up being correct in the mapping. The type-specific queries on that field will return the correct results. Even in scripts that work off of the documents after them being saved, the doc values should be in the correct type.

However I still think pipelines processing the events initially, and consumers of the data that use the `_source` document may get issues when the fields aren't properly typecast.

**Comment by webmat** [comment]
I'd be curious to hear from folks working on Kibana apps (e.g. SIEM app), or working on detections, whether this has been causing issues.

cc @dcode @FrankHassanabad

**Pull request closed without merging**
