### PR TITLE
Docs: Asciidoctor compatibilty step 1

### PR DESCRIPTION
**Pull request by nik9000**
Fixes an asciidoctor incompatibility discovered while working on the APM
server.

Mirrors elastic/apm-server#2567

### CODE REVIEW

**Comment by nik9000** [comment]
@bmorelli25, it doesn't look like the second half of elastic/apm-server#2567 merges cleanly here.

**Comment by bmorelli25** [comment]
Ahhh yeah, there was just a big update to those files that we're pulling into APM Server in https://github.com/elastic/apm-server/pull/2542. That's gonna ugly up the APM Server side of things too. Let me take a looksie!

**Comment by exekias** [comment]
Hi folks, I see this want is stalled. Is this change still relevant?

**Comment by nik9000** [comment]
Yeah. I think we can close this. We're already on Asciidoctor.

**Pull request closed without merging**
