### PR TITLE
Provide basic log parsing capability in filebeat

### PR DESCRIPTION
**Pull request by ageetha**
The ability to provide basic log parsing capability in filebeat was discussed under https://github.com/elastic/beats/issues/2644

**The submitted code provides three functionalities**
a) parse the log record using the regex (named regex) present in yml file per prospector

>   `parsingRegex: (?P<was_requestHost>\S+)\s\S+\s\S+\s\[(?P<was_datetime_date>.+)\]\s"(?P<was_requestMethod>\S+)\s(?P<was_uriPath>\S+)(?:\?)?(?P<was_queryString>\S+)?\s(?P<was_requestProtocol>\S+)\s(?P<was_responseCode_int>\S+)\s(?P<was_bytesReceived_long>\S+)\s(?P<was_elapsedTime_long>\S+)?`

b) based on the suffix of field names (_int,_float, _long), convert values of those fields to correct datatype

c) convert fields having _date suffix from format specified under dateFormat (YML config) to  ISO-8601  format (1994-11-05T08:15:30-05:00). 

**Example YML section for WebSphere Application Server's SystemOut.log is as follows**

`parsingRegex: \[(?P<was_datetime_date>.+)\]\s(?P<was_threadId>[\w|\d]+)\s(?P<module>\w+)?\s+?(?P<loglevel>\w{1})\s+(?:(?P<was_className>\w+\.[\w|\.]+)\s(?P<was_methodName>\S+)\s)?(?:(?P<was_messageId>\S+):\s)?(?:.+:\s(?P<was_exceptionName>\w+\.[\w|\.]+Exception))?`

 `dateFormat : "1/02/06 15:04:05:000 GMT-07:00"`

**Example Systemout.log file to test is as follows**

[4/16/16 11:28:41:090 GMT+05:30] 00000028 SystemOut     O inside connect...
[4/16/16 11:28:41:090 GMT+05:30] 00000028 SystemOut     O getting connnection..
[4/16/16 11:28:41:091 GMT+05:30] 00000028 SystemOut     O Connection Successful 
[4/16/16 11:28:41:091 GMT+05:30] 00000028 SystemOut     O forwarding to logonfail
[4/16/16 11:28:41:091 GMT+05:30] 00000028 SystemOut     O requestURL--->/app1/RequestPendingViewAction.do
[4/16/16 11:28:52:815 GMT+05:30] 00000028 SystemOut     O LoginAction processed
[4/16/16 11:28:52:815 GMT+05:30] 00000028 SystemOut     O Email ID : usr@abc.com
[4/16/16 11:28:54:726 GMT+05:30] 00000028 SystemOut     O Authenticate Status : Success
[4/16/16 11:28:54:726 GMT+05:30] 00000028 SystemOut     O empid--->usr@abc.com
[4/16/16 11:28:59:086 GMT+05:30] 00000028 SystemOut     O Url---->/app1/RequestPendingViewAction.do

### CODE REVIEW

**Comment by ageetha** [comment]
@karmi, signed CCLA as Geetha Adinarayan. is there any other requirement ?

**Comment by karmi** [comment]
@ageetha, the check has succeeded now, so OK in that aspect of the PR!

**Comment by tsg** [comment]
@ageetha as per our discussion, I'm closing this PR, because we don't want regexp parsing in Filebeat at the moment. I suggest implementing it as a processor in libbeat, which will simplify your maintenance of it if you want to maintain this in a fork.

**Comment by Nilamkhule** [comment]
So is this something that in filebeat we are not going to add parsing facility?

**Comment by ruflin** [comment]
@Nilamkhule Currently it is not planned.

**Comment by ericpai** [comment]
I have developed a processor called `parse_regex_fields` with several test cases based on v5.4. Could it be added to the official repository, like `decode_json_fields`, as a custom choice?

**Comment by ruflin** [comment]
We currently don't plan adding regexp processors filebeat as this can also be done in Logstash or Ingest in Elasticsearch. Could you share why you needed to do this on the beats side instead of LS or Ingest?

As processors are designed with plugins in mind these can also be developed outside the main repo. For some guidance on this see this post here on outputs: https://github.com/elastic/beats/issues/581#issuecomment-247034174 Adding processors should work very similar.

Is your code open source? Perhaps link it here in case others are interested.

**Comment by ericpai** [comment]
@ruflin Thanks for your reply.
We collect logs by filebeat and output them to Kafka. However, we need to extract each line by a regular expression and capture one or more fields as the topic of Kafka.

Here is my code about `parse_regex_fields`. It just receives only one parameter `regexp`, which should be a regular expression satisfying RE2 syntax. If the `message` field matches `regexp`, those captured subgroup will be exported as root fields of new event.
The link: https://github.com/laincloud/beats/blob/v5.4.0-lain-p1/libbeat/processors/actions/parse_regex_fields.go

**Pull request closed without merging**
