### PR TITLE
[Heartbeat] Allow browser monitors on ARM

### PR DESCRIPTION
**Pull request by andrewvc**
This patch removes the now unnecessary restriction that the extra syscall perms only apply to x86. This was necessary IIRC on centos, where IIRC attempting these syscalls on ARM would cause issues. 

It seems odd that would be the case, regardless, this is tested and works on a graviton2 processor.

Resolves https://github.com/elastic/beats/issues/29034

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

Attempt to run synthetic monitors with an ARM processor. I usually use this one: https://github.com/elastic/synthetics-demo/blob/main/heartbeat/monitors.d/browser-inline.yml . I'd also check that things look good in kibana. This will require synthetics 1.0.0-beta.24 or higher

### CODE REVIEW

**Comment by andrewvc** [comment]
@mergifyio update

**Review by emilioalvap — APPROVED** [review]
LGTM

**Pull request merged**
