### PR TITLE
[7.x] Update geoip data after change in ES snapshot (#14713)

### PR DESCRIPTION
**Pull request by ycombinator**
Backports the following commits to 7.x:
 - Update geoip data after change in ES snapshot  (#14713

**DO NOT MERGE THIS PR** until CI looks good on https://github.com/elastic/beats/pull/14726.

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
https://github.com/elastic/elasticsearch/pull/49308 Hmm is this backported to 7.x in ES?

**Comment by ycombinator** [comment]
Yes, it is: https://github.com/elastic/elasticsearch/commit/224374345071211fc16369a548cbafb9917aad32.

**Comment by ycombinator** [comment]
It looks like this PR is not (yet) necessary. The `7.x` Beats build is using the `7.5.0` ES image, not the `7.6.0` one, where the MaxMind DB has been updated.

**Comment by ycombinator** [comment]
Related: https://github.com/elastic/beats/pull/14725. Once ⬅️ this PR is merged, this PR here will become relevant again, and should be rebased on `7.x`.

**Comment by kaiyan-sheng** [comment]
I think this can be closed? https://github.com/elastic/beats/pull/14761 covered backport of this PR also.

**Pull request closed without merging**
