### PR TITLE
[ci] use ubuntu-18

### PR DESCRIPTION
**Pull request by v1v**
## What does this PR do?

Use `ubuntu-18`

## Why is it important?

EOL for `ubuntu-16`

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Comment by v1v** [comment]
run elasticsearch-ci/docs

**Review by jsoriano — APPROVED** [review]

**Comment by ruflin** [comment]
Interesting that the docs build broke but change LGTM.

**Comment by v1v** [comment]
We are safe to merge this PR, the es-docs check seems unrelated to this particular changeset but something else

**Comment by v1v** [comment]
run elasticsearch-ci/docs

**Pull request merged**
