### PR TITLE
[Filebeat][module][elastisearch] exclude gc and audit log from server fileset

### LINKED ISSUE #30995: Filebeat elasticsearch module sending gc.log even if only server submodule is enabled
### Bug description

Filebeat elasticsearch module sending gc.log even if only server submodule is enabled and gc submodule is disabled.

**/etc/filebeat/modules.d/elasticsearch.yml**

```
- module: elasticsearch
  server:
    enabled: true

  gc:
    enabled: false

  audit:
    enabled: true

  slowlog:
    enabled: true

  deprecation:
    enabled: true
```

gc.log added cause *.log pattern

**/usr/share/filebeat/module/elasticsearch/server/manifest.yml**
```
module_version: 1.0

var:
  - name: paths
    default:
      - /var/log/elasticsearch/*.log
      - /var/log/elasticsearch/*_server.json
    os.darwin:
      - /usr/local/var/lib/elasticsearch/*.log
      - /usr/local/var/lib/elasticsearch/*_server.json
    os.windows:
      - c:/ProgramData/Elastic/Elasticsearch/logs/*.log
      - c:/ProgramData/Elastic/Elasticsearch/logs/*_server.json

ingest_pipeline:
  - ingest/pipeline.yml
  - ingest/pipeline-plaintext.yml
  - ingest/pipeline-json.yml
input: config/log.yml
```

Files like access.log, slowlog.log and deprecation.log excluded but not gc.log

**/usr/share/filebeat/module/elasticsearch/server/config/log.yml**

```
type: log
paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}
exclude_files: [".gz$","_slowlog.log$","_access.log$","_deprecation.log$"]
multiline:
  pattern: '^(\[[0-9]{4}-[0-9]{2}-[0-9]{2}|{)'
  negate: true
  match: after

processors:
# Locale for time zone is only needed in non-json logs
- add_locale.when.not.regexp.message: "^{"
- add_fields:
    target: ''
    fields:
      ecs.version: 1.9.0
```

### Solution

gc.log should be added to exclude_files:

`
exclude_files: [".gz$","_slowlog.log$","_access.log$","_deprecation.log$", "gc.log$"]
`

### Version
Filebeat 7.17.1

### PR DESCRIPTION
**Pull request by alioug**
## What does this PR do?

Fix filebeat sending gc.log even if gc fileset is disabled

## Why is it important?

gc.log is verbose and unnecessarily fills filebeat indices/data streams

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ] Check gc.log is sended when gc fileset is enabled

## How to test this PR locally

Install filebeat and elasticsearch locally, only enable server fileset (disable gc fileset) and check in filebeat indices there is no more gc logs.

## Related issues

- Closes #30995

### CODE REVIEW

**Comment by klacabane** [comment]
Another workaround would be specifying more precise path names in the filebeat configuration to avoid pulling unnecessary files, but it's great to add guards around the suggested defaults. Going that route we'd also have to filter out audit files right ?

**Comment by klacabane** [comment]
@alioug are you still interested in merging this change ? We should also filter out audit logs to be exhaustive

**Comment by alioug** [comment]
yes of course, i will add the audit log file.

**Review by matschaffer — APPROVED** [review]
At first I thought we should add rotated GC as well based on https://github.com/elastic/beats/blob/main/filebeat/module/elasticsearch/gc/manifest.yml#L6

But since the manifest default is `*.log` I think only the initial gc log will get picked up. LGTM!

**Comment by matschaffer** [comment]
I've assigned myself to this and the associated issue to make sure we merge it for @alioug once it's green.

**Comment by matschaffer** [comment]
All green! Merging. Thanks for the fix @alioug !

**Pull request merged**
