### PR TITLE
Improving Top-level-Array support in metricbeat [ http module ]

### PR DESCRIPTION
**Pull request by live-wire**
This PR aims to close the issue: elastic/beats#9743 

**More Context**
elastic/beats#6480 added support for arrays as top-level response. However, the arrays are expected to have items of type `common.MapStr` which should not be the case. Even `[ ["storm"] , "trooper", 1, {"darth": "vader"}]` is a valid JSON response. 
- According to the current implementation (and documentation in #8951), **each item** in the _array-response_ is sent as a separate event. 
- In case the **item** in the array-response is not a valid `common.MapStr`, it is assigned as a value to the key `_data` (Is it okay to do it ?)
- I tried running the integration test using the make target `test-module` but that seems to get stuck. `$make MODULE=http test-module`. I noticed that TravisCI also _skips_ integration checks. (The test always times out while trying to kill old services in the function [EnsureUpWithTimeout](https://github.com/elastic/beats/blob/master/libbeat/tests/compose/compose.go#L49)) How do you suggest I run the integration test ? 😓 

Is this fix acceptable ? 👨‍🚒

### CODE REVIEW

**Comment by ruflin** [comment]
Thanks for starting this. Can you share and example json even that you expect in case of an array?

**Comment by live-wire** [comment]
Hi @ruflin, 

Suppose **metricbeat[http]** hits a REST endpoint for a list of connected systems that returns a JSON that looks like this:
`["system1", "system2", "system3", "system4"]`, currently the implementation would not be able to process it because it expects the list to be `[]common.MapStr` which **should** be something like:
`[ {"name": "system1"}, {"name": "system2"} ...]` and all of these objects will be sent as different events.

The solution proposed will accept _strings_ or _integers_ or anything and assign it to a key (`_data`) and **will not expect the items in the list to be already** of type `common.MapStr`. For this example, this fix will convert the input to this:
`[ {"_data": "system1"}, {"_data": "system2"}, {"_data": "system3"}, {"_data": "system4"}]`
.
.
.
.

PS: These examples were inspired by the example in #9743 and [discussion](https://discuss.elastic.co/t/161342)

**Comment by live-wire** [comment]
Hi @ruflin,
I added a tiny documentation as well 😇

**Comment by ruflin** [comment]
I see in your example above, that you even mix array and non array values. I wonder if we should support that?

For the pure array values, I would expect that it's all sent as 1 array. In Elasticsearch / Lucene every key is automatically an array, so you can sen `foo: ["bar", "blurb"]`. Above you suggest to send 1 event for each entry?

**Comment by live-wire** [comment]
Hey @ruflin, 
So, looking at your suggestion in #9743:
> - []common.MapStr: Array of objects, send multiple docs

☝️ Already done in the existing implementation.
> - []string: Array of strings, my suggestion would be to just send one doc with the array in

☝️ Will change my PR to incorporate this change ☕️ 

What about other valid JSON arrays ?
- Should I send `[]interface{}` as a single doc as well just like `[]string` ?

**Comment by live-wire** [comment]
@ruflin, 
Since reverting back is always an option 🕺,  I updated this PR with your suggestion assuming your answer as *yes* to [this question](https://github.com/elastic/beats/pull/10136#issuecomment-456489186) for now.

**Comment by ruflin** [comment]
@live-wire Can you share some example on what `[]interface{}` would be in JSON form to discuss more specific examples. How is it different from `[]common.MapStr`?

For the PR review: It's on my list but I really want to play around with it locally and probably will not get to it this week. Thanks for your patience.

**Comment by ruflin** [comment]
@live-wire I'm really sorry for the super late reply, this completely slipped through on my end.

For the 4 cases that you showed above, we should discuss what the expected elasticsearch docs are. Here some thoughts:

* []int / []string: To store this in Elasticsearch, we need a field name. For example to store these values under `foo`. Should this be a configuration options? Or should we just put it directly on the prefix we already have?
* `[][]string`/ `[][]int`: I must confess I had to test if these docs actually work in Elasticsearch. They do but like in the previous one, a prefix is needed that would have to be configured.

What I'm asking myself for the second use case is on how the queries would like like that you want to run against these values?

**Comment by ruflin** [comment]
@live-wire Any updates from you on this one?

**Comment by live-wire** [comment]
Hi @ruflin sorry for the delayed response. 

> To store this in Elasticsearch, we need a field name. For example to store these values under foo. Should this be a configuration options? Or should we just put it directly on the prefix we already have?

This is a choice we'd have to make :) My current implementation defines a `DefaultDataKey ` which could be instead read from a configuration file. I personally think that it would be too specific a use case for us to support. 
The issue that PR is trying to solve is already too specific, but it is **needed** as any request which has a top-level array *fails* ⚔️ right now if the items in the array are not _objects_. 😄

**Comment by ruflin** [comment]
The problem we have if we hard code it, is that if one of the top level arrays is `string` and the other `long` ingestion might start to fail. I think having it configurable will be a requirement. The problem we then have is that we can only make this configuration per endpoint which breaks if even the same endpoint exposes multiple formats. Do you have some real world examples on what to expect?

We could also argue, all the values we expect in an array should always be a number and we make it a float or double by default. Like this we would even be able to have a template for it. But your example in the PR description is one with keywords, so I guess this is also not an option.

**Comment by exekias** [comment]
Closing this one due inactivity, I wonder if the https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-http-json.html solves this already?

**Pull request closed without merging**
