### PR TITLE
align service parameters to documentation (#19616)

### PR DESCRIPTION
**Pull request by 111andre111**
corrected for Linux and Windows part to be conform to command line implementation holding 2 dashes:
https://www.elastic.co/guide/en/beats/filebeat/current/command-line-options.html

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by jsoriano** [comment]
jenkins run the tests

**Comment by jsoriano** [comment]
run beats-ci/package

**Comment by urso** [comment]
@jsoriano I think we can go ahead here. AFAIK the default test suite does not really test the changes. The beats-tester should have some related tests though.

**Pull request merged**
