### PR TITLE
Release CockroachDB metricbeat module as GA

### LINKED ISSUE #14064: Move cockroachdb module to GA
- Ensure the [requirements](https://github.com/elastic/beats/blob/master/.github/ISSUE_TEMPLATE/module-checklist.md) are met.
- Move the module to GA

### PR DESCRIPTION
**Pull request by jsoriano**
Fixes https://github.com/elastic/beats/pull/14064.

### CODE REVIEW

**Comment by jsoriano** [comment]
Kibana Home tutorial added in https://github.com/elastic/kibana/pull/49672

**Comment by jsoriano** [comment]
jenkins, test this again please

**Comment by jsoriano** [comment]
I will wait to make this module GA, as I think that fields can change in the future:
* We are not doing any mapping on the fields we take from prometheus, this could be reevaluated in the future.
* This service uses lots of histogram metrics, we may have a different way of storing these metrics in the following releases.

**Comment by jlind23** [comment]
@jsoriano  - Closing this one as there were no activity for a while

**Pull request closed without merging**
