### PR TITLE
Recognize log level in Elasticsearch JVM logs

### LINKED ISSUE #34054: Add GC log level for Elasticsearch
Elasticsearch 8.7.0 will change the JVM log output format to include a `level` parameter (see https://github.com/elastic/elasticsearch/pull/92382); the available log levels are described in the [java man page](https://docs.oracle.com/en/java/javase/19/docs/specs/man/java.html#xlog-tags-and-levels). As there is an [existing ingest pipeline to ingest GC logs](https://github.com/elastic/beats/blob/2263f3ed42e6299a2cf2c85d10084b0b2f48694d/filebeat/module/elasticsearch/gc/ingest/pipeline.yml#L35), it needs to be adapted as well (only the `JVM9HEADER` will need to change).

Here are some example log lines:

Before this change:

```
[2022-12-15T06:19:16.936+0000][15181][gc,start    ] GC(0) Pause Young (Normal) (G1 Evacuation Pause)
```

After this change:

```
[2022-12-15T06:22:27.932+0000][16320][info][gc,start    ] GC(0) Pause Young (Normal) (G1 Evacuation Pause)
[2022-12-15T06:22:27.932+0000][16320][debug][gc,age      ] GC(0) Desired survivor size 14680064 bytes, new threshold 15 (max threshold 15)
[2022-12-15T06:22:27.935+0000][16320][info ][gc,phases   ] GC(0)   Pre Evacuate Collection Set: 0.1ms
[2022-12-15T06:22:27.935+0000][16320][trace][gc,age      ] GC(0) Age table with threshold 15 (max threshold 15)
```

Notice how the log level might have trailing spaces (third line in the example).

I'm not familiar enough with `grok` but I believe the grok pattern would need to change to something like:

```
 JVM9HEADER: \[%{TIMESTAMP_ISO8601:timestamp}\]\[%{DATA:elasticsearch.gc.level}%{SPACE}\]\[%{POSINT:process.pid}\]\[%{DATA:elasticsearch.gc.tags}%{SPACE}\]
```

where `elasticsearch.gc.level`  needs to be optional to support also pre 8.7.0 clusters. It should also end up in [`log.level`](https://www.elastic.co/guide/en/ecs/current/ecs-log.html#field-log-level) when present.

### PR DESCRIPTION
**Pull request by danielmitterdorfer**
## What does this PR do?

Elasticsearch will add a log level to its JVM logs to allow users to help them detect errors / warnings more easily in elastic/elasticsearch#92382. With this commit we detect this new field if present and continue to recognize the prior log format which does not contain a log level.

## Why is it important?

This change is required to keep compatibility with Elasticsearch's JVM log output.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

Relates elastic/elasticsearch#92382
Closes #34054

### CODE REVIEW

**Comment by danielmitterdorfer** [comment]
There is one thing where I'm specifically looking for guidance from reviewers. In line with `elasticsearch.gc.tags`, I've put the log level in `elasticsearch.gc.level` but I wonder whether it makes more sense to put it into [`log.level`](https://www.elastic.co/guide/en/ecs/current/ecs-log.html#field-log-level) instead.

**Comment by danielmitterdorfer** [comment]
`x-pack/filebeat-pythonIntegTest` is currently failing but none of the failing tests are related to the Elasticsearch module (the failures are in `cyberarkpa` and `cisco`).

**Comment by ruflin** [comment]
Lets make sure, any change we add here also makes it into the integrations package: https://github.com/elastic/integrations/tree/main/packages/elasticsearch/data_stream/gc

**Comment by danielmitterdorfer** [comment]
Lee has already opened an issue for that: https://github.com/elastic/integrations/issues/4842. :)

**Review by leehinman — CHANGES_REQUESTED** [review]
I think `log.level` is the way to go, otherwise everything looks great.

**Comment by danielmitterdorfer** [comment]
> I think log.level is the way to go, otherwise everything looks great.

Great, thanks for having a look @leehinman . Is this as simple as just changing the grok pattern from

```
(\[%{DATA:elasticsearch.gc.level}%{SPACE}\])?
```

to 

```
(\[%{DATA:log.level}%{SPACE}\])?
```

or am I missing something?

**Comment by danielmitterdorfer** [comment]
I've pushed the rename now in https://github.com/elastic/beats/pull/34159/commits/24cf0bb254f6833d3d120a90d17326d68b248d93. @leehinman can you please take another look?

**Comment by miltonhultgren** [comment]
> Lee has already opened an issue for that: [elastic/integrations#4842](https://github.com/elastic/integrations/issues/4842). :)

@danielmitterdorfer When will that work be done and by whom?

**Comment by danielmitterdorfer** [comment]
> @danielmitterdorfer When will that work be done and by whom? My team is tagged for it but it's not planned on our part.

@miltonhultgren I would hope it's not much effort once this change is in (basically copy & paste what's done here)? I'd like to see this change being released with 8.7.0. I can attempt to do this myself but will require some guidance.

**Review by leehinman — APPROVED** [review]
LGTM

**Comment by leehinman** [comment]
> > @danielmitterdorfer When will that work be done and by whom? My team is tagged for it but it's not planned on our part.
> 
> @miltonhultgren I would hope it's not much effort once this change is in (basically copy & paste what's done here)? I'd like to see this change being released with 8.7.0. I can attempt to do this myself but will require some guidance.

Let me know if you want help.

**Comment by miltonhultgren** [comment]
@danielmitterdorfer @leehinman Okay, I had to confirm with our expert about what would be affected but it seems like a small change so I think we can handle that, I'm putting it into our queue!

**Review by miltonhultgren — APPROVED** [review]

**Comment by danielmitterdorfer** [comment]
@miltonhultgren thanks for taking care of the changes on the integrations side!

@leehinman The changes are now approved and all PR checks are green but I am not authorized to merge the PR. Could you please merge the PR on my behalf? Thank you!

**Pull request merged**
