### PR TITLE
Fix exit for beats if version flag is provided

### PR DESCRIPTION
**Pull request by ruflin**
See https://github.com/elastic/beats/pull/789 and https://github.com/elastic/beats/pull/755

### CODE REVIEW

**Comment by cyrilleverrier** [comment]
Wouldn't it be a better idea to ensure that libbeats does not call the beater's Stop() function if the beater's Start() has not been called?
If you do so, you don't need to do this check in all the beats.

See my commit: https://github.com/cyrilleverrier/beats/commit/15b2e7c82bc2027de86331c0be0faca31b8c5af3

**Comment by ruflin** [comment]
That was my first approach. I decided then to fix the "beats" because I think there are other options that actually Stop could be called multiple times. I could see that in the future actually every beat has something like a "Status" that could be checked in which stage it is currently (Setup, Running, Stopping, ...).

**Comment by tsg** [comment]
What does this mean for community Beats, will they be broken if they upgrade libbeat and don't add something similar to the Stop functions?

**Comment by ruflin** [comment]
@tsg @cyrilleverrier I redid the implementation by introducing a beat state. This is closer to what @cyrilleverrier initially suggested and does not break existing beats. In addition it will help us in the long run to get the state in which for example a beat crashed.

**Comment by cyrilleverrier** [comment]
@ruflin : looks very promising

**Pull request merged**
