### PR TITLE
Add scripts to import the Kibana dashboards of a single Beat

### PR DESCRIPTION
**Pull request by monicasarbu**
Add a bash script for Unix systems and a powershell script for Windows systems to import all the dashboards (including the dependencies) to Elasticsearch.

I added another parameter to the script to pass the local directory containing the dashboards, visualizations, searches and index pattern.

### CODE REVIEW

**Comment by monicasarbu** [comment]
@andrewkroh Could you please have a look at the PR, especially at the changes done to the powershell script?

**Comment by tsg** [comment]
Merging this one, as it has no actual diff and we'll need to test it anyway.

**Comment by andrewkroh** [comment]
@monica The PowerShell changes LGTM. I'll try it out on Windows this week with the 5.0.0-alpha1 testing.

**Comment by ruflin** [comment]
@elastic/beats My idea about a `beat-helper` binary mentioned a few weeks ago was to prevent these kind of complex shell scripts which we have to maintain for different platforms. Instead it would be just a binary that could be executed written in Golang. I still think it would be a good idea to move this code to a beat-helper binary. Alternatively it could be implemented as flag into libbeat, so if the flag is used, only the helper part is run (not very clean).

**Comment by monicasarbu** [comment]
@ruflin I like the idea of having one binary (written in Golang) to import the dashboards, but I am not sure about the idea of the beat-helper. The way I see this binary is to be included in the Beat package together with the dashboards and the Beat binary.

**Comment by ruflin** [comment]
@monicasarbu I would also see beat-helper packaged with all the other beat related things. As far as I understand the main difference is that you would only do the dashboard stuff, which I think is a reasonable first step.

**Pull request merged**
