### PR TITLE
beat contrib: added apexbeat link

### PR DESCRIPTION
**Pull request by jenssaade**
Added link for community beat contrib. 
Additional docs can be found here: http://toolkits.verticle.io/docs/index.html#elasticsearch-apexbeats

### CODE REVIEW

**Comment by ruflin** [comment]
Thanks for creating apexbeats. One thing I'm curious about: Is the data structure of apex metrics known in advance or different in each case?

**Comment by jenssaade** [comment]
The apex message structure is more or less generic and consisting of key-value pairs. The values types are currently not restricted but in general serializable objects are supported. There is some special handling for Java List and Map types though. The apex collector will transform those to stringified JSON objects so they don't clash with existing ES types.

**Comment by ruflin** [comment]
Thanks for the details. I was thinking if this could make sense as a metricbeat module / metricset: https://www.elastic.co/guide/en/beats/metricbeat/current/creating-metricsets.html

**Comment by jenssaade** [comment]
Depends on the data flow from the collector to the beat. Since metricbeat fetches the data there would be some changes to the current flow. Let's discuss on gitter.

**Comment by ruflin** [comment]
Gitter? We don't have a channel there, but we have IRC: https://kiwiirc.com/client/irc.freenode.net/beats

**Pull request merged**
