### PR TITLE
Cherry-pick #16139 to 7.x: Regenerate expected files after changes in date parsing

### PR DESCRIPTION
**Pull request by jsoriano**
Cherry-pick of PR #16139 to 7.x branch. Original message: 

Elasticsearch has modified the behaviour on date parsing when the date
doesn't include timezone data. Regenerate a couple of golden files that
are affected by this change.

New values are actually correct, so this will fix some issues on logs without
timezone information.

I think the change in Elasticsearch is https://github.com/elastic/elasticsearch/pull/51215

We will need to backport this for 7.7 as this change is going to be included
in Elasticsearch 7.7.

### CODE REVIEW

**Comment by graphaelli** [comment]
Looks like this is needed now, can we get this branch up to date with 7.x please?

**Comment by jsoriano** [comment]
@graphaelli branch updated, but feel free to bring this change to #16699 and merge it all together.

**Comment by kaiyan-sheng** [comment]
ci failure in libbeat is caused by https://github.com/elastic/beats/pull/16764

**Comment by graphaelli** [comment]
merged as part of #16699, thanks

**Pull request closed without merging**
