### PR TITLE
Add rabbitmq module (#3887) #WIP

### PR DESCRIPTION
**Pull request by amandahla**
Metricset node using HTTP API call ["/api/nodes"](https://rawcdn.githack.com/rabbitmq/rabbitmq-management/rabbitmq_v3_6_9/priv/www/doc/stats.html) to collect metrics from RabbitMQ nodes.

To do:
 - [x] Integration test
- [x] Complete fields.yml
- [x] Changelog entry

### CODE REVIEW

**Comment by ruflin** [comment]
@amandahla Thanks a lot for taking this on. I added a few points to the list above. Please ping me when I should have a first look. Had a quick one already and looks really good (as usual) :-)

**Comment by exekias** [comment]
jenkins, test it please

**Comment by exekias** [comment]
Thank you very much for contributing @amandahla, awesome module!

**Comment by monicasarbu** [comment]
Thanks @amandahla for your contribution. Would be nice if you can add a Kibana dashboards for the RabbitMQ module.

**Comment by balamuralinagella** [comment]
Hi @monicasarbu.I am new to ELK.Not sure I can ask  questions here.Can you please describe the use ?Can we see metrics of rabbitmq in Kibana dashboard or not?I am bit confused here.Kibana dashboards and logstash will support rabbitmq?

**Comment by monicasarbu** [comment]
@balamuralinagella Currently, with the rabbitmq module in Metricbeat you can monitor the RabbitMQ nodes, but we are planning to extend it to monitor queues, for example. The current version is not coming with a dedicated Kibana dashboard to visualize the collected metrics from RabbitMQ, but you can easily build your own Kibana dashboard. 
Out of topic: Can you please use our [forum](https://discuss.elastic.co/c/beats) for your next questions? Thanks!

**Comment by balamuralinagella** [comment]
Thanks @monicasarbu for clarifying. I will use forum here after.

**Pull request merged**
