### PR TITLE
Support SHA3 hash algorithm family (#5345)

### LINKED ISSUE #5345: Add SHA-3 algorithm support to file integrity module
The Auditbeat file integrity module currently has support for MD5, SHA-1, and SHA-2 algorithms. It would be simple to add support for the latest member of the Secure Hash Algorithm family - SHA-3. The algorithms are implemented in [golang.org/x/crypto/sha3](https://godoc.org/golang.org/x/crypto/sha3).

### PR DESCRIPTION
**Pull request by liketic**
Closes #5345 

Seems like `make fmt` has a bug, when I run `make fmt` under `auditbeat`,  this line 
https://github.com/elastic/beats/blob/ce9e47b83ab5a7dd09c99832cdcf0ebdbc485cb0/auditbeat/module/audit/file/config.go#L6

will be removed.

### CODE REVIEW

**Comment by andrewkroh** [comment]
@liketic Would it possible to have to take another pass at this one now that #5344 has merged?

**Comment by liketic** [comment]
@andrewkroh I updated the PR. Thanks for reviewing.

**Comment by andrewkroh** [comment]
Looks good. Can you please update this [test case](https://github.com/elastic/beats/blob/bba54234a2f39bff1e5074bb14c22e1d6b6d9323/auditbeat/module/audit/file/event_test.go#L144) that validates the hashes. I would double check the hashes against some outside source (I found this [site](https://convert.tools/cryptography-security/hasher-algorithms/sha3-hash-generator.html) that does sha3).

**Comment by liketic** [comment]
@andrewkroh Thanks a lot! I will add it. However, the following test I cannot get passed on my laptop...

https://github.com/elastic/beats/blob/bba54234a2f39bff1e5074bb14c22e1d6b6d9323/auditbeat/module/audit/file/event_test.go#L132

And I got a error:
`panic: reflect.Value.Slice: slice index out of bounds [recovered]
	panic: reflect.Value.Slice: slice index out of bounds
`
Do you have any thoughts? Thanks.

**Comment by andrewkroh** [comment]
Once you add the new SHA3 keys to the `expectedHashes` map that error will go away. It's caused by the [`assert.Equals`](https://github.com/elastic/beats/blob/bba54234a2f39bff1e5074bb14c22e1d6b6d9323/auditbeat/module/audit/file/event_test.go#L166) check not validating that its `expected` param is non-nil.

**Comment by liketic** [comment]
@andrewkroh Thanks! I made a minor change to avoid raising that error. Please review. 😃

**Comment by andrewkroh** [comment]
jenkins, test it

**Comment by andrewkroh** [comment]
Looks like there are two other switch statements that also need updated.

- https://github.com/elastic/beats/blob/01a9e43b8aecb402624018253b17416b12b492aa/auditbeat/module/audit/file/flatbuffers.go#L57
- https://github.com/elastic/beats/blob/01a9e43b8aecb402624018253b17416b12b492aa/auditbeat/module/audit/file/flatbuffers.go#L241

**Comment by andrewkroh** [comment]
jenkins, test it

**Comment by andrewkroh** [comment]
@liketic Thanks! And BTW this is the fastest response I've seen to an issue I've logged. I created the enhancement issue, went to sleep, and woke up to a PR with the enhancement. 👏

**Pull request merged**
