### PR TITLE
filebeat/module/postgresql: Add authentication messages parsing and source.ip & related.ip

### LINKED ISSUE #32228: Filebeat module Postgresql - add ECS authentication fields for SIEM
**Describe the enhancement:**

Postgresql log has authentication messages for successful and failed attempt. But ECS fields important for SIEM like 
event.category, event.type, event.action, event.outcome are missing.

**Describe a specific use case for the enhancement or feature:**

```
2022-07-06 18:04:42 MSK [3646793-2] user_name@postgres LOG:  connection authorized: user= user_name database=postgres application_name=psql
2022-07-06 18:10:13 MSK [2017465-4] user_name@postgres FATAL:  Peer authentication failed for user "user_name"
```

Successful authentication message should have fields:

-  event.category = "authentication"
-  event.action = "logged-in"
-  event.type = "start"
-  event.outcome = "success"

Failed authentication message should have fields:

- event.category = "authentication"
- event.action = "logon-failed"
- event.type = "start"
- event.outcome = "failure"

**Steps to reproduce**

```
POST /_ingest/pipeline/filebeat-7.17.4-postgresql-log-pipeline/_simulate
{
  "docs": [
    {
      "_source": {
        "message": "2022-07-06 18:04:42 MSK [3646793-2] user_name@postgres LOG:  connection authorized: user=user_name database=postgres application_name=psql"
      }
    }
  ]
}
```

```
POST /_ingest/pipeline/filebeat-7.17.4-postgresql-log-pipeline/_simulate
{
  "docs": [
    {
      "_source": {
        "message": "2022-07-06 18:10:13 MSK [2017465-4] user_name@postgres FATAL:  Peer authentication failed for user \"user_name\""
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by leweafan**
## What does this PR do?

Adds postgresql authentication messsages parsing and source.ip & related.ip fields

## Why is it important?

Authentication messages parsing and source.ip & related.ip important for SIEM

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes #32228

### CODE REVIEW

**Comment by leweafan** [comment]
Can any one help with review?

**Comment by rdner** [comment]
@leweafan it seems like your last force-push broke this PR. If you still think we should review it, please fix it.

**Comment by rdner** [comment]
I'm closing this for now, feel free to re-open once the changes are ready for a review again.

**Pull request closed without merging**
