### PR TITLE
Update gettingstarted.asciidoc

### PR DESCRIPTION
**Pull request by ngbrown**
Clarify that it is the server that Metricbeat is installed on.

### CODE REVIEW

**Comment by exekias** [comment]
sorry, could you open this PR against `master` branch?

**Comment by ngbrown** [comment]
@exekias Cherry-picked change over to `master` and edited this pull request.

**Comment by dedemorton** [comment]
@ngbrown We've tried that before (setting the edit URL to master), but it causes confusion when content gets deleted or moved around between releases. Plus there's some manual coding on our side required to make that happen. We find it's easier to cherry-pick the changes.  Thank you for your contribution!

**Comment by exekias** [comment]
ok to test

**Pull request merged**
