### PR TITLE
Added pgid support to topbeat

### PR DESCRIPTION
**Pull request by nickivanov**
Following my accepted pull request to gosigar to support reporting of the process group ID (pgid), adding appropriate support to topbeat.

### CODE REVIEW

**Comment by karmi** [comment]
Hi @nickivanov, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/beats/pull/1901.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by andrewkroh** [comment]
jenkins, test it

**Comment by ruflin** [comment]
@nickivanov As topbeat was removed in 5.0, these changes should go into the system module of metricbeat: https://github.com/elastic/beats/tree/master/metricbeat/module/system As you still have topbeat it seems like you are having an old version of the master branch.

**Comment by nickivanov** [comment]
@ruflin I forked earlier this week, there are both topbeat and metricbeat in it. metricbeat says it's experimental. I can put pgid stuff in there too.

**Comment by ruflin** [comment]
@nickivanov The pull request to remove Topbeat was merged during (last week). That explains the difference. If you also want to add it to Topbeat, you must open a PR against the 1.3 branch. In 5.0 there will only be Metricbeat.

**Comment by nickivanov** [comment]
OK, I'll go back and stick it into Metricbeat

**Comment by ruflin** [comment]
@nickivanov Thanks a lot.

**Pull request closed without merging**
