### PR TITLE
Fixes to import_dashboards

### PR DESCRIPTION
**Pull request by cwurm**
Fixes issues with `import_dashboards`:

 1. Do not try to re-create the `.kibana` index. First check if it already exists.
 2. Stop and report HTTP error code when dashboards archive cannot be downloaded.

### CODE REVIEW

**Comment by tsg** [comment]
I think `make fmt` should fix the import style error.

**Comment by tsg** [comment]
LGTM on first sight. For my understanding, is this about avoiding an unnecessary error message? Or was it broken in a more serious way?

**Comment by cwurm** [comment]
> For my understanding, is this about avoiding an unnecessary error message? Or was it broken in a more serious way?

@tsg It's mostly about making it stop on errors and providing more details when one happens.

On 6.0.0-alpha2, this is the output I get when running it with a wrong password. Several things happen here that I think shouldn't happen:
 1. It silently ignores not being able to create the Kibana index (return code is not checked).
 2. It logs not being able to set the mapping, but since the method doesn't return the error the script continues.

With this PR, it will stop and report the error when it can't create the index, and it will stop when it can't set the mapping.
```
Failed to set the mapping: 401 Unauthorized
Created temporary directory /tmp/tmp036288845
Downloading https://artifacts.elastic.co/downloads/beats/beats-dashboards/beats-dashboards-6.0.0-alpha2.zip
Unzip archive /tmp/tmp036288845
Importing Kibana from /tmp/tmp036288845/beats-dashboards-6.0.0-alpha2/filebeat
Importing Kibana from /tmp/tmp036288845/beats-dashboards-6.0.0-alpha2/heartbeat
Importing Kibana from /tmp/tmp036288845/beats-dashboards-6.0.0-alpha2/metricbeat
Import directory /tmp/tmp036288845/beats-dashboards-6.0.0-alpha2/metricbeat/index-pattern
Import index to /.kibana/index-pattern/metricbeat-* from /tmp/tmp036288845/beats-dashboards-6.0.0-alpha2/metricbeat/index-pattern/metricbeat.json

Error importing URL/file: Failed to import index-pattern: Failed to load directory /tmp/tmp036288845/beats-dashboards-6.0.0-alpha2/metricbeat/index-pattern:
  error loading /tmp/tmp036288845/beats-dashboards-6.0.0-alpha2/metricbeat/index-pattern/metricbeat.json: couldn't load json. Error: 401 Unauthorized
Exiting
```

It also doesn't stop right away when it can't download the archive. E.g. on master, it doesn't report not being able to download the alpha3.zip. With this PR, it will report the 404 Not Found and stop the script without trying to unzip what is not there. Output on master:
```
Failed to set the mapping: 401 Unauthorized
Created temporary directory /tmp/tmp581683811
Downloading https://artifacts.elastic.co/downloads/beats/beats-dashboards/beats-dashboards-6.0.0-alpha2.zip
Unzip archive /tmp/tmp581683811
Error importing URL/file: Failed to unzip the archive: /tmp/tmp581683811/beats-dashboards-6.0.0-alpha2.zip: zip: not a valid zip file
Exiting
```

**Comment by cwurm** [comment]
jenkins, retest it

**Comment by cwurm** [comment]
@tsg The tests are running locally for me, yet the CI is failing. Any ideas on what I can do?

**Comment by tsg** [comment]
jenkins, retest it

**Comment by andrewkroh** [comment]
jenkins, test it

**Comment by tsg** [comment]
@cwurm I think we're good on this one, tests failure were more likely due to old ES docker images, which should be fixed in #4485. Can you rebase to master just to be sure?

**Comment by cwurm** [comment]
jenkins, test it

**Pull request merged**
