### PR TITLE
Cherry-pick #7997 to 6.x: Add tag "multiline" to "log.flags" if event consists of multiple lines.

### LINKED ISSUE #957: Provide an indication that a line is a multiline.
When a multiline is processed and shipped by Filebeat, add to 'tags' an indicator. This is to mimic the behaviour the logstash multiline filter performs by adding 'multiline' to tags.
Originally [reported](https://discuss.elastic.co/t/add-multiline-to-tags-field/41285) on the discuss forum.

### PR DESCRIPTION
**Pull request by kvch**
Cherry-pick of PR #7997 to 6.x branch. Original message: 

Add "multiline" tag to "log.status" if the event contains multiple lines. This way users can filter for multiline messages using `"multiline" in [log.status]`.

Example event
```json
{
  "@timestamp": "2018-08-17T11:35:21.813Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "doc",
    "version": "7.0.0-alpha1"
  },
  "source": "/home/n/test.log",
  "offset": 0,
  "log": {
    "status": ["multiline"],
  },
  "message": "[test line\ntest line]",
  "prospector": {
    "type": "log"
  },
  "input": {
    "type": "log"
  },
  "beat": {
    "hostname": "sleipnir",
    "version": "7.0.0-alpha1",
    "name": "sleipnir"
  },
  "host": {
    "name": "sleipnir"
  }
}

```

Depends on #7991 
Closes #957

### CODE REVIEW

**Comment by kvch** [comment]
jenkins test this

**Comment by ruflin** [comment]
I assume this will need a rebase as soon as the geoip fix is merged / backported into 6.x 

@jsoriano FYI

**Comment by jsoriano** [comment]
#8204 with the fix for the geoip issue merged

**Comment by kvch** [comment]
jenkins test this

**Comment by kvch** [comment]
Failing test is unrelated.

**Pull request merged**
