### PR TITLE
[Metricbeat] upgrade flatbuffers to 1.12.1

### PR DESCRIPTION
**Pull request by endorama**
## What does this PR do?

Version 1.12.0 seems to have changed, producing a verification error.

``````
verifying github.com/google/flatbuffers@v1.12.0: checksum mismatch
        downloaded: h1:N8EguYFm2wwdpoNcpchQY0tPs85vOJkboFb2dPxmixo=
        go.sum:     h1:/PtAHvnBY4Kqnx/xCQ3OIV9uYcSFGScBsWI3Oogeh6w=

SECURITY ERROR
This download does NOT match an earlier download recorded in go.sum.
The bits may have been replaced on the origin server, or an attacker may
have intercepted the download attempt.
``````

As 1.12.1 is available, upgrading the module.

## Why is it important?

Prevent an error when building `x-pack/metricbeat`

## Checklist

- [ ] ~~My code follows the style guidelines of this project~~
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [ ] ~~I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Author's Checklist

- [ ]

## How to test this PR locally

Run `mage build` in `x-pack/metricbeat`

## Related issues

-

### CODE REVIEW

**Review by sayden — APPROVED** [review]
LGTM

**Comment by andrewkroh** [comment]
Please run `make notice` from the root of the repo.

**Comment by endorama** [comment]
Finally all green! Merging.

**Comment by endorama** [comment]
@Mergifyio refresh

**Pull request merged**
