### PR TITLE
Update shared-docker.asciidoc

### PR DESCRIPTION
**Pull request by ggnanasekaran77**
Inside filebeat Image all files are owned by root:filebeat

### CODE REVIEW

**Comment by andrewkroh** [comment]
It does look like they are root owned. 👍 

```
$ docker run -it --rm docker.elastic.co/beats/filebeat:6.3.1 ls -la /usr/share/filebeat
total 46784
drwxr-x--- 1 root filebeat     4096 Jun 29 21:24 .
drwxr-xr-x 1 root root         4096 Jun 29 21:24 ..
-rw-r----- 1 root filebeat       41 Jun 29 21:09 .build_hash.txt
-rw-r----- 1 root filebeat    13675 Jun 29 21:09 LICENSE.txt
-rw-r----- 1 root filebeat   143351 Jun 29 21:09 NOTICE.txt
-rw-r----- 1 root filebeat      802 Jun 29 21:09 README.md
drwxrwx--- 2 root filebeat     4096 Jun 29 21:24 data
-rw-r----- 1 root filebeat    55717 Jun 29 21:10 fields.yml
-rwxr-x--- 1 root filebeat 47580429 Jun 29 21:10 filebeat
-rw-r----- 1 root filebeat    58886 Jun 29 21:10 filebeat.reference.yml
-rw-r----- 1 root filebeat      312 Jun 29 21:24 filebeat.yml
drwxr-x--- 1 root filebeat     4096 Jun 29 21:08 kibana
drwxrwx--- 2 root filebeat     4096 Jun 29 21:24 logs
drwxr-x--- 1 root filebeat     4096 Jun 29 21:05 module
drwxrwx--- 1 root filebeat     4096 Jun 29 21:09 modules.d
drwxr-x--- 1 root filebeat     4096 Jun 29 21:24 prospectors.d
```

**Comment by jordansissel** [comment]
Indeed! Here's where the Dockerfile does it: https://github.com/elastic/beats-docker/blob/master/templates/Dockerfile.j2#L28

**Comment by andrewkroh** [comment]
@ggnanasekaran77 Could you please sign the CLA? http://www.elasticsearch.org/contributor-agreement/

**Comment by ggnanasekaran77** [comment]
@andrewkroh .. Thanks. Done.

**Comment by dedemorton** [comment]
@andrewkroh Yup! will do. I'll also backport it to 6.4.

**Pull request merged**
