### PR TITLE
Changing field type to keyword

### LINKED ISSUE #17834: Change ingress_controller fields mapping from text to keyword
**Describe the enhancement:**

With PR https://github.com/elastic/beats/pull/16197 filebeat now supports ingress controller logs which is great.

I would like to change the mapping of the text fields to keyword instead. These three fields would be affected:
- nginx.ingress_controller.http.request.id
- nginx.ingress_controller.upstream.alternative_name
- nginx.ingress_controller.upstream.name

**Describe a specific use case for the enhancement or feature:**
We have started to use the pipeline and mapping in our elasticsearch environment and would like to visualize metrics split by nginx.ingress_controller.upstream.name, which is not possible when it is a text field.

Changing mapping to keyword would solve this. And I think that the use case of visualizing the nginx.ingress_controller.upstream.name would be more common than free-text searching on the field.

### PR DESCRIPTION
**Pull request by SHolzhauer**
- Enhancement

## What does this PR do?
Modify the field type from filebeat/nginx module fields from text to keyword as requested in #17834  

## Why is it important?
See Issue #17834

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [x] I have made corresponding changes to the documentation
- [ ] ~~I have made corresponding change to the default configuration files~~
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues
- Closes elastic/beats#17834

## Note
First PR ever, go easy on me ;)

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
Thanks for contributing! Change looks good to me. Could you add a [changelog](https://raw.githubusercontent.com/elastic/beats/master/CHANGELOG.next.asciidoc) entry under Filebeat bug fixes please? Thanks!!

**Comment by SHolzhauer** [comment]
@kaiyan-sheng Sure, but is this really a bugfix? As it "improves" but doesn't actually fix an issue right?

**Comment by kaiyan-sheng** [comment]
Good point! @exekias WDYT about the changelog?

**Comment by kaiyan-sheng** [comment]
jenkins, test this please

**Comment by SHolzhauer** [comment]
> Good point! @exekias WDYT about the changelog?

For now I added it under bug-fixes, let me know if it requires changing.

**Comment by exekias** [comment]
Having it under bugfix sounds good to me! Thank you for contributing!

**Comment by kaiyan-sheng** [comment]
jenkins, test this please

**Pull request merged**
