### PR TITLE
Update breaking changes docs for 8.0.0-rc2

### PR DESCRIPTION
**Pull request by dedemorton**
Summary of changes:

* Deletes old 7.x breaking changes doc files.
* Fixes links to old 7.x breaking changes.
* Updates Breaking Changes doc to only include 8.0.
* Adds "coming" tag to upgrade instructions.

@kvch  We need to decide how to proceed with the Beats upgrade instructions. Are we going to recommend that users upgrade Beats to 8.x? If so, we need to update the upgrade instructions. I've commented them out in this PR to prepare for 8.0.0-rc2 and added a "coming" tag instead.

We should also decide if we want to continue providing BCs in a separate file. This does incur some overhead, but makes it easier for the upgrade guide to pull in a consolidated view of important BCs that users need to take action on.

Closes https://github.com/elastic/beats/issues/30115

### CODE REVIEW

**Comment by kvch** [comment]
> @kvch We need to decide how to proceed with the Beats upgrade instructions. Are we going to recommend that users upgrade Beats to 8.x? If so, we need to update the upgrade instructions. I've commented them out in this PR to prepare for 8.0.0-rc2 and added a "coming" tag instead.

Yes, we recommend that. They should first upgrade to 7.17.x and then upgrade to 8.x. One thing that worth mentioning is that from 8.1 we no longer allow connecting to older versions of Elasticsearch instances. But if someone is first upgrading their Beats instances, they can enabled `output.elasticsearch.allow_older_versions` temporarily.

**Review by kvch — APPROVED** [review]

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by dedemorton** [comment]
I've created https://github.com/elastic/beats/issues/30291 to track changes required to the upgrade docs for 8.0.

Sorry I haven't gotten this merged yet, but I need to clean up some links that point to the old 7.x docs...kinda hoping they have been fixed by now, but if not, I will fix them if/when the build breaks.

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
