### PR TITLE
Fail travis if "go fmt" make diff

### PR DESCRIPTION
**Pull request by ewgRa**

### CODE REVIEW

**Comment by ewgRa** [comment]
Seems already implemented.

**Comment by andrewkroh** [comment]
Yeah, travis runs `make check` which does this.

**Comment by ewgRa** [comment]
@andrewkroh just found several files in vendor folder that unformatted and think that it is not under travis, but for now find this code

I think it can be improved bychecking only files that changes in PR, like this:

"git diff HEAD^ --name-status | grep "^D" -v | sed 's/^.\t//g' | grep "\.go$" | while read FILE; do go fmt $FILE; done"

**Comment by andrewkroh** [comment]
`vendor` contains the project's dependencies and we have no control over how those files are formatted so we don't do any enforcement of `gofmt` styling there. Those files are simply copies from their source repos.

I think it's simpler to just check all go files not in the vendor directory. But that is some nice command line fu.

**Comment by ewgRa** [comment]
@andrewkroh sorry, I just kind of newbie in Go world. Look to Beats repository for some answers for my lib :)

Can you explain why there is no golint checks in travis?

I face in my lib that I name function like "Id" and it is not golint compatible. So for now I need to rename it and it is broke backward compatibility. I want add golint to travis, but maybe you explain why this is not so good idea?

**Comment by ewgRa** [comment]
Also "| read && echo "Code differs from gofmt's style" 1>&2 && exit 1 || true" 

can be changed to more understandable "| grep -q . && echo "Code differs from gofmt's style" && false"

grep return exit code 1 if nothing found, it is easy to use

**Comment by ewgRa** [comment]
Nope, seems changes needed, as is not working

**Comment by ewgRa** [comment]
@andrewkroh 

This one works very well "gofmt -l . | (! grep . -q) || (echo "Code differs from gofmt's style" && false)" and more understandable and more powerfull since there is a "grep", that can easily filter vendor folder and so on.


Can you explain why no golint in travis?

**Comment by ewgRa** [comment]
PR for more simple gofmt code check - #938

**Comment by andrewkroh** [comment]
By the time our team considered using golint we had already accumulated enough golint debt that it would be a lot of work to enable it. I encourage you to run golint checks in your project's CI from the start. Have a look at the gometalinter project too. Additionally see https://github.com/elastic/libbeat/issues/287

**Comment by ewgRa** [comment]
@andrewkroh thanks!

**Pull request closed without merging**
