### PR TITLE
`aws-s3` input: Split S3 poller and SQS reader into explicit input objects

### PR DESCRIPTION
**Pull request by faec**
A large cleanup in the `aws-s3` input, reorganizing the file structure and splitting internal APIs into additional helpers.

This change is meant to have no functional effect, it is strictly a cleanup and reorganization in preparation for future changes. The hope is that the new layout makes initialization steps and logical dependencies clearer. The main changes are:

- Make `s3Poller` and `sqsReader` into standalone input objects, `s3PollerInput` and `sqsReaderInput`, that implement the `v2.Input` interface, instead of interleaving the two implementations within the same object.
  * Choose the appropriate input in `(*s3InputManager).Create` based on configuration
  * Move associated internal API out of the shared `input.go` into the new `s3_input.go` and `sqs_input.go`, while leaving `s3.go` and `sqs.go` for auxiliary helpers.
  * Give each input a copy of `config` and `awsConfig`, and remove redundant struct fields that simply shadowed fields already in those configs.
- In `sqsReaderInput`, use a fixed set of worker goroutines and track task allocation via channel-based work requests instead of creating ephemeral workers via the previous custom semaphore implementation (similar to the [recent cloudwatch cleanup](https://github.com/elastic/beats/pull/38953)).
  * Delete `aws.Sem`, since this was its last remaining caller
- Collect the helpers related to approximate message count polling into a helper object, `messageCountMonitor`, so their role in the input is clearer.
- Generally, break larger steps up into smaller helper functions
- Generally, collect initialization dependencies in the same place so the sequencing is clearer.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] ~~I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

### CODE REVIEW

**Review by leehinman — CHANGES_REQUESTED** [review]
Code changes look fine to me.

Can you add to the description what tests were done to verify that changes keep the same behavior?

I know there are multiple rounds of changes anticipated, so this might be too early for this.  But at the end I'd like to see us test a few scenarios:

1. SQS message every 5 sec that results in 250 events per SQS message
2. SQS message as quickly as possible that results in 1 event per SQS message
3. SQS message every 5 minutes that results in 64k events per SQS message
4. S3 bucket with object added every 5 sec that results in 250 events per object added
5. S3 bucket where we add objects as quickly as possible that result in one event per object
6. S3 bucket were we add object every 5 minutes that results in 64k events per object
7. S3 bucket with 64k objects and append data that results in one event to a randomly selected object every second

**Comment by faec** [comment]
@leehinman I was expecting to write more tests ("all existing tests pass" isn't as reassuring as I want it to be). Some scenarios you mentioned might be out of scope for this pass -- one thing I didn't change at all is the S3/SQS API proxies, so things like "number of events per S3 object" or "appending an event to an object" are opaque to this change, it's all handled internally in sqsProcessor and s3ObjectHandler. So for confirming behavior is unchanged, we can restrict scope to three interface points:
- Calls to S3/SQS API proxies
- Calls to create a Beats pipeline client, or publish an event through one
- Calls to `awss3.inputMetrics`, the helper object used to update the input's monitoring variables.

There are existing tests for at least the first two using auto-generated mocks, and I've updated them for the new code. I'm not satisfied with them, though -- they're the sort of mocks where you list the exact order and inputs of each mocked call even if it isn't part of the spec, so this PR broke them just by removing redundant calls to deterministic functions and changing who's is responsible for starting a helper goroutine.

One thing I was considering was rewriting / expanding those tests with more granular boundaries -- e.g. instead of checking that the full input calls NextPage the right number of times, then calls GetObject the right number of times, then calls Publish the right number of times, just confirm that objects given to the reader loop are sent to the work channel, and separately, that objects sent to the work channel are published by the work loop.

Having said all that: does that plan sound good? Are there any areas of this PR where you'd especially like to see expanded test coverage?

**Comment by leehinman** [comment]
> @leehinman I was expecting to write more tests ("all existing tests pass" isn't as reassuring as I want it to be).

:-) yeah.

>Some scenarios you mentioned might be out of scope for this pass

Absolutely out of scope.  I wrote them down to start thinking/talking about them.  Probably should have done 2 separate comments.

>-- one thing I didn't change at all is the S3/SQS API proxies, so things like "number of events per S3 object" or "appending an event to an object" are opaque to this change, it's all handled internally in sqsProcessor and s3ObjectHandler. So for confirming behavior is unchanged, we can restrict scope to three interface points:
> 
>     * Calls to S3/SQS API proxies
> 
>     * Calls to create a Beats pipeline client, or publish an event through one
> 
>     * Calls to `awss3.inputMetrics`, the helper object used to update the input's monitoring variables.
> 
> 
> There are existing tests for at least the first two using auto-generated mocks, and I've updated them for the new code. I'm not satisfied with them, though -- they're the sort of mocks where you list the exact order and inputs of each mocked call even if it isn't part of the spec, so this PR broke them just by removing redundant calls to deterministic functions and changing who's responsible for starting a helper goroutine.
> 
> One thing I was considering was rewriting / expanding those tests with more granular boundaries -- e.g. instead of checking that the full input calls NextPage the right number of times, then calls GetObject the right number of times, then calls Publish the right number of times, just confirm that objects given to the reader loop are sent to the work channel, and separately, that objects sent to the work channel are published by the work loop.
> 
> Having said all that: does that plan sound good? Are there any areas of this PR where you'd especially like to see expanded test coverage?

Any additional automated tests would be great.

For this PR a manual test that either mode still works as expected would be fine.

**Comment by zmoog** [comment]
I am running some manual tests ingesting CloudTrail logs using the SQS mode. 

I'm using a very simple setup, here are the differences with the default `modules.d/aws.yml` file:

```yaml

  - module: aws
    cloudtrail:
      #    enabled: false
      enabled: true

      # AWS SQS queue url
      var.queue_url: https://sqs.eu-north-1.amazonaws.com/<redacted>/mbranca-cloudtrail-logs

      var.access_key_id: <redacted>
      var.secret_access_key: <redacted>
```

Filebeat is running and ingesting CloudTrail logs. Here are a couple of screenshot of the SQS queue and the logs on Discover:

CleanShot 2024-05-08 at 22 43 02

CleanShot 2024-05-08 at 22 51 52

**Comment by zmoog** [comment]
I am also running manual tests ingesting CloudTrail logs from the same S3 bucket using the S3 polling.

Here's the config:

```yaml
  - module: aws
    cloudtrail:
      enabled: true

      # AWS S3 bucket arn
      var.bucket_arn: 'arn:aws:s3:::<redacted>'

      # Number of workers on S3 bucket
      var.number_of_workers: 5
```


The S3 polling mode panics because the input log is `nil`; however, I was able to successfully run the input with this small change:

```diff
diff --git a/x-pack/filebeat/input/awss3/s3_input.go b/x-pack/filebeat/input/awss3/s3_input.go
index 50786626d2..999b27da53 100644
--- a/x-pack/filebeat/input/awss3/s3_input.go
+++ b/x-pack/filebeat/input/awss3/s3_input.go
@@ -68,11 +68,11 @@ func (in *s3PollerInput) Run(
        inputContext v2.Context,
        pipeline beat.Pipeline,
 ) error {
-       log := inputContext.Logger.Named("s3")
+       in.log = inputContext.Logger.Named("s3")
        var err error
 
        // Load the persistent S3 polling state.
-       in.states, err = newStates(log, in.store)
+       in.states, err = newStates(in.log, in.store)
        if err != nil {
                return fmt.Errorf("can not start persistent store: %w", err)
        }
@@ -95,7 +95,7 @@ func (in *s3PollerInput) Run(
        defer in.metrics.Close()
 
        in.s3ObjectHandler = newS3ObjectProcessorFactory(
-               log,
+               in.log,
                in.metrics,
                in.s3,
                in.config.getFileSelectors(),

```

The log ingestion is making progress:

CleanShot 2024-05-08 at 23 19 16

**Comment by zmoog** [comment]
A recent change in the main branch created an inconsistency in the versions of the AWS SDK core and services modules. In practice, all the AWS inputs I tested failed with a "not found, ResolveEndpointV2" error.

A [PR](https://github.com/elastic/beats/pull/39454) is being reviewed to address this problem.

**Review by zmoog — COMMENTED** [review]
I like the new design. It breaks down the current complexity into smaller chunks that are easier to understand and follow how they fit together. 

We should address the `nil` log in the S3 polling mode.

**Review by leehinman — APPROVED** [review]
Assuming manual testing passes.  LGTM.

**Review by zmoog — APPROVED** [review]
LGTM

**Pull request merged**
