### PR TITLE
Starting to replace gotestcover

### PR DESCRIPTION
**Pull request by ruflin**
See https://github.com/elastic/beats/issues/1685

Problem will be Windows compatibilty.

### CODE REVIEW

**Comment by ruflin** [comment]
@pierrre One thing that was nice about gotestcover is that the same command worked on all OS, including Windows :-)

**Comment by pierrre** [comment]
Yes I understand.
But it was by accident and was not supported :P
Actually, I used it only on Travis, so I didn't care about compatibility...

Feel free to fork and maintain your own version.
But for me, my personal and professional projects, I will use the bash script :)

By the way, I just found this:
https://github.com/pkg/errors/blob/master/.travis.yml#L2
https://docs.travis-ci.com/user/languages/go#Go-Import-Path
Could it replace "rsync" in your travis config file? (for forks)

**Comment by ruflin** [comment]
I try to maintain as few projects as possible ;-) TBH a great accident with Windows. 

That is great news about the `go_import_path`. I wasn't aware of this and it should solve our rsync hack. Makes my blog post obsolete :-) https://www.ruflin.com/2015/08/13/fix-for-travis-ci-failure-in-forked-golang-repositories/

**Comment by ruflin** [comment]
Closing in favor of https://github.com/elastic/beats/pull/2154 We decided to add gotestcover as it is to our dependencies as currently gotestcover does everything we need and is cross platform compatible.

go_import_path was implemented and works like a charm.

**Pull request closed without merging**
