### PR TITLE
fix some typos

### PR DESCRIPTION
**Pull request by cuishuang**

### CODE REVIEW

**Comment by rdner** [comment]
@cuishuang could you please sign the [contributor agreement](https://www.elastic.co/contributor-agreement)?

**Review by rdner — COMMENTED** [review]
@cuishuang could you please sign the [contributor agreement](https://www.elastic.co/contributor-agreement)?

**Review by rdner — APPROVED** [review]

**Comment by cuishuang** [comment]
> @cuishuang could you please sign the [contributor agreement](https://www.elastic.co/contributor-agreement)?

of course

**Pull request merged**
