### PR TITLE
Add instance_name in GCE add_cloud_metadata processor

### PR DESCRIPTION
**Pull request by BeLi4L**

### CODE REVIEW

**Comment by tsg** [comment]
Thanks, can you sign the CLA, please? Should only take 5 mins.

One question on the "name" key. Is it guaranteed to always be there? Or should we mark it as optional?

**Comment by BeLi4L** [comment]
Yes, the "name" field is always there. 

See https://cloud.google.com/compute/docs/reference/latest/instances#name

**Comment by tsg** [comment]
jenkins, test it

**Comment by ruflin** [comment]
I think this also needs to be added to the `fields.yml` as it is not there yet.

**Comment by BeLi4L** [comment]
Done ;)

**Comment by exekias** [comment]
@BeLi4L you will need to run `make update` in the root folder of the project, it will update docs with your new field.

Also please add a line to `CHANGELOG.asciidoc` file

Apart from that, LGTM :) thanks for contributing!

**Comment by BeLi4L** [comment]
Alright, fixed :)

**Comment by exekias** [comment]
jenkins test this please

**Pull request merged**
