### PR TITLE
Remove count field from filebeat event

### PR DESCRIPTION
**Pull request by ruflin**
This closes https://github.com/elastic/beats/issues/778

Remove count as required field from system tests checks

### CODE REVIEW

**Comment by tsg** [comment]
LGTM.

**Comment by ruflin** [comment]
@andrewkroh I didn't check in detail why, but it seems like the EnsureField functions don't work as expected as I didn't change it: https://github.com/elastic/beats/blob/master/libbeat/common/mapstr.go#L91-L91 I assume the reason is that a copy and not a reference is passed, so the copy is modified. Perhaps we should have a closer look at this in an other PR?

**Comment by andrewkroh** [comment]
The method is written correctly (maps are passed by reference). It just isn's called in libbeat (anymore?). It's only invoked by Packetbeat.

**Comment by ruflin** [comment]
@andrewkroh Will you have a look at that?

**Comment by andrewkroh** [comment]
I don't think there is anything to look into. I think that is the behavior we want because this means `count` is not required to be included in the data produced by all Beats.

**Comment by tsg** [comment]
Yes, I think @urso moved the check for it to Packetbeat.

**Pull request merged**
