### PR TITLE
Bundle apm-server by default with Elastic Agent

### PR DESCRIPTION
**Pull request by jalvz**
## What does this PR do?

As title.

## Why is it important?

1. Optimization
2. If we use APM to instrument Elastic Agent, to guarantee that apm-server is always available.

## Checklist

- [X] My code follows the style guidelines of this project

## Related issues

Closes https://github.com/elastic/beats/issues/23545

### CODE REVIEW

**Comment by michalpristas** [comment]
@ruflin @mostlyjason are we ok with increased size of agent binary, we recently removed Heartbeat for that reason. 
@jalvz can you mention how much binary size increases ?

**Comment by michalpristas** [comment]
bundle size disussed offline.
i suggest looking also into `x-pack/elastic-agent/magefile.go` and check line 580, there's a list of beats which get prebuild and packed in so with apm there you should be able to test this locally and when you run `mage package` resulting packages should contain them.

**Comment by jalvz** [comment]
> i suggest looking also into x-pack/elastic-agent/magefile.go and check line 580

Actually I had look at it and dismissed because apm-server is not in `beats/x-pack` and would fail; but now that you mentioned it occurred to me to change the path for apm-server, and doing that I could test that it actually works.

But I wont commit the change because it is going to fail for everyone else, including CI

**Comment by ruflin** [comment]
Agree, we should know the increase on the binary size but I don't expect it to change the opinion that it should be bundled by default.

**Review by michalpristas — APPROVED** [review]
i think is' fine  then, please check snapshot to see if apm is packed in after this gets in

**Pull request merged**
