### PR TITLE
Add warning about autodiscover and template scoping

### LINKED ISSUE #7312: Clarify free use of wildcards in Filebeat autodiscover docs
When using autodiscover with Filebeat, you  are allowed to use wildcards (`*`) in input configurations, we should clarify docs to explain the risk of doing so, if paths are not scoped to the container.

### PR DESCRIPTION
**Pull request by exekias**
When using autodiscover, you have to be careful when defining config templates, especially if they are
reading from places holding information for several containers. For instance, under this file structure:

```
/mnt/logs/<container_id>/*.log
```

You can define a config template like this:

:warning: Wrong settings:
```
autodiscover.providers:
  - type: docker
    templates:
      - condition.contains:
          docker.container.image: nginx
        config:
          - type: log
            paths:
              - "/mnt/logs/*/*.log"
```

That would read all the files under the given path several times (one per nginx container). What you really want is to scope your template to the container that matched the autodiscover condition:

:green_heart: Good settings:
```
autodiscover.providers:
  - type: docker
    templates:
      - condition.contains:
          docker.container.image: nginx
        config:
          - type: log
            paths:
              - "/mnt/logs/${data.docker.container.id}/*.log"
```

I'm not sure if I explained this well in the text, so any input is welcomed :)

Closes #7312

### CODE REVIEW

**Comment by ruflin** [comment]
@exekias I like a lot what you put in the PR message. I wonder if we should put this into the docs?

**Comment by exekias** [comment]
updated to include the PR message

**Comment by ruflin** [comment]
Worth backporting?

**Comment by exekias** [comment]
I opened it, just in case ^

**Pull request merged**
