### PR TITLE
Add traefik module

### PR DESCRIPTION
**Pull request by mmatur**
This commit introduces the [Træfik](https://traefik.io) module for Filebeat. It is capable
of processing access logs of Træfik

### CODE REVIEW

**Comment by exekias** [comment]
Awesome contribution @mmatur! I'll give this a try. Could you please add a `CHANGELOG.asciidoc` entry?

**Comment by ruflin** [comment]
jenkins, test it

**Comment by mmatur** [comment]
@ruflin I am not sure to understand why tests failed
Console seems to indicate that failure come from metricbeat.

> 18:03:04 elastic / beats # pull-request - linux tests » winlogbeat,ubuntu completed with result SUCCESS
18:09:08 elastic / beats # pull-request - linux tests » filebeat,ubuntu completed with result SUCCESS
18:09:08 elastic / beats # pull-request - linux tests » heartbeat,ubuntu completed with result SUCCESS
18:31:05 elastic / beats # pull-request - linux tests » metricbeat,ubuntu completed with result FAILURE
18:31:05 elastic / beats # pull-request - linux tests » libbeat,ubuntu completed with result SUCCESS
18:31:05 elastic / beats # pull-request - linux tests » auditbeat,ubuntu completed with result SUCCESS
18:31:05 elastic / beats # pull-request - linux tests » packetbeat,ubuntu completed with result SUCCESS

Could you give me more informations please ?

**Comment by exekias** [comment]
You can ignore that error, it's probably a flaky test or temporal issue, nothing to do with this PR

**Pull request merged**
