### PR TITLE
Add enable-setting to all output plugins

### PR DESCRIPTION
**Pull request by urso**

### CODE REVIEW

**Comment by monicasarbu** [comment]
Shall we also update the`full` configuration files of the Beats to contain `enable` even if it's not needed?

**Comment by urso** [comment]
Not sure. For me the enable-config mostly makes sense in conjunction with #1985 and #1986, as this will allow to disable modules e.g. from command line.

But having it named `full`-config, maybe it makes sense to add enable.

**Comment by tsg** [comment]
I think it should be in the full configs, as we said the full configs contain all the non-deprecated options and they can be used as a reference.

**Comment by monicasarbu** [comment]
As you already added the `enable` option, I would say to use it in the `full` -config as it's easier to just change the value of `enable` instead of commenting in/out an output.

**Comment by monicasarbu** [comment]
+1 enable/disable one output in the command line.

**Comment by urso** [comment]
makes sense. will add `enable` to `full` config.

**Comment by andrewkroh** [comment]
LGTM

**Comment by ruflin** [comment]
@urso there is one issue with this PR. Metricbeat uses `enabled`, you used `enable`. We should be consistent here.

**Pull request merged**
