### PR TITLE
[Agent] Include agentID in event payload

### PR DESCRIPTION
**Pull request by michalpristas**
Including agent ID in event payload so it is searchable 

ref: #15268

### CODE REVIEW

**Comment by michalpristas** [comment]
I'm not sure if this should be part of payload or data field of event. 
@nchaulet could you clarify the difference between these two fields?

**Comment by nchaulet** [comment]
We could probably keep only one field, On the fleet side we currently add the `agent_id` to every event so this is not needed in the agent.

https://github.com/nchaulet/kibana/blob/feature-ingest-fleet-admin-user/x-pack/legacy/plugins/fleet/server/mappings.ts/#L109-L122

**Comment by michalpristas** [comment]
with the scenario in mind that events will go to ES directly i think it is good to have it in agent as well, 

@nchaulet do you internally use some of these two fields? so i can eventually scratch (the correct) one, otherwise i would get rid of `data` field and leave `payload` untouched ( i would address this in a separate PR anyway)

**Comment by nchaulet** [comment]
No internally we do not use it.

If we have it in the agent maybe we can make it a top level field as it is currently?

**Comment by michalpristas** [comment]
works with me, i will add it to both regular event and ACK as well

**Comment by ph** [comment]
I am OK to include that changes but I've changed the description to remove fix of the issue, because it doesn't address the problem of adding the Agend uuid in the data send from Filebeat to Elasticsearch.

**Comment by paul-tavares** [comment]
@ph Endpoint would have the same issue, since it intends to send date directly to Elasticsearch as well.
Side question: Will Endpoint (or any beat, I guess) have access to or know the ID of the Agent?
_(It was a question I had on an ongoing discussion around another Endpoint discussion)_

**Comment by michalpristas** [comment]
I guess we can provide UUID as either
- env variable
- argument to binary
- part of config

i think we can start with first 2 options and pack in third one if it will be necessary

**Comment by ph** [comment]
> part of config 

@michalpristas I think it should be part of a grpc call from agent to the process more like a "ehlo: " process?

**Comment by ph** [comment]
There is an open PR on top of kibana do we need to synchronize the merge?

**Comment by michalpristas** [comment]
i will merge after kibana changes are in

**Pull request closed without merging**
