### PR TITLE
Kubernetes events are collected from the api server

### PR DESCRIPTION
**Pull request by jsoriano**
In the reference configuration the event metricset was in the block of
configurations for kube-state-metrics.

From discuss: https://discuss.elastic.co/t/why-cant-i-get-k8s-event/250320

### CODE REVIEW

**Comment by ChrsMark** [comment]
Hmm, wondering if that's the case actually 🤔 . I see that we use `kube_config` to create a watcher and watch for events: https://github.com/elastic/beats/blob/ef6274d0d1e36308a333cbed69846a1bd63528ae/metricbeat/module/kubernetes/event/event.go#L67, no?

**Comment by jsoriano** [comment]
@ChrsMark kube config is used to connect to the API server, not to kube state metrics, right?

**Comment by jsoriano** [comment]
Oh, or you mean that actually the `event` metricset uses the kube config and ignores the rest of config values?

**Comment by ChrsMark** [comment]
> Oh, or you mean that actually the `event` metricset uses the kube config and ignores the rest of config values?

Exactly! Initilly I thought that his PR aims to make use of `hosts` for `event` metricset. Maybe having it standalone would make things more clear?

**Comment by jsoriano** [comment]
> > Oh, or you mean that actually the `event` metricset uses the kube config and ignores the rest of config values?
> 
> Exactly! Initially I thought that his PR aims to make use of `hosts` for `event` metricset. Maybe having it standalone would make things more clear?

Yep, I am going to do that, this is also how we have it in the reference configuration.

**Review by ChrsMark — APPROVED** [review]

**Pull request merged**
