### PR TITLE
[DOCS] Fix hard-coded mapping type doc link

### PR DESCRIPTION
**Pull request by lcawl**
Relates to https://github.com/elastic/docs/pull/2521

This PR fixes a hard-coded docmentation link that will cease to work when we move away from "master" URLS:

> 17:07:03 INFO:build_docs:  /tmp/docsbuild/target_repo/html/en/beats/devguide/6.0/metricset-details.html contains broken links to:
17:07:03 INFO:build_docs:   - en/elasticsearch/reference/master/mapping-types.html

NOTE: This fix needs to be backported all the way to 6.0

### CODE REVIEW

**Review by bmorelli25 — APPROVED** [review]
Thanks!

**Comment by bmorelli25** [comment]
> NOTE: This fix needs to be backported all the way to 6.0

Oh my.

**Comment by bmorelli25** [comment]
@dedemorton let me know if you want help backporting this. I could be down to go back in time.

**Comment by dedemorton** [comment]
@bmorelli25 Oh my, indeed! If only I'd caught that problem when I edited the file 6 years ago. :-P

I'll take care of the backports. There's no way we'll get the CI to pass for those old branches, though, so I'll need to get the dev team's OK to merge with broken CI.

**Comment by dedemorton** [comment]
@lcawl What is the deadline for getting this backported (just so I add it to my schedule)?

**Comment by lcawl** [comment]
> @lcawl What is the deadline for getting this backported (just so I add it to my schedule)?

It's part of the broader dev issue re moving away from "master", but AFAIK there's no official deadline

**Comment by dedemorton** [comment]
Went ahead and merged this. I will chase down the backports. I suspect the old ones will not pass CI at all, but that's OK.

**Pull request merged**
