### PR TITLE
Backport to 6.0: Fix getting started (#5326)

### LINKED ISSUE #4391: Docs clarity on enabling JSON parsing
Currently it's not clear in [the docs](https://www.elastic.co/guide/en/beats/filebeat/5.4/configuration-filebeat-options.html#config-json) that in order to enable JSON parsing mode, at least one `prospectors.-.json.*` config key must be set.

cc @andrewkroh

### LINKED ISSUE #5083: Warning on docs regarding deleting data
[The docs here](https://www.elastic.co/guide/en/beats/winlogbeat/current/winlogbeat-template.html) make a reference to deleting data in order to re-apply templates, but should offer a warning.

### PR DESCRIPTION
**Pull request by dedemorton**
Cherry-picks #5326 into 6.0 branch.

* Move sentence to correct location

* Adds warning about deleting the index (fixes #5083)

* Clarify settings for JSON parsing (fixes #4391)

* Fix misc issues

### CODE REVIEW

**Comment by ruflin** [comment]
@dedemorton Could you rebase this commit on top of the most recent 6.0 branch. CI seems to complain because of some version problems but I can't see how this is caused by this PR.

**Comment by dedemorton** [comment]
@ruflin OK, I also ran `make update` in case a previous PR got merged with problems. It did pick up a change in winlogbeat, so could be related?

**Comment by ruflin** [comment]
@dedemorton The build still complains. I wonder what is going on here. Did you fetch the most recent version of the 6.0 branch before rebasing?

**Comment by dedemorton** [comment]
@ruflin I've created a new PR with the cherry-pick to see if that resolves the problem here. See https://github.com/elastic/beats/pull/5573. I'm closing this PR.

**Pull request closed without merging**
