### PR TITLE
fix citadel service name

### PR DESCRIPTION
**Pull request by OneideLuizSchneider**
## What does this PR do?

This PR just fix citadel service name.

## Why is it important?

Because in this way it was sending the pilot metrics to citadel.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Review by ChrsMark — APPROVED** [review]
Thanks for fixing this!

**Comment by ChrsMark** [comment]
@OneideLuizSchneider you will need to run `mage fmt update` under `/beats/x-pack/metricbeat` and `/beats/metricbeat` so as to update the required files properly. Also you will need to sign the CLA. Thanks!

**Comment by OneideLuizSchneider** [comment]
@ChrsMark It's done. Thanks.

**Comment by OneideLuizSchneider** [comment]
It's there a problem, or why this still is open?

**Comment by ChrsMark** [comment]
Apologies for missing your first ping @OneideLuizSchneider  :(, thank you for bringing this up again.
For some reason I cannot see any diff in this PR, it show 0 lines +/- 🤔 . Could you please rebase against the latest master please?

**Pull request closed without merging**
