### PR TITLE
[Ingest Manager] Fix refresh of monitoring configuration

### PR DESCRIPTION
**Pull request by michalpristas**
## What does this PR do?

This PR fixes few things
1. tests for decorator were out of date

2. More sensitive monitoring change detection.
We were only regenerating on program list change now we regenerate even on internal config change

3. Generate monitoring steps for operator not only when switch is changed but also when config is changed for agent and monitoring is running. New config will be generated and picked up by monitoring beats.

## Why is it important?

Fixes: #23599

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Review by blakerouse — APPROVED** [review]
Looks good to me.

Looks like the unit test does good coverage of if this is actually working now. Lets land it and get some real world testing on it.

**Comment by EricDavisX** [comment]
I pulled the branch gcp agent artifact for linux .tar.gz and tested it out and the logging seems to be turned off or on exactly as policy states without problem now.  this is great, nice work Michal

**Review by EricDavisX — APPROVED** [review]
tests like it works to me.

**Pull request merged**
