### PR TITLE
Cherry-pick #22557 to 7.x: add unit file states to system/service

### PR DESCRIPTION
**Pull request by fearful-symmetry**
Cherry-pick of PR #22359 to 7.x branch. Original message: 

## What does this PR do?

This PR adds the unit file state to `system/service` This tells you if the service is enabled or disabled, and what the vendor default is.

## Why is it important?

This is an important bit of data that appears in `systemctl status ...`

## Checklist

- [X] My code follows the style guidelines of this project
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

- Pull down PR and build
- run `system/service` on Linux, check to see if `unit_file` exists.

## Related issues

- https://github.com/elastic/beats/issues/22368

### CODE REVIEW

**Comment by ChrsMark** [comment]
🤔 something looks weird with backport? does look to be a backport for https://github.com/elastic/beats/pull/22359

**Comment by fearful-symmetry** [comment]
Argh, what the heck

**Comment by fearful-symmetry** [comment]
This is the PR that I'm trying to backport, somehow the Tool got the wrong label?

**Comment by fearful-symmetry** [comment]
Okay, fixed.

**Review by sayden — APPROVED** [review]

**Pull request merged**
