### PR TITLE
[Metricbeat] Add field description to MSSQL

### PR DESCRIPTION
**Pull request by sayden**
Tries to fix https://github.com/elastic/beats/issues/11893 (_[Metricbeat] Flaky test mssql_)

### CODE REVIEW

**Comment by exekias** [comment]
this probably needs a `make update`

**Comment by sayden** [comment]
> this probably needs a `make update`

Thanks Carlos, you're completely right. Apart from the `mage fmt update `in xpack folder a `make update` is also needed on _common_ folder

**Comment by kaiyan-sheng** [comment]
Oh hmm so the check checks for fields are documented as well as the description 🤔

**Comment by kaiyan-sheng** [comment]
Does this PR need backport?

**Comment by sayden** [comment]
> Oh hmm so the check checks for fields are documented as well as the description

Yes? Actually I want to see if that's the problem but I don't think so, because failure would have been consistent.

> Does this PR need backport?

**Comment by sayden** [comment]
jenkins, test this please

Checked and no, it doesn't need it, at least not now / yet.

**Pull request merged**
