### PR TITLE
[WIP] Filebeat. Added option to filebeat to read files without disk cache. #3501 

### PR DESCRIPTION
**Pull request by shelomentsevd**
Issue #3501.
I added option to read files without disk cache for darwin, windows and unix systems except OpenBSD and Plan9.
Almost all code I took https://github.com/ncw/directio here. 
I'll be glad if somebody reviewed this. 
Also I don't know how to write documentation to this project I edit only one file: `input-common-harvester-options.asciidoc`, may be it's not enough.

### CODE REVIEW

**Comment by urso** [comment]
The directio package is MIT licensed. Please do not include and relicense other projects code.

The original issue was about NFS? Problem with NFS is, it is not made for concurrent writes and reads at all. NFS protocol might include meta-data updates in responses, while the data are actually not available yet. An alternative solution to direct IO that seems to work in practice:
- use state to get size of file -> track file size internally
- only read up to position given by stat
- actively update end file size internally via stat

**Comment by shelomentsevd** [comment]
@urso 
Thank you for your reply!

> The directio package is MIT licensed. Please do not include and relicense other projects code.
My mistake, I will use directio and will include it in vendor then.

About #3501:
I take this issue for another reason:
Sometimes log files take all disk cache and displace other files from him. 
By using DIRECT_O I want to control it.

Does your solution solve this?

**Comment by urso** [comment]
Well, your use-case is different from the problem described in #3501 (The title is misleading). The description of #3501 is clearly about trying to solve issues with NFS, not about introducing direct IO per se.

NFS is quite a beast and there are subtle differences in protocol version/implementation details which makes me wonder if direct IO is really the final/good and portable solution for NFS.

> I took this issue for another reason:
Sometimes log files take all disk cache and displace other files from him.
By using DIRECT_O I want to control it.

That's a valid reason for sure.

**Comment by jsoriano** [comment]
@urso even if this is for a different use case, would it also solve the issue with NFS? should we continue with this PR? There are some merge conflicts that would need to be solved.

**Pull request closed without merging**
