### PR TITLE
Update indexing.go

### PR DESCRIPTION
**Pull request by HeGaoYuan**
Docs

### CODE REVIEW

**Comment by jsoriano** [comment]
Hey @HeGaoYuan, thanks for opening this PR! For us to accept it you would need to [sign the CLA](https://www.elastic.co/contributor-agreement) with the same email address you used in your commits, could you please do it?

**Review by jsoriano — APPROVED** [review]

**Comment by HeGaoYuan** [comment]
@jsoriano 
I have signed the CLA two days ago. I do not know why it is failing to check

**Comment by jsoriano** [comment]
> @jsoriano
> I have signed the CLA two days ago. I do not know why it is failing to check

Oh, I see the check green now, I don't know what happened, thanks!

**Pull request merged**
