### PR TITLE
x-pack/winlogbeat: move event.ingested setting to routing

### LINKED ISSUE #30516: [Winlogbeat] Move addition of event.ingested field from the modules' pipelines to the winlogbeat-routing pipeline
**Describe the enhancement:**

Move addition of ecs field `event.ingested` from the modules' pipelines (sysmon, security, powershell and powershell_operational) pipelines to the `winlogbeat-{{agent.version}-}routing` pipeline.

**Describe a specific use case for the enhancement or feature:**

- As an Elasticsearch user I want all indices to be ECS-compliant
- As an Elasticsearch user I want to see the latency between the event on the original machine (@timestamp), generation of the event in winlogbeat (event.created) and the arrival to elasticsearch (event.ingested)
- As a Kibana user I may want to create index-patterns based on `event.ingested` instead of `@timestamp`

**References**

See #29435 for additional details

### PR DESCRIPTION
**Pull request by efd6**
## What does this PR do?

This moves setting `event.ingested` from individual pipelines to the routing pipeline.

## Why is it important?

The change allows enrichment of events with `event.ingested` from outside the four existing pipelines.

## Checklist

- [x] My code follows the style guidelines of this project
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ] 

## Related issues

- Closes #30516.
- Requires #30406.

### CODE REVIEW

**Comment by rdner** [comment]
@mergify update

**Comment by efd6** [comment]
The re-addition of endpoint-level tests is not enough to test this, so it will need to wait until the full winlogbeat tests are implemented. Even then, I'm not sure how this would be tested — that `event.ingested` exists and is parsable as a timestamp?

**Comment by efd6** [comment]
This now has the additional tests.

**Pull request merged**
