### PR TITLE
[Heartbeat] Fix expiration of cert chains calculation

### PR DESCRIPTION
**Pull request by andrewvc**
Fixes https://github.com/elastic/beats/issues/33215

This is a bit WIP in that I'm not certain this is the final logic we want. It appears the elastic agent libs override the default golang TLS implementation's verification and only set the cert chains attribute on the connection when `strict` validation is enabled, where the default is `full`. See https://www.elastic.co/guide/en/beats/heartbeat/current/configuration-ssl.html for definition of the various validation options.

I suspect we'd be best off making strict the default since this is what chrome does nowadays, requiring a SAN to be set, which is the only distinction between the checks of `strict` and `full`.

To test this use the following config, which returns a too-early expiration date without this patch:

```
- type: http
  enabled: true
  id: wyportal
  name: WYPortal
  schedule: "@every 1m"
  ssl.verification_mode: strict
  urls: "https://portals.edu.wyoming.gov/"
```

You can try playing with the verification mode as well

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

Use the above config and run and build with the following command to prune the output. Note this requires your heartbeat yaml to not have an `output` section set.
```
mage build && ./heartbeat -e  -E output.console={} | jq '{"id": .monitor.id, "na": .tls.server.x509.not_after}'
```

### CODE REVIEW

**Review by emilioalvap — COMMENTED** [review]
On the `strict` by default issue, it would seem the actual config that drives chain behaviour is `InsecureSkipVerify`, not `verification_mode` itself. Could we add this as a default for all https monitors? It would still make possible to get the correct result with `full` verification mode.

**Comment by andrewvc** [comment]
@emilioalvap this is now ready for review again, I spent probably a bit too much effort improving the logic and test cases in aa35bb0 , while I think it could be cleaned up further, given that this requires strict, I think it covers more than can probably be justified given the effort of digging up the right certs.

**Comment by paulb-elastic** [comment]
Taking the PR off the board as the [parent issue](https://github.com/elastic/beats/issues/33215) is on there

**Review by emilioalvap — APPROVED** [review]
LGTM, reviewed test scenarios locally and it holds up. Still some linting to fix, though

**Comment by andrewvc** [comment]
@Mergifyio backport 7.17

**Pull request merged**
