### PR TITLE
libbeat: allow to extend "make clean" rule

### PR DESCRIPTION
**Pull request by cyrilleverrier**

### CODE REVIEW

**Comment by tsg** [comment]
jenkins, package it

**Comment by tsg** [comment]
Should we also update `generate/beat/Makefile`?

**Comment by tsg** [comment]
jenkins, test it

**Comment by cyrilleverrier** [comment]
> Should we also update generate/beat/Makefile?
@ruflin said he is going to re-implement the beat generator anyway.

**Comment by ruflin** [comment]
@cyrilleverrier @tsg I think the generate Makefile does not have to be updated, as it does not depend on the libbeat one.

**Comment by ruflin** [comment]
jenkins, retest it

**Pull request merged**
