### PR TITLE
libbeat/beat: add ClientConfig.WaitCloseChan

### PR DESCRIPTION
**Pull request by axw**
## What does this PR do?

This PR adds a `ClientConfig.WaitCloseChan` channel which, if signalled/closed, will interrupt `Client.Close`. Setting either `ClientConfig.WaitClose` (duration) or `Client.WaitCloseChan` (channel) will cause the client to wait for enqueued events to be acknowledged, or for one of the wait conditions to be satisfied.

## Why is it important?

Users of `pipeline.Client` may wish to block for a limited amount of time while closing the client. Currently there is a single means of achieving this: setting `WaitClose` when creating the client. This means the wait time cannot be dynamically adjusted.

In APM Server we have a "shutdown timeout" configuration, which is intended to cover all operations during shutdown: graceful HTTP server shutdown, flushing internal event queues, and finally closing the pipeline.Client. The operations leading up to closing the client may take a non-negligible amount of time, so conceptually we need to adjust the `WaitClose` time while closing, by subtracting the amount of time taken so far from the configured shutdown timeout.

We can achieve this by creating a cancellable context and passing its Done channel in as WaitCloseChan; then cancelling it with a timer started at the beginning of the APM Server's shutdown sequence.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files~
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

https://github.com/elastic/apm-server/issues/3789

### CODE REVIEW

**Comment by axw** [comment]
@urso I'd appreciate a preliminary review of this before I go and add tests. I've marked it draft because I haven't done that yet.

**Comment by axw** [comment]
I'm going to rework this. Although I think passing context to Close would be the more idiomatic approach, for now we can do this less invasively by specifying a channel sibling to `libbeat/beat.Pipeline.WaitClose`.

**Comment by axw** [comment]
@urso this is now ready, please take a look.

If you're hesitant about adding the whole PR into 7.9, then I think we should cherry-pick 8aa304ec375304feb01b8242f3d5462e029ceecd.

**Comment by urso** [comment]
Have you considered to not rely on the waiting functionality from the pipeline? If possible I'd like to 'shrink' the pipeline API instead of adding more features. For example filebeat also has a shutdown timeout, but it is implemented using an ACKer that is attached to each beat.Client. The ACKer gets informed when an event is published, dropped by the processors, ACKed, or the Client is shut down. Using ACKers one can add behavior globally or locally, e.g. by incrementing and decrementing a counter.

Filebeat is somewhat special, because it creates events to be dropped on purpose, but still requires them to be ACKed in order, so special state updates can be forward to it's registry. The implementation could be simpler (as we're planning to fix this behavior in filebeat). For reference see the current filebeat event counter: https://github.com/elastic/beats/blob/master/filebeat/beater/filebeat.go#L235

Libbeat provides some common ACKer (and helpers) in [libbeat/common/acker](https://github.com/elastic/beats/blob/master/libbeat/common/acker/acker.go).

An ACKer that blocks on shutdown until all non-filtered events are published could be implemented like this (very naive implementation):

```
type waitPublishedACKer struct {
  wg sync.WaitGroup
}

func (a *waitPublishedACKer) AddEvent(event beat.Event, published bool) {
  if published {  // event not dropped by processors
    a.wg.Add(1)
  }
}

func (a *waitPublishedACKer) ACKEvents(n int) {
  a.wg.Add(-n)
}

// Close is used by the publisher pipeline to indicate that the beat.Client is closed. We ignore the signal, as we want to be informed for all pending operations
func (*waitPublishedACKer) Close() {}

func (a *waitPublishedACKer) Wait() {
  a.wg.Wait()
}

```

Being in control of the counting and 'Wait' we can be quite flexible in the implementation without touching the pipeline API (which is already quite big).

The acker can be hooked up like this (Filebeat postpones the `pipeline.Close` by blocking shutdown, but not the `Client.Close`):

```
shutdownWait := &waitPublishedACKer{}
pipeline = pipetool.WithACKer(pipeline, shutdownWait) // the new pipeline attaches the sutdownWait acker to each client on `Connect` or `ConnectWith`. ACKers are 'merged' if the input/client registers it's own ACKer
client := pipeline.Connect() // one can also pass the custom acker via ACKHandler
defer func() {
  shutdownWait.Wait()
  client.Close()
}()
```

If you look into Filebeat you will notice that it also installs the counter into the `beat.Client`. This is not really necessary, but a workaround by Filebeat itself to also account for "invalid" events. The acker approach should be enough.

The `ACKer` approach allows you to develop the functionality independent in apm-server. Still it would be nice to share it via `libbeat/common/acker`, so we can reuse the functionality at will (either local per input, or global per beat).

**Comment by axw** [comment]
@urso sounds reasonable. I'll take a look at that approach soonish. In the mean time, I'll create a separate PR for the bug fix.

**Comment by axw** [comment]
I've implemented this in https://github.com/elastic/apm-server/pull/3971; that won't be going in until 7.10.0. Once I'm satisfied the implementation works well for apm-server I'll create a PR to propose adding it to libbeat. Closing this one - thanks for your feedback @urso!

**Comment by urso** [comment]
> Once I'm satisfied the implementation works well for apm-server I'll create a PR to propose adding it to libbeat.

Cool, looking forward to it.

**Pull request closed without merging**
