### PR TITLE
Update saram dependency to v1.12

### PR DESCRIPTION
**Pull request by urso**
- Update to more recent sarama release
- Add lz4 compression option
- Add more configurable kafka versions
- Update docs

### CODE REVIEW

**Comment by ruflin** [comment]
jenkins, retest it

**Comment by urso** [comment]
> Should we add a changelog entry for this?

Will add changelog entry

> Do you want to have it merged as 1 commit or multiples?

use 'Squash and merge' please.

**Comment by tsg** [comment]
@urso intake error on this one.

**Comment by urso** [comment]
jenkins, test it

**Pull request merged**
