### PR TITLE
[build] Minimize Go and Python downloads from containers

### PR DESCRIPTION
**Pull request by andrewkroh**
## What does this PR do?

**Use host's Go pkg cache as GOPROXY in container**

When running integration tests in a container that involve buillding or testing Go code,
the container must download the Go module dependencies. If the host has already
downloaded them then this will allow the host's packages to be used as a cache.

This mounts $GOPATH/pkg/mod/cache/download inside the container then sets
GOPROXY to point to a file:// URL.

 **Use Python venv from repo root**

Instead of creating (and downloading) a new python venv on every container launch
reuse a shared venv from $repoRoot/build/ve/docker.

## Why is it important?

This allows for faster more reliable integ testing. It mostly helps developers who are running locally, less so for CI because each CI test uses a new machine were the host has none of the Go/Python packages already. But if we change CI images to contain some of the deps in the image then this would help.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by andresrc** [comment]
ping @elastic/integrations

**Comment by urso** [comment]
Cool. Do we even need to set GOPROXY? Can't we just mount the default module cache location?

**Comment by andrewkroh** [comment]
That is an option. I tested it once while putting this together. It worked, but I wasn't sure if modifying the pkg cache from Docker could result in any soft of conflicts with the host machine (like concurrent updates). It's probably safe. Want me to change it?

**Comment by urso** [comment]
> Docker could result in any soft of conflicts with the host machine (like concurrent updates). It's probably safe. Want me to change it?

Good point about soft conflicts. When run from within docker the owner of the additional downloads on the host might be root.

GOPROXY supports multiple entries, I don't think there is a need to change the PR.

**Comment by andrewkroh** [comment]
Oh, yeah... I forgot about the `root` owned file issue.

**Pull request merged**
