### PR TITLE
Update golang/x/text to 4e4a3210bb54bb31f6ab2cdca2edcc0b50c420c1 (latest version on master branch)

### PR DESCRIPTION
**Pull request by cyrilleverrier**

### CODE REVIEW

**Comment by ruflin** [comment]
jenkins, test it

**Comment by cyrilleverrier** [comment]
Probably a different behaviour with end of line?
Maybe the python tests needs \r\n on Windows

**Comment by ruflin** [comment]
In case someone has time to look into it, here are the generated test files + logs: https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-windows/3154/beat=filebeat,label=windows/artifact/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_harvester.Test.test_decode_error/

**Comment by cyrilleverrier** [comment]
@ruflin could you please force a new build? I changed the test slightly and I tested on Windows 10.

**Comment by ruflin** [comment]
jenkins, test it

**Comment by cyrilleverrier** [comment]
jenkins is stucked at `11:12:33 + docker kill ffefbaa50d60`: https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/3203/beat=packetbeat,label=ubuntu/console

**Comment by cyrilleverrier** [comment]
Could someone trigger a new Jenkins build, please?

**Comment by ruflin** [comment]
jenkins, test it

**Comment by cyrilleverrier** [comment]
@ruflin good to be merged? I will rebase PR https://github.com/elastic/beats/pull/6341 afterwards

**Pull request merged**
