### PR TITLE
Replace optional FlagsHandler interface with callback list

### PR DESCRIPTION
**Pull request by urso**

### CODE REVIEW

**Comment by ruflin** [comment]
LGTM. Not sure if any other beats made use of this. 

The flags handler is also documented in the newbeat.asciidoc. This should be removed / changed.

**Comment by urso** [comment]
@ruflin newbeat doc will be adjusted once all changes are in place.

**Comment by dedemorton** [comment]
@ruflin I'm removing mention of the flags handler from newbeat.asciidoc for now. Let me know what, if anything, I should say in that doc about adding custom flags.

**Comment by ruflin** [comment]
@dedemorton The addition of custom flags should be very rare and config options should be used. So no need to add docs about it.

**Pull request merged**
