### PR TITLE
Support `log_format combined` setting of NGINX access logs

### LINKED ISSUE #6798: Filebeat - nginx module - grok fail
If some fcgi application like php throws errors to nginx then they look like this in the nginx error log:

```
2018/04/07 20:21:45 [error] 16234#0: *88661 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught exception 'Exception' with message 'TEST' in /var/www/vhosts/src/index.php:19
Stack trace:
#0 /var/www/vhosts/src/index.php(7): {closure}()
#1 /var/www/vhosts/src/index.php(19): awd::run(Object(Closure))
#2 {main}
  thrown in /var/www/vhosts/src/index.php on line 19" while reading response header from upstream, client: 79.237.34.117, server: localhost.net, request: "GET /?awd=de HTTP/2.0", upstream: "fastcgi://unix:///var/www/vhosts/system/php-fpm.sock:", host: "localhost.net"
```

The grok pattern in the filebeat nginx module can not parse this format.
The field `error.message` contains:

`Provided Grok expressions do not match field value: `...

- Version: filebeat version 6.2.3 (amd64), libbeat 6.2.3
- Operating System: Debian 8.10

### PR DESCRIPTION
**Pull request by kvch**
The following log line was not parsed successfully:
```
127.0.0.1 - - [12/Apr/2018:09:48:40 +0200] "" 400 0 "-" "-"
```
`""` had to match the pattern ```
\"%{WORD:nginx.access.method} %{DATA:nginx.access.url} HTTP/%{NUMBER:nginx.access.http_version}\"```

It failed because those fields had to be there, empty values were not accepted. Also the pattern looks for `HTTP/` which was also missing.

Now missing fields are allowed in this part of the message.

Closes #6798

### CODE REVIEW

**Comment by ph** [comment]
@kvch can you add a test case for that change?

**Comment by kvch** [comment]
sure.
something is still failing due to my change.

**Comment by kvch** [comment]
Should be fixed now. Let's see what the CIs have to say. :)

**Comment by ph** [comment]
@kvch Changes look good, waiting for Travis and Jenkins to do the CI dance.

**Comment by kvch** [comment]
@ph The failing test is unrelated to this change.

**Pull request merged**
