### PR TITLE
[Filebeat][New Module] Snyk vulnerabilities and audit logs

### PR DESCRIPTION
**Pull request by P1llus**
## What does this PR do?

Adds support for collecting found vulnerabilities and audit logs from the Snyk API.

## Why is it important?

Adds support for new OOTB products to Filebeat.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Requires https://github.com/elastic/beats/pull/22320

### CODE REVIEW

**Comment by P1llus** [comment]
This PR is not fully ready yet for review. It requires the updates to the httpjson input, so the config template is not finalized, and the documentation needs to be updated.

**Comment by P1llus** [comment]
jenkins test please

**Comment by P1llus** [comment]
jenkins test this

**Review by leehinman — APPROVED** [review]
Looks great

**Comment by P1llus** [comment]
the templating delimiters changed in the last minute, so do not merge yet, need to apply changes for https://github.com/elastic/beats/pull/23056

**Comment by P1llus** [comment]
The updates have now been pushed, some internal teams have already tested the module as well and its working fine. Might want to add some more ECS fields or testing after merge.

**Pull request merged**
