### PR TITLE
Fleet apache: convert status.total_kbytes to status.total_bytes

### PR DESCRIPTION
**Pull request by mtojek**
## What does this PR do?

This PR modifies the the `apache.status` metricset to report `apache.status.total_bytes` instead of `apache.status.total_kbytes` in the fleet mode.

## Why is it important?

This change is required to improve overview dashboard and support human readable format (expects bytes input). 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

It will be tested by the CI in the Integrations project. 

## Related issues

- https://github.com/elastic/integrations/issues/370

### CODE REVIEW

**Comment by mtojek** [comment]
@jsoriano let me assign you to this PR as it's similar to the last one in terms of the Apache integration.

**Comment by fearful-symmetry** [comment]
>  in the fleet mode.

I don't see anything here that would make this only function while under fleet? Maybe I'm missing something.

**Review by jsoriano — APPROVED** [review]

**Comment by mtojek** [comment]
Thanks!

**Pull request merged**
