### PR TITLE
Rename filter to filters

### PR DESCRIPTION
**Pull request by ruflin**

### CODE REVIEW

**Comment by monicasarbu** [comment]
LGTM. Shall we add this change to alpha2?

**Comment by ruflin** [comment]
I would think so.

**Comment by andrewkroh** [comment]
There's more, this one and its test: https://github.com/elastic/beats/blob/master/winlogbeat/config/config.go#L37

I can open a PR for it in a bit.

**Comment by ruflin** [comment]
@andrewkroh I missed these :-(

**Pull request merged**
