### PR TITLE
elasticsearch: set _type=doc

### PR DESCRIPTION
**Pull request by 7AC**
Use special `_type=doc` instead of custom ones. The `_type` field is deprecated per https://github.com/elastic/elasticsearch/issues/15613.

### CODE REVIEW

**Comment by ruflin** [comment]
Can you link to the elasticsearch / pr of the change to provide some more feedback on why this change is needed?

This must be added to the CHANGELOG.asciidoc as this is a breaking change in case someone was using _type before. This becomes especially obvious for people using filebeat where `document_type` was mapped to `_type`.

**Comment by ruflin** [comment]
Can you rebase and squash and update the commit and PR message? This makes it easier for people that stumble over the PR later to find the right info.

**Comment by 7AC** [comment]
I updated the first comment to the PR, I have a single commit I don't think I need squashing. Thanks!

**Comment by ruflin** [comment]
@7AC I see 2 commits in this PR? One is a merge commit.

**Pull request merged**
