### PR TITLE
Add Mesos module to Metricbeat

### PR DESCRIPTION
**Pull request by berfinsari**

### CODE REVIEW

**Comment by ruflin** [comment]
Hi @berfinsari . We discussed the Mesos module a bit internally. Our current problem is that we don't feel very comfortable yet to support it as we lack the knowledge around mesos and resources internally as the focus is currently on a few other big modules. 

As usual, your contribution is of high quality and it would be great to still get this code out there. I'm wondering if you potentially could put this into a mesosbeat (in case it doesn't exist yet) so community members can already start to use it and we get some feedback on it?

**Comment by berfinsari** [comment]
Thanks for the review! @ruflin .
I created mesosbeat elastic/beats#12185 . So We can talk again for mesos module with regard to the feedback we will have.

**Comment by ruflin** [comment]
@berfinsari Great, thanks a lot. See my comment there about having it as still a module in a Beat. The advantage is that the output format would look identical as inside the Beat, so a later transition would be seamless.

Are you ok if we close this PR for now?

**Comment by berfinsari** [comment]
Thanks, @ruflin.
I am okay to close Mesos PR for now.  I updated the Mesosbeat to beat based on Metricbeat so after the feedback, I am willing to contribute Mesos module.

**Comment by ruflin** [comment]
@berfinsari Thanks for all your work.

@exekias @andresrc FYI

**Pull request closed without merging**
