### PR TITLE
[Metricbeat] migrate consul module to ReporterV2 error

### PR DESCRIPTION
**Pull request by berfinsari**
See elastic/beats#11374 and elastic/beats#10727

### CODE REVIEW

**Comment by ruflin** [comment]
jenkins, test this

**Comment by ruflin** [comment]
One more that needs rebase. @berfinsari Sorry, we had some issues with the debian package dependencies which affects all new builds.

**Comment by berfinsari** [comment]
Thank you for the review @ruflin

**Comment by ruflin** [comment]
jenkins, test this

**Pull request merged**
