### PR TITLE
Heartbeat support options for lightweight checks

### PR DESCRIPTION
**Pull request by lowryxiao**
## What does this PR do?

According to this issue:
https://github.com/elastic/beats/issues/32457
We're looking for a way to support url check with OPTIONS method.

## Why is it important?
With this change, heartbeat could do the url check with OPTIONS without any more response message.

## Checklist
- [*] My code follows the style guidelines of this project
- [*] I have commented my code, particularly in hard-to-understand areas
- [*] I have made corresponding changes to the documentation
- [] I have made corresponding change to the default configuration files
- [*] I have added tests that prove my fix is effective or that my feature works
- [] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally
```
# go to heartbeat dir, something like `beats/heartbeat`
mage update
mage pythonUnitTest 
# heartbeat/tests/system/test_monitor.py::Test::test_http_check_with_options_method_#num were my unittest
```

## Related issues
https://github.com/elastic/beats/issues/32457

## Use cases
```
new options for check url.check:
check.request.method: OPTIONS
```

full example is
```
heartbeat.monitors:
- type: http
  schedule: '@every 1s'
  hosts:
    - 'localhost:64572'
    
  check.request.method: OPTIONS
```

### CODE REVIEW

**Comment by lowryxiao** [comment]
enhancement

**Review by andrewvc — APPROVED** [review]
LGTM

**Comment by andrewvc** [comment]
Thanks for the contribution @lowryxiao !

**Comment by lowryxiao** [comment]
Welcome.
Thanks for the review, Andrew.

**Pull request merged**
