### PR TITLE
[gcp] Add gcp.dns filebeat fileset

### PR DESCRIPTION
**Pull request by LiamSennitt**
## What does this PR do?

Add gcp.dns filebeat fileset.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Relates https://github.com/elastic/integrations/pull/2624

### CODE REVIEW

**Comment by andrewkroh** [comment]
Hi @LiamSennitt, we are in the progress of migrating most of the Filebeat modules towards Fleet integrations ([contributing](https://github.com/elastic/integrations/blob/main/CONTRIBUTING.md) / [overview docs](https://www.elastic.co/guide/en/fleet/7.16/fleet-overview.html#unified-integrations)). So instead of adding new features in the module we prefer to target them directly in the [GCP integration](https://github.com/elastic/integrations/tree/main/packages/gcp). Would you be interested in moving your contribution over?

If you aren't familiar with Fleet integrations, there are several benefits. There's better development tools for building/testing the integration. The data will be indexed into its own data stream (logs-gcp.dns-*) so you have a smaller index template that only contains the gcp.dns fields. You can more fine grained control over retention periods for each type of data. There's no more beat setup command since index templates/pipelines/dashboards are all managed by Kibana.

If you haven't migrated over to [Agent](https://www.elastic.co/guide/en/fleet/7.16/fleet-overview.html#elastic-agent) you can install an integration in Kibana then configure your Beat input to write data to the integration's data stream (I've been using this a bit in transitions).

**Comment by LiamSennitt** [comment]
Hi @andrewkroh, I'll make a second PR to add this as a Fleet integration.

I would still be quite keen to get this added to as a filebeat module if you're still accepting contributions? I would imagine there are sill quite a few people who haven't migrated over to the Elastic Agent since Fleet was in `beta` until quite recently?

**Comment by LiamSennitt** [comment]
Hi @andrewkroh, PR for elastic integration opened [2624](https://github.com/elastic/integrations/pull/2624).

**Comment by LiamSennitt** [comment]
@andrewkroh is there any likelihood of this being merged?

**Comment by rdner** [comment]
@mergifyio update

**Comment by rdner** [comment]
jenkins run tests

**Comment by rdner** [comment]
@LiamSennitt please run `make update` in the root of the repository, it should make changes in these files as well:
* x-pack/filebeat/filebeat.reference.yml
* x-pack/filebeat/module/gcp/fields.go 
* x-pack/filebeat/modules.d/gcp.yml.disabled

**Comment by andrewkroh** [comment]
Given we have this available in Fleet (https://docs.elastic.co/en/integrations/gcp#dns) I'm inclined to close this so that we are not adding more new things into Beats that we need to maintain. If you haven't migrated to Agent/Fleet yet you may be able to take advantage of the GPC DNS integration with steps like [this](https://gist.github.com/andrewkroh/c253717ebe82f2ec47fe003eda99c1dc).

**Pull request closed without merging**
