### PR TITLE
adding a for loop with script processor to add values from cisco.umbrella.identities to related.user field

### PR DESCRIPTION
**Pull request by hungnguyen-elastic**
Enhancement Request

## What does this PR do?

This PR added the foreach loop to append the value from cisco.umbrella.identities field to related.user field in cisco umbrella module pipeline
```
- script:
    if: ctx?.cisco?.umbrella?.identities != null && ctx?.related?.user!= null
    lang: painless
    description: "Extract user name values from ctx.cisco.umbrella.identities and append it to related.user"
    source: |
      for (def x=0; x < ctx?.cisco?.umbrella?.identities.size(); x++) {
        def cisco_identity = ctx?.cisco?.umbrella?.identities[x];
        if (cisco_identity.contains('@') && !ctx?.related?.user.contains(cisco_identity)) {
          ctx?.related?.user.add(cisco_identity)
        }
      }
```
## Why is it important?

There are instances where cisco.umbrella.identities actually contains the username that is involved with the action and is not included in the related.user field. This addition will make sure the values are added. 

for example: event below will be missing the actual username in the related.user field

"message" : "\"2021-05-14 19:39:58\",\"hostname34P787\",\"hostname34P787,User Name(userName@domain.com)\",\"1.1.1.1\",\"2.2.2.2\",\"Allowed\",\"1 (A)\",\"NOERROR\",\"v-google.com.\",\"Infrastructure\",\"Roaming Computers\",\"Roaming Computers,AD Users\",\"\""

Output: 
```
          "related" : {
              "user" : [
                "hostname34P787"
              ]
           }
```

With the script processor
```
          "related" : {
            "user" : [
              "hostname34P787",
              "User Name(userName@domain.com)"
            ]
```

## Checklist

- [ x ] My code follows the style guidelines of this project
- [ x ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ x ] I have made corresponding change to the default configuration files
- [ x ] I have added tests that prove my fix is effective or that my feature works
- [ x ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by leehinman — CHANGES_REQUESTED** [review]
Thank You.

Do you have any example logs we can add to the test directory that will exercise this?

For the script, I made a few changes:
  -  will add `related.user` if it doesn't exist
  - will only iterate on `cisco.umbrella.identities` if it is a list

Can you test to see if this works?

``` yaml
- script:
    if: ctx?.cisco?.umbrella?.identites != null && ctx.cisco.umbrella.identites instanceof List
    lang: painless
    description: "Extract user name values from ctx.cisco.umbrella.identities and append it to related.user"
    source: |-
      void addRelatedUser(def x) {
        if (ctx?.related == null) {
          Map map = new HashMap();
          ctx.put("related", map);
        }
        if (ctx?.related?.user == null) {
          ArrayList al = new ArrayList();
          ctx.related.put("user", al);
        }
        if (!ctx.related.user.contains(x)) {
          ctx.related.user.add(x);
        }
      }

      for (cisco_identity in ctx.cisco.umbrella.identities) {
        if (cisco_identity_contains('@')) {
          addRelatedUser(cisco_identity);
        }
      }
```

**Comment by leehinman** [comment]
oops, need to pass in the context.

``` yaml
- script:
    if: ctx?.cisco?.umbrella?.identites != null && ctx.cisco.umbrella.identites instanceof List
    lang: painless
    description: "Extract user name values from ctx.cisco.umbrella.identities and append it to related.user"
    source: |-
      void addRelatedUser(def ctx, def x) {
        if (ctx?.related == null) {
          Map map = new HashMap();
          ctx.put("related", map);
        }
        if (ctx?.related?.user == null) {
          ArrayList al = new ArrayList();
          ctx.related.put("user", al);
        }
        if (!ctx.related.user.contains(x)) {
          ctx.related.user.add(x);
        }
      }

      for (cisco_identity in ctx.cisco.umbrella.identities) {
        if (cisco_identity.contains('@')) {
          addRelatedUser(ctx, cisco_identity);
        }
      }
```

**Comment by hungnguyen-elastic** [comment]
@leehinman There was a typo in the condition which I corrected and it works like a charm. identites --> identities. I will sanitize the sample logs and share it

```
- script:
    if: ctx?.cisco?.umbrella?.identities != null && ctx.cisco.umbrella.identities instanceof List
    lang: painless
    description: "Extract user name values from ctx.cisco.umbrella.identities and append it to related.user"
    source: |-
      void addRelatedUser(def x) {
        if (ctx?.related == null) {
          Map map = new HashMap();
          ctx.put("related", map);
        }
        if (ctx?.related?.user == null) {
          ArrayList al = new ArrayList();
          ctx.related.put("user", al);
        }
        if (!ctx.related.user.contains(x)) {
          ctx.related.user.add(x);
        }
      }

      for (cisco_identity in ctx.cisco.umbrella.identities) {
        if (cisco_identity_contains('@')) {
          addRelatedUser(cisco_identity);
        }
      }
```

**Review by leehinman — APPROVED** [review]

**Review by P1llus — APPROVED** [review]
LGTM

**Pull request merged**
