### PR TITLE
ci: use withKindEnv step

### PR DESCRIPTION
**Pull request by v1v**
## What does this PR do?

Use https://github.com/elastic/apm-pipeline-library/pull/1530

## Why is it important?

DRY

### CODE REVIEW

**Comment by v1v** [comment]
@Mergifyio rebase

**Comment by v1v** [comment]
@Mergifyio rebase

**Comment by v1v** [comment]
```
[2022-02-21T14:05:07.463Z] /var/lib/jenkins/workspace/PR-30275-8-f965bd4d-8ccb-4be4-a9d4-eb6236426fdd/.magefile cleaned
[2022-02-21T14:05:07.464Z] rm -f build/TEST-go-integration.out
[2022-02-21T14:05:07.464Z] mage goIntegTest || ( cat build/TEST-go-integration.out && false )
[2022-02-21T14:05:54.205Z] Generated fields.yml for metricbeat to /var/lib/jenkins/workspace/PR-30275-8-f965bd4d-8ccb-4be4-a9d4-eb6236426fdd/src/github.com/elastic/beats/metricbeat/fields.yml
[2022-02-21T14:05:54.205Z] Generated fields.yml for metricbeat to /var/lib/jenkins/workspace/PR-30275-8-f965bd4d-8ccb-4be4-a9d4-eb6236426fdd/src/github.com/elastic/beats/metricbeat/fields.yml
[2022-02-21T14:07:32.516Z] Error: failed modules: kubernetes
[2022-02-21T14:07:32.516Z] cat: build/TEST-go-integration.out: No such file or directory
[2022-02-21T14:07:32.516Z] ../dev-tools/make/mage.mk:51: recipe for target 'integration-tests' failed
[2022-02-21T14:07:32.516Z] make: *** [integration-tests] Error 1
```

No clue what's going on...

**Comment by jlind23** [comment]
@v1v if this PR is still relevant, could you please update the backport label accordingly? I do not think that 8.0 is still useful.

**Pull request closed without merging**
