### PR TITLE
ironbank: validate with retry

### PR DESCRIPTION
**Pull request by v1v**
## What does this PR do?

Retry a few times

## Why is it important?

HA for the docker registry is not in place, so this will avoid the overhead to analyse failures related to timeouts or networking with the docker registry.

The downside is related with genuine failures, since they will be retried a few times... although I don't expect any problems since the existing pipeline in  based on a timer so it will not affect anything else

image

### CODE REVIEW

**Comment by cachedout** [comment]
I think this particular approach is fine, but I also wonder if there might be a trick that we're missing, especially for these cases where restarting the pipeline after a failure might result in some inconsistency. Basically, I am wondering if we should consider something like a "pre-flight" check at the very beginning of the pipeline where we ensure that all external services are available before continuing? That way, we could fail early in the event of a service dep being down and we wouldn't waste time and energy continuing.

WDYT?

**Comment by v1v** [comment]
> Basically, I am wondering if we should consider something like a "pre-flight" check at the very beginning of the pipeline where we ensure that all external services are available before continuing

I thought about it, but flakiness can happen even after the `pre-flight` during the docker image generation, ideally, the docker caching should help if it happens.

The docker image generations, relies on [docker.elastic.co, google storage and the APT mirrors](https://github.com/elastic/beats/blob/15e846c2749412b2884553664d5a3905a51f1bce/dev-tools/packaging/templates/ironbank/heartbeat/hardening_manifest.yaml#L59-L90) to fetch the required dependencies, any of those third party systems could be flaky.

That's the reason the retry is the hardcore fix when I asked about this to the System owners back in the days, they mentioned to use a retry. That's in fact what we do in https://github.com/elastic/apm-pipeline-library/blob/dce3ec188d28b51bd1117f2114c9030ea5483ecc/vars/withDockerEnv.groovy#L47-L49 

Do you think the `pre-flight` is the most appropriate approach in this case?

**Comment by cachedout** [comment]
> Do you think the pre-flight is the most appropriate approach in this case?

My thinking was that the pre-flight itself would contain retries, just to try and eliminate any flakiness.

**Comment by v1v** [comment]
> My thinking was that the pre-flight itself would contain retries, just to try and eliminate any flakiness.

Do you mean https://github.com/elastic/beats/pull/33163/commits/14b98f94f01b2994a9ac3e886be071190317738a ?

Just bear in mind, the `pre-flight` won't warranty a flakiness could happen when building the docker image within the `validate` stage.

**Review by cachedout — APPROVED** [review]

**Pull request merged**
