### PR TITLE
[Manual backport][Heartbeat] Unpack beats in elastic-agent docker image

### PR DESCRIPTION
**Pull request by emilioalvap**
Manual backport of elastic/elastic-agent#202

## What does this PR do?

This PR enables unpacking of beats inside the container at build time, so that required `cap_net_raw, cap_setuid` capabilities can be assigned to the binary.

## Why is it important?

Without the required capabilities, heartbeat cannot execute ICMP pings or setuid calls. As it is now, agent is unpacking beats at runtime, most likely with a user that doesn't have permission to assign capabilities.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have made corresponding change to the default configuration files

## Author's Checklist

- [ ]

## How to test this PR locally

- Build elastic-agent containers, run:
`DEV=true SNAPSHOT=true PLATFORMS=linux/amd64 TYPES=docker mage package`
- Run one of the built containers and provide some heartbeat configuration:
```
docker run --name agent -it -u root --env FLEET_ENROLL=1 --env \
FLEET_URL=<url> --env \ 
FLEET_ENROLLMENT_TOKEN=<token> \ 
docker.elastic.co/beats/elastic-agent:8.2.0-SNAPSHOT
```

## Related issues
- Relates elastic/beats#27651

## Screenshots
image

## Logs
````bash
15:38:37.323
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] heartbeat start running.
15:38:37.323
elastic_agent.heartbeat
[elastic_agent.heartbeat][warn] BETA: Fleet management is enabled
15:38:37.323
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Starting fleet management service
15:38:37.323
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] heartbeat is running! Hit CTRL-C to stop it.
15:38:37.323
elastic_agent.heartbeat
[elastic_agent.heartbeat][info] Effective user/group ids: 1000/1000, with groups: [0]
````

### CODE REVIEW

**Comment by andrewvc** [comment]
@Mergifyio update

**Comment by emilioalvap** [comment]
@Mergifyio update

**Review by michel-laterman — APPROVED** [review]

**Comment by emilioalvap** [comment]
Hi @elastic/beats, could someone provide a review for this PR? Thanks!

**Comment by cmacknz** [comment]
LGTM, you should be good with just the approval from the agent control plane team (which Michel has provided).

**Pull request merged**
