### PR TITLE
Cherry-pick #8768 to 6.x: Update Filebeat Traefik module to handle mixed Common and Combined Log Format

### PR DESCRIPTION
**Pull request by sayden**
Cherry-pick of PR #8768 to 6.x branch. Original message: 

This is a continuation of PRs https://github.com/elastic/beats/pull/6488 and https://github.com/elastic/beats/pull/6136

Previous PR's were misleading because there's no difference between Traefik 1.5 and 1.7 log formats but as you can see in this [issue](https://github.com/containous/traefik/issues/2649) Traefik could miss some quote which would make our parser to fail. So those PR's were to address that issue.

Traefik uses by default since 1.4 version (at least) the Combined Log Format https://httpd.apache.org/docs/trunk/logs.html#combined also used in Apache. In 1.7 it still uses this format but you can also setup Common Log Format or JSON. Maybe we should open an issue to support JSON in the future.

Solves https://github.com/elastic/beats/issues/8015 and https://github.com/elastic/beats/issues/6111
* `frontend_name` field was added so #8015 is solved.
* The Grok pattern have been improved to handle the case of #6111 and the log lines described there have been added to the test cases successfully so the issue is also solved.
* Added `user_identifier field` which was hardcoded to '-' before
* Added `duration` field which was missing too
* Added `request_count` field
* Numeric fields added as string have been converted to long like `response_code`

### CODE REVIEW

**Comment by ruflin** [comment]
CI failure seems to be related. It could be that it's related to a different Geoip processor in Elasticsearch 6.x. Try to run `make start` in this branch and generate the test outputs again.

**Comment by sayden** [comment]
jenkins, test this please

**Comment by sayden** [comment]
jenkins test this

**Comment by sayden** [comment]
jenkins, test this

**Pull request merged**
