### PR TITLE
libbeat/publisher/pipeline: expand monitoring

### LINKED ISSUE #22215: monitoring: report configured queue.mem.*, output.elasticsearch.workers, output.elasticsearch.bulk_max_size
**Describe the enhancement:**

Report additional metrics for telemetry/stack monitoring:

 - `queue.mem.events`
 - `output.elasticsearch.workers`
 - `output.elasticsearch.bulk_max_size`

**Describe a specific use case for the enhancement or feature:**

Part of the tuning exercise for APM Server is to tweak output parameters (https://www.elastic.co/guide/en/apm/server/current/tune-apm-server.html): `queue.mem.events`, `output.elasticsearch.workers`, and `output.elasticsearch.bulk_max_size`. At the moment there is no way to see, through Kibana, what the currently configured values are.

### PR DESCRIPTION
**Pull request by axw**
## What does this PR do?

Expand monitoring to report:

 - pipeline.queue.max_events (queue capacity)
 - output.batch_size (e.g. ES bulk_max_size)
 - output.clients (e.g. number of ES hosts * workers)

Queue capacity is recorded in stats rather than state so it can be used along with queue size to calculate saturation.

Note to reviewer, I introduced the `metricsObserverVars` type to avoid having awkward variable names just to avoid clashing with the method names.

## Why is it important?

In APM Server we recommend users tune `queue.mem.events`, `output.elasticsearch.bulk_max_size`, and `output.elasticsearch.worker` according to their scale. It would be helpful to be able to observe the current value in effect.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

Run a beat with the Elasticsearch output and monitoring enabled, and check the values of `pipeline.queue.max_events`, `output.batch_size`, and `output.clients` match the configuration.

## Related issues

Closes #22215

### CODE REVIEW

**Review by stuartnelson3 — APPROVED** [review]

**Review by blakerouse — APPROVED** [review]
Looks good to me.

**Review by urso — APPROVED** [review]

**Comment by axw** [comment]
Seems to be an issue with reporting Jenkins success, `packetbeat-windows-7-32-windows-7-32-bit` shows as failed but it has succeeded in the most recent build: https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-24700/7/pipeline

**Pull request merged**
