### PR TITLE
Add user.id to Sysmon's Event ID 13

### PR DESCRIPTION
**Pull request by janniten**
## What does this PR do?
Add the user.id  field to EVENT ID 13  (from field winlog.user.identifier)
https://www.elastic.co/guide/en/ecs/current/ecs-user.html#field-user-id
## Why is it important?
During the revision of some windows detection rules I've found that Sysmon's event ID13  does not populate the user.id field, so those rules won't work.
The affected rules are

- Startup or Run Key Registry Modification
- Potential LSA Authentication Package Abuse
- Network Logon Provider Registry Modification
- Potential Port Monitor or Print Processor Registration Abuse

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by efd6** [comment]
@janniten, the failure here is due to the change in year. You can fix this by merging master back into your branch.

**Comment by janniten** [comment]
> master back into your branch
HI @efd6, do I have to rebase?

**Comment by efd6** [comment]
You can either rebase this onto master or re-merge master back into this branch. Either will work.

**Comment by janniten** [comment]
> You can either rebase this onto master or re-merge master back into this branch. Either will work.

Done. Pls let me know if it is ok. Thanks!

**Pull request closed without merging**
