### PR TITLE
Fix logstash default bulk max size

### LINKED ISSUE #1662: logstash bulk_max_size only 1024 by default in 1.x releases
by default bulk_max_size for logstash is still 1024, but should be 2048.

Workaround: Set bulk_max_size for logstash output plugin.

### PR DESCRIPTION
**Pull request by urso**
Resolves #1662

### CODE REVIEW

**Comment by ruflin** [comment]
LGTM. 

@urso see second comment in #1662 You also want to add it here?

**Comment by urso** [comment]
Oh, thanks. Yeah, will introduce it

**Comment by ruflin** [comment]
@urso ok, thanks. I removed the review label so it doesn't get merged by accident.

**Comment by urso** [comment]
@ruflin done

**Comment by ruflin** [comment]
@urso not sure if we have to forward port this?

**Pull request merged**
