### PR TITLE
[Metricbeat] Don't query unused Uids in socket_summary metricset

### PR DESCRIPTION
**Pull request by Brian-Williams**
Closes elastic/beats#14649

Update gopsutil to tags/v2.19.11 and use `WithoutUids` function to avoid querying UIDs that we don't use in `calculateConnStats`.

### Performance
For call graph performance see the gopsutil discussion [here](https://github.com/shirou/gopsutil/pull/782#issue-331711001).

On an smp with 500 endpoints the performance went from measurable to noise with this change:

| field | beats off mean | beats on mean | delta (diff) | beats off P99 |  beats on P99 | delta(diff) |
|-------|---------------:|--------------:|-------------:|--------------:|--------------:|------------:|
|total cpu usage:sys |           0.91|           1.24|+36.03%(0.33)|           6.02|           6.65|+10.48%(0.63)|
|total cpu usage:usr |           8.11|           8.19|+1.02%(0.08)|          94.68|          93.30|-1.46%(-1.38)|

Additional testing was done on 50,000 endpoint systems.

Before change:
oldhtop

After change:
newhtop

### CODE REVIEW

**Comment by exekias** [comment]
Something weird happened with the vendor dir. We use [govendor](https://github.com/kardianos/govendor) to manage dependencies, did you use that tool to fetch the new version of gopsutil?

**Comment by Brian-Williams** [comment]
> Something weird happened with the vendor dir. We use [govendor](https://github.com/kardianos/govendor) to manage dependencies, did you use that tool to fetch the new version of gopsutil?

Ah thanks, I've only used dep and vgo. Deleted the vendored dir and updated with `govendor fetch github.com/shirou/gopsutil@=v2.19.11`. Please let me know if that's an incorrect usage.

**Comment by mtojek** [comment]
@Brian-Williams  Nice finding BTW.

I'm not confident about the constraint `=v2.19.11`. With this one you rejects all further upgrades and I wouldn't say this is an expected behavior.

**Comment by mtojek** [comment]
Also, some test seems to be failing:

```
ERROR: Test system/socket_summary output.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/gopath/src/github.com/elastic/beats/metricbeat/tests/system/test_system.py", line 471, in test_socket_summary
    summary = evt["system"]["socket"]["summary"]
KeyError: 'system'
```

**Comment by Brian-Williams** [comment]
Ah, this is a problem in the build targets. Will patch when I get a free moment.

**Comment by Brian-Williams** [comment]
A filebeat test failed, but I don't believe this change should've affected filebeat:
```
======================================================================
ERROR: Test basic start and replace with another input
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/gopath/src/github.com/elastic/beats/filebeat/tests/system/test_reload_inputs.py", line 109, in test_start_stop_replace
    self.wait_until(lambda: self.output_lines() == 1)
  File "/Users/travis/gopath/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 352, in wait_until
    "Waited {} seconds.".format(max_timeout))
TimeoutError: Timeout waiting for 'cond' to be true. Waited 10 seconds.
```

**Comment by exekias** [comment]
This one will need backport to 7.x, @mtojek will you handle it?

**Comment by mtojek** [comment]
@exekias Done. https://github.com/elastic/beats/pull/15047

**Pull request merged**
