### PR TITLE
Rename TEST-empty.xml to .out

### PR DESCRIPTION
**Pull request by mtojek**
~~_Please leave it as an experimental._~~

~~Trying to understand what will happen if TEST-empty.xml is deleted.~~

~~This PR removes file TEST-empty.xml, which left as empty one apparently fails Jenkins builds. I assumed that the file is here to verify RW permissions, so once it's successfully created it's removed.~~

~~If somebody can confirm that it's no required anymore, I can remove `touch` at all.~~

~~FTR Jenkins build job is green now.~~

I think I found a corresponding fix in the Git history. It has been applied to 7.x branches: https://github.com/elastic/beats/pull/12247

### CODE REVIEW

**Comment by mtojek** [comment]
jenkins, test it please

**Comment by mtojek** [comment]
jenkins, test this please

**Comment by exekias** [comment]
@andrewkroh perhaps you know more about this one?

**Comment by mtojek** [comment]
@exekias @andrewkroh I've renamed the file according to the fix applied in https://github.com/elastic/beats/pull/12247 

Also, the issue description has been updated.

**Comment by mtojek** [comment]
Thank you for the explanation!

**Pull request merged**
