### PR TITLE
[Metricbeat] Migrate couchbase cluster & pool metricset to new data generation

### PR DESCRIPTION
**Pull request by ruflin**
The data.json is now generated based on example JSON documents. In case they change, it means the code change in some way. This will make it much easier to detect changes.

Also the basic tests for the cluster are now covered by the new testing.

The error handling moved over to the new error interface for simplicity.

### CODE REVIEW

**Comment by ruflin** [comment]
@berfinsari Thanks to your work, this is now possible 🎉

**Comment by kaiyan-sheng** [comment]
@ruflin LGTM, just one question: data.json is generated by _meta/testdata/docs.json here, so does docs.json-expected.json still needed/useful here?

**Comment by fearful-symmetry** [comment]
Sorta going off what @kaiyan-sheng asked, should we handle the docs.json files differently?  Considering how many json files we'll have floating around as we migrate more tests to this, I wonder if there's a more clever solution to `data.json` in general? That's probably a longer term question, though. 

Otherwise LGTM, but do we want to update the ReporterV2 error handling in the same PR?

**Comment by ruflin** [comment]
@kaiyan-sheng I would say yes. There is a difference here. If the `data.json` is not correct, we will get a diff but unit tests do not fail. If the expected is wrong, tests will fail. Also `data.json` only takes the first event if their are multiple, in the expected-json there are all events produced.

@fearful-symmetry I'm sure there are better ways. Perhaps you can open an issue to discuss it with a suggestion?

For the error handling: If you prefer, I can also put it into a different PR.

**Comment by ruflin** [comment]
@fearful-symmetry I remove the logging change, we can tackle it in a separate PR.

**Comment by sayden** [comment]
Tested locally. Everything ok

**Pull request merged**
