### PR TITLE
Metricbeat docs fixes

### PR DESCRIPTION
**Pull request by robin13**
Corrected docs for new metricbeat / diskio / await section (there was a copy/paste error)

### CODE REVIEW

**Comment by exekias** [comment]
Thanks @robin13! asciidoc files are autogenerated, you will need to update https://github.com/elastic/beats/blob/master/metricbeat/module/system/diskio/_meta/fields.yml#L103 and run `make update` to reflect this change :smiley:

**Comment by robin13** [comment]
Ahh... better now @exekias ? :)

**Comment by ruflin** [comment]
@robin13 You updated it now in the right place but you need to run `make update` in metricbeat to also created the generated parts.

**Comment by robin13** [comment]
@ruflin I've been trying all morning with @tsg to get `make update` to work... no luck so far, so I guess unless you can merge this PR yourself and run `make update` for me, the effort is too much. :(

**Comment by exekias** [comment]
Thanks for taking the time @robin13! :100:  I've just opened https://github.com/elastic/beats/pull/5578 so we can close this one

**Comment by ruflin** [comment]
@robin13 Thanks for going through this and trying to get it work. Sorry that this was not successful.
@exekias Thanks for taking over.

**Pull request closed without merging**
