### PR TITLE
Changelog cleanup in master

### PR DESCRIPTION
**Pull request by tsg**
This includes the recent releases and eliminates duplicates.

### CODE REVIEW

**Comment by tsg** [comment]
@exekias FYI, the changelog cleanup i promised for the master branch.

**Comment by ruflin** [comment]
@tsg Seems like this needs a rebase.

**Comment by tsg** [comment]
Solved conflict via the web editor.

**Comment by ruflin** [comment]
I did not check every single line but tried some examples and looks good.

**Pull request merged**
