### PR TITLE
Osquerybeat: Add install verification for osquerybeat

### PR DESCRIPTION
**Pull request by aleksmaus**
## What does this PR do?

Adds ```verify``` command to osquerybeat ```check_install``` spec step. Checks the presence of the essential files that are needed for osquerybeat to function properly. Failed verification indicates to the agent to reinstall osquerybeat.

## Why is it important?

This should allow the agent with osquerybeat to recover in case if osquerybeat install became corrupted.
Addresses the final changes that allows to close https://github.com/elastic/beats/issues/30067#issuecomment-1034085775

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas

## Related issues

- Closes https://github.com/elastic/beats/issues/30067

## Use cases

Delete any of the essential osquerybeat binaries leaving osquerybeat install ```corrupted```. 
The essential files are osquerybeat, osqueryd, osquery-extension.ext (osquery-extension.exe on windows).  
Restart the agent, observe the osquerybeat is reinstalled.

### CODE REVIEW

**Review by ph — APPROVED** [review]
LGTM

**Comment by amolnater-qasource** [comment]
Hi @aleksmaus 
We have revalidated this with Windows 10 host on latest 8.1 Snapshot and found this issue **still** reproducible.

**Build details:**
BUILD: 50363
COMMIT: 05408fe74aee0f7161fe4b1568b71e91fb030874
Artifact link: https://snapshots.elastic.co/8.1.0-732c5a10/downloads/beats/elastic-agent/elastic-agent-8.1.0-SNAPSHOT-windows-x86_64.zip

**Steps followed:**
1. Installed an agent with policy having System and OS Query Manager integrations.
2. From the installed folder at `C:\Program Files\Elastic\Agent\data\elastic-agent-438761\install\osquerybeat-8.1.0-SNAPSHOT-windows-x86_64` we deleted `osquery-extension.exe`.
3. We restarted agent service and observed this deleted binary isn't installed back.

Further we attempted to delete all the necessary binaries however none of them re-installed on agent restart.


**Logs:**
[logs.zip](https://github.com/elastic/beats/files/8087788/logs.zip)

Please let us know if we are missing anything.
Thanks

**Comment by aleksmaus** [comment]
> Hi @aleksmaus We have revalidated this with Windows 10 host on latest 8.1 Snapshot and found this issue **still** reproducible.
> 
> **Build details:** BUILD: 50363 COMMIT: 05408fe74aee0f7161fe4b1568b71e91fb030874 Artifact link: https://snapshots.elastic.co/8.1.0-732c5a10/downloads/beats/elastic-agent/elastic-agent-8.1.0-SNAPSHOT-windows-x86_64.zip
> 
> **Steps followed:**
> 
> 1. Installed an agent with policy having System and OS Query Manager integrations.
> 2. From the installed folder at `C:\Program Files\Elastic\Agent\data\elastic-agent-438761\install\osquerybeat-8.1.0-SNAPSHOT-windows-x86_64` we deleted `osquery-extension.exe`.
> 3. We restarted agent service and observed this deleted binary isn't installed back.
> 
> Further we attempted to delete all the necessary binaries however none of them re-installed on agent restart. 
> 
> **Logs:** [logs.zip](https://github.com/elastic/beats/files/8087788/logs.zip)
> 
> Please let us know if we are missing anything. Thanks

The backport to 8.1 branch is still open and was not merged yet.

**Comment by amolnater-qasource** [comment]
Hi @aleksmaus 
We have revalidated this on 8.0.1 BC-1 build and found it working **fine**.
- Installed agent with OSquerybeat.
- Deleted `osquery-extension.exe`
- Restarted agent service and observed OSquerybeat is reinstalled.

**Build details:**
BUILD: 49342
COMMIT: f4b44d7eb7355c9d1e38d9f2dc753b3fe10c601c
Artifact Link: https://staging.elastic.co/8.0.1-91daef6b/downloads/beats/elastic-agent/elastic-agent-8.0.1-windows-x86_64.zip

We will revalidate this on 8.1, once these merges are available.
Please let us know if anything else is required from our end.
Thanks

**Pull request merged**
