### PR TITLE
Fixes example fleet-agent k8s guide

### PR DESCRIPTION
**Pull request by jasonrhodes**
## What does this PR do?

As far as I can tell, docker.elastic.co/beats/elastic-agent doesn't exist (anymore?) and 8.2.0 isn't available on DockerHub. I switched the image reference to the DockerHub path and used 8.0.0 for now, with a comment about adjusting that to the version tag that's right for the user.

## Why is it important?

The main public guide for monitoring k8s with Elastic Agent points to this file: https://www.elastic.co/guide/en/fleet/master/running-on-kubernetes-managed-by-fleet.html, so that experience is broken for users until they figure out that our own image reference is broken.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by ph — APPROVED** [review]
LGTM, I think there are other files that need to be adjusted. Let's merge your changes and we  need to take that on our side. 

Thanks @jasonrhodes for noticing it.

Reference https://github.com/elastic/beats/issues/30542

**Comment by jasonrhodes** [comment]
@ph I see what's happening now -- these guides are generated per version, so there is a https://www.elastic.co/guide/en/fleet/8.0/running-on-kubernetes-managed-by-fleet.html version of the docs as well.

Unfortunately, if I google for "kubernetes with elastic agent" this is one of the first hits, and it's for the "master" version which points at 8.2 (and a non-existent repo). I wonder how we should fix this kind of thing. @ollyhowell do you have thoughts here?

**Comment by ph** [comment]
Yeah, I think the doc can link to a specific tag in the repository that should solve the problem, @dedemorton might know too.

**Comment by ollyhowell** [comment]
Thanks for the conditional content tip @dedemorton!

Just to check I understand:
- https://www.elastic.co/guide/en/fleet/master/running-on-kubernetes-managed-by-fleet.html points _Docker images_ to https://www.docker.elastic.co/r/beats/elastic-agent (note the "/r/")
- https://www.docker.elastic.co/r/beats/elastic-agent lists 8.0 but not 8.1 or 8.2
- but the yaml file needs an explicit link to a tagged version? i.e.           
> image: docker.elastic.co/beats/elastic-agent:8.2.0
> image: elastic/elastic-agent:8.0.0 # choose the version tag that's right for you
- not familiar with the deployment bit, where does the yaml output show up? i.e. what is broken for users right now?

There is a general issue that we're still using /master in user-facing docs where we've renamed to main internally but I think it's quite tangled with search and our various urls.

**Comment by ph** [comment]
@ollyhowel The page  https://www.elastic.co/guide/en/fleet/master/running-on-kubernetes-managed-by-fleet.html 
Point to a manifest file in our repository on our main (master) branch (curl -L -O https://raw.githubusercontent.com/elastic/beats/master/deploy/kubernetes/elastic-agent-managed-kubernetes.yaml)

These files reference docker images which are not released (8.2.0), the master always refers to 8.2.0).

This means, if a user tries the manifest file from the main it will not work because the docker images aren't released. 

I don't think we should fix it in the beats repository but in the doc repository using dede tips.

@ollyhowell I will close this PR, should we create an issue on the document repository, or you ware taking care of it?

**Pull request closed without merging**
