### PR TITLE
[All Beats]move from extensions/v1beta1 to apps/v1

### LINKED ISSUE #13850: [AllBeats]Kubernetes: Move away from extensions/v1beta1
**Describe the enhancement:**
`extensions/v1beta1` have been deprecated as a group for DaemonSets and ReplicaSets among other objects.

Some of our deployments use that ApiGroup, which will make it fail at kubernetes 1.16
Moving to `apps/v1` will make deployments fail at kubernetes 1.8 and below.

As per statistics at the ECK project, there are no users for them using 1.8, but we can expect people using latest minikube images targeting 1.16.

This issue affects mainly documentation, but there is also an import from the kubernetes API project using `extensions/v1beta1`. While it seems that it should still work, new releases of the library will probably remove the package.

### PR DESCRIPTION
**Pull request by odacremolbap**
Move API Groups for DaemonSets from `extensions/v1beta1` to `apps/v1`

Current examples are not deployable at kubernetes 1.16
Reference: https://kubernetes.io/blog/2019/07/18/api-deprecations-in-1-16/

Fixes elastic/beats#13850

### CODE REVIEW

**Comment by exekias** [comment]
Change LGTM, thank you for taking this! let's tackle testing to update supported versions :+1:

**Comment by odacremolbap** [comment]
jenkins, test this

**Comment by odacremolbap** [comment]
jenkins, test this

**Comment by odacremolbap** [comment]
**message for manual testing**: while the deployment manifests are tested by travis, examples inside documents are not. Boot up a kubernetes v1.15 or v1.16 cluster and try the examples.

**Comment by odacremolbap** [comment]
jenkins, test this

**Comment by odacremolbap** [comment]
jenkins, test this

I would say that jenkins issues are not related to this issue (but can't tell 100%), happy to see a review comming

**Comment by MorrieAtElastic** [comment]
Customer reports he encounters the problem in discussed in https://discuss.elastic.co/t/metricbeats-on-gke-not-working-as-expected-missing-deployments-nodes-etc/204948/2 in metricbeat 7.4.1 as well. 

I'd appreciate clarification: does this problem apply to a limited scope of metricbeat and filebeat functionality? Customer is claiming that he cannot use 7.4.X of metricbeat in K8 at all.

**Comment by odacremolbap** [comment]
@MorrieAtElastic
I think you mean https://github.com/elastic/beats/pull/13905
I can see that one at 7.5.0, I guess it haven't made it to 7.4.x

There was a code issue that tried to use a ReplicaSet when receiving a StatefulSet object. I haven't tracked all usages of the function that contains the error, the original authors will know a lot more than me, but I think the cases for hitting the error are using StatefulSets and configuring:

- kubernetes autodiscover provider
- kubernetes_add_metadata
- kubernetes state metrics for most objects (it uses an enricher that setups the watcher that uses the function containing the issue)

**Pull request merged**
