### PR TITLE
Change proxy_url from url.URL to string

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
## What does this PR do?
When trying to use Filebeat aws-s3 input with the proxy_url config parameter, Filebeat will fail to start with error:
```
2021-10-29T03:14:40.088Z ERROR instance/beat.go:989 Exiting: Failed to start crawler: starting input failed: Error while initializing input: (assert) value of type 'string' not convertible into unsupported go type 'url.URL' accessing 'filebeat.inputs.2.proxy_url' (source:'/etc/filebeat/filebeat.yml')
```

Instead of `url.URL`, this PR changes the `proxy_url` input to string type instead.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

Test Filebeat with the config below and there shouldn't be an error with not able to parse the URL:
```
filebeat.inputs:
- type: aws-s3
  enabled: true
  queue_url:  https://sqs.us-east-1.amazonaws.com/12345/test-vpcflow
  credential_profile_name: elastic-beats
  proxy_url: http://proxy:1234
```

## Related issues

- Closes  https://github.com/elastic/beats/issues/28724

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
Hey @legoguy1000, before I continue on this change, could you correct me if I'm specifying the `proxy_url` config in the wrong format please? I also tried with `proxy_url: 'http://proxy:1234'` and `"proxy_url: http://proxy:1234"`. Thank you!!

**Comment by legoguy1000** [comment]
> Hey @legoguy1000, before I continue on this change, could you correct me if I'm specifying the `proxy_url` config in the wrong format please? I also tried with `proxy_url: 'http://proxy:1234'` and `"proxy_url: http://proxy:1234"`. Thank you!!

That looks correct. When I first made the Proxy config for the `httpjson` input I made the input a string but was told to make it a `url.URL`.  Looking at the remake of the `httpcomon` module, its still a `url.URL` but maybe there was something I missed. https://github.com/elastic/beats/blob/master/libbeat/common/transport/httpcommon/proxy.go#L39

**Comment by kaiyan-sheng** [comment]
@legoguy1000 Sorry for the late response. Have you used `proxy_url` successfully before? Let me check to see if it's a formatting issue. Thank you!!

**Review by aspacca — APPROVED** [review]

**Comment by aspacca** [comment]
> its still a `url.URL`

it is indeed the aliased type `ProxyURI` that implements `Unpack` :)

**Pull request merged**
