### PR TITLE
Bump go version to 1.21.0, bump lookslike version

### PR DESCRIPTION
**Pull request by andrewvc**
## Proposed commit message

Bumps the go version to 1.21.0 and bumps the version of go-lookslike (test library) to 1.0.0 both of which combine to fix segfaults on failed tests. Go-lookslike requires go 1.21+ as of https://github.com/elastic/go-lookslike/pull/21 . Previously the only way to avoid segfaults (and see the failed test output) on go 1.20.x was to run the tests under the debugger, which weirdly did not trigger segfaults.

I initially tried to bump to 1.21.1 but https://github.com/elastic/golang-crossbuild doesn't seem to support that yet.

## Checklist

- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by cmacknz** [comment]
We will want to Go to 1.21.1, we usually avoid the .0 release to avoid the initial wave of bugs. We also won't want to release a version with known CVEs in it if we can avoid it.

I kicked the golang-crossbuild Github action that polls for new releases and creates the necessary PR to create the build container: https://github.com/elastic/golang-crossbuild/pull/314

This is done by manually triggering the `bump-golang-main` GH action: https://github.com/elastic/golang-crossbuild/actions/workflows/bump-golang.yml

**Comment by cmacknz** [comment]
You should be able to upgrade to Go 1.20.1 now. I am going to bump main to 1.20.8 first so I can backport that to 8.10 so 8.10.1 has the CVE fixes. No opposition to moving main to 1.20.1.

**Comment by pierrehilbert** [comment]
@andrewvc do you have time to take care of this PR?

**Comment by cmacknz** [comment]
Closing this, let's reopen once ready for review again.

**Pull request closed without merging**
