### PR TITLE
[7.x] Ensure index pattern version is a string (#10689)

### PR DESCRIPTION
**Pull request by simitt**
Backports the following commits to 7.x:
 - Ensure index pattern version is a string  (#10689)

### CODE REVIEW

**Comment by ruflin** [comment]
We will do bulk backports, no need for the 7.x PR.

**Comment by simitt** [comment]
@ruflin should I add the `needs_backports` label then again to the original PR?

**Comment by simitt** [comment]
APM CI will fail on 7.x until this is backported and merged. Any chance of doing a bulk backport _soon_?

**Comment by ruflin** [comment]
No backport label need. Let me see if I can open a bulk backport.

**Comment by graphaelli** [comment]
I don't think that bulk backport happened and there have been a number of other backports for 7.x in the meantime.  Reopening for consideration.

**Comment by graphaelli** [comment]
jenkins, retest this please

The test failures don't seem to be directly related to this change.

**Comment by graphaelli** [comment]
jenkins, retest this please

different unrelated failures this time

**Comment by simitt** [comment]
I just updated to the latest 7.x changes again. Pinging @ruflin and @elastic/beats on this one - I'd appreciate if we could get this merged, as our CI is failing on the 7.x branch because of this.

**Pull request merged**
