### PR TITLE
add missing return statement

### LINKED ISSUE #4041: filebeat 5.3 regression - console output returning crit errors then stops logging to output
There seems to be some regression with the latest version of filebeat in regards to console output.

**Example**:
```
# t.sh
for i in $(seq 1 20); do echo $i; sleep 1; done

# filebeat.yaml
filebeat:
  shutdown_timeout: 0s
  prospectors:
    - input_type: stdin
      encoding: utf-8

output.console:
  codec.format:
    string: '%{[message]}'

logging.level: critical
logging.to_files: false
logging.to_syslog: false
```

**filebeat version 5.3.0 (amd64), libbeat 5.3.0**
*Notice how it stops at 6 and logs a CRIT to stderr*
```
$ sh t.sh | ./filebeat -c filebeast.yaml -e
1
2017/04/18 19:11:46.026826 console.go:83: CRIT Unable to publish events to console: <nil>
2
2017/04/18 19:11:46.026872 console.go:83: CRIT Unable to publish events to console: <nil>
3
2017/04/18 19:11:46.026881 console.go:83: CRIT Unable to publish events to console: <nil>
4
2017/04/18 19:11:46.026893 console.go:83: CRIT Unable to publish events to console: <nil>
5
2017/04/18 19:11:46.026901 console.go:83: CRIT Unable to publish events to console: <nil>
6
2017/04/18 19:11:46.026909 console.go:83: CRIT Unable to publish events to console: <nil>
```

**filebeat version 5.2.1 (amd64), libbeat 5.2.1**
*The formating is different because `codec.format` is not available on this version*
```
sh t.sh | filebeat -c /tmp/filebeast-stdin2.yaml -e
{"@timestamp":"2017-04-18T19:12:35.603Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"1","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:36.600Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"2","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:37.601Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"3","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:38.601Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"4","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:39.602Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"5","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:40.602Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"6","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:41.603Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"7","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:42.603Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"8","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:43.603Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"9","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:44.604Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"10","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:45.604Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"11","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:46.605Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"12","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:47.605Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"13","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:48.605Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"14","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:49.606Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"15","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:50.606Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"16","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:51.607Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"17","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:52.607Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"18","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:53.608Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"19","offset":0,"source":"","type":"log"}
{"@timestamp":"2017-04-18T19:12:54.608Z","beat":{"hostname":"ee86c6ebade2","name":"ee86c6ebade2","version":"5.2.1"},"input_type":"stdin","message":"20","offset":0,"source":"","type":"log"}
```

### PR DESCRIPTION
**Pull request by glefloch**
Add missing return statement

Close #4041

### CODE REVIEW

**Comment by karmi** [comment]
Hi @glefloch, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/beats/pull/4045.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by glefloch** [comment]
Yes I'm gonna do that

**Comment by monicasarbu** [comment]
@glefloch Thanks for the PR. Waiting for the CLA check to be green.

**Comment by glefloch** [comment]
I already signed it... It was green before my last commit. Is that normal that it's not?

**Comment by ruflin** [comment]
I think there is currently an issue with the CLA checker on all PRs ...

**Pull request merged**
