### PR TITLE
add mariadb module for filebeat

### PR DESCRIPTION
**Pull request by rdglinux**
**Added filebeat module to mariadb logs.**

Module created based on discuss: https://discuss.elastic.co/t/filebeat-mysql-module-slowlog-error-message-provided-grok-expressions-do-not-match-field-value/135945/3

Logging pattern to be parsed:

```
# Time: 180613 11:04:36
# User@Host: root[root] @ localhost [ ]
# Thread_id: 5  Schema:   QC_hit: No
# Query_time: 2.000652  Lock_time: 0.000000  Rows_sent: 1  Rows_examined: 0
SET timestamp=1528898676;
select sleep(2);
```

**To do:**

Adjust and create dashboard file do Kibana

### CODE REVIEW

**Comment by karmi** [comment]
Hi @rdglinux, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/beats/pull/7422.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by jsoriano** [comment]
@rdglinux thanks for this! You will need to run `make update` inside filebeat and commit the changes.

**Comment by ruflin** [comment]
Could you also add a small test log file to verify the changes (see other filesets). PR will also need a changelog entry.

**Comment by rdglinux** [comment]
@karmi thanks for your reply...i updated my other e-mail in my github.

**Comment by karmi** [comment]
@rdglinux , great!, the CLA check is green now.

**Comment by ruflin** [comment]
@rdglinux Something seems to be still off with the generated files. Could you rebase on master and run again `make update` ?

**Comment by ceesvanegmond** [comment]
Cool new feature! Will it get merged?

**Comment by ceesvanegmond** [comment]
Fix works on my machine!

**Comment by jsoriano** [comment]
@rdglinux are you planning to continue with this PR? if you cannot do it we could try to finish and merge it. It'd be great in any case if you could add some example log file for testing. Thanks!

**Comment by rdglinux** [comment]
Hi @jsoriano!

Sorry for my late reply, i was involved in other projects.

I used this module for my database MariaDB and works good. So i belive we could merge it.

Fallow my log!.

image

**Comment by NoSkillGuy** [comment]
Hi @rdglinux 

My MariaDB slow log format is slightly different. 

```
# Time: 181004 10:53:53
# User@Host: user_name[host_name] @  [ip]
# Thread_id: 25844  Schema: blah  QC_hit: No
# Query_time: 178.306017  Lock_time: 0.000000  Rows_sent: 0  Rows_examined: 53022772
# Rows_affected: 3062
# Full_scan: Yes  Full_join: No  Tmp_table: Yes  Tmp_table_on_disk: No
# Filesort: Yes  Filesort_on_disk: No  Merge_passes: 0  Priority_queue: No
SET timestamp=1538650433;
call PROC('blah');
```

Version Details:
`mysql  Ver 15.1 Distrib 10.2.12-MariaDB, for debian-linux-gnu (x86_64) using readline 5.2`

**Comment by NoSkillGuy** [comment]
Hi @rdglinux, For my above format i had written a new grok pattern: but couple of things i took loosely
1. Hardcoded spaces 
2. Did for the exact log, didn't write any optional patterns. 

`^# Time: %{NUMBER:microseconds} %{NUMBER:hours}:%{NUMBER:minutes}:%{NUMBER:seconds}..\# User@Host: %{USER:user}\[%{USER:current_user}\] @  \[%{IP:ip}\]..\# Thread_id: %{NUMBER:thread_id}  Schema: %{WORD:schema}  QC_hit: %{WORD:qc_hit}..\# Query_time: %{NUMBER:qc_time}  Lock_time: %{NUMBER:lock_time}  Rows_sent: %{NUMBER:rows_sent}  Rows_examined: %{NUMBER:rows_examined}..\# Rows_affected: %{NUMBER:rows_affected}..\# Full_scan: %{WORD:full_scan}  Full_join: %{WORD:full_join}  Tmp_table: %{WORD:tmp_table}  Tmp_table_on_disk: %{WORD:tmp_table_on_disk}..\# Filesort: %{WORD:filesort}  Filesort_on_disk: %{WORD:filesort_on_disk}  Merge_passes: %{NUMBER:merge_passes}  Priority_queue: %{WORD:priority_queue}..SET timestamp=%{NUMBER:timestamp};..%{GREEDYDATA:query}`

**Comment by jsoriano** [comment]
@rdglinux sorry also for my late reply :slightly_frowning_face:

This is looking good to me, could you try to add some example test files? It'd be good if this works also with @NoSkillGuy's example.

**Comment by pr0sto** [comment]
Hi @rdglinux and @jsoriano 
When can we expect new functionality in production?

**Comment by jsoriano** [comment]
MariaDB support added at the end in the mysql module itself (https://github.com/elastic/beats/pull/9731), thanks for the work and example cases here!
I will try to backport this for 6.7.0.

**Pull request closed without merging**
