### PR TITLE
Add icingabeat to the list

### PR DESCRIPTION
**Pull request by bobapple**
Icingabeat collects data from the Icinga 2 API

### CODE REVIEW

**Comment by ruflin** [comment]
@bobapple Great to see one more beat. Could you sign the CLA: https://www.elastic.co/contributor-agreement?

One question about icingabeat as I'm not aware of the details of the icinga API: Does it fetch monitoring data from icinga (monitoring the montioring system) or also data that has been fetched by icinga?

**Comment by bobapple** [comment]
About the CLA: I have to clarify if we will sign it as a company or as individuals. I hope it won't take to long to figure this out.

The Icinga API is part of Icinga 2. It is used for configuration changes and to publish various information. Icinga runs plugins to figure out the state of hosts or services and decides whether to notifiy someone, take an action or do nothing. Everything that happens "inside" Icinga is handled as an event. For example the return value of a plugin, is a checkresult. When a user is notified, its a notification. When a user sets a downtime via the webinterface, this is also an event. Icingabeat can fetch all these data. Additionally, it can poll data about the Icinga 2 daemon itself. These are metrics about how the system is doing. How many checks it's running, how long the execution time of these is etc.

Hope this helps!

**Comment by ruflin** [comment]
@bobapple Thanks a lot for the details. Reminds me slightly of https://github.com/PhaedrusTheGreek/nagioscheckbeat but more powerful. As far as I remember icinga was a fork of nagios? 

About CLA: Just leave a comment as soon as it is signed and it should rerun the check or ping me so I can trigger it. For company CLA's it sometimes does not recognise it automatically ...

**Comment by bobapple** [comment]
@ruflin you're very welcome. The first version of Icinga indeed was a fork of nagios. However, we decided to start from scratch. The current Icinga 2 differs in configuration (object oriented, rule-based) and feature set (API, graphite, logstash etc.)

I'll leave you a note as soon as I've signed the CLA

**Comment by ruflin** [comment]
@bobapple I was thinking of the statuspoller part of icingabeat could also make sense as a metricbeat module? I quickly tried to run incinga locally via docker and access `/v1/status` to see the info but was not successful.

**Comment by bobapple** [comment]
@ruflin Icingabeat is the first part in my plan for Elastic integration in Icinga. I am planing also a logstash output and a filebeat module. A metricbeat module would probably make sense as well.

Here's a sample output of `/v1/status`

```json
{
  "results": [
    {
      "name": "ApiListener",
      "perfdata": [
        "'api_num_conn_endpoints'=0",
        "'api_num_endpoints'=0",
        "'api_num_not_conn_endpoints'=0"
      ],
      "status": {
        "api": {
          "conn_endpoints": [],
          "identity": "demo",
          "not_conn_endpoints": [],
          "num_conn_endpoints": 0,
          "num_endpoints": 0,
          "num_not_conn_endpoints": 0,
          "zones": {
            "demo": {
              "client_log_lag": 0,
              "connected": true,
              "endpoints": [
                "demo"
              ],
              "parent_zone": ""
            }
          }
        }
      }
    },
    {
      "name": "CIB",
      "perfdata": [],
      "status": {
        "active_host_checks": 0.26666666666666666297,
        "active_host_checks_15min": 223,
        "active_host_checks_1min": 16,
        "active_host_checks_5min": 74,
        "active_service_checks": 2.3666666666666666963,
        "active_service_checks_15min": 2075,
        "active_service_checks_1min": 142,
        "active_service_checks_5min": 694,
        "avg_execution_time": 1.2398966125079564637,
        "avg_latency": 0.00049015453883579794461,
        "max_execution_time": 10.002501964569091797,
        "max_latency": 0.001644134521484375,
        "min_execution_time": 0,
        "min_latency": 0,
        "num_hosts_acknowledged": 0,
        "num_hosts_down": 0,
        "num_hosts_flapping": 0,
        "num_hosts_in_downtime": 0,
        "num_hosts_pending": 0,
        "num_hosts_unreachable": 0,
        "num_hosts_up": 5,
        "num_services_acknowledged": 1,
        "num_services_critical": 7,
        "num_services_flapping": 0,
        "num_services_in_downtime": 1,
        "num_services_ok": 21,
        "num_services_pending": 0,
        "num_services_unknown": 0,
        "num_services_unreachable": 0,
        "num_services_warning": 0,
        "passive_host_checks": 0,
        "passive_host_checks_15min": 0,
        "passive_host_checks_1min": 0,
        "passive_host_checks_5min": 0,
        "passive_service_checks": 0.050000000000000002776,
        "passive_service_checks_15min": 3,
        "passive_service_checks_1min": 3,
        "passive_service_checks_5min": 3,
        "uptime": 126353.72569417953491
      }
    },
    {
      "name": "CheckResultReader",
      "perfdata": [],
      "status": {
        "checkresultreader": {}
      }
    },
    {
      "name": "CheckerComponent",
      "perfdata": [
        {
          "counter": false,
          "crit": null,
          "label": "checkercomponent_checker_idle",
          "max": null,
          "min": null,
          "type": "PerfdataValue",
          "unit": "",
          "value": 33,
          "warn": null
        },
        {
          "counter": false,
          "crit": null,
          "label": "checkercomponent_checker_pending",
          "max": null,
          "min": null,
          "type": "PerfdataValue",
          "unit": "",
          "value": 0,
          "warn": null
        }
      ],
      "status": {
        "checkercomponent": {
          "checker": {
            "idle": 33,
            "pending": 0
          }
        }
      }
    },
    {
      "name": "CompatLogger",
      "perfdata": [],
      "status": {
        "compatlogger": {}
      }
    },
    {
      "name": "ExternalCommandListener",
      "perfdata": [],
      "status": {
        "externalcommandlistener": {
          "command": 1
        }
      }
    },
    {
      "name": "FileLogger",
      "perfdata": [],
      "status": {
        "filelogger": {
          "main-log": 1
        }
      }
    },
    {
      "name": "GraphiteWriter",
      "perfdata": [],
      "status": {
        "graphitewriter": {
          "graphite": 1
        }
      }
    },
    {
      "name": "IcingaApplication",
      "perfdata": [],
      "status": {
        "icingaapplication": {
          "app": {
            "enable_event_handlers": true,
            "enable_flapping": true,
            "enable_host_checks": true,
            "enable_notifications": true,
            "enable_perfdata": true,
            "enable_service_checks": true,
            "node_name": "demo",
            "pid": 11753,
            "program_start": 1489759338.9575219154,
            "version": "r2.6.2-1"
          }
        }
      }
    },
    {
      "name": "IdoMysqlConnection",
      "perfdata": [
        {
          "counter": false,
          "crit": null,
          "label": "idomysqlconnection_ido-mysql_queries_rate",
          "max": null,
          "min": null,
          "type": "PerfdataValue",
          "unit": "",
          "value": 5.5999999999999996447,
          "warn": null
        },
        {
          "counter": false,
          "crit": null,
          "label": "idomysqlconnection_ido-mysql_queries_1min",
          "max": null,
          "min": null,
          "type": "PerfdataValue",
          "unit": "",
          "value": 336,
          "warn": null
        },
        {
          "counter": false,
          "crit": null,
          "label": "idomysqlconnection_ido-mysql_queries_5mins",
          "max": null,
          "min": null,
          "type": "PerfdataValue",
          "unit": "",
          "value": 1623,
          "warn": null
        },
        {
          "counter": false,
          "crit": null,
          "label": "idomysqlconnection_ido-mysql_queries_15mins",
          "max": null,
          "min": null,
          "type": "PerfdataValue",
          "unit": "",
          "value": 4850,
          "warn": null
        },
        {
          "counter": false,
          "crit": null,
          "label": "idomysqlconnection_ido-mysql_query_queue_items",
          "max": null,
          "min": null,
          "type": "PerfdataValue",
          "unit": "",
          "value": 0,
          "warn": null
        }
      ],
      "status": {
        "idomysqlconnection": {
          "ido-mysql": {
            "connected": true,
            "instance_name": "default",
            "query_queue_items": 0,
            "version": "1.14.2"
          }
        }
      }
    },
    {
      "name": "InfluxdbWriter",
      "perfdata": [],
      "status": {
        "influxdbwriter": {}
      }
    },
    {
      "name": "NotificationComponent",
      "perfdata": [],
      "status": {
        "notificationcomponent": {
          "notification": 1
        }
      }
    },
    {
      "name": "OpenTsdbWriter",
      "perfdata": [],
      "status": {
        "opentsdbwriter": {}
      }
    },
    {
      "name": "PerfdataWriter",
      "perfdata": [],
      "status": {
        "perfdatawriter": {}
      }
    },
    {
      "name": "StatusDataWriter",
      "perfdata": [],
      "status": {
        "statusdatawriter": {}
      }
    },
    {
      "name": "SyslogLogger",
      "perfdata": [],
      "status": {
        "sysloglogger": {}
      }
    }
  ]
}
```

**Comment by dnsmichi** [comment]
@ruflin You could also use the preconfigured Vagrant boxes for a quick peek :) Either Virtualbox or Parallels as provider are supported.

```
git clone https://github.com/Icinga/icinga-vagrant.git
cd icinga-vagrant/icinga2x
vagrant up

curl -k -s -u root:icinga 'https://192.168.33.5:5665/v1/status' | python -m json.tool
```

There's also the `icinga2x-elastic` box but that's currently work in progress. The icingabeat integration is missing, but I'm working on it in icinga/icinga-vagrant#30 :)

**Comment by bobapple** [comment]
@ruflin I've signed the CLA

**Comment by ruflin** [comment]
@bobapple Great, I just merged it.

Thanks for the json. It's quite an interesting format. It seems the results array contains stats from all the different components. For the "major" components we could build a metricset that knows the data structure in advance. It seems `CIB`, `ApiListener`, `IcingaApplication` seem to fall into this category. And we could have one more dynamic metricset that fetches everything inside results and a filter could be applied (white / blacklist) based on the `name` field on what to include. But there we would not know the structure in advance. Just a thought.

Looking forward to all the future contributions :-)

@dnsmichi Thanks for the details on the vagrant box.

**Pull request merged**
