### PR TITLE
Fixing broken documentation links for filebeat and metricbeat

### PR DESCRIPTION
**Pull request by jeniawhite**
## What does this PR do?
This PR fixes `filebeat` and `metricbeat` broken links that were directed to the wrong branch (`main` instead of `master`).
This resulted in invalid `404` pages when attempting to access the document resources.

## Why is it important?
In order to see the documentation and not browse to broken links.

## Checklist
- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist
- [ ]

## How to test this PR locally
Browse the documentation links and verify that they are directed to the relevant pages.

## Related issues
- 

## Use cases
As a developer/user, I would like to get up-to-date valid documentation links.

### CODE REVIEW

**Comment by jeniawhite** [comment]
Found out that this is being autogenerated by the `mage` scripts.
The problem is that the `:doc-branch: main` is set to `main`, yet the website for the docs is using `master`.
This `main` is good whenever we are generating `GitHub` links, but not when we direct to `Elastic documentation`.

**Review by cmacknz — APPROVED** [review]
Thanks

**Review by bmorelli25 — APPROVED** [review]
LGTM

**Pull request merged**
