### PR TITLE
[GCP] Move modules to GA

### PR DESCRIPTION
**Pull request by endorama**
## What does this PR do?

Mark most of GCP module metricset and GCP module itself `ga`. The only one still beta is `gcp.carbon`, which has been recently added.

- mark gcp.billing as GA
- mark gcp.compute as GA
- mark gcp.dataproc as GA
- mark gcp.gke as GA
- mark gcp.firestore as GA
- mark gcp.loadbalancing as GA
- mark gcp.pubsub as GA
- mark gcp.storage as GA
- mark gcp.metrics as GA
- mark gcp module as GA

## Why is it important?

There is a discrepancy between Metricbeat metricsets and Agent integration: metricset where not marked as `ga`.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by endorama** [comment]
Some linter failures have been fixed in a separate PR due to their scope. See https://github.com/elastic/beats/pull/35060

Merging blocked until the other PR is merged.

**Review by tommyers-elastic — APPROVED** [review]
LGTM - thanks edo. 

small nit: it would be better to keep functional changes around error handling separate from this PR. and wrt those changes, is there are a reason for making the change to use errors.Is? i.e. is it fixing a bug where we're missing a wrapped error? if so it would be good to include a unit test.

**Comment by endorama** [comment]
@tommyers-elastic I touched go code, so the linter kicked in on the whole file. Those changes are to make it happy (+1 error handling additional that was missing and discovered while fixing the related linter error) and have a green CI. I can move them to a separate PR if you prefer.

**Comment by endorama** [comment]
Also adding backport to 8.7 as we want this to land in next patch release.

**Comment by tommyers-elastic** [comment]
no all good - thanks for the explanation edo 👍

**Pull request merged**
