### PR TITLE
Rewrite fields.yml collection unit test

### LINKED ISSUE #7721: [libbeat] - global_field tests failing
The tests in `libbeat/scripts/cmd/global_fields/main_test.go` are failing. In its current state it's not really maintainable because each new module needs to be added to this test. I suggest putting some files into a `testdata` directory and execute tests against them.

https://github.com/elastic/beats/blob/35a7882f69d6daf9ab72f36c6509a00aaa2904d0/libbeat/scripts/cmd/global_fields/main_test.go#L778

```
assertions.go:247: 
Error Trace:	main_test.go:807
	
Error:      	Should be true
	
Test:       	TestCollectModuleFiles
assertions.go:247: 
Error Trace:	main_test.go:807
	
Error:      	Should be true
	
Test:       	TestCollectModuleFiles
```

https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-windows/5707/beat=libbeat,label=windows/testReport/junit/(root)/global_fields/TestCollectModuleFiles/

### PR DESCRIPTION
**Pull request by kvch**
Previously, real modules data with fields.yml were tested. But as the number of modules are increasing rapidly, it's not possible to keep up with it. Before introducing mage, this test hasn't run on the CI, so nothing broke.

I added test folders and fields.yml files, to see if the required files can be collected.

@andrewkroh Do I need to add something to our magefiles, so these test folders are not added to the package?

Closes #7721

### CODE REVIEW

**Comment by ruflin** [comment]
It seems the test still breaks on Windows CI?

**Comment by kvch** [comment]
I forgot to add two test files. Now it should be fixed.

**Comment by kvch** [comment]
jenkins test this

**Comment by kvch** [comment]
jenkins test this

**Pull request merged**
