### PR TITLE
Winlogbeat/Windows Services: changed default keystore path to program files

### PR DESCRIPTION
**Pull request by gustavofbreunig**
## Proposed commit message

If the user install winlogbeat accordingly the [official documentation](https://www.elastic.co/guide/en/beats/winlogbeat/current/winlogbeat-installation-configuration.html#installation) (executing install-service-winlogbeat.ps1), winlogbeat service will search for the keystore file into ProgramData (C:\ProgramData\winlogbeat), but, to create a keystore, it is expected to execute `winlogbeat.exe keystore add` inside Program Files, so, winlogbeat put the keystore into `.\data` `(C:\Program Files\data)`

Setting keystore path to `$workdir` `(c:\program files)` for any beats running as Windows Services solves this problem and don't affect users who do not use a keystore.

Version:
winlogbeat version 8.11.1 (amd64), libbeat 8.11.1

O.S: Windows

Related to issue https://github.com/elastic/beats/issues/12315, which is stalled for many years.

## Checklist

- [ ] ~~My code follows the style guidelines of this project~~
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [X] I have made corresponding changes to the documentation
- [X] I have made corresponding change to the default configuration files
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [X] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

`mage package`

## Related issues

https://github.com/elastic/beats/issues/12315

### CODE REVIEW

**Comment by gustavofbreunig** [comment]
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement): [f99bef7](https://github.com/elastic/beats/commit/f99bef780a674cb154b1f51c5b9e68043bb203b9), [1ce200e](https://github.com/elastic/beats/commit/1ce200ee00aaca26abe04ef31b618484760bce5c), [eff72e8](https://github.com/elastic/beats/commit/eff72e8cf186cf41acd4a8938dd2a328d08e4ae0),
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

Already signed the contributor agreement, not sure what I've done wrong

**Comment by leehinman** [comment]
> Already signed the contributor agreement, not sure what I've done wrong

did the email address you signed with match the email address in GitHub?  That is the most common problem.

**Review by leehinman — APPROVED** [review]

**Comment by gustavofbreunig** [comment]
> > Already signed the contributor agreement, not sure what I've done wrong
> 
> did the email address you signed with match the email address in GitHub? That is the most common problem.

Thanks, all done.

**Comment by pierrehilbert** [comment]
@leehinman is it ready to be merged? (from what I can observe yes but prefer to double check).

**Pull request merged**
