### PR TITLE
added reference to springboot2beat in community beats doc

### PR DESCRIPTION
**Pull request by philkra**

### CODE REVIEW

**Comment by philkra** [comment]
I signed the CLA

**Comment by kvch** [comment]
Are you sure you did? The CLA checker says it's not signed. Have you received an email after signing?

**Comment by philkra** [comment]
Yes, I signed the CLA on the 14th Aug 2018 and after this PR I signed it again. I can forward you the signed the agree via mail if you want to.

**Comment by kvch** [comment]
Yes, it's possible.

**Pull request merged**
