### PR TITLE
[docs] Update build script and descriptions

### PR DESCRIPTION
**Pull request by bmorelli25**
Moves `make docs` and `make docs-preview` to the new docker build script. Updates the description as well.

### CODE REVIEW

**Comment by bmorelli25** [comment]
The only confusing thing about the docker build is it's not really helpful in showing where the built docs end up. We could log something like `echo "Destination directory: $dest_dir"` at the end of the `build_docs.sh` file to fix this?

**Comment by bmorelli25** [comment]
@Titch990 Since APM was built on the beats framework, a lot of the code and documentation comes from the Beats repo. Certain cahnges in the APM repo have to be persisted in the Beats repo. That's why you're seeing some of the same changes in this PR as you are in https://github.com/elastic/apm-server/pull/2279

**Comment by dedemorton** [comment]
> The only confusing thing about the docker build is it's not really helpful in showing where the built docs end up.

I agree totally. It kind of breaks my usual way of testing the docs for Beats: run make docs to build everything and then follow the links in my terminal to the the build files. I like your idea!

**Comment by bmorelli25** [comment]
Added the extra log! @dedemorton or @Titch990, would you mind testing this out on your machine just to ensure this works?

Marjorie, here's how you would do that.
1) Fetch the commits from this branch (PR)
2) Check out the PR
3) CD into one of the beats subdirectories - Filebeat in this example
4) Run the make docs command

In other words, after you cd into the beats repo, run:
```
git fetch upstream pull/12522/head:update-doc-builds
git checkout update-doc-builds
cd filebeat/
make docs
```

**Pull request merged**
