### PR TITLE
Add filters to AWS EC2 kibana dashboard and pie chart to show instance state

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
Add filters for ec2 overview dashboard: aws region, ec2 machine type and availability zone. Also added a pie chart to show ec2 instance state.
screen shot 2019-02-08 at 6 17 05 pm

### CODE REVIEW

**Comment by ruflin** [comment]
@kaiyan-sheng I added the `needs_backport` label as we might need to backport this to the 7.0 branch depending on when it gets merged.

**Comment by kaiyan-sheng** [comment]
@ruflin 👍 Thank you!

**Comment by jsoriano** [comment]
@kaiyan-sheng you can also add all the selectors in a single box (like in https://user-images.githubusercontent.com/15763/47107903-d81d1e80-d24a-11e8-8c59-782ca1375275.png)

**Comment by kaiyan-sheng** [comment]
> @kaiyan-sheng you can also add all the selectors in a single box (like in https://user-images.githubusercontent.com/15763/47107903-d81d1e80-d24a-11e8-8c59-782ca1375275.png)

Aha good idea! I made the change to combine them in one box :-) Thanks!
screen shot 2019-02-06 at 9 12 18 pm

**Comment by ruflin** [comment]
jenkins, test this

**Comment by kaiyan-sheng** [comment]
The new instance state pie chart showing stopped/terminated states only works with https://github.com/elastic/beats/pull/10627. There are some bugs fixed in there so with that PR, ec2 metricset actually starts reporting events when instance state is not running.

**Pull request merged**
