### PR TITLE
nvidiagpubeat: Monitor NVIDIA GPUs.

### PR DESCRIPTION
**Pull request by deepujain**
Details of beats at : https://github.com/deepujain/nvidiagpubeat/

### CODE REVIEW

**Comment by karmi** [comment]
Hi @deepujain, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/beats/pull/3794.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by deepujain** [comment]
I signed CLA and used same email address. Is it different  ?

**Comment by deepujain** [comment]
Primary email address on my github profile is what i used to sign CLA and later verified it from.

**Comment by deepujain** [comment]
Is there any action pending from my side ?

**Comment by deepujain** [comment]
Ok to test

**Comment by tsg** [comment]
@deepujain I found your gmail address in our records, but you signed the [patch](https://patch-diff.githubusercontent.com/raw/elastic/beats/pull/3794.patch) with your work address. I'm clarifying internally if this is OK, but if you add your work address to your profile (hidden) then the check should become green automatically.

**Comment by tsg** [comment]
Btw, awesome project! Out of curiosity, do you use the GPUs for server side loads or is this for your own personal needs?

**Comment by karmi** [comment]
@deepujain, I second what @tsg has said -- we cannot match your work e-mail (used in your Git configuration) to your Github profile, and the easiest way to make that happen is indeed to add that e-mail to your Github profile (it can be hidden).

**Comment by deepujain** [comment]
@tsg we provide GPUs to data scientist as part of kubernetes cluster. @karmi  i included work-email in git profile and its not marked as primary. Is it ok ?

**Comment by deepujain** [comment]
All green 👍

**Comment by karmi** [comment]
@deepujain yes, thanks!

**Comment by deepujain** [comment]
That was quick. Thank you. When can i expect nvidiagpubeat to be available in Beats Community list ?

**Comment by dedemorton** [comment]
The published list will be updated in master the next time our doc build runs successfully (should be within the next 20-30 minutes unless there are issues). 

You should see the addition in the current docs (5.2) by the end of the day.

**Comment by dedemorton** [comment]
Actually...it's already in master: https://www.elastic.co/guide/en/beats/libbeat/master/community-beats.html

**Pull request merged**
