### PR TITLE
fix update condition bug in reloader

### PR DESCRIPTION
**Pull request by DanielQujun**
as mentioned in[#12155](https://github.com/elastic/beats/issues/12155) ,update condition is invalid

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @DanielQujun, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/beats/pull/12156.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by DanielQujun** [comment]
> Hi @DanielQujun, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/beats/pull/12156.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

email add done.

**Comment by DanielQujun** [comment]
> Since this is a community submitted pull request, a Jenkins build has not been kicked off automatically. Can an Elastic organization member please verify the contents of this patch and then kick off a build manually?

yes

**Comment by DanielQujun** [comment]
heart broken, why the test suit always got timeout error.

**Comment by exekias** [comment]
Closing as it was fixed by https://github.com/elastic/beats/pull/16440

**Pull request closed without merging**
