### PR TITLE
Test: Suppress Edit URLs

### PR DESCRIPTION
**Pull request by dedemorton**
Test to see if we are still able to suppress Edit links in the published docs.

### CODE REVIEW

**Comment by dedemorton** [comment]
@gtback Is this still the preferred approach for suppressing Edit URLs in the published docs? Is it correct to reset the variable at the end? Is there some way to preview the Edit links without merging the change?

This is potentially a short-term change so that users don't inadvertently edit generated files.

We'd really prefer to send contributors to the correct source file, but that would need to be done with fixes to [docgen script](https://github.com/elastic/beats/blob/main/filebeat/scripts/docs_collector.py) (because the file with the includes is itself generated).

**Comment by gtback** [comment]
@dedemorton to be honest, I'm not sure. I haven't had to deal with editing the edit URLs much at all. If you want to disable all the edit links in a book, you can use `private: 1` in  conf.yaml (which indicates it's a private repo, so we don't generate edit links by default). If you want to selectively enable and disable the links for specific sections within a book, I'm not sure the best way to do that. I'd have to dig into the code a bit more.

> Is there some way to preview the Edit links without merging the change?

I think a normal doc build that occurs as part of a PR will do the right thing and let you preview the result. Even if you have to manually make changes to start, and later adapt the generator script to insert the correct attributes.

**Comment by dedemorton** [comment]
Actually...the link override does seem to be working! (I was tired when I opened this PR and thought it didn't work.) This PR is just a backup plan, but I'm going to try to override the actual URLs first.

**Comment by dedemorton** [comment]
Closed in favor of https://github.com/elastic/beats/pull/31327

**Pull request closed without merging**
