### PR TITLE
Close changelog for 6.1.0 release

### PR DESCRIPTION
**Pull request by tsg**

### CODE REVIEW

**Comment by monicasarbu** [comment]
The changelog for windows service metricset is missing: https://github.com/elastic/beats/pull/5332

**Comment by tsg** [comment]
@monicasarbu done.

**Comment by monicasarbu** [comment]
Thanks @tsg

**Comment by mmatur** [comment]
Hi @tsg, the changelog for Træfik module for filebeat is missing: #5372

**Pull request merged**
