### PR TITLE
Fixing type of ingress_hostname

### LINKED ISSUE #17192: Metricbeat mappings
So few observations. 
I've 7.6.0 and running kubernetes modules for metricbeat.
kubernetes.service.ingress_hostname -> this is defined as ip, but as field says - it is hostname not ip, therefore does not match mappipng.
kubernetes.service.cluster_ip -> this can be also "None" which is not exactly ip address, probably field in such case can be dropped out by pipeline code.

### PR DESCRIPTION
**Pull request by jonatan-ivanov**
Type of change: Bug

## What does this PR do?

See issue: #17192   
It changes the type of the `ingress_hostname` field since it is not an IP address

## Why is it important?

It is causing mapping issues (`ingress_hostname` is not an IP address): https://github.com/elastic/beats/issues/17192#issuecomment-637703103

## Checklist

- [x ] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

Please let me know if I'm missing something here and I should have done anything else.

## Related issues

- Closes elastic/beats#17192

Other types seem fishy too (should be IPs?), please let me know if you want these to be fixed too in this PR:

```
    - name: external_ip
      type: keyword
      description: Service external IP
    - name: load_balancer_ip
      type: keyword
      description: Load Balancer service IP
    - name: ingress_ip
      type: keyword
      description: Ingress IP
```

## Logs

See: https://github.com/elastic/beats/issues/17192#issuecomment-637703103

```
{
  "type":"mapper_parsing_exception",
  "reason":"failed to parse field [kubernetes.service.ingress_hostname] of type [ip] in document with id 'abc123'. Preview of field's value: 'xyz123.elb.us-west-2.amazonaws.com'",
  "caused_by":{
    "type":"illegal_argument_exception",
    "reason":"'xyz123.elb.us-west-2.amazonaws.com' is not an IP string literal."
  }
}
```

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
Thank you for fixing this! Could you run `mage update` under beats/metricbeat to update the fields please?

**Comment by jonatan-ivanov** [comment]
@kaiyan-sheng I've already done that right after the bot notified me. Is it possible to rerun the check or did I messed something up?

**Comment by jonatan-ivanov** [comment]
Oh wait: https://github.com/elastic/beats/pull/18912#issuecomment-637725743 and the check is passed. :)

**Comment by jsoriano** [comment]
jenkins run the tests please

**Comment by jsoriano** [comment]
@jonatan-ivanov could you please update this branch with master? Metricbeat tests are failing because of an issue that has been already solved.

**Comment by jonatan-ivanov** [comment]
@jsoriano @kaiyan-sheng done

**Comment by jsoriano** [comment]
ok to test

**Comment by jsoriano** [comment]
jenkins run the tests please

**Comment by jonatan-ivanov** [comment]
@kaiyan-sheng @jsoriano Could you please re-run the failing jobs?
I'm not sure if they will persist, to me they sem flaky:
- Travis has two failures both are apt-get install errors
- x-pack Linux has an InterruptedException (timeout/something shut down?)

**Comment by jsoriano** [comment]
Failure in metricbeat x-pack job should be fixed by https://github.com/elastic/beats/pull/18777, I think this PR would be good to go.

**Comment by kaiyan-sheng** [comment]
@jsoriano Great! I will get this merged and cherrypicked. Thank you @jonatan-ivanov!

**Pull request merged**
