### PR TITLE
Fix: Concatenate composed headers

### PR DESCRIPTION
**Pull request by PinXo**
Related to https://discuss.elastic.co/t/handling-cookies-in-http-parser/67335

If we have a response with two or more cookies, the cookie content is overwritten.

Response example:
> HTTP/1.0 200 OK
Date: Mon, 28 Nov 2016 08:49:56 GMT
Server: Apache/1.3.34 (Debian) PHP/4.4.4-8+etch6
X-Powered-By: PHP/4.4.4-8+etch6
Set-Cookie: name1=justname
Set-Cookie: name2=withexpire; expires=Wed, 28 Dec 2016 08:49:57 GMT
Set-Cookie: name3=withexpirepath; expires=Wed, 28 Dec 2016 08:49:57 GMT; path=/test/index.php
Set-Cookie: name4=withexpirepathdomain; expires=Wed, 28 Dec 2016 08:49:57 GMT; path=/test/index.php; domain=ZZZZZ
Set-Cookie: name5=withexpiredomainsecure; expires=Wed, 28 Dec 2016 08:49:57 GMT; path=/test; domain=ZZZZZ; secure
Content-Type: text/html; charset=iso-8859-1
X-Cache: MISS from XXXXX
X-Cache-Lookup: MISS from XXXX:YYYY
Via: 1.0 XXXX (squid)
Connection: close

Current result:

> "response" : {
			"code" : 200,
			"headers" : {
				"connection" : "Keep-Alive",
				"content-length" : 21,
				"content-type" : "text/html; charset=iso-8859-1",
				"date" : "Mon, 28 Nov 2016 09:17:32 GMT",
				"keep-alive" : "timeout=15, max=100",
				"server" : "Apache/1.3.34 (Debian) PHP/4.4.4-8+etch6",
				"set-cookie" : "naname5=withexpiredomainsecure; expires=Wed, 28 Dec 2016 09:17:32 GMT; path=/test; domain=ZZZZZ; secure\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000, \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000, \u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000\u0000",
				"transfer-encoding" : "chunked",
				"x-powered-by" : "PHP/4.4.4-8+etch6"
			},
			"phrase" : "OK"
		}

With this fix:

> "headers" : {
> 				"connection" : "Keep-Alive",
> 				"content-length" : 21,
> 				"content-type" : "text/html; charset=iso-8859-1",
> 				"date" : "Mon, 28 Nov 2016 09:24:03 GMT",
> 				"keep-alive" : "timeout=15, max=100",
> 				"server" : "Apache/1.3.34 (Debian) PHP/4.4.4-8+etch6",
> 				"set-cookie" : "name1=justname, name2=withexpire; expires=Wed, 28 Dec 2016 09:24:03 GMT, name3=withexpirepath; expires=Wed, 28 Dec 2016 09:24:03 GMT; path=/test/index.php, name4=withexpirepathdomain; expires=Wed, 28 Dec 2016 09:24:03 GMT; path=/test/index.php; domain=ZZZZZ, name5=withexpirepathdomainsecure; expires=Wed, 28 Dec 2016 09:24:03 GMT; path=/test; domain=ZZZZZ; secure",
> 				"transfer-encoding" : "chunked",
> 				"x-powered-by" : "PHP/4.4.4-8+etch6"
> 			},

### CODE REVIEW

**Comment by andrewkroh** [comment]
Do you think it would be more useful/usable to have fields like `headers.set-cookie.name1`? Basically make `set-cookie` an object all of the time instead of appending to it's value.

**Comment by PinXo** [comment]
Yes. A better solution would be a list of cookie objects with its own fields (name, expires, path, domain...):

> set-cookie : [
>     {
>         "id":"name1"
>         "name":"justname"
>     },
>     {
>         "id":"name2", 
>         "name":"withexpire", 
>         "expires":"Wed, 28 Dec 2016 09:24:03 GMT"
>     },
>     {
>         "id":"name3", 
>         "name":"withexpirepath", 
>         "expires":"Wed, 28 Dec 2016 09:24:03 GMT",
>         "path":"/test/index.php"
>     },
> ]
> 

My pull request is a temporary patch that fixes the content visualization, but this doesn't fix the split cookie function. This function is incongruous with the set-cookie content. The split function breaks the string in wrong tokens (commas, semicolons are mixed in the same "set-cookie" field) so should be revised too 
With the proposed solution, split function would become useless

**Comment by monicasarbu** [comment]
@PinXo Having `set-cookie` an array is not an ideal solution, as it's difficult to visualize arrays with Kibana. Instead, I suggest to have a dictionary:
```
set-cookie.name1: {
      "name":"justname"
}
set-cookie.name2: {
     "name":"withexpire",
     "expires":"Wed, 28 Dec 2016 09:24:03 GMT"
}
set-cookie.name3: {
     "name":"withexpirepath",
     "expires":"Wed, 28 Dec 2016 09:24:03 GMT",
    "path":"/test/index.php"
}
```

**Comment by PinXo** [comment]
You have a better global view of the system. From my point of view, any working solution would be fine :)

**Comment by faec** [comment]
Closing, since this issue been fixed by other changes in the meantime.

**Pull request closed without merging**
