### PR TITLE
[Agent] Using context propagated to

### PR DESCRIPTION
**Pull request by michalpristas**
Using context and propagating background context down to propagate cancellation to:
- http calls
- downloader
- reporter 
- fleet api

### CODE REVIEW

**Comment by ph** [comment]
This is a lot of changes, ping when ready to review. you are using straight context.Context? Have you look at the `chorus.Context`?

**Comment by michalpristas** [comment]
@ph draft so far. i looked at it and as it implements context.Context i believe they should be interchangeable. I started with a simpler step and using context directly.

**Comment by michalpristas** [comment]
Tested with Kibana, cancellation is propagated and agent cancels ongoing connections and escapes retry loops.

**Comment by ph** [comment]
Starting to look at it, I think it should be a blocker to merge in master.

**Pull request merged**
