### PR TITLE
[WIP] Fix a thread safety issues with the Logstash output.

### PR DESCRIPTION
**Pull request by ph**
The underlying library is not threadsafe, but when you are using Central
management it is possible that we are closing the client while trying to
send events just after from another go routine.

The things is the channel used by the client will be closed so it will
result in a panic.

### CODE REVIEW

**Comment by ph** [comment]
@urso I think theses errors will be raised more and more often as we move more stuff to be configured by CM. I know you have plan to refactor the output and move more logic in the client, with that I think a client should also be responsible of handling thread safety.

**Comment by Leaf-Lin** [comment]
Looks like https://github.com/elastic/beats/issues/12530 is related to the same issue.

**Comment by ph** [comment]
@urso just a ping for the [comment](https://github.com/elastic/beats/pull/12424#issuecomment-498777594)

**Comment by ph** [comment]
@Leaf-Lin indeed, look like the same issue.

**Comment by urso** [comment]
Yes, the crash is related.

But we should rather fix it in go-lumber, not here. e.g. `Send` might eventually block (send buffer is full). In this case an async call to `Close` shall unblock `Send` and force the publishing to fail.

The reason you see the panic is that 'Close' did not unblock and the sending did succeed. On success the sender forwards some meta-data to another go-routine waiting for ACKs.

**Comment by ph** [comment]
@urso I will take a look at go-lumber

**Comment by ph** [comment]
closing this, working on a fix on go-lumber instead.

**Pull request closed without merging**
