### PR TITLE
[Filebeat][Fortinet Module] Small bugfixes for time formats and IP address arrays

### LINKED ISSUE #19010: Timezone parsing error in pipeline of Fortinet module
The Fortinet module (#13245) seems to have issues with parsing timezone information from source logs. The issue being that the timezone is not formatted according to the standard expected by the (Java-based) timezone parser.

While parsing fortinet logs which are received via syslog (as described in https://www.elastic.co/guide/en/beats/filebeat/master//filebeat-module-fortinet.html), the following error is repored by the pipeline processor:

> Invalid ID for ZoneOffset, non numeric characters found: +2:00

The original log line starts as follows:

> <189>logver=60` timestamp=1591368557 tz="UTC+2:00" devname="....

From [Java's documentation about the timezone parser](https://docs.oracle.com/javase/8/docs/api/java/time/ZoneId.html), it becomes clear that timezones must always be two-digits, meaning that single-digit timezones like the one in my case would need to be prepended with a 0 to become UTC+02:00

**Proposed solution** 
In [module/fortinet/firewall/ingest/pipeline,yml](https://github.com/elastic/beats/blob/master/x-pack/filebeat/module/fortinet/firewall/ingest/pipeline.yml), add a processor to update the `fortinet.firewall.tz` value and prepend a 0 if needed, before all other processors are executed.

..

### LINKED ISSUE #19154: [FileBeat] Fortinet module doesn't handle multiple IP addresses in dns.resolved_ip (ipaddr) field.
Filebeat Fortinet module doesn't handle multiple IP addresses in dns.resolved_ip (ipaddr) field.

Sample log message:

`timestamp=1591954984 tz="UTC+1:00" devname="xxx" devid="xxx" vd="root" date=2020-06-12 time=10:43:04 logid="1501054401" type="utm" subtype="dns" eventtype="dns-response" level="information" eventtime=1591954984675787304 tz="+0100" policyid=39 sessionid=38501592 user="xx" srcip=xx srcport=64848 srcintf="port2" srcintfrole="lan" dstip=8.8.8.8 dstport=53 dstintf="wan1" dstintfrole="wan" proto=17 profile="xx" xid=43289 qname="xx" qtype="A" qtypeval=1 qclass="IN" ipaddr="1.1.1.1, 1.1.1.2" msg="Domain was allowed because it is in the domain-filter list" action="pass" domainfilteridx=1 domainfilterlist="xxx"`

note, field ipaddr is processed as follows:

```- rename:
    field: fortinet.firewall.ipaddr
    target_field: dns.resolved_ip
    ignore_missing: true
```
Error message:

`Cannot index event publisher.Event`
`failed to parse field [dns.resolved_ip]`
`"reason":"'1.1.1.1, 1.1.1.2' is not an IP string literal."`

The document here https://www.elastic.co/guide/en/ecs/current/ecs-dns.html says:

`dns.resolved_ip | Array containing all IPs seen in answers.data. (snip) type: ip Note: this field should contain an array of values. example: ['10.10.10.10', '10.10.10.11']`

I fixed this by adding a split processor to the utm pipeline as follows:

```
      {
        "split" : {
          "field" : "dns.resolved_ip",
          "separator" : ", ",
          "if" : "ctx.dns.resolved_ip.contains(',')"
        }
      },
```

I can submit PR if required?

### PR DESCRIPTION
**Pull request by P1llus**
## What does this PR do?

This PR resolves reported issues around the eventtime field being in both seconds and milliseconds and that the field ipaddr can also be an array.

## Why is it important?

Resolves niche usecases that would otherwise throw an error

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

Added new logs and reran nosetests to ensure it was fixed.

## Related issues

- Closes #19154 
- Closes #19010

### CODE REVIEW

**Comment by P1llus** [comment]
Done @leehinman

**Comment by rosswakelin** [comment]
This update does not fix all the date format issues.   Using the following event:

<189>date=2020-06-24 time=01:16:08 devname="LAB-AH-BCN-FG01" devid="FG5H1E5818905592" logid="0000000013" type="traffic" subtype="forward" level="notice" vd="OPERATIONAL" eventtime=1592961368 srcip=10.38.160.201 srcport=60899 srcintf="ATM-GAMMA" srcintfrole="lan" dstip=10.38.34.3 dstport=161 dstintf="CORE-OPS" dstintfrole="lan" sessionid=1539390213 proto=17 action="deny" policyid=0 policytype="policy" service="SNMP" dstcountry="Reserved" srccountry="Reserved" trandisp="noop" duration=0 sentbyte=0 rcvdbyte=0 sentpkt=0 appcat="unscanned" crscore=30 craction=131072 crlevel="high"

results in this parsing error
Invalid ID for ZoneOffset, invalid format:

Fortigate version 6.0.5
This issue has existed since the release of this module, but this update does not fix it.

**Comment by P1llus** [comment]
Il take a look @rosswakelin . This specific case was not known to me, as we do handle non-tz events in the pipeline, though seems not in this case. I will add the fix soon and include it + add another log event similar to yours (though anonymized) to our unit tests.

**Comment by P1llus** [comment]
@rosswakelin Much appreciated for the comment, it has now been resolved with the last commit and tests updated to catch anything similar later.

Since we do not know anything about the timezone we will have to default to something, currently that is UTC

**Comment by fredtj** [comment]
finding time errors in event.start,

i added UNIX alongside UNIX_MS to formats in pipeline.yml, this should now cover seconds and milliseconds?

**Comment by P1llus** [comment]
Please create a new issue if you find anything @fredtj else it might be possible for any of us to miss it. I have added the update here: https://github.com/elastic/beats/pull/19512

**Pull request merged**
