### PR TITLE
[fix][metricbeat] Change default value for server_status_path in nginx module

### PR DESCRIPTION
**Pull request by marc-gr**
## What does this PR do?

Fixes the default path for the nginx module from `server-status` to `nginx_status`

## Why is it important?

If set by default the endpoint will return a 404

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by andrewkroh** [comment]
Is this a breaking change for users that were relying on the default?

**Comment by marc-gr** [comment]
> Is this a breaking change for users that were relying on the default? Or would no one be using the default?

From my understanding, this change was intended to happen here https://github.com/elastic/beats/pull/14730, but was missing the bits in this PR. I'd like @kaiyan-sheng to confirm both my assumption and if it is a breaking change, and in that case how we should proceed.

**Comment by kaiyan-sheng** [comment]
@marc-gr Sorry maybe the original [PR](https://github.com/elastic/beats/pull/14099) from the community shouldn't be merged. Seems like this is not simply a documentation change but since the existing default path causes a 404 error, I would consider it as a bug fix instead of breaking change.

**Review by kaiyan-sheng — APPROVED** [review]
Thank you for fixing this!

**Pull request merged**
