### PR TITLE
fix: update pytest versions and pytest_otel

### PR DESCRIPTION
**Pull request by kuisathaverat**
## What does this PR do?

* It bumps pytest_otel to 1.3.0
* It bumps pytest to 7.1.3
* It bumps Otel Python SDK to 1.13

## Why is it important?

There is an issue with Otel Python SDK 1.11 running on Python 3.10+ see https://github.com/open-telemetry/opentelemetry-python/issues/2288

## Checklist

- [X] My code follows the style guidelines of this project
- ~[ ] I have commented my code, particularly in hard-to-understand areas~
- ~[ ] I have made corresponding changes to the documentation~
- [X] I have made corresponding change to the default configuration files
- ~[ ] I have added tests that prove my fix is effective or that my feature works~
- ~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~

## How to test this PR locally

```bash
cd x-pack/auditbeat
mage build test
```

## Related issues

related to https://github.com/elastic/beats/pull/33863 https://github.com/elastic/apm-pipeline-library/issues/1969

### CODE REVIEW

**Review by cachedout — APPROVED** [review]

**Comment by andrewkroh** [comment]
Looks like there is an issue with the virtualenv requirements.

>  \>\> python test: Unit Testing
> ERROR: Could not find a version that satisfies the requirement opentelemetry-api==1.13.0 (from versions: 0.1a0, 0.2a0, 0.3a0, 0.4a0, 0.4a1, 0.5b0, 0.6b0, 0.7b0, 0.7b1, 0.8b0, 0.9b0, 0.10b0, 0.11b0, 0.12b0, 0.13b0, 0.14b0, 0.15b0, 0.16b0, 0.16b1, 0.17b0, 1.0.0rc1, 1.0.0, 1.1.0, 1.2.0, 1.3.0, 1.4.0, 1.4.1, 1.5.0, 1.6.0, 1.6.1, 1.6.2, 1.7.0, 1.7.1, 1.8.0, 1.9.0, 1.9.1, 1.10a0, 1.10.0, 1.11.0, 1.11.1, 1.12.0rc1, 1.12.0rc2, 1.12.0)

**Comment by kuisathaverat** [comment]
@andrewkroh [Ubuntu 18.04 workers have Python 3.6](https://packages.ubuntu.com/bionic/python3), and [Python OpenTelemetry SDK removed support for Python 3.6 in the version 1.13](https://github.com/open-telemetry/opentelemetry-python/blob/main/CHANGELOG.md#version-1130034b0-2022-09-26) 

Solutions are bump Ubuntu 18.04 workers to 20.04 or 22.04 or remove pytest_otel. WDYT @v1v?

**Comment by v1v** [comment]
> Solutions are bump Ubuntu 18.04 workers to 20.04 or 22.04 or remove pytest_otel. WDYT @v1v?

I'd be inclined to use `ubuntu:22` if possible, let me put a couple of PRs for both OSes so we can then test they work as expected

**Comment by andrewkroh** [comment]
If ubuntu 22.04 is passing for everything then that SGTM. We can add a new OS column to a support matrix for Beats too 😄 .

**Comment by v1v** [comment]
https://github.com/elastic/beats/pull/34355 has been merged hence this PR will be ready to give another go :) I'll update the branch with the above button

**Comment by kuisathaverat** [comment]
The CI pass, @andrewkroh Are you OK to merge?

**Review by andrewkroh — APPROVED** [review]
👍

**Comment by kuisathaverat** [comment]
The issue is still present in the ARM workers. We have to bump the Python version in those workers too

**Comment by v1v** [comment]
I guess we won't backport this to 8.6 and 7.17, so I'll then close the ones that were opened for the ubuntu-22

**Pull request merged**
