### PR TITLE
[Metricbeat] gcp: fix dataproc fields

### PR DESCRIPTION
**Pull request by ghost**
## What does this PR do?

Fixes gcp dataproc fields.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by rdner** [comment]
@mergifyio update

**Comment by jlind23** [comment]
@elastic/obs-cloud-monitoring can we have your eyes on it as it seems to be GCP related.

**Comment by kaiyan-sheng** [comment]
@gpop63 Could you share more background on why these fields are removed? Thank you so much!!

**Comment by gpop63** [comment]
> @gpop63 Could you share more background on why these fields are removed? Thank you so much!!

The GCP module doesn't support `DISTRIBUTION` type metrics yet. We decided to remove these metrics and add them later after support for `DISTRIBUTION` metrics is added in the module.

**Comment by rdner** [comment]
@kaiyan-sheng would you mind to have another look?

**Comment by kaiyan-sheng** [comment]
@gpop63 Good to know. Thanks for the information. Here is the issue for add distribution type into gcp: https://github.com/elastic/beats/issues/17975

**Comment by kaiyan-sheng** [comment]
Removing the distribution type is OK for me, @endorama do you have any concerns here? 

CI seems to be unhappy with lint though:
```
Error: SA1019: package github.com/golang/protobuf/ptypes is deprecated: Well-known types have specialized functionality directly injected into the generated packages for each message type. See the deprecation notice for each function for the suggested alternative.  (staticcheck)
  Error: import of package `github.com/pkg/errors` is blocked because the module is in the blocked modules list. `errors` and `fmt` are recommended modules. This package is deprecated, use `fmt.Errorf` with `%!w(MISSING)` instead. (gomodguard)
  Error: `(*incomingFieldExtractor).extractTimeSeriesMetricValues` - result `err` is always `nil` (unparam)
  Error: SA1019: ptypes.Timestamp is deprecated: Call the ts.AsTime and ts.CheckValid methods instead.  (staticcheck)
  Error: x-pack/metricbeat/module/gcp/metrics/response_parser.go:[26](https://github.com/elastic/beats/runs/5865910048?check_suite_focus=true#step:6:26)5: Line contains TODO/BUG/FIXME: "TODO Distribution values aren't simple v..." (godox)
```

**Comment by gpop63** [comment]
@kaiyan-sheng The `golangci-lint` CI job was added recently, and for it to pass the whole module would need a refactor. Replace `github.com/pkg/errors` with `fmt` package etc.

**Comment by endorama** [comment]
@kaiyan-sheng I reviewed this with @gpop63 already and from my understanding this is not working anyway (we collect data but when we send the event is not correct)

**Comment by rdner** [comment]
@kaiyan-sheng @endorama so my understanding we can merge it now, please approve the PR if so.

**Review by kaiyan-sheng — APPROVED** [review]

**Pull request merged**
