### PR TITLE
Add regex based cid extractor to add_process_metadata

### PR DESCRIPTION
**Pull request by jtinkus**
- Enhancement
## What does this PR do?

Adds regex based cid extractor to add_kubernetes_metadata
## Why is it important?

Adds more flexibility and makes possible to bypass bug with kube-proxy cid turning out to be "kube-proxy"
## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- 
Relates:
#15947
#17351

### CODE REVIEW

**Comment by jtinkus** [comment]
Hello @exekias 

Here is regex addon to cid extraction. 
Is it something you had in your mind?

Regards,

**Comment by jtinkus** [comment]
@exekias  auto checks green and checklist check-boxes checked now :)

**Comment by exekias** [comment]
ok to test

**Comment by exekias** [comment]
Thank you so much for contributing! Waiting for a green light from the CI

**Pull request merged**
