### PR TITLE
Clean up formatting in help message

### PR DESCRIPTION
**Pull request by cachedout**
This is a minor change in a help message just to make it slightly easier to read. No functionality should be affected.

### CODE REVIEW

**Comment by cachedout** [comment]
jenkins, test this.

**Comment by elasticcla** [comment]
Hi @cachedout, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/beats/pull/9696.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by cachedout** [comment]
jenkins, retest this.

**Comment by cachedout** [comment]
jenkins, test this.

**Comment by ycombinator** [comment]
Hey @cachedout, just curious: why was this PR closed w/o merging?

**Comment by cachedout** [comment]
@ycombinator It contained a commit that was not signed with an email address and so the CLA checker wouldn't pass. I intend to re-submit the changes.

**Pull request closed without merging**
