### PR TITLE
Basic Kibana client apm instrumentation

### PR DESCRIPTION
**Pull request by simitt**
## What does this PR do?

Vendor go.elastic.co/apm and add context to Kibana client Send method. If the passed in context includes an APM transaction the outgoing Kibana request will be recorded as span.

Use context.TODO() where no starting context is currently available.

## Why is it important?

This lays the groundwork for adding instrumentation to outgoing calls to Kibana. At the moment,
the beats use the Kibana connection only for one-off requests, such as loading dashboards. APM Server uses it for regular queries to Kibana where adding instrumentation helps gaining more insights into these requests.

## Checklist

- [x] My code follows the style guidelines of this project
~- [ ] I have commented my code, particularly in hard-to-understand areas~
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files~
~- [ ] I have added tests that prove my fix is effective or that my feature works~

## Author's Checklist

- [x] Add changelog entry

## Related issues

Precondition for https://github.com/elastic/apm-server/issues/3185

### CODE REVIEW

**Comment by simitt** [comment]
jenkins run the tests again

**Comment by urso** [comment]
LGTM. Can you please add some instructions to the PR description about testing and how to configure?

**Comment by urso** [comment]
Please check formatting or `go vet`. The intake job is complaining with:

```
14:44:39 >> check: Checking source code for common problems
14:44:43 Error: some files are not up-to-date. Run 'mage fmt update' then review and commit the changes. Modified: [auditbeat/auditbeat.reference.yml]
14:44:43 ../libbeat/scripts/Makefile:143: recipe for target 'check' failed
14:44:43 make[1]: Leaving directory '/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-intake/src/github.com/elastic/beats/auditbeat'
14:44:43 make[1]: *** [check] Error 1
14:44:43 Makefile:92: recipe for target 'check' failed
14:44:43 Running cleanup...
```

**Comment by simitt** [comment]
I decided to go with the minimal required changes. This is superseded by https://github.com/elastic/beats/pull/16515.

**Pull request closed without merging**
