### PR TITLE
Fix generating your beat documentation

### PR DESCRIPTION
**Pull request by tomotargz**
## What does this PR do?

Fix the "generating your beat" documentation. According to the documentation, you run `mage GenerateCustomBeat` command in `${GOPATH}/src/github.com/{user}` dir, but it fails. You should run the command in `${GOPATH}/src/github.com/elastic/beats` directory

## Why is it important?

To prevent confusion for those who try to develop a new beat.

## Checklist

- [ ] ~~My code follows the style guidelines of this project~~
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

I ran the commands I wrote in the "Logs" section on the following environment.
- Max OS Big Sur
- go 1.15.3

## Related issues

- 

## Logs

Running `mage GenerateCustomBeat` command in the directory specified by the documentation fails.

```sh
$ mkdir ${GOPATH}/src/github.com/tomotargz
$ cd ${GOPATH}/src/github.com/tomotargz
$ mage GenerateCustomBeat
No .go files marked with the mage build tag in this directory.
```

You should run the command in `${GOPATH}/src/github.com/elastic/beats` dir.

```sh
$ rm -rf ${GOPATH}/src/github.com/tomotargz
$ cd ${GOPATH}/src/github.com/elastic/beats
$ mage GenerateCustomBeat
Enter the beat name [examplebeat]: Countbeat
Enter your github name [your-github-name]: tomotargz
Enter the beat path [github.com/tomotargz/countbeat]:
Enter your full name [Firstname Lastname]: Tomota Nakamura
Enter the beat type [beat]:
Enter the github.com/elastic/beats revision [master]:
go: creating new go.mod: module github.com/tomotargz/countbeat
.
.
.
=======================
Your custom beat is now available as /Users/tomota/go/src/github.com/tomotargz/countbeat
=======================
$ ls ${GOPATH}/src/github.com/tomotargz/countbeat
CONTRIBUTING.md         README.md               cmd                     countbeat.yml           go.sum                  main_test.go
LICENSE.txt             _meta                   config                  docs                    include                 make.bat
Makefile                beater                  countbeat.docker.yml    fields.yml              magefile.go             tests
NOTICE.txt              build                   countbeat.reference.yml go.mod                  main.go                 tools
```

### CODE REVIEW

**Comment by fearful-symmetry** [comment]
Looks good to me, @tomotargz can you add a changelog entry

**Comment by fearful-symmetry** [comment]
Jenkins, test this

**Comment by tomotargz** [comment]
@fearful-symmetry Thanks! I added an entry.

**Comment by fearful-symmetry** [comment]
jenkins, test this

**Comment by jlind23** [comment]
Backlog grooming - Closing this until further update.

**Pull request closed without merging**
