### PR TITLE
[Metricbeat] Create dashboard for AWS SNS metricset

### PR DESCRIPTION
**Pull request by mtojek**
This PR introduces dashboard for the AWS SNS metricset.

Screenshot:

metricbeat-aws-sns-overview

Master issue: https://github.com/elastic/beats/issues/14855

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
[Metricbeat AWS] for each session in dashboard can be removed 👍

**Comment by kaiyan-sheng** [comment]
Maybe metrics like SNS Notification failed only needs to be a metric instead of time series? For example: EC2 Status Check Failed visualization

**Comment by mtojek** [comment]
> [Metricbeat AWS] for each session in dashboard can be removed 👍

Fixed.

**Comment by mtojek** [comment]
> Maybe metrics like SNS Notification failed only needs to be a metric instead of time series? For example: EC2 Status Check Failed visualization

I would like to keep TSVBs as they give a meaningful information. User story: as ops I would like to see if the infrastructure faced some notification delivery hiccups over the night. Simple counters might be useful if you're tracking currently rolled out deployments and there's no more space on your main dashboard, but still - you can the same with TSVB

**Comment by mtojek** [comment]
> [Metricbeat AWS] for each session in dashboard can be removed 👍

Unfortunately, linter failed. Reverting. Proof:

```
[2019-12-09T08:58:25.099Z] >> Dashboard format - module/aws/_meta/kibana/7/dashboard/Metricbeat-aws-sns-overview.json:
[2019-12-09T08:58:25.099Z]    expected title with format 'Some title [Metricbeat Module]', found 'SNS Messages Published': title doesn't match pattern
[2019-12-09T08:58:25.099Z]    expected title with format 'Some title [Metricbeat Module]', found 'SNS Notifications Delivered': title doesn't match pattern
[2019-12-09T08:58:25.099Z]    expected title with format 'Some title [Metricbeat Module]', found 'SNS Notifications Failed': title doesn't match pattern
[2019-12-09T08:58:25.099Z]    expected title with format 'Some title [Metricbeat Module]', found 'SNS Publish Size': title doesn't match pattern
[2019-12-09T08:58:25.099Z]    expected title with format 'Some title [Metricbeat Module]', found 'SNS Notifications Filtered Out': title doesn't match pattern
[2019-12-09T08:58:25.099Z]    expected title with format 'Some title [Metricbeat Module]', found 'SNS Notifications Filtered Out No Message Attributes': title doesn't match pattern
[2019-12-09T08:58:25.099Z]    expected title with format 'Some title [Metricbeat Module]', found 'SNS Notifications Filtered Out Invalid Attributes': title doesn't match pattern
[2019-12-09T08:58:25.099Z]    expected title with format 'Some title [Metricbeat Module]', found 'SNS SMS Success Rate': title doesn't match pattern
[2019-12-09T08:58:25.099Z]    expected title with format 'Some title [Metricbeat Module]', found 'SNS Notifications Failed To Redrive To DLQ': title doesn't match pattern
[2019-12-09T08:58:25.099Z]    expected title with format 'Some title [Metricbeat Module]', found 'SNS Notifications Redriven To DLQ': title doesn't match pattern
[2019-12-09T08:58:25.099Z]    expected title with format 'Some title [Metricbeat Module]', found 'SNS SMS Month To Date Spent USD': title doesn't match pattern
```

**Comment by jsoriano** [comment]
> > [Metricbeat AWS] for each session in dashboard can be removed +1
> 
> Unfortunately, linter failed. Reverting. Proof:
> 

@mtojek yeah, the prefix is needed in the visualization, to help when they are listed in Kibana. But panel titles can be modified once placed in the dashboard, like described in this comment https://github.com/elastic/beats/pull/13187#issuecomment-519911298

**Comment by mtojek** [comment]
@jsoriano 

Thank for you for the explanation. Customizations (titles) have been applied, also screenshot updated.

**Pull request merged**
