### PR TITLE
Remove machine learning functionality from Beats

### PR DESCRIPTION
**Pull request by kvch**
### **DO NOT BACKPORT THIS PR TO 7.x**

In 8.0 loading machine learning jobs are removed from Beats. From now on, the Kibana app needs to be used instead.

This PR removes the following things:
- `--machine-learning` flag from `setup` subcommand
- machine-learning configuration from manifest.yml of modules
- machine-learning loader functionality and tests

### CODE REVIEW

**Comment by urso** [comment]
Added the v8.0.0 label. This change should not be backported. We still need a PR in 7.x to log a deprecation message.

**Comment by urso** [comment]
@sophiec20 fyi

**Comment by kvch** [comment]
The failing tests are unrelated and already fixed on master. I rebased the branch.

A deprecation message has been added to Filebeat in https://github.com/elastic/beats/pull/14532

**Comment by kvch** [comment]
Failing tests are unrelated.

**Pull request merged**
