### PR TITLE
Close changelog for 7.2.1

### PR DESCRIPTION
**Pull request by mikemadden42**

### CODE REVIEW

**Comment by mikemadden42** [comment]
jenkins retest this please

**Comment by urso** [comment]
There are obviously some backports since this PR has been created.
The last build candidate was created on July 9th (commit 16393a91243079bef6e6c9986eb7e3229ebf20da).

Missing changelog entries:
- https://github.com/elastic/beats/commit/16393a91243079bef6e6c9986eb7e3229ebf20da

**Comment by mikemadden42** [comment]
jenkins retest this please

**Comment by mikemadden42** [comment]
jenkins retest this please

**Comment by mikemadden42** [comment]
jenkins retest this please

**Pull request merged**
