### PR TITLE
Fix geoip link

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
This PR is to fix error in https://elasticsearch-ci.elastic.co/job/elastic+docs+master+build/3967/console:
```
11:35:00 Bad cross-document links:
11:35:00   html/en/beats/packetbeat/master/packetbeat-geoip.html:
11:35:00    - en/elasticsearch/reference/master/ingest-geoip.html
11:35:00    - en/elasticsearch/reference/master/using-ingest-geoip.html
```

### CODE REVIEW

**Comment by ruflin** [comment]
Do we need this also for `user_agent`?

**Comment by kaiyan-sheng** [comment]
@ruflin I didn't see anywhere referenced ingest-user-agent webpage under packetbeat. If I see any, I will add the change for sure.

**Comment by ruflin** [comment]
Thanks for checking.

**Comment by exekias** [comment]
failing tests are unrelated

**Pull request merged**
