### PR TITLE
libbeat/reader: Fix messge conversion to beat.Event

### PR DESCRIPTION
**Pull request by belimawr**
## What does this PR do?

`Message.ToEvent` was not copying the `Message.Privage` field when
converting a Message to `beat.Event`. This commit fixes it.

Fixes: #30031
## Why is it important?

It fixes the journald input
## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

~~## Author's Checklist~~

## How to test this PR locally

Use journald input and console output, the events outputted should look like the one described on #30031

## Related issues

- Fixes: #30031

~~## Use cases~~

~~## Screenshots~~

~~## Logs~~

### CODE REVIEW

**Comment by belimawr** [comment]
@kvch @mtojek could you double check my backport labels, please?

**Review by kvch — APPROVED** [review]

**Comment by kvch** [comment]
Removed backporting to 7.17, as the code that broke journald input was released in 7.x.

**Comment by kvch** [comment]
jenkins run tests

**Comment by belimawr** [comment]
> Removed backporting to 7.17, as the code that broke journald input was released in 7.x.

Was it released in 7.x or was it **not** released on 7.x?

Anyway, I trust you more than myself on this one ;)

**Pull request merged**
