### PR TITLE
[GCP] update permissions and remove wrong config example

### PR DESCRIPTION
**Pull request by endorama**
## What does this PR do?

Updates `gcp` module docs to fix required permissions list.
Updated `gcp.metrics` metricset docs to remove example for collecting set of metrics starting with prefix.

## Why is it important?

The first because without that permissions compute information cannot be retrieved.
The second because we do not support that use case so the configuration is misleading.

## Checklist

- [ ] ~~My code follows the style guidelines of this project~~
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [ ] ~~I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by llermaly** [comment]
@endorama  you may also this use PR to fix the permissions titles 

* `Monitoring Viewer` (2 permissions in use of 13)
- `compute.instances.get`
- `compute.instances.list`

Title says Monitoring Viewer , but it is actually listing "Compute  Viewer" needed permissions.

**Comment by endorama** [comment]
I can't successfully run `make update` to make the CI happy, I'm in touch with the beats to understand how to solve it.

**Comment by gpop63** [comment]
I think you should run `make update` from `metricbeat` folder path not from `x-pack/metricbeat` folder path. I tried it locally and it generated a new `gcp.asciidoc` file with your changes.

**Review by gpop63 — APPROVED** [review]

**Comment by endorama** [comment]
@gpop63 I had to remove a build cache folder and run `make clean` to successfully run `make update`. Thanks for the review!

**Pull request merged**
