### PR TITLE
Export percentages for CPU usage 

### PR DESCRIPTION
**Pull request by monicasarbu**
WIP

With this PR, Topbeat exports CPU usage statistics in percentage instead of CPU ticks. The percentages are: 
- `cpu.iowait_p`, `cpu.idle_p`, `cpu.irq_p`, `cpu.nice_p`, `cpu.softirq_p`, `cpu.steal_p`, `cpu.system_p` and `cpu.user_p`.
- `proc.cpu.total_p`

If `cpu_per_core` is true, then Topbeat exports the CPU usage statistics in percentage for each core.

By default the CPU usage is exported only in percentage.

If the user is interested in exporting the CPU ticks (`cpu.iowait`, `cpu.idle`, `cpu.irq`, `cpu.nice`, `cpu.softirq`, `cpu.steal`), he/she needs to set the configuration option `cpu_ticks` to true.

If the user is interested in exporting the CPU ticks (`proc.cpu.user`, `proc.cpu.system`, `proc.cpu.total`), he/she needs to set the configuration option `cpu_ticks_per_proc` to true.

cc-ed: @tsg @simianhacker @ruflin @andrewkroh

### CODE REVIEW

**Comment by ruflin** [comment]
Two things:

* This is a BC break and requires the CHANGELOG to be updated
* This change also affects metricbeat and needs updates in metricbeat. Question here for metricbeat is if these are 2 different metricsets or just one?

**Comment by monicasarbu** [comment]
The PR is still work in progress and I will update Metricbeat. I cc-ed you guys, so you can see that I started working on it.

**Comment by ruflin** [comment]
@monicasarbu Sorry, thought it is ready for review. My mistake.

**Comment by monicasarbu** [comment]
Close this one in favor of https://github.com/elastic/beats/pull/1705. I would like to open a different PR to refactor the Topbeat code.

**Pull request closed without merging**
