### PR TITLE
Cosmetic/type changes to  fields.yml and fields.common.yml

### PR DESCRIPTION
**Pull request by ilyaresh**
Cosmetic changes to have capital case for first letter of duration description  in heartbeat/_meta/fields.common.yml
Typo fix for response_header's description in heartbeat/monitors/active/http/_meta/fields.yml

### CODE REVIEW

**Comment by ruflin** [comment]
@ilyaresh Thanks for the contribution. Could you sign the CLA? http://www.elasticsearch.org/contributor-agreement/

Also run `make update` in the `heartbeat` directory to make sure all files are updated. This should get CI green.

**Comment by ruflin** [comment]
@ilyaresh Any update on this one? Also happy to take this over if you like.

**Comment by ilyaresh** [comment]
Hi Nicholas,
Please do take it over,
I'm a bit struggling to make a docs build on my Windows machine...:-(

On 27 Nov 2017 4:14 PM, "Nicolas Ruflin" <notifications@github.com> wrote:

@ilyaresh <https://github.com/ilyaresh> Any update on this one? Also happy
to take this over if you like.

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/elastic/beats/pull/5324#issuecomment-347080793>, or mute
the thread

**Comment by ruflin** [comment]
Thanks @ilyaresh. Closing this in favor of https://github.com/elastic/beats/pull/5724 .

**Pull request closed without merging**
