### PR TITLE
[Metricbeat] migrate haproxy module to ReporterV2 error

### PR DESCRIPTION
**Pull request by berfinsari**
See elastic/beats#11374 and elastic/beats#10727

### CODE REVIEW

**Comment by fearful-symmetry** [comment]
jenkins, test this

**Comment by fearful-symmetry** [comment]
jenkins, test this

**Comment by fearful-symmetry** [comment]
It looks like the jenkins failures are fixed by #11468 
Merge and try again?

**Comment by ruflin** [comment]
Best rebase and this one should go green.

**Comment by berfinsari** [comment]
Thanks for the review! @ruflin @fearful-symmetry

**Comment by ruflin** [comment]
jenkins, test this

**Pull request merged**
