### PR TITLE
Mark logging.ecs and json as deprecated

### PR DESCRIPTION
**Pull request by michel-laterman**
## What does this PR do?

Mark `logging.ecs` and `logging.json` as deprecated for the `v7.16.0` release.
These attributes will no longer be used in 8.0.

## Why is it important?

These settings will be removed for 8.0 as part of the work to get all components producing ECS logs by default.
The PR is https://github.com/elastic/beats/pull/28573

## Checklist

- [] ~~My code follows the style guidelines of this project~~
- [] ~~I have commented my code, particularly in hard-to-understand areas~~
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [] ~~I have added tests that prove my fix is effective or that my feature works~~
- [] ~~I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Related issues

- Relates #15544

### CODE REVIEW

**Comment by kvch** [comment]
Maybe add a `cfgwarn` message if the user configures the option.

**Comment by michel-laterman** [comment]
@kvch there will be a circular dependency if I try to use `cfgwarn` within `logp`

**Review by dedemorton — APPROVED** [review]
LGTM. Thanks for contributing!

**Comment by kvch** [comment]
:facepalm:

**Comment by kvch** [comment]
Then how about noting the deprecation in the configuration files as well?

**Review by kvch — APPROVED** [review]

**Pull request merged**
