### PR TITLE
Replace EOL modules: github.com/golang/protobuf by google.golang.org/protobuf

### PR DESCRIPTION
**Pull request by AndersonQ**
## Proposed commit message

Replace EOL modules `github.com/golang/protobuf` by `google.golang.org/protobuf`

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

Tun all the tests

## Related issues

- Closes https://github.com/elastic/beats/issues/37016

### CODE REVIEW

**Comment by andrewkroh** [comment]
Is that title and description correct? Did you mean replaced by `google.golang.org/protobuf/proto`?

**Comment by AndersonQ** [comment]
> Is that title and description correct? Did you mean replaced by `google.golang.org/protobuf/proto`?

ops, my bad. I fixed it already

**Review by andrewkroh — APPROVED** [review]

**Review by blakerouse — APPROVED** [review]
Looks good.

**Comment by AndersonQ** [comment]
@elastic/obs-cloud-monitoring, folks I believe the code I touched is under your ownership. Could you review it or let me know if it isn't yours?

**Comment by pierrehilbert** [comment]
@bturquet could someone in your team validate this change please?

**Review by kaiyan-sheng — APPROVED** [review]
LGTM

**Review by rdner — APPROVED** [review]

**Pull request merged**
