### PR TITLE
New `add_lxc_metadata` processor

### PR DESCRIPTION
**Pull request by 907th**
This PR adds a new `add_lxc_metadata` processor which detects LXC container ID of the process from event. The processor adds `container.id` field to the event.

This PR is based on `add_docker_metadata` processor. It rely on sysfs and try to extract container ID from `/lxc/<cid>/...` cgroup paths.

My personal use case for this processor: I have a Proxmox virtual environment setup with many microservices run in LXC containers. I need to audit this setup with auditbeat (auditd module) and I want containers ID to be automatically detected and stored along with each audit event.

### CODE REVIEW

**Comment by 907th** [comment]
I'm unable to sign CLA as DocuSign renders error: Unable to load PowerForm, invalid template ID. =(

**Comment by 907th** [comment]
I also realized that `add_kubernetes_metadata` adds `kubernetes.*` keys to event fields. But `add_docker_metadata` (and this processor) doesn't use `docker.*` prefix and adds `container.id`, `container.name`, etc. fields. Would it be better to add `lxc.container.id` instead of `container.id` field?

**Comment by odacremolbap** [comment]
Hi @907th 
getting that docusign error myself, let me find out what might be going on

**Comment by odacremolbap** [comment]
Hi again @907th 
The CLA issue should be fixed now, can you try to sign it again please?

**Comment by elasticcla** [comment]
Hi @907th, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/beats/pull/11663.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by 907th** [comment]
@odacremolbap Thank you! I successfully signed a single developer license now.

**Comment by 907th** [comment]
@odacremolbap Travis check reports this:
```
packetbeat/docs/fields.asciidoc: needs update
packetbeat/include/fields.go: needs update
winlogbeat/docs/fields.asciidoc: needs update
winlogbeat/include/fields.go: needs update
```
I'm unsure how to fix that. Can you help me, please?

**Comment by odacremolbap** [comment]
You can follow instructions [here](https://www.elastic.co/guide/en/beats/devguide/current/beats-contributing.html)

You will most probably need to execute `make update` to update all generated assets.

**Comment by exekias** [comment]
> I also realized that `add_kubernetes_metadata` adds `kubernetes.*` keys to event fields. But `add_docker_metadata` (and this processor) doesn't use `docker.*` prefix and adds `container.id`, `container.name`, etc. fields. Would it be better to add `lxc.container.id` instead of `container.id` field?

We are trying to standardize some fields for better analysis, you can find more details here: https://www.elastic.co/blog/introducing-the-elastic-common-schema. For this reason, `container.*` fields will be preferred where applicable.

**Comment by 907th** [comment]
@exekias @odacremolbap Before continuing with this PR I want to complete the setup of my development env. I use Vagrant with `ubuntu1804` machine and there are some problems: e.g. I can not execute `make update` command:

```
$ cd /vagrant # or cd ~/go/src/github.com/elastic/beats/
$ make update
...
Error: failed to determine root import path (Did you git init?, Is the project in the GOPATH? GOPATH=/home/vagrant/go, CWD=/vagrant/libbeat?): [directory "/vagrant/libbeat" is outside source root "/home/vagrant/go/src"]
...
```

Should I open an issue for this problem? Which is the best option for development configuration for Beats project?

**Comment by andrewkroh** [comment]
Directly running `make` and `mage` commands from a given beat directory seems to work OK for me from within the ubuntu1804 VM when I work from the `GOPATH` (`~/go/src/github.com/elastic/beats`).

But I do get an error while trying to run the top-level `make update`. `make` seems to be following the symlink when running `make -C <dir>` and jumping to `/vagrant` which is not the canonical location for a Go project so then nothing in the project's `vendor/` dir is found by Go.

You can see the issue just by running `make -C x-pack/auditbeat clean`.

```
make -C x-pack/auditbeat clean
make: Entering directory '/vagrant/x-pack/auditbeat'
```

**Comment by blakerouse** [comment]
@907th We are in the process of cleanup some old PR's, noticed this hasn't had any activity in a while. Are you still interested in getting this merged? Would you be able to rebase with latest master?

**Pull request closed without merging**
