### PR TITLE
Allow the Host header to be overriden (fixes #9376)

### LINKED ISSUE #9376: [Heartbeat]Permit  Host header override
Hello

**Describe the enhancement:**
I should be abled to override the Host header to test my services.
At the beginning i thought i did something wrong but Mr Cholakian told me to ask for a feature request: https://discuss.elastic.co/t/http-check-override-host-header/157660

**Describe a specific use case for the enhancement or feature:**
I want to test individually:

My CDN
My varnish
My backend
To do that i need to check the IP with a custom Header, if i had to script it i would use Curl:

curl -I -H "Host:my_superb_domain_name.com" http://IPCDN/myasset.json
curl -I -H "Host:my_superb_domain_name.com" http://IPvarnish/myasset.json
curl -I -H "Host:my_superb_domain_name.com" http://IPbackend/myasset.json
So i tried to do something like that:

- type: http
  urls: ["http://IPCDN/myasset.json","http://IPvarnish/myasset.json","http://IPbackend/myasset.json"]
  check.request:
    method: GET
    headers:
      accept-encoding: gzip,deflate
      host: my_superb_domain_name.com

The Host header is not used, so i get a 404 or a 403 depending of the default behavior of my cdn/varnish/backend

It would be nice to be able to do so :)
Have a good day

PS: Heartbeat.... not metricbeat of course

### PR DESCRIPTION
**Pull request by K-Phoen**
As explained on [golang's repository](https://github.com/golang/go/issues/7682), adding a *Host* header to the request's headers list isn't enough. So when this header is defined by the configuration, I also explicitly give it to the HTTP request.

### CODE REVIEW

**Comment by andrewvc** [comment]
Thanks for opening this @K-Phoen . Would you be able to write a test, either in go or python, to back this PR?

You can find python acceptance tests [here](https://github.com/elastic/beats/tree/master/heartbeat/tests)
Golang tests are alongside the source files.

**Comment by K-Phoen** [comment]
I wrote a small unit test showing that the Host header is correctly defined in the HTTP request.

**Comment by andrewvc** [comment]
jenkins, please test this

**Comment by K-Phoen** [comment]
Done!

Thanks for reviewing my PR :)

**Comment by andrewvc** [comment]
@K-Phoen of course!

jenkins, test this please

**Comment by andrewvc** [comment]
Build failures are unrelated, merging. Thanks!

**Pull request merged**
