### PR TITLE
Add central management telemetry

### LINKED ISSUE #7979: Basic telemetry for Beats central configuration
When we ship the Beats central configuration issue, we should track basic telemetry metrics around usage, to help us improve the feature going forward.

Initial idea is to add number of Beats enrolled with central management, split up by type of Beat. This could serve as a basic measure of adoption.

Down the road, we should discuss other metrics that might be a good measure of ongoing engagement, such as # of configuration changes tracked over time, etc..

cc: @ruflin @exekias @mattapperson

### PR DESCRIPTION
**Pull request by exekias**
This will report central management enabled status

closes #7979

### CODE REVIEW

**Comment by ruflin** [comment]
@exekias This will need backport?

@chrisronline I wonder if we should show this info somehow in monitoring?

**Comment by ruflin** [comment]
@exekias This will need backport?

@chrisronline I wonder if we should show this info somehow in monitoring?

**Comment by ruflin** [comment]
@exekias This will need backport?

@chrisronline I wonder if we should show this info somehow in monitoring?

**Comment by ruflin** [comment]
@exekias This will need backport?

@chrisronline I wonder if we should show this info somehow in monitoring?

**Comment by ruflin** [comment]
Will this need a backport?

@chrisronline Perhaps we could should this somehow in the monitoring UI?

**Comment by chrisronline** [comment]
@ruflin Ideally, this data is reported through monitoring documents (instead of an api) so we can support multi-cluster setups, so as long as it's reported there, we should be able to show it.

**Comment by exekias** [comment]
Thank you for your changes @ruflin, as PR author I cannot approve them, but I'm ok with this going in :smile:

**Pull request merged**
