### PR TITLE
Moving outputs/transport => common/transport

### LINKED ISSUE #16728: Remove libbeat/outputs/transport
The libbeat/outputs/transport package has been superseded by the libbeat/common/transport package, with the common/transport package being supposed to have sub-packages per use-cases/service. The libbeat/output/transport package mostly aliases libbeat/common/transport/tlscommon and should be removed.

### PR DESCRIPTION
**Pull request by ycombinator**
## What does this PR do?

- Moves the `transport` package from `libbeat/outputs/transport` to `libbeat/common/transport`. 
- Removes `outputs/tls.go` and updates all it's usages.
- Replaces `*Config` parameters (pass-by-pointer) with `Config` parameters (pass-by-value) in functions/methods wherever safe.

## Why is it important?

The code in this package is used in places other than outputs.

## Developer Docs

This PR introduces breaking changes to the API provided by libbeat. 
- If you were importing `libbeat/outputs/transport`, in most cases you must now import `libbeat/common/transport` instead.
- If you were importing `libbeat/outputs/transport` or `libbeat/outputs` for using any TLS-related symbols, you must now import `libbeat/common/transport/tlscommon` instead.
- If you were calling `libbeat/outputs/transport.MakeDialer` with a `*Config` object as the first argument, you must now call `libbeat/common/transport.MakeDialer` with a `Config` object as the first argument instead.
- If you were calling `libbeat/outputs/transport.NewClient` with a `*Config` object as the first argument, you must now call `libbeat/common/transport.NewClient` with a `Config` object as the first argument instead.
- If you were calling `libbeat/outputs/transport.NewClientWithDialer` with a `*Config` object as the second argument, you must now call `libbeat/common/transport.NewClientWithDialer` with a `Config` object as the second argument instead.
- If you were calling `libbeat/outputs/transport.Dial` with a `*Config` object as the first argument, you must now call `libbeat/common/transport.Dial` with a `Config` object as the first argument instead.

## Checklist

- [x] My code follows the style guidelines of this project
- ~[ ] I have commented my code, particularly in hard-to-understand areas~
- ~[ ] I have made corresponding changes to the documentation~
- ~[ ] I have made corresponding change to the default configuration files~
- ~[ ] I have added tests that prove my fix is effective or that my feature works~

## Related issues

- Closes elastic/beats#16728 
- Required for elastic/beats#16150
- Required for https://github.com/elastic/apm-server/issues/3416

### CODE REVIEW

**Comment by urso** [comment]
Looks like we need to rebase.

This is an API breaking change, as a many things got moved that other code (also community code) might rely upon. Please add a developers changelog. Would be nice to include some 'Developer Change' section in the PR description giving some instructions on what needs to be done to adapt existing code to the changes.

ping @elastic/apm-server

**Comment by ycombinator** [comment]
> Looks like we need to rebase.

Done!

> This is an API breaking change, as a many things got moved that other code (also community code) might rely upon. Please add a developers changelog. 

Added in b80a8f5cc3714fd60ee59444c536c4a33a54366b.

> Would be nice to include some 'Developer Change' section in the PR description giving some instructions on what needs to be done to adapt existing code to the changes.

Done, PR description updated.

> ping @elastic/apm-server

I created https://github.com/elastic/apm-server/issues/3416 as well.

**Comment by ycombinator** [comment]
@urso This is ready for re-review, when you get a chance. Thanks!

**Comment by ycombinator** [comment]
@urso Just want to clarify something — even though this is a developer breaking change, we want to backport this to `7.x`, correct? We'll need it for the larger ES output refactoring PR.

**Comment by urso** [comment]
> Just want to clarify something — even though this is a developer breaking change, we want to backport this to 7.x, correct? We'll need it for the larger ES output refactoring PR.

TBH, tough call :)
But if we want to push forward with the output changes, in order to make the output properly reloadable it is a must to backport.

One option for 7.x is to add 'compatbility' with existing code by introducing aliases (this use case is exactly why aliases have been introduced in go in the first place).

**Comment by ycombinator** [comment]
Okay, sounds good. I will setup a backport PR (once this PR is merged) but amend it to include aliases from the old => new exported symbols.

**Comment by ycombinator** [comment]
Jenkins CI failures are unrelated (they are also seen on `master` builds) and Travis CI is green. Merging.

**Pull request merged**
