### PR TITLE
Cherry-pick #9869 to 6.x: Handle IPv6 zone id in IIS filebeat ingest pipeline

### PR DESCRIPTION
**Pull request by jsoriano**
Cherry-pick of PR #9869 to 6.x branch. Original message: 

Possible workaround for #9836, this may be needed in other modules if other services also log IPv6 addresses with zone id.

Wait for https://github.com/elastic/elasticsearch/issues/37107 before deciding what to do about this.

### CODE REVIEW

**Comment by ruflin** [comment]
I think the CI failures are related. You need to regenerate the iis expected files as they look a bit different in 6.x then 7.

**Comment by jsoriano** [comment]
Expected JSON regenerated

**Comment by jsoriano** [comment]
jenkins, test this

**Comment by jsoriano** [comment]
jenkins, test this

**Pull request merged**
