### PR TITLE
Update gosputil to build and work under macOS Monterey 12.1

### PR DESCRIPTION
**Pull request by ph**
## What does this PR do?

Fix issues when compiling beats under macOS 12.1 Monterey.

Remove these errors:

```
# github.com/shirou/gopsutil/disk
iostat_darwin.c:28:2: warning: 'IOMasterPort' is deprecated: first deprecated in macOS 12.0 [-Wdeprecated-declarations]
/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/IOKit.framework/Headers/IOKitLib.h:132:1: note: 'IOMasterPort' has been explicitly marked deprecated here
# github.com/shirou/gopsutil/cpu
../../../go/pkg/mod/github.com/shirou/gopsutil@v3.20.12+incompatible/cpu/cpu_darwin_cgo.go:13:5: warning: 'TARGET_OS_MAC' is not defined, evaluates to 0 [-Wundef-prefix=TARGET_OS_]
exec: go run /Users/ph/src/beats/x-pack/metricbeat/scripts/msetlists/main.go
```

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas ~~
-  ~~[ ] I have made corresponding changes to the documentation~~
-  ~~[ ] I have made corresponding change to the default configuration files~~
-  ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
-  ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by ph** [comment]
Sadly it seems to bring a few more dependencies, all of them with approved license.

**Review by fearful-symmetry — APPROVED** [review]

**Comment by fearful-symmetry** [comment]
I think we've allowed ourselves to merge without E2E in the past, assuming it's unrelated.

**Pull request merged**
