### PR TITLE
Set shard count to 1 in all default configs

### PR DESCRIPTION
**Pull request by tsg**
This reimplements #7091.

We already set shards to 1 in our Metricbeat and Heartbeat configurations, but we were
explicitly setting it to 3 in the other configs. I changed to be 1 everywhere. I went
for a change that still contains the number of shards in the Beat config, rather than
just rely on the ES default, so that Beats 7.0 behave the same even when talking to ES 6.x.

### CODE REVIEW

**Comment by ph** [comment]
Functionbeat and journalbeat are missing from the changes?

**Comment by webmat** [comment]
Isn't Elasticsearch's default moving to 1 as well? Why are we duplicating this default here?

It's ok to have the config option to override it, of course. But why duplicate the effort setting this default? Also, does Beats try to match the default value of the Elasticsearch cluster it talks to? (Beats 6 setting up on ES 7, or the reverse)

**Comment by tsg** [comment]
@webmat There was a discussion on that topic, in the end, @urso's preference is to have the same number of shards regardless of whether we speak to ES6 or ES7. That's why we explicitly set it.

**Comment by tsg** [comment]
@ph They didn't have explicit settings for that before, and I did mostly find and replace. I added them explicitly now, assuming that's what we want for those two as well.

**Pull request merged**
