### PR TITLE
Registry file fsync improvements

### PR DESCRIPTION
**Pull request by urso**
- Return error if Sync fails
- Execute fsync on new parent directory
- improve metrics:
  - registrar.writes.total: total number of registry write attempts
  - registrar.writes.fail: total number of failed write attempts
  - registrar.writes.success: total number of successfull write attempts

Resolves: #6792 (followup for #6877)

### CODE REVIEW

**Comment by ruflin** [comment]
There is a clean_inactive failure on travis. Not sure if it is related: https://travis-ci.org/elastic/beats/jobs/374064172

**Comment by urso** [comment]
The tests did succeed on jenkins. I wonder if the extra fsyncs change some timings, making some tests more flaky.

**Comment by ph** [comment]
@urso more flaky maybe, we will need a bit more iteration to find out. Did you restart the failings tests on travis?

**Comment by urso** [comment]
@ph yes, I did restart the test. Now it's green :) . Related beats-ci tests have been green.

**Comment by ph** [comment]
@urso I will merge this, lets keep an eye out if this test is still flaky, I've seen it fails before :)

**Comment by ruflin** [comment]
Should we backport this one?

**Comment by rockybean** [comment]
When will this pr release? in 6.3? We actually met this kind of problem in our production environment. Though we can solve by deleting the registrar file, but as a result, filebeat will read old files once again. This is terrible.

**Pull request merged**
