### PR TITLE
Fix k8s watcher issue when node access to list nodes and ns

### PR DESCRIPTION
**Pull request by ChrsMark**
## What does this PR do?
This PR changes Pod's metadata initialisation process so as not to fatally fail when node's or namespace's objects are not accessible via k8s api. Instead we only log an `ERROR`.

## Why is it important?
So as not to fail when users do not have permission to `watch` nodes and namespaces in a cluster.
Default manifests of Metricbeat provide `watch` access by default: https://github.com/elastic/beats/blob/f5df6407be1832eb7f1ab726861dc4cbb9d01023/deploy/kubernetes/metricbeat-kubernetes.yaml#L241

## Related issues

- Closes https://github.com/elastic/beats/issues/22683

### CODE REVIEW

**Review by jsoriano — COMMENTED** [review]
Looks good, but we would need a changelog entry mentioning the fix.

And, do we have any test with the the pod metadata generator initialized without node and namespace generators? If not maybe we should add one.

Thanks!

**Comment by ChrsMark** [comment]
Thanks @jsoriano ! Do we really need a changelog for this? This one targets to fix an issue introduced at https://github.com/elastic/beats/pull/22189 which will be landed in `7.11`.

Regarding tests, Pod meta generator is covered by tests at https://github.com/elastic/beats/blob/95a88a6ed7f0c175175a1d3772a63c6e8d313437/libbeat/common/kubernetes/metadata/pod_test.go#L36 and there are tests with and without nodeMeta and namespaceMeta. Do you think this should be enough or we should add tests for the wrapper `GetPodMetaGen` too?

**Comment by jsoriano** [comment]
> This one targets to fix an issue introduced at #22189 which will be landed in `7.11`.
> 

Oh ok, I was thinking that 7.10 was also affected by this, good to go then.

> Regarding tests, Pod meta generator is covered by tests at
> 
> https://github.com/elastic/beats/blob/95a88a6ed7f0c175175a1d3772a63c6e8d313437/libbeat/common/kubernetes/metadata/pod_test.go#L36
> and there are tests with and without nodeMeta and namespaceMeta. Do you think this should be enough or we should add tests for the wrapper `GetPodMetaGen` too?

Oh ok, I think this is enough :+1:

**Review by jsoriano — APPROVED** [review]
:+1:

**Pull request merged**
