### PR TITLE
Cherry-pick #20576 to 7.x: Build docker images based on Red Hat UBI

### PR DESCRIPTION
**Pull request by jsoriano**
Cherry-pick of PR #20576 to 7.x branch. Original message: 

## What does this PR do?

Add an additional docker build that builds images based on Red Hat UBI, following [Red Hat requirements for certified images](https://redhat-connect.gitbook.io/partner-guide-for-red-hat-openshift-and-container/program-on-boarding/technical-prerequisites).

Additional checks have been added to packaging tests for labels and licenses.

Additional changes done to support it also in Elastic Agent images:
* Apply #20356 and #18873 to agent Dockerfile.
* Explicitly select a Dockerfile and entry point template, selecting it based on the image name is error prone, as our image names can have suffixes (`-oss`, `-ubi8`...).
* Add `NOTICE.txt` file to all agent packages.
* Actually run package tests after building packages, added flag to allow root user.
* Improved checks on required packages, so they are not always built, what significantly speeds up local builds.

**NOTE**: Some of the changes for Elastic Agent could be actually moved to separate PRs, but they are quite intertwined and I would like to test them together. I decided to do them on this PR to don't have to conditionally disable package tests, and to be able to test everything together. But happy to move them to other PRs if preferred.

## Why is it important?

To build images that can be certified for Red Hat OpenShift.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [x] Move licenses to `/licenses`
  - [x] Add the proper licenses to x-pack and OSS images
- [x] Add labels
- [x] Add test to check that licenses are in place
- [x] Add test to check that required labels are present
- [x] Add build for Elastic Agent

Possibly to be done in a follow up PR
- [ ] Refactor how files are prepared and copied, so it is not needed to change permissions in Dockerfile
- [ ] Unify Dockerfiles for Agent and the rest of beats, as they are quite similar
- [ ] Add checks for the included packages in Agent image

### CODE REVIEW

**Review by michalpristas — APPROVED** [review]
backport looks ok

**Comment by jsoriano** [comment]
Failing tests are not related to this change, they are also failing in 7.x branch, merging.

**Comment by jsoriano** [comment]
Failing tests are caused by https://github.com/elastic/beats/issues/20716

**Pull request merged**
