### PR TITLE
Add ip address of containers to event

### LINKED ISSUE #5282: Get Container IPAddress
Hi guys，
    we have a specical requirement, It's that get the IPAddress of container under the swam cluster,
and i change the code, such as：
    open  the file, beats/metricbeat/module/docker/container/data.go:
```
func eventMapping(cont *dc.APIContainers) common.MapStr {
        event := common.MapStr{
                "created": common.Time(time.Unix(cont.Created, 0)),
                "id":      cont.ID,
                "name":    docker.ExtractContainerName(cont.Names),
                "command": cont.Command,
                "IPAddres": cont.Networks,
                "image":   cont.Image,
                "size": common.MapStr{
                        "root_fs": cont.SizeRootFs,
                        "rw":      cont.SizeRw,
                },
                "status": cont.Status,
        }
```
your will be see the ipaddress in the container info schema.

### PR DESCRIPTION
**Pull request by liketic**
Closes #5282

### CODE REVIEW

**Comment by ruflin** [comment]
@liketic Thanks for the contribution. Could you add a CHANGELOG entry?

**Comment by ruflin** [comment]
jenkins, test it

**Comment by liketic** [comment]
@ruflin Thanks for reviewing this one. I rebased it. Thanks.

**Comment by ruflin** [comment]
jenkins, test it

**Comment by ruflin** [comment]
@liketic Thanks for the rebase. Tried to do a "Github commit" myself to fix the issue but a rebase is much nicer.

**Comment by liketic** [comment]
Hi @ruflin Is this mergeable ? 😄

**Comment by exekias** [comment]
Thank you for your contribution @liketic! :tada:

**Pull request merged**
