### PR TITLE
Replace proc.cpu.user_p with proc.cpu.total_p

### PR DESCRIPTION
**Pull request by monicasarbu**
Fixes https://github.com/elastic/beats/issues/631

### CODE REVIEW

**Comment by andrewkroh** [comment]
Since we have the data available to truly calculate `proc.cpu.user_p` I think we should calculate it so that Topbeat has both `proc.cpu.user_p` and `proc.cpu.total_p`. Then there would be no perceived loss of functional nor backwards compatibility issues with dashboards.

**Comment by andrewkroh** [comment]
The changes made LGTM.

**Comment by monicasarbu** [comment]
@andrewkroh Yes, indeed we can export both `proc.cpu.user_p` and `proc.cpu.total_p`, but I would prefer to have only one to be similar with what top command displays. One reason is that I am afraid that people will get confuse if topbeat exports two percentages and the top command shows only one. Another reason is that I prefer to keep the data that we export to the minimum. To fix the second concern, we could add another config option that decides when to export proc.cpu.user_p ... What are your thoughts?

**Comment by andrewkroh** [comment]
Ok. I don't think I would bother with the config option. As long as we document the breaking change to the schema, users should be able to update any custom dashboards.

**Comment by dedemorton** [comment]
@monicasarbu The screen captures in the getting started doc also need to be updated to reflect the name change: https://www.elastic.co/guide/en/beats/topbeat/current/topbeat-getting-started.html.

Should I open a doc issue to remind me to do this, or do you want to do a quick screen grab and add it yourself? I'm not sure my data will be as interesting as your data. :-)

**Pull request merged**
