### PR TITLE
fix typos in reference config files, add default value for loadbalance

### PR DESCRIPTION
**Pull request by DdPerna**

### CODE REVIEW

**Comment by exekias** [comment]
Thanks for contributing @DdPerna! could you please sign the CLA?

**Comment by ruflin** [comment]
jenkins, test it

**Comment by ruflin** [comment]
@DdPerna Thanks for the contribution.

**Comment by andrewkroh** [comment]
Thanks @DdPerna! I was surprised to see how many issues those files accumulated over time.

**Pull request merged**
