### PR TITLE
packetbeat/{beater,npcap}: prevent panic when querying Npcap version and perform install before all other work

### LINKED ISSUE #30820: packetbeat/{beater,npcap}: install and first run on Windows 10 results in failure
Please post all questions and issues on https://discuss.elastic.co/c/beats
before opening a Github Issue. Your questions will reach a wider audience there,
and if we confirm that there is a bug, then you can open a new issue.

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 8.1
- Operating System: Windows 10
- Steps to Reproduce:
    1. install packetbeat
    2. run packetbeat with `packetbeat -e -d *`.

This results in one of two errors.

1. "Exiting: Error getting devices list: Can't get list of interfaces: PacketGetAdapterNames: The system cannot find the path specified. (3)"
2. "Error getting devices list: couldn't load wpcap.dll"

### PR DESCRIPTION
**Pull request by efd6**
## What does this PR do?

This fixes a crash on Windows 10 when running Packetbeat.

## Why is it important?

The bug block all functionality on that platform.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

This needs to be tested on a Windows 10 machine. I used StefanScherer/windows_10 with the beats Vagrantfile. Build x-pack/packetbeat with `go build` and run with `.\packetbeat -e -d *`. Check `C:\Program Files` for the presence of the Npcap installation directory. Without this fix, no install will result; after this fix a new installation will be present on exit (packetbeat will still exit with an error unless a network interface is setup on the VM).

## Related issues

- Closes #30820.

### CODE REVIEW

**Review by adriansr — APPROVED** [review]
LGTM

I guess the reason this wasn't caught in early testing is that there must have been a wpcap.dll file in the system, from a previous npcap / winpcap install.

**Comment by efd6** [comment]
I suppose so. It's not wildly satisfying though. Thanks for taking a look. I'll wait also for @andrewkroh.

**Review by andrewkroh — APPROVED** [review]
I think we should spend some time setting up some smoke tests that execute the binary on Windows (like https://github.com/elastic/beats/commit/b4888fb1452be7d9b22d1c8308049464f37b2404).

**Comment by efd6** [comment]
@andrewkroh PTAL

**Pull request merged**
