### PR TITLE
Upgrade go-ucfg to v0.8.1 release

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Updates the vendored go-ucfg to v0.8.1.

**Note**: This includes a breaking change that removes the variable substition from environment variables when they are read from the configuration. https://github.com/elastic/go-ucfg/issues/139

## Why is it important?

Gets the latest fixes and additions including:

### Added
- Add support for HJSON. https://github.com/elastic/go-ucfg/issues/131
- Add new parse.Config to adjust parsing of varibles returned by a Resolve. https://github.com/elastic/go-ucfg/issues/139
- Add call to InitDefaults when map, primitives, or structs implement Initializer interface during Unpack. https://github.com/elastic/go-ucfg/issues/104

### Changed
- Moved internal/parse to parse module. https://github.com/elastic/go-ucfg/issues/139
- Add parse.Config to resolvers return. https://github.com/elastic/go-ucfg/issues/139

### Fixed
- Prevent Validate from being called when value is a pointer or interface and is nil. https://github.com/elastic/go-ucfg/issues/144
- Call Validate on custom slice types. https://github.com/elastic/go-ucfg/issues/133
- Call Validate on custom map types. https://github.com/elastic/go-ucfg/issues/136
- Disabled object parsing of environment variables. https://github.com/elastic/go-ucfg/issues/139
- Apply validation to defaults passed into Unpack when Config doesn't contain a value. https://github.com/elastic/go-ucfg/issues/42

## Checklist

- [X] My code follows the style guidelines of this project
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [X] I have added tests that prove my fix is effective or that my feature works

## Author's Checklist

- [X] Does not break beats reading and parsing configuration files

## Related issues

-

### CODE REVIEW

**Comment by kvch** [comment]
I meant updating all entries in the vendor.json, not just the top-level one. For example, github.com/elastic/go-ucfg/cfgutil, github.com/elastic/go-ucfg/flag, etc.

**Comment by blakerouse** [comment]
@kvch I have used `govendor` and `make notice` to update the required files. I have also added the changelog entry and fixed the pull request description to link to the go-ucfg project pulls instead of old ones from beats.

**Comment by kvch** [comment]
The other packages from `github.com/elastic/go-ucfg` I have mentioned above are still not updated in vendor.json.

**Comment by blakerouse** [comment]
@kvch updated with govendor done correctly this time

**Pull request merged**
