### PR TITLE
Fix missing period in setup.dashboards.always_kibana

### PR DESCRIPTION
**Pull request by mattayes**

### CODE REVIEW

**Comment by mattayes** [comment]
Hi folks, I signed the CLA a few minutes ago.

**Comment by ruflin** [comment]
jenkins, test this

**Comment by mattayes** [comment]
It looks like there's an unrelated test failure with `libbeat`'s Kafka test installation process:

https://travis-ci.org/elastic/beats/jobs/512186112
https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/6504/beat=libbeat,label=linux-immutable/console

**Comment by ruflin** [comment]
@mattayes Yes, test failure was unrelated.

**Comment by mattayes** [comment]
Thanks for merging @ruflin! :rocket:

**Comment by ruflin** [comment]
@dedemorton Could you take care of the forward ports?

**Pull request merged**
