### PR TITLE
x-pack/filebeat/input/cel: add support for partial evaluation debug logging

### PR DESCRIPTION
**Pull request by efd6**
## Proposed commit message

See title.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

Run `go test -v -run TestInput/debug` in the cel package. You should see the logs for the test, including a line like so
```
{"log.level":"debug", ... ,"log.logger":"cel_test.cel_debug"," ... ,"message":"DEBUG", ... ,"tag":"partial sum","value":5, ...}
```
for the happy path test and like so
```
{"log.level":"debug", ... ,"log.logger":"cel_test.cel_debug", ... ,"message":"ERROR", ... ,"tag":"divide by zero","error":{"message":"division by zero"}, ...}
```
for the error path test.

The surprising field rename from "value" to "error" that is not explainable from the code in this change is undocumented pixie dust from zap. I guess it's OK.

## Related issues

- Depends #36651

### CODE REVIEW

**Review by kcreddy — APPROVED** [review]
LGTM 👍🏼 
I guess there is no easy way to create unit test if log is being produced with the specified `tag` ?

**Comment by efd6** [comment]
The logging behaviour is hard to test here, but is tested in the library. elastic/mito#40 (testdata/debug.txt)

**Pull request merged**
