### PR TITLE
Backport #12284 to 7.2: Import ECS 1.0.1

### PR DESCRIPTION
**Pull request by webmat**
Backport of #12284 to 7.2. Original message:

This is a patch release of ECS, as it only contains minor fixes, mostly field formatting, and examples for a few fields. No new fields in this release.

The killer feature of ECS 1.0.1 is https://github.com/elastic/ecs/pull/454. This change will make pivoting around numeric values such as port numbers & PIDs much more streamlined, as it will prevent Kibana from adding thousands separators.

I'm hoping we can backport this to 7.2, as I think it fits really well with the introduction of the SIEM app.

### CODE REVIEW

**Comment by webmat** [comment]
@ruflin I'm confused. What does this have to do with this PR? :-)

**Comment by webmat** [comment]
Ah you mean the Golang generated code. You're right. 🤦‍♂

**Comment by webmat** [comment]
I won't have time to pick that up. A Beats dev should do that part.

**Comment by ruflin** [comment]
I think it's important that we ship both at the same time (single PR) as otherwise we have an inconsistency between definition and what we ship as part of each event.

@cwurm Could you pick this up? We also must fix "master" as it slipped through there.

**Comment by webmat** [comment]
@ruflin Agreed.

**Comment by cwurm** [comment]
PR for fixing it in master: https://github.com/elastic/beats/pull/12317

**Comment by webmat** [comment]
This didn't make it. Closing

**Pull request closed without merging**
