### PR TITLE
[DOCS] Add 7.1, 7.2, 7.3, and 8.0 breaking changes files

### PR DESCRIPTION
**Pull request by dedemorton**
Adds 8.0 and 7.3 breaking changes. The files will not be hooked up to the navigation until we have an 8.x and 7.3 branches. 

Also forward ports changes added in https://github.com/elastic/beats/pull/12326 and https://github.com/elastic/beats/pull/12322.

This PR must be merged at the same time as https://github.com/elastic/stack-docs/pull/350

### CODE REVIEW

**Comment by lcawl** [comment]
Would it save time to create a 7.3.0 page for the 7.x branch now too?

**Comment by lcawl** [comment]
FYI in other products' docs we don't include the 7.* release notes or highlights or breaking changes in the 8.* books. e.g. https://www.elastic.co/guide/en/elasticsearch/reference/master/breaking-changes.html
Just mentioning in case you want to omit the 7.* pages. If that's not feasible because of the merge strategy in this repo, that's fine.

**Comment by dedemorton** [comment]
> Just mentioning in case you want to omit the 7.* pages. If that's not feasible because of the merge strategy in this repo, that's fine.

Yes, that's exactly why I'm including the 7.x pages. I don't want to mess up the automerge from master > 7.x.

**Comment by dedemorton** [comment]
@lcawl I've added the 7.3 file, too.  Once we create an 8.x branch, we can clean out the 7.x files, but for now, let's keep all the 7.x files in master so the merge is simpler.

**Pull request merged**
