### PR TITLE
Add example dashboards using the time series visual builder

### PR DESCRIPTION
**Pull request by monicasarbu**
Replace https://github.com/elastic/beats/pull/3981. 

Several improvements are done to the Metricbeat system dashboards:
- [x] change navigation to be on top of the page in order to occupy less space
- [x] add two dashboards that are using the widgets built with the new time series visual builder 
- [x] re-arrange the old dashboards to accommodate the new navigation bar 

Here are a few screenshots with the result:

screen shot 2017-04-26 at 1 46 59 pm

screen shot 2017-04-26 at 1 47 13 pm

cc-ed: @simianhacker

### CODE REVIEW

**Comment by andrewkroh** [comment]
Why is there a "Top 10 hosts by CPU" table on the host overview dashboard? Maybe this should be processes instead.

**Comment by monicasarbu** [comment]
@andrewkroh That's a good question. The second screenshot is a dashboard that shows system details per host. By default, it shows the details for all the hosts, but you can select a host by clicking on one host from the "top 10 hosts" widget. This way, you can easier have a per host view. This is a temporary workaround until we have links between dashboards.

**Comment by andrewkroh** [comment]
Ok, makes sense. I use a tag cloud of hostnames for a similar purpose.

**Comment by andrewkroh** [comment]
With the "alpha2" tag here, do you want to hold off the merge until after alpha1 is released?

**Pull request merged**
