### PR TITLE
Update testing env 6.8.11

### PR DESCRIPTION
**Pull request by cachedout**
## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by cachedout** [comment]
I am waiting to merge this until we [get clarification on this](https://github.com/elastic/beats/pull/19670#issuecomment-654350053).

**Comment by urso** [comment]
LGTM. This is the state the 6.8 branch should have been in. After release 6.8.11 we bump the versions to 6.8.12. This requires us to update the snapshot.yml

After release of 7.8.1 we should update latest.yml.

**Comment by cachedout** [comment]
> This is the state the 6.8 branch should have been in. 

@urso I am a bit confused by this comment. This PR is being submitted against the 6.8 branch. Are you saying that the changes in this PR should have been applied earlier? Is this safe to merge now?

**Comment by urso** [comment]
> Are you saying that the changes in this PR should have been applied earlier?

Yes

> Is this safe to merge now?

Yes

**Pull request merged**
