### PR TITLE
Update elastic-agent-system-metrics

### PR DESCRIPTION
**Pull request by fearful-symmetry**
## Proposed commit message

Update elastic-agent-system-metrics to bring in the fix for https://github.com/elastic/elastic-agent-system-metrics/pull/129

### CODE REVIEW

**Comment by fearful-symmetry** [comment]
I...think the CI errors are unrelated?

**Comment by pierrehilbert** [comment]
Doesn't seem to be related! @pazone are those failures something you are aware of?

**Comment by pierrehilbert** [comment]
@fearful-symmetry should we continue with https://github.com/elastic/beats/pull/38229 ?

**Comment by fearful-symmetry** [comment]
@pierrehilbert Oops, forgot about dependabot!

**Pull request closed without merging**
