### PR TITLE
Fix mysql slowlog parser

### PR DESCRIPTION
**Pull request by tsg**
The IP grok expression was bogus.

### CODE REVIEW

**Comment by liuhuang9492** [comment]
@ruflin  I have changed the file filebeat/module/mysql/slowlog/ingest/pipeline.json ，but I foud the error in kibana web . I have install filebeat rpm package. So Can I help me ? mysql 5.6.25 slow_log

> # User@Host: sns[sns] @  [10.10.10.10]  Id: 4921654
# Query_time: 1.611364  Lock_time: 0.000059 Rows_sent: 0  Rows_examined: 1842248
SET timestamp=1494413943;
UPDATE report SET deleted_at = '2017-05-10 18:59:02' WHERE type= '123' AND source = '2222';

**Comment by liuhuang9492** [comment]
@ruflin  I have changed the file filebeat/module/mysql/slowlog/ingest/pipeline.json , but the error:

Provided Grok expressions do not match field value: [# User@Host: sns[sns] @  [10.232.64.105]  Id: 4921654\n# Query_time: 1.611364  Lock_time: 0.000059 Rows_sent: 0  Rows_examined: 1842248\nSET timestamp=1494413943;\nUPDATE report SET deleted_at = '2017-05-10 18:59:02' WHERE type= 'circle_article' AND source = '12224222';]

and I install filebeat rpm package . mysql 5.6.23 . Can you help me？what I shuold do. thanks.

**Comment by ruflin** [comment]
@liuhuang9492 This fix is not release yet. The fix is currently only available in the 6.0.0-alpha1 releases (see tab Preview Release here: https://www.elastic.co/downloads/beats/filebeat) or  in the nightly builds: https://beats-nightlies.s3.amazonaws.com/index.html?prefix=filebeat/

**Comment by presto9292** [comment]
Faced same issue as @liuhuang9492
Just editing pipeline.json is not enough, need to delete the previously loaded pipeline definition in ES as well - then it works

**Pull request merged**
