### PR TITLE
Add support for PostgreSQL Extended Queries(issue #78)

### PR DESCRIPTION
**Pull request by MingchunZhao**
I've dealt with PostgreSQL extended queries via JDBC Driver.

### CODE REVIEW

**Comment by MingchunZhao** [comment]
I am just working on fixing conflicts, will commit again.

**Comment by tsg** [comment]
Hi @MingchunZhao, I'm very happy to see this enhancement! Before we can review, can you make sure you signed the [CLA](http://www.elasticsearch.org/contributor-agreement/), please?

**Comment by tsg** [comment]
@MingchunZhao Never mind, I could check that you signed the CLA already. Thanks!

**Comment by MingchunZhao** [comment]
@tsg Thanks! Let me fix that conflicts first,  will commit again.

**Comment by urso** [comment]
LGTM. Unfortunately parser has changed quite a lot since.

**Comment by MingchunZhao** [comment]
@urso, Yes, I realized that it would be a good work   for me:-)

**Comment by urso** [comment]
Looks like we've been working on pgsql parser at about the same time.

Merging would be easiest by splitting up the different parsing-blocks into separate functions before trying to rebase. On rebase move functions to parser.go and required adjustments should be minimal. Just ping me if you have any troubles.

**Comment by MingchunZhao** [comment]
Thank you so much!

**Pull request closed without merging**
