### PR TITLE
libbeat: add support for defining analyzers in-line in fields.yml files

### LINKED ISSUE #28540: [libbeat] Support custom analyzers in fields.yml
**Describe the enhancement:**

Fields.yml fields currently support using the [built-in analyzers](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-analyzers.html) on `text` fields. But it's not possible to declare a [custom analyzer](https://www.elastic.co/guide/en/elasticsearch/reference/current/analysis-custom-analyzer.html) in fields.yml and have it installed as part of the index settings in the index template.

**Describe a specific use case for the enhancement or feature:**

Using a custom `analyzer` or `search_analzyer` for `text` fields in fields.yml. This will give users a better experience when searching data indexed by Beats.

### PR DESCRIPTION
**Pull request by efd6**
## What does this PR do?

This adds support for defining custom text analyzers in fields.yml files. For example:
```
- key: powershell
  title: PowerShell module
  description: >
    These are the event fields specific to the module for the Microsoft-Windows-PowerShell/Operational and Windows PowerShell logs.
  release: beta
  analyzer:
    powershell_script_analyzer:
      type: pattern
      pattern: "[\\W&&[^-]]+"
  fields:
  ...
```

## Why is it important?

Not being able to define custom analyzers is a blocker for processing some documents containing syntactically meaningful non-standard token structures (for example captured script text as shown above).

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

No specific recommendations.

## How to test this PR locally

Running `go test` in the relevant packages tests this change.

## Related issues

- Closes #28540
- Relates #28483
- Relates elastic/integrations#1931

## Use cases

Use case is shown above.

## Screenshots

N/A

## Logs

N/A

### CODE REVIEW

**Comment by efd6** [comment]
It's not obvious to me where documentation for this should go. So suggestions welcomed.

**Comment by andrewkroh** [comment]
> It's not obvious to me where documentation for this should go. So suggestions welcomed.

~Personally if I were looking for info on how to use it I would be reading the `Field` struct or the `Analyzer` struct so I suggest some godocs in one of those places.~

Now I also see we have docs in https://www.elastic.co/guide/en/beats/devguide/current/event-fields-yml.html. That's probably what most contributors read rather than reading Go source.

**Review by andrewkroh — APPROVED** [review]
LGTM

**Comment by efd6** [comment]
> Now I also see we have docs in https://www.elastic.co/guide/en/beats/devguide/current/event-fields-yml.html.

That's perfect. Thanks.

> That's probably what most contributors read rather than reading Go source.

:sadpanda:

**Comment by efd6** [comment]
@andrewkroh PTAL for docs.

**Review by andrewkroh — APPROVED** [review]
LGTM

**Pull request merged**
