### PR TITLE
Add missing config options to Logstash section of reference.yml

### LINKED ISSUE #3062: Mismatch between documentation and `filebeat.full.yml` and missing settings
There could possibly be more inconsistencies in default valuess but these are the ones I spotted for Logstash output:

- `#loadbalance: true` inside `filebeat.full.yml` while the [documentation](https://www.elastic.co/guide/en/beats/filebeat/current/logstash-output.html#loadbalance) mentions a default value of `false`
- missing defaults from `filebeat.full.yml`: `port`, `timeout`, `max_retries`, `bulk_max_size`

### PR DESCRIPTION
**Pull request by dedemorton**
Closes #3062 

A couple of open issues:

- [x] So do we want to remove the deprecation statement under `port` in the [reference docs](https://www.elastic.co/guide/en/beats/filebeat/current/logstash-output.html#port)? (NO)
- [x] The [reference docs](https://www.elastic.co/guide/en/beats/filebeat/current/logstash-output.html#port) say that the default setting for `port` is 10200, but the [code here](https://github.com/elastic/beats/blob/master/libbeat/outputs/logstash/config.go#L50) says 5044.  I'll change it in the reference docs (assuming I'm reading the code correctly...let me know). (Fixed docs.)

### CODE REVIEW

**Comment by urso** [comment]
> So do we want to remove the deprecation statement under port in the reference docs?

No. We should add the deprecation notice to the config file. Setting will be removed in 7.0

>  The reference docs say that the default setting for port is 10200, but the code here says 5044. I'll change it in the reference docs (assuming I'm reading the code correctly...let me know).

10200 is actually correct. It's the one used in code. But for some reason we started documenting 5044 about everywhere. We will change the default to 5044 in beats.

**Comment by urso** [comment]
Checking the code we did change the default to 5044 at some point.

**Comment by dedemorton** [comment]
Actually, since `port` is deprecated, we should not add it to the reference.yml since we say the following at the top of that file:

```
# This file is a full configuration example documenting all non-deprecated
# options in comments. For a shorter configuration example, that contains only
# the most common options, please see filebeat.yml in the same directory.
```

**Comment by dedemorton** [comment]
@urso This should be ready for a final review.

**Pull request merged**
