### PR TITLE
Add missing allowed syscalls for coreos

### PR DESCRIPTION
**Pull request by amencarini**
While testing the changes made with https://github.com/elastic/beats/pull/9994 on our Kubernetes/CoreOS setup we were getting `error while waiting for event: operation not permitted` lines logged. Adding these syscalls to the whitelist allowed us to avoid the error while enjoying continued logging after a journald rotation.

cc @kvch

### CODE REVIEW

**Comment by kvch** [comment]
Thank you! How did you test these syscalls?
I have opened a PR with more to the whitelist yesterday: https://github.com/elastic/beats/pull/10593
I seem to have more syscalls than you. :D

**Comment by kvch** [comment]
Also, were you able to read entries after logrotation or after starting Journalbeat?

**Comment by amencarini** [comment]
We found out the relevant syscalls by using a combination of strace and checking the C code of systemd! I've closed this PR as yours is definitely more comprehensive 😆 Just tested it and after forcing a rotation logs are still shipped 🎉

**Comment by kvch** [comment]
What systemd version do you have?

**Comment by amencarini** [comment]
233

**Pull request closed without merging**
