### PR TITLE
Revert "Adding inforamtion for CRI-O configuration and enhancing our …

### PR DESCRIPTION
**Pull request by bmorelli25**
https://github.com/elastic/beats/pull/32151 was merged with a failing doc build and needs to be reverted to fix the build.

This reverts commit c47ef26637466f10ed9cf3b28bfda38b83052cae.

### CODE REVIEW

**Comment by ollyhowell** [comment]
Brandon is reverting as this change broke the docs build - see https://elastic.slack.com/archives/C0JF80CJZ/p1657550460466379

**Comment by dedemorton** [comment]
Curious why we are reverting rather than fixing the error.

**Comment by dedemorton** [comment]
Repacled by https://github.com/elastic/beats/pull/32308

**Comment by bmorelli25** [comment]
> Curious why we are reverting rather than fixing the error.

Because I didn't have time to fix it before going AFK. A fix is much better. Thanks!

**Pull request closed without merging**
