### PR TITLE
Fix import_dashboards script name on Windows

### PR DESCRIPTION
**Pull request by tsg**
Needs the `.exe` extension to be correctly treated as a binary.

### CODE REVIEW

**Comment by tsg** [comment]
jenkins, package it

**Comment by monicasarbu** [comment]
LGTM, waiting for green

**Comment by ruflin** [comment]
LGTM

**Comment by tsg** [comment]
Package tests green: http://build-eu-00.elastic.co/view/Beats/job/beats-package-PR/32/

**Pull request merged**
