### PR TITLE
Fix bug with override path in cgroups

### PR DESCRIPTION
**Pull request by fearful-symmetry**
## What does this PR do?

This is a fix for https://github.com/elastic/beats/issues/27598

In cases where `cgroupsHierarchyOverride` is set to `/`, and `ignoreRootCgroups` is set, we'll just completely bypass any cgroups reporting.

## Why is it important?

It's a bug that was breaking containers.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

- Build metricbeat (or any other beat) for docker
- run on linux
- set `http.enabled` to true in the beat config
- From inside the docker container, do `curl localhost:5066/stats?pretty`
- Make sure cgroup metrics are reported.

## Related issues

- Fixes https://github.com/elastic/beats/issues/27598

### CODE REVIEW

**Comment by ruflin** [comment]
@matschaffer Not before the merge of the PR. But I can build it for you or tell you how to build it ;-)

**Comment by matschaffer** [comment]
@ruflin either way. Pretty sure you also have all the access you need to try to squeeze a build into a test deployment. Since @axw approved maybe we can just wait for the next BC.

**Comment by axw** [comment]
FWIW, I tested this with this small program - ran it before/after changes in a Docker container:

```go
package main

import (
        "fmt"
        "log"

        "github.com/elastic/beats/v7/libbeat/cmd/instance/metrics"
        "github.com/elastic/beats/v7/libbeat/monitoring"
)

func main() {
        if err := metrics.SetupMetrics("testing"); err != nil {
                log.Fatal(err)
        }
        snapshot := monitoring.CollectFlatSnapshot(monitoring.Default, monitoring.Full, false)
        for name, value := range snapshot.Ints {
                fmt.Println(name, value)
        }
}
```

I think we're good, and can just wait for the next BC after this merges.

**Comment by fearful-symmetry** [comment]
Yep, sorry for the delay, once again fighting with CI...

**Comment by fearful-symmetry** [comment]
FINALLY

**Pull request merged**
