### PR TITLE
Merge master into 7.x 2019 06 21

### PR DESCRIPTION
**Pull request by urso**

### CODE REVIEW

**Comment by ph** [comment]
@urso The CLA is failing on this PR, we will need to find out which commit is the problem.

**Comment by ycombinator** [comment]
@urso Not sure if this PR should be pulled in as well: https://github.com/elastic/beats/pull/12637? I put it up to fix `master` CI so I'm wondering if `7.x` CI will fail without it as well?

**Comment by urso** [comment]
@ycombinator let's wait for CI run. 7.x follows master. This also includes docs and developer tools.

**Comment by urso** [comment]
Jenkins, test this.

**Pull request merged**
