### PR TITLE
Remove deprecated field awscloudwatch

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
## Proposed commit message

This PR removes deprecated field `awscloudwatch` in filebeat aws-cloudwatch input. 

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes https://github.com/elastic/beats/issues/41088

### CODE REVIEW

**Review by vigneshshanmugam — APPROVED** [review]
LGTM, Need to update the docs page.

**Comment by vigneshshanmugam** [comment]
@kaiyan-sheng Does it need have backport-8.x label given this be removed only from 9?

**Review by gizas — APPROVED** [review]

**Comment by gizas** [comment]
Indeed make update is needed for the docs.
It is only for 9.0 version right?

**Comment by kaiyan-sheng** [comment]
Yes ahh I need to add the backport skip label on top of removing the backport label 😂 Thanks @vigneshshanmugam and @gizas !

**Review by Kavindu-Dodan — APPROVED** [review]

**Pull request merged**
