### PR TITLE
Fix typo in netflow module docs

### PR DESCRIPTION
**Pull request by rruckley**
## What does this PR do?

Fixes typo in netflow config documentation (s/find/bind/).

## Why is it important?

Sloppy spelling gives bad impression for Elastic.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ x ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by rruckley** [comment]
I have now signed the contributor agreement. All this to fix a typo.

**Comment by rruckley** [comment]
@andrewkroh I've signed the CLA. I would be chuffed if my single character typo fix could make it through the paperwork but I feel like this process is not really set up for such trivial things!

**Comment by marc-gr** [comment]
jenkins run tests

**Comment by marc-gr** [comment]
Thanks for your contribution @rruckley! When changing documentation we need to re-generate some files, you can do so by running `mage fmt update` inside `filebeat` folder and commiting the modified files. Please let us know if you encounter any issue during the process 😄

**Comment by adriansr** [comment]
Also you'll need to point to PR to the `master` branch instead of `7.7`.

**Comment by dedemorton** [comment]
Thanks for catching this! Sorry this easy fix is so complicated. I will apply your commit to master and run `mage fmt update`.

**Comment by rruckley** [comment]
Thank you, I wasn't really looking to become a full developer but it's nice to get these little things fixed.

**Comment by andrewkroh** [comment]
run tests

**Pull request merged**
