### PR TITLE
fix: Allow use of valid Port 0

### PR DESCRIPTION
**Pull request by MarcWort**
## Proposed commit message

Port 0 is a normal but reserved port.
See: https://www.iana.org/assignments/service-names-port-numbers/service-names-port-numbers.xhtml or RFC6335 Section 6

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Use cases

Our internet facing server with Shorewall sometimes logs packets with SPT=0.
These trigger an alarm because of many dropped messages in our monitoring. 

## Logs

```
{"log.level":"debug","@timestamp":"2024-06-24T16:21:53.900+0200","log.logger":"elasticsearch","log.origin":{"function":"github.com/elastic/beats/v7/libbeat/outputs/elasticsearch.(*Client).bulkCollectPublishFails","file.name":"elasticsearch/client.go","file.line":455},"message":"Cannot index event publisher.Event{Content:beat.Event{Timestamp:time.Date(2024, time.June, 24, 14, 21, 53, 112000000, time.UTC), Meta:{\"pipeline\":\"logs-shorewall\",\"truncated\":false}, Fields:{\"agent\":{\"ephemeral_id\":\"6981b9de-7b5c-4058-a9e6-cc33b1ece2c4\",\"id\":\"788b7445-d688-46d8-8c47-e16da00a4f11\",\"name\":\"filebeat\",\"type\":\"filebeat\",\"version\":\"8.13.4\"},\"ecs\":{\"version\":\"8.0.0\"},\"event\":{\"severity\":6},\"host\":{\"name\":\"server123\"},\"input\":{\"type\":\"syslog\"},\"log\":{\"source\":{\"address\":\"192.168.110.104:34265\"}},\"message\":\"Shorewall FORWARD DROP IN=bond1 OUT=bond1 MAC=aa:aa:aa:aa:bb:bb:bb:bb SRC=123.123.123.123 DST=1.2.3.4 LEN=52 TOS=0x00 PREC=0x00 TTL=56 ID=0 DF PROTO=TCP SPT=0 DPT=80 WINDOW=875 RES=0x00 SYN URGP=0 \",\"process\":{\"program\":\"kernel\"},\"syslog\":{\"facility\":0,\"facility_label\":\"kernel\",\"priority\":6,\"severity_label\":\"Informational\"}}, Private:interface {}(nil), TimeSeries:false}, Flags:0x1, Cache:publisher.EventCache{m:mapstr.M(nil)}} (status=400): {\"type\":\"illegal_argument_exception\",\"reason\":\"invalid source port [null]\"}, dropping event!","service.name":"filebeat","ecs.version":"1.6.0"}
```

### CODE REVIEW

**Review by rdner — APPROVED** [review]

**Comment by rdner** [comment]
@MarcWort the test does not pass, could you please fix it?

```
=== FAIL: libbeat/processors/communityid TestRun/invalid_destination_port (0.00s)
    communityid_test.go:85:
        	Error Trace:	/opt/buildkite-agent/builds/bk-agent-prod-gcp-1722602121494028845/elastic/beats-libbeat/libbeat/processors/communityid/communityid_test.go:189
        	            				/opt/buildkite-agent/builds/bk-agent-prod-gcp-1722602121494028845/elastic/beats-libbeat/libbeat/processors/communityid/communityid_test.go:85
        	Error:      	Not equal:
        	            	expected: <nil>(<nil>)
        	            	actual  : string("1:YaVkVTbWUkgn0a2QrblLOEsia9g=")
        	Test:       	TestRun/invalid_destination_port
=== FAIL: libbeat/processors/communityid TestRun (0.00s)
```

**Review by faec — APPROVED** [review]

**Comment by MarcWort** [comment]
Could someone please run the remaining tests to get this done?

**Comment by pierrehilbert** [comment]
run docs-build

**Pull request merged**
