### PR TITLE
[Testing] Disable geoip downloader

### PR DESCRIPTION
**Pull request by andrewkroh**
## What does this PR do?

Disable database updates via an Elasticsearch property `ingest.geoip.downloader.enabled: false`. This will cause Elasticsearch to use the circa 2019 maxmind database version that is embedded. This would work for now, but the embedded database will be removed in 8.x IIUC.

Closes: #25159

## Why is it important?

This prevents our golden file tests from failing everytime the database changes geo or asn values. It also prevents race conditions in tests that might run before the database has been updated or in cases where the downloader service is unavailable.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~[ ] I have made corresponding changes to the documentation~
- ~[ ] I have made corresponding change to the default configuration files~
- ~[ ] I have added tests that prove my fix is effective or that my feature works~
- ~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~

## Related issues

- Closes: #25159

### CODE REVIEW

**Comment by andrewkroh** [comment]
The generator tests are failing. I opened a separate fix for them in https://github.com/elastic/beats/pull/25251.

**Comment by andrewkroh** [comment]
This fix needs backported to 7.x and 7.13. AFAIK neither of those branches have had their golden files updated to work on the new geoip database so those PRs should be much smaller.

**Comment by exekias** [comment]
+1 to this, do you know how often the actual fields change? or perhaps that doesn't happen at all? I'm wondering if we need a way to detect that situation to update mappings

**Comment by andrewkroh** [comment]
Field mapping changes would only change when Elasticsearch modifies the `geoip` processor. The geoip processor interacts with the raw database data so it should isolate us from DB schema changes should they be implemented by MaxMind. And according to MaxMind the database data updates ~weekly.

**Comment by andrewkroh** [comment]
run tests

**Review by jsoriano — APPROVED** [review]
:+1:

**Pull request merged**
