### PR TITLE
Fcgi - devel

### PR DESCRIPTION
**Pull request by patricio-dorantes**
Hi i red that if I'm intending to help with some code is advisable to start early with a pull request. I'm making an early request although my code doesn't make much in case you guys got comments for me. 

If you are short on time to check out on this stage of code I'll glad to carry on on a functional fcgi protocol dissector. 

Thank you in advance!

PD: If you further accept this into your branch do you mind if this gets GLPv3 lic.?

### CODE REVIEW

**Comment by tsg** [comment]
Hi, glad to see someone working on FCGI, we will be happy to review and help get this merged. We do need you to sign the [CLA](http://www.elasticsearch.org/contributor-agreement/) in order to review and merge it.

> PD: If you further accept this into your branch do you mind if this gets GLPv3 lic.?

I don't think that can technically work. Packetbeat is Apache licensed and all modules are statically compiled together, so I don't think you can have one of the modules GPL. Even if that would be possible, we'd very much prefer to have everything in the Beats repository (except from the `vendor` folder for dependencies) be the same license. Otherwise things get too difficult to review for potential users.

**Comment by patricio-dorantes** [comment]
Hi! I signed yesterday CLA the project may take my code in its convince. It would prefer you guys eventually you transform apache license into GPL protecting users' freedom, but for now is really my interest to help and get help adding FCGI to packetbeat.

**Comment by ruflin** [comment]
@patricio-dorantes It seems the current builds fail because of some code formatting issue (https://travis-ci.org/elastic/beats/jobs/108901606). Just run `make fmt` and `make check` inside the packetbeat directory and push the changes. This should resolve the build issues.

**Comment by tsg** [comment]
@patricio-dorantes we think this is a valuable contribution and we'd like to take it in. Can you address the comment above (run `make fmt` and push)? If you don't have the time, we're happy to take over the work here, just let us know. Thanks!

**Comment by karmi** [comment]
Hi @patricio-dorantes, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/beats/pull/959.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Pull request closed without merging**
