### PR TITLE
Enable DRA for main via Buildkite

### PR DESCRIPTION
**Pull request by dliappis**
## Proposed commit message

This commit disables automated DRA builds for
the `main` branch via Jenkins, and enables the
same functionality via Buildkite.

## Related issues

- https://github.com/elastic/ingest-dev/issues/3095

### CODE REVIEW

**Review by alexsapran — APPROVED** [review]

**Review by v1v — APPROVED** [review]

**Comment by dliappis** [comment]
@v1v it appears Jenkins reported a failure https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-39234/1/console

```
17:21:16  Transform JJBB to JJB
17:21:16  2024-04-26 14:21:16,416 [jjbb.main] [INFO] No templates found in .ci/templates, continuing without them.
17:21:16  Traceback (most recent call last):
17:21:16    File "/usr/local/bin/jjbb", line 8, in <module>
17:21:16      sys.exit(cli())
17:21:16    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1128, in __call__
17:21:16      return self.main(*args, **kwargs)
17:21:16    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1053, in main
17:21:16      rv = self.invoke(ctx)
17:21:16    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1395, in invoke
17:21:16      return ctx.invoke(self.callback, **ctx.params)
17:21:16    File "/usr/local/lib/python3.9/site-packages/click/core.py", line 754, in invoke
17:21:16      return __callback(*args, **kwargs)
17:21:16    File "/usr/local/lib/python3.9/site-packages/jjbb/scripts/cli.py", line 59, in cli
17:21:16      main(
17:21:16    File "/usr/local/lib/python3.9/site-packages/jjbb/main.py", line 328, in main
17:21:16      merged_templates = apply_template_jobs(template_paths, templates, var_defaults)
17:21:16    File "/usr/local/lib/python3.9/site-packages/jjbb/main.py", line 189, in apply_template_jobs
17:21:16      template_job_variables = get_template_job_variables(job_variables)
17:21:16    File "/usr/local/lib/python3.9/site-packages/jjbb/main.py", line 236, in get_template_job_variables
17:21:16      for variable in variables:
17:21:16  TypeError: 'NoneType' object is not iterable
```

any idea what's up?

**Comment by v1v** [comment]
> any idea what's up?

It runs https://github.com/elastic/apm-pipeline-library/blob/51fa7b4e45944bdd7e97c6c21398eb7f89c3838c/.ci/scripts/validate-jjbb.sh

No clue what's the state of those docker images...

I think you are good to move forward. Otherwise, I can disable the branch manually using the Jenkins UI and my super-powers

**Comment by dliappis** [comment]
> No clue what's the state of those docker images...
> 
> I think you are good to move forward. Otherwise, I can disable the branch manually using the Jenkins UI and my super-powers

ACK. Trouble is that beats-ci/pr-merge is a required check and thus can't merge this without Jenkins passing this check.

**Review by cmacknz — APPROVED** [review]

**Comment by v1v** [comment]
https://github.com/elastic/beats/pull/39234/commits/a4b359da2fdcb3c3e4d696c56dcaa554c5a35d1a should help.

I don't think the jjb validation makes any sense anyway, and rather than debugging what's causing the failure, I'd say we can disable it for the shake of simplicity.

**Pull request merged**
