### PR TITLE
packetbeat: preparation for npcap addition

### PR DESCRIPTION
**Pull request by efd6**
## What does this PR do?

This does largely mechanical cleanup of code under packetbeat, but also includes minor bug fixes.

## Why is it important?

This is preparatory for changes to add npcap support for integrations.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ] Confirm manual changes are consistent with original code intention. Mechanical changes are marked with a git-generate stanza.

## Related issues

- Relates elastic/integrations#2132

## Use cases

N/A

## Screenshots

N/A

## Logs

N/A

### CODE REVIEW

**Review by andrewkroh — APPROVED** [review]
LGTM. Lot's of good clean up here. Do you think any of this is worth a changelog mention? Like the error handling improvements in mongodb?

**Comment by efd6** [comment]
Yes, I'll do that.

**Comment by efd6** [comment]
Should ask: can significant clean ups be considered bugfix in the context of the changelog and is it OK to add multiple changelog lines in a PR?

**Comment by efd6** [comment]
@andrewkroh PTAL

**Comment by andrewkroh** [comment]
> can significant clean ups be considered bugfix

There's no hard rules on this so yes. It lacks specificity, but it would be good to know about if you were trying to track down a behavior change.

> and is it OK to add multiple changelog lines in a PR?

Yes, AFAIK that's OK (I've done this a few times). You cannot have individual entries that span multiple lines (I think it trips up someone's scripting used to generate the final changelog file).

**Pull request merged**
