### PR TITLE
Add rename processor to prevent error

### PR DESCRIPTION
**Pull request by robeatoz**
## What does this PR do?

Adds a `rename` processor to prevent error message on each container start

## Why is it important?

I used the docker image `elastic/filebeat:8.0.0` to harvest all logs from all containers, which worked really great! But every time a container started, I found the following error message from the filebeat container:

```
(status=400): {
"type": "mapper_parsing_exception", "reason": "object mapping for [source] tried to parse field [source] as object, but found a concrete value"
```

We have to rename the field "source" because the indices `.ds-filebeat-8.0.0-*` expect an object, but filebeat provides here the name of the log file as a string.

## Checklist

- [ ] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by belimawr** [comment]
@robeatoz could you provide more information on how to reproduce this issue? I tried, but did not manage to reproduce it.

I followed all the steps on our [documentation for 8.0](https://www.elastic.co/guide/en/beats/filebeat/current/running-on-docker.html). I used both images `docker.elastic.co/beats/filebeat:8.0.0` and `elastic/filebeat:8.0.0`. They all work fine, every time I start a new container the logs are successfully sent to ES.

Is this error log you posted from Elasticsearch or from Filebeat?

**Comment by robeatoz** [comment]
@belimawr I created a minimal showcase to reproduce the problem: <https://github.com/robeatoz/filebeat-minimal-showcase>

First start the setup with

```
docker-compose up --build
```

After all containers started, the `filebeat` container starts to harvest all logs of all containers, including his own logs.
When you start another container, e.g.

```
docker run --rm hello-world
``` 

The `filebeat` container logs:

```
{
  "log.level": "info",
  "log.logger": "input.harvester",
  ...
  "service.name": "filebeat",
  "source": "/var/lib/docker/containers/xxx/xxx-json.log",
}
```

This log message causes the following error in the  `filebeat` container:
```
{"log.level":"warn", 
... 
{\"type\":\"mapper_parsing_exception\",\"reason\":\"object mapping for [source] tried to parse field [source] as object, but found a concrete value\"}, dropping event!","service.name":"filebeat","ecs.version":"1.6.0"}
```

This error occurs because the index expects that the attribute `source` is an object, not a string.

I found this by investigating the index with `elasticvue`:

```
docker run --rm -p 8080:8080 cars10/elasticvu
```

To see the indexes, you have to go to settings and add `(?!)` (never matching regex) to the field `Hide indices regex`.
In the `Indices` menu, the `.ds-filebeat-8.0.0...` index appears. I clicked on `Show info` and searched for `"source"`:
image

The only solution I found is to rename the attribute like described in the PR. But this will cause every attribute with the name `source` to be renamed, what is maybe an overkill.

I hope the problem is now clear, and we find a better solution than in the PR.

**Comment by belimawr** [comment]
@robeatoz thank you so much for such a detailed showcase! I can now reproduce the issue.

Any logs (actually, events being sent to ES) containing the `source` key in a format that differs from the default mapping (an object with multiple fields) will fail to be indexed.

Some logs from our haverster that use the `source` key, like `Harvester started for file.` or `File was removed. Closing because close_removed is enabled.` fail to be indexed.

Using the [Dev tools](http://localhost:5601/app/dev_tools#/console) one can run the following query to get the mapping (you might need to adjust the index name):
```
GET .ds-filebeat-8.0.0*/_mapping
```

@jlind23 we should look into this. It seems our default mapping for the `.ds-filebeat-8.0.0-*` datastream cannot collect Filebeat own logs.

Renaming the `source` field as @robeatoz suggested on this PR avoids the issue by not using the default mapping for `source`. However if any container uses the `source` without being a string, those events will also be dropped. Off the top of my head I don't have a good solution for it.

**Comment by jlind23** [comment]
I have just created a public issue to update our docs stating that Filebeat shouldn't be used to ingest its own logs.
https://github.com/elastic/observability-docs/issues/1636

And I have created a follow up PR to potentially rename the source field which will be a more long term solution.

Thanks @robeatoz for your contribution, you can either work on this new public PR if you want to.
https://github.com/elastic/beats/issues/30667

**Pull request closed without merging**
