### PR TITLE
[libbeeat] add DropFields processor to js API

### PR DESCRIPTION
**Pull request by mib1185**
## What does this PR do?

This will register the `drop_fields` processor to the JavaScript API as `DropFields`, so that it can be used in custom js processors like already used to do with AddFields and many more.

Should also be backported to 7.17.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by mib1185** [comment]
> If this is a bug or security fix, could you label this PR @mib1185? 🙏.

@ mergify🤖 : sorry, but I'm not allowed to add labels in this repo

**Review by belimawr — APPROVED** [review]

**Comment by belimawr** [comment]
@mib1185 would you mind updating this PR with the latest changes on `main`? You can use the `Update branch` button here on the PR or do it manually.

**Comment by belimawr** [comment]
@mib1185 Could you also add a changelog entry?

After that it will be good to merge.

**Comment by mib1185** [comment]
hi @belimawr 
thanks for your review and comments 🙂 
Can I add the backport labels, or do you have to do it yourself?

**Comment by belimawr** [comment]
> hi @belimawr thanks for your review and comments slightly_smiling_face Can I add the backport labels, or do you have to do it yourself?

My plan was to skip the backport labels, I saw this PR like an enhancement rather than a bug-fix that should be backported.

Does it make sense to you? Or what are your thoughts on that?

**Comment by mib1185** [comment]
I agree that this is not a bugfix, but on the other hand it could also be a benefit for users of the 7.17 (_like myself_) 🙂

**Comment by belimawr** [comment]
> I agree that this is not a bugfix, but on the other hand it could also be a benefit for users of the 7.17 (_like myself_) slightly_smiling_face

I totally get that, but we can only backport bug fixes to 7.17.

That's a good opportunity for you to upgrade to the latest 8.x release ;)


I see a couple of checks are still failing, could you run:
```
make notice
``` 

From the root of the project and commit any changes?

**Comment by cmacknz** [comment]
> From the root of the project and commit any changes?

Probably the checks will pass after merging the go.mod updates from https://github.com/elastic/beats/pull/33789 to fix CI in beats in general.

**Comment by belimawr** [comment]
> will give it a try tomorrow, rebase unfortunately seems not to solve the CI issues

If you don't manage to fix it, I can also give it a shot.

**Comment by belimawr** [comment]
> Would it be convenient for you, when we say we fix the missing JS API availablity of the drop_fields processor?

Nothing prevents you from running your own fork ;).

**Comment by mib1185** [comment]
> > will give it a try tomorrow, rebase unfortunately seems not to solve the CI issues
> 
> If you don't manage to fix it, I can also give it a shot.

Would be great if you could give it a try 🙂

**Comment by belimawr** [comment]
Let's see if the latest changes on `main` helps CI to be happy

**Review by belimawr — APPROVED** [review]

**Pull request merged**
