### PR TITLE
[Filebeat] Add sophos XG log samples containing new field names

### PR DESCRIPTION
**Pull request by piellick**
Here is a bunch of firewall logs from sophos.

## Type of change 

 Enhancement

## What does this PR do?

Update firewall logs from sophos XG for testing.

## Why is it important?

Related to PR #28932 --> [elastic/beats] [Filebeat] Sophos Module - support for changed field names

### CODE REVIEW

**Comment by andrewkroh** [comment]
@piellick Thank you. Can you please sign the Contributor License Agreement (CLA). https://www.elastic.co/contributor-agreement

**Comment by andrewkroh** [comment]
What version of Sophos XG are these logs taken from?

**Comment by piellick** [comment]
Hi @andrewkroh 
> What version of Sophos XG are these logs taken from?
18.5.2-MR2 build 380

> @piellick Thank you. Can you please sign the Contributor License Agreement (CLA). https://www.elastic.co/contributor-agreement
Done

In meanwhile, i have found this doc who provide sample logs per log type fro 18.5.X version :
[https://docs.sophos.com/nsg/sophos-firewall/18.5/PDF/SF%20syslog%20guide%2018.5.pdf]()
COuld be very helpfull for you.

**Comment by andrewkroh** [comment]
Indeed, that is a great resource. Thanks

**Comment by efd6** [comment]
Thanks for providing these @piellick. It looks like there have been retained in a quoted document (probably as a JSON string). Is that the case?

**Comment by efd6** [comment]
Great. Thanks for confirming. I will go over it and fix up some of the issues that I noticed if that's OK with you, and generate the expected output so we can merge this.

**Comment by andrewkroh** [comment]
In https://github.com/elastic/integrations/pull/3127 I incorporated the samples from the reference docs you pointed us to. I didn't use the samples here b/c I think the documentation samples gives us good coverage. After the new version is out if you still have issues let us know.

I am curious if these samples came from the Sophos Log Viewer or were directly from a device over syslog? The reason I ask is because some of the fields, like `victim`, are not used in the syslog format (it is `target`).

Screen Shot 2022-04-21 at 16 53 28

**Pull request closed without merging**
