### PR TITLE
Bump LICENSE year in beat templates

### PR DESCRIPTION
**Pull request by srenatus**
🎉 😄

### CODE REVIEW

**Comment by srenatus** [comment]
Does the CLA have a "trivial fix" clause? If so, this would sure apply 😉

**Comment by tsg** [comment]
No, I think we don't have such a clause, but it should only take a few minutes to sign it. If you don't want to go through that, I'm happy to "redo" this in a new PR.

**Comment by srenatus** [comment]
Ok, I think I'll go through that 😉 -- It's not too terrible if this fix sits a day longer, I suppose, and it's a good chance to settle this.

**Comment by srenatus** [comment]
I've done the ICLA -- LGTM? 😃

**Comment by ruflin** [comment]
@srenatus Looks good. Thanks for the contribution.

**Pull request merged**
