### PR TITLE
Update Dockerfiles from the stack to 7.0

### PR DESCRIPTION
**Pull request by jsoriano**
Updating this so we can take advantage of features from 7.0. For
example tests don't pass now if we add a new dashboard exported
from Kibana 7.0.

### CODE REVIEW

**Comment by jsoriano** [comment]
jenkins, test this again please

**Comment by ruflin** [comment]
Already approved but now looking at CI failures it looks like the panics are related. @ycombinator Could you have a look?

**Comment by ycombinator** [comment]
Hmmm, I'm unable to reproduce this locally. Could we add `|| ${DOCKER_COMPOSE} logs --tail 200` to the Makefile target for the integration tests and see what we get back in the Kibana logs?

**Comment by jsoriano** [comment]
@ycombinator I can reproduce one of the issues locally with `INTEGRATION_TESTS=1 nosetests module/elasticsearch/test_elasticsearch.py`, and I see similar errors to the ones in https://travis-ci.org/elastic/beats/jobs/522269841
In ES logs I only see warnings about the deprecation of `/_xpack/license` (I guess that because of the healthcheck?)

Regarding the Kibana test, I see in the Kibana logs similar errors to the ones seen in the previous travis build, and it stays in `starting` state.
```
[circuit_breaking_exception] [parent] Data too large, data for [<http_request>] would be [90664734/86.4mb], which is larger than the limit of [86664806/82.6mb], real usage: [90664224/86.4mb], new bytes reserved: [510/510b], with { bytes_wanted=90664734 & bytes_limit=86664806 & durability=\"TRANSIENT\" }
```
Maybe the ugly error we see in Jenkins is some timeout.

**Comment by ycombinator** [comment]
@jsoriano regarding the ES error you posted in your latest comment, that should be fixed with https://github.com/jsoriano/beats/pull/1.

**Comment by ycombinator** [comment]
@jsoriano regarding the Kibana errors, I suspect these are a result of the ES heap size issue. When I ran this PR locally without the heap size fix, I see that that Kibana docker container just dies with this as its final words:

```
{"type":"log","@timestamp":"2019-04-25T12:25:52Z","tags":["fatal","root"],"pid":1,"message":"{ [circuit_breaking_exception] [parent] Data too large, data for [<http_request>] would be [89923704/85.7mb], which is larger than the limit of [86664806/82.6mb], real usage: [89923704/85.7mb], new bytes reserved: [0/0b], with { bytes_wanted=89923704 & bytes_limit=86664806 & durability=\"TRANSIENT\" } :: {\"path\":\"/.kibana\",\"query\":{},\"statusCode\":429,\"response\":\"{\\\"error\\\":{\\\"root_cause\\\":[{\\\"type\\\":\\\"circuit_breaking_exception\\\",\\\"reason\\\":\\\"[parent] Data too large, data for [<http_request>] would be [89923704/85.7mb], which is larger than the limit of [86664806/82.6mb], real usage: [89923704/85.7mb], new bytes reserved: [0/0b]\\\",\\\"bytes_wanted\\\":89923704,\\\"bytes_limit\\\":86664806,\\\"durability\\\":\\\"TRANSIENT\\\"}],\\\"type\\\":\\\"circuit_breaking_exception\\\",\\\"reason\\\":\\\"[parent] Data too large, data for [<http_request>] would be [89923704/85.7mb], which is larger than the limit of [86664806/82.6mb], real usage: [89923704/85.7mb], new bytes reserved: [0/0b]\\\",\\\"bytes_wanted\\\":89923704,\\\"bytes_limit\\\":86664806,\\\"durability\\\":\\\"TRANSIENT\\\"},\\\"status\\\":429}\"}\n    at respond (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:308:15)\n    at checkRespForFailure (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:267:7)\n    at HttpConnector.<anonymous> (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:166:7)\n    at IncomingMessage.wrapper (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/lodash.js:4935:19)\n    at IncomingMessage.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1103:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n  status: 429,\n  displayName: 'TooManyRequests',\n  message:\n   '[parent] Data too large, data for [<http_request>] would be [89923704/85.7mb], which is larger than the limit of [86664806/82.6mb], real usage: [89923704/85.7mb], new bytes reserved: [0/0b]: [circuit_breaking_exception] [parent] Data too large, data for [<http_request>] would be [89923704/85.7mb], which is larger than the limit of [86664806/82.6mb], real usage: [89923704/85.7mb], new bytes reserved: [0/0b], with { bytes_wanted=89923704 & bytes_limit=86664806 & durability=\"TRANSIENT\" }',\n  path: '/.kibana',\n  query: {},\n  body:\n   { error:\n      { root_cause: [Array],\n        type: 'circuit_breaking_exception',\n        reason:\n         '[parent] Data too large, data for [<http_request>] would be [89923704/85.7mb], which is larger than the limit of [86664806/82.6mb], real usage: [89923704/85.7mb], new bytes reserved: [0/0b]',\n        bytes_wanted: 89923704,\n        bytes_limit: 86664806,\n        durability: 'TRANSIENT' },\n     status: 429 },\n  statusCode: 429,\n  response:\n   '{\"error\":{\"root_cause\":[{\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be [89923704/85.7mb], which is larger than the limit of [86664806/82.6mb], real usage: [89923704/85.7mb], new bytes reserved: [0/0b]\",\"bytes_wanted\":89923704,\"bytes_limit\":86664806,\"durability\":\"TRANSIENT\"}],\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be [89923704/85.7mb], which is larger than the limit of [86664806/82.6mb], real usage: [89923704/85.7mb], new bytes reserved: [0/0b]\",\"bytes_wanted\":89923704,\"bytes_limit\":86664806,\"durability\":\"TRANSIENT\"},\"status\":429}',\n  toString: [Function],\n  toJSON: [Function],\n  isBoom: true,\n  isServer: true,\n  data: null,\n  output:\n   { statusCode: 500,\n     payload:\n      { message: 'An internal server error occurred',\n        statusCode: 500,\n        error: 'Internal Server Error' },\n     headers: {} },\n  reformat: [Function],\n  [Symbol(SavedObjectsClientErrorCode)]: 'SavedObjectsClient/generalError' }"}

 FATAL  [circuit_breaking_exception] [parent] Data too large, data for [<http_request>] would be [89923704/85.7mb], which is larger than the limit of [86664806/82.6mb], real usage: [89923704/85.7mb], new bytes reserved: [0/0b], with { bytes_wanted=89923704 & bytes_limit=86664806 & durability="TRANSIENT" } :: {"path":"/.kibana","query":{},"statusCode":429,"response":"{\"error\":{\"root_cause\":[{\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be [89923704/85.7mb], which is larger than the limit of [86664806/82.6mb], real usage: [89923704/85.7mb], new bytes reserved: [0/0b]\",\"bytes_wanted\":89923704,\"bytes_limit\":86664806,\"durability\":\"TRANSIENT\"}],\"type\":\"circuit_breaking_exception\",\"reason\":\"[parent] Data too large, data for [<http_request>] would be [89923704/85.7mb], which is larger than the limit of [86664806/82.6mb], real usage: [89923704/85.7mb], new bytes reserved: [0/0b]\",\"bytes_wanted\":89923704,\"bytes_limit\":86664806,\"durability\":\"TRANSIENT\"},\"status\":429}"}
```

**Comment by jsoriano** [comment]
@ycombinator thanks! this solves the error locally, let's see if it also solves the other error.

**Comment by ycombinator** [comment]
> In ES logs I only see warnings about the deprecation of /_xpack/license (I guess that because of the healthcheck?)

Correct, I confirmed this locally as well and fixed it in https://github.com/jsoriano/beats/pull/2.

**Comment by jsoriano** [comment]
Increasing a little more the heap size did the trick, this would be ready for another review.

**Comment by jsoriano** [comment]
> It's strange that it complains about the coverage as this should not change the coverage by much, only a few functions which are ES version specific.

The codecov report points to changes in coverage in auditbeat and in a filebeat input, I don't think is related. I have launched travis tests again to see if it gets a different result now.

**Comment by jsoriano** [comment]
Merging this, changes in coverage report don't seem related.

**Pull request merged**
