### PR TITLE
Remove huaweicloud - revert #27607

### LINKED ISSUE #31022: Wrong detection of cloud.provider since Beats 8.0 (openstack as huawei)
User reported:

After deploying elastic agent via fleet (ECE 3.1) on a VM on an internal OpenStack Cloud, all log entries - regardless of being delivered by filebeat or metricbeat - show the field "cloud.provider" = "huawei". The cloud platform is plain OpenStack.

Pre-8.0 versions correctly identified the cloud provider as OpenStack.

The regression may have been introduced by https://github.com/elastic/beats/pull/27607.

### PR DESCRIPTION
**Pull request by mstinsky**
- Bug

## What does this PR do?
This PR removes the huaweicloud from beats. The huaweicloud is just a openstack installation so since PR #27607 got merged all public and private openstack clouds can get detected as huaweicloud.
All the following lines from the huawei part are plain openstack [1] and are avaiable by every openstack metadata agent.

[1] https://github.com/elastic/beats/blob/main/libbeat/processors/add_cloud_metadata/provider_huawei_cloud.go#L49-L50

## Why is it important?
As described above all openstack clouds may get detected as a huaweicloud.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues
- Closes #31022

### CODE REVIEW

**Comment by belimawr** [comment]
@elastic/obs-cloud-monitoring I believe this processor belongs to your team. Could someone take a look at it?

@mstinsky I see you haven't signed the [Contributor Agreement](https://www.elastic.co/contributor-agreement) yet. Could you follow the instructions on the link and sign it?

**Comment by mstinsky** [comment]
@belimawr thats strange I signed the license agreement last week when I opened this PR. Do I need to do anything that it registers here correctly?

**Comment by kaiyan-sheng** [comment]
Thanks @mstinsky for your contribution. Is there a way to fix the issue instead of removing huaweicloud support? This would be a breaking change for users who are using this add_cloud_metadata processor for huaweicloud.

**Comment by mstinsky** [comment]
@kaiyan-sheng I am an operator of an openstack cloud and not using any huaweicloud service. As such I have no idea of the internal working of the huaweicloud other then that the huaweicloud is using openstack.
If I look into the implementation of the huaweicloud processor it just plain identifies that huawei is running openstack. As long as huawei does not patch the openstack metadata agent to expose any kind of special identifier there is no way to differentiate between a 'normal' openstack installation and the openstack installation of huaweicloud (as its just openstack :D).

**Comment by mstinsky** [comment]
I was thinking about this issue a bit more and have another arguement to remove huaweicloud from beats @kaiyan-sheng. There are a lot of other public available clouds that use openstack under the hood like OVH, Open Telekom Cloud, Cleura, VEXXHOST and many more.
If we want to have 'special' support for the huaweicloud's openstack installation how do we manage every other public available openstack cloud that wants to have support in beats? My arguement is everything is openstack so it makes sense (at least to me) that all just gets detected as plain openstack.

**Comment by andrewkroh** [comment]
Like @mstinsky highlighted, the implementation is literally checking if it is running inside of openstack and then labeling it as being huawei. That is clearly insufficient to identity Huawei. It needs to have additional selection criteria (like checking another API that is huawei specific) OR it huawei should be disabled by default OR removed entirely.

https://github.com/elastic/beats/blob/90cd631cabf82c2bac7999029feb791764ba2698/libbeat/processors/add_cloud_metadata/provider_huawei_cloud.go#L49-L50

**Comment by mstinsky** [comment]
@andrewkroh whats the plan here? Do we move forward with removing huaweicloud?

**Comment by mstinsky** [comment]
Can we get any feedback here from a codeowner on how to proceed with this issue?

**Comment by andrewkroh** [comment]
@elastic/obs-cloud-monitoring WDYT about the approach I laid out in my previous comment for removing the huawei provider?

**Comment by kaiyan-sheng** [comment]
@andrewkroh I think treating huawei as an alias and removing it should work at least for the short term. We are trying to prioritize the work of fixing the add_cloud_metadata processor but no clue if we will even find a solution for huawei vs OpenStack tbh.

**Comment by kaiyan-sheng** [comment]
@andrewkroh WDYT about instead of completely removing `huaweiMetadataFetcher`, we keep it and only use this fetcher when `huawei` is specified using the `providers` config parameter?

Something like this:
```
diff --git a/libbeat/processors/add_cloud_metadata/providers.go b/libbeat/processors/add_cloud_metadata/providers.go
index 2b9f0d9064..022784399b 100644
--- a/libbeat/processors/add_cloud_metadata/providers.go
+++ b/libbeat/processors/add_cloud_metadata/providers.go
@@ -64,7 +64,7 @@ var cloudMetaProviders = map[string]provider{
        "nova-ssl":      openstackNovaSSLMetadataFetcher,
        "qcloud":        qcloudMetadataFetcher,
        "tencent":       qcloudMetadataFetcher,
-       "huawei":        huaweiMetadataFetcher,
+       "huawei":        openstackNovaMetadataFetcher,
        "hetzner":       hetznerMetadataFetcher,
 }
 
@@ -91,7 +91,11 @@ func filterMetaProviders(filter func(string) bool, fetchers map[string]provider)
        out := map[string]provider{}
        for name, ff := range fetchers {
                if filter(name) {
-                       out[name] = ff
+                       if name == "huawei" {
+                               out[name] = huaweiMetadataFetcher
+                       } else {
+                               out[name] = ff
+                       }
                }
        }
        return out
```

**Comment by andrewkroh** [comment]
> WDYT about instead of completely removing huaweiMetadataFetcher, we keep it and only use this fetcher when huawei is specified using the providers

That could work (not commenting on the patch), the processor would need to enforce a restriction that `huawei` cannot be used along side any of the openstack providers (`openstackNovaMetadataFetcher`, `openstackNovaSSLMetadataFetcher`).

**Comment by mstinsky** [comment]
I am neither a go developer nor do I have good knowledge about the filebeat codebase.
But as the `huaweiMetadataFetcher` is essentially doing the same thing as the `openstackNovaMetadataFetcher`, I would argue that keeping the code is redundant and opens the door for more bugs down the line when handling it in a special way. 

Also I would like to bring up my argument from https://github.com/elastic/beats/pull/35184#issuecomment-1534354967 once more. 
There are many more public openstack clouds out there, having a special case for huawei opens the door to support numerous other openstack clouds. And I am not sure if beats wants to do that.

**Comment by kaiyan-sheng** [comment]
@mstinsky @andrewkroh Thank you both for the comments! I agree with your argument about having special case for huawei can be problematic in the future. Let's make huawei an alias for OpenStack and keep it as a provider option, so we are not breaking anyone then!

**Comment by mstinsky** [comment]
@kaiyan-sheng would you be willing to provide a patch for that?
I am not sure what you both mean with keeping huawei as an alias. As I said I dont have much experience with go, if you want me to provide a patch for that I would need a bit of guidance :)

**Comment by mstinsky** [comment]
Thanks for the patch @kaiyan-sheng!
Is anything required on my part to unblock the pipelines?

**Comment by kaiyan-sheng** [comment]
@mstinsky I dont think so! Thanks again for your contribution!
@andrewkroh Could you take a look when you get a chance please? Thanks!!

**Review by andrewkroh — COMMENTED** [review]
What would the behavior be when both `huawei` and `nova` are configured as providers? Does the processor run the two instances of the same detection logic? If so, it would be nice to prevent this duplication of work by treating the providers as a set.

**Comment by mstinsky** [comment]
Hi @kaiyan-sheng, @andrewkroh.
What is the status of this PR?
The OpenStack integration is now broken for several years. Any chance that we get this merged soon?

**Comment by kaiyan-sheng** [comment]
@mstinsky SORRY my bad! I went on leave and left this behind. Will address the previous comment now!

**Comment by kaiyan-sheng** [comment]
> What would the behavior be when both `huawei` and `nova` are configured as providers? Does the processor run the two instances of the same detection logic? If so, it would be nice to prevent this duplication of work by treating the providers as a set.

Hey @andrewkroh, that's a good point! I was looking at the code and I think function [setupFetchers](https://github.com/elastic/beats/blob/main/libbeat/processors/add_cloud_metadata/providers.go#L100) is already doing the deduplication.

**Review by kaiyan-sheng — APPROVED** [review]

**Pull request merged**
