### PR TITLE
Use MODULE in metricbeat python system tests

### PR DESCRIPTION
**Pull request by jsoriano**
## What does this PR do?

Use `MODULE` environment variable to run the tests for a single module as
run in CI.

## Why is it important?

Faster CI builds, and easier to locally reproduce failures in CI.

## Related issues

- Related to #18678, fixes it for metricbeat

### CODE REVIEW

**Comment by exekias** [comment]
I realize it's outdated, but it would be nice to update this section https://www.elastic.co/guide/en/beats/devguide/current/metricset-details.html#_running_the_tests

**Comment by jsoriano** [comment]
> I realize it's outdated, but it would be nice to update this section https://www.elastic.co/guide/en/beats/devguide/current/metricset-details.html#_running_the_tests

Good point, updated.

**Comment by jsoriano** [comment]
jenkins run the tests please

**Comment by jsoriano** [comment]
jenkins run the tests please :crossed_fingers:

**Pull request merged**
