### PR TITLE
Update go-sysinfo to v1.1.1 to fix getting distro info on Fedora 30.

### PR DESCRIPTION
**Pull request by mikemadden42**

### CODE REVIEW

**Comment by urso** [comment]
@andrewkroh @mikemadden42 Looks like the go-sysinfo update breaks the winlogbeat build:

```
sys/eventlogging/eventlogging_windows.go:416:18: assignment mismatch: 2 variables but sid.String returns 1 values
```

**Comment by andrewkroh** [comment]
IIRC there was a breaking change in the golang.org/x/sys/windows package. elastic/beats needs a vendor/ update to fix the compatibility issue.

**Comment by mikemadden42** [comment]
jenkins please retest this

**Comment by mikemadden42** [comment]
jenkins retest this please

**Comment by andrewkroh** [comment]
This will be fixed by @fearful-symmetry 's https://github.com/elastic/beats/pull/15196.

**Comment by richard-mauri** [comment]
> IIRC there was a breaking change in the golang.org/x/sys/windows package. elastic/beats needs a vendor/ update to fix the compatibility issue.

Can someone help me sort out a change I can make to my go.mod file so I can build a simple winlogbeat under GOOS=windows?

I am trying to use beats v7.5.2 and I see the SID.String() returns two args even in v7.6 so if there was a vendor.json change it isn't getting picked up.

> $ make build-windows
> GOOS=windows GOARCH=amd64 go build -o /Users/rmauri/gopath/src/githubdev.dco.elmae/CloudPlatform/em-top-beats/ebsbeat/bin/windows_amd64/ebsbeat -ldflags "-X githubdev.dco.elmae/CloudPlatform/em-top-beats/ebsbeat/processor/ebsprocessor.Version=0.0.3-abc" main.go
> # github.com/elastic/beats/winlogbeat/sys/eventlogging
> ../../../../../pkg/mod/github.com/elastic/beats@v7.5.2+incompatible/winlogbeat/sys/eventlogging/eventlogging_windows.go:416:18: assignment mismatch: 2 variables but sid.String returns 1 values
> make: *** [build-ebs-windows] Error 2
> w10mkimx1:ebsbeat rmauri$ cat go.mod
> module githubdev.dco.elmae/CloudPlatform/em-top-beats/ebsbeat
> 
> go 1.13
> 
> require (
> 	4d63.com/tz v1.1.0 // indirect
> 	github.com/Microsoft/go-winio v0.4.14 // indirect
> 	github.com/Shopify/sarama v1.25.0 // indirect
> 	github.com/dlclark/regexp2 v1.2.0 // indirect
> 
> 	github.com/docker/distribution v2.7.1+incompatible // indirect
> 	github.com/docker/docker v1.13.1 // indirect
> 	github.com/docker/go-connections v0.4.0 // indirect
> 	github.com/docker/go-units v0.4.0 // indirect
> 
> 	github.com/dop251/goja v0.0.0-20200110130636-0a0a0d8cb944 // indirect
> 	github.com/dop251/goja_nodejs v0.0.0-20200120171228-34eac44e576f // indirect
> 	github.com/dustin/go-humanize v1.0.0 // indirect
> 	github.com/elastic/beats v7.5.2+incompatible
> 	github.com/elastic/ecs v1.4.0 // indirect
> 	github.com/elastic/go-lumber v0.1.0 // indirect
> 	github.com/elastic/go-seccomp-bpf v1.1.0 // indirect
> 	github.com/elastic/go-structform v0.0.6 // indirect
> 	github.com/elastic/go-sysinfo v1.3.0 // indirect
> 	github.com/elastic/go-txfile v0.0.7 // indirect
> 	github.com/elastic/gosigar v0.10.5 // indirect
> 	github.com/fatih/color v1.9.0 // indirect
> 	github.com/garyburd/redigo v1.6.0 // indirect
> 	github.com/go-sourcemap/sourcemap v2.1.2+incompatible // indirect
> 	github.com/gofrs/uuid v3.2.0+incompatible // indirect
> 	github.com/imdario/mergo v0.3.8 // indirect
> 	github.com/miekg/dns v1.1.27 // indirect
> 	github.com/mitchellh/hashstructure v1.0.0 // indirect
> 	github.com/opencontainers/go-digest v1.0.0-rc1 // indirect
> 	github.com/opencontainers/image-spec v1.0.1 // indirect
> 	github.com/pkg/errors v0.9.1
> 	github.com/rcrowley/go-metrics v0.0.0-20190826022208-cac0b30c2563 // indirect
> 	github.com/sirupsen/logrus v1.4.2 // indirect
> 	github.com/spf13/cobra v0.0.5 // indirect
> 	go.uber.org/multierr v1.4.0 // indirect
> 	go.uber.org/zap v1.13.0 // indirect
> 	golang.org/x/crypto v0.0.0-20200117160349-530e935923ad // indirect
> 	golang.org/x/net v0.0.0-20200114155413-6afb5195e5aa // indirect
> 	golang.org/x/oauth2 v0.0.0-20200107190931-bf48bf16ab8d // indirect
> 	golang.org/x/sys v0.0.0-20200122134326-e047566fdf82 // indirect
> 	golang.org/x/time v0.0.0-20191024005414-555d28b269f0 // indirect
> 	google.golang.org/grpc v1.26.0 // indirect
> 	gopkg.in/yaml.v2 v2.2.8 // indirect
> 	//k8s.io/api v0.17.2 // indirect
> 	//k8s.io/client-go v11.0.0+incompatible // indirect
> 	//k8s.io/utils v0.0.0-20200122174043-1e243dd1a584 // indirect
> 
> 	k8s.io/api v0.0.0-20191108065827-59e77acf588f // indirect
> 	k8s.io/client-go v0.0.0-20190620085101-78d2af792bab // indirect
> 	k8s.io/utils v0.0.0-20191030222137-2b95a09bc58d // indirect
> )
> 
> replace github.com/docker/docker => github.com/docker/engine v1.4.2-0.20190717161051-705d9623b7c1
> 
> replace github.com/Sirupsen/logrus v1.4.2 => github.com/sirupsen/logrus v1.4.2
> 
> replace github.com/dop251/goja v0.0.0-20200110130636-0a0a0d8cb944 => github.com/andrewkroh/goja v0.0.0-20190128172624-dd2ac4456e20


I am using go1.13.4 with GO111MODULE=on

**Comment by andrewkroh** [comment]
Try setting up your go.mod to use the same version that beats v7.5.2 uses:

https://github.com/elastic/beats/blob/v7.5.2/vendor/vendor.json#L3449-L3450

**Pull request closed without merging**
