### PR TITLE
Update cloud.google.com/go library

### PR DESCRIPTION
**Pull request by ChrsMark**
## What does this PR do?
This PR updates `cloud.google.com/go` to a more recent version.

### CODE REVIEW

**Comment by ChrsMark** [comment]
We can upgrade to a more recent one but in order to unblock https://github.com/elastic/beats/pull/28023/files#diff-33ef32bf6c23acb95f5902d7097b7a1d5128ca061167ec0716715b0b9eeaa5f6R6 we just need this version. @sayden @endorama let me know what you think about this update.

**Comment by endorama** [comment]
@ChrsMark FYI I'm testing this locally right now.

**Review by endorama — APPROVED** [review]
Data collection works as expected, so 👍 from me

**Comment by ChrsMark** [comment]
Thank for taking the time to test it @endorama! Merging!

**Pull request merged**
