### PR TITLE
transform beat.cgroup.memory.mem.usage.bytes to Gauge

### PR DESCRIPTION
**Pull request by boranx**
## What does this PR do?

This transforms _beat.cgroup.memory.mem.usage.bytes_ to Gauge  as it can have a negative value

## Why is it important?

it tries to eliminate `Non-zero metrics in the last 30s` errors by transforming `beat.cgroup.memory.mem.usage.bytes` to gauge 

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

Fix: https://github.com/elastic/beats/issues/31582

### CODE REVIEW

**Comment by cmacknz** [comment]
Changes look good, you'll need to sign the CLA and then we can kick the tests and get this merged.

**Comment by boranx** [comment]
I'd bet I've signed this a couple of hours ago, but in order to reflect the changes, should we re-trigger ci?

/test

**Comment by cmacknz** [comment]
Yes, CLA check has passed now. Someone from Elastic has to trigger the first test run, which I've now done.

We can ignore the linter errors here as they aren't caused by changes you've made (it always wants to lint the entire file, not just the changed lines).

**Review by cmacknz — APPROVED** [review]

**Comment by cmacknz** [comment]
Merged, thanks!

**Pull request merged**
