### PR TITLE
Lower the font size of the metric visualizations for Metricbeat dashboards

### LINKED ISSUE #2615: Improve built-in metricbeat dashboards
- Version: 5.0-beta1
- Operating System: MacOSX
- Steps to Reproduce: 

1. Download Metricbeat 5.0-beta1 and install
2. Install the Metricbeat dashboard
3. View the built-in Metricbeat Kibana dashboard and obsesrve that particularly the metric(number) visualizations don't fit well in the chart region as below images. 

Feedback on **Usability**:
From the user's perspective, it'd make the numbers more glimpse-able and easy to understand if we can shorten the decimal points. 

Feedback on **Consistency**:
we're not consistent with the metrics with or without units. In the overview dashboard as well as in Metricbeat memory dashboard, we show available memory as raw number, which isn't consistent with Total memory which shows as 16GB.

Overview dashboard:
image

Metricbeat Memory: 
image

Network:
image

### PR DESCRIPTION
**Pull request by monicasarbu**
This PR is meant to fix #2615, and comes with two big changes:

1. Set the format to bytes, instead of simple number for: `system.memory.actual.free`, `system.memory.actual.used.bytes` and percentage for `system.memory.actual.used.pct`.
2. Lower the font-size to 30pt for all metric visualizations

### CODE REVIEW

**Comment by tsg** [comment]
Shouldn't the index pattern be generated here?

**Comment by monicasarbu** [comment]
Indeed it's strange that the index pattern was not generated after `make update`. Looking into it.

**Comment by monicasarbu** [comment]
It is generated.

**Comment by monicasarbu** [comment]
I added to this PR the changes done to the Kibana dashboards to lower the font-size of the metric visualizations.

**Comment by ruflin** [comment]
@monicasarbu Can you rebase on master?

**Comment by monicasarbu** [comment]
@ruflin rebase done. Finished all the small details. Now the overview dashboards looks nice also on smaller screens.

**Comment by ruflin** [comment]
@monicasarbu I pushed a fix as part of https://github.com/elastic/beats/pull/2700 but TBH I think it is cleaner to do a separate PR for it which can be backported.

**Pull request merged**
