### PR TITLE
[Filebeat] Add TLS to haproxy grok pattern

### LINKED ISSUE #29318: Filebeat: Add HAProxy module support for TLS version and cipher log fields
**Describe the enhancement:**
At the moment, the exported fields for HAProxy Filebeat module provide a wide variety of fields but it is missing the SSL/TLS Version and Cipher fields.
We currently use this log-format and parse this in Logstash but we would like to use only filebeat:
```
log-format: "%ci:%cp\\ [%t]\\ %ft\\ %b/%s\\ %ST\\ %B\\ %CC\\ %CS\\ %tsc\\ %ac/%fc/%bc/%sc/%rc\\ %sq/%bq\\ %hr\\ %hs\\ %%{}{+Q}r\\ %sslv\\ %sslc\\ %ID"
```
The last entries provide the version and cipher. Our other option is to migrate this format to JSON and let it parse by an filebeat input but I would prefer the module.

**Describe a specific use case for the enhancement or feature:**
In todays world it is important to know which TLS versions are supported and used in order to decide to enable/disable one for specific interfaces to improve security.

### PR DESCRIPTION
**Pull request by legoguy1000**
## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes #29318

### CODE REVIEW

**Comment by legoguy1000** [comment]
unstall

**Comment by jlind23** [comment]
@legoguy1000 is it still a draft or is it ready to be reviewed?

**Comment by legoguy1000** [comment]
I need to regenerate the test data and then I think it's good. This fell off my radar so I'll get this updated

**Comment by legoguy1000** [comment]
I'm having an issue with generating the test data running `GENERATE=1 TESTING_FILEBEAT_MODULES=haproxy TESTING_FILEBEAT_FILESETS=log mage -v pythonIntegTest`.  It hangs on waiting for the Kafka container to start and then just craps out.  This is the first I've touched the beats modules in a while so IDK if something changed or I'm missing something.

**Comment by legoguy1000** [comment]
I'm trying to generate the data with `GENERATE=1 TESTING_FILEBEAT_MODULES=haproxy TESTING_FILEBEAT_FILESETS=log mage -v pythonIntegTest`, but it hangs at certain points and IDK exactly whats up.  It's been a while since I've run these commands so IDK if my VM that i'm running it in or something else.

**Pull request closed without merging**
