### PR TITLE
Add initial Apache HTTPD server status dashboard visualizations

### PR DESCRIPTION
**Pull request by radoondas**

### CODE REVIEW

**Comment by ruflin** [comment]
@radoondas Thanks a lot. What would be nice to also have a screenshot of the dashboard in the module docs file ... ;-)

**Comment by radoondas** [comment]
@ruflin yes! I will update PR.

**Comment by radoondas** [comment]
@ruflin Should I put image to following path? metricbeat/docs/images

**Comment by ruflin** [comment]
@radoondas good question. I just realised that this is missing in the collect script. Put it under docs/images for the moment as you suggested.

**Comment by radoondas** [comment]
@ruflin screenshot is added.

**Comment by ruflin** [comment]
@radoondas Thanks a lot

**Pull request merged**
