### PR TITLE
Fix metricbeat generator test to use mage test

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Updates the generated custom metricbeat to use `mage test` instead of `make unit`.

## Why is it important?

So the generator tests pass.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

### CODE REVIEW

**Comment by blakerouse** [comment]
Got it further but it seems to be breaking on building the packaging now. With `_meta/kibana.generated` not being found.

**Comment by blakerouse** [comment]
run beats-ci/package

**Comment by jsoriano** [comment]
> Got it further but it seems to be breaking on building the packaging now. With `_meta/kibana.generated` not being found.

Maybe generators magefiles need to use `PackageKibanaDashboardsFromBuildDir` now?

**Comment by andrewkroh** [comment]
run tests

**Comment by andrewkroh** [comment]
It looks like we are dealing with two separate failures. We merged one change that broke the generators and then while it was broken merged another change that caused a new failure.

I think @jsoriano is correct, that `PackageKibanaDashboardsFromBuildDir` is needed because the dashboards are generated by mage which puts them into `build/` dir instead of `_meta/kibana.generated` (where Make used to put them).

The other failure has something to with the k8s dependencies in the go.mod / go.sum of the "new beat". The error I'm seeing looks like it's getting the wrong version of k8s.io/apimachinery?

```
# k8s.io/client-go/tools/clientcmd/api/v1
../../../pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/clientcmd/api/v1/conversion.go:29:15: scheme.AddConversionFuncs undefined (type *runtime.Scheme has no field or method AddConversionFuncs)
../../../pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/clientcmd/api/v1/conversion.go:31:12: s.DefaultConvert undefined (type conversion.Scope has no field or method DefaultConvert)
../../../pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/clientcmd/api/v1/conversion.go:34:12: s.DefaultConvert undefined (type conversion.Scope has no field or method DefaultConvert)
../../../pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/clientcmd/api/v1/conversion.go:37:12: s.DefaultConvert undefined (type conversion.Scope has no field or method DefaultConvert)
../../../pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/clientcmd/api/v1/conversion.go:40:12: s.DefaultConvert undefined (type conversion.Scope has no field or method DefaultConvert)
../../../pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/clientcmd/api/v1/conversion.go:43:12: s.DefaultConvert undefined (type conversion.Scope has no field or method DefaultConvert)
../../../pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/clientcmd/api/v1/conversion.go:46:12: s.DefaultConvert undefined (type conversion.Scope has no field or method DefaultConvert)
../../../pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/clientcmd/api/v1/conversion.go:49:12: s.DefaultConvert undefined (type conversion.Scope has no field or method DefaultConvert)
../../../pkg/mod/k8s.io/client-go@v0.0.0-20190620085101-78d2af792bab/tools/clientcmd/api/v1/conversion.go:52:12: s.DefaultConvert undefined (type conversion.Scope has no field or method DefaultConvert)
```

**Pull request merged**
