### PR TITLE
Cleanup breaking changes section (#29489)

### PR DESCRIPTION
**Pull request by andresrc**
Forward port to 7.17

### CODE REVIEW

**Review by ruflin — APPROVED** [review]
Empty LGTM as there are any.

**Comment by ruflin** [comment]
There is a diff now but also there is a conflict now :-(

**Comment by rdner** [comment]
@andresrc @ruflin is this PR still relevant or we can discard it?

**Comment by ruflin** [comment]
@andresrc We had many chnages to the changelog for 7.17 since. I have a suspicion this is obosolete?

**Comment by rdner** [comment]
I'm going to close this PR now, we can re-open later if needed.

**Comment by andresrc** [comment]
@rdner sorry I missed the ping. I'll take a look

**Comment by andresrc** [comment]
Exactly, obsolete now, closing

**Pull request closed without merging**
