### PR TITLE
Move yum install of epel-release and jq to the docker file

### LINKED ISSUE #18345: Elastic Agent: don't install packages in entrypoint
Everytime the container is starting it tries to perform following actions:

```
yum install -y epel-release
yum install -y jq
``

If I spawn dozens of instances, it's a bottleneck.

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Moves yum install of epel-release and jq to the docker file and not something that is done on first start of the docker container.

## Why is it important?

So on startup is faster and so it doesn't need access to the yum repo, in closed environment there might not be access to yum.

## Checklist

- [X] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Related issues

- Closes #18345

### CODE REVIEW

**Comment by blakerouse** [comment]
run beats-ci/package

**Comment by michalpristas** [comment]
i will test it with kibana, i had issues when installing jq there it was not available.

**Comment by michalpristas** [comment]
this is happening for me when i run 
```
export PLATFORMS='+all linux/amd64'
mage package
```

from `x-pack/elastic-agent` directory

error:
`The command '/bin/sh -c yum -y --setopt=tsflags=nodocs update &&     yum install -y epel-release jq     yum clean all' returned a non-zero code: 1`

**Comment by blakerouse** [comment]
@michalpristas I am not seeing that issue.

```
blake@MacBook-Pro elastic-agent % PLATFORMS="+all linux/amd64" mage package
>> Building elastic-agent.yml for linux/amd64
>> Building elastic-agent.reference.yml for linux/amd64
>> Building elastic-agent.docker.yml for linux/amd64
>> Buildspec from spec/*.yml to pkg/agent/program/supported.go
>> BuildFleetCfg _meta/elastic-agent.fleet.yml to pkg/agent/application/configuration_embed.go
>> buildGoDaemon: Building for linux/amd64
>> golangCrossBuild: Building for linux/amd64
>> Building using: cmd='build/mage-linux-amd64 golangCrossBuild', env=[CC=gcc, CXX=g++, GOARCH=amd64, GOARM=, GOOS=linux, PLATFORM_ID=linux-amd64]
>> Building using: cmd='build/mage-linux-amd64 buildGoDaemon', env=[CC=gcc, CXX=g++, GOARCH=amd64, GOARM=, GOOS=linux, PLATFORM_ID=linux-amd64]
>> package: Building elastic-agent type=deb for platform=linux/amd64
>> package: Building elastic-agent type=docker for platform=linux/amd64
>> package: Building elastic-agent type=tar.gz for platform=linux/amd64
>> package: Building elastic-agent type=rpm for platform=linux/amd64
Unable to find image 'docker.elastic.co/beats-dev/fpm:1.11.0' locally
Unable to find image 'docker.elastic.co/beats-dev/fpm:1.11.0' locally
1.11.0: Pulling from beats-dev/fpm
56da78ce36e9: Already exists
f9ad043b5b84: Pulling fs layer
bbc7e171b46d: Pulling fs layer
cc1fb972a797: Pulling fs layer
f17f8847fcfe: Pulling fs layer
f17f8847fcfe: Waiting
1.11.0: Pulling from beats-dev/fpm
56da78ce36e9: Already exists
f9ad043b5b84: Pulling fs layer
bbc7e171b46d: Pulling fs layer
cc1fb972a797: Pulling fs layer
f17f8847fcfe: Pulling fs layer
f17f8847fcfe: Waiting
bbc7e171b46d: Verifying Checksum
bbc7e171b46d: Verifying Checksum
bbc7e171b46d: Download complete
bbc7e171b46d: Download complete
f17f8847fcfe: Verifying Checksum
f17f8847fcfe: Download complete
f17f8847fcfe: Verifying Checksum
f17f8847fcfe: Download complete
cc1fb972a797: cc1fb972a797: Verifying Checksum
Verifying Checksum
cc1fb972a797: Download complete
cc1fb972a797: Download complete
f9ad043b5b84: Verifying Checksum
f9ad043b5b84: Download complete
f9ad043b5b84: Verifying Checksum
f9ad043b5b84: Download complete
f9ad043b5b84: Pull complete
f9ad043b5b84: Pull complete
bbc7e171b46d: bbc7e171b46d: Pull complete
Pull complete
cc1fb972a797: Pull complete
cc1fb972a797: Pull complete
f17f8847fcfe: Pull complete
f17f8847fcfe: Pull complete
Digest: sha256:492e7ad8a450136f8502325886b1c57f484db3774a0a27f484e946e890848e3c
Digest: sha256:492e7ad8a450136f8502325886b1c57f484db3774a0a27f484e946e890848e3c
Status: Downloaded newer image for docker.elastic.co/beats-dev/fpm:1.11.0
Status: Image is up to date for docker.elastic.co/beats-dev/fpm:1.11.0
Doing `require 'backports'` is deprecated and will not load any backport in the next major release.
Require just the needed backports instead, or 'backports/latest'.
Doing `require 'backports'` is deprecated and will not load any backport in the next major release.
Require just the needed backports instead, or 'backports/latest'.
package ran for 57.502934243s
```

**Comment by michalpristas** [comment]
strange, i think go ahead and merge it, i will play with it on my end. i did system prune before building this but it should not matter. i see you;re on mac as well

**Comment by blakerouse** [comment]
Package build on linux passed, but seems the build on Mac OS failed. That seems unrelated to my change and I was able to build it on Mac just fine.

```
12:11:14 Generated fields.yml for metricbeat to /private/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-package-darwin/src/github.com/elastic/beats/metricbeat/build/fields/fields.all.yml
12:13:41 exec: go list -m
12:13:46 exec: go list -m
12:15:09 >> golangCrossBuild: Building for darwin/amd64
12:15:14 >> Building using: cmd='build/mage-linux-amd64 golangCrossBuild', env=[CC=o64-clang, CXX=o64-clang++, GOARCH=amd64, GOARM=, GOOS=darwin, PLATFORM_ID=darwin-amd64]
12:23:05 /usr/local/go/pkg/tool/linux_amd64/link: signal: killed
12:23:13 Error: running "go build -o build/golang-crossbuild/metricbeat-darwin-amd64 -ldflags -s -X github.com/elastic/beats/v7/libbeat/version.buildTime=2020-05-07T16:15:14Z -X github.com/elastic/beats/v7/libbeat/version.commit=70b0e7bca84543f7aa2709ef5408f224b4d3ac10" failed with exit code 1
12:23:13 Error: failed building for darwin/amd64: exit status 1
12:23:13 failed building for darwin/amd64: exit status 1
12:23:19 Error: running "docker run --env EXEC_UID=596 --env EXEC_GID=503 --env GOFLAGS=-mod=vendor --rm --env MAGEFILE_VERBOSE= --env MAGEFILE_TIMEOUT= --env SNAPSHOT=true -v /private/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-package-darwin/src/github.com/elastic/beats:/go/src/github.com/elastic/beats -w /go/src/github.com/elastic/beats/metricbeat docker.elastic.co/beats-dev/golang-crossbuild:1.13.10-darwin --build-cmd build/mage-linux-amd64 golangCrossBuild -p darwin/amd64" failed with exit code 1
12:23:19 package ran for 12m12.396146685s
12:23:19 make[1]: *** [release] Error 1
12:23:19 make: *** [release] Error 1
```

Going to go ahead and land and backport.

**Pull request merged**
