### PR TITLE
Stop using mage:import in custom beats

### LINKED ISSUE #13998: mage:import doesn't use vendored beats on custom beats
Since 7.4.0, custom beats reuse common mage targets from beats, for that they make use of `mage:import`. This is not using vendored beats in the `vendor` directory, though other go tools do use it. This causes problems if a different version of beats is in the `GOPATH`, like this one:
```
# command-line-arguments
./mage_output_file.go:498:5: undefined: common.AddLicenseHeaders
./mage_output_file.go:518:5: undefined: common.CheckLicenseHeaders
Error: error compiling magefiles
```

It was reported in the mage repository (https://github.com/magefile/mage/issues/244). Migration of Beats to go modules is proposed there as solution.

We will need to look for another solution in the meantime. Or look for an alternative way of reusing targets.

For confirmed bugs, please report:
- Version: >= 7.4.0
- Steps to Reproduce: Create a new beat from a version of beats that makes use of `mage:import` in magefiles, and checkout a different version in the `GOPATH`.

// cc: @radoondas

### PR DESCRIPTION
**Pull request by jsoriano**
`mage:import` doesn't take into account vendorized dependencies, this is a
problen for custom beats, because by default they have libbeat as a
vendorized dependency. The solution would be to use go modules, but in
the meantime lets remove the use of `mage:import` from the magefiles
intended to be used by custom beats.

Fix #13998

### CODE REVIEW

**Comment by fearful-symmetry** [comment]
It looks like we're missing a bunch of the `test` targets, or do we not care about those in the generator beats?

**Comment by jsoriano** [comment]
> It looks like we're missing a bunch of the `test` targets, or do we not care about those in the generator beats?

I wouldn't care about them. Before using `mage:import` we didn't have them. Also I wouldn't add targets that we need for python or integration testing, as this will probably be different in other beats. I am going to take a look to the go unit testing targets in any case.

**Comment by fearful-symmetry** [comment]
It looks like we're still importing `build` but a lot of the `Build` and `CrossBuild` targets are missing. We might want those.

**Comment by jsoriano** [comment]
> It looks like we're still importing `build` but a lot of the `Build` and `CrossBuild` targets are missing. We might want those.

Agree, I will add `build` and `crossBuild`.

**Comment by jsoriano** [comment]
Failing tests happening in filebeat only, not related, merging and backporting this.

**Comment by jsoriano** [comment]
Thanks @fearful-symmetry for the review!

**Pull request merged**
