### PR TITLE
Fix update target in metricbeat magefile.go to include collectDocs target

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Fixes the `mage update` target in metricbeat to also call `mage collectDocs`.

## Why is it important?

So the `docs/` are generate for metricbeat.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Author's Checklist

- [X] Calling `mage update` updates the documentation.

## How to test this PR locally

`$ mage update`

or

`$ make update`

### CODE REVIEW

**Comment by dedemorton** [comment]
I think there are still problems (unless we removed support for `make docs` and no one told me). :-) 

1 - `make docs` doesn't work.
2 - When I run `make update`, it doesn't update fields.asciidoc with changes made to the fields.yml.

Here's git status after running `make update` from beats/metricbeat. Notice that fields.yml changed, but the fields.asciidoc is not updated as it should be:

```
Rhodas-MBP:metricbeat⎇ metricbeat-collect-docs-on-update⇡$ git status
On branch metricbeat-collect-docs-on-update
Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

	modified:   module/aerospike/_meta/fields.yml
	modified:   module/aerospike/fields.go
```

**Comment by dedemorton** [comment]
I checked Filebeat and confirmed that `make docs` and `make docs-preview` do work for that beat, so it must be a metricbeat issue.

**Comment by dedemorton** [comment]
Seems like this commit broke the doc scripts for metricbeat: https://github.com/elastic/beats/commit/8786d05e3e55a46921dc2be195b7e7254ff0465c#diff-34acb1c4bf062801dbb1a2e9554fcfaf

**Comment by blakerouse** [comment]
@dedemorton Nice catch, I have updated the magefile to do the correct thing for the asciidocs on fields. I also added the `make doc` and `make doc-preview` shims, so those will work now in the metricbeat directory.

**Pull request merged**
