### PR TITLE
Update autoconfigure to stop on Docker delete events

### LINKED ISSUE #6694: Filebeat autodiscover should not stop docker prospectors until it reads all lines
I am using filebeat with autodiscover feature to read docker logs. When I stop and remove docker container, the prospector stops so it does not process latest logs from the container. I think it should reflect close_removed, so in case docker json log is missing it should still process remaining lines from its opened file descriptor. I am using filebeat 6.2.3.

So when autodiscover closes the prospector, it should check 2 conditions:
 1. Does docker container exists?
 2. Are all opened log files for this prospector already read?

```
filebeat.autodiscover:
  providers:
    - type: docker
      templates:
        - condition:
            and:
              - regexp:
                  docker.container.name: "^somename-.+"
              - not:
                  equals:
                    docker.container.id: "d2b3a6101c8f4644449cfcbc31f3057080e186bdbe7aad6a8d2a0982234bb852"
          config:
            - type: docker
              containers:
                ids:
                  - "${data.docker.container.id}"
                path: "/var/lib/docker/containers"
              close_inactive: 1h
              close_removed: false
              clean_removed: false
```

### PR DESCRIPTION
**Pull request by brianjones**
Fixes #6694

The Docker Autodiscover Provider was listening for "stop" events from Docker, which occur when a container stops. This immediatly stopped harvesting of the log file, often losing the end of the it. In the case of a failure, the end of the log file is the most important.

Fortunately, the common Docker component already generates "delete" events 60s after a container is stopped.

This PR changes the provider to use the delete event instead, allowing the rest of the log file to be harvested in that 60s.

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @brianjones, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/beats/pull/8488.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by exekias** [comment]
Hi @brianjones, I think this change would cause some modules to run forever if you stop on a container without deleting it. While we want to stop the module/input for that container.

Something we do in the `kubernetes provider` is [delaying stop events for a while](https://github.com/elastic/beats/blob/master/libbeat/autodiscover/providers/kubernetes/kubernetes.go#L117), I think something similar could be done here, what do you think?

**Comment by brianjones** [comment]
Hi @exekias, when a Docker container dies, the watcher component emits a `stop` event and adds the container ID to a `deleted` map. Every 60s, it iterates through this map, looks for entries over 60s old, and emits a `delete` event for them. So any container that is stopped will get a `delete` event if they are not restarted within 60 to 120s, regardless of whether or not the container is actually deleted.

Or at least that's my best reading of the code... and some of the integration tests that tripped me up would seem to back that up: e.g. `filebeat/tests/system/test_autodiscover.py` runs a Docker container which finishes after 1 second, but doesn't take any action to delete it - and it now gets a delete event within 130s rather than the original 10s.

I do quite like the approach taken by the `kubernetes provider`, but was trying to avoid massive changes to the current Docker implementation - I really just wanted it to give the harvester the extra 60s you mentioned in #6694.

**Comment by exekias** [comment]
Understood, btw you got the code right. I would be ok with exposing the 60s timeout as a configuration variable. Does that sound good to you?

I think we should closed this PR and open a new issue or PR for that

**Comment by brianjones** [comment]
Hi @exekias - I'm not sure what you're looking for: do you want
* to merge and close this PR and I'll open another one to allow the 60s be configured
* close this PR and create another one to cover both this change and one to allow the 60s be configured?

**Comment by exekias** [comment]
Hi, I would:

- Close this PR as the change breaks autodiscover for stopped but not deleted containers
- Open a pull request to add this 60s timeout, similar to what Kubernetes autodiscover does

Best regards

**Comment by brianjones** [comment]
@CpuID @exekias I'm afraid I'm unlikely to submit a new PR for this any time soon. Rewriting the module to follow the Kuberenetes approach of using time.AfterFunc is a pretty big undertaking... especially when this PR represents my sole development experience in Go to date.

This was PR was originally created in response to @exekias's assertion in #6694: "As of today we allow for 60s before notifying of container stop, to give Filebeat some time to retrieve the pending logs. In most cases, this is enough.". But the behaviour that you and I have observed is that this is not the case.

As far as I can tell, this PR as it stands implements that 60s delay correctly. The docker module as written only reacts to `die` events from Docker itself, and then emits a `stop` event immediately and a `delete` event 60 to 120s later (i.e. it checks every 60s for containers that have been dead for over 60s). The change I've made here is to stop the harverster in response to that second `delete` event rather than the first `stop` event.

I'm not sure I understand how it breaks "stopped but not deleted containers" since it's still only reacting to Docker's `die` event.

**Comment by exekias** [comment]
I'll have a look into this and try to provide a new PR, thank you for the detailed explanation!

**Comment by brianjones** [comment]
Closing this as it was solved differently by #10905

**Pull request closed without merging**
