### PR TITLE
In mysql.yml, clarify DSN format

### PR DESCRIPTION
**Pull request by smokris**

### CODE REVIEW

**Comment by jsoriano** [comment]
Hi @smokris,

Thanks for opening this PR!

Tests are failing because the file you have modified is generated from `module/mysql/_meta/config.reference.yml`. In principle the reference file should be modified first, and then you need to run `make update` so it is copied. Alternatively you can try to do the change in both files.

**Comment by jsoriano** [comment]
ok to test

**Comment by smokris** [comment]
@jsoriano, thanks for the feedback.  I modified the source file, ran `make update`, and pushed another version.  (I also updated `create-module.asciidoc` for consistency, since the same text appears there.)

**Comment by smokris** [comment]
Hmm, the `elastic+beats+pull-request+multijob-windows` failure doesn't seem to be related to this change.

**Comment by jsoriano** [comment]
> Hmm, the `elastic+beats+pull-request+multijob-windows` failure doesn't seem to be related to this change.

Yeah, something went bad on this Windows build, let's ignore this as doc checks are run in other builds.

**Pull request merged**
