### PR TITLE
Change image references to use block syntax not inline

### PR DESCRIPTION
**Pull request by dedemorton**
The beats docs use the inline image syntax (image:) for block images instead of (image::), the correct syntax. You don't see the problem in the docs because the images are all page width, but it's worth fixing for the future.

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
```a2x: ERROR: missing resource: /home/travis/gopath/src/github.com/elastic/beats/packetbeat/docs/:./images/filterforval_icon.png```CI failure seems to be related to this change 🤔

**Comment by dedemorton** [comment]
@kaiyan-sheng Good catch! I should have looked at the replacements more carefully.

**Comment by dedemorton** [comment]
docs passed CI, so I am merging.

**Comment by dedemorton** [comment]
Removing `needs_backport` label because the change is already in 7.2.

**Pull request merged**
