### PR TITLE
Use newer version of dbus for compatibility 

### PR DESCRIPTION
**Pull request by fearful-symmetry**
## What does this PR do?

Fixes a very dumb and subtle bug where a user couldn't set `DBUS_SYSTEM_BUS_ADDRESS` because the natively imported version of `godbus/dbus` and a version imported by the systemd helper libraries expected the env var key to be formatted different ways.

Note that we should follow this up with some documentation on how to properly use `DBUS_SYSTEM_BUS_ADDRESS` , but that's outside the scope of this.

## Why is it important?

This is a bug.

## Checklist

- [x] My code follows the style guidelines of this project
~- [ ] I have commented my code, particularly in hard-to-understand areas~
~- [ ] I have made corresponding changes to the documentation~
~- [ ] I have made corresponding change to the default configuration files~
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

Fixes https://github.com/elastic/elastic-agent/issues/2377

### CODE REVIEW

**Comment by fearful-symmetry** [comment]
Arg, those files haven't been touched in a while, will need to take some time to make the linter happy.

**Review by rdner — APPROVED** [review]

**Comment by cmacknz** [comment]
Is there a test we could add that would have caught this?

**Comment by fearful-symmetry** [comment]
@cmacknz Yah, I was thinking about this. Testing systemd stuff is kind of a pain, and we need at least one of the following:

1) A test that we can configure to _not_ run in a container, and just on a specified linux VM
2) A test that we can configure to run in a special container that mounts the dbus path from the host

Right now my understanding is that our testing infrastructure can't really do this, but I could be wrong?

**Comment by fearful-symmetry** [comment]
Yah, this is the error I was expecting:
```
error getting connection to system bus: dial unix /var/run/dbus/system_bus_socket: connect: no such file or directory
```
It's not a problem with Ubuntu itself, so I suspect it's either a quirk of the immutable images, or some permissions particular to jenkins.

**Comment by fearful-symmetry** [comment]
Currently working on spinning up an instance of the CI workers that I can poke around in.

**Comment by fearful-symmetry** [comment]
CI error appears unrelated.

**Review by cmacknz — APPROVED** [review]
Thanks for getting the test figured out!

**Pull request merged**
