### PR TITLE
[Elastic Agent] Remove beta warn and warn module

### LINKED ISSUE #26748: Changing Agent start up warning
The Agent start up warning should be reviewed and possibly changed before 7.14

https://github.com/elastic/beats/blob/7.14/x-pack/elastic-agent/pkg/agent/warn/warn.go#L14

For security vulnerabilities please only send reports to security@elastic.co.
See https://www.elastic.co/community/security for more information.

Please include configurations and logs if available.

For confirmed bugs, please report:
- Version: 
- Operating System: 
- Discuss Forum URL:
- Steps to Reproduce:

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Removes the log line and print line messages about Elastic Agent being in BETA.

## Why is it important?

For release of GA Elastic Agent.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #26748

### CODE REVIEW

**Comment by EricDavisX** [comment]
@mostlyjason @blakerouse @andresrc any reason not to push this out of draft and merge it?

**Comment by blakerouse** [comment]
@EricDavisX I was waiting on confirmation that we are going full GA for Elastic Agent in 7.14. If that is 100% sure then I can merge it.

**Comment by mostlyjason** [comment]
@blakerouse yes we already removed beta messaging on the fleet side

**Review by EricDavisX — APPROVED** [review]
looks ok to me.

**Pull request merged**
