### PR TITLE
[7.6] Generate haproxy module docs (#16776)

### PR DESCRIPTION
**Pull request by ycombinator**
Backports the following commits to 7.6:
 - Generate haproxy module docs  (#16776)

### CODE REVIEW

**Comment by dedemorton** [comment]
I don't think this is required. When you run `make update` or `mage fmt update`  on the other PR you have open, this file will get updated automatically.

**Comment by kaiyan-sheng** [comment]
```Error: some files are not up-to-date. Run 'mage fmt update' then review and commit the changes. Modified: [metricbeat/docs/modules/haproxy.asciidoc``` 
Seems like `mage fmt update` is needed.

**Comment by ycombinator** [comment]
Closing PR. Changes will be incorporated into https://github.com/elastic/beats/pull/16801.

**Comment by ycombinator** [comment]
Closing PR. Changes will be incorporated into https://github.com/elastic/beats/pull/16801.

**Pull request closed without merging**
