### PR TITLE
[Metricbeat] gcp: add README

### PR DESCRIPTION
**Pull request by endorama**
## What does this PR do?

Provide a README for `gcp` module.

## Why is it important?

The module is poorly documented from a dev perspective.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [ ] ~~I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Author's Checklist

- [ ]

## Related issues

- Supersede #16260 (only 10723 PR after :dancers:)

### CODE REVIEW

**Review by kaiyan-sheng — COMMENTED** [review]
Thanks for continuing on this work! I wonder for some of the implementation details, should we expose them here? Should we move this under observability repo?

**Comment by endorama** [comment]
@kaiyan-sheng Do we already have developer documentation about this module? The advantage of having the file here is that is public. I also think it's easier to edit/update contextually with the code.

Any drawbacks in keeping it here? We can reference it from the observability repo if needed.

**Comment by kaiyan-sheng** [comment]
@endorama Good point on keeping this documentation closer to the codebase. How about changing the file name to `readme_dev` or something similar? So users know this file includes implementation details that they might not care about 🙂

**Comment by endorama** [comment]
Renamed as `DEVELOPMENT.md` (inspired by other repos that use this nomenclature).

**Review by kaiyan-sheng — APPROVED** [review]
LGTM, thank you!

**Pull request merged**
