### PR TITLE
[Debug only] [filebeat] Workaround for missing offsets in Azure event hub response

### PR DESCRIPTION
**Pull request by faec**
This is a simple workaround for #14536. It's for testing only, while we decide next steps. So far this only works on event hubs with a single partition. If we want to make this into a "real" fix we would at minimum need to inspect the outgoing request and only add placeholder offsets for the specific partitions that are missing in the response.

### CODE REVIEW

**Comment by narph** [comment]
@faec , tested the workaround using several eventhubs but got different behaviors.
It will loop over all partitions and still get into the same error when reaching partition 1.
```
for topic, partitions := range claims {
		for _, partition := range partitions {
			pom, err := offsets.ManagePartition(topic, partition)
```
A similar scenario happens when the block is not null as well. Will look into details and provide more info soon.

**Comment by narph** [comment]
@faec , thanks for the multiple partitions workaround, works great

**Comment by exekias** [comment]
Thank you for working on this @faec! How do you feel about getting this in? I'm not sure about the implications, but it sounds like this case shouldn't happen when using Kafka itself. Is that correct?

**Comment by andresrc** [comment]
@faec can we close this one?

**Pull request closed without merging**
