### PR TITLE
Revert "[filebeat] Fix long filepaths in diagnostics exceeding max path limits on Windows"

### PR DESCRIPTION
**Pull request by jlind23**
Reverts elastic/beats#40909

@aleksmaus I am sorry I have to revert this but it introduced a problem with Elastic Agent where lock file on Windows remain and diagnostic are not being generated at all.

cc @ycombinator @cmacknz

### CODE REVIEW

**Review by pierrehilbert — APPROVED** [review]

**Comment by efd6** [comment]
@jlind23 What was the mechanism for that?

**Comment by jlind23** [comment]
@efd6 
On windows tests are always failing as you can see on the Elastic Agent main branch:
https://buildkite.com/elastic/elastic-agent-extended-testing/builds/3027#_
If you take one of the recent build failure on elastic agent main you'll see the problem.
Looks like the process PID on windows are always changing and we end up with a problem like:
image

**Comment by efd6** [comment]
OK, but I don't see how this change would cause that.

**Comment by jlind23** [comment]
@ycombinator can tell you more as he worked on the analysis yesterday and found out that this specific commit was the one causing problem.

**Comment by ycombinator** [comment]
> @ycombinator can tell you more as he worked on the analysis yesterday and found out that this specific commit was the one causing problem.

We are _suspecting_ that this commit might be the problem but haven't proved it definitively yet.  @efd6 I'll ping you on the Slack thread where we've been discussing this issue for the past couple of days so I don't have to duplicate the conversation and findings in both places.

**Comment by ycombinator** [comment]
Let's merge this to see if it unblocks Agent CI.  If it doesn't we'll revert this PR (revert the revert).

**Review by ycombinator — APPROVED** [review]

**Pull request merged**
