### PR TITLE
[Agent] Remove workaround outpout url returned by Fleet

### PR DESCRIPTION
**Pull request by nchaulet**
## Description 

The Fleet API has been fixed here (https://github.com/elastic/kibana/pull/54258 ) so we do not need rename anymore.

### CODE REVIEW

**Comment by ph** [comment]
do not merge before https://github.com/elastic/kibana/pull/54258

**Comment by nchaulet** [comment]
@ph it's ok to merge even if the CI is not passing?

**Comment by ph** [comment]
I am going to take a look the failures, we have a timeout and strangely I haven't seen that before.

**Comment by nchaulet** [comment]
@ph agent tests passed, it's normal that other tests failed?

**Comment by ph** [comment]
@nchaulet  Can you rebase and run `mage update` ?

**Pull request merged**
