### PR TITLE
Provide 'Done' signaling via beat.Done

### PR DESCRIPTION
**Pull request by urso**

### CODE REVIEW

**Comment by ruflin** [comment]
After we introduced "waitSignal" in filebeat, this starts to look even more natural to be used. Some thoughts for this PR to go forward:

* I suggest to introduce the new `beat.Done` signal in a separate PR (without changing the existing beats)
* Introduce the Done channel for the publisher logic and make Stop and additional interface
* Introduce it in all beats and remove old channels

The reason for this split up is to make it for community beats creater easier to track what happened. Most of the beats will not be affected by the PR's. The first two PR's are enhancements which are made in the background. Only the last PR makes the "optional" change to our beats. Currently it seems like we can keep all these changes BC compatible.

**Comment by urso** [comment]
I also see this PR as complementary.

Th PR is already fully BC compatible. If Beat implements 'Stop', it's automatically added into list of stop-callbacks.

**Comment by ruflin** [comment]
@urso The change I would propose above is to split the PR in 3 PR's, so we could point beats developer to a much simpler PR which only contains the migration part of beats from old to new.

**Comment by monicasarbu** [comment]
@urso Should we close this PR as it's too old?

**Comment by urso** [comment]
Yeah, it's quite old, let's close it.

Still, I'm planning to get this in, in one way or the other. This will also help with potential races on `Stop` and simplify the beater interface.

**Comment by ruflin** [comment]
+1 on doing this one day :-)

**Pull request closed without merging**
