### PR TITLE
update 7.x test images to 7.7.0

### PR DESCRIPTION
**Pull request by graphaelli**
## What does this PR do?

update 7.x tests images to 7.7.0

## Why is it important?

7.x tests are using the wrong stack version

### CODE REVIEW

**Comment by graphaelli** [comment]
`test_fileset_file_053_system` and `test_fileset_file_059_system` are failing - I'm not clear on whether these are transient / known / etc - @mikemadden42 thoughts on how to proceed?

**Comment by mikemadden42** [comment]
> `test_modules.Test.test_fileset_file_053_system` and `test_modules.Test.test_fileset_file_059_system` are failing on travis, `test_modules.Test.test_fileset_file_094_system` and `test_modules.Test.test_fileset_file_098_system` on jenkins - I'm not clear on whether these are transient / known / etc - @mikemadden42 thoughts on how to proceed?

I have not seen these tests failing.  I can look into it.

**Comment by mikemadden42** [comment]
jenkins retest this please

**Comment by mikemadden42** [comment]
@graphaelli - I looked into the current Jenkins failures when using your branch, foo-x-y.

`make -C filebeat clean check testsuite`

I'm seeing this failure when I build locally:

```
--- FAIL: TestReadConfig2 (0.00s)
--- FAIL: TestMergeConfigFiles (0.00s)
--- FAIL: TestLoadManifestNginx (0.00s)
```

`make -C metricbeat clean check testsuite`

I'm seeing this failures whenI build locally.

```
--- FAIL: TestLightModulesAsModuleSource (0.00s)
    --- FAIL: TestLightModulesAsModuleSource/no_registered_modules (0.00s)
        --- FAIL: TestLightModulesAsModuleSource/no_registered_modules/metricsets_for_service (0.00s)
        --- FAIL: TestLightModulesAsModuleSource/no_registered_modules/default_metricsets_for_service (0.00s)
    --- FAIL: TestLightModulesAsModuleSource/same_module_registered_(mixed_modules_case) (0.00s)
        --- FAIL: TestLightModulesAsModuleSource/same_module_registered_(mixed_modules_case)/metricsets_for_service (0.00s)
        --- FAIL: TestLightModulesAsModuleSource/same_module_registered_(mixed_modules_case)/default_metricsets_for_service (0.00s)
    --- FAIL: TestLightModulesAsModuleSource/some_metricsets_registered (0.00s)
        --- FAIL: TestLightModulesAsModuleSource/some_metricsets_registered/metricsets_for_service (0.00s)
        --- FAIL: TestLightModulesAsModuleSource/some_metricsets_registered/default_metricsets_for_service (0.00s)
--- FAIL: TestNewModuleFromConfig (0.01s)
    --- FAIL: TestNewModuleFromConfig/light_module_default_metricset (0.00s)
    --- FAIL: TestNewModuleFromConfig/light_module_override_option (0.00s)
    --- FAIL: TestNewModuleFromConfig/light_module (0.01s)
    --- FAIL: TestNewModuleFromConfig/light_module_with_query (0.00s)
    --- FAIL: TestNewModuleFromConfig/light_module_with_custom_period (0.00s)
    --- FAIL: TestNewModuleFromConfig/mixed_module_with_standard_and_light_metricsets (0.00s)
--- FAIL: TestLightMetricSet_VerifyHostDataURI (0.00s)
--- FAIL: TestLightMetricSet_WithoutHostParser (0.00s)
--- FAIL: TestLightMetricSet_VerifyHostDataURI_NonParsableHost (0.00s)
--- FAIL: TestNewModulesCallModuleFactory (0.00s)
--- FAIL: TestProcessorsForMetricSet_ProcessorsRead (0.00s)
--- FAIL: TestProcessorsForMetricSet_FromSource (0.00s)
```

Are this also failing locally for you?

**Comment by mikemadden42** [comment]
@graphaelli - I looked into the current Travis failures when using your branch, update-7.x-test-snapshots.  This looks consistent with what we're seeing on Jenkins.

`make -C filebeat testsuite`

I'm seeing this failure when I build locally:

```
--- FAIL: TestReadConfig2 (0.00s)
--- FAIL: TestMergeConfigFiles (0.00s)
--- FAIL: TestLoadManifestNginx (0.00s)
```

**Comment by graphaelli** [comment]
@mikemadden42 would you be able to apply #16175 and see if those still fail?  I haven't set up to reproduce locally, I need this change to ensure the next beats sync doesn't revert the same change needed in apm-server.

**Comment by mikemadden42** [comment]
@graphaelli , I'm still seeing those failures with the changes.

```
$ grep FAIL: ~/make.log
--- FAIL: TestReadConfig2 (0.00s)
--- FAIL: TestMergeConfigFiles (0.00s)
--- FAIL: TestLoadManifestNginx (0.00s)

$ git diff
diff --git a/filebeat/module/system/auth/test/timestamp.log-expected.json b/filebeat/module/system/auth/test/timestamp.log-expected.json
index 2b881dc5f..0f9022325 100644
--- a/filebeat/module/system/auth/test/timestamp.log-expected.json
+++ b/filebeat/module/system/auth/test/timestamp.log-expected.json
@@ -1,6 +1,6 @@
 [
     {
-        "@timestamp": "2019-06-14T08:40:20.912-02:00",
+        "@timestamp": "2019-06-14T10:40:20.912-02:00",
         "event.dataset": "system.auth",
         "event.module": "system",
         "event.timezone": "-02:00",
@@ -27,4 +27,4 @@
         "process.name": "pam",
         "service.type": "system"
     }
-]
\ No newline at end of file
+]
diff --git a/filebeat/module/system/syslog/test/tz-offset.log-expected.json b/filebeat/module/system/syslog/test/tz-offset.log-expected.json
index 0e9c7d984..9f0a18dee 100644
--- a/filebeat/module/system/syslog/test/tz-offset.log-expected.json
+++ b/filebeat/module/system/syslog/test/tz-offset.log-expected.json
@@ -29,7 +29,7 @@
         "service.type": "system"
     },
     {
-        "@timestamp": "2019-06-14T08:40:20.912-02:00",
+        "@timestamp": "2019-06-14T10:40:20.912-02:00",
         "event.dataset": "system.syslog",
         "event.module": "system",
         "event.timezone": "-02:00",
@@ -42,4 +42,4 @@
         "process.name": "sudo",
         "service.type": "system"
     }
-]
\ No newline at end of file
+]
```

**Comment by jsoriano** [comment]
Feel free to include the changes of https://github.com/elastic/beats/pull/16175 in this PR so both changes are tested and merged together.

**Comment by graphaelli** [comment]
travis is green, jenkins failures appear to be transient - merging.

**Comment by jsoriano** [comment]
Thanks!

**Pull request merged**
