### PR TITLE
[Metricbeat]Kubernetes: make state_container metricset ECS compliant

### PR DESCRIPTION
**Pull request by odacremolbap**
Move existing field `kubernetes.container.id`, at `state_container` kubernetes metricset, to the ECS compliant fields.

Origin field contains a string prefixed by the container runtime, and suffixed with the container ID
New fields populated are 
- `container.runtime` 
- `container.id`

Previous field won't be removed until `8.0` elastic stack release.

Fixes https://github.com/elastic/beats/issues/10926

### CODE REVIEW

**Comment by odacremolbap** [comment]
@kaiyan-sheng thanks for taking a look.
new fields are ECS, so I guess they don't

**Comment by odacremolbap** [comment]
jenkins test this

**Comment by odacremolbap** [comment]
jenkins, test this

**Comment by odacremolbap** [comment]
jenkins, test this

**Comment by odacremolbap** [comment]
jenkins, test this

**Comment by odacremolbap** [comment]
manual testing:
- run ES + optionally kibana
- deploy kubernetes (could be minikube) and kube-state-metrics as stated [here](https://github.com/elastic/beats/tree/master/metricbeat/module/kubernetes/_meta/test)
- deploy metricbeat, you can either use an build candidate image, or use the release branch and the playground pod.
- configure `state_container` metricset:
```
- module: kubernetes
  enabled: true
  metricsets:
    - state_container
  period: 10s
  hosts: ["kube-state-metrics.kube-system:8080"]
  in_cluster: true
```

Expected behaviour:
- Events must still contain `kubernetes.container.id`
- Field `container.runtime` exists, and contains the container runtime used
- Field `container.id` exists, and contains the container unique identifier
- All new fields are already mapped by ECS (no `?` shown at kibana

**Comment by tbragin** [comment]
@sorantis @sgrodzicki @jasonrhodes Do we need any special handling for this change on the Metrics UI front, especially as we move toward 8.0 where the old fields are going to be removed?

**Comment by sgrodzicki** [comment]
@simianhacker probably knows best

**Comment by kaiyan-sheng** [comment]
We are looking at removing old fields here in 8.0. @simianhacker Could you confirm here that metrics UI is already switched to use the new field names? TIA!!

**Comment by MichaelKatsoulis** [comment]
@kaiyan-sheng  after discussions in https://github.com/elastic/beats/issues/23585#issuecomment-917895144 we will remove      only `kubernetes.container.image` in 8.0 as its value is  duplicated to ECS field `container.image.name`. 
@simianhacker can you confirm that this field is not used in Metrics UI ?

**Pull request merged**
