### PR TITLE
Add NATS Filebeat dashboard

### PR DESCRIPTION
**Pull request by ChrsMark**
This PR is part of  #10071.

Co-Authored-By: Stamatis Katsaounis <katsaouniss@gmail.com>
Co-Authored-By: Michael Katsoulis <michaelkatsoulis88@gmail.com>

### CODE REVIEW

**Comment by ChrsMark** [comment]
Screenshot from 2019-03-09 00-03-02

**Comment by ChrsMark** [comment]
filebeatdashboard

**Comment by ChrsMark** [comment]
Taking the opportunity to mention here that the importing procedure of Filebeat's dashboards is quite tricky. Actually I was not able to import the dashboards with `make import-dashboards` as I had done with Metricbeat's in the past.

In order to make it work for me I copied Metricbeat's Makefile approach, so I add the following lines in the Makefile of Filebeat: 
```
# Collects all module dashboards
.PHONY: kibana
kibana:
       @rm -rf _meta/kibana.generated
       @mkdir -p _meta/kibana.generated
       @-cp -pr module/*/_meta/kibana/* _meta/kibana.generated
```

Then I run:
1. `make kibana`
2. `python ../libbeat/scripts/unpack_dashboards.py --glob="./_meta/kibana.generated/7/dashboard/*.json"`
3. `make import-dashboards`

Is there a more solid way to achieve this? Despite I searched a lot I didn't find anything so I had to dive into the code to tackle this.

**Comment by ruflin** [comment]
jenkins, test this

**Comment by ruflin** [comment]
The way I test it is: `./filebeat -E setup.dashboards.directory=./build/kibana/ -e`. In Filebeat the generated dashboards are under `build/kibana`. We plan to unify this moving forward.

**Comment by skatsaounis** [comment]
@ruflin: Hi Nicolas! A quick info: I found out that this PR is not part of 7.x branch. I do not know if it happens for a reason or it was mistakenly not back-ported.

**Comment by ruflin** [comment]
We do bulk backports to 7.x once a week. Seems like we didn't do one since this got merged, but it will happen soon ;-)

**Pull request merged**
