### PR TITLE
Migrate needed .ci/* scripts into .buildkite/* ( elastic#3353 )

### PR DESCRIPTION
**Pull request by ev1yehor**
## Proposed commit message

Migrate needed .ci/* scripts into .buildkite/* and change path for them.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Relates https://github.com/elastic/ingest-dev/issues/3353

### CODE REVIEW

**Review by oakrizan — COMMENTED** [review]
There is no docker-compose.yml on 7.17. I believe that file shouldn't be backported there. WDYT @dliappis?

**Review by dliappis — APPROVED** [review]
LGTM

seems that docker-compose got trigger as expected: https://buildkite.com/elastic/beats-xpack-filebeat/builds/3013#018fba0c-7e0b-43ad-b640-57c0f0689171/157-158

**Pull request merged**
