### PR TITLE
Adding threads_cached,threads_created,threads_connected,threads_running to mysql module exports.

### PR DESCRIPTION
**Pull request by claygorman**
See https://discuss.elastic.co/t/mysql-exports/59899 for information.

### CODE REVIEW

**Comment by karmi** [comment]
Hi @claygorman, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/beats/pull/2484.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by claygorman** [comment]
Hey @karmi, sorry about that! I have added the other email. I hope that does it?

Thanks!

**Comment by ruflin** [comment]
@claygorman Thanks a lot for the PR. CLA looks good now. A few more things that need to be done:

* Build complains that not all fields are documented. To fix this you have to update fields.yml (https://github.com/elastic/beats/blob/master/metricbeat/module/mysql/status/_meta/fields.yml) with the new fields. As soon as the fields are added there, run `make collect` and it will updated to docs, templates etc. automatically
* Update the CHANGELOG.asciidoc with this change

This should fix the CI issue. Let me know if you need some more details.

**Comment by claygorman** [comment]
Ok thanks! I ran `make collect` but it says `make: *** No rule to make target `collect'.  Stop.`.

What path should I run this command from?

On the `CHANGELOG.asciidoc` do I add my changes to line 9 or do I add them on line 91?

Thank you for your guidance.

**Comment by claygorman** [comment]
Ok I believe I resolved the conflict. Please let me know if it looks ok.

Thanks

**Comment by andrewkroh** [comment]
> Please let me know if it looks ok.

No, it doesn't look correct since the changeset includes a bunch of other people's commits.

**Comment by claygorman** [comment]
@andrewkroh,

I am unsure how to resolve that? Pulling in latest master to rebase my changes will pull in commits presently found in elastic/beats master branch.

**Comment by claygorman** [comment]
Looking at other peoples changelog additions I modified mine to have my change. Is this what you mean? https://github.com/elastic/beats/pull/2484/commits/00dea038fa3b1e2185cd314aff747fdcdc707cde

**Comment by andrewkroh** [comment]
@claygorman Yeah, it looks like you fixed it :)

jenkins, test it

**Comment by ruflin** [comment]
jenkins, test it

**Comment by ruflin** [comment]
jenkins, retest it

**Comment by ruflin** [comment]
@claygorman Merged. Thanks a lot for the contribution. It should be available in the next hours in the snapshot builds: https://beats-nightlies.s3.amazonaws.com/index.html?prefix=filebeat/

**Comment by claygorman** [comment]
Thanks!

**Comment by claygorman** [comment]
I noticed in https://beats-nightlies.s3.amazonaws.com/index.html?prefix=metricbeat/ the last file modified date was 2016-09-07T10:06:33.000Z and it is currently 2016-09-09T16:59:44.781Z.

Seems like snapshot hasn't been updated in 2 days (I assume its at ~10:00 every day)?

**Comment by andrewkroh** [comment]
It's fixed now. New snapshots are published.

**Comment by claygorman** [comment]
awesome you guys have been very helpful!

**Pull request merged**
