### PR TITLE
[CM] Parse enrollment_token response correctly

### PR DESCRIPTION
**Pull request by michalpristas**
Followup to #11377 

Fixes enrollment token response to be parsed correctly according to a new response format

### CODE REVIEW

**Comment by ph** [comment]
Jenkins test this please

**Comment by ph** [comment]
I've rekick the jenkins test suite, I saw a weird error with the runbld execution.

**Comment by michalpristas** [comment]
@ph this is how i found out, i enabled the tests which were disabled and all of them started failing on enroll.

**Comment by michalpristas** [comment]
Jenkins test this please

**Comment by ph** [comment]
@michalpristas we seen to have a few problem with dockers images in tests, lets try to run them again.

But looking at the `x-pack/libbeat` tests I think we are fine.

```
----------------------------------------------------------------------
XML: /go/src/github.com/elastic/beats/x-pack/libbeat/build/TEST-system.xml
[success] 50.51% test_management.TestManagement.test_fetch_configs: 15.0651s
[success] 42.29% test_management.TestManagement.test_configs_cache: 12.6123s
[success] 6.58% test_management.TestManagement.test_enroll: 1.9617s
[success] 0.63% test_management.TestManagement.test_enroll_bad_pw: 0.1868s
----------------------------------------------------------------------
Ran 4 tests in 29.833s
```

**Comment by ph** [comment]
```
ava.nio.file.InvalidPathException: Malformed input or input contains unmappable characters: /var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-linux/beat/x-pack/libbeat/label/linux-immutable/src/github.com/elastic/beats/x-pack/libbeat/build/system-tests/run/test_management.TestManagement.test_enroll/mockbeat.yml.���.bak
```

I think its a bit I've introduced in #11034

**Comment by michalpristas** [comment]
looks like it will get green now

**Pull request merged**
