### PR TITLE
Update generalconfig.asciidoc

### PR DESCRIPTION
**Pull request by DominikMoelter**
Tested this and the default was millisecond

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by rdner — APPROVED** [review]
I can confirm that the default value in the code is `millisecond`

https://github.com/elastic/beats/blob/c348a3135f17467cd1ca6923d3740a06de8399a5/libbeat/common/datetime.go#L37

**Comment by rdner** [comment]
@DominikMoelter just for future contributions: it's better to fix something in the `main` branch and then backport to 8.5. We have an automation for it but not the other way around.

**Comment by rdner** [comment]
@DominikMoelter may I ask you to sign the CLA? https://www.elastic.co/contributor-agreement

**Comment by DominikMoelter** [comment]
@rdner thank you for advise. CLA is signed ✅

**Pull request merged**
