### PR TITLE
[Ingest Manager] Agent fetching DBus service PID fix

### PR DESCRIPTION
**Pull request by michalpristas**
## What does this PR do?

For some reason debian9 is not happy when quering service without `.service` suffix just by a service name. 
Adding that debian does not complain anymore

## Why is it important?

This prevents us from monitoring PID and checking agent crashes. If agent crashes constantly status checker will know and rollback instead of this crash checker, so i would not say it's that critical.

Fixes: #23488

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by michalpristas** [comment]
cc @EricDavisX

**Comment by EricDavisX** [comment]
thx - are we intending backports for 7.11?  up to you.

**Comment by michalpristas** [comment]
yes i wanted to backport this one

**Review by blakerouse — APPROVED** [review]
Oh debian.... Looks good!

**Pull request merged**
