### PR TITLE
fix TCP input message size problem, issue#11966

### PR DESCRIPTION
**Pull request by jiayuchen**
When Filebeat uses TCP input, we can set the option `max_message_size` as maximum size in bytes of the message received over TCP. But, there is another option that limits the message size when Filebeat calls 

> scanner.Scan()

 to collect data: `MaxScanTokenSize,` the meaning of this option is the maximum size used to buffer a message. Filebeat does not override `MaxScanTokenSize` with `max_message_size`, which causes an error when the value of `max_message_size` we set is greater than `MaxScanTokenSize` and the length of our message is greater than `MaxScanTokenSize` and less than `max_message_size.` (position: filebeat/inputsource/tcp) . beats version: 6.5.4, but 7.0 also has this problem.

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @jiayuchen, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/beats/pull/11967.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by ph** [comment]
@jiayuchen Thanks for the PR, could you sign the [CLA](https://www.elastic.co/contributor-agreement) and it is possible to add a unit test to verify the problem?

**Comment by jiayuchen** [comment]
how to recheck?

**Comment by jiayuchen** [comment]
> sign the [CLA](https://www.elastic.co/contributor-agreement)
i hava  signed the CLA, but how to recheck?

**Comment by ph** [comment]
@jiayuchen Did you sign the CLA with the same email as defined in https://patch-diff.githubusercontent.com/raw/elastic/beats/pull/11967.patch

**Comment by jiayuchen** [comment]
Sorry, I made a mistake.

**Comment by jiayuchen** [comment]
> @jiayuchen Did you sign the CLA with the same email as defined in https://patch-diff.githubusercontent.com/raw/elastic/beats/pull/11967.patch

Sorry, I made a mistake.

**Pull request closed without merging**
