### PR TITLE
[Filebeat] aws-s3 - create beat.Client for each SQS worker

### PR DESCRIPTION
**Pull request by andrewkroh**
## What does this PR do?

To address mutex connection in the single beat.Client used for publishing S3 events, create a unique beat.Client for each worker goroutine that is processing an SQS message. The beat.Client is used for all S3 objects contained within the SQS message (they are processed serially). After all events are ACKed the beat.Client is closed.

## Why is it important?

A mutex profile of the aws-s3 input showed that there was a lot of contention for the "Publish()" lock.

https://github.com/elastic/beats/blob/3e928b702b660d5cf31e8f3090c57f2feb541338/libbeat/publisher/pipeline/client.go#L72-L77

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related

- https://github.com/elastic/beats/issues/32278#issuecomment-1182736420
## Pprof Mutex

I ran Filebeat for 90s with `max_number_of_messages: 5`.

#### Before

```
(pprof) top10
Showing nodes accounting for 48.18s, 100% of 48.18s total
      flat  flat%   sum%        cum   cum%
    48.18s   100%   100%     48.18s   100%  sync.(*Mutex).Unlock
         0     0%   100%     48.18s   100%  github.com/elastic/beats/v7/filebeat/beater.(*countingClient).Publish
         0     0%   100%     48.18s   100%  github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).Publish
         0     0%   100%     48.18s   100%  github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*s3ObjectProcessor).ProcessS3Object
         0     0%   100%     48.18s   100%  github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*s3ObjectProcessor).publish
         0     0%   100%     48.18s   100%  github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*s3ObjectProcessor).readFile
         0     0%   100%     48.18s   100%  github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*sqsReader).Receive.func1
         0     0%   100%     48.18s   100%  github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*sqsS3EventProcessor).ProcessSQS
         0     0%   100%     48.18s   100%  github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*sqsS3EventProcessor).processS3Events
```

#### After

```
(pprof) top10
Showing nodes accounting for 46.26ms, 100% of 46.26ms total
Showing top 10 nodes out of 14
      flat  flat%   sum%        cum   cum%
   46.26ms   100%   100%    46.26ms   100%  sync.(*Mutex).Unlock (inline)
         0     0%   100%    46.26ms   100%  github.com/elastic/beats/v7/filebeat/beater.(*countingClient).Publish
         0     0%   100%    46.26ms   100%  github.com/elastic/beats/v7/libbeat/common/acker.(*eventDataACKer).AddEvent
         0     0%   100%     1.67ms  3.61%  github.com/elastic/beats/v7/libbeat/common/acker.(*trackingACKer).AddEvent
         0     0%   100%     1.67ms  3.61%  github.com/elastic/beats/v7/libbeat/common/acker.(*trackingACKer).addPublishedEvent
         0     0%   100%    46.26ms   100%  github.com/elastic/beats/v7/libbeat/common/acker.ackerList.AddEvent
         0     0%   100%    46.26ms   100%  github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).Publish
         0     0%   100%    46.26ms   100%  github.com/elastic/beats/v7/libbeat/publisher/pipeline.(*client).publish
         0     0%   100%    46.26ms   100%  github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*s3ObjectProcessor).ProcessS3Object
         0     0%   100%    46.26ms   100%  github.com/elastic/beats/v7/x-pack/filebeat/input/awss3.(*s3ObjectProcessor).publish
```

### CODE REVIEW

**Comment by efd6** [comment]
I'm wondering if https://github.com/elastic/beats/blob/3e928b702b660d5cf31e8f3090c57f2feb541338/libbeat/publisher/pipeline/client.go#L72-L77 could be further improved to reduce contention.

If it's guaranteed that X can't panic, then it can be rewritted as 
```
func (c *client) Publish(e beat.Event) {
	c.mutex.Lock()
	c.publish(e)
	c.mutex.Unlock()
}
```
which will reduce the time during the locked state.

If that can't be guaranteed, then this makes some (less) reduction without the potential for leaving the mutex in the locked state, by retaining the deferred unlock, but not locking until the defer is constructed.
```
func (c *client) Publish(e beat.Event) {
	defer c.mutex.Unlock()
	c.mutex.Lock()

	c.publish(e)
}
```

**Comment by andrewkroh** [comment]
I remember back in Go 1.14 the release notes came out saying that `defer` incurred almost zero overhead due to https://github.com/golang/proposal/blob/master/design/34481-opencoded-defers.md. I've never tried to measure the speed of defer vs no defer.

It is possible that a processor could panic so I would be wary of removing the `defer`.

> 	defer c.mutex.Unlock()
>	c.mutex.Lock()

Interesting, I've never seen code that uses this ordering. I realize that it has the same outcome. What makes this any different?

**Review by aspacca — APPROVED** [review]

**Comment by efd6** [comment]
> Interesting, I've never seen code that uses this ordering. I realize that it has the same outcome. What makes this any different?

The time taken is the same, but less of that time is in the locked state.

**Pull request merged**
