### PR TITLE
Adjust host fields in Metricbeat to use ECS 1.9.0 field names

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
## What does this PR do?

With additional host fields get into ECS 1.9.0, we need to adjust the fields we added into Metricbeat to adopt the ECS field names.

- [x] system module
- [x] aws module
- [x] azure module
- [x] gcp module

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by narph** [comment]
@kaiyan-sheng , have you checked if these changes affected any of the dashboards? I have a feeling we are using some of the fields in the visualizations?

**Review by sayden — APPROVED** [review]
All good! But I haven't checked the dashboards though

**Comment by kaiyan-sheng** [comment]
Thanks @sayden @narph ! These fields are brand new actually, we added them when we started the inventory schema work. So they are not used in any dashboards or visualizations yet. They will be adopted in kibana metrics UI soon and that's why I want to get this in soon so the UI doesn't have to make the naming change again.

**Review by narph — APPROVED** [review]

**Review by fearful-symmetry — APPROVED** [review]

**Pull request merged**
