### PR TITLE
packetbeat: update nfs packets processing 

### PR DESCRIPTION
**Pull request by kofemann**
accumulate PR. Highlights:

   - refactoring to better code
   - keep fix src/dst addresses in correct order independent from first packet seen
   - use unique key (baeed on client ip + rpc transaction id ) in cache
   - fix stream initialization - first packet was always lost

### CODE REVIEW

**Comment by ruflin** [comment]
jenkins, test it

**Comment by monicasarbu** [comment]
@kofemann Can you please rebase to master?

**Comment by kofemann** [comment]
@monicasarbu  rebased on top of current (3994e49) master

**Comment by monicasarbu** [comment]
@kofemann It's merged. Thanks!

**Comment by kofemann** [comment]
Thanks, @monicasarbu .

**Pull request merged**
