### PR TITLE
[Filebeat] Update Grok pattern for UDM logs

### LINKED ISSUE #25615: Iptables module unable to parse some logs from UDM-Pro device
I'm using the Iptables module of Filebeat (`master` branch on Github, commit `ddcf8f1aa`) to receive and parse logs from a Unifi Dream Machine Pro over UDP. My module configuration looks like this:

    - module: iptables
      log:
        enabled: true

The data is sent from the beat to a Logstash pipeline. That pipeline does no processing/parsing of the message itself. It just sends the incoming data into the appropriate Elasticsearch index. All of the message processing happens using the ingest pipeline provided by the Iptables module.

Most of the sample log data I've tested parses fine, however there are a handful of logs (about 70 out of 3800) that fail to parse properly by the module.

Here's a few logs that fail to parse:

    May  5 20:46:45 My-Office-Gateway user.info kernel: TTL=126 ID=15317 DF PROTO=TCP SPT=59344 DPT=443 WINDOW=8212 RES=0x00 ACK PSH URGP=0
    May  5 20:46:46 My-Office-Gateway user.info kernel:  TTL=126 ID=51392 DF PROTO=TCP SPT=51653 DPT=7914 WINDOW=1024 RES=0x00 ACK PSH URGP=0
    May  5 20:46:46 My-Office-Gateway user.info kernel: L=126 ID=8698 DF PROTO=TCP SPT=88 DPT=51179 WINDOW=2053 RES=0x00 ACK URGP=0
    May  5 20:47:09 My-Office-Gateway user.info kernel: 0 TTL=126 ID=15461 DF PROTO=TCP SPT=59289 DPT=443 WINDOW=8208 RES=0x00 ACK PSH URGP=0
    May  5 20:46:56 My-Office-Gateway user.info kernel: L=126 ID=8702 DF PROTO=TCP SPT=88 DPT=51182 WINDOW=2053 RES=0x00 ACK URGP=0
    May  5 20:45:44 My-Office-Gateway user.info kernel: TL=126 ID=4622 DF PROTO=TCP SPT=389 DPT=49209 WINDOW=8192 RES=0x00 ECE ACK SYN URGP=0

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Updates the IPtables ingest pipeline with an additional grok pattern.

## Why is it important?

The module currently isn't able to parse some log entries created by the UDM pro

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have made corresponding change to the default configuration files
- [X] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes #25615

### CODE REVIEW

**Comment by legoguy1000** [comment]
@JAndritsch Let me know what you think for these changes.  Also if you find out anything on the weird format of these logs, let me know.

**Comment by JAndritsch** [comment]
> @JAndritsch Let me know what you think for these changes. Also if you find out anything on the weird format of these logs, let me know.

I'll try to test them out today. I just posted an issue on the Ubiquiti forums, so hopefully that'll help shed some light on things.

https://community.ui.com/questions/Strange-UDM-Pro-log-formatting/27969dc6-78eb-4d17-9417-38d252c62ce9

**Comment by JAndritsch** [comment]
I just had a chance to test these changes. It looks like the sample messages I gave you now parse properly. I was hoping to hear back from the UI forums this gets merged, but it's quiet over there.

**Comment by P1llus** [comment]
run tests

**Comment by P1llus** [comment]
run tests

**Pull request merged**
