### PR TITLE
Make file system metadata values strings

### PR DESCRIPTION
**Pull request by rdner**
To better align with ECS and better store the values in Elasticsearch.

## Checklist

- [x] My code follows the style guidelines of this project
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

See steps in https://github.com/elastic/beats/pull/36065

## Related issues

- Closes https://github.com/elastic/beats/issues/36695
- Relates https://github.com/elastic/integrations/pull/7716

### CODE REVIEW

**Comment by bhapas** [comment]
Possible to backport this to `8.10` ?

**Comment by rdner** [comment]
@jlind23 it's technically a breaking change, do you think we can backport it to 8.10 anyway? It would fix some things for integration developers.

**Comment by jlind23** [comment]
@rdner No we shouldn't backport any breaking change in a patch release. 8.11 is lined up to be out soon so better stick with 8.11.

**Review by ycombinator — APPROVED** [review]
LGTM.

**Pull request merged**
