### PR TITLE
Fix logstash output config examples

### LINKED ISSUE #33480: Suggested configuration of Logstash output is broken
The suggested Elasticsearch output for Logstash configuration in https://github.com/elastic/beats/blob/main/libbeat/outputs/logstash/docs/logstash.asciidoc doesn't work as is because of this bug https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/1070

The workaround is to add `action => "create"` to the config
```
output {
  elasticsearch {
    hosts => ["http://localhost:9200"]
    index => "%{[@metadata][beat]}-%{[@metadata][version]}"
    action => "create"
  }
}
```
The documentation should include the workaround (and explain why) until the bug is fixed.

### PR DESCRIPTION
**Pull request by dedemorton**
Fixes #33480

### CODE REVIEW

**Comment by dedemorton** [comment]
Can someone on the dev team please confirm this fix? cc @cmacknz

**Comment by cmacknz** [comment]
@jsvd can you sanity check the 1 additional line of Logstash syntax here?

**Review by jsvd — COMMENTED** [review]
The create action needs to be set when indexing to data streams since they don't support update/delete/index.
I'm not sure these examples are strictly scoped to data streams? the last one mentions ILM, but even index aliases support deletes.

**Comment by dedemorton** [comment]
@jsvd 
>The Beats use data streams by default (I think starting in 8.x or possibly earlier), so I think we _can_ assume these examples are scoped to data streams, no?

**Comment by dedemorton** [comment]
@jsvd Are the changes here valid? Ready to merge? If so, I need approval. Thanks!

**Review by jsvd — APPROVED** [review]
The need to have this setting can be considered a bug, and we have an issue to track defaulting to "create" when datastreams are used https://github.com/logstash-plugins/logstash-output-elasticsearch/issues/1070.
That said the current state of things requires this configuration, so LGTM.

**Comment by dedemorton** [comment]
@jsvd I'll try to backport this change to 8.0 and later (if it goes smoothly), but let me know if I should not backport it that far. Thanks!

**Pull request merged**
