### PR TITLE
[Agent] Remove heartbeat from bundled beats in agent.

### PR DESCRIPTION
**Pull request by andrewvc**
This keeps most of the changes in https://github.com/elastic/beats/pull/20488 but un-bundles heartbeat since it's not ready for prime time yet. We may as well keep the work that has been done already, but keep it somewhat out of the way and undocumented / unsupported for now. We will open a separate issue for removing the package.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by michalpristas** [comment]
you need to update packages.yml as well otherwise it will be looking for heartbeat in a drop location provided by release build
look for `downloads/heartbeat-{{ beat_version }`

**Comment by andrewvc** [comment]
@michalpristas thanks for taking a look. I've updated `packages.yml`, can you take a look?

**Comment by michalpristas** [comment]
looking/testing

**Review by michalpristas — APPROVED** [review]
Looks ok

**Comment by ph** [comment]
@andrewvc Can we merge this/backport it?

**Pull request merged**
