### PR TITLE
Add JSON options to autodiscover hints

### LINKED ISSUE #12634: Add JSON options to hints
Hints based autodiscover provides a way for user to configure how a containers logs will be ingested. It would be nice to add existing JSON parameters as hints, making it possible for containers logging JSON documents to be configured in a way that would make Filebeat decode these.

I think al the existing json options make sense: https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-log.html#filebeat-input-log-config-json, so they would look like this:

```
co.elastic.logs/json.keys_under_root
co.elastic.logs/json.add_error_key
co.elastic.logs/json.message_key
``` 

More details: https://discuss.elastic.co/t/decode-json-logs-filebeat-docker-hints-based-autodiscover/185953

### PR DESCRIPTION
**Pull request by ChrsMark**
Closes #12634.

cc: @odacremolbap, @exekias 

### Configure filebeat autodiscover
```yml
filebeat:
  autodiscover.providers:
    - type: docker
      hints.enabled: true
```

Having `filebeat` running, launch containers with the proper labels each time.
Make sure that Filebeat has permissions to read from `/var/lib/docker/containers/`, if not a quick option could be to run with sudo like `sudo -E ./filebeat -e -d "*" --strict.perms=false`.

### Test that keys are not copied under top level in the output document
```console
docker run -l co.elastic.logs/json.keys_under_root=false -it busybox echo '{"foo":"bar", "error_msg": "error opening file"}'
```

You should see in the event the following:
```json
"json": {
      "foo": "bar",
      "error_msg": "error opening file"
    },
```

### Test keys are copied under top level in the output document
```console
docker run -l co.elastic.logs/json.keys_under_root=true -it busybox echo '{"foo":"bar", "error_msg": "error opening file"}'
```

You should see the `foo` and `error_msg` in top level.

### Test that error is reported
```console
docker run -l co.elastic.logs/json.keys_under_root=true -l co.elastic.logs/json.add_error_key=true -it busybox echo '{"foo":"bar", "error_msg": "error opening file" and some buggy stuff}'
```

Event should be enriched with:
```json
"error": {
      "type": "json",
      "message": "Error decoding JSON: invalid character 's' after object key:value pair"
    },
```

### CODE REVIEW

**Comment by ChrsMark** [comment]
> Also, outside of the scope of this PR (maybe a followup). What would you think about simplifying these parameters for the user? I'm thinking something like this would make things better:
> 
> ```
> co.elastic.logs/json.enabled=true
> ```
> 
> This somehow would be an alias for:
> 
> ```
> co.elastic.logs/json.message_key=message
> ```
> 
> which is probably what most users want

🤔 could you elaborate more?

**Comment by exekias** [comment]
I will create a new issue so we move the conversation there, I don't think we should stall this PR :+1:

**Comment by exekias** [comment]
@ChrsMark had a chat and we decided it probably makes more sense to have the `enabled` keyword in the original JSON settings if possible, I will create an issue for that

**Comment by ChrsMark** [comment]
jenkins, test this again please

**Comment by ChrsMark** [comment]
jenkins, test this again please

**Comment by ChrsMark** [comment]
Merging this since Travis went green and failing tests of Jenkins look irrelevant to this patch.

**Comment by ycombinator** [comment]
Assigning myself for manually testing this PR for 7.6.0 release per `test-plan` label.

**Comment by ycombinator** [comment]
Tested manually. Works as expected!

**Comment by ycombinator** [comment]
Removed `test-plan-ok` label for now. Will re-test with BC (previously I tested by building from the `7.x` branch).

**Comment by ycombinator** [comment]
Tested with BC1 an works as expected!

**Pull request merged**
