### PR TITLE
Change integer fields in system-memory metrics to long

### PR DESCRIPTION
**Pull request by ruflin**

### CODE REVIEW

**Comment by simianhacker** [comment]
LGTM... Installed it and the memory metrics started flowing 👍

**Comment by andrewkroh** [comment]
I expected to see updates to docs/fields.assciidoc too. Did you run the generate script for that?

**Comment by ruflin** [comment]
@andrewkroh Isn't that the first file on the top or am I missing something?

**Comment by andrewkroh** [comment]
I had a suspicion that I just missed it. ☕  would probably solve this problem.

**Comment by ruflin** [comment]
@andrewkroh I would actually like to add this under the check build step, so CI already checks if it happened. It is a little bit a pity that for metricbeat also make collect is needed at the moment. I will perhaps have a solution for that (later) ;-)

**Pull request merged**
