### PR TITLE
[AWS S3 input] Add support in s3 input for JSON with array of objects

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
## What does this PR do?

AWS S3 input only supported an array of objects with a given `expand_event_list_from_field`. For example:
```
{
    "Events": [
        {
            "time": "2021-05-25 18:20:58 UTC",
            "msg": "hello"
        },
        {
            "time": "2021-05-26 22:21:40 UTC",
            "msg": "world"
        }
    ]
}
```
In this case, `expand_event_list_from_field` is set to `Events`.

This PR adds support for JSON files with an array of objects. For example: 
`[{"id":"1234","message":"success"},{"id":"5678","message":"failure"}]` with `expand_event_list_from_field` set to `.[]`.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

Closes https://github.com/elastic/beats/issues/35344

### CODE REVIEW

**Comment by aspacca** [comment]
@kaiyan-sheng seems similar to what we had from @legoguy1000 at https://github.com/elastic/beats/pull/31904
but with a different approach for the configuration

**Comment by legoguy1000** [comment]
> @kaiyan-sheng seems similar to what we had from @legoguy1000 at https://github.com/elastic/beats/pull/31904
> but with a different approach for the configuration

I would close my PR. I haven't had any time to work on any of my open PRs.  I think the same conversation applies on whether it's the default to unmarshal the array or require an explicit config?

**Comment by legoguy1000** [comment]
I would love to see this feature to split arrays into independent docs for all inputs. I started this here #29951 but was never able to get it fully working and haven't had time to continue it. I was able to get it working great when it was added to each input but once I tried making it a parser, it kinda went down hill.

**Comment by jamiehynds** [comment]
@kaiyan-sheng thanks for raising this PR. I've confirmed with our integration developers that it will unblock us on the Trellix EDR integration, based on the `{"id":"1234","message":"success"},{"id":"5678","message":"failure"}` format. 

Do you think this PR can be merged soon or is more feedback required?

**Comment by andrewkroh** [comment]
This is a breaking change for users that were dependent upon the array being contained in the `message` field. This was discussed in https://github.com/elastic/beats/pull/31904 a bit. My proposal was to have an explicit value to signify to split the root array. This would be the change:

```diff
diff --git a/x-pack/filebeat/input/awss3/s3_objects.go b/x-pack/filebeat/input/awss3/s3_objects.go
index 933a6c41a8..6c233055fc 100644
--- a/x-pack/filebeat/input/awss3/s3_objects.go
+++ b/x-pack/filebeat/input/awss3/s3_objects.go
@@ -234,14 +234,18 @@ func (p *s3ObjectProcessor) readJSON(r io.Reader) error {
 }
 
 func (p *s3ObjectProcessor) splitEventList(key string, raw json.RawMessage, offset int64, objHash string) error {
-	var jsonObject map[string]json.RawMessage
-	if err := json.Unmarshal(raw, &jsonObject); err != nil {
-		return err
-	}
+	// .[] signifies the root object is an array and it should be split.
+	if key != ".[]" {
+		var jsonObject map[string]json.RawMessage
+		if err := json.Unmarshal(raw, &jsonObject); err != nil {
+			return err
+		}
 
-	raw, found := jsonObject[key]
-	if !found {
-		return fmt.Errorf("expand_event_list_from_field key <%v> is not in event", key)
+		var found bool
+		raw, found = jsonObject[key]
+		if !found {
+			return fmt.Errorf("expand_event_list_from_field key <%v> is not in event", key)
+		}
 	}
 
 	dec := json.NewDecoder(bytes.NewReader(raw))
```

**Comment by kaiyan-sheng** [comment]
@jamiehynds @andrewkroh Thank you! Sorry I got distracted by other tasks. Will look into it now!

**Review by andrewkroh — COMMENTED** [review]
@kaiyan-sheng How would you feel about reducing the changes in s3_objects.go to this smaller changeset? It has the same behavior, but doesn't modify any of the methods contracts.

https://github.com/elastic/beats/compare/main...andrewkroh:beats:fix_s3_json_array?expand=1#diff-f345fd6a1f5ea9523117d4ead2e5f1d13fb82eb1c65a089fd34fcdd514916a96

**Review by andrewkroh — APPROVED** [review]

**Review by aspacca — APPROVED** [review]

**Pull request merged**
