### PR TITLE
[libbeat] Fix parsing of RFC 3164 process IDs in syslog processor

### LINKED ISSUE #38947: [libbeat] RFC 3164 process ID parsing issues
If an RFC 3164 syslog event includes square brackets in the message portion of the event, the process ID will be set to everything from the first square bracket, just before the process ID, and everything to the last square bracket in the message.

For example:

```
<114>Apr 12 13:30:01 aaaaaa001.adm.domain aaaaaa001[25259]: my.some.domain 10.11.12.13 - USERNAME [12/Apr/2024:13:29:59.993 +0200] /skodas "GET /skodas/group/pod-documentation/aaa HTTP/1.1" 301 301 290bytes 1 10327
                                                   ^ - From here to -------------------------------------------------------here -^

Resulting process ID:

25259]: my.some.domain 10.11.12.13 - USERNAME [12/Apr/2024:13:29:59.993 +0200
```

This is caused by the pattern for the process ID being too relaxed, allowing all printable characters (including closing square brackets). While the parser ensures the value of the process ID must be contained between a pair of square brackets, it does not care how many square brackets are in between. The solution is to lock down the pattern to a more acceptable range of characters. Since this is a process ID, digits would be the best option.

### PR DESCRIPTION
**Pull request by taylor-swanson**
## Proposed commit message

- The pattern for parsing process IDs was too relaxed and would match everything between the first opening and the last closing square bracket in a message. If the message included multiple closing square brackets, the process ID would be set to not only the process ID, but also whatever leads up to the last closing square bracket.
- The pattern has now been locked down to only digits.
- Added test case.

## Checklist

- [x] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #38947

### CODE REVIEW

**Review by pkoutsovasilis — APPROVED** [review]
this LGTM! I am far from a ragel expert but based on the issue the substitution of `print+` with `digit+` makes sense to me

**Comment by taylor-swanson** [comment]
> this LGTM! I am far from a ragel expert but based on the issue the substitution of `print+` with `digit+` makes sense to me

I think `digit` should be the right choice here. If for some reason we needed alpha and special characters, we could use `print`, but remove square brackets as valid characters (similar to the `tag` pattern above it).

**Review by leehinman — APPROVED** [review]
LGTM

**Pull request merged**
