### PR TITLE
Backport #11240 to 7.0: Re-introduce field formats on ECS fields. (#11240)

### PR DESCRIPTION
**Pull request by webmat**
They were accidentally removed by #11150.

### CODE REVIEW

**Comment by webmat** [comment]
I'm kicking off this backport early (aka before the original is merged) because the original is trivial. Hopefully this can streamline the fixing of 7.0, if tests are all green here tomorrow morning.

**Comment by webmat** [comment]
Error here is also in the Metricbeat testsuite around elasticsearch:6.6.0. But the errors are very different than on #11240. Will investigate tomorrow.

**Comment by webmat** [comment]
jenkins, test this bro

**Comment by simitt** [comment]
Same comment as for #11240, otherwise LGTM.

**Comment by webmat** [comment]
Yes, waiting to backport #11249 first, then I'll reapply #11240 on top of all that

**Comment by webmat** [comment]
This is merged @simitt

**Pull request merged**
