### PR TITLE
Allow the Docker image to be run with a random user id (#12905)

### LINKED ISSUE #18858: docker images for APM Server failing with permission issues
It seems that with introducing changes in https://github.com/elastic/beats/pull/12905 config file permissions were changed from `0640` to `0660`.  

When running the APM Server docker images without setting `BEAT_STRICT_PERMS=false` the check [OwnerHasExclusiveWritePerms](https://github.com/elastic/beats/blob/master/libbeat/common/config.go#L404) now fails with the error `config file ("apm-server.yml") can only be writable by the owner but the permissions are "-rw-rw----"`. Our integration test environment fails since pulling in these changes into APM Server.

It seems to be the same issue for other beats, e.g. running `docker run -e  docker.elastic.co/beats/metricbeat:8.0.0-SNAPSHOT` results in the mentioned error and prevents the beat from starting, whereas `docker run -e BEAT_STRICT_PERMS=false docker.elastic.co/beats/metricbeat:8.0.0-SNAPSHOT` works fine.

@barkbay @jsoriano could you please take a look at this, from what I understand the intention was not to switch to `BEATS_STRICT_PERMS=false`.

### LINKED ISSUE #18871: Support arbitrary user IDs in secured Kubernetes environments
Add support for arbitrary user IDs in secured Kubernetes environments without needing to disable permission checks.

#12905   added support for arbitrary user IDs, but it changed the permissions of the files in a way that require Beats docker images to be run with `BEAT_STRICT_PERMS=false`, what is not recommended so far.

We should find a way to support arbitrary user IDs, without changing the current behaviour for the rest of cases.

Related issues:
- elastic/beats#12905 
- elastic/beats#18858 
- elastic/beats#18872

### PR DESCRIPTION
**Pull request by jsoriano**
Apply changes on ownership proposed in #12905, but keep the permissions, to avoid the
issues reported in #18858.

I think this could be enough to run containers with arbitrary user ids, because beats don't need to write these files, only read them.

Make changes also to the kubernetes reference manifests to help running beats with arbitrary user ids. These manifests still won't work on restricted environments.

Fixes #18871 
Changes were previously reverted in #18872 

Co-authored-by: Michael Morello <michael.morello@elastic.co>

How to test
----
* Do it with auditbeat (that uses the root user by default), and with some other beat like metricbeat or filebeat (that use a non-root user by default):
  * Build the docker image for the beat with `PLATFORMS=linux/amd64 mage package`, or use one of the pre-built snapshots including this change.
  * Run the docker container with and without explicit user id, and check that beat is able to start and read configuration without `--privileged` and without `BEAT_STRICT_PERMS`.
    It should behave the same on these scenarios (auditbeat will fail to configure audit, this is expected unless `--privileged --user 0 --pid=host` is also used):
    * Default user: `docker run -it --rm docker.elastic.co/beats/filebeat:8.0.0`
    * Root: `docker run -it --rm --user 0 docker.elastic.co/beats/filebeat:8.0.0`
    * Beat user: `docker run -it --rm --user 1000 docker.elastic.co/beats/filebeat:8.0.0`
    * Arbitrary user (use any other user id): `docker run -it --rm --user 100042 docker.elastic.co/beats/filebeat:8.0.0`
  * Check that reference kubernetes manifests continue working as they are (using arbitrary user ids there will require more changes).

### CODE REVIEW

**Comment by jsoriano** [comment]
run beats-ci/package

**Comment by barkbay** [comment]
@jsoriano Thanks for the PR, and sorry for breaking your CI 😞 

Could you tell me where I can find a docker image of the APM Server from this PR. I'll do a quick test to check if it fixes the arbitrary UID issue.

Otherwise I'm fine with merging #18872 in order to unlock the situation.

**Comment by jsoriano** [comment]
> @jsoriano Thanks for the PR, and sorry for breaking your CI :disappointed:
> 

No worries, I should have seen these issues with strict perms come :grimacing: 

> Could you tell me where I can find a docker image of the APM Server from this PR. I'll do a quick test to check if it fixes the arbitrary UID issue.
> 

Not sure how to do this, I guess you would need to update libbeat in apm-server, or at least the packaging templates.

> Otherwise I'm fine with merging #18872 in order to unlock the situation.

Yeah, I think we can merge the revert, and go on here.

**Comment by jsoriano** [comment]
run beats-ci/package

**Comment by jsoriano** [comment]
run beats-ci/package

**Comment by jsoriano** [comment]
@barkbay sorry for the delay, I am back with this. I have updated the branch with master.

You can build an apm-server docker image with this branch running these commands from the apm-server working directory:
```
go mod edit -replace github.com/elastic/beats/v7=github.com/jsoriano/beats/v7@fix-18858
PLATFORMS=linux/amd64 mage package
```

I did some smoke tests and it seems to start correctly with and without random user ids. Could you also confirm? thanks!

**Comment by barkbay** [comment]
@jsoriano no worries ! I was quite busy myself...

Thanks a lot for this PR 🙇 
I will do some tests and get back to you asap.

**Comment by jsoriano** [comment]
run beats-ci/package

**Comment by jsoriano** [comment]
@barkbay thanks for your tests!

> The only issue I have is this test which is failing and I don't understand why:
> 
> ```
> >> Testing package contents
> --- FAIL: TestDocker (13.81s)
>     --- FAIL: TestDocker/apm-server-7.9.0-linux-amd64.docker.tar.gz_config_file_permissions (0.00s)
>         package_test.go:206: file usr/share/apm-server/apm-server.yml has wrong permissions: expected=-rw-r----- actual=-rw-rw----
>     --- FAIL: TestDocker/apm-server-oss-7.9.0-linux-amd64.docker.tar.gz_config_file_permissions (0.00s)
>         package_test.go:206: file usr/share/apm-server/apm-server.yml has wrong permissions: expected=-rw-r----- actual=-rw-rw---
> ```

Umm, this is strange because now we are not changing anything on permissions. Does it happen to you with master, without the go mod replace?

**Comment by barkbay** [comment]
> Umm, this is strange because now we are not changing anything on permissions. Does it happen to you with master, without the go mod replace?

Agreed, sounds odd. I think something is wrong with my environment.
Let me do a last test before I approve the PR.

Thanks.

**Comment by jsoriano** [comment]
jenkins run the tests please

**Comment by barkbay** [comment]
@jsoriano we just had this issue on our CI: https://github.com/elastic/cloud-on-k8s/issues/3349#issuecomment-651766520

Do you think it's related ? If yes I don't understand why it was working fine yesterday during my tests.

**Comment by jsoriano** [comment]
I have found that our reference Kubernetes manifests don't work when they need to store files in the default data path, as filebeat does, because the directory is created by `DirectoryOrCreate` and then it can be only written by root.
I will try to use a persistent volume claim for these data paths.

@barkbay were you using some volume from the host in your tests?

**Comment by jsoriano** [comment]
> I have found that our reference Kubernetes manifests don't work when they need to store files in the default data path, as filebeat does, because the directory is created by `DirectoryOrCreate` and then it can be only written by root.
> I will try to use a persistent volume claim for these data paths.

Clarification: it only fails when beats are run with non-root user. I haven't managed to find another way of having a persistent volume for daemonsets, so I have added a comment mentioning the required permissions to the reference files. I have also added read permissions to the volumes mounted with configuration files.

**Comment by jsoriano** [comment]
I am trying to verify that beats can continue writing to their data directories after restart.

@barkbay another question about your tests. Do you set a non-root user ID with `runAsUser`? or the user ID is somehow given randomly by OpenShift/GKE?

**Comment by barkbay** [comment]
> @barkbay were you using some volume from the host in your tests?

No, when the APM Server is run with ECK the data dir is an `emptyDir`. 

> @barkbay another question about your tests. Do you set a non-root user ID with `runAsUser`? or the user ID is somehow given randomly by OpenShift/GKE?

The UID is randomly assigned by Openshift: you can find [here the Pod as it is created with ECK](https://gist.githubusercontent.com/barkbay/4a4422022a9d7a453d8ed5482fe4307a/raw/a5bfccd69a0eb10ff00c17cebb24372657cee1bb/apm.pod.yaml) on Openshift (and here the [ECK manifest](https://gist.githubusercontent.com/barkbay/4a4422022a9d7a453d8ed5482fe4307a/raw/a5bfccd69a0eb10ff00c17cebb24372657cee1bb/apmserver-sample-8.0.0.eck.yaml)).

**Comment by jsoriano** [comment]
I have been doing several tests and I think we can go on with merging this. As summary of my tests:
* Main conclusion: I think we don't introduce regressions and this unblocks APM server needings.
* Docker containers can be used with arbitrary ids, but it may not make sense with some beats (auditing for example seens to require 0 uid, apart of being run on pid namespace and with additional capabilities). We will have to continue evolving this as we find possible use cases to support.
* Reference Kubernetes manifests can be used to run Beats with arbitrary user ids, but:
  * Data path directory has to be externally managed (`DirectoryOrCreate` creates the directory without write permissions for the group).
  * They cannot be used on restricted environments (they need to mount local paths, they need to run on host namespaces, and so on). If required to deploy on restricted environments, monitoring capabilities will be limited, and a quite different configuration will be needed.

**Comment by jsoriano** [comment]
I have created an issue to keep track of some issues I found trying to run Beats on restricted environments: #19600

**Comment by jsoriano** [comment]
@barkbay @simitt I have merged this on master and 7.x, please let me know if you find any issue with the docker images when updating beats on apm-server. Thanks!

**Pull request merged**
