### PR TITLE
Update haproxy.asciidoc

### PR DESCRIPTION
**Pull request by OleOle7177**
Fix stats port number

### CODE REVIEW

**Comment by jsoriano** [comment]
@OleOle7177 good catch :) Could you please run `make update` to regenerate documentation and commit the changes?

And you'd also need to sign the CLA.

Thanks!

**Comment by OleOle7177** [comment]
@jsoriano thanks, 
I've signed CLA and ran `make update` (no changes).

**Comment by OleOle7177** [comment]
@ruflin here it is: https://github.com/elastic/beats/pull/6869

**Comment by ruflin** [comment]
jenkins, test it

**Comment by ruflin** [comment]
jenkins, test it

**Comment by ph** [comment]
Jenkins test this please

**Pull request merged**
