### PR TITLE
Upgrade github.com/elastic/go-sysinfo v1.8.0 => v1.8.1

### LINKED ISSUE #30833: Metricbeat system modules reports Windows 11 as Windows 10
When running on Windows 11 the system module will report the running Windows version as Windows 10.

This was noticed as the endpoint security integration correctly identifies Windows 11 when agent is running on that operating system with both endpoint security and the system integration:

Endpoint Security:
```json
      "os": {
        "Ext": {
          "variant": "Windows 11 Home"
        },
        "kernel": "21H2 (10.0.22000.556)",
        "name": "Windows",
        "family": "windows",
        "type": "windows",
        "version": "21H2 (10.0.22000.556)",
        "platform": "windows",
        "full": "Windows 11 Home 21H2 (10.0.22000.556)"
      },
```
System:
```json
      "os": {
        "build": "22000.556",
        "kernel": "10.0.22000.556 (WinBuild.160101.0800)",
        "name": "Windows 10 Home",
        "family": "windows",
        "type": "windows",
        "version": "10.0",
        "platform": "windows"
      },
```

We are reporting the value from reading the `SOFTWARE\Microsoft\Windows NT\CurrentVersion` registry key exactly as read:

https://github.com/elastic/go-sysinfo/blob/bef435f84e9706a7c8fff908b5e54b984f98ca3b/providers/windows/os_windows.go#L33

The product name wasn't updated by Microsoft between the two products and the system integration isn't looking at anything else that allows distinguishing Windows 10 from Windows 11 like Endpoint is.

There are some related answers in the Microsoft support forums confirming the situation:

- https://docs.microsoft.com/en-us/answers/questions/555857/windows-11-product-name-in-registry.html?page=1&pageSize=10&sort=oldest
- https://docs.microsoft.com/en-us/answers/questions/586619/windows-11-build-ver-is-still-10022000194.html

This is a bug in that the system integration hasn't accounted for this problem yet.

### PR DESCRIPTION
**Pull request by andrewkroh**
## What does this PR do?

Fix OS name reported by add_host_metadata on Windows 11.

https://github.com/elastic/go-sysinfo/releases/tag/v1.8.1

Fixes #30833

## Why is it important?

Prior to this fix, Windows 11 was being reported as Windows 10.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #30833

### CODE REVIEW

**Review by cmacknz — APPROVED** [review]
Thanks for fixing this! Also thanks Microsoft for making this bug possible...

**Comment by andrewkroh** [comment]
Packaging failure is caused by:

> [2022-07-08T04:29:15.709Z] osxcross: error: xcrun: cannot find 'dsymutil' executable

**Comment by andrewkroh** [comment]
@Mergifyio rebase

**Review by efd6 — APPROVED** [review]

**Pull request merged**
