### PR TITLE
[Metricbeat] Add state_statefulset replicas.ready

### LINKED ISSUE #24372: Include kube_statefulset_status_replicas_ready metric in kubernetes Metricbeat module
**Describe the enhancement:**

As part of the `state_statefulset` metricseat some users are reporting the need of using the metric `kube_statefulset_status_replicas_ready`, which is not collected at the moment,  but it's returned by `kube-state-metrics`:

https://github.com/elastic/beats/blob/master/metricbeat/module/kubernetes/state_statefulset/state_statefulset.go

That metric is useful to build better dashboards for kubernetes monitoring.

My recommendation is also to review the available metrics to see if there are other similar metrics that we might be discarding at the moment.

### PR DESCRIPTION
**Pull request by jarpy**
Add a "replicas.ready" field to the state_statefulset metricset of the
Kubernetes module.

This is drawn from the "readyReplicas" value in the Kubernetes
StatefulSetStatus API response.

## What does this PR do?

Adds a `replicas.ready` field to the Kubernetes `state_statefulset` metricset.

## Why is it important?

Allows the operator to define alerts on ready/unready replicas in a StatefulSet.

## Checklist

- [x] My code follows the style guidelines of this project
- [] <strike>I have commented my code, particularly in hard-to-understand areas</strike>
- [x] I have made corresponding changes to the documentation
- [] <strike>I have made corresponding change to the default configuration files</strike>
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

```
MODULE=kubernetes mage -v test
```

## Related issues

- Closes #24372

### CODE REVIEW

**Comment by jarpy** [comment]
cc @eedugon

**Review by ChrsMark — APPROVED** [review]
lgtm, thanks @jarpy! 
It will require a change in https://github.com/elastic/integrations/tree/master/packages/kubernetes too to add the extra field.

Can you open an issue there @jarpy  please and assign it to me so as not to forget about it?

**Comment by jarpy** [comment]
Thanks, @ChrsMark. <3

Not sure how to handle backports, is that all automated these days?

**Comment by ChrsMark** [comment]
Nope, we still handle the backports manually. I opened the backport for 7.14 so we are just fine here!

**Comment by jarpy** [comment]
Sweet. Thanks so much, @ChrsMark.

**Pull request merged**
