### PR TITLE
Osquerybeat - Linux AARCH64 support

### PR DESCRIPTION
**Pull request by aleksmaus**
## What does this PR do?

* Add Osquerybeat - Linux AARCH64 support. Package the AARCH64 osqueryd binary from the official osquery distro.
* Update Osquery to 4.8.0, this is the offical distro version for beta ARM support https://osquery.io/blog/linux-arm64-beta-support
* Update the agent spec to allow osquerybeat to run on arm64 arch

## Why is it important?

Addresses: https://github.com/elastic/security-team/issues/1252

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas

## Related issues

- Closes https://github.com/elastic/security-team/issues/1252

## Screenshots

Tested with the agent
Screen Shot 2021-05-26 at 3 40 01 PM

### CODE REVIEW

**Comment by urso** [comment]
The packaging errors might be related to this change.

**Comment by aleksmaus** [comment]
@kvch 
I'm trying to get the osquerybeat build for aarch64 with CI, getting errors:
https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-25925/runs/3/steps/5487/log/?start=0
```
Error: failed to run "arm-linux-gnueabihf-gcc /go/pkg/mod/github.com/tsg/go-daemon@v0.0.0-20200207173439-e704b93fd89b/src/god.c -o build/golang-crossbuild/god-linux-armv7 -lpthread -static: exec: "arm-linux-gnueabihf-gcc": executable file not found in $PATH"
Error: failed building for linux/armv7: exit status 1
```

don’t need arm7 build, we don’t have osquery distro for that, just arm64

what need to happen to get it built?

**Review by urso — APPROVED** [review]

**Review by scunningham — APPROVED** [review]
looks good to me. 👍

**Pull request merged**
