### PR TITLE
Updated snapshot-2x environment for the 1.2.2 release testing

### PR DESCRIPTION
**Pull request by tsg**

### CODE REVIEW

**Comment by ruflin** [comment]
@tsg The url `https://download.elastic.co/logstash/logstash/logstash_5.0.0~alpha1~snapshot2-1_all.deb?20160330` is not working for me?

**Comment by ruflin** [comment]
It seems like the build failure is not related to this PR, but to an invalid snapshot LS url for 5.0-alpha1. Will check and provide a fix ...

**Comment by tsg** [comment]
@ruflin just pushed a new URL for the LS alpha1. It's now released, so I'm simply using the official download link.

**Comment by ruflin** [comment]
@tsg just did the same :-) You were faster. I will add some more stuff in https://github.com/elastic/beats/pull/1420 afterwards. Lets get this one in first.

**Comment by tsg** [comment]
Ha, Elasticsearch just published another release candidate. Let me update it first.

**Comment by tsg** [comment]
Done and rebased.

**Comment by ruflin** [comment]
Merged as build errors are not related to this change but a flaky filter test.

**Pull request merged**
