### PR TITLE
Added weekly macos pipeline

### PR DESCRIPTION
**Pull request by oakrizan**
## Proposed commit message
Changes in catalog.info to introduce new macOS weekly job.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Relates: https://github.com/elastic/ingest-dev/issues/3271

## Logs
BK builds: https://buildkite.com/elastic/beats/builds/14118

### CODE REVIEW

**Comment by rowlandgeoff** [comment]
Fast turnaround on creating this, thanks Olga! But since the catalog-info entry and the pipeline are getting created in the same PR, that means the pipeline can't be tested until after the PR is merged, right? I think with other new pipelines, we've had a first PR to create the catalog-info entry with a mostly empty pipeline, and then a second PR that fills in the pipeline details. Then the pipeline can get tested against the PR branch until it's ready to be merged.

**Review by pazone — APPROVED** [review]

**Review by pazone — CHANGES_REQUESTED** [review]
LGTM. I'd recommend testing the pipeline first by separating the catalog-info resource creation

**Comment by pazone** [comment]
I'm worried about our Orka VMs capacity. 22 parallel steps will not fit it. It will clog up our cluster.

**Comment by oakrizan** [comment]
I have updated PR with catalog-info updates && initial pipeline creation.
Regarding Orka capacity - once this pr is merged, I can test couple of approaches, that will execute tests in limited batches/subsequently.

**Review by pazone — APPROVED** [review]

**Comment by rowlandgeoff** [comment]
Does this need to be backported if it's only targeted for the main branch?

**Comment by oakrizan** [comment]
> Does this need to be backported if it's only targeted for the main branch?

@rowlandgeoff, I would say that we need to run tests on all set of branches, in a same way we do it with AWS.
Not sure what was the history behind the weekly job logic on Jenkins, but since we know that macOS tests are frequently forgotten to be triggered upon the PRs, it makes sense to have them running at least on weekly basis.

I will postpone BP merging, unless we have agreement on this.

cc: @pazone @alexsapran @dliappis

**Comment by pazone** [comment]
IMHO this requirement can be reconsidered. The load to the macos instances may be too high

**Comment by rowlandgeoff** [comment]
I agree with the macOS load issues as well. Let's cancel the backports for now.

**Pull request merged**
