### PR TITLE
Fixed socket scanning for tcp6

### PR DESCRIPTION
**Pull request by tomaszrichert**
Fixed issue with /proc/net/tcp6 not being scanned due to simple bug

### CODE REVIEW

**Comment by exekias** [comment]
LGTM @tomaszrichert, can you add a bugfix line to `CHANGELOG.asciidoc` file?

jenkins test it please

**Comment by exekias** [comment]
BTW, thank you so much for taking the time to research and fix this! :100:

**Comment by tomaszrichert** [comment]
Fixed 2 bugs: 
* enabled scanning of /proc/net/tcp6
* fixed parsing ip v6

**Comment by tomaszrichert** [comment]
Updated changelog. 
ps: Is there a release roadmap somewhere ?

**Comment by exekias** [comment]
We don't publish roadmaps, but as soon as this is merged it should make it to the next release

**Comment by exekias** [comment]
jenkins test it

**Pull request merged**
