### PR TITLE
Skip sockets summary system tests on Windows

### LINKED ISSUE #7868: [Metricbeat] Flaky test_socket_summary test
* Platform: Windows
* Link: https://beats-ci.elastic.co/job/elastic+beats+master+multijob-windows/beat=metricbeat,label=windows/1321/console
* Related PR: https://github.com/elastic/beats/pull/6782

Error:
```
07:17:10 ======================================================================
07:17:10 ERROR: Test system/socket_summary output.
07:17:10 ----------------------------------------------------------------------
07:17:10 Traceback (most recent call last):
07:17:10   File "C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\metricbeat\label\windows\src\github.com\elastic\beats\metricbeat\tests\system\test_system.py", line 473, in test_socket_summary
07:17:10     summary = evt["system"]["socket"]["summary"]
07:17:10 KeyError: 'system'
07:17:10 
```

Log:
```
2018-08-06T07:17:09.433Z	INFO	instance/beat.go:544	Home path: [C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\metricbeat\label\windows\src\github.com\elastic\beats\metricbeat\build\system-tests\run\test_system.Test.test_socket_summary] Config path: [C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\metricbeat\label\windows\src\github.com\elastic\beats\metricbeat\build\system-tests\run\test_system.Test.test_socket_summary] Data path: [C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\metricbeat\label\windows\src\github.com\elastic\beats\metricbeat\build\system-tests\run\test_system.Test.test_socket_summary\data] Logs path: [C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\metricbeat\label\windows\src\github.com\elastic\beats\metricbeat\build\system-tests\run\test_system.Test.test_socket_summary\logs]
2018-08-06T07:17:09.466Z	DEBUG	[beat]	instance/beat.go:571	Beat metadata path: C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\metricbeat\label\windows\src\github.com\elastic\beats\metricbeat\build\system-tests\run\test_system.Test.test_socket_summary\data\meta.json
2018-08-06T07:17:09.466Z	INFO	instance/beat.go:551	Beat UUID: 7477dc90-7dea-46b1-81b1-85577d7f347b
2018-08-06T07:17:09.467Z	DEBUG	[seccomp]	seccomp/seccomp.go:88	Syscall filtering is only supported on Linux
2018-08-06T07:17:09.467Z	INFO	[beat]	instance/beat.go:768	Beat info	{"system_info": {"beat": {"path": {"config": "C:\\Users\\jenkins\\workspace\\elastic+beats+master+multijob-windows\\beat\\metricbeat\\label\\windows\\src\\github.com\\elastic\\beats\\metricbeat\\build\\system-tests\\run\\test_system.Test.test_socket_summary", "data": "C:\\Users\\jenkins\\workspace\\elastic+beats+master+multijob-windows\\beat\\metricbeat\\label\\windows\\src\\github.com\\elastic\\beats\\metricbeat\\build\\system-tests\\run\\test_system.Test.test_socket_summary\\data", "home": "C:\\Users\\jenkins\\workspace\\elastic+beats+master+multijob-windows\\beat\\metricbeat\\label\\windows\\src\\github.com\\elastic\\beats\\metricbeat\\build\\system-tests\\run\\test_system.Test.test_socket_summary", "logs": "C:\\Users\\jenkins\\workspace\\elastic+beats+master+multijob-windows\\beat\\metricbeat\\label\\windows\\src\\github.com\\elastic\\beats\\metricbeat\\build\\system-tests\\run\\test_system.Test.test_socket_summary\\logs"}, "type": "metricbeat", "uuid": "7477dc90-7dea-46b1-81b1-85577d7f347b"}}}
2018-08-06T07:17:09.467Z	INFO	[beat]	instance/beat.go:777	Build info	{"system_info": {"build": {"commit": "unknown", "libbeat": "7.0.0-alpha1", "time": "1754-08-30T22:43:41.128Z", "version": "7.0.0-alpha1"}}}
2018-08-06T07:17:09.467Z	INFO	[beat]	instance/beat.go:780	Go runtime info	{"system_info": {"go": {"os":"windows","arch":"amd64","max_procs":4,"version":"go1.10.3"}}}
2018-08-06T07:17:09.473Z	INFO	[beat]	instance/beat.go:784	Host info	{"system_info": {"host": {"architecture":"x86_64","boot_time":"2018-07-14T14:24:49.17Z","hostname":"WORKER-0CC433DC","ips":["fe80::5468:dc20:18ed:9012/64","10.34.171.149/20","::1/128","127.0.0.1/8","2001:0:9d38:953c:30a6:323b:c945:2095/64","fe80::30a6:323b:c945:2095/64","fe80::5efe:a22:ab95/128"],"kernel_version":"10.0.14393.1715 (rs1_release_inmarket.170906-1810)","mac_addresses":["0a:bc:80:20:69:68","00:00:00:00:00:00:00:e0","00:00:00:00:00:00:00:e0"],"os":{"family":"windows","platform":"windows","name":"Windows Server 2016 Datacenter","version":"10.0","major":10,"minor":0,"patch":0,"build":"14393.1715"},"timezone":"GMT","timezone_offset_sec":0,"id":"31e2265d-393d-4e51-bffb-e2e2e71580a3"}}}
2018-08-06T07:17:09.474Z	INFO	instance/beat.go:273	Setup Beat: metricbeat; Version: 7.0.0-alpha1
2018-08-06T07:17:09.474Z	DEBUG	[beat]	instance/beat.go:290	Initializing output plugins
2018-08-06T07:17:09.474Z	DEBUG	[processors]	processors/processor.go:66	Processors: 
2018-08-06T07:17:09.474Z	DEBUG	[rotator]	file/rotator.go:135	Initialized file rotator	{"rotator": {"filename": "C:\\Users\\jenkins\\workspace\\elastic+beats+master+multijob-windows\\beat\\metricbeat\\label\\windows\\src\\github.com\\elastic\\beats\\metricbeat\\build\\system-tests\\run\\test_system.Test.test_socket_summary\\output\\metricbeat", "max_size_bytes": 1024000, "max_backups": 7, "permissions": "-rw-------"}}
2018-08-06T07:17:09.475Z	INFO	fileout/file.go:94	Initialized file output. path=C:\Users\jenkins\workspace\elastic+beats+master+multijob-windows\beat\metricbeat\label\windows\src\github.com\elastic\beats\metricbeat\build\system-tests\run\test_system.Test.test_socket_summary\output\metricbeat max_size_bytes=1024000 max_backups=7 permissions=-rw-------
2018-08-06T07:17:09.475Z	DEBUG	[publish]	pipeline/consumer.go:137	start pipeline event consumer
2018-08-06T07:17:09.476Z	INFO	pipeline/module.go:98	Beat name: WORKER-0CC433DC
2018-08-06T07:17:09.476Z	DEBUG	[modules]	beater/metricbeat.go:98	Register [ModuleFactory:[docker, mongodb, mysql, postgresql, system, uwsgi, windows], MetricSetFactory:[aerospike/namespace, apache/status, ceph/cluster_disk, ceph/cluster_health, ceph/cluster_status, ceph/monitor_health, ceph/osd_df, ceph/osd_tree, ceph/pool_disk, couchbase/bucket, couchbase/cluster, couchbase/node, docker/container, docker/cpu, docker/diskio, docker/healthcheck, docker/image, docker/info, docker/memory, docker/network, dropwizard/collector, elasticsearch/cluster_stats, elasticsearch/index, elasticsearch/index_recovery, elasticsearch/index_summary, elasticsearch/ml_job, elasticsearch/node, elasticsearch/node_stats, elasticsearch/pending_tasks, elasticsearch/shard, envoyproxy/server, etcd/leader, etcd/self, etcd/store, golang/expvar, golang/heap, graphite/server, haproxy/info, haproxy/stat, http/json, http/server, jolokia/jmx, kafka/consumergroup, kafka/partition, kibana/stats, kibana/status, kubernetes/apiserver, kubernetes/container, kubernetes/event, kubernetes/node, kubernetes/pod, kubernetes/state_container, kubernetes/state_deployment, kubernetes/state_node, kubernetes/state_pod, kubernetes/state_replicaset, kubernetes/state_statefulset, kubernetes/system, kubernetes/volume, kvm/dommemstat, logstash/node, logstash/node_stats, memcached/stats, mongodb/collstats, mongodb/dbstats, mongodb/metrics, mongodb/status, munin/node, mysql/galera_status, mysql/status, nginx/stubstatus, php_fpm/pool, postgresql/activity, postgresql/bgwriter, postgresql/database, postgresql/statement, prometheus/collector, prometheus/stats, rabbitmq/connection, rabbitmq/exchange, rabbitmq/node, rabbitmq/queue, redis/info, redis/keyspace, system/core, system/cpu, system/diskio, system/filesystem, system/fsstat, system/memory, system/network, system/process, system/process_summary, system/raid, system/socket_summary, system/uptime, traefik/health, uwsgi/status, vsphere/datastore, vsphere/host, vsphere/virtualmachine, windows/perfmon, windows/service, zookeeper/mntr]]
2018-08-06T07:17:09.476Z	DEBUG	[processors]	processors/processor.go:66	Processors: 
2018-08-06T07:17:09.479Z	INFO	helper/privileges_windows.go:79	Metricbeat process and system info: {"OSVersion":{"Major":6,"Minor":2,"Build":9200},"Arch":"amd64","NumCPU":4,"User":{"SID":"S-1-5-21-2485467087-2958747450-187013876-1004","Account":"jenkins","Domain":"WORKER-0CC433DC","Type":1},"ProcessPrivs":{"SeBackupPrivilege":{"enabled":false},"SeChangeNotifyPrivilege":{"enabled_by_default":true,"enabled":true},"SeCreateGlobalPrivilege":{"enabled_by_default":true,"enabled":true},"SeCreatePagefilePrivilege":{"enabled":false},"SeCreateSymbolicLinkPrivilege":{"enabled":false},"SeDebugPrivilege":{"enabled":true},"SeDelegateSessionUserImpersonatePrivilege":{"enabled":false},"SeImpersonatePrivilege":{"enabled_by_default":true,"enabled":true},"SeIncreaseBasePriorityPrivilege":{"enabled":false},"SeIncreaseQuotaPrivilege":{"enabled":false},"SeIncreaseWorkingSetPrivilege":{"enabled":false},"SeLoadDriverPrivilege":{"enabled":false},"SeManageVolumePrivilege":{"enabled":false},"SeProfileSingleProcessPrivilege":{"enabled":false},"SeRemoteShutdownPrivilege":{"enabled":false},"SeRestorePrivilege":{"enabled":false},"SeSecurityPrivilege":{"enabled":false},"SeShutdownPrivilege":{"enabled":false},"SeSystemEnvironmentPrivilege":{"enabled":false},"SeSystemProfilePrivilege":{"enabled":false},"SeSystemtimePrivilege":{"enabled":false},"SeTakeOwnershipPrivilege":{"enabled":false},"SeTimeZonePrivilege":{"enabled":false},"SeUndockPrivilege":{"enabled":false}}}
2018-08-06T07:17:09.479Z	INFO	helper/privileges_windows.go:87	SeDebugPrivilege is enabled. SeDebugPrivilege=(Enabled)
2018-08-06T07:17:09.479Z	WARN	[cfgwarn]	socket_summary/socket_summary.go:52	EXPERIMENTAL: The socket_summary metricset is experimental.
2018-08-06T07:17:09.480Z	INFO	[monitoring]	log/log.go:114	Starting metrics logging every 30s
2018-08-06T07:17:09.480Z	INFO	instance/beat.go:367	metricbeat start running.
2018-08-06T07:17:09.480Z	DEBUG	[service]	service/service_windows.go:68	Windows is interactive: false
2018-08-06T07:17:09.480Z	DEBUG	[module]	module/wrapper.go:117	Starting Wrapper[name=system, len(metricSetWrappers)=1]
2018-08-06T07:17:09.481Z	DEBUG	[module]	module/wrapper.go:179	Starting metricSetWrapper[module=system, name=socket_summary, host=]
2018-08-06T07:17:09.481Z	ERROR	service/service_windows.go:76	Error: The service process could not connect to the service controller.
2018-08-06T07:17:09.482Z	DEBUG	[publish]	pipeline/processor.go:308	Publish event: {
  "@timestamp": "2018-08-06T07:17:09.481Z",
  "@metadata": {
    "beat": "metricbeat",
    "type": "doc",
    "version": "7.0.0-alpha1"
  },
  "beat": {
    "name": "WORKER-0CC433DC",
    "hostname": "WORKER-0CC433DC",
    "version": "7.0.0-alpha1"
  },
  "host": {
    "name": "WORKER-0CC433DC"
  },
  "metricset": {
    "namespace": "system.socket.summary",
    "name": "socket_summary",
    "module": "system"
  },
  "error": {
    "message": "not implemented yet"
  }
}
2018-08-06T07:17:09.583Z	DEBUG	[memqueue]	memqueue/ackloop.go:160	ackloop: receive ack [0: 0, 1]
2018-08-06T07:17:09.583Z	DEBUG	[memqueue]	memqueue/eventloop.go:535	broker ACK events: count=1, start-seq=1, end-seq=1

2018-08-06T07:17:09.583Z	DEBUG	[memqueue]	memqueue/ackloop.go:128	ackloop: return ack to broker loop:1
2018-08-06T07:17:09.583Z	DEBUG	[memqueue]	memqueue/ackloop.go:131	ackloop:  done send ack
2018-08-06T07:17:09.674Z	DEBUG	[service]	service/service.go:51	Received sigterm/sigint, stopping
2018-08-06T07:17:09.674Z	DEBUG	[publish]	pipeline/client.go:148	client: closing acker
2018-08-06T07:17:09.674Z	DEBUG	[module]	module/wrapper.go:202	Stopped metricSetWrapper[module=system, name=socket_summary, host=]
2018-08-06T07:17:09.674Z	DEBUG	[publish]	pipeline/client.go:150	client: done closing acker
2018-08-06T07:17:09.674Z	DEBUG	[module]	module/wrapper.go:145	Stopped Wrapper[name=system, len(metricSetWrappers)=1]
2018-08-06T07:17:09.674Z	DEBUG	[publish]	pipeline/client.go:154	client: cancelled 0 events
2018-08-06T07:17:09.705Z	INFO	[monitoring]	log/log.go:149	Total non-zero metrics	{"monitoring": {"metrics": {"beat":{"cpu":{"system":{"ticks":62,"time":{"ms":62}},"total":{"ticks":202,"time":{"ms":202},"value":202},"user":{"ticks":140,"time":{"ms":140}}},"info":{"ephemeral_id":"36b8c928-8ee5-414f-83aa-5190d8489e27","uptime":{"ms":1090}},"memstats":{"gc_next":5225248,"memory_alloc":4111632,"memory_total":9021048,"rss":62128128}},"libbeat":{"config":{"module":{"running":0}},"output":{"events":{"acked":1,"batches":1,"total":1},"type":"file","write":{"bytes":370}},"pipeline":{"clients":0,"events":{"active":0,"published":1,"total":1},"queue":{"acked":1}}},"system":{"cpu":{"cores":4}}}}}
2018-08-06T07:17:09.705Z	INFO	[monitoring]	log/log.go:150	Uptime: 1.1209794s
2018-08-06T07:17:09.705Z	INFO	[monitoring]	log/log.go:127	Stopping metrics logging.
2018-08-06T07:17:09.705Z	INFO	instance/beat.go:373	metricbeat stopped.
PASS
coverage: 8.3% of statements in github.com/elastic/beats/metricbeat, github.com/elastic/beats/metricbeat/autodiscover, github.com/elastic/beats/metricbeat/autodiscover/appender/kubernetes/token, github.com/elastic/beats/metricbeat/autodiscover/builder/hints, github.com/elastic/beats/metricbeat/beater, github.com/elastic/beats/metricbeat/cmd, github.com/elastic/beats/metricbeat/cmd/test, github.com/elastic/beats/metricbeat/helper, github.com/elastic/beats/metricbeat/helper/elastic, github.com/elastic/beats/metricbeat/helper/prometheus, github.com/elastic/beats/metricbeat/helper/prometheus/ptest, github.com/elastic/beats/metricbeat/helper/server, github.com/elastic/beats/metricbeat/helper/server/http, github.com/elastic/beats/metricbeat/helper/server/tcp, github.com/elastic/beats/metricbeat/helper/server/udp, github.com/elastic/beats/metricbeat/include, github.com/elastic/beats/metricbeat/include/fields, github.com/elastic/beats/metricbeat/mb, github.com/elastic/beats/metricbeat/mb/module, github.com/elastic/beats/metricbeat/mb/parse, github.com/elastic/beats/metricbeat/mb/testing, github.com/elastic/beats/metricbeat/module, github.com/elastic/beats/metricbeat/module/aerospike, github.com/elastic/beats/metricbeat/module/aerospike/namespace, github.com/elastic/beats/metricbeat/module/apache, github.com/elastic/beats/metricbeat/module/apache/status, github.com/elastic/beats/metricbeat/module/ceph, github.com/elastic/beats/metricbeat/module/ceph/cluster_disk, github.com/elastic/beats/metricbeat/module/ceph/cluster_health, github.com/elastic/beats/metricbeat/module/ceph/cluster_status, github.com/elastic/beats/metricbeat/module/ceph/monitor_health, github.com/elastic/beats/metricbeat/module/ceph/osd_df, github.com/elastic/beats/metricbeat/module/ceph/osd_tree, github.com/elastic/beats/metricbeat/module/ceph/pool_disk, github.com/elastic/beats/metricbeat/module/couchbase, github.com/elastic/beats/metricbeat/module/couchbase/bucket, github.com/elastic/beats/metricbeat/module/couchbase/cluster, github.com/elastic/beats/metricbeat/module/couchbase/node, github.com/elastic/beats/metricbeat/module/docker, github.com/elastic/beats/metricbeat/module/docker/container, github.com/elastic/beats/metricbeat/module/docker/cpu, github.com/elastic/beats/metricbeat/module/docker/diskio, github.com/elastic/beats/metricbeat/module/docker/healthcheck, github.com/elastic/beats/metricbeat/module/docker/image, github.com/elastic/beats/metricbeat/module/docker/info, github.com/elastic/beats/metricbeat/module/docker/memory, github.com/elastic/beats/metricbeat/module/docker/network, github.com/elastic/beats/metricbeat/module/dropwizard, github.com/elastic/beats/metricbeat/module/dropwizard/collector, github.com/elastic/beats/metricbeat/module/elasticsearch, github.com/elastic/beats/metricbeat/module/elasticsearch/cluster_stats, github.com/elastic/beats/metricbeat/module/elasticsearch/index, github.com/elastic/beats/metricbeat/module/elasticsearch/index_recovery, github.com/elastic/beats/metricbeat/module/elasticsearch/index_summary, github.com/elastic/beats/metricbeat/module/elasticsearch/ml_job, github.com/elastic/beats/metricbeat/module/elasticsearch/node, github.com/elastic/beats/metricbeat/module/elasticsearch/node_stats, github.com/elastic/beats/metricbeat/module/elasticsearch/pending_tasks, github.com/elastic/beats/metricbeat/module/elasticsearch/shard, github.com/elastic/beats/metricbeat/module/envoyproxy, github.com/elastic/beats/metricbeat/module/envoyproxy/server, github.com/elastic/beats/metricbeat/module/etcd, github.com/elastic/beats/metricbeat/module/etcd/leader, github.com/elastic/beats/metricbeat/module/etcd/self, github.com/elastic/beats/metricbeat/module/etcd/store, github.com/elastic/beats/metricbeat/module/golang, github.com/elastic/beats/metricbeat/module/golang/expvar, github.com/elastic/beats/metricbeat/module/golang/heap, github.com/elastic/beats/metricbeat/module/graphite, github.com/elastic/beats/metricbeat/module/graphite/server, github.com/elastic/beats/metricbeat/module/haproxy, github.com/elastic/beats/metricbeat/module/haproxy/info, github.com/elastic/beats/metricbeat/module/haproxy/stat, github.com/elastic/beats/metricbeat/module/http, github.com/elastic/beats/metricbeat/module/http/json, github.com/elastic/beats/metricbeat/module/http/server, github.com/elastic/beats/metricbeat/module/jolokia, github.com/elastic/beats/metricbeat/module/jolokia/jmx, github.com/elastic/beats/metricbeat/module/kafka, github.com/elastic/beats/metricbeat/module/kafka/consumergroup, github.com/elastic/beats/metricbeat/module/kafka/partition, github.com/elastic/beats/metricbeat/module/kibana, github.com/elastic/beats/metricbeat/module/kibana/mtest, github.com/elastic/beats/metricbeat/module/kibana/stats, github.com/elastic/beats/metricbeat/module/kibana/status, github.com/elastic/beats/metricbeat/module/kubernetes, github.com/elastic/beats/metricbeat/module/kubernetes/apiserver, github.com/elastic/beats/metricbeat/module/kubernetes/container, github.com/elastic/beats/metricbeat/module/kubernetes/event, github.com/elastic/beats/metricbeat/module/kubernetes/node, github.com/elastic/beats/metricbeat/module/kubernetes/pod, github.com/elastic/beats/metricbeat/module/kubernetes/state_container, github.com/elastic/beats/metricbeat/module/kubernetes/state_deployment, github.com/elastic/beats/metricbeat/module/kubernetes/state_node, github.com/elastic/beats/metricbeat/module/kubernetes/state_pod, github.com/elastic/beats/metricbeat/module/kubernetes/state_replicaset, github.com/elastic/beats/metricbeat/module/kubernetes/state_statefulset, github.com/elastic/beats/metricbeat/module/kubernetes/system, github.com/elastic/beats/metricbeat/module/kubernetes/util, github.com/elastic/beats/metricbeat/module/kubernetes/volume, github.com/elastic/beats/metricbeat/module/kvm, github.com/elastic/beats/metricbeat/module/kvm/dommemstat, github.com/elastic/beats/metricbeat/module/logstash, github.com/elastic/beats/metricbeat/module/logstash/node, github.com/elastic/beats/metricbeat/module/logstash/node_stats, github.com/elastic/beats/metricbeat/module/memcached, github.com/elastic/beats/metricbeat/module/memcached/stats, github.com/elastic/beats/metricbeat/module/mongodb, github.com/elastic/beats/metricbeat/module/mongodb/collstats, github.com/elastic/beats/metricbeat/module/mongodb/dbstats, github.com/elastic/beats/metricbeat/module/mongodb/metrics, github.com/elastic/beats/metricbeat/module/mongodb/status, github.com/elastic/beats/metricbeat/module/munin, github.com/elastic/beats/metricbeat/module/munin/node, github.com/elastic/beats/metricbeat/module/mysql, github.com/elastic/beats/metricbeat/module/mysql/galera_status, github.com/elastic/beats/metricbeat/module/mysql/status, github.com/elastic/beats/metricbeat/module/nginx, github.com/elastic/beats/metricbeat/module/nginx/stubstatus, github.com/elastic/beats/metricbeat/module/php_fpm, github.com/elastic/beats/metricbeat/module/php_fpm/pool, github.com/elastic/beats/metricbeat/module/postgresql, github.com/elastic/beats/metricbeat/module/postgresql/activity, github.com/elastic/beats/metricbeat/module/postgresql/bgwriter, github.com/elastic/beats/metricbeat/module/postgresql/database, github.com/elastic/beats/metricbeat/module/postgresql/statement, github.com/elastic/beats/metricbeat/module/prometheus, github.com/elastic/beats/metricbeat/module/prometheus/collector, github.com/elastic/beats/metricbeat/module/prometheus/stats, github.com/elastic/beats/metricbeat/module/rabbitmq, github.com/elastic/beats/metricbeat/module/rabbitmq/connection, github.com/elastic/beats/metricbeat/module/rabbitmq/exchange, github.com/elastic/beats/metricbeat/module/rabbitmq/mtest, github.com/elastic/beats/metricbeat/module/rabbitmq/node, github.com/elastic/beats/metricbeat/module/rabbitmq/queue, github.com/elastic/beats/metricbeat/module/redis, github.com/elastic/beats/metricbeat/module/redis/info, github.com/elastic/beats/metricbeat/module/redis/keyspace, github.com/elastic/beats/metricbeat/module/system, github.com/elastic/beats/metricbeat/module/system/core, github.com/elastic/beats/metricbeat/module/system/cpu, github.com/elastic/beats/metricbeat/module/system/diskio, github.com/elastic/beats/metricbeat/module/system/filesystem, github.com/elastic/beats/metricbeat/module/system/fsstat, github.com/elastic/beats/metricbeat/module/system/load, github.com/elastic/beats/metricbeat/module/system/memory, github.com/elastic/beats/metricbeat/module/system/network, github.com/elastic/beats/metricbeat/module/system/process, github.com/elastic/beats/metricbeat/module/system/process_summary, github.com/elastic/beats/metricbeat/module/system/raid, github.com/elastic/beats/metricbeat/module/system/socket, github.com/elastic/beats/metricbeat/module/system/socket_summary, github.com/elastic/beats/metricbeat/module/system/uptime, github.com/elastic/beats/metricbeat/module/traefik, github.com/elastic/beats/metricbeat/module/traefik/health, github.com/elastic/beats/metricbeat/module/traefik/mtest, github.com/elastic/beats/metricbeat/module/uwsgi, github.com/elastic/beats/metricbeat/module/uwsgi/status, github.com/elastic/beats/metricbeat/module/vsphere, github.com/elastic/beats/metricbeat/module/vsphere/datastore, github.com/elastic/beats/metricbeat/module/vsphere/host, github.com/elastic/beats/metricbeat/module/vsphere/virtualmachine, github.com/elastic/beats/metricbeat/module/windows, github.com/elastic/beats/metricbeat/module/windows/perfmon, github.com/elastic/beats/metricbeat/module/windows/service, github.com/elastic/beats/metricbeat/module/zookeeper, github.com/elastic/beats/metricbeat/module/zookeeper/mntr, github.com/elastic/beats/metricbeat/processor/add_kubernetes_metadata, github.com/elastic/beats/metricbeat/scripts/assets
```

### PR DESCRIPTION
**Pull request by jsoriano**
Required method of gopsutil is not implemented for Windows.

Fixes #7868

### CODE REVIEW

**Comment by andrewkroh** [comment]
Should the metricset even be registered on Windows?

Do the docs reflect the lack of Windows support?

**Comment by jsoriano** [comment]
Indeed it appeared in the documentation as supported, line removed.

Regarding registering it, I don't know if we are doing this in other modules, what would be the better way of doing it? Directly checking the OS in the init and skipping registering the ms, or returning an error explicitely mentioning the lack of support in windows in `New`?

**Comment by jsoriano** [comment]
Added by now an error when starting the metricset, I find it more explicit for the user, but I'm ok with moving the check to init to avoid even registering it.

**Comment by ruflin** [comment]
I remember in some cases we didn't `init` not supported modules / metricsets. It would be nice if code not needed would not be compile for a platform at the same time I like the error message that states specifically a metricset is not supported for a platform and not only an error that it doesn't exist. Not sure how we can get the best of both worlds.

**Comment by andrewkroh** [comment]
For metricsets that are not implemented for an OS we have traditionally done one of two things.

- Use a build tag to not include an implementation. This results in an error like `x metricset is not registered` which isn't that clear to a user.
- Use a build tag to include a `metricset_unsupported.go` that registers a factory that returns an error like `x is not supported on Windows`.

**Comment by jsoriano** [comment]
I like the second option :slightly_smiling_face:

**Comment by ruflin** [comment]
++ on the second option. Let's make this our default.

**Pull request merged**
