### PR TITLE
Allow `-` in Apache access log byte count

### PR DESCRIPTION
**Pull request by cwurm**
Allows a `-` instead of a number for the byte sent part of the Apache access log, as described in http://httpd.apache.org/docs/current/mod/mod_log_config.html

In contrast, Nginx will always output `0` - so no need to change anything there.

There are a few more pieces in the Grok pattern that are not quite in line with what Apache can produce. The Elasticsearch grok processor inherited [a list of patterns](https://github.com/elastic/elasticsearch/blob/master/modules/ingest-common/src/main/resources/patterns/grok-patterns#L95) from Logstash. One of them being `COMBINEDAPACHELOG`, we might want to mirror that in Filebeat. I guess that might be a more intrusive change, while this PR as-is can do no harm and should be fully backward compatible.

### CODE REVIEW

**Comment by cwurm** [comment]
This addresses https://github.com/elastic/beats/issues/3833.

**Comment by exekias** [comment]
jenkins, retest it please

**Comment by exekias** [comment]
Could you please add  CHANGELOG entry?

**Comment by cwurm** [comment]
@exekias I guess, though what should it look like? Which version(s)? Most recent release is 5.3.0, and the CHANGELOG here on master doesn't even cover that.

**Comment by exekias** [comment]
Just add it in HEAD section, we will manage that in the backport

**Comment by cwurm** [comment]
@exekias done

**Comment by tsg** [comment]
Thanks for the fix @cwurm. I didn't use the `COMBINEDAPACHELOG` because I want control over the names of the resulting fields. Perhaps another option would have been to do renames afterwards, not sure.

**Comment by cwurm** [comment]
@tsg We could take the grok pattern behind `COMBINEDAPACHELOG` and replace the variable names. Except for some for which we don't have a field Beats - but that's probably fine, as almost nobody uses `ident` anyway for example.

**Pull request merged**
