### PR TITLE
Remove duplicate line from the reference config

### PR DESCRIPTION
**Pull request by TheFakeStefan**
Remove duplicate line from the reference config

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

It is just a removal of a comment line. No need to test this PR.

## Related issues

None.

### CODE REVIEW

**Comment by adriansr** [comment]
jenkins run the tests please

**Comment by adriansr** [comment]
Build is failing with:
> Error: some files are not up-to-date. Run 'mage fmt update' then review and commit the changes. Modified: [auditbeat/auditbeat.reference.yml]

This needs a `mage fmt update` inside `auditbeat` and `x-pack/auditbeat`, then push the resulting changes to autogenerated files. I can push those changes for you if you prefer.

**Comment by TheFakeStefan** [comment]
Feel free to push Adrian.

Thanks,
Stefan

**Comment by adriansr** [comment]
Given that the source repo has been removed I'm performing the same changes in https://github.com/elastic/beats/pull/23481

Sorry it took so long to respond.

**Pull request closed without merging**
