### PR TITLE
Include log.source.address for unparseable syslog messages

### LINKED ISSUE #13268: filebeat syslog input: missing `log.source.address` when message not parsed
- Version: 7.3.0
- Operating System: Ubuntu 18.04.3
- Steps to Reproduce: 

```
filebeat.inputs:
- type: syslog
  enabled: true
  protocol.udp:
    host: "localhost:5514"

output.console:
  enabled: true
  codec.json:
    pretty: true
```

Submit a message using `nc` in a format which is not parsable.  The following example is a message from a Netgear switch, which has a spurious space after the `<PRI>`

```
echo -n "<13> Aug 16 12:25:24 10.12.255.2-1 TRAPMGR[53034492]: traputil.c(696) 135956 %% Link Up: g5." | nc -w0 -u localhost 5514
```

Result:

```
{
  "@timestamp": "2019-08-16T11:40:46.045Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "_doc",
    "version": "7.3.0",
    "truncated": false
  },
  "ecs": {
    "version": "1.0.1"
  },
  "host": {
    "name": "test1"
  },
  "message": "<13> Aug 16 12:25:24 10.12.255.2-1 TRAPMGR[53034492]: traputil.c(696) 135956 %% Link Up: g5.",
  "input": {
    "type": "syslog"
  },
  "agent": {
    "type": "filebeat",
    "ephemeral_id": "1dd71572-8757-4810-8840-f7d9e75eace5",
    "hostname": "test1",
    "id": "5ebedd24-b8a6-4445-bd8a-055a026404e3",
    "version": "7.3.0"
  }
}
```

The message has been captured, and it has not been further parsed (which is fine).

However, the JSON is missing the `log.source.address` field which is normally present.  If I resend the message without the spurious space, then I get:

```
  "log": {
    "source": {
      "address": "127.0.0.1:32818"
    }
  },
```

This means that with such badly-formatted messages, the information about where they originated from has been lost, making it very hard to trace them back to source.

### PR DESCRIPTION
**Pull request by candlerb**
Fixes #13268

### CODE REVIEW

**Comment by jsoriano** [comment]
ok to test

**Comment by strawgate** [comment]
Can this move forward? This is causing us significant problems in our environment

**Comment by jsoriano** [comment]
This will need a changelog entry.

@ph could you also take a look to this change? Thanks!

**Comment by ph** [comment]
LGTM, need a changelog entry and a test

**Comment by strawgate** [comment]
Not having this is causing issues in our environment as its basically impossible to tell where the log message that is invalid came from...

**Comment by jsoriano** [comment]
@candlerb could you add the test and the changelog entry? If you don't have time it is ok, we can also continue with this change.

Thanks!

**Comment by candlerb** [comment]
Sorry, at the time I couldn't see an easy way to add a test to this without big refactoring, in a codebase I wasn't familiar with.

**Comment by jsoriano** [comment]
I am continuing with this in https://github.com/elastic/beats/pull/15453.

@candlerb I will add you as co-author, thanks for starting with this!

**Pull request closed without merging**
