### PR TITLE
Moved files out of the scripts folder

### PR DESCRIPTION
**Pull request by tsg**
We now have the `dev-tools` folder, so moved the `aggregate_coverage.py` script
there. The `docker-entrypoint.sh` is moved for now in `libbeat/scripts`.

Also added a README in the `dev-tools` folder and updated the README from the
`libbeat/scripts` folder.

### CODE REVIEW

**Comment by ruflin** [comment]
@tsg Looks like these paths have to be updated: https://github.com/elastic/beats/blob/master/.appveyor.yml#L76

**Comment by tsg** [comment]
Updated and rebased. Thanks, i got tricked by the fact that `ag` doesn't search in dot files.

**Comment by ruflin** [comment]
@tsg I just merged https://github.com/elastic/beats/pull/723 and realised it will conflict with this one here. You probably have to rebase again :-( Sorry.

**Comment by tsg** [comment]
@ruflin I just rebased it to master. Thanks!

**Comment by tsg** [comment]
Rebased again, now actually mergeable.

**Pull request merged**
