### PR TITLE
Packetbeat: add COMMAND, COMMANDREPLY mongodb opcodes

### PR DESCRIPTION
**Pull request by jaipradeesh**
Ref: https://github.com/elastic/beats/issues/6191

r? @adriansr 

Signed-off-by: Jaipradeesh <jaipradeesh@gmail.com>

### CODE REVIEW

**Comment by ruflin** [comment]
@jaipradeesh Could you add some tests with pcap files for this if possible? Also please add a line to the changelog file.

Still needs review from probably @adriansr

**Comment by jaipradeesh** [comment]
```
15:41 < dolftax> In need of pcap files to test OP_COMMAND and OP_COMMANDREPLY opcodes // How to trigger them?
15:46 <@Derick> dolftax: let me check for you
15:46 <@Derick> dolftax: what do you need the pcap files for?
15:47 <@Derick> dolftax: I believe these are used by the mongos balancer in a sharded environment
15:48 <@Derick> and only with MongoDB 3.4 (although 3.2 and 3.6 support it too for up/downgrade)
15:49 < dolftax> Just need to know it some calls to DB from the client returns such opcodes. Since what queries is made by the client is not in my control, just need to run a quick test on the response opcodes and see if it sends any invalid opcodes.
15:49 < dolftax> invalid -> not whitelisted by us.
15:49 <@Derick> I would strongly suggest you do not white or blacklist any opcodes that MongoDB uses, as this can change in the future without warning
15:51 <@Derick> But: mongos 3.4 balancer commands use it
15:52 <@Derick> and to illustrate that op codes get added all the time: https://derickrethans.nl/wireshark-mongo-36.html
15:53 < dolftax> So, https://docs.mongodb.com/manual/reference/mongodb-wire-protocol/ are not really a whitelist of opcodes?
15:54 <@Derick> no
15:54 <@Derick> it misses things
15:55 <@Derick> do not restrict what MongoDB can send/receive
```

@ruflin In such case, I don't think validating across the whitelist of opcodes makes sense. What do you think?

**Comment by andrewkroh** [comment]
LGTM, but I would feel better about merging if there were a test covering these opcodes. Would you be able to add a test case? Like in either of:

- https://github.com/elastic/beats/blob/master/packetbeat/tests/system/test_0025_mongodb_basic.py
- https://github.com/elastic/beats/blob/master/packetbeat/protos/mongodb/mongodb_test.go

**Comment by jaipradeesh** [comment]
@andrewkroh I was waiting for @adriansr 's input on this because (I was looking for a sample pcap file with OP_COMMAND and OP_COMMANDREPLY codes) Derick from MongoDB team suggested not to whitelist any opcodes as it might change without warning. An example scenario from Wireshark who did the same (whitelist opcodes on wire protocol) - https://derickrethans.nl/wireshark-mongo-36.html

For example: `OP_COMPRESSED` isn't documented on Wire protocol opcode docs - https://docs.mongodb.com/manual/reference/mongodb-wire-protocol/ but it is a valid one.

Ref: https://github.com/elastic/beats/issues/6191#issuecomment-368825298

**Comment by adriansr** [comment]
Hi @jaipradeesh 

How do you feel about adding the test?

I think best is adding a system-test (the python ones) that reads a pcap file and checks that no warning/errors are printed to the log (`self.assert_no_logged_warnings()`).

**Pull request closed without merging**
