### PR TITLE
[Metricbeat] Enable all AWS regions by default

### PR DESCRIPTION
**Pull request by mtojek**
This PR enables all AWS regions by default.

Issue: https://github.com/elastic/beats/issues/14964

/cc @kaiyan-sheng

### CODE REVIEW

**Comment by ChrsMark** [comment]
Will this work as is? I had a case where I had not set `region` at all and Metricbeat was not collecting metrics at all. I had to set the region explicitly so as to start collecting. Also there was no relevant logs to indicate this "problem".

**Comment by mtojek** [comment]
Looking at logs at the moment I see two regions (so I assume it works?):

```
2019-12-17T11:40:46.842+0100	DEBUG	[processors]	processing/processors.go:186	Publish event: {
  "@timestamp": "2019-12-17T10:40:34.387Z",
  "@metadata": {
    "beat": "metricbeat",
    "type": "_doc",
    "version": "8.0.0"
  },
  "service": {
    "type": "aws"
  },
  "cloud": {
    "provider": "aws",
    "region": "us-west-2",
    "account": {
      "id": "428152502467",
      "name": "elastic-beats"
    }
  },
  "aws": {
    "s3": {
      "bucket": {
        "name": "cloudtrail-ingest-beats-serverlessdeploymentbucke-18ogydbac2dwg"
      }
    },
    "s3_daily_storage": {
      "bucket": {
        "size": {
          "bytes": 4.80237e+06
        }
      },
      "number_of_objects": 6
    }
  },
  "ecs": {
    "version": "1.2.0"
  },
  "host": {
    "os": {
      "family": "darwin",
      "name": "Mac OS X",
      "kernel": "18.7.0",
      "build": "18G95",
      "platform": "darwin",
      "version": "10.14.6"
    },
    "id": "24F065F8-4274-521D-8DD5-5D27557E15B4",
    "hostname": "MacBook-Elastic.local",
    "name": "MacBook-Elastic.local",
    "architecture": "x86_64"
  },
  "agent": {
    "ephemeral_id": "27418697-ecf1-4b10-bfd6-baca82fafa92",
    "hostname": "MacBook-Elastic.local",
    "id": "d662b58a-49c9-4241-aaaf-c5489341138c",
    "version": "8.0.0",
    "type": "metricbeat"
  },
  "event": {
    "duration": 12453996824,
    "dataset": "aws.s3_daily_storage",
    "module": "aws"
  },
  "metricset": {
    "period": 86400000,
    "name": "s3_daily_storage"
  }
}
2019-12-17T11:40:50.106+0100	DEBUG	[processors]	processing/processors.go:186	Publish event: {
  "@timestamp": "2019-12-17T10:40:29.468Z",
  "@metadata": {
    "beat": "metricbeat",
    "type": "_doc",
    "version": "8.0.0"
  },
  "event": {
    "dataset": "aws.ec2",
    "module": "aws",
    "duration": 20637262288
  },
  "service": {
    "type": "aws"
  },
  "aws": {
    "ec2": {
      "instance": {
        "state": {
          "name": "running",
          "code": 16
        },
        "monitoring": {
          "state": "disabled"
        },
        "core": {
          "count": 1
        },
        "threads_per_core": 1,
        "public": {
          "ip": "54.147.243.63",
          "dns_name": "ec2-54-147-243-63.compute-1.amazonaws.com"
        },
        "private": {
          "dns_name": "ip-172-31-81-156.ec2.internal",
          "ip": "172.31.81.156"
        },
        "image": {
          "id": "ami-00068cd7555f543d5"
        }
      },
      "cpu": {
        "surplus_credits_charged": 0,
        "total": {
          "pct": 0.10060297719992839
        },
        "credit_usage": 0.006431,
        "credit_balance": 108.636723,
        "surplus_credit_balance": 0
      },
      "diskio": {
        "read": {
          "count_per_sec": 0,
          "bytes": 0,
          "count": 0,
          "bytes_per_sec": 0
        },
        "write": {
          "count_per_sec": 0,
          "bytes": 0,
          "count": 0,
          "bytes_per_sec": 0
        }
      },
      "network": {
        "in": {
          "bytes": 745.6,
          "packets": 8.6,
          "bytes_per_sec": 2.4853333333333336,
          "packets_per_sec": 0.028666666666666667
        },
        "out": {
          "bytes_per_sec": 1.9313333333333333,
          "packets_per_sec": 0.030666666666666665,
          "bytes": 579.4,
          "packets": 9.2
        }
      },
      "status": {
        "check_failed_system": 0,
        "check_failed": 0,
        "check_failed_instance": 0
      }
    }
  },
  "cloud": {
    "account": {
      "name": "elastic-beats",
      "id": "428152502467"
    },
    "instance": {
      "id": "i-05381e495aa0f95ef"
    },
    "machine": {
      "type": "t2.micro"
    },
    "availability_zone": "us-east-1b",
    "provider": "aws",
    "region": "us-east-1"
  },
  "metricset": {
    "name": "ec2",
    "period": 300000
  },
  "ecs": {
    "version": "1.2.0"
  },
  "host": {
    "name": "MacBook-Elastic.local",
    "os": {
      "family": "darwin",
      "name": "Mac OS X",
      "kernel": "18.7.0",
      "build": "18G95",
      "platform": "darwin",
      "version": "10.14.6"
    },
    "id": "24F065F8-4274-521D-8DD5-5D27557E15B4",
    "hostname": "MacBook-Elastic.local",
    "architecture": "x86_64"
  },
  "agent": {
    "id": "d662b58a-49c9-4241-aaaf-c5489341138c",
    "version": "8.0.0",
    "type": "metricbeat",
    "ephemeral_id": "27418697-ecf1-4b10-bfd6-baca82fafa92",
    "hostname": "MacBook-Elastic.local"
  }
}
```

**Comment by ChrsMark** [comment]
Thanks for clarifying this @mtojek ! I re tested it on my and and I cannot reproduce it any more. Maybe it had to do with lack of data on Cloudwatch.

**Comment by kaiyan-sheng** [comment]
> Will this work as is? I had a case where I had not set `region` at all and Metricbeat was not collecting metrics at all. I had to set the region explicitly so as to start collecting. Also there was no relevant logs to indicate this "problem".

Hmm which version did you run into this issue? We used to have a `default_region` parameter(different than this region) but that is not being used anymore.

**Pull request merged**
