### PR TITLE
fix the url of reviewdog

### PR DESCRIPTION
**Pull request by shogo82148**
- Bug

## What does this PR do?

Updates the url of reviewdog.

## Why is it important?

related to https://github.com/elastic/beats/issues/21976
It looks that Go tries to install the reviewdog from [github.com/haya14busa/reviewdog](github.com/haya14busa/reviewdog), but the reviewdog was moved to [reviewdog organization](https://github.com/reviewdog/).
New url of the reviewdog is [github.com/reviewdog/reviewdog](github.com/reviewdog/reviewdog).

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by ycombinator** [comment]
Hi @shogo82148, would you mind signing the Elastic Contributor License Agreement (CLA) at https://www.elastic.co/contributor-agreement so we can review your PR? Thanks!

**Comment by shogo82148** [comment]
@ycombinator Sure. I have signed.

**Comment by ycombinator** [comment]
jenkins, test this

**Review by jsoriano — APPROVED** [review]
Thanks @shogo82148!

**Pull request merged**
