### PR TITLE
Cherry-pick #14190 to 7.x: Regenerate expected user agent fields

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
This is a cherry pick PR with trying to run `test_modules.py` for 7.x with the new user_agent plugin change and geoip change.

Cherry-pick of PR #14190 to 7.x branch. Original message: 

User agent plugin seems to have changed, and some expected
fields are different. Regenerate expected fields in golden files.

See https://github.com/elastic/beats/pull/14179 and https://github.com/elastic/elasticsearch/issues/48318 for more details.

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
@jsoriano Not sure why when I ran `MODULES_PATH=`pwd`/module GENERATE=1 INTEGRATION_TESTS=1 TESTING_FILEBEAT_MODULES=suricata nosetests -v -d -s tests/system/test_xpack_modules.py`, I got error:
```
2019-11-25T02:13:00.277-0200	ERROR	instance/beat.go:877	Exiting: Error while initializing input: failed to make if/then/else processor: the processor action registered_domain does not exist. Valid actions: decompress_gzip_field, drop_fields, add_observer_metadata, decode_csv_fields, add_kubernetes_metadata, dissect, copy_fields, decode_json_fields, drop_event, add_process_metadata, add_tags, include_fields, truncate_fields, convert, dns, script, add_fields, decode_base64_field, add_cloud_metadata, add_host_metadata, timestamp, rename, add_docker_metadata, extract_array, community_id, add_labels, add_locale
Exiting: Error while initializing input: failed to make if/then/else processor: the processor action registered_domain does not exist. Valid actions: decompress_gzip_field, drop_fields, add_observer_metadata, decode_csv_fields, add_kubernetes_metadata, dissect, copy_fields, decode_json_fields, drop_event, add_process_metadata, add_tags, include_fields, truncate_fields, convert, dns, script, add_fields, decode_base64_field, add_cloud_metadata, add_host_metadata, timestamp, rename, add_docker_metadata, extract_array, community_id, add_labels, add_locale
/Users/kaiyansheng/go/src/github.com/elastic/beats/x-pack/filebeat/filebeat.test -systemTest -e -d * -once -c /Users/kaiyansheng/go/src/github.com/elastic/beats/x-pack/filebeat/build/system-tests/run/test_xpack_modules.XPackTest.test_fileset_file_2_suricata/filebeat.yml -E setup.ilm.enabled=false -modules=suricata -M suricata.*.enabled=false -M suricata.eve.enabled=true -M suricata.eve.var.input=file -M suricata.eve.var.paths=[/Users/kaiyansheng/go/src/github.com/elastic/beats/x-pack/filebeat/module/suricata/eve/test/eve-small.log] -M *.*.input.close_eof=true
```
Do I need to install `registered_domain` separately somehow?

**Comment by jsoriano** [comment]
@kaiyan-sheng it works for me, did you try to rebuild `filebeat.test` with `go test -c`?

**Comment by kaiyan-sheng** [comment]
@jsoriano @urso @ycombinator This PR got a green on travis CI. Should we merge this one and then https://github.com/elastic/beats/pull/14725?

**Comment by jsoriano** [comment]
Umm, this PR doesn't seem to be changing anything at the end? :thinking:

**Comment by kaiyan-sheng** [comment]
@jsoriano oh no what did I do!

**Comment by kaiyan-sheng** [comment]
@jsoriano I reran the test with the wrong ES snapshot... I just created a new PR with changing version from 7.5.0-SNAPSHOT to 7.6.0-SNAPSHOT and all the filebeat changes: https://github.com/elastic/beats/pull/14761

**Pull request closed without merging**
