### PR TITLE
Collect total_data_set_size_in_bytes from elasticsearch module

### LINKED ISSUE #37254: Collect total size for searchable snapshot indices (frozen)
**Describe the enhancement:**
Currently if an index is mounted as a searchable snapshot, it shows as size 0, e.g. in Stack monitor:
image

This is because the ES API for a searchable snapshot returns `size_in_bytes` zero, but reports the underlying size in `total_data_set_size_in_bytes`.
```
    "partial-.ds-logs-apm-ingest-service.log-default-2023.09.01-000029": {
      "uuid": "JHqJcqSHSoOfQ9QRKa4Uvg",
      "health": "green",
      "status": "open",
      "primaries": {
        "docs": {
          "count": 137054,
          "deleted": 0
        },
        "store": {
          "size_in_bytes": 0,
          "total_data_set_size_in_bytes": 59407378,
          "reserved_in_bytes": 0
        },
```
We should collect this field as well.

**Describe a specific use case for the enhancement or feature:**
We want to also show the underlying size to know which indices are taking the most space on object storage.

### PR DESCRIPTION
**Pull request by henrikno**
## Proposed commit message

Collect total_data_set_size_in_bytes from elasticsearch module

Some APIs return total_data_set_size_in_bytes, which is usually the same as size_in_bytes, except when using partially mounted indices/searchable snapshots. For those the size_in_bytes returns zero, while total_data_set_size_in_bytes is the total shard size of the backing index on object storage.
We want to collect this to see how much storage each index is using on object storage.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

Closes #37254

### CODE REVIEW

**Comment by miltonhultgren** [comment]
@henrikno Before I look at the code, is this something we want to make available to X-pack mode users (ESS for example) and Elastic Agent Integration users? If yes to either of those, we'll need to update the mappings for those modes as well.

**Comment by henrikno** [comment]
I'd say yes. Not sure which files need to be updated for that.

**Comment by miltonhultgren** [comment]
The change for the X-pack mode would happen in the elasticsearch repo and look something like this https://github.com/elastic/elasticsearch/pull/103709

The change for the Integration would look something like this https://github.com/elastic/integrations/pull/8796

**Review by miltonhultgren — APPROVED** [review]
Code changes look like expected 👍🏼

**Comment by henrikno** [comment]
@miltonhultgren Thanks for your help. 
Created https://github.com/elastic/elasticsearch/pull/104432 and https://github.com/elastic/integrations/pull/8897

**Pull request merged**
