### PR TITLE
Update Go to 1.13.4

### PR DESCRIPTION
**Pull request by mikemadden42**

### CODE REVIEW

**Comment by urso** [comment]
Please rebase on top of master. I found some missing `testing.Init` and fixed them.

**Comment by andrewkroh** [comment]
run beats-ci/package

**Comment by mikemadden42** [comment]
> Please rebase on top of master. I found some missing `testing.Init` and fixed them.

I've rebased on top of master.

**Comment by mikemadden42** [comment]
run beats-ci/package

**Pull request merged**
