### PR TITLE
Fix kubernetes in-cluster configuration on IPv6

### LINKED ISSUE #8749: filebeat add_kubernetes_metadata and IPv6
When using filebeat in a Kubernetes cluster as a pod, using the add_kubernetes_metadata processor, the processor can't handle IPv6 addresses if an IPv6 address resolves from https://kubernetes.default.svc.cluster.local. The parser freaks out on the colons in the address. I don't know if this is an issue in an underlying library or Filebeat itself.

Secondary to this issue, it would be nice to provide a custom Kubernetes API endpoint to use, so I could try something like https://[2001:0db8:85a3:0000:0000:8a2e:0370:7334]:443 (and force the use of brackets). It looks like I can only do this if I set in_cluster to "false" and provide a kubeconfig file.

Error:
```
2018-10-25T14:45:51.809Z    ERROR    instance/beat.go:743    Exiting: performing request: Get https://fd00:1234::1:443/api/v1/pods?fieldSelector=spec.nodeName%3Dlocalhost&resourceVersion=0: invalid URL port "1234::1:443"

Exiting: performing request: Get https://fd00:1234::1:443/api/v1/pods?fieldSelector=spec.nodeName%3Dlocalhost&resourceVersion=0: invalid URL port "1234::1:443"
```

For confirmed bugs, please report:
- Version: docker.elastic.co/beats/filebeat:6.4.2
- Discuss Forum URL: https://discuss.elastic.co/t/filebeat-add-kubernetes-metadata-and-ipv6/154018
- Steps to Reproduce: Run Kubernetes v1.11 in an IPv6-only environment (can be run locally with [KDinD](https://github.com/kubernetes-sigs/kubeadm-dind-cluster/blob/master/fixed/dind-cluster-v1.11.sh), deploy the Filebeat daemonset.

### PR DESCRIPTION
**Pull request by jsoriano**
Include patch for IPv6 in kubernetes client library (https://github.com/ericchiang/k8s/pull/103),
already merged in master but not released yet.

Fixes #8749

### CODE REVIEW

**Comment by jsoriano** [comment]
Failing tests in CI are not related

**Comment by exekias** [comment]
This is great @jsoriano, did you push the fix upstream? It would be awesome to keep vendoring the main repo, we will probably want to upgrade to next releases in the future

**Comment by exekias** [comment]
Just saw https://github.com/ericchiang/k8s/pull/103 :+1: merging this now, let's upgrade the dependency once they tag the next version including this fix

**Comment by hhoover** [comment]
just to close the loop on this - what container tag should I use with the fix in it when deploying?

**Comment by jsoriano** [comment]
@hhoover there is still no release including this change, in principle it will be included in upcoming 6.5 and subsequent releases.

**Pull request merged**
