### PR TITLE
i5354: Harmonize field names between Packetbeat HTTP and Metricbeat Module

### PR DESCRIPTION
**Pull request by christiangalsterer**
@ruflin: Here the new/updated PR.

### CODE REVIEW

**Comment by ruflin** [comment]
@christiangalsterer Thanks for the PR. Could you add an entry to the Changelog under breaking changes? It's ok that it is breaking as the http module is still in beta.

**Comment by christiangalsterer** [comment]
Changelog updated.

**Comment by ruflin** [comment]
jenkins, test it

**Comment by ruflin** [comment]
@christiangalsterer Seems like this conflicts with a PR I merged before this one :-( Could you rebase again?

**Comment by christiangalsterer** [comment]
Rebased and committed again ;-)

**Comment by ruflin** [comment]
jenkins, test it

**Pull request merged**
