### PR TITLE
libbeat: kafka: partially solve infinite loops with non-existent topics

### PR DESCRIPTION
**Pull request by GiedriusS**
Partially solve infinite loops that Filebeat goes into by explicitly
listing what Apache Kafka calls "retriable errors" and checking for them
when an error occurs. Then, as time goes on given that no new events
come in, the batch will be completely dropped if `flush.timeout` is set
to at least `10s`. After `10s`, the breaker will be half-open and then 
1 event will be dropped due to an error, and then it will be open again.

Ideally, the breaker wouldn't open when such errors happen but at the
very least we can be smarter from Beats's side by handling errors like
this.

Partially inspired by
https://github.com/logstash-plugins/logstash-integration-kafka/pull/29.

Signed-off-by: Giedrius Statkevičius <giedriuswork@gmail.com>

Will fill these up if there is any interest at all:

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

Start Filebeat with Kafka output configured to point to some non-existent topic. Watch how it constantly tries and fails to do that.

## Related issues

https://github.com/elastic/beats/issues/4166

## Logs

Infinite loop on events every 1 second with default settings:
```
2020-07-17T09:14:35.755Z        DEBUG   [kafka] kafka/client.go:277     finished kafka batch
2020-07-17T09:14:35.755Z        DEBUG   [kafka] kafka/client.go:291     Kafka publish failed with: circuit breaker is open
2020-07-17T09:14:35.755Z        INFO    [publisher]     pipeline/retry.go:221   retryer: send unwait signal to consumer
2020-07-17T09:14:35.755Z        INFO    [publisher]     pipeline/retry.go:225     done
2020-07-17T09:14:35.769Z        DEBUG   [kafka] kafka/client.go:277     finished kafka batch
2020-07-17T09:14:35.769Z        DEBUG   [kafka] kafka/client.go:291     Kafka publish failed with: circuit breaker is open
```

### CODE REVIEW

**Comment by GiedriusS** [comment]
Ping? Is there any interest in this?

**Comment by GiedriusS** [comment]
Hello? :-)

**Comment by faec** [comment]
jenkins run the tests please

**Comment by faec** [comment]
Sorry for the delay! Yes, we are interested and on first pass it looks good. My main uncertainty is how to make sure that the retriable list is stable / complete. I'd want to make sure we don't start rejecting errors that could be retried just because we missed something in the list. Your Kafka link is an excellent reference, but can we be sure that there aren't any other errors that Sarama itself might return that don't correspond to the spec?

`ErrBreakerOpen`, for example, seems to be a sort of out-of-band error in that regard -- are we sure it's the only one? It's plausible to me that the answer is "yes," but I don't know enough about Sarama error conditions to be confident of it at first glance, so if you have more context on that it'd be welcome. Either way it would be nice to get this merged once we've made sure of the details.

**Comment by GiedriusS** [comment]
> Sorry for the delay! Yes, we are interested and on first pass it looks good. My main uncertainty is how to make sure that the retriable list is stable / complete. I'd want to make sure we don't start rejecting errors that could be retried just because we missed something in the list. Your Kafka link is an excellent reference, but can we be sure that there aren't any other errors that Sarama itself might return that don't correspond to the spec?
> 
> `ErrBreakerOpen`, for example, seems to be a sort of out-of-band error in that regard -- are we sure it's the only one? It's plausible to me that the answer is "yes," but I don't know enough about Sarama error conditions to be confident of it at first glance, so if you have more context on that it'd be welcome. Either way it would be nice to get this merged once we've made sure of the details.

Hi! Sorry for the delay in response. It seems like since you wrote that message, you've had some time to look into Sarama & this issue because that code chunk has been changed a bit by you. The link in the comment is generated directly from Kafka's sources so I think there is no better source of information for this. You can double-check here: https://github.com/apache/kafka/search?q=extends+RetriableException.

It seems to me like the previous failure has been related to certain files not being regenerated after I have added a new module to `go.mod`. I have fixed the merge conflicts for this PR. I think that it is still very valid. PTAL @faec

**Comment by faec** [comment]
Closing since this bug has been fixed via other changes in the meantime.

**Pull request closed without merging**
