### PR TITLE
Determine log level for kafka output

### PR DESCRIPTION
**Pull request by anx-mr**
As discussed here:
https://discuss.elastic.co/t/kafka-output-logs-everything-with-warn-level/102259

### CODE REVIEW

**Comment by kvch** [comment]
Thank you for your contribution. Could you please sign the CLA?
https://www.elastic.co/contributor-agreement
Also, could you please add a new entry in CHANGELOG.asciidoc?

**Comment by anx-mr** [comment]
Done. Sorry I think the second changelog update was wrong.. tried to merge

**Comment by kvch** [comment]
I think if you rebase your branch on top of this master, the conflict would diappear.

**Comment by kvch** [comment]
jenkins, test it

**Comment by anx-mr** [comment]
merge/commit mess. will recreate a clean pull request

**Pull request closed without merging**
