### PR TITLE
Update fields.yml

### PR DESCRIPTION
**Pull request by dharada**
it looks typo there. Can you take a look at this PR ?

### CODE REVIEW

**Comment by dharada** [comment]
hello @elastic/docs do you knwo why `Mergify` bot assigened me to this PR ? what is expected to me ?

**Comment by dedemorton** [comment]
I'll get this fixed and merged. Thanks!

**Comment by dedemorton** [comment]
@dharada You get assigned the PR so that you remember to merge the auto backports. BTW, I'm going to add bgckport tags for later releases. Let me know if there was some reason you only wanted to backport this to 7.16. If the changes are already in 7.17+, it's OK...the notice file should be updated anyhow.

**Comment by dharada** [comment]
> @dharada You get assigned the PR so that you remember to merge the auto backports. BTW, I'm going to add backport tags for later releases. Let me know if there was some reason you only wanted to backport this to 7.16. If the changes are already in 7.17+, it's OK...the notice file should be updated anyhow.

hello @dedemorton  sorry I'm not familiar about labeling on PR "auto backports etc..". It was my shortsighted labeling to just put backport to 7.16 only.   (I just thought docs team will handle properly in anyway.)

(If we have some document or manual to know how to do labeling, I'd like to learn it. :smile: )

>you remember to merge the auto backports.

I suppose no manual handling needed from my side anymore. but please let me know if something still expected to do from my side.

**Comment by dedemorton** [comment]
@dharada That's right. I can take it from here. Sorry about the confusing mergify messages. It's the downside of adding automation.

And all you wanted to do was fix a typo. :-)

**Comment by dedemorton** [comment]
jenkins run the tests please

**Review by dedemorton — APPROVED** [review]

**Pull request merged**
