### PR TITLE
Call host parser only once when building light metricsets

### LINKED ISSUE #19849: Lightweight modules parses hosts twice
The Lightweight modules executes the `WithHostParser` twice. This is currently creating a bug when using a custom host parser like the DSN parsers that you can use in MySQL.

# How to reproduce
* Add a custom host parser to the MySQL module, `query` metricset https://github.com/elastic/beats/blob/master/metricbeat/module/mysql/query/query.go#L39 that uses the HostParser defined here https://github.com/elastic/beats/blob/master/metricbeat/module/mysql/mysql.go#L56
* Activate performance metricset and execute and configure the host, for example with `root:root@tcp(127.0.0.1:3306)/`.
* Fails with:
```
Exiting: 1 error: host parser failed on light metricset factory for 'mysql/performance': error parsing mysql host: default addr for network 'root:/' unknown
```
What is happening is that it gets the config data from `mysql.yml` creates the uri and parses it. Then it **mutates** incoming config with the output of the parser. Finally, the parser is executed again with the mutated data and it fails.

Failling block is probably this one https://github.com/elastic/beats/blob/master/metricbeat/mb/lightmetricset.go#L86

It seems that the solution would be to avoid the second execution of the host parser.

## Related issues
https://github.com/elastic/beats/pull/16205

### PR DESCRIPTION
**Pull request by jsoriano**
## What does this PR do?

Call host parser only once on Metricbeat light modules.

## Why is it important?

When using light modules, host parser is called twice. First by the actual implementation
of the metricset, and second after adding the configuration defined in the light module
manifest. Second call might be missing data as the original host is modified after the first
call, causing problems as the ones described in #16205 and #19849.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] ~~I have added tests that prove my fix is effective or that my feature works~~ (Covered by tests from https://github.com/elastic/beats/pull/16205).
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

- There should be no changes in addresses included in metricbeat events, check specially on modules using custom host parsers as the sql ones.
- Check that steps described in #19849 don't cause any issue.

## Related issues

- Closes #19849
- Replaces #16205
- Relates #18955

## Use cases

- Implement light modules based on native modules with custom host parsers.

### CODE REVIEW

**Comment by sayden** [comment]
It LGTM. I know this is a draft but I just wanted to understand how this small piece works:
```
		// At this point host parser was already run, we need to run this again
		// Run the host parser if there was any
		// with the overriden defaults
```

The really confusing part for me is the "overriden defaults". That's why I didn't touch it myself to change it. Can you elaborate briefly what does it mean?

Because it seems obvious that, in the past, we were running host parser twice on purpose for some reason. My question is why Beats did it a bit more complicated in the past (running hostparser twice) when we could do it in a straightforward way (this PR). I mean, maybe we are missing something in this PR that may break if we merge it into Beats

**Comment by sayden** [comment]
I'll also summon @mtojek in case he can spend few minutes peeking around this, as it was related with something he needed to and he may realize of something

**Comment by jsoriano** [comment]
@sayden let me try to explain all this :slightly_smiling_face:

Metricbeat module builder calls the host parser if the registration has anyone defined, here:
https://github.com/elastic/beats/blob/10bfeb4c05a17ffbfaea21ec3f7b88d6f327e184/metricbeat/mb/builders.go#L121-L137

Lightweight metricsets are not registered. When needed, they create a registration based on the registration of the metricset they are based on, here:
https://github.com/elastic/beats/blob/10bfeb4c05a17ffbfaea21ec3f7b88d6f327e184/metricbeat/mb/lightmetricset.go#L44

Then on this registration we replace some things:
* The `Factory`, to override the defaults and some things in the base module as the name and so on. And then call the original factory to setup the metricset.
* `IsDefault`, to indicate if the metricset is a default one.

("Overriding the defaults" on this context is to use the defaults included in the `manifest.yml`, so default settings in the module are updated with default settings in the `manifest.yml`, and they will be updated with the user-defined configuration when building the metricset.)

On the initial implementation we found that host parsers can use other settings apart of `host` to build the host data, and some of these settings make sense in a light module. For example `ParseURL` can use other settings like `username`, `password`, `query` or `path`. It can make sense to define a default path in a `manifest.yml`, but the host parser is called before the factory, before the overrides we do for light modules. So I added the second call to the host parser so settings in the `manifest.yml` are taken into account for the final host data. _At this point I should have done a change like the one of this PR instead of adding the second call, but I didn't foresee the problems then, and I was trying to override the less things I could._

This seemed to work, till @mtojek found that the scheme got lost, the problem is that information in `host` can get lost after parsing it, because we are replacing the `host` value after calling the host parser:
https://github.com/elastic/beats/blob/10bfeb4c05a17ffbfaea21ec3f7b88d6f327e184/metricbeat/mb/builders.go#L136

So the second call to the host parser could be missing some of the original configuration. Then he added #16205 to workaround this specific issue with the scheme, and it worked well for all our current cases because they use in general normal URLs. Now you have found another case that doesn't work.

On this PR I am removing Marcin's change, but I am not touching his tests, so in principle this should work as he expected. I will add him to the review in any case.

**Comment by jsoriano** [comment]
Failures in auditbeat are also happening in master.

**Pull request merged**
