### PR TITLE
Added a link to fileagebeat to the community beats page.

### PR DESCRIPTION
**Pull request by Ardiea**
- Enhancement

## What does this PR do?

Adding a link to fileagebeat to communitybeats.asciidoc

## Why is it important?

It is a beat I developed and contributed to the community. 

## Checklist

- [NA] My code follows the style guidelines of this project
- [NA] I have commented my code, particularly in hard-to-understand areas
- [Yes] I have made corresponding changes to the documentation
- [NA] I have made corresponding change to the default configuration files
- [NA] I have added tests that prove my fix is effective or that my feature works
- [NA] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

NA

## How to test this PR locally

NA

## Related issues

NA

## Use cases

NA

## Screenshots

NA

## Logs

NA

### CODE REVIEW

**Comment by Ardiea** [comment]
I just signed the CLA with username Ardiea about 3 minutes before I opened the PR, so maybe it isn't sync'd yet?

**Comment by andresrc** [comment]
cla/check

**Comment by andresrc** [comment]
cla/check

**Comment by Ardiea** [comment]
cla/check

**Comment by Ardiea** [comment]
I've signed it twice now? I'm not sure what else to do. Definitely signed it with my gh username.

**Comment by andresrc** [comment]
Are you sure it is signed with the same email used in the commit? Thanks!

**Comment by andresrc** [comment]
cla/check

**Comment by Ardiea** [comment]
cla/check

**Pull request closed without merging**
