### PR TITLE
Cherry-pick #22076 to 7.x: Cherry-pick to 7.10: packaging backports

### PR DESCRIPTION
**Pull request by jsoriano**
Cherry-pick of PR #22076 to 7.x branch. Original message: 

Backports the following commits to 7.10:
 - feat: add a new step to run the e2e tests for certain parts of Beats (#21100)
 - [E2E Tests] fix: set versions ony for PRs (#21608)
 - [CI: Packaging] fix: push ubi8 images too (#21621)
 - fix: remove extra curly brace in script (#21692)
 - fix: update fleet test suite name (#21738)
 - chore: create CI artifacts for DEV usage (#21645)
 - chore: simplify triggering the E2E tests for Beats (#21790)
 - chore: delegate variant pushes to the right method (#21861)
 - feat: package aliases for snapshots (#21960)
 - fix: use proper param name for e2e tests (#22836)

### CODE REVIEW

**Review by v1v — APPROVED** [review]

**Comment by jsoriano** [comment]
@v1v I have added #22836 also here to see if it helps with E2E tests.

**Comment by jsoriano** [comment]
@v1v do you think failures in E2E tests are related to this PR? :thinking:

**Comment by v1v** [comment]
I'm not sure :_( 

Maybe `7.x` was not ready to use with these changes?

**Comment by mdelapenya** [comment]
@jsoriano, as we merged a potential fix for the E2E, I'm retriggering the E2E job for this PR

**Comment by mdelapenya** [comment]
> @jsoriano, as we merged a potential fix for the E2E, I'm retriggering the E2E job for this PR, wait for results here: https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/7.x/53/pipeline

Tests are passing, although I found a corner case for the tests verifying the default config files for metricbeat. I'll open a ticket for that.

**Comment by mdelapenya** [comment]
@jsoriano next try once the fixes where merged in the e2e project. Follow the build here: https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/7.x/56/pipeline

**Comment by mdelapenya** [comment]
@jsoriano this is good to merge 🎉 🚀 

https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/7.x/60/tests The only failure is a well-known flaky test.

👍

**Comment by jsoriano** [comment]
@mdelapenya merged, thanks! I have opened the backport to 7.11 #23396.

**Pull request merged**
