### PR TITLE
[Ingest Manager] Allow using drop path for agent build

### PR DESCRIPTION
**Pull request by michalpristas**
## What does this PR do?

This PR allows specifying drop path for dependencies for agent packaging.
When `AGENT_DROP_PATH` is specified as ENV packaging skips preparation of dependencies and uses entire directory.
It requires directory to contain `tar.gz` or `zip` archives, `sha512` files. 

If env is omitted agent packaging prepares filebeat and metrcibeat and includes them in a resulting package.

## Why is it important?

This allows release manager to prepare beats, endpoint and asc files which are needed for release ready packages.
Discussed in #19623 

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by ph** [comment]
Super exciting, I am testing this.

**Comment by ph** [comment]
@michalpristas You are looking with @Conky5  to test this on master before backporting it?

**Comment by michalpristas** [comment]
yes so far no backports

**Comment by blakerouse** [comment]
@michalpristas Have you tried `mage package` locally with this change. I keep getting an error saying that `build/distribution/agent-drop-path` filepath does not exist.

**Comment by michalpristas** [comment]
yeah i tried, you do this on windows?

**Comment by michalpristas** [comment]
can you also get me an error with a stacktrace?

**Comment by ph** [comment]
@michalpristas I've done a bit more testing locally on this, but I haven't been able to make it work like I was expecting it.

If I run `mage package` It generates the artifacts correctly, I don't have the issues that @blakerouse is reporting.
If I create an `/tmp/hello` directory and I copied over the metricbeat and filebeat files and I run `AGENT_DROP_PATH=/tmp/hello mage package` it seems to generate the right thing.
But if I add a `ph-8.0.0-linux-x86_64.tar.gz` and `ph-8.0.0-linux-x86_64.tar.gz.sha512` to the drop path and run the same command as above the ph* files aren't included in the artifact.

**Comment by michalpristas** [comment]
@ph oh yeah, if you look at packaging file (`packages.yml`) it stayed the same and we're still whitelisting things we want to include. 
if we want to blindly copy everything there i can make it so together with including endpoint change. but i'm afraid that this might result in agent bringing too many things which will make our binary too big.

**Comment by ph** [comment]
I've miss the "allowlist" let me try it again. @blakerouse do you still have issues?

**Comment by ph** [comment]
@michalpristas Oh I see, you wanted to make the endpoint support another PR?

**Comment by michalpristas** [comment]
yes this just lays down the base for that

**Comment by ph** [comment]
ok, lets make a followup to add optional bundling of endpoint?

**Comment by blakerouse** [comment]
My repo must have been in a bad state, working good for me as well.

**Comment by Conky5** [comment]
> @michalpristas You are looking with @Conky5 to test this on master before backporting it?

This looks good to me and is working in testing an initial release-manager integration.

**Pull request merged**
