### PR TITLE
Resolve broken download link

### LINKED ISSUE #9580: [Broken Link] Download Functionbeat Package
The [docs](https://www.elastic.co/guide/en/beats/functionbeat/current/functionbeat-installation.html#functionbeat-installation) has a broken link to `Functionbeat-6.5.3` package . Currently, available version download link is for the `Functionbeat-6.5.1` package.

### PR DESCRIPTION
**Pull request by cachedout**
I don't know enough about how and where packages are supposed to be deployed that I can be completely confident this is correct, so please double-check. :)

@dedemorton or @jsoriano may be able to verify, perhaps.

Closes #9580

### CODE REVIEW

**Comment by webmat** [comment]
jenkins, test this please

**Comment by dedemorton** [comment]
So it looks like the download link changed for 6.5.3 (or maybe 6.5.2), so this path needs to be changed in the `6.5` branch. However, if you merge this into `master`, you will break the download for Alpha 1 (the path cannot be changed until Apha 2 is released, when I assume we will be using the changed path).

@ph Should we be changing download paths on bug fix releases? Not sure, but won't this affect customers who are using automation? (I dunno...just speculating.)

@acchen97 I'm on vacation the next couple of weeks (checking email sporadically). Can you make sure this gets resolved? I expect the path change will be relevant in `master` when we release alpha2. So what needs to happen is that someone needs to cherry-pick and merge this into 6.5, then when Alpha 2 releases, someone needs to merge this PR into master. I hope this makes sense.

**Comment by dedemorton** [comment]
So it looks like the download link changed for 6.5.3 (or maybe 6.5.2), so this path needs to be changed in the `6.5` branch. However, if you change it in `master` you will break the download for Alpha 1 (the path cannot be changed until Apha 2 is released).

@ph Should we be changing download paths on bug fix releases? Not sure, but doesn't this affect customers who have automation in place?

@acchen97 I'm on vacation the next couple of weeks (just checking email sporadically). Can you make sure this gets resolved?

**Comment by PosicubeBeege** [comment]
This is still an issue

**Comment by dedemorton** [comment]
jenkins test this please

**Comment by dedemorton** [comment]
@ PosicubeBeege Thanks for bringing this to my attention. I will make sure this change gets merged asap.

**Comment by dedemorton** [comment]
The build errors are not related to docs, so I am merging this.

**Pull request merged**
