### PR TITLE
[Heartbeat] Update synthetics warning message form experimental -> beta

### LINKED ISSUE #25287: [Heartbeat] Move synthetics from experimental to beta
We currently log a warning that synthetics is experimental, but it will be beta in 7.13, let's update those log messages.

### PR DESCRIPTION
**Pull request by andrewvc**
We are now in beta, let's reflect it in our startup warning.

Fixes #25287

### CODE REVIEW

**Review by vigneshshanmugam — APPROVED** [review]
LGTM

**Comment by andrewvc** [comment]
@Mergifyio backport 7.x

**Comment by andrewvc** [comment]
@Mergifyio backport 7.x

**Comment by andrewvc** [comment]
@Mergifyio backport 7.x

**Comment by andrewvc** [comment]
@Mergifyio backport 7.13

**Pull request merged**
