### PR TITLE
Add dns.string.length to improve detection's of dns exfil and tunnelling - Enhancement 

### PR DESCRIPTION
**Pull request by mbudge**
## What does this PR do?

Added dns.question.name and dns.answer.data string lengths to make dns tunneling and dns-exfiltration more efficient when building detection's with Elasticsearch machine learning. The string length fields will prevent ML models for storing all DNS strings which causes problems in high-throughput environments, where systems generate lots of lookups and responses. Instead of storing all strings when these strings have high cardinality, the string length fields will filter out dns.question.name and dns.answer.data strings which aren't dns tunneling. The operator can build the ML model using string lengths over X characters (40 characters is a good place to start).

This will make the detection process more efficient, accurate and reduce false positives. DNS exfil can be detected by analysing dns txt lookups with long subdomain strings. DNS tunnelling by be detected by lookups which return long dns.answer.data strings. Legitimate applications like Anti-virus generate similar lookups which creates background noise.

The code add the following fields

dns.string.length.question.name: int
dns.string.length.answers.data: int array

dns.string.length.question.name is the length of the dns.question.name string
dns.string.length.answers.data is a string array of the dns.answers.data string lengths. 

## Why is it important?

Attempts to build ML models which detect dns exfiltration and dns tunnelling have failed because the fields used to detect this activity have high string cardinality. The ML job's run out of resources before failing. The adding of string length will mean ML jobs can be set up which vastly reduce the amount of data processed. Range queries will be used to only analyse dns.question.name and dns.answer.data string lengths over approximately 40 characters.

During analysis of the dns data this will vastly reduce the amount of data processed. It will also be more accurate than using server.bytes and client.bytes when analysing DNS TXT queries and answers. 

## Checklist

Not got time to finish all the steps.

## Author's Checklist

The following need to be completed.

- Changelog
- Tests 

## How to test this PR locally

Make sure the values are generated when a dns.question.name or dns.answers.data field exists.

## Use cases

- Detecting DNS tunneling where malware communicated with a C2 server through DNS.
- Detecting exfiltration of data over DNS.
- The aim of the PR is to make the detection process more efficient.

### CODE REVIEW

**Comment by andrewkroh** [comment]
Hi @mbudge, I think it would be good to discuss these new fields in the Elastic Common Schema (ECS) [repository](https://github.com/elastic/ecs) since they affect the `dns` namespace. If the values can be standardized in the schema then we can add these to other DNS data sources too.

**Comment by mbudge** [comment]
Finally got round to suggesting the fields in the ECS repo 

https://github.com/elastic/ecs/issues/992

**Comment by marc-gr** [comment]
👍

**Comment by mbudge** [comment]
See update in https://github.com/elastic/ecs/issues/992

**Comment by mbudge** [comment]
Update in https://github.com/elastic/elasticsearch/issues/65636

**Comment by andrewkroh** [comment]
I'm closing this one until we have the ECS enhancement worked out. elastic/ecs#992

**Pull request closed without merging**
