### PR TITLE
Cherry-pick to 6.x: Support for multi-core thread_id in filebeat postgresql module (#9482)

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
* Add support for multi-core thread_id in filebeat postgresql module

* Change timestamp for test log file

* update changelog and add multi-core.log-expected.json

* Change timestamp in example log file

* Update fields.go

(cherry picked from commit 384b11b7d5ba5ede9c08a7fc5b2364ccd83737d9)

### CODE REVIEW

**Comment by jsoriano** [comment]
It seems that `make update` is needed.

**Comment by kaiyan-sheng** [comment]
@jsoriano ha yes! thanks!

**Comment by kaiyan-sheng** [comment]
@jsoriano not good... `test_fileset_file_4_postgresql` failed. I need to look into this hmm

**Comment by ruflin** [comment]
@kaiyan-sheng The data looks a bit different 6.x then master so the generated file might differ. I recommend you to run the tests with the `GENERATE=1` flag against a 6.x Elasticsearch instance.

**Comment by kaiyan-sheng** [comment]
@ruflin Thanks! I switched to use 6.x ES and it helped :-) Now there are several tests failed hmm
> Blacklist blocks bad configs ... FAIL
Config cache is used if Kibana is not available ... FAIL
Enroll the beat in Kibana Central Management ... FAIL
Config is retrieved from Central Management and updates are applied ... FAIL

**Comment by jsoriano** [comment]
Tests are passing in jenkins, I guess failures were something sporadic in travis, I relaunched it.

**Comment by kaiyan-sheng** [comment]
CI failure is tracked by https://github.com/elastic/beats/issues/9597

**Pull request merged**
