### PR TITLE
[Filebeat] Remove space from field `sophos.xg.trans_src_ ip`

### LINKED ISSUE #25154: [FileBeat] Sophos xg field has a space in it's name
Since at least 7.9.0, Sophos xg has `trans_src_ ip` instead of `trans_src_ip`

https://github.com/elastic/beats/blob/23e4403ae093fcc8f7905345cad2c7ad256976d8/x-pack/filebeat/module/sophos/xg/_meta/fields.yml#L228

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Removes the space in `sophos.xg.trans_src_ ip` -> `sophos.xg.trans_src_ip`

## Why is it important?

Field has an invalid space

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have made corresponding change to the default configuration files
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

```
cd beats/x-pack/filebeat
TESTING_FILEBEAT_MODULES=sophos mage -v pythonIntegTest
```

## Related issues

- Closes #25154

### CODE REVIEW

**Comment by legoguy1000** [comment]
@andrewkroh Can you take a look at this one too.  Should be a quick one.

**Comment by P1llus** [comment]
run tests

**Review by P1llus — APPROVED** [review]
LGTM, will await CI to pass then merge.

**Comment by P1llus** [comment]
run tests

**Comment by P1llus** [comment]
Could you backport this to 7.x, 7.12 and 7.13 branches @legoguy1000 ?

**Pull request merged**
