### PR TITLE
Fix kafka TestConfigAcceptValid test when when GSS-API mechanism is used

### LINKED ISSUE #17506: [Flaky Test] TestConfigAcceptValid/Kerberos_with_keytab
## Flaky Test

* **Test Name:** TestConfigAcceptValid
* **Link:** https://github.com/elastic/beats/blob/62f297169fafaf458ccd2963ca6ea51f1832e5d1/libbeat/outputs/kafka/config_test.go#L38-L46
* **Branch:** master
* **Artifact Link:** If available, attach the generated zip artifact associated with the stack trace for this failure.
* **Notes:** It's failing on travis-ci when running `make testsuite`

### Stack Trace

```
github.com/elastic/beats/v7/libbeat/outputs/kafka]: exit status 1
--- FAIL: TestConfigAcceptValid (0.00s)
    --- FAIL: TestConfigAcceptValid/Kerberos_with_keytab (0.00s)
        config_test.go:69: Failure creating sarama config: kafka: invalid configuration (Net.SASL.GSSAPI.Username must not be empty when GSS-API mechanism is used)
FAIL
```

### PR DESCRIPTION
**Pull request by sincejune**
## What does this PR do?

Fix the kafka TestConfigAcceptValid test.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes elastic/beats#17506

### CODE REVIEW

**Comment by sincejune** [comment]
Looks like the CI failed due to OOM.
Would you help re-run the job so that it can pass? Thanks. @kvch

**Comment by kvch** [comment]
jenkins test this

**Comment by kvch** [comment]
Failures are unrelated.

**Comment by kvch** [comment]
Thank you for your fix!

**Pull request merged**
