### PR TITLE
feat: bump badger to v4

### PR DESCRIPTION
**Pull request by kruskall**
## Proposed commit message

bump badger to current major version
drop ristretto replace directive as the glog dependency was removed upstream
See https://github.com/dgraph-io/ristretto/pull/350

bonus point for dropping other unused indirect dependencies

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by mauri870** [comment]
For context, there seems to be no breaking changes in this migration: https://github.com/dgraph-io/badger/releases/tag/v4.0.0.

**Review by mauri870 — APPROVED** [review]

**Comment by blakerouse** [comment]
@kruskall Could you remove the replace on `github.com/golang/glog`? This is no longer needed as the upgraded badger doesn't pull in that dependency anymore.

**Review by cmacknz — APPROVED** [review]

**Comment by blakerouse** [comment]
@kruskall Really? I could have sworn when I looked at the glog dependency it was only being used because of badger v3.

**Comment by blakerouse** [comment]
We also pull in `google.golang.org/grpc` in elastic-agent and it doesn't pull in `github.com/golang/glog`. See here: https://github.com/elastic/elastic-agent/blob/main/go.mod#L72 (and no glog present)

**Comment by carsonip** [comment]
Is the team aware of the implication of upgrading badger across a major version? According to [badger README](https://github.com/dgraph-io/badger?tab=readme-ov-file#choosing-a-version),

> New major versions are released when the data format on disk changes in an incompatible way.
> v2.x.x and v3.x.x are data incompatible as their major version implies, so files created with v2.x.x will need to be converted into the new format before they can be used by v3.0.0.

I see that beats use badger for a persistent cache. If this cache lives across version upgrade without proper handling, there may be a problem.

**Comment by blakerouse** [comment]
@carsonip badger/v4 has no on-disk changes so it can be upgraded safely with no issues - https://github.com/dgraph-io/badger/compare/v3.2103.5...v4.0.0#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4edR10

**Comment by carsonip** [comment]
Thanks, sorry I missed that statement.

**Pull request merged**
