### PR TITLE
Merge from master to 7.x

### PR DESCRIPTION
**Pull request by urso**
There were no significant conflicts.

### CODE REVIEW

**Comment by ruflin** [comment]
Seems like this needs an additional `make update`.

**Comment by ph** [comment]
I've glanced through the commits and it Looks OK, let's wait for CI.

**Comment by adriansr** [comment]
Checked my commits, all OK 👍

**Comment by ycombinator** [comment]
Checked my commits, all OK 👍

**Comment by ruflin** [comment]
jenkins, test this

**Comment by urso** [comment]
Jenkins, test this!

**Pull request merged**
