### PR TITLE
Set ecszap version to v0.2.0

### PR DESCRIPTION
**Pull request by cachedout**
## What does this PR do?

This bumps the version of ecszap from v0.1.1-0.20200424093508-cdd95a104193 to v0.2.0. 

## Why is it important?

This resolves a failure to download modules from a Gocenter proxy. Without this change, the following error is returned when running `go mod download`.

```
go: finding go.elastic.co/ecszap v0.1.1-0.20200424093508-cdd95a104193
go.elastic.co/ecszap@v0.1.1-0.20200424093508-cdd95a104193: proxy returned info for version v0.2.0 instead of requested version
exit status 1
```

This was happening because there is not a v0.1.1 release of ecszap. Current releases can be seen at https://github.com/elastic/ecs-logging-go-zap/releases

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [ ] ~~I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Author's Checklist

- [ ]

## How to test this PR locally

Run `go modules download` and ensure it works.

## Related issues

- Related to https://github.com/elastic/beats/pull/18655

### CODE REVIEW

**Comment by cachedout** [comment]
Thank you @urso and @simitt . I have now included an updated `go.sum` in this PR.

**Comment by cachedout** [comment]
This was failing lint tests due to an error I believe may have been fixed this morning by this: https://github.com/elastic/beats/pull/19124

I have rebased against HEAD and we'll see what happens this time. :)

**Comment by cachedout** [comment]
Hi @urso . Given that you had to write https://github.com/elastic/beats/pull/19161 to correct problems with this PR, I wanted to verify that when I put together a backport PR for this that it should contain both the changes found in this PR and the changes found in https://github.com/elastic/beats/pull/19161. Is that what you had in mind?

**Comment by urso** [comment]
> I wanted to verify that when I put together a backport PR for this that it should contain both the changes found in this PR and the changes found in #19161. Is that what you had in mind?

Yes, please.

**Pull request merged**
