### PR TITLE
nfs: add support for v4.2 operations and error codes

### PR DESCRIPTION
**Pull request by kofemann**
NFSv4.2 (rfc7862) is a published standard since Nov. 2016 and
supported by various nfs servers and clients.

This change is adding operation and status codes defined by
v4.2 spec.

Signed-off-by: Tigran Mkrtchyan <tigran.mkrtchyan@desy.de>

### CODE REVIEW

**Comment by ph** [comment]
Jenkins test this please

**Comment by kofemann** [comment]
I will try to collect some packets with v4.2 and add couple of tests

**Comment by kofemann** [comment]
I have added a simple minimal test for v4.2 operations. I will update tests as soon as new packet capture will be available.

**Comment by kofemann** [comment]
@andrewkroh I don't have any other capture file to add new test

**Comment by andrewkroh** [comment]
Jenkins test this please

**Comment by kofemann** [comment]
Do you expect some actions on my side?

**Comment by andrewkroh** [comment]
Jenkins test this please

**Comment by andrewkroh** [comment]
@kofemann Thanks

**Pull request merged**
