### PR TITLE
update github.com/stretchr/testify/assert to v1.2.0

### PR DESCRIPTION
**Pull request by graphaelli**
and its deps:
* github.com/davecgh/go-spew/spew to v1.1.0
* github.com/pmezard/go-difflib/difflib to v1.0.0

### CODE REVIEW

**Comment by exekias** [comment]
tests seem to be failing:
`can't load package: package github.com/elastic/beats/vendor/github.com/stretchr/testify: no Go files in /home/travis/gopath/src/github.com/elastic/beats/vendor/github.com/stretchr/testify`

**Comment by ruflin** [comment]
@graphaelli What are the commands you did run to update it? It seems quite a few files have been removed which were still needed for our testing I think.

**Comment by simitt** [comment]
@ruflin @exekias can we backport this to `6.x` and `6.2` as the apm-server testsuite is failing otherwise?

**Comment by ruflin** [comment]
@simitt I think the change is to big for 6.2 but should automatically make it into 6.x. Any temp fixes you could do on the 6.2 branch for apm?

**Comment by graphaelli** [comment]
@ruflin we were able to work around it, thanks

**Pull request merged**
