### PR TITLE
Agentbeat: remove unused files from package and silence new error message

### PR DESCRIPTION
**Pull request by cmacknz**
Removes the individual beat configuration files and the README from the agentbeat package. Beats don't read their configuration files when running under agent since 8.6, and the README is wrong for agentbeat (but not the other beats it is templated for).

I also silenced a new error log I noticed that results because the modules sub-directory is no longer present.

The package contents after this change are:

```sh
❯ ls agentbeat-8.15.0-darwin-aarch64/
LICENSE.txt           agentbeat             certs                 osquery-extension.ext
NOTICE.txt            agentbeat.spec.yml    lenses                osquery.app
```

The certs and lenses directories are osquery specific.

What is included in an 8.14.0 agent is (Notice the presence of the readme and beat config files):

```
❯ ls elastic-agent-8.14.0-SNAPSHOT-darwin-aarch64/data/elastic-agent-883cf0/components
LICENSE.txt                     checksum.yml                    heartbeat.yml
NOTICE.txt                      endpoint-security               lenses
README.md                       endpoint-security-resources.zip metricbeat.yml
agentbeat                       endpoint-security.spec.yml      osquery-extension.ext
agentbeat.spec.yml              filebeat.yml                    osquery.app
auditbeat.yml                   fleet-server                    osquerybeat.yml
certs                           fleet-server.spec.yml           packetbeat.yml
```

Tested by extracting the new package into the components directory of a new agent and making sure the Beats start. I don't know that we have a better way to test agentbeat in this repository yet.

### CODE REVIEW

**Comment by cmacknz** [comment]
> [2024-04-22T18:30:04.025Z] docker: Error response from daemon: Head "https://docker.elastic.co/v2/beats-dev/golang-crossbuild/manifests/1.21.9-darwin-arm64-debian10": dial tcp 34.68.230.202:443: i/o timeout.

**Comment by rdner** [comment]
@cmacknz should we fix the linter issues?

**Review by belimawr — APPROVED** [review]

**Comment by cmacknz** [comment]
The latest packaging run succeeded but didn't update the PR status here, https://beats-ci.elastic.co/job/Beats/job/packaging/job/PR-39064/6/. Merging.

**Comment by mamccorm** [comment]
Any plans to cut a v7 and v8 release with this change?

**Comment by cmacknz** [comment]
Not as part of this change. Some time ago it was decided that we would avoid creating a v8 to avoid the toil of updating the import paths across 100s of repositories.

**Pull request merged**
