### PR TITLE
Setup docbook for Metricbeat

### PR DESCRIPTION
**Pull request by andrewkroh**
Setup docbook for Metricbeat so we have a place to incrementally add content.

- Cloned the doc structure from Topbeat.
- Made changes to fields.yml to remove duplicate section titles from the metric sets.

All of the original content written by @ruflin remains in `README.asciidoc` (renamed form index.asciidoc) and needs migrated into the appropriate places within these docs.

You can test the docs with:

```
git clone https://github.com/elastic/docs.git
cd docs
./build_docs.pl --doc $GOPATH/src/github.com/elastic/beats/metricbeat/docs/index.asciidoc
```

### CODE REVIEW

**Comment by andrewkroh** [comment]
I set up a preview of the Metricbeat docs from master on Jenkins. So once this merges this content will update: http://build-eu-00.elastic.co/view/Beats/job/Metricbeat/ws/docs/html_docs/index.html

**Comment by andrewkroh** [comment]
jenkins, retest it

**Comment by ruflin** [comment]
Thanks a lot for working on the docs and do the cleanup. The Docs build is great as I assume this also notifies us, in case we break the docs build?

**Comment by ruflin** [comment]
Change LGTM. I didn't check every single line, but I think it is important to get these changes in and do incremental changes from there.

**Pull request merged**
