### PR TITLE
Merge master to 5.x

### PR DESCRIPTION
**Pull request by andrewkroh**

### CODE REVIEW

**Comment by andrewkroh** [comment]
jenkins, package it

**Comment by andrewkroh** [comment]
jenkins, packet it

**Comment by andrewkroh** [comment]
jenkins, package it

**Comment by andrewkroh** [comment]
After this merges I need to push and update to elastic/stack/5.x to prevent the build from failing.

**Comment by ruflin** [comment]
jenkins, retest it

**Pull request merged**
