### PR TITLE
guard allocating debug statements in tcp module

### PR DESCRIPTION
**Pull request by urso**

### CODE REVIEW

**Comment by ruflin** [comment]
@urso Looks like this could be a general issue? Is this to optimize memory usage?

**Comment by urso** [comment]
yes, it's a general pattern. go allocates a slice right on heap when using variadic arguments.

In general this is fine, I just don't want all these allocs in the very hot code pathes. If no additional arguments are given to debug 'nil' is passed => no alloc.

**Comment by ruflin** [comment]
LGTM

**Comment by tsg** [comment]
LGTM, waiting for travis.

**Pull request merged**
