### PR TITLE
Prometheus Dashboard for Metricbeat

### PR DESCRIPTION
**Pull request by sorantis**
In an effort to increase our dashboard coverage for all modules (https://github.com/elastic/beats/issues/10594) I've created a Prometheus dashboard that shows the following metrics:

- `prometheus_http_requests_total`: Counter of HTTP requests.
- `prometheus_engine_query_duration_seconds`: Query timings for (99th percentile).
- `tsdb_wal_truncations_failed_total`: Total number of WAL truncations that failed.
- `prometheus_tsdb_wal_corruptions_total`: Total number of WAL corruptions.
- `prometheus_tsdb_reloads_total`: Number of times the database reloaded block data from disk.
- `prometheus_tsdb_reloads_failures_total`: Number of times the database failed to reload block data from disk.
- `prometheus_sd_discovered_targets`: Current number of discovered targets.
- `prometheus_tsdb_head_chunks`: Total number of chunks in the head block.
- `prometheus_api_remote_read_queries`: The current number of remote read queries being executed or waiting.
- `prometheus_notifications_queue_capacity`: The capacity of the alert notifications queue.
- `prometheus_notifications_queue_length`: The number of alert notifications in the queue.

The dashboards looks like this:
Screen Shot 2019-07-30 at 22 36 08

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @sorantis, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/beats/pull/13121.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by exekias** [comment]
Thank you! do you have an screenshot for the dashboard? it would be interesting to add it here so we can show it in the docs

**Comment by exekias** [comment]
We will also need to explain that this dashboard is for metrics collected from a Prometheus server

**Comment by sorantis** [comment]
@exekias , yes there's a screenshot in the related issue https://github.com/elastic/beats/issues/13120

**Comment by sorantis** [comment]
Accidentally merged this PR.

**Pull request merged**
