### PR TITLE
fix metricbeat docker run command error

### PR DESCRIPTION
**Pull request by jenhaoyang**
add missing strict.perms environment variable for metricbeat

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by jsoriano** [comment]
Hey @jenhaoyang,

This flag shouldn't be needed with default configuration. With what version and beat are you seeing it? How are you running the container?

**Comment by jenhaoyang** [comment]
I follow the tutorial for [Metricbeat](https://www.elastic.co/guide/en/beats/metricbeat/7.12/running-on-docker.html#_volume_mounted_configuration) (Metricbeat Reference [7.12]) and run the docker run command which give me the following error
```
Exiting: error loading config file: config file ("metricbeat.yml") must be owned by the user identifier (uid=0) or root
```
Then I saw the similar docker run command in [Filebeat ](https://www.elastic.co/guide/en/beats/filebeat/7.12/running-on-docker.html#_volume_mounted_configuration) (Filebeat Reference [7.12]).  This docker run command have enviornment variable ` -e  -strict.perms=false`. Everything run smooth with ` -e  -strict.perms=false` both with Metricbeat and Filebeat  so I add make this pull request to improve this document

**Comment by jsoriano** [comment]
> I follow the tutorial for [Metricbeat](https://www.elastic.co/guide/en/beats/metricbeat/7.12/running-on-docker.html#_volume_mounted_configuration) (Metricbeat Reference [7.12]) and run the docker run command which give me the following error
> 
> ```
> Exiting: error loading config file: config file ("metricbeat.yml") must be owned by the user identifier (uid=0) or root
> ```
> 
> Then I saw the similar docker run command in [Filebeat ](https://www.elastic.co/guide/en/beats/filebeat/7.12/running-on-docker.html#_volume_mounted_configuration) (Filebeat Reference [7.12]). This docker run command have enviornment variable ` -e -strict.perms=false`. Everything run smooth with ` -e -strict.perms=false` both with Metricbeat and Filebeat so I add make this pull request to improve this document

I guess that the source `metricbeat.yml` file is not owned by the root user in your case? I think that then the error message would be expected. The recommended solution would be to modify the ownership and permissions to the ones that metricbeat (or filebeat) expect. Perhaps we should modify the docs to mention the expectations for the mounted files.

The use of `--strict.perms=false` should be an active decision of the user, taking into account that this is less secure. I would prefer not making this the default recommendation.

**Comment by jlind23** [comment]
PR grooming - Closing this until further update.

**Pull request closed without merging**
