### PR TITLE
[WIP] Add for timestamps with nanoseconds precisio

### LINKED ISSUE #15871: Add support for nanosecond timestamps
The `@timestamp` field only has microsecond precisions. Internally, or when collecting from external sources, timestamps might have higher precisions. Elasticsearch supports the `date_nano` type, and allows to store timestamps with higher precision even if `date` is used.

The `feature-timestamp-nano` branch is used for development.
In progress PR merging the feature branch into master: https://github.com/elastic/beats/pull/15872

- [x] Support for parsing timestamp with different permissions. #9818     
- [x] Update dtfmt to support higher precision. #9818
  - [x] Add `n` formatter to always print nanoseconds. #9818     
  - [x] Allow `S` formatter to be used for higher precisions. #9818     
  - [x] Add `f` formatter. elastic/beats#15911 
- [x] Update unit tests. elastic/beats#9818 
- [x] Update integration tests. elastic/beats#16005 
- [x] Update system tests. #16005,
- [ ] Check timestamp parsing in individual beats/modules/inputs:
  - Can the input/module parse the timestamp with higher precision than is currently the case?
  - [ ] Metricbeat modules
  - [ ] Filebeat inputs
  - [ ] Filebeat modules
  - [ ] Heartbeat monitors
  - [ ] Auditbeat modules
  - [ ] Packetbeat
- [ ] Check whether we can change the template in a backwards compatible way.
  - Do we need to use `date_nano`, or can keep `date` for timestamps?
- [ ] Check Kibana works correctly with nano types (according to https://github.com/elastic/kibana/issues/31424 it works but we would need to do some testing):
  - [ ] do visualizations work without updates?
  - [ ] do visualizations/dashboards work when mixing data from indices with millisecond and microsecond precision.

Other related issues:
- [ ] Support log4j format for timestamps (comma-milliseconds) #17794
- [ ] filebeat docker-json timestamp support nanoseconds? #17660

### PR DESCRIPTION
**Pull request by urso**
- Enhancement

## What does this PR do?

Add support for parsing and serializing timestamps with microsecond and nanosecond precisions.

## Why is it important?

Some data sources have higher precisions than microseconds for it's events or logs. This will allow these events to be indexed in Elasticsearch using that higher precisions.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works

## How to test this PR locally

TODO

## Related issues

- Closes elastic/beats#15871

### CODE REVIEW

**Comment by TomGudman** [comment]
Hi @urso, do you think we could have this feature in elastic stack 8.0?

**Comment by urso** [comment]
It's still in progress. Fixing tests did open quite a can of worms. I hope we can finish way before 8.0 though :)

**Comment by pytimer** [comment]
@urso What's progress about this feature, what do i need to do?

**Comment by urso** [comment]
This is more or less a task of diligence and finding time to do so. Check the meta issue here: https://github.com/elastic/beats/issues/15871

First of all we need to make sure that all CI runs through. I already spend quite some time fixing/updating tests.

We also have to spend some time maybe manually testing various setup types and the update process to be sure that the switch to nanosecond does not break introduce breaking changes somewhere else.

**Comment by urso** [comment]
Update: still in progress

**Comment by TomGudman** [comment]
Yes we’d like to have it! Otherwise high frequency logs are all mixed up in Kibana because milliseconds are not enough. Thanks for your efforts

**Comment by JeanChristopheMorinRodeoFX** [comment]
Hi, I'm also waiting on this PR to eventually get merged! I was actually surprised that Filebeat wasn't supporting nanoseconds as they are supported in Elasticsearch since 7.0.

Anyway, I'm glad to see that there is some progress being made in this area of Filebeat!

**Comment by TomGudman** [comment]
Hi Jean-Christophe,


If you also use logstash you can also +1 this : https://github.com/elastic/logstash/issues/10822 because that is the next step 😉 Unless you ingest directly in ES via filebeat ingester.


One day, we'll get that feature and we will get our logs in the right order, it will be amazing! :-)

________________________________

**Comment by zamirka** [comment]
👍

**Comment by T0bl** [comment]
👍

**Pull request closed without merging**
