### PR TITLE
Added Link to timebeat

### PR DESCRIPTION
**Pull request by lasselj**
Added link to the free timebeat.app beat.

Timebeat Kibana Dashboard

### CODE REVIEW

**Comment by lasselj** [comment]
> ❌ Author of the following commits did not sign a [Contributor Agreement](https://www.elastic.co/contributor-agreement):
> [ebec2bb](https://github.com/elastic/beats/commit/ebec2bbe73725dac02e4e980cb46133a0466918d)
> 
> Please, read and sign the above mentioned agreement if you want to contribute to this project

This was done before Christmas.

**Comment by lasselj** [comment]
+1

**Review by jlind23 — APPROVED** [review]
LGTM again sorry @lasselj for the delay here.

**Pull request merged**
