### PR TITLE
Add custom JSON unmarshaller to logstash node_stats

### PR DESCRIPTION
**Pull request by fearful-symmetry**
## What does this PR do?
This is a revision/follow-up to  #32599

From the original PR: 

This fixes rather odd bug that would happen the logstash module we receive a large integer value, handle it as a float, and then re-encode the json event as an integer or a float depending on the number of digits in the resulting number. This resulted in some mapping errors as fields would sometimes be floats, and sometimes be integers when received by logstash on the other end of metricbeat.

## Why is it important?

By default, if you pass an `interface{}` value to the go JSON unmarshaller, it'll treat any number as a float.
On the other end, Beat's JSON marshaller has some logic such that `if typeof(value) == float && number_of_digits(value) > x; then format_as_scientific_notation()` so that that floats that are sufficiently large like `12345678.0` will become `"1.2345678e7"` or whatever, which is breaking something ES when it tries to read it as a `long` type specified by the mapping, which I assume wouldn't happen if the float was rendered as `"12345678.0"`

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Review by matschaffer — COMMENTED** [review]
This seems to work:

Screen Shot 2022-08-24 at 10 32 57

Screen Shot 2022-08-24 at 10 32 53

But should we maybe include (or doctor) one of the test json files to include something large like what we saw in the support case?

```
logstash_stats.pipelines.queue.capacity.queue_size_in_bytes: 1073741824
```

Or maybe a unit test for `LongEnforce`?

**Comment by fearful-symmetry** [comment]
@matschaffer / @klacabane if you could take a look at this, that would be great. Hoping this will be a less scary, and more conservative way of solving this.

**Comment by fearful-symmetry** [comment]
@matschaffer ah, thanks! Yah, was thinking of adding a few more tests here.

**Comment by matschaffer** [comment]
So @klacabane sent me this yesterday which seems to invalidate the theory behind this PR

```
{
  ".ds-foobar-baz-2022.08.24-000001": {
    "mappings": {
      "a-long-field": {
        "full_name": "a-long-field",
        "mapping": {
          "a-long-field": {
            "type": "long",
            "doc_values": false,
            "ignore_malformed": false,
            "coerce": true
          }
        }
      }
    }
  }
}

------
POST foobar-baz/_doc
{
  "@timestamp": 1661332556021,
  "a-long-field": 1.2345678e7
}
success
```

I'm thinking it might be best to try to reproduce the error more thoroughly before we merge this. I typically run logstash from source so I don't think it'd be difficult to inject `logstash_stats.pipelines.queue.capacity.queue_size_in_bytes: 1073741824`

@fearful-symmetry are you working on this as part of SDH coverage?

It might make sense to open this as a @elastic/infra-monitoring-ui issue and work on it as part of our backlog if getting it all fixed is distracting from other team work you have going on.

**Comment by matschaffer** [comment]
@klacabane I just noticed the `"coerce": true` on your field. Did you try without? If that fails maybe we can fix this with a mapping udpate to add coercion.

**Comment by klacabane** [comment]
It will succeed with `coerce: false`, however it will fail if we provide a float value but with a different error. The mappings have coerce enabled

```
{
  "error": {
    "root_cause": [
      {
        "type": "mapper_parsing_exception",
        "reason": "failed to parse field [a-long-field] of type [long] in document with id 'k6mU1IIBAD3favn8gyOM'. Preview of field's value: '1231.1'"
      }
    ],
    "type": "mapper_parsing_exception",
    "reason": "failed to parse field [a-long-field] of type [long] in document with id 'k6mU1IIBAD3favn8gyOM'. Preview of field's value: '1231.1'",
    "caused_by": {
      "type": "illegal_argument_exception",
      "reason": "1231.1 cannot be converted to Long without data loss"
    }
  },
  "status": 400
}
```

**Comment by fearful-symmetry** [comment]
> are you working on this as part of SDH coverage?

@matschaffer , yah, this is one of those times where I volunteered to look at the SDH and it ended up all the way at a PR, even though I'm not a logstash expert.

> I just noticed the "coerce": true on your field. Did you try without? If that fails maybe we can fix this with a mapping update to add coercion.

I....didn't even know that was a thing.

**Comment by fearful-symmetry** [comment]
> The mappings have coerce enabled

@klacabane Alright, this might be a learning moment for me. The mappings in `metricbeat/module/logstash/node_stats/_meta/fields.yml` don't define a `coerce` field, is that something set globally?

**Comment by matschaffer** [comment]
These are not the templates you're looking for...


The monitoring templates live over in https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/src/main/resources/monitoring-logstash-mb.json - weird I know, but we have large wheels turning to get out of that situation :)

**Comment by klacabane** [comment]
@matschaffer In the original SDH the issue happened on the `metricbeat-*` indice, the mappings defined in the metricbeat module would be the right place to look at. Now I'm wondering if there is a user requirement for publishing the metrics in metricbeat instead of the monitoring indices, and if not maybe turning `xpack.enabled: true` for the logstash collection would fix the issue ?

@fearful-symmetry Looks like `coerce` can be defined both [at the index or field level](https://www.elastic.co/guide/en/elasticsearch/reference/master/coerce.html), but it is enabled by default. I inspected the mappings through Kibana's Data management and coerce was indeed enabled for the offending fields.

**Comment by fearful-symmetry** [comment]
So, the actual error seen by the user is `[logstash_stats.pipelines.queue.capacity.queue_size_in_bytes] cannot be changed from type [float] to [long]` which looks different from the error than the one @klacabane reproduced with `coerce: off`, but that could just be a version/config issue. If this is actually fixed by `coerce`, I'm a tad lost.

However, there's also this issue linked in the SDH, which might be related: https://github.com/elastic/elasticsearch/issues/40409

**Comment by matschaffer** [comment]
Nice find @fearful-symmetry - I opened https://github.com/elastic/kibana/issues/139607 so we can take this over as part of our usual work to dig into the issue and figure out what the right ™️ fix is.

**Comment by miltonhultgren** [comment]
@fearful-symmetry This PR has been open for a long time, I'm looking to clean up our Github reminder bot and not sure what we should do here.

Do you have the time to bring this branch up to date, are these changes still valid/needed? Or should we close the PR?

**Comment by fearful-symmetry** [comment]
@miltonhultgren sorry bout that, this was my attempt at fixing an issue that was on another team's integration, and if I remember, the discussion moved to slack about other, simpler, ways to fix this, which is where it stalled. So I'm not sure if it's still needed.

**Pull request closed without merging**
