### PR TITLE
Fix metricbeat generator beat path

### LINKED ISSUE #3294: Wrong BEAT_PATH for metricbeat based community beats
See [discuss](https://discuss.elastic.co/t/make-package-broken-for-community-beats/70511) for background information. @ruflin advised to create an issue for it

DST_FOLDER is not correctly set in [build.sh](https://github.com/elastic/beats/blob/master/dev-tools/packer/docker/xgo-image/base/build.sh) when building a metricbeat based community beat.

"make package" fails as follows:

```
Working directory=/go/src/github.com
Copying main source folder /source to folder /go/src/github.com
Fetching dependencies...
Execute /scripts/before_build.sh github.com/someuser
/scripts/before_build.sh: 13: cd: can't cd to /go/src/github.com/someuser
make[1]: *** [prepare-package-cgo] Error 2
make: *** [package] Error 2
```

The issue seems to be that the argument passed to build.sh is the value of the BEAT_DIR variable in the generated Makefile that doesn't contain the beat name.

Extract from generated Makefile
```
BEATNAME=somebeat
BEAT_DIR=github.com/someuser
```

build.sh is extracting the directory name using the dirname command, thus removing the last part of the BEAT_DIR variable

Extract from build.sh

```
BEAT_PATH=$1
DST_FOLDER=`dirname $GOPATH/src/$BEAT_PATH`
GIT_REPO=$BEAT_PATH
```

In the example BEAT_PATH is "github.com/someuser", DST_FOLDER will be "/go/src/github.com". build.sh creates the DST_FOLDER (/go/src/github.com). Then [before_build.sh](https://github.com/elastic/beats/blob/master/dev-tools/packer/xgo-scripts/before_build.sh) is called with $BEAT_PATH (github.com/someuser) as argument and tries to change directory to /go/src/${1} (/go/src/github.com/someuser) and fails.

To workaround the issue I modified build.sh to:

```
BEAT_NAME=$PACK
BEAT_PATH=$1/$BEAT_NAME
DST_FOLDER=`dirname $GOPATH/src/$BEAT_PATH`
GIT_REPO=$BEAT_PATH
```

There are multiple ways in which this could be solved, I tried a few, but this is the only one I found that didn't have side-effects. Not sure if this is the correct way though.

I'll submit a PR with the changes described above.

Tested on 5b973a073a02ab3753a0b1e61c7947df48f656b0
OS: Ubuntu 14.04
Steps to reproduce:

```
$ cd $GOPATH/src/github.com/someuser
$ cookiecutter $GOPATH/src/github.com/elastic/beats/generate/metricbeat/metricset
project_name [Examplebeat]: somebeat
github_name [your-github-name]: someuser
beat [somebeat]: somebeat
beat_path [github.com/someuser]: github.com/someuser
full_name [Firstname Lastname]: Some User

$ cd somebeat/
$ make setup
$ make update
$ make package
```

### PR DESCRIPTION
**Pull request by ruflin**
This closes #3294

### CODE REVIEW

**Comment by fjgal** [comment]
Tested this PR by creating a metricbeat based community beat.

The generated Makefile, as expected, has the full path in BEAT_DIR

"""
BEATNAME=otherbeat
BEAT_DIR=github.com/someuser/otherbeat
"""

But this introduces a new issue, the generated include/list.go file has the wrong path in the imports (beat name included twice):

```
import (
	// This list is automatically generated by `make imports`
	_ "github.com/someuser/otherbeat/otherbeat/module/otherbeatmodule"
	_ "github.com/someuser/otherbeat/otherbeat/module/otherbeatmodule/otherbeatmetricset"
)
```

I tried modifying [metricbeat/scripts/generate_imports.py](https://github.com/elastic/beats/blob/master/metricbeat/scripts/generate_imports.py) by commenting out the special case for other beats (! metricbeat), so it doesn't append beat_name to the go_beat_path which already includes full path:

```
if __name__ == "__main__":
    # First argument is the beat path under GOPATH.
    # (e.g. github.com/elastic/beats/metricbeat)
    go_beat_path = sys.argv[1]
    beat_name = sys.argv[2]

    #if go_beat_path != "github.com/elastic/beats/metricbeat":
    #   go_beat_path += "/" + beat_name
```

After this change the generated include/list.go has the right paths in the imports and it solves the compilation issue. make package also works.

So it seems that modifying the Makefile template **and** generate_imports.py solves the issue. However, the change in generate_imports.py reverts a fairly recent commit 41d4983688181807a92063f6dbcef2d5b1fafe37, so I'm afraid this may break other things.

I'll try to update this PR with the change to generate_imports.py (not sure if I have permissions)

Note: I had to apply PR #3296 on top this PR in order to get the package to work.

**Comment by fjgal** [comment]
I don't have permission to push to this PR. Here is a patch containing the changes I had to make (as per previous comment):

```
diff --git a/metricbeat/Makefile b/metricbeat/Makefile
index f22642b..a1385ab 100644
--- a/metricbeat/Makefile
+++ b/metricbeat/Makefile
@@ -51,7 +51,7 @@ configs: python-env
 .PHONY: imports
 imports:
 	mkdir -p include
-	python ${ES_BEATS}/metricbeat/scripts/generate_imports.py ${BEAT_DIR} ${BEATNAME} > include/list.go
+	python ${ES_BEATS}/metricbeat/scripts/generate_imports.py ${BEAT_DIR} > include/list.go
 
 # This is called by the beats packer before building starts
 .PHONY: before-build
diff --git a/metricbeat/scripts/generate_imports.py b/metricbeat/scripts/generate_imports.py
index e1c9ee8..495a3c4 100644
--- a/metricbeat/scripts/generate_imports.py
+++ b/metricbeat/scripts/generate_imports.py
@@ -47,9 +47,5 @@ if __name__ == "__main__":
     # First argument is the beat path under GOPATH.
     # (e.g. github.com/elastic/beats/metricbeat)
     go_beat_path = sys.argv[1]
-    beat_name = sys.argv[2]
-
-    if go_beat_path != "github.com/elastic/beats/metricbeat":
-        go_beat_path += "/" + beat_name
 
     generate(go_beat_path)
```

The changes to metricbeat/Makefile are not required but are there for consistency.

Would be great if someone can push this and test to see if it breaks anything. Thanks!

**Comment by ruflin** [comment]
jenkins, package it

**Comment by ruflin** [comment]
@fjgal Thanks for testing, that is one that I missed :-( I applied to above changes to my PR. Can you test again?

This is actually a nice change as it already removes one of this ugly "if beats" clauses.

**Comment by ruflin** [comment]
Build looks good: http://build-eu-00.elastic.co/job/beats-package-PR/61/

**Comment by ruflin** [comment]
@fjgal The general change I want to make, is that also our beats have BEAT_PATH including BEAT_NAME as I think that is the "correct/expected" path in this variable. Unfortunately I didn't get to make this change yet as it involves lots of movable parts in the build process.

That would also mean `basename $BEAT_PATH == $BEAT_NAME`

**Comment by fjgal** [comment]
@ruflin I tested the fix with a beat based on metric beat and it works fine (after applying #3297 on top of it). Thanks a lot!

Yes, it would be great to have consistency on the meaning of BEAT_PATH across beats. I agree, that it seems to be the "correct/expected" path for the variable.

**Pull request merged**
