### PR TITLE
Update shared-directory-layout.asciidoc

### PR DESCRIPTION
**Pull request by dongcarl**

### CODE REVIEW

**Comment by dedemorton** [comment]
LGTM. Strange, but I remember seeing a fix for this awhile back ago. Must have gotten trumped by someone else's change.

**Comment by dongcarl** [comment]
I have to sign the CLA to make this PR?

**Comment by ruflin** [comment]
@dongcarl Thanks a lot for the fix. Our system requires a CLA on every PR. You can find it here: https://www.elastic.co/contributor-agreement

**Comment by ruflin** [comment]
@dongcarl Any update on the CLA? I also just realised you opened this against 6.1. Any chance you could open it against mater and we backport it?

**Comment by ruflin** [comment]
@dongcarl Do you mind if we take this over?

**Comment by dongcarl** [comment]
Please do.

**Comment by ruflin** [comment]
@dongcarl Thanks for your work. New PR opened here: https://github.com/elastic/beats/pull/6557

**Pull request closed without merging**
