### PR TITLE
buildkite: change github comments

### PR DESCRIPTION
**Pull request by v1v**
## Proposed commit message

- WHAT: Simplify the GitHub comment for running the Buildkite pipeline.
- WHY: This pipeline is not currently used, and it was created as a placeholder. This will help with https://github.com/elastic/beats/pull/38162 temporarily, then it could be changed again.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

I used https://regex101.com/ for verifying the regex:

image

## Related issues

-

### CODE REVIEW

**Comment by rowlandgeoff** [comment]
@alexsapran This older open PR looks very similar to your fix from https://github.com/elastic/beats/pull/38487

**Comment by v1v** [comment]
> @alexsapran This older open PR looks very similar to your fix from https://github.com/elastic/beats/pull/38487

Indeed, https://github.com/elastic/beats/pull/38487 might have some side effects while Jenkins is still the CI.

This PR was intended to leverage the existing proposal in https://github.com/elastic/beats/pull/38162 without running twice (builds in Jenkins and Buildkite) during the migration.

**Comment by v1v** [comment]
> What type of side effects you are thinking of? other than the fact that it will trigger both?

That's the only thing.

> It's something that I wanted to have, so I can test that both implementations are doing what we want them to do, this is how I discovered for example an issue with how we select some pipeline steps, by checking the Jenkins and Buildkite steps.

Then forget please what I said, I didn't have that context. Sorry for the noise 🙏

**Comment by v1v** [comment]
I'll close this now as duplicates the other one

**Pull request closed without merging**
