### PR TITLE
[Docs] Reformat exported fields documentation

### LINKED ISSUE #9519: Proposal to improve the layout of the field reference documentation for Beats
Currently the documentation about exported fields is not easy to read and scan due to problems with the layout. This proposal recommends improvements to the layout based on what I think should be done.

**Problems with the existing layout:**

- We use the same heading level for all headings, which makes the topic harder to scan and  understand the relationship between sections.
- Definition list formatting makes the content longer (by about 40%) and therefore harder to scan.
- Redundant sections are not useful and make it look like there is a mistake. The logic in our generator creates these sections because of the filesets/metricsets used to collectd the data, but the sections don't really add value for the user.

**Problems with the writing style/content:**

- Inconsistent style (some full sentences, some fragments, erratic capitalization)
- Many descriptions lack depth and completeness. Some descriptions are missing. Users can't always tell how the fields get populated (do they enable a module? an input? define a processor?)

**Proposal to address these issues:**

- Use a different heading level for sub-sections. Avoid introducing additional heading levels beyond the title and sub-headings.
- Format the field reference info using tables instead of definition lists. Each table should have no more than 3 cols. When additional information is available (such as format, alias to, and required), include this information in the description. _Why?_ Tables with more than 3 columns may result in formatting issues (text that overruns in the navigation) and are hard to read on smaller devices. Complex tables are also more difficult for people using screen readers.
- Edit the existing content for consistency and define style guidelines for new contributors to encourage consistency.
- Make sure the descriptions in each section indicate which modules/inputs/processors/etc populate the fields with data. This is useful for new users who aren't familiar with the available modules. If possible, there should be an active link back to the docs for the module that collects the data.

~A prototype of the layout is available here: https://field-reference-test.firebaseapp.com/index.html~ Commented out because I accidentally blew this away.

The asciidoc I used is here: https://github.com/dedemorton/beats-docs-review/pull/2/files

Note that links are missing in this small test case. I've put everything into a single file to make it easy to build. The table layout I've chosen is relatively simple and easy to read as raw text in GitHub.

**Some other stuff I played around with:**

- Added descriptions to the overview page. I think this is better than a bulleted list that simply repeats the navigation.
- Removed repetition of "fields" in sub-headings. Does this work?
- Capitalized all headings. 

**Layout problems caused by our CSS or asciidoc (not easy to fix):**

- Heading size and fonts do not play well together.
- Not enough cell padding between columns.
- No way to set the width of columns so that all tables on a page have the same column widths (this makes it easier to scan content quickly). Our docbook transform in our toolchain swallows column attributes. 

**Questions and open issues:**

- Can we extract the descriptions defined in the Elastic Common Schema? Users should not have to look in more than one place to figure out the content and data type of  a field.
- Can the script be modified to strip out redundant sections (sections that do not contain field descriptions)? Do these sections provide any real purpose, or are they just an artifact of how the current script logic works?
- Who will create the script?

### PR DESCRIPTION
**Pull request by dedemorton**
Closes #9519 

This PR changes the structure of collapses the structure of the exported field reference docs by removing sections that add little value. You can see the layout under https://metricbeatexample.firebaseapp.com/exported-fields.html

Note that I had to add `description` to  `heartbeat/_meta/fields.common.yml` because it was missing. We'll need area owners to verify that no other fields were dropped.

There's some real content that's stripped out with this change. We need to decide how to handle it. 

@ruflin Please check my logic. Also let me know if you have any thoughts on how we can simplify the structure without throwing away useful content.

**Update:** I've reverted back to the version that includes all the sections because important info was being stripped out. I've (hopefully) made the existing content easier to scan by fixing the heading levels and removing duplicated info.

### CODE REVIEW

**Comment by ruflin** [comment]
Good to see this kicked off. Now we also see what it means of content we miss. It's quite a bit more then I expected and in some case the content seems to be useful. I think we need a different strategy :-(

I keep thinking the table view like we have in ECS will make things better. And every time we have a description we put it on top of the following table?

**Comment by dedemorton** [comment]
@ruflin I was afraid you would say that. I monkeyed around with the script quite a bit and couldn't get my logic for building tables to work quite right...there were always a couple of modules with yml structures that resulted in end table tags in the wrong place. If you can help me think through the logic to get this working, I would be obliged.

**Comment by dedemorton** [comment]
I think I just figured out why my original attempt at creating tables was not working. Fixed a bug in the script for generating field reference: https://github.com/elastic/beats/pull/12432

I'll take another crack at this after I get all the books building in asciidoctor.

**Comment by dedemorton** [comment]
I've been playing around with this a bit more, and I'm not loving the way the long names look in the table format. Our page layout is not optimized for displaying tables, plus we can't currently control column widths because docbook does not preserve table attributes. ECS doesn't have this problem because we control the names. 

image

**Comment by ruflin** [comment]
What if we do some tricks with tables and having 2 rows per entry. First entry with the field name and then below 2-3 columns with all the other things? I wonder if with this we could make it nicer?

**Comment by dedemorton** [comment]
>  I wonder if with this we could make it nicer

I'll come up with a few variations and put them up on firebase. I think you might find that complex tables are less readable than lists when rendered using our current site template. :-/ We also need to consider how these tables look when viewed on mobile devices.

**Comment by dedemorton** [comment]
Here's an example that illustrates why tables with long, non-breaking content do not display well with our current doc tool chain:

image

**Comment by dedemorton** [comment]
@ruflin I've done several iterations of table formats, and none of them works well with the long names that we use in some modules (see example above). I recommend that we avoid formatting this content in tables. Several reasons:

* The logic to generate the tables is more complex and will break more easily
* Special characters (like `[` and `|`) break the table format and need to be fixed in the source yaml files. This fails silently, which means that the table format can break without us realizing it.
* The benefits of using a table (compressed content that's easy to scan) are mostly lost when we create lopsided tables (big wide left col for very long fully-qualified names).

I'm going to propose a different approach. I've cleaned up the script a bit to add nested section levels and remove repeated content. That way, we don't lose content by removing sections (as we did with my first commit), but the content is a bit easier to scan because it doesn't have so much repeated info and the heading levels are properly nested. 

I recommend that we also add content to descriptions that are missing content.

<screen capture coming soon....>

**Comment by ruflin** [comment]
@dedemorton Thanks for the interations. I wonder if we should skip group fields if they don't have a description?

An other option could be that we go for a more compact bullet list like we have here: https://www.elastic.co/guide/en/beats/metricbeat/current/metricbeat-metricset-mssql-performance.html And the type we just mark in brackets in the end (type: keyword).

**Comment by dedemorton** [comment]
@ruflin and I met to discuss our plans going forward. We decided to merge this PR because it's better than what we have now and requires no additional changes to the yaml files.

I've opened https://github.com/elastic/beats/issues/12523 to track the next phase of work that's required. Our end goal is to someday format this content in tables for easy scanning and retrievability, but we need to wait for updates to our doc site design to enable this.

**Comment by ruflin** [comment]
Change LGTM. So basically it fixes the heading, removes `fields` from the sub titles and moves type to the bottom.

@dedemorton Could you rebase this on master and run make update to get the build green?

**Comment by mikemadden42** [comment]
jenkins retest this please

**Comment by ycombinator** [comment]
Sorry @dedemorton, I just merged https://github.com/elastic/beats/pull/12621, so this one will need the rebase.

**Comment by dedemorton** [comment]
I cannot get the CI on this PR to pass. Should I try creating a new branch that has only the new commits? I have no idea what to do to fix this.

**Comment by dedemorton** [comment]
merging since the docs build is now GREEN! thanks @ycombinator!

**Comment by dedemorton** [comment]
Let's consider this to be a 7.2 enhancement to the docs. Not planning to backport to 7.1 and earlier unless there's a big desire.

**Pull request merged**
