### PR TITLE
[DOCS] Add openvpnbeat in community docs

### PR DESCRIPTION
**Pull request by nabeel-shakeel**
## What does this PR do?

Added a link to openvpnbeat beat developed by me in community docs.

### CODE REVIEW

**Comment by nabeel-shakeel** [comment]
Not allowing to add label in PR ? Any idea how to do that

**Comment by bmorelli25** [comment]
jenkins test this please

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by bmorelli25** [comment]
Hi @nabeel-shakeel, thanks for the contribution! I've kicked off the tests -- once they pass, I'll get this merged for you.

**Review by bmorelli25 — APPROVED** [review]

**Comment by bmorelli25** [comment]
Failing tests are unrelated

**Comment by bmorelli25** [comment]
Failing tests are unrelated, but I can't merge without all tests passing. @nabeel-shakeel would you be able to merge upstream/master with your PR so we can rerun? Tests look to have been fixed in a recent commit.

**Comment by nabeel-shakeel** [comment]
@bmorelli25 : Sure will merge master with my PR

**Comment by nabeel-shakeel** [comment]
@bmorelli25  Done

**Comment by bmorelli25** [comment]
And we're green! Thanks for doing that. Merging now.

**Comment by bmorelli25** [comment]
FYI: It takes a couple of hours for changes to propagate to the website.

**Pull request merged**
