### PR TITLE
[Ingest Management] Push log level downstream

### PR DESCRIPTION
**Pull request by michalpristas**
## What does this PR do?

This PR injects log level settings into fleet section of config as discussed in linked issue. 
resulting config will look like this
```
fleet:
  agent:
    id: {agent_id}
    logging:
      level: warning
  api:
    access_api_key: {agent_api_key}
    kibana:
      host: {host_uri}:443
      hosts:
      - {host_uri}
      protocol: https
      timeout: 5m0s
  host:
    id: {host_id}
inputs:
- artifact_manifest:
    artifacts:
      endpoint-exceptionlist-macos-v1:
...so on
```

## Why is it important?

#20756

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

cc @ph @ferullo

### CODE REVIEW

**Review by blakerouse — APPROVED** [review]
Looks good.

**Comment by ph** [comment]
Should we have tests for this?

**Comment by ph** [comment]
@EricDavisX @rahulgupta-qasource This should be available soon see linked issues for endpoint support.

**Comment by michalpristas** [comment]
Mac doc
```json
{
  "_index": ".ds-metrics-elastic_agent.elastic_agent-default-000001",
  "_id": "cxpMKHYBn_NsX8oVHzZA",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2020-12-03T11:10:45.039Z",
    "event": {
      "dataset": "elastic_agent.elastic_agent",
      "module": "system",
      "duration": 32733063
    },
    "metricset": {
      "name": "process",
      "period": 10000
    },
    "host": {
      "name": "Michals-MacBook-Pro-2.local",
      "mac": [
        "ab:cd:ab:cd:ab:cd",
      ],
      "hostname": "Michals-MacBook-Pro-2.local",
      "architecture": "x86_64",
      "os": {
        "family": "darwin",
        "name": "Mac OS X",
        "kernel": "18.7.0",
        "build": "18G6032",
        "platform": "darwin",
        "version": "10.14.6"
      },
      "id": "FC609F24-07E1-54EA-8E33-56F9D5A7A97E",
      "ip": [
        "fe80::e7:12ae:ee12:a1a2",
        "192.168.0.1",
      ]
    },
    "user": {
      "name": "root"
    },
    "service": {
      "type": "system"
    },
    "system": {
      "process": {
        "memory": {
          "size": 5263314944,
          "rss": {
            "bytes": 33759232,
            "pct": 0.002
          },
          "share": 0
        },
        "cpu": {
          "total": {
            "value": 7370,
            "pct": 0.0035,
            "norm": {
              "pct": 0.0004
            }
          }
        },
        "state": "running",
        "cmdline": "/Library/Elastic/Agent/elastic-agent"
      }
    },
    "process": {
      "executable": "/Library/Elastic/Agent/elastic-agent",
      "args": [
        "/Library/Elastic/Agent/elastic-agent"
      ],
      "name": "elastic-agent",
      "pid": 54683,
      "ppid": 1,
      "pgid": 54683,
      "command_line": "/Library/Elastic/Agent/elastic-agent"
    },
    "data_stream": {
      "type": "metrics",
      "dataset": "elastic_agent.elastic_agent",
      "namespace": "default"
    },
    "elastic_agent": {
      "version": "8.0.0",
      "id": "05267c3b-1a71-43f3-ab86-b2e89579fb86",
      "snapshot": false
    },
    "ecs": {
      "version": "1.6.0"
    },
    "agent": {
      "type": "metricbeat",
      "version": "8.0.0",
      "ephemeral_id": "a37dae92-8155-4075-b558-525829319c3f",
      "id": "0128aa34-eda1-4674-8ecb-663b1c1df52e",
      "name": "Michals-MacBook-Pro-2.local"
    }
  },
  "fields": {
    "@timestamp": [
      "2020-12-03T11:10:45.039Z"
    ]
  },
  "sort": [
    1606993845039
  ]
}
```

Linux one:
```json

{
  "_index": ".ds-metrics-elastic_agent.elastic_agent-default-000001",
  "_id": "ppheKHYBK5zocPioLtgX",
  "_version": 1,
  "_score": null,
  "_source": {
    "@timestamp": "2020-12-03T11:30:28.588Z",
    "process": {
      "pgid": 28358,
      "command_line": "/opt/Elastic/Agent/elastic-agent",
      "working_directory": "/opt/Elastic/Agent",
      "executable": "/opt/Elastic/Agent/data/elastic-agent-725dd5/elastic-agent",
      "args": [
        "/opt/Elastic/Agent/elastic-agent"
      ],
      "name": "elastic-agent",
      "pid": 28358,
      "ppid": 1
    },
    "user": {
      "name": "root"
    },
    "data_stream": {
      "type": "metrics",
      "dataset": "elastic_agent.elastic_agent",
      "namespace": "default"
    },
    "elastic_agent": {
      "snapshot": false,
      "version": "8.0.0",
      "id": "8292606e-4988-4d31-b773-ea561a777d5b"
    },
    "agent": {
      "id": "96e65eaa-05ea-4038-bec0-f6e4b11412ec",
      "name": "vagrant",
      "type": "metricbeat",
      "version": "8.0.0",
      "ephemeral_id": "bcb22e06-7bc8-4803-8676-3617201149ac"
    },
    "metricset": {
      "name": "process",
      "period": 10000
    },
    "service": {
      "type": "system"
    },
    "system": {
      "process": {
        "cgroup": {
          "path": "/system.slice/elastic-agent.service",
          "cpu": {
            "id": "elastic-agent.service",
            "path": "/system.slice/elastic-agent.service",
            "cfs": {
              "period": {
                "us": 100000
              },
              "quota": {
                "us": 0
              },
              "shares": 1024
            },
            "rt": {
              "period": {
                "us": 0
              },
              "runtime": {
                "us": 0
              }
            },
            "stats": {
              "periods": 0,
              "throttled": {
                "ns": 0,
                "periods": 0
              }
            }
          },
          "cpuacct": {
            "path": "/system.slice/elastic-agent.service",
            "total": {
              "ns": 14699109710
            },
            "stats": {
              "system": {
                "ns": 5820000000
              },
              "user": {
                "ns": 7900000000
              }
            },
            "percpu": {
              "1": 4369349590,
              "2": 2528918420,
              "3": 2753279002,
              "4": 5047574875
            },
            "id": "elastic-agent.service"
          },
          "memory": {
            "memsw": {
              "limit": {
                "bytes": 0
              },
              "usage": {
                "bytes": 0,
                "max": {
                  "bytes": 0
                }
              },
              "failures": 0
            },
            "kmem": {
              "limit": {
                "bytes": 9223372036854772000
              },
              "usage": {
                "bytes": 0,
                "max": {
                  "bytes": 0
                }
              },
              "failures": 0
            },
            "kmem_tcp": {
              "failures": 0,
              "limit": {
                "bytes": 9223372036854772000
              },
              "usage": {
                "bytes": 0,
                "max": {
                  "bytes": 0
                }
              }
            },
            "stats": {
              "pages_out": 5005,
              "hierarchical_memory_limit": {
                "bytes": 9223372036854772000
              },
              "inactive_anon": {
                "bytes": 0
              },
              "rss_huge": {
                "bytes": 134217728
              },
              "mapped_file": {
                "bytes": 120369152
              },
              "active_anon": {
                "bytes": 193740800
              },
              "active_file": {
                "bytes": 240467968
              },
              "cache": {
                "bytes": 275685376
              },
              "inactive_file": {
                "bytes": 35217408
              },
              "pages_in": 74138,
              "swap": {
                "bytes": 0
              },
              "rss": {
                "bytes": 193765376
              },
              "page_faults": 12836,
              "major_page_faults": 0,
              "unevictable": {
                "bytes": 0
              },
              "hierarchical_memsw_limit": {
                "bytes": 0
              }
            },
            "id": "elastic-agent.service",
            "path": "/system.slice/elastic-agent.service",
            "mem": {
              "usage": {
                "bytes": 469716992,
                "max": {
                  "bytes": 469716992
                }
              },
              "failures": 0,
              "limit": {
                "bytes": 9223372036854772000
              }
            }
          },
          "blkio": {
            "id": "elastic-agent.service",
            "path": "/system.slice/elastic-agent.service",
            "total": {
              "bytes": 549093376,
              "ios": 2746
            }
          },
          "id": "elastic-agent.service"
        },
        "cmdline": "/opt/Elastic/Agent/elastic-agent",
        "cpu": {
          "total": {
            "value": 7920,
            "pct": 0.006,
            "norm": {
              "pct": 0.0015
            }
          }
        },
        "fd": {
          "limit": {
            "soft": 1024,
            "hard": 4096
          },
          "open": 18
        },
        "memory": {
          "size": 1353097216,
          "rss": {
            "bytes": 43999232,
            "pct": 0.007
          },
          "share": 27164672
        },
        "state": "sleeping"
      }
    },
    "event": {
      "dataset": "elastic_agent.elastic_agent",
      "module": "system",
      "duration": 48434335
    },
    "ecs": {
      "version": "1.6.0"
    },
    "host": {
      "mac": [
        "12:34:ab:12:34:ab",
      ],
      "hostname": "vagrant",
      "architecture": "x86_64",
      "os": {
        "name": "Ubuntu",
        "kernel": "4.4.0-31-generic",
        "codename": "xenial",
        "platform": "ubuntu",
        "version": "16.04.1 LTS (Xenial Xerus)",
        "family": "debian"
      },
      "id": "c0cc2a7efa902a719ada8ab6584b6bcb",
      "name": "vagrant",
      "containerized": false,
      "ip": [
        "192.168.0.1",
        "fe80::e7:12ae:ee12:a1a2",
      ]
    }
  },
  "fields": {
    "@timestamp": [
      "2020-12-03T11:30:28.588Z"
    ]
  },
  "sort": [
    1606995028588
  ]
}
```

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have created 03 testcases for this ticket and linked ticket [#20756](https://github.com/elastic/beats/issues/20756) . testcases links are as follows:
https://elastic.testrail.io/index.php?/cases/edit/35174
https://elastic.testrail.io/index.php?/cases/view/35175
https://elastic.testrail.io/index.php?/cases/view/35176

However, we have 01 query at information provided on point below at [#8105](https://github.com/elastic/endpoint-dev/issues/8105)
`Move all of the existing Endpoint logging config from policy.<os>.logging to policy.<os>.advanced.logging. Keep in mind updating Binaries/Endpoint/production_config.yaml`

Could you please confirm where we could locate this file and verify the same.

**Comment by EricDavisX** [comment]
@dikshachauhan-qasource I believe... you shouldn't see a difference there, it was an internal refactor to make the logging come out right.  If the Endpoint logs show up, and have policy items displayed - then it is working.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX

We have validated this ticket on 8.0.0 snapshot cloud environment as per code commit in https://github.com/elastic/kibana/commit/62e79eec7011cb8ffa6f1c9626f4f989656ddad1 and found that **code for same is not merged**. Below are the build details:
```
BUILD 38666
COMMIT 62e79eec7011cb8ffa6f1c9626f4f989656ddad1
Artifact link: https://artifacts-api.elastic.co/v1/search/8.0.0-SNAPSHOT/
```
image

Steps to reproduce:
- Installed agent using default policy
- Verified agent logs were generated successfully and logging level is 'info' by default on agent details page
- Navigated to 'Default policy'. Go to Actions>View policy

Observation: logging level is not displayed under fleet section of default policy. Screenshot:
#22815_Codenotmerged

**Comment by EricDavisX** [comment]
@dikshachauhan-qasource Hi.  I think the commit yesterday morning missed the Tuesday build, and the Wednesday build isn't 'done' yet by the time you were testing.  So, let us re-test tomorrow.  I wish we had a better mechanism for tracking check-ins to when they are available in SNAPSHOT builds.  I don't know of one better than tracing in git and correlating against the Jenkins jobs for the build for the branch in question, tho we can always do that.  

The good news is that for many tests, we can use the Observability generated artifacts.  I think @rahulgupta-qasource knows of those, so please follow up with him.  I will confirm in our sync tomorrow too.

Final comment... I don't expect the Agent policy that the Agent is assigned to would show the log-level change.  I'll ask @michalpristas to help confirm, please.  I think we should lay out some AC for the expectation here in terms of precedence:
 - what happens when the Agent log level is set manually with this new feature, and then the policy is re-applied... does the level get re-set by the policy application?  Or is the level not part of policy and so it is left alone?

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX

We have updated our testcases as per discussion on the expected behaviour of [this](https://github.com/elastic/beats/pull/22815) pr.

Testcases link is as follows:
- [C35176](https://elastic.testrail.io/index.php?/cases/view/35176)
- [C35174](https://elastic.testrail.io/index.php?/cases/view/35174)

Also, created 02 testcases. Link is as follows:
- [C35264](https://elastic.testrail.io/index.php?/cases/view/35264)
- [C35265](https://elastic.testrail.io/index.php?/cases/view/35265)

Please let us know if anything else is required to be covered.

**Comment by dikshachauhan-qasource** [comment]
Hi @EricDavisX 

We have executed **05** testcases under test plan [Push log level downstream Test Run](https://elastic.testrail.io/index.php?/runs/view/919) 

Build details are as follows:
```
BUILD 37399
COMMIT f3abc08ac648f8b302733c5c22a39048314a027c
Artifact link: https://staging.elastic.co/7.11.0-710164a0/downloads/beats/elastic-agent/elastic-agent-7.11.0-windows-x86_64.zip
```

Please let us know if anything is required from our side.

Thanks
QAS

**Pull request merged**
