### PR TITLE
ci: retry release manager if it failed

### PR DESCRIPTION
**Pull request by v1v**
## What does this PR do?

Retry `release-manager` integration for the DRA if it failed

## Why is it important?

Temporarily workaround the existing issue with the release manager when running and returns:

```
Cannot invoke "String.length()" because "value" is null
```

This will run up to `3 times` regardless of the failure with some `sleep * factor`, see https://github.com/elastic/apm-pipeline-library/blob/main/vars/retryWithSleep.txt

Caveat, if there are some other errors then it will try again... I didn't want to get a complex algorithm so it could detect when to run based on the error in the logs since Jenkins is gonna be decommissioned in the future.

### CODE REVIEW

**Comment by v1v** [comment]
run elasticsearch-ci/docs

**Review by amannocci — APPROVED** [review]

**Review by jlind23 — APPROVED** [review]

**Comment by kingherc** [comment]
We're still seeing many failures like this. E.g., [here](https://gradle-enterprise.elastic.co/s/5w5cng426zc4c) and [here](https://gradle-enterprise.elastic.co/s/3xcrfzjbjjgug). Is there ongoing work for this and a ticket for @v1v ?

**Comment by v1v** [comment]
@kingherc ,worth to contact the release team who own the DRA process. In this PR I just added an automated retry for the release manager.

**Comment by v1v** [comment]
There is an open issue linked in this PR but it's in a private repository and hence only shown for Elasticians. Look for `[ALERT] Vault GCP error for Service Account used by Release Manager`

**Pull request merged**
