### PR TITLE
Add Command Line to Process Data Reported by Topbeat

### PR DESCRIPTION
**Pull request by andrewkroh**
Depends on elastic/gosigar#11. Basically this PR resurrects the work from elastic/topbeat#63.

### CODE REVIEW

**Comment by ruflin** [comment]
LGTM. I suggest to squash the commits before merging.

**Comment by andrewkroh** [comment]
I squashed my commits.

**Comment by monicasarbu** [comment]
Great work!

**Comment by monicasarbu** [comment]
waiting for the tests to finish

**Comment by andrewkroh** [comment]
@monicasarbu  Thanks. I really only made a few tweaks to the work you had done.

**Comment by biswajit86** [comment]
How do I report any bugs.

First of all this feature works great for parent processes. i am able to see all command line options in the output

However, I am unable to see command line options for `child` proceses. Some of our ancient perl scripts use ForkManager to fork child processes. In such cases, I do not see any value populated in command line options

**Comment by andrewkroh** [comment]
Please start a discussion at https://discuss.elastic.co/c/beats/topbeat.

**Comment by biswajit86** [comment]
[done](https://discuss.elastic.co/t/bug-for-pr-749/39921)

**Pull request merged**
