### PR TITLE
[Ingest-Manager] Fix windows installer during enroll

### LINKED ISSUE #24317: [Windows specific]: Metricbeat service is not started by itself and unable to unzip completely at Endpoint under Elastic folder.
**Kibana version:** 7.12 BC3 Kibana Cloud environment 

**Host OS and Browser version:** Windows 10, All

**Preconditions**
1.  7.12 BC3 Kibana Cloud environment should be available.
```
Build: 39134
Commit: 08417cbd6c15e4c866651a7dcdfeded58845206d
Artifact link: https://staging.elastic.co/7.12.0-96914cb5/downloads/beats/elastic-agent/elastic-agent-7.12.0-windows-x86_64.zip
```
2. Default policy having system integration should exist.

**Steps to reproduce:**
1. Login to Kibana cloud environment.
2. Install a new agent using Default policy.
3. Wait for agent logs to come up.
4. Observe an error logs for metricbeat are generated in Agent Tab.

Logs on Ui:
```
19:11:03.357
elastic_agent
[elastic_agent][error] Elastic Agent status changed to: 'error'
19:11:03.357
elastic_agent
[elastic_agent][error] 2021-03-03T08:41:02-05:00: type: 'ERROR': sub_type: 'FAILED' message: Application: metricbeat--7.12.0--36643631373035623733363936343635[bda121a0-7c25-11eb-8585-5b9f507c66c5]: State changed to CRASHED: exited with code: 1
```

Actual Result:
Metricbeat service is not started by itself and unable to unzip completely at Endpoint under Elastic folder.

**Screenshots:** 
image

Expected result:
All binaries like Filebeat nad metricbeat should be in running state.

### PR DESCRIPTION
**Pull request by michalpristas**
## What does this PR do?

after #24253 issue still occurred on some systems.
the problem really is with rename and sync after unzip which is skipped in case ctx is cancelled.  
my first option was to make agent rename rootDir even if zip is not fully unpacked and sync directories all rootDir, installDir and temp directories.
this complicated code to the form I did not like, so many conditions there. but it was working 5/5

i went with a code-cleaner way _(especially with change in mind @blakerouse suggested that we should remove it before start)_ and i let unzip finish, rename rootDir to correct tmp install path, sync paths and then let awaitable installer wait for whole installation to finish. we lose tiny amount of time, but cleaner code is worth small perf impact especially in this edge case scenario.

## Why is it important?

Fixes #24317

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Review by blakerouse — COMMENTED** [review]
How does this force the re-extract everytime? I would have expected the extract operation to change the `Check` function.

**Comment by michalpristas** [comment]
@blakerouse sorry for the confusion this is not forcing that just yet. this just lets unzip finish and waits for it before shutdown. the behavior is very weird. 

i want to do forced reextraction but this will be not that trivial as we need to check if there's some application already running/strarting (other checks i did not think of) before removing it.

**Review by blakerouse — APPROVED** [review]
True we do not need handle the case where it is already running. Maybe we should do an extraction per application (instead of per application type). Basically we run 2 filebeats, we can extract filebeat twice into 2 different directories.

Otherwise this change looks okay. PR description through me off, maybe that should be updated just for reference in the future.

**Comment by amolnater-qasource** [comment]
Hi @EricDavisX 

We have performed smoke test using windows OS on 7.12.0 Snapshot Kibana cloud environment. Build Details are as follows:
```
    Artifact link used: https://snapshots.elastic.co/7.12.0-07994102/downloads/beats/elastic-agent/elastic-agent-7.12.0-SNAPSHOT-windows-x86_64.zip
    Build: 39220
    Commit: 10e035085b6ab636765b76500803c9db19492c8b
```

**Testrun Link:** [Ingest Manager 7.12.0 Snapshot Smoke Test Plan](https://elastic.testrail.io/index.php?/runs/view/1369&group_by=cases:section_id&group_order=asc)

Thanks
QAS

**Pull request merged**
