### PR TITLE
additions to metricbeats memcached-module

### PR DESCRIPTION
**Pull request by Hooddominator**
added metrics to determ free/used bytes of memory of memcached-instance to metricbeats memcached-module

### CODE REVIEW

**Comment by ruflin** [comment]
Thanks for opening a PR with this. Could you run locally `make fmt` and `make update`. This should update all the generated files with the changes.

**Comment by jsoriano** [comment]
@Hooddominator Thanks for this PR, please ping us if you need help to finish it.
As the changes look good, in the meantime I have created a new PR with this branch updated with master and with the little missing pieces so we can merge them in any case :slightly_smiling_face:

**Comment by jsoriano** [comment]
We have finally merged these changes in #7740, thanks for working on this!

**Comment by Hooddominator** [comment]
thanks

**Pull request closed without merging**
