### PR TITLE
Update Makefile add python-env to fields

### PR DESCRIPTION
**Pull request by rzmf**
else "make collect" fails on clean build

### CODE REVIEW

**Comment by kvch** [comment]
Do you mind signing the CLA? https://www.elastic.co/contributor-agreement

**Comment by ruflin** [comment]
@rzmf Could you sign the CLA so we could move this forward?

**Comment by rzmf** [comment]
Alread signed last thursday, thought that would be resolved automatically

**Comment by ruflin** [comment]
@rzmf It rechecks it after an additional comment, which now happened. Thanks :-)

**Comment by ruflin** [comment]
jenkins, test it

**Comment by ruflin** [comment]
@rzmf Thanks for the contribution.

**Pull request merged**
