### PR TITLE
Change docker image from CentOS 7 to Ubuntu 20.04

### LINKED ISSUE #29255: Change the base docker image to ubuntu 20.04 for Beats & Elastic Agent
**Describe the enhancement:**

Beats and Agent to be aligned with other Elastic products and change the default image to ubuntu 20.04

**Describe a specific use case for the enhancement or feature:**

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Change the docker image from CentOS 7 to Ubuntu 20.04.

Note: Takes over from where pull #29374 left off. 

## Why is it important?

Closes #29255

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #29255

### CODE REVIEW

**Review by jlind23 — APPROVED** [review]
LGTM

**Comment by andrewvc** [comment]
@blakerouse can you let us know when we can help test out synthetics / browsers to make sure they still work?

**Comment by blakerouse** [comment]
@andrewvc This is ready for some testing. Did you want to test before merge?

**Review by jsoriano — COMMENTED** [review]
:+1: 

Only failing E2E tests are related to autodiscover, I don't think they are related, but it'd be good to double-check, @elastic/cloudnative-monitoring-squad could you please take a look?

**Comment by ChrsMark** [comment]
Seeing that `unable to upgrade connection: container not found (\"elastic-agent\")` tells me that `elastic-agent` container/pod is not started properly and most probably fails on startup. I had hit this in the past but it then disappeared. We cannot say for sure if we don't have a actual logs of the failing container/pod.

**Comment by andrewvc** [comment]
@blakerouse yes, I'd love to test these out before merge.

**Comment by andrewvc** [comment]
I spent some time with this today and the deps aren't quite right. I think I fixed the deps, but the `elastic-synthetics` CLI (which is used by heartbeat) just hangs when run. I suspect there's some further compat issue. I've opened https://github.com/blakerouse/beats/pull/1/files which improves the situation somewhat, but more exploration is needed on our end. 

I'll find someone on our team who can dedicate some time to figuring out what's hanging here and testing it thoroughly.

**Comment by andrewvc** [comment]
I'll mention that merging in my PR (which is targetting this PR's branch, in your repo @blakerouse ) is probably a good incremental step, no reason to delay that for a full fix.

**Comment by andrewvc** [comment]
FYI @lucasfcosta is taking on the next step of fixing this for synthetics, which is determining why, even with the added deps, synthetics is now hanging

**Comment by blakerouse** [comment]
Okay going to merge. The e2e failure is due to ansible issue, checked with the robots team.

**Comment by andrewvc** [comment]
I just want to note that with this change synthetics now is broken in 8.0.0 and we should consider this a blocker

**Pull request merged**
