### PR TITLE
beats: import time/tzdata explicitly in main

### PR DESCRIPTION
**Pull request by mauri870**
## Proposed commit message

In order to handle timezones we import Go's own timezone database. This
import is done indirectly by libbeat/common/cfgtype. We trust that this
package will end up being required by the dependency chain of every beats
main binary.

To ensure that the binaries continue to handle timezones correctly even if the
indirect import is removed let's import time/tzdata explicitly in the main packages.

See discussion at https://github.com/elastic/beats/pull/40326.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ] All main packages expected to handle timezones should import time/tzdata.

## Related issues

- Relates #31329

### CODE REVIEW

**Review by taylor-swanson — APPROVED** [review]

**Comment by pierrehilbert** [comment]
run docs-build

**Review by nfritts — APPROVED** [review]

**Review by belimawr — APPROVED** [review]

**Comment by pierrehilbert** [comment]
run docs-build

**Comment by pierrehilbert** [comment]
@graphaelli could you please find someone to review here as @bturquet is currently out?

**Review by axw — APPROVED** [review]

**Pull request merged**
