### PR TITLE
Update packetbeat-options.asciidoc

### PR DESCRIPTION
**Pull request by tinker-li**
I can't find the third type. So I think it should be "two types".

### CODE REVIEW

**Comment by urso** [comment]
Sorry, I can't merge this. I just noticed that your fix targets the 7.2 branch. Can you open your PR against the master branch please?

**Comment by andrewkroh** [comment]
@tinker-li You might be able to simply hit `Edit` at the top of this page and switch the target branch to master.

**Comment by tinker-li** [comment]
OK! I will create a new one.

**Comment by tinker-li** [comment]
> @tinker-li You might be able to simply hit `Edit` at the top of this page and switch the target branch to master.

I think this made a little trouble in #12961 .
I found this issue in v7.2. Just fix it in elastic:7.2.

**Comment by ph** [comment]
duplicate of #13067, (I will forward port it)

**Pull request closed without merging**
