### PR TITLE
[input/awscloudwatch] Set startTime to 0 for the first iteration of retrieving log events from CloudWatch

### PR DESCRIPTION
**Pull request by tetianakravchenko**
## Proposed commit message

- WHAT: Set `startTime` to `0` for the first iteration when retrieving log events from CloudWatch
- WHY:  to fix error:
```
InvalidParameterException: 1 validation error detected: Value '-6795364578871' at 'startTime' failed to satisfy constraint: Member must have value greater than or equal to 0"
```
as mentioned in https://docs.aws.amazon.com/AmazonCloudWatchLogs/latest/APIReference/API_StartQuery.html#API_StartQuery_RequestSyntax:
```
startTime
    The beginning of the time range to query. The range is inclusive, so the specified start time is included in the query. Specified as epoch time, the number of seconds since January 1, 1970, 00:00:00 UTC.
    Type: Long
    Valid Range: Minimum value of 0.
    Required: Yes
```
and in https://pkg.go.dev/github.com/aws/aws-sdk-go-v2/service/cloudwatchlogs#FilterLogEventsInput:
```
// The start of the time range, expressed as the number of milliseconds after Jan
// 1, 1970 00:00:00 UTC . Events with a timestamp before this time are not returned.
StartTime *[int64](https://pkg.go.dev/builtin#int64)
```
invalid value cause missed log event for the first iteration.

Changes in PR align with our documentation - https://www.elastic.co/guide/en/beats/filebeat/current/filebeat-input-aws-cloudwatch.html#_start_position

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by kaiyan-sheng — COMMENTED** [review]
Good catch, thank you! Could you add some unit tests please?

**Comment by tetianakravchenko** [comment]
@kaiyan-sheng I've added https://github.com/elastic/beats/pull/40079/commits/ef7e11cb404de8e59c87a1a580c2c6afdf89f0b4, please have a look

**Review by kaiyan-sheng — APPROVED** [review]

**Review by gizas — APPROVED** [review]

**Comment by smartkathycat** [comment]
@kaiyan-sheng My user hit this bug on version 8.14.  I see the fix is back ported to 8.14.x. May I confirm if the latest v8.14.3 has this fix? Thank you.

**Comment by kaiyan-sheng** [comment]
Hi @smartkathycat Unfortunately I dont think this bug fix got into 8.14.3. Here is the changelog I see: https://www.elastic.co/guide/en/beats/libbeat/8.14/release-notes-8.14.3.html
This bug will be fixed for 8.15.

**Pull request merged**
