### PR TITLE
Added browserbeat to the community beats documentation page.

### PR DESCRIPTION
**Pull request by MelonSmasher**
Hi all,

I've created a beat that reads browser history for Chrome, Firefox, and Safari and ships it to the output of your choice. I had to learn Go to pull this off, so be nice :-) .

### CODE REVIEW

**Comment by jsoriano** [comment]
Hey @MelonSmasher, we would need you to sign the CLA before merging this. Thanks!

**Comment by jsoriano** [comment]
jenkins, test this

**Comment by kvch** [comment]
jenkins test this

**Comment by MelonSmasher** [comment]
:+1

**Pull request merged**
