### PR TITLE
Update naming conventions with micro and nano seconds

### PR DESCRIPTION
**Pull request by ruflin**
@andrewkroh I'm somehow tempted to go with ns for nanoseconds but ns could also stand for namespace and other things. WDYT?

### CODE REVIEW

**Comment by tsg** [comment]
LGTM. Both `ns` and `nanos` seem fine to me.

**Comment by andrewkroh** [comment]
@ruflin  I like `nanos` more, but `ns` is more consistent. So I'm torn. Both are good with me. I can change my code that uses `nanos` if you want to go with `ns`.

**Comment by ruflin** [comment]
3 people that are torn between the two. @brandonmensing one more opinion? :-D

**Comment by brandonmensing** [comment]
I did a little searching for a precedent in our favorite bigger sibling project and found that they are also inconsistently using both 'ns' and 'nanos' :) 

In this context, I would go with consistency w/r/t the other conventions nearby. So 'ns' has my vote to make it a little easier on users who are using 'ms' and 'us'.

**Comment by ruflin** [comment]
PR for renaming opened here: https://github.com/elastic/beats/pull/2252

**Pull request merged**
