### PR TITLE
Agent info docs and ci test pr

### PR DESCRIPTION
**Pull request by EricDavisX**
Research into Beats ci system and usage with intention to update it eventually to build a local docker container of the Elastic Agent to facilitate pr testing in ci.

## What does this PR do?
This is a test pr, but it has a real change we could review as of now, I have added a link to the Elastic Agent in the README.md file.

This will remain a draft PR and of course get help to push it thru correctly and document all requirements before attempting to merge in to master.

### CODE REVIEW

**Comment by EricDavisX** [comment]
I'm not sure if we decided the cited / package call was working... but I'm not currently following up on this.  We can review and merge as desired the minor docs change.

**Comment by ph** [comment]
@EricDavisX Why you want to build the package, Are you trying to fix the readme shipped with the Elastic Agent, If so the code we need to modify is not in this place. https://github.com/elastic/beats/issues/21122

**Comment by EricDavisX** [comment]
i was using this pr that i was imminently merging to test the e2e test locally against the package created by this pr.  Manu says its available and ready to be used manually - super exciting, just validating it works.

**Comment by ph** [comment]
oh sneaky @EricDavisX  :D

**Comment by EricDavisX** [comment]
So, using this lil pr I confirmed it.  I ran the test with the Agent from my pr, since it was packaged and its stored in gcp storage it can be accessed. 

for ex:
 OP_LOG_LEVEL=TRACE DEVELOPER_MODE=true ELASTIC_AGENT_USE_CI_SNAPSHOTS=true ELASTIC_AGENT_VERSION=pr-19805 godog -t "stand_alone_mode"

the package call is /package

I ran it from the e2e-testing repo, in the Ingest-manager folder:
https://github.com/elastic/e2e-testing/tree/master/e2e/_suites/ingest-manager

FYI.  And now I'll merge this, too.

**Pull request merged**
