### PR TITLE
[Filebeat] Allow - for source IP for AWS S3 Access pipeline

### LINKED ISSUE #26913: Filebeat AWS Module (S3 Access Log) Grok Pattern Issue
PUT requests in AWS S3 access logs may include a hyphen in place of an IP address, so the `%{IP:aws.s3access.remote_ip}` grok pattern for the `message` field defined in `filebeat-7.13.3-aws-s3access-pipeline` results in the following error: “Provided Grok expressions do not match field value”. 

Modifying the pattern to `(?:-|%{IP:aws.s3access.remote_ip})` resolves the issue.

- Version: 7.13.3
- Operating System: Amazon Linux
- Discuss Forum URL:
- Steps to Reproduce: 
```
POST _ingest/pipeline/filebeat-7.13.3-aws-s3access-pipeline/_simulate
{
  "docs": [
    {
      "_source": {
        "message": """67797214d75628047d9c76b18a78cded1a4b069b71f2a9d5a53649c38da8770b flow-log-test [14/Jul/2021:18:57:31 +0000] - svc:delivery.logs.amazonaws.com MVGXZXEVN3IG9S24 REST.PUT.OBJECT AWSLogs/000000000000/vpcflowlogs/us-gov-east-1/2021/07/13/000000000000_vpcflowlogs_us-gov-east-1_fl-_20210713T1855Z_f12aa632.log.gz "PUT /AWSLogs/000000000000/vpcflowlogs/us-gov-east-1/2021/07/13/000000000000_vpcflowlogs_us-gov-east-1_fl-0e7c13bf00cf15bfe_20210713T1855Z_f12aa632.log.gz HTTP/1.1" 200 - - 773 103 13 "-" "-" - 02SxwfXpO5UysN0GsKGa3uGDQ6E/W7+Hwo/luRH8p1VEexULoe66RCM+nja0dEq2JqLrtgjocvVRRkVt4= SigV4 ECDHE-RSA-AES128-GCM-SHA256 AuthHeader flow-log-test.s3.us-gov-west-1.amazonaws.com TLSv1.2 -
        """
      }
    }
  ]
}
```

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Allows for a - in place of the remote IP in the AWS S3 Access ingest pipeline.

## Why is it important?

When there isn't a value for a specific field in the AWS S3 Access logs, a - is used in its place.  Currently if the remote IP is not recorded and a - is present, the grok pattern doesn't match.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have made corresponding change to the default configuration files
- [X] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally
```
cd beats/x-pack/filebeat
TESTING_FILEBEAT_MODULES=aws TESTING_FILEBEAT_FILESETS=s3access mage -v pythonIntegTest
```
## Related issues

- Closes #26913

### CODE REVIEW

**Review by kaiyan-sheng — APPROVED** [review]
Thanks for fixing this, looks good to me.

**Comment by legoguy1000** [comment]
@kaiyan-sheng looks like it's ready to merge.

**Review by leehinman — APPROVED** [review]
LGTM

**Pull request merged**
