### PR TITLE
Move v7.8 Elastic Agent docs to the observability-docs repo

### PR DESCRIPTION
**Pull request by dedemorton**
This PR moves the Elastic Agents docs to the observability-docs repo where other related docs live.

DO NOT MERGE UNTIL AFTER https://github.com/elastic/observability-docs/pull/308

### CODE REVIEW

**Review by bmorelli25 — APPROVED** [review]
Diffs match up. Pending the merge of https://github.com/elastic/observability-docs/pull/308, LGTM.

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by bmorelli25** [comment]
I believe this will fail until the scheduled build picks up the changes.

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by dedemorton** [comment]
The build fails because it's looking for the docs directory that's deleted. To make it easier, I'm adding a readme that we can remove later, but will keep the docs building until we can update the conf.yaml. https://github.com/elastic/beats/pull/23256

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs

**Pull request merged**
