### PR TITLE
Update go-quark to v0.2.0

### PR DESCRIPTION
**Pull request by mjwolf**
## Proposed commit message

Update go-quark to v0.2.0. This version of go-quark includes a bugfix from libquark that fixes use of kprobes
on newer Linux kernels.

This also removes the license override for go-quark; the license in it should now be detected properly, removing the need for the override.

## Checklist

- [x] My code follows the style guidelines of this project
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Disruptive User Impact

None

### CODE REVIEW

**Review by haesbaert — APPROVED** [review]
:heart:

**Comment by haesbaert** [comment]
Can we get a quick ok here, we would like this to make it to 8.16 as it fixes a real bug.

**Review by nicholasberlin — APPROVED** [review]

**Review by mauri870 — APPROVED** [review]

**Review by pierrehilbert — APPROVED** [review]

**Comment by pierrehilbert** [comment]
@haesbaert we should be able to merge this when the automated tests will be finalized.

**Comment by haesbaert** [comment]
> @haesbaert we should be able to merge this when the automated tests will be finalized.

awesome, many thanks!

**Pull request merged**
