### PR TITLE
Use badger code from upstream repository

### PR DESCRIPTION
**Pull request by jsoriano**
Issue in badger with 32-bits architectures has been solved in the
release branch used by Beats. Update to the version with this fix and
stop using the Elastic fork.

Fork was introduced in https://github.com/elastic/beats/pull/21613.

### CODE REVIEW

**Comment by mdelapenya** [comment]
GH checks not populated because of https://github.com/elastic/beats/pull/21738

**Comment by jsoriano** [comment]
Failing tests are #21748.

**Review by ChrsMark — APPROVED** [review]

**Pull request merged**
