### PR TITLE
Govendor ECS 1.0.1

### PR DESCRIPTION
**Pull request by cwurm**
Updates vendor dependency to ECS 1.0.1. Field definitions were already imported in https://github.com/elastic/beats/pull/12284.

### CODE REVIEW

**Comment by andrewkroh** [comment]
It looks like this is what controls the `ecs.version` value and now many of the golden files in Filebeat need to be updated. Perhaps a more sustainable fix would be to ignore the value of the `ecs.version` field in the Filebeat module tests.

**Comment by webmat** [comment]
Oh wait. You'll need to re-generate the golden files

**Comment by webmat** [comment]
Brain waking up. +1 to what @andrewkroh suggests.

☕️🏃

**Comment by ruflin** [comment]
I'm on the fence about this one as we also use this to generate the examples. I kind of like that we have it in all examples but we could also remove it.

For now I would generate it and follow up if we remove it or not. You will also have to update the generated files for metricbeat.

**Comment by cwurm** [comment]
I think I'd want to ignore `ecs.version`. If we keep checking it, we have countless (hundreds? thousands?) files to update every time we want to import even a bugfix release of ECS.

**Comment by cwurm** [comment]
> You will also have to update the generated files for metricbeat.

I don't see any of the golden files for Metricbeat containing `ecs.version`? The build for Metricbeat did not fail either, just Filebeat OSS and Filebeat X-Pack.

I've [pushed a commit](https://github.com/elastic/beats/pull/12317/commits/2aa673a5da4f56c2ce5a2d8637a9d180623ddaa7) ignoring `ecs.version` to see if that fixes the build. Let me know if that's the way we want to go, or if you prefer another way.

**Comment by ruflin** [comment]
Ok, SGTM. You are correct we don't have it in the metricbeat golden files.

One problem with the above change is that it goes green on CI but the next time someone runs generate it will remove the ECS fields and create a diff. Suggestion: Merge this PR as is but have a follow up PR which updates all the generated files?

**Comment by webmat** [comment]
Or run with `INTEGRATION_TESTS=1 GENERATE=1` and update this PR again?

**Comment by cwurm** [comment]
> Or run with `INTEGRATION_TESTS=1 GENERATE=1` and update this PR again?

What's the command to run with that?

**Comment by webmat** [comment]
Ah sorry. From one non-Filebeat developer to another 😂 

```
INTEGRATION_TESTS=1 nosetests tests/system/test_modules.py

**Comment by webmat** [comment]
Oh no, accidentally closed the PR, sorry.

I think I had Cmd or shift stuck, when hitting enter (I'm turning my laptop in for a keyboard repair this Friday, true story)

**Comment by webmat** [comment]
Make sure your Python venv is set & all that. If you want the full slew of commands to build Filebeat & get the venv right, hit me up when you see me online

**Comment by cwurm** [comment]
> Or run with `INTEGRATION_TESTS=1 GENERATE=1` and update this PR again?

Yeah, let's do it all in one so the repo is not inconsistent. I'll push a commit with the changes to the generated files in a minute.

**Comment by webmat** [comment]
Metricbeat in Travis seems completely unrelated. Some dep install problem.

Also, Jenkins, test this

**Pull request merged**
