### PR TITLE
feat: Add CloudWatchSynthetics namespace to metricbeat

### PR DESCRIPTION
**Pull request by cjr125**
- Enhancement

## What does this PR do?

This PR adds the ability to pull metrics from the CloudWatchSynthetics namespace for metricbeat's AWS module.

## Why is it important?

In order to monitor synthetics such as Canaries hosted in AWS using Kibana, it is necessary to be able to pull metrics from the CloudWatchSynthetics namespace.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by aspacca** [comment]
hello @cjr125

we recently made a huge effort in migrating to the latest aws sdk v2 version and introducing back the v1 it's not something we'd like to do

I have the impression as well that this new `cloudwatchsynthetics` it's mostly a duplication of the current `cloudwatch` module, do I miss anything?

you might want to contribute adding an integration instead (see https://github.com/elastic/integrations/tree/main/packages/aws/data_stream/cloudwatch_metrics for an example)

**Comment by cjr125** [comment]
> hello @cjr125
> 
> we recently made a huge effort in migrating to the latest aws sdk v2 version and introducing back the v1 it's not something we'd like to do
> 
> I have the impression as well that this new `cloudwatchsynthetics` it's mostly a duplication of the current `cloudwatch` module, do I miss anything?
> 
> you might want to contribute adding an integration instead (see https://github.com/elastic/integrations/tree/main/packages/aws/data_stream/cloudwatch_metrics for an example)

@aspacca that is correct. the cloudwatchsynthetics namespace is basically the same as cloudwatch with a few caveats. i originally thought it was only supported by aws sdk for go v1, but i just tried again and got it to work with v2. i will refactor the code to use the latest version of the sdk. thanks

**Comment by aspacca** [comment]
> the cloudwatchsynthetics namespace is basically the same as cloudwatch with a few caveats

can you expand on the caveats?
from a short review it seems all this code duplication is not required and just having the following in `modules.d/aws.yml` should be enough:
```
- module: aws
  period: 5m
  metricsets:
    - cloudwatch
  metrics:
    - namespace: CloudWatchSynthetics
      resource_type: synthetics
      statistic: ["Average"]
      name:
        - SuccessPercent
        - Duration
        - VisualMonitoringSuccessPercent
    - namespace: CloudWatchSynthetics
      resource_type: synthetics
      statistic: ["Sum"]
      name:
        - 2xx
        - 4xx
        - 5xx
        - Failed
        - Failed requests
    - namespace: CloudWatchSynthetics
      resource_type: synthetics
      name:
        - VisualMonitoringTotalComparison
```

**Comment by cjr125** [comment]
> > the cloudwatchsynthetics namespace is basically the same as cloudwatch with a few caveats
> 
> can you expand on the caveats? from a short review it seems all this code duplication is not required and just having the following in `modules.d/aws.yml` should be enough:
> 
> ```
> - module: aws
>   period: 5m
>   metricsets:
>     - cloudwatch
>   metrics:
>     - namespace: CloudWatchSynthetics
>       resource_type: synthetics
>       statistic: ["Average"]
>       name:
>         - SuccessPercent
>         - Duration
>         - VisualMonitoringSuccessPercent
>     - namespace: CloudWatchSynthetics
>       resource_type: synthetics
>       statistic: ["Sum"]
>       name:
>         - 2xx
>         - 4xx
>         - 5xx
>         - Failed
>         - Failed requests
>     - namespace: CloudWatchSynthetics
>       resource_type: synthetics
>       name:
>         - VisualMonitoringTotalComparison
> ```

yep, that works. thanks again

**Comment by cjr125** [comment]
@aspacca i just tried a test using the tags_filter option and it didn't work. can you please confirm?

**Pull request closed without merging**
