### PR TITLE
Fix field alias for nginx.access.remote_ip

### LINKED ISSUE #11510: [ECS] nginx.access.remote_ip should map to source.address
Currently, `nginx.access.remote_ip` does not map to `source.address`

```
apache2.access.remote_ip    ----->     source.address
iis.access.remote_ip        ----->     source.address
iis.error.remote_ip         ----->     source.address
traefik.access.remote_ip    ----->     source.address
nginx.access.remote_ip      --/-->     source.address
```
Source: https://www.elastic.co/guide/en/beats/libbeat/7.0/breaking-changes-7.0.html

For consistency sake, it probably should.

### PR DESCRIPTION
**Pull request by webmat**
- It was missing in the breaking changes doc (generated from ecs-migration.yml)
- The actual field alias was incorrectly pointing to source.ip, this has been
  adjusted to source.address
- Re-generating the documentation file also updated the breaking changes to
  include a change introduced in #11334

This should be backported to 7.0.

Closes #11510

### CODE REVIEW

**Comment by EthanStrider** [comment]
Will this update the filebeat nginx dashboards as well, as I'm fairly certain there are some visualizations that still point to nginx.access.remote_ip.

Screen Shot 2019-03-28 at 12 56 30 PM

**Comment by webmat** [comment]
@EthanStrider Ah indeed. The updates to kibana objects have also been done with the file that was missing this entry. I'll update this as well.

**Comment by EthanStrider** [comment]
I don't know if you want to try to address this issue: https://github.com/elastic/beats/issues/11517 in this PR, but mentioning it in case you do.

**Comment by webmat** [comment]
@EthanStrider Ok, the source of this job is here: https://github.com/elastic/kibana/blob/7.0/x-pack/plugins/ml/server/models/data_recognizer/modules/nginx_ecs/ml/source_ip_request_rate_ecs.json

It appears like it's been adjusted to use the ECS fields directly in January (https://github.com/elastic/kibana/pull/29383), so this should be in 7.0-rc1. How did you get this ML content installed, are you using 7.0-rc1?

**Comment by webmat** [comment]
Wait, I take that back. It may be fine over in that repo.

But when playing with Beats locally, the wrong file seems to be pulled in, referencing the old field name.

**Comment by webmat** [comment]
jenkins, test this

**Pull request merged**
