### PR TITLE
DNS over TLS support for DNS processor

### LINKED ISSUE #16663: [*beats] Reverse DNS processor support DNSoverTLS
**Describe the enhancement:**
Hi,

I wanted to suggest that there should be a DNSoverTLS configuration possibility in the reverse DNS processor.

[Filebeat DNS processor](https://www.elastic.co/guide/en/beats/filebeat/master/processor-dns.html)

### PR DESCRIPTION
**Pull request by philippkahr**
## What does this PR do?

Implement DNS over TLS (DoT) handler for the DNS Processor. #16663

## Why is it important?

Now you can securely query for reverseDNS lookups across the internet. E.g. cloudflare 1.1.1.1 supports DNS over TLS

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
I would need a bit of *help* here. Do I have to touch every beat config, or is the DNS processor page in the docs rendered from the libbeat ascii doc file?
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

1. go to filebeat
2. make
3. edit filebeat config to include the at least the DNS processor

<details><summary>Minimum filebeat config</summary>
<p>

```yaml
  - dns:
      type: reverse
      transport: tls
      fields:
        source.ip: source.hostname
        destination.ip: destination.hostname
      nameservers: ["1.1.1.1"]
```
</p>
</details>

<details><summary>Full filebeat config</summary>
<p>

```yaml
filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /Users/e_pkah/Documents/GitHub/pkahr/demodata/*
  json.keys_under_root: true
  json.add_error_key: true
filebeat.config.modules:
  path: ${path.config}/modules.d/*.yml
  reload.enabled: false
setup.template.settings:
  index.number_of_shards: 1
output.elasticsearch:
  hosts: ["localhost:9200"]
processors:
  - decode_json_fields:
      fields: log
      overwrite_keys: true
  - dns:
      type: reverse
      transport: tls
      fields:
        source.ip: source.hostname
        destination.ip: destination.hostname
      nameservers: ["1.1.1.1"]
```

</p>
</details>

<details><summary>Example doc</summary>
<p>

```json
{"source.ip": "1.1.1.1","destination.ip": "8.8.8.8"}
```

</p>
</details>

4. replace transport: either with `tls`, `udp`. If left empty it will revert to default `udp`
5. Ingest some file that has a source.ip or destination.ip (e.g. use example doc above)

## Related issues

- Closes elastic/beats#16663
- Should we create an additional issue that tracks the status of the implementation of DNS over HTTPS in the <https://github.com/miekg/dns> repo?

## Use cases

- Allow for secure reverse DNS lookups across the entire Internet and locally

## Logs

<details><summary>TLS</summary>
<p>

```bash
./filebeat -e -d "*"
2020-06-22T19:56:00.082+0200    DEBUG   [processor.dns] dns/dns.go:67   DNS processor config: {CacheConfig:{SuccessCache:{TTL:0s InitialCapacity:1000 MaxCapacity:10000} FailureCache:{TTL:1m0s InitialCapacity:1000 MaxCapacity:10000}} Nameservers:[1.1.1.1] Timeout:500ms Type:reverse Action:append TagOnFailure:[] Fields:{"destination":{"ip":"destination.hostname"},"source":{"ip":"source.hostname"}} transport:tls reverseFlat:map[destination.ip:destination.hostname source.ip:source.hostname]}      {"instance_id": 1}
```

```json
2020-06-22T20:28:31.155+0200    DEBUG   [processors]    processing/processors.go:187    Publish event: {
  "@timestamp": "2020-06-22T18:28:30.854Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "_doc",
    "version": "8.0.0"
  },
  "log": {
    "offset": 0,
    "file": {
      "path": "/Users/e_pkah/Documents/GitHub/pkahr/demodata/apache.json"
    }
  },
  "ecs": {
    "version": "1.5.0"
  },
  "destination": {
    "hostname": "dns.google"
  },
  "agent": {
    "id": "6bc4fd89-5e9e-4382-a2fb-5068f5782406",
    "name": "N1890002",
    "type": "filebeat",
    "version": "8.0.0",
    "ephemeral_id": "b8d53727-48f5-4a6a-9c84-735b7d4d0905"
  },
  "source": {
    "hostname": "one.one.one.one"
  },
  "source.ip": "1.1.1.1",
  "destination.ip": "8.8.8.8",
  "input": {
    "type": "log"
  },
  "host": {
    "name": "N1890002"
  }
}
```

<p>
</details>

<details><summary>UDP / no config</summary>
<p>

```bash
./filebeat -e -d "*"
2020-06-22T20:13:33.150+0200    DEBUG   [processor.dns] dns/dns.go:67   DNS processor config: {CacheConfig:{SuccessCache:{TTL:0s InitialCapacity:1000 MaxCapacity:10000} FailureCache:{TTL:1m0s InitialCapacity:1000 MaxCapacity:10000}} Nameservers:[1.1.1.1] Timeout:500ms Type:reverse Action:append TagOnFailure:[] Fields:{"destination":{"ip":"destination.hostname"},"source":{"ip":"source.hostname"}} transport:udp reverseFlat:map[destination.ip:destination.hostname source.ip:source.hostname]}      {"instance_id": 1}
```

```json
2020-06-22T20:28:31.155+0200    DEBUG   [processors]    processing/processors.go:187    Publish event: {
  "@timestamp": "2020-06-22T18:28:30.854Z",
  "@metadata": {
    "beat": "filebeat",
    "type": "_doc",
    "version": "8.0.0"
  },
  "log": {
    "offset": 0,
    "file": {
      "path": "/Users/e_pkah/Documents/GitHub/pkahr/demodata/apache.json"
    }
  },
  "ecs": {
    "version": "1.5.0"
  },
  "destination": {
    "hostname": "dns.google"
  },
  "agent": {
    "id": "6bc4fd89-5e9e-4382-a2fb-5068f5782406",
    "name": "N1890002",
    "type": "filebeat",
    "version": "8.0.0",
    "ephemeral_id": "b8d53727-48f5-4a6a-9c84-735b7d4d0905"
  },
  "source": {
    "hostname": "one.one.one.one"
  },
  "source.ip": "1.1.1.1",
  "destination.ip": "8.8.8.8",
  "input": {
    "type": "log"
  },
  "host": {
    "name": "N1890002"
  }
}
```

<p>
</details>

### CODE REVIEW

**Comment by philippkahr** [comment]
Hi,

I am not too happy about all the added duplicated code for the `TLS` test, however, I could not figure out a way where we can reuse most of the code. Maybe someone can point me in the right direction https://github.com/elastic/beats/pull/19321/commits/17b1c077a00b5048a8be734ea39b8ea32832c4ef

**Comment by philippkahr** [comment]
Hi @andrewkroh I hope it is ok, that I ping you on this PR. I saw that you originally developed the DNS processor. Could you look into this PR?

**Comment by marc-gr** [comment]
Hello @philippkahr and thanks for opening this PR!

Couple of things:

Please add the `CHANGELOG.next.asciidoc` entry to the end of the entry list, and remove it from `CHANGELOG-developer.next.asciidoc`
 I think this will need a rebase and to run `mage fmt update` to generate the new documentation.

If you wish, we can help you through it or do it ourselves, as you prefer.

**Comment by philippkahr** [comment]
Hi @marc-gr I am currently on vacation and do not have access to my MacBook. If you could be so kind and perform those changes for me, I would be happy.

**Comment by marc-gr** [comment]
> Hi @marc-gr I am currently on vacation and do not have access to my MacBook. If you could be so kind and perform those changes for me, I would be happy.

Sure no problem! enjoy the rest of your vacations!

**Comment by marc-gr** [comment]
jenkins run tests

**Comment by marc-gr** [comment]
jenkins run tests

**Comment by marc-gr** [comment]
jenkins run tests

**Pull request merged**
