### PR TITLE
[heartbeat][agent] Remove unnecessary cups dependency

### PR DESCRIPTION
**Pull request by andrewvc**
We currently install cups mistakenly, it's not needed to support
chromium browsers.

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Review by vigneshshanmugam — APPROVED** [review]
LGTM

**Review by justinkambic — APPROVED** [review]
LGTM - did not do any real-world testing. LMK if needed.

**Comment by andrewvc** [comment]
@Mergifyio backport 8.0

**Pull request merged**
