### PR TITLE
use ADC on GCP instances

### PR DESCRIPTION
**Pull request by mwasilew2**
## What does this PR do?

Instead of requiring a file with credentials, the beat uses Google's ADC

## Why is it important?

Without this change, Filebeat requires a path to a file with credentials to be provided in its config and is unable to use for example a default service account.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~

## Author's Checklist

- [ ]

## How to test this PR locally

1. Upload the Filebeat binary to a GCP instance created with default config
1. Run the binary configured to read from PubSub, but do not provide any credentials
1. Filebeat should be able to detect that it's on GCP and use ADC (get a token for the default service account for the VM from the metadata server)

## Related issues

- Closes https://github.com/elastic/beats/issues/15667

## Use cases

Sending logs to Elastic from PubSub queue

### CODE REVIEW

**Comment by blakerouse** [comment]
@elastic/siem Can you take a look at this change?

**Comment by andrewkroh** [comment]
jenkins, test this please

**Comment by andrewkroh** [comment]
The integration tests is failing due to this change. https://travis-ci.org/elastic/beats/jobs/638704764#L9301-L9327

**Comment by mwasilew2** [comment]
@andrewkroh

> So the validation would check that one of the options is available - ADC, credential_file exists, or JSON credentials is non-empty.

yea, it definitely makes sense

I took another stab at it, let me know if this approach is better

I also tried running the integration tests locally but they seem to fail on netflow:
```bash
$ make -C x-pack/filebeat testsuite
make: Entering directory '/home/michal/go/src/github.com/elastic/beats/x-pack/filebeat'
Installing mage v1.9.0 from vendor dir.
go install -mod=vendor -ldflags="-X github.com/magefile/mage/mage.gitTag=v1.9.0" github.com/magefile/mage
/home/michal/.magefile cleaned
rm -f build/TEST-go-integration.out
mage update build unitTest integTest || ( cat build/TEST-go-integration.out && false )
No fields files for module azureeventhub
No fields files for module cloudfoundry
No fields files for module googlepubsub
No fields files for module httpjson
No fields files for module o365audit
Generated fields.yml for filebeat to /home/michal/go/src/github.com/elastic/beats/x-pack/filebeat/fields.yml
>> Building filebeat.yml for linux/amd64
>> Building filebeat.reference.yml for linux/amd64
>> Building filebeat.docker.yml for linux/amd64
exec: go list -m
>> build: Building filebeat
>> go test: Unit Testing
FAILURES:
Package: github.com/elastic/beats/v7/x-pack/filebeat/input/netflow
Test:    [build failed]
----
SUMMARY:
  Fail:     1
  Skip:     7
  Pass:     453
  Packages: 21
  Duration: 26.73016531s
  JUnit Report: /home/michal/go/src/github.com/elastic/beats/x-pack/filebeat/build/TEST-go-unit.xml
  Output File:  /home/michal/go/src/github.com/elastic/beats/x-pack/filebeat/build/TEST-go-unit.out
>> go test: Unit Test Failed
Error: go test failed: 1 test failures
cat: build/TEST-go-integration.out: No such file or directory
make: *** [../../dev-tools/make/xpack.mk:48: testsuite] Error 1
make: Leaving directory '/home/michal/go/src/github.com/elastic/beats/x-pack/filebeat'
[1]    59958 exit 2     make -C x-pack/filebeat testsuite
```

let me know if there's anything else I can help with

**Comment by andrewkroh** [comment]
I update the PR to add:

- unit test for the config validation
- updated google-pubsub doc to mention ADC can be used
- update googlecloud modules to support ADC and `credentials_json`

**Comment by andrewkroh** [comment]
run tests

**Pull request merged**
