### PR TITLE
imgbot: optimize images

### PR DESCRIPTION
**Pull request by hazcod**

### CODE REVIEW

**Comment by hazcod** [comment]
Welp, not sure how a build can fail for image changes. :-)

**Comment by ycombinator** [comment]
Hi @hazcod, thanks for this PR. Please sign the [Elastic CLA](https://www.elastic.co/contributor-agreement) so we can review and merge this PR. Thanks!

**Comment by hazcod** [comment]
Hmm that should be in order.

**Comment by ycombinator** [comment]
@hazcod Ah, I think I see the problem. It's the commit made by `ImgBotApp`: https://github.com/elastic/beats/pull/18117/commits/06d0b0ae68837911ea613a1fc6456c86caed4a0c. That user hasn't signed the CLA 🙂. Any chance you could remove that commit and make it with your GitHub user instead?

**Pull request closed without merging**
