### PR TITLE
Upgrade elasticsearch templates so that they are compliant with the upcoming elasticsearch 5.0.

### PR DESCRIPTION
**Pull request by jpountz**
Elasticsearch 5.0 has refactored mappings as described in
elastic/elasticsearch#12394. Most notably the string field has been replaced
by the `text` and `keyword` fields.

### CODE REVIEW

**Comment by ruflin** [comment]
@jpountz Thanks a lot for the contribution. I saw you updated the generation script, so I assume all the template files are generated automatically based on this?

**Comment by jpountz** [comment]
@ruflin Indeed I used the script to regenerate the templates.

**Comment by tsg** [comment]
I tested Topbeat, Packetbeat and Filebeat and they all seem to work fine. The travis fail is because of the LS plugin, so not related.

However, I'm going to sit on this at least until our team meeting today, because we probably will want to keep the old templates around, so that Beats 5.0 work with ES < 5.0.

**Comment by jpountz** [comment]
> However, I'm going to sit on this at least until our team meeting today, because we probably will want to keep the old templates around, so that Beats 5.0 work with ES < 5.0.

Something to be careful with is that it means that Beats 5.0 will not be compatible with Elasticsearch 6.0.

Would it be possible for Beats to load a different template based on the version of the elasticsearch cluster that it connects to?

**Comment by ruflin** [comment]
@jpountz Potentially possible to load different templates for different ES version. We still have to solve the problem of versioning templates for different beats versions and then should also take this one into account.

**Comment by tsg** [comment]
We decided in the meeting that we want to go with the new templates only, because we only aim to work with the previous version of ES for the purpose of upgrading, in which case the templates are already loaded.

So I'm simply merging this one, thanks @jpountz.

**Pull request merged**
