### PR TITLE
just fix a word.

### PR DESCRIPTION
**Pull request by bellship24**
I think that 'module' on 29 line might be 'volume'.

## What does this PR do? 
Docs

## Why is it important? 
It's simple, but beginners who don't know the concept of modules can get confused.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by EamonnTP** [comment]
Hi @bellship24 Thanks for your contribution. Would you mind signing the [Contributor Agreement](https://www.elastic.co/contributor-agreement)?

**Comment by EamonnTP** [comment]
jenkins run the tests please

**Comment by EamonnTP** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by EamonnTP** [comment]
jenkins run the tests please

**Review by bmorelli25 — CHANGES_REQUESTED** [review]
The tests won't pass on this PR because this is a generated file (see the top of the file) The source needs to be edited instead. You can then run `mage fmt update` to update this file.

Source file is located here: https://github.com/elastic/beats/blob/master/metricbeat/module/kubernetes/_meta/docs.asciidoc

**Comment by EamonnTP** [comment]
Hi @bellship24 thanks for your contribution to Elastic!

Unfortunately, we require a signed contributor agreement to be able to merge a PR. I have made the update in a separate PR, so I'm going to close this one. Thanks again for helping us improve our documentation!

**Pull request closed without merging**
