### PR TITLE
Cherry-pick #9056 to 6.x: Use _doc if ES major version is 7

### PR DESCRIPTION
**Pull request by urso**
Cherry-pick of PR #9056 to 6.x branch. Original message: 

Update the Elasticsearch output and template generator to set the type
to _doc if Elasticsearch major version is 7.

### CODE REVIEW

**Comment by ruflin** [comment]
The failures are presistent so I wonder how they are related to this change. Does the template need adjustments or the tests at least?

**Comment by ruflin** [comment]
@urso What should be the upgrade behaviour here? Someone using MB 6.6 with ES 6.7 and then ES is upgraded, will still have the old template. As soon as he goes to the next version of MB, the new template will be loaded. Is that ok?

**Comment by urso** [comment]
It's a system test that fails. Unfortunately all system tests make assumptions about the ES version being used and how template format should look like. This will hunt us a while.

**Comment by urso** [comment]
> What should be the upgrade behaviour here? Someone using MB 6.6 with ES 6.7 and then ES is upgraded, will still have the old template. As soon as he goes to the next version of MB, the new template will be loaded. Is that ok?

Oh good point... this might be a problem. We have to update/overwrite the template when we detect ES is updated. Otherwise ES will reject indexing due to us having two types `doc` and `_doc`.

In the future (not yet supported by ES) we will remove the `_type` from the bulk request. Then we won't have this issue. But I don't think we will have this behavior ready in ES when we have Beats 6.6.

Thinking about it, we should wait with backporting the change until 6.6 has it's own branch AND we do not set `_type` in bulk requests anymore.

**Pull request closed without merging**
