### PR TITLE
Merge support for prometheus exporter

### PR DESCRIPTION
**Pull request by vjsamuel**
To test, please deploy a sample prometheus exporter like the following:
https://github.com/prometheus/node_exporter

Point the config file to the prometheus exporter endpoint

### CODE REVIEW

**Comment by vjsamuel** [comment]
can someone help me on this one? I added the glide.yaml and yet its not able to get the vendor packages

**Comment by vjsamuel** [comment]
@ruflin Could you please help me resolve this build issue?

**Comment by ruflin** [comment]
@vjsamuel Sure. We are all currently still traveling. Will have a look at it as soon as I find the time.

**Comment by ruflin** [comment]
How did you add the vendor dependencies (which command did you run)? It seems like quite a few are missing. See for example:

```
module/prometheus/vendor/github.com/prometheus/client_model/go/metrics.pb.go:25:8: cannot find package "github.com/golang/protobuf/proto" in any of:
```

**Comment by ruflin** [comment]
As mentioned at Elastic{ON} I plan to make some bigger changes to the config which "could" also affect the modules. One suggestion for this PR is to make it first its independent beat so that major changes will not affect it directly. Creating your own beat for a module adds only a few lines. An example on how to do it can be found in the df2beat: https://github.com/ruflin/df2beat 

This allows you to already run and test your beat and we "decouple" the dependency a little bit until metricbeat is getting more stable.

WDYT? Happy to also help with this.

**Comment by vjsamuel** [comment]
I ran glide guess and then appended the list of modules to the glide.yaml. I've already tested the code and it seems to work fine. Just that Im not able to get CI to build it. Is there a timeline for the config changes to go in? For the time being Im fine to use the changes that I've made in my branch until the config changes are out.

Could you please share some documents on how to use glide? Im not very familiar with go dependency management.

**Comment by ruflin** [comment]
The best docs for glide can be found here: https://github.com/Masterminds/glide

Basically it is `glide init` and then `glide update`. I think the problem is that the dependencies of the dependencies are missing. As you realised, glide tries to load the dependencies as submodule. So after all the packages were added to the vendor directory, make sure to remote all the `.git` folders inside the vendor directory.

About config changes timeline: Hopefully soon :-)

**Comment by vjsamuel** [comment]
should we have vendor directories for individual modules? i read that go code breaks when two modules manage the same package

**Comment by ruflin** [comment]
@vjsamuel This is a good question. We haven't made a decision here yet. The main part I like about having it "local" is that it is obvious which dependency belongs to which module. But as you described above, it can also break things.

**Comment by vjsamuel** [comment]
There are simply too many dependencies. Is there an easy way to get all dependency of dependencies? Also, Im not sure if checking in all the dependencies is such a good idea.

**Comment by ruflin** [comment]
@vjsamuel Glide should by default fetch all the dependencies of the dependencies.

**Comment by vjsamuel** [comment]
Having some problem with that. I just did a glide create and then glide up. When I do make test it expects several other modules.

**Comment by ruflin** [comment]
So there are more modules then listed here? https://github.com/vjsamuel/beats/blob/72705ab2c6c02ea2a0e5b49d9a4892e426de599c/metricbeat/module/prometheus/glide.yaml

Do you see any solution that we don't need all the dependencies at all? My assumption so far is that every module will have 1-3 dependencies for the connection. But it seems like this one has many more.

How will the event of one metricset look like?

**Comment by vjsamuel** [comment]
This is how the payload looks:
```
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_rejected_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "percolate"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_rejected_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "refresh"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_rejected_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "search"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_rejected_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "snapshot"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_rejected_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "suggest"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_rejected_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "warmer"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "count": "1057",
    "name": "go_gc_duration_seconds",
    "percentiles": {
      "0": "0.00011421700000000001",
      "0.25": "0.00014423700000000002",
      "0.5": "0.00016346900000000002",
      "0.75": "0.000212837",
      "1": "0.0015055300000000001"
    },
    "sum": "0.29963586000000003"
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_indices_filter_cache_evictions",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_indices_filter_cache_memory_size_bytes",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_indices_merges_total_size_bytes_total",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1"
    },
    "value": 1.0727933e+07
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_transport_tx_packets_total",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1"
    },
    "value": 58
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_indices_segments_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1"
    },
    "value": 51
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "go_memstats_last_gc_time_seconds",
    "value": 1.456363081737495e+19
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "count": "357",
    "name": "http_response_size_bytes",
    "percentiles": {
      "0.5": "3275",
      "0.9": "3285",
      "0.99": "3290"
    },
    "sum": "1150430",
    "tags": {
      "handler": "prometheus"
    }
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_active_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "bulk"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_active_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "fetch_shard_started"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_active_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "fetch_shard_store"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_active_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "flush"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_active_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "force_merge"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_active_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "generic"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_active_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "get"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_active_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "index"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_active_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "listener"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_active_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "management"
    },
    "value": 1
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_active_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "percolate"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_active_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "refresh"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
{
  "@timestamp": "2016-02-25T01:19:01.575Z",
  "beat": {
    "hostname": "localhost",
    "name": "localhost"
  },
  "elasticsearch-metrics": {
    "name": "elasticsearch_thread_pool_active_count",
    "tags": {
      "cluster": "elasticsearch",
      "node": "127.0.0.1",
      "type": "search"
    },
    "value": 0
  },
  "metricset": "metrics",
  "module": "elasticsearch",
  "type": "metricsets"
}
```

Prometheus can export metrics either as text or protobuf message,  hence the reason why so many dependencies are coming in to picture.

**Comment by vjsamuel** [comment]
Will submit a fresh PR once this is resolved.

**Comment by ruflin** [comment]
@vjsamuel Thanks for the patience and sorry for the late reply. Some updates and thoughts from my side.

Config changes for metricbeat are merged into master: https://github.com/elastic/beats/pull/1049

I had a closer look at prometheus and node-exporter. The idea of a module is to connect to a system and fetch its stats / metrics. In the case of prometheus module I would expect that it fetches the metrics of prometheus itself, not metrics that it collected from other systems.

What you implemented is much more then just prometheus metrics, but actually all the metrics prometheus collected as far as I understand. I'm not 100% sure this directly fits the current metricbeat model, but what you did is really powerful. It no only reports single metrics but also precentiles, aggregated metrics and much more. 

This is definitively a project I highly encourage to move forward as with a quite simple implementation a very broad ranges of metrics gets availabl (it indirectly also competes with metricbeat itself). At the moment I more see it as its independent beat (Nodeexporterbeat?) based on metricbeat as a library. This keeps the implementation as simple as it is right now and will make it possible to profit from all improvements made on metricbeat directly.

@vjsamuel Please let me know your thoughts. Also happy to jump on a call to discuss more in details.

**Pull request closed without merging**
