### PR TITLE
use main default branch

### PR DESCRIPTION
**Pull request by v1v**
## What does this PR do?

Rename `master` for `main` in:
- Jenkins pipelines
- JJBB files
- https://github.com/elastic/beats URLs with the `blob/master` reference

## Why is it important?

Neutral naming initiative

## Follow ups

- Doc changes to be done in another PR.
- Change docs to support `master` for the time being.
- Change infra jjb automation.

### CODE REVIEW

**Review by jlind23 — COMMENTED** [review]
Looks good to me. Will github protection rules be updating accordingly?

**Comment by v1v** [comment]
> Looks good to me. Will github protection rules be updating accordingly?

Yes

image

**Review by jsoriano — APPROVED** [review]
LGTM, but please wait for some other approval :slightly_smiling_face:

**Review by jlind23 — APPROVED** [review]
LGTM

**Review by kuisathaverat — APPROVED** [review]

**Pull request merged**
