### PR TITLE
Merge master into 6.x

### PR DESCRIPTION
**Pull request by ruflin**
Please do merge this branch and not squash the commits.

### CODE REVIEW

**Comment by ruflin** [comment]
As soon as https://github.com/elastic/beats/pull/5171 is in will update this PR again.

**Comment by tsg** [comment]
@ruflin Just FYI, we've got a `./dev-tools/merge_pr` script that you can use to create these merging PRs.

**Comment by ruflin** [comment]
@tsg Forgot about the script. I think I should also use this in apm-server.

**Comment by ruflin** [comment]
Closing this PR and will use the script for a "proper" merge.

**Pull request closed without merging**
