### PR TITLE
[DOC] Typo for Juniper module / Junos fileset example

### PR DESCRIPTION
**Pull request by lucabelluccini**
## What does this PR do?

Fix typo for Juniper module / Junos fileset example

## Checklist for maintainers

- [ ] Backport this to previous branches/versions

### CODE REVIEW

**Comment by lucabelluccini** [comment]
@elastic/obs-docs can you please take a look to this PR 🙏 ?

**Comment by rdner** [comment]
@mergifyio update

**Comment by rdner** [comment]
Seems like this PR requires to run `make update` and commit generated changes.

**Review by efd6 — APPROVED** [review]
This could potentially be extended to include the other filesets in the module.

**Review by rdner — APPROVED** [review]

**Pull request merged**
