### PR TITLE
Add test collector for the Beats projects

### PR DESCRIPTION
**Pull request by alexsapran**
## Proposed commit message

This change will add the Buildkite test collector suite to the Beats pipelines.

We are starting with the Filebeat and Libbeat.

Related: [#3914](https://github.com/elastic/ingest-dev/issues/3914)

### CODE REVIEW

**Comment by alexsapran** [comment]
Just discovered that I need to do some more testing on something, please hold reviewing

**Review by jlind23 — APPROVED** [review]

**Review by jlind23 — APPROVED** [review]
Looks good to me but do we really want to keep debug true on all?

**Comment by alexsapran** [comment]
>Looks good to me but do we really want to keep debug true on all?

I have taken this from the similar changes as in https://github.com/elastic/elastic-agent/pull/5385.
My thought are to have it on, then monitor some builds and then turn it off.

**Comment by jlind23** [comment]
@alexsapran sounds good to me, let's get this merged.

**Pull request merged**
