### PR TITLE
Use docker prospector in examples, fixes #5934 and #5920

### LINKED ISSUE #5934: Update Filebeat Kubernetes manifests to use `docker` prospector
https://github.com/elastic/beats/pull/5402 was released already, we should update Kubernetes manifests to take benefit from it.

This also fixes #5920

### PR DESCRIPTION
**Pull request by zytek**

### CODE REVIEW

**Comment by zytek** [comment]
cla signed

**Comment by karmi** [comment]
Hi @zytek, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/beats/pull/5963.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by zytek** [comment]
@karmi just fixed that via amend + push force

**Comment by zytek** [comment]
.. and added secondary email to my GH profile

**Comment by ruflin** [comment]
@exekias You are the best one to review this.

@zytek I think we will also need a changelog for this one.

**Comment by ruflin** [comment]
jenkins, test it

**Comment by zytek** [comment]
Added changelog entry, squashed all commits.

**Comment by exekias** [comment]
Closes #5920 and #5934

**Pull request merged**
