### PR TITLE
Add rsbeat to communitybeats doc

### PR DESCRIPTION
**Pull request by rockybean**

### CODE REVIEW

**Comment by ruflin** [comment]
@rockybean Great to see a beat for the redis slow log. Could you sign the CLA? https://www.elastic.co/contributor-agreement

**Comment by tsg** [comment]
Nice one!

**Comment by rockybean** [comment]
@ruflin I just signed the CLA

**Comment by ruflin** [comment]
@rockybean Thanks that worked. Could you change the order of your beat in the list? We sort it alphabetically based on the beat name.

**Comment by rockybean** [comment]
@ruflin I've changed the order

**Comment by ruflin** [comment]
@rockybean Thanks

**Pull request merged**
