### PR TITLE
[Filebeat] Additional parsing for `haproxy.http.request.raw_request_line`

### LINKED ISSUE #25480: [Filebeat] [HaProxy] Parse http and url fields
**Describe the enhancement:**
The current pipeline for HaProxy does not parse the `haproxy.http.request.raw_request_line` further into possible fields.
Example:
```
{
    "haproxy.http.request.raw_request_line": "POST /path/to/page HTTP/1.1"
}
```
Can be further parsed into:
```
{
    "haproxy": {
        "http": {
            "request": {
                "raw_request_line": "POST /path/to/page HTTP/1.1"
            }
        }
    },
    "http": {
        "request": {
            "method": "POST"
        ",
        "version": "1.1"
    },
    "url": {
        "path": "/path/to/page"
    }
}
```

I'm not entirely sure if HaProxy logs request parameters (query) but if so the path can be split into it ofcourse:
```
{
    "haproxy.http.request.raw_request_line": "POST /path/to/page?key=value HTTP/1.1"
}
```
Can be further parsed into:
```
{
    "haproxy": {
        "http": {
            "request": {
                "raw_request_line": "POST /path/to/page?key=value HTTP/1.1"
            }
        }
    },
    "http": {
        "request": {
            "method": "POST"
        ",
        "version": "1.1"
    },
    "url": {
        "path": "/path/to/page",
        "query": "key=value"
    }
}
```

**Describe a specific use case for the enhancement or feature:**
More complete parsing will allow for better monitoring in both observability (how often is page `y` opened) as well as security.

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Parses the `haproxy.http.request.raw_request_line` field into `url.original`,`http.request.method`,`http.version`

## Why is it important?

Allows for better correlation between other logs.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have made corresponding change to the default configuration files
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally
```
cd beats/filebeat
TESTING_FILEBEAT_MODULES=haproxy mage -v pythonIntegTest
```
## Related issues

- Closes #25480

### CODE REVIEW

**Comment by P1llus** [comment]
run tests

**Review by P1llus — APPROVED** [review]
LGTM.
**Checked for:**
Changelog entry.
Updated golden files.
Existing field is not renamed/removed, so no breaking change.
The new ECS mappings are correct.

Would need a +1 from a observability/integrations member as well.

Will wait for CI to finish first.

**Comment by legoguy1000** [comment]
Looks like some Jenkins error on the windows 7 job.

**Comment by P1llus** [comment]
> Looks like some Jenkins error on the windows 7 job.

Yeah that one is unrelated to yours, its a known issue.

Did you make this PR from the latest master?

**Comment by legoguy1000** [comment]
It should be. Let me verify real quick.

**Comment by P1llus** [comment]
run tests

**Comment by legoguy1000** [comment]
> run tests

Looks like it worked this time.

**Comment by P1llus** [comment]
> > run tests
> 
> Looks like it worked this time.

Yeah all good, just waiting for the approval from the other team.

**Comment by SHolzhauer** [comment]
@legoguy1000 LGTM

**Review by marc-gr — APPROVED** [review]

**Comment by legoguy1000** [comment]
@marc-gr @P1llus can one of you merge this if it GTG?

**Comment by P1llus** [comment]
Can you cherry-pick this to 7.x branch @legoguy1000 ?

**Comment by legoguy1000** [comment]
> Can you cherry-pick this to 7.x branch @legoguy1000 ?

sure

**Pull request merged**
