### PR TITLE
Configurable line terminator

### LINKED ISSUE #5500: Support \r as line separator
- Version: 5.6.3
- Operating System: limitation reproduced on Mac and Linux
- Current behaviour : 
Filebeat looks for \n or \r\n to split the lines (LF and CR+LF)
- Requested behaviour : 
Ability to specify newline separator (similar to logstash file input separator) or native support for following separators (extract from https://en.wikipedia.org/wiki/Newline):

```
The Unicode standard defines a number of characters that conforming applications should recognize as line terminators:

 LF:    Line Feed, U+000A
 VT:    Vertical Tab, U+000B
 FF:    Form Feed, U+000C
 CR:    Carriage Return, U+000D
 CR+LF: CR (U+000D) followed by LF (U+000A)
 NEL:   Next Line, U+0085
 LS:    Line Separator, U+2028
 PS:    Paragraph Separator, U+2029
```

### PR DESCRIPTION
**Pull request by kvch**
This PR add a new input configuration option named `line_terminator`:

```
# Characters which separate the lines. Valid values: auto, line_feed, vertical_tab, form_feed,
# carriage_return, carriage_return_line_feed, next_line, line_separator, paragraph_separator.
#line_terminator: auto
```
The option `auto` tells Filebeat to use our current hybrid new line finder approach. Thus, we can avoid introducing a breaking change.

It also contains a minor refactoring in `readfile` package. I have created a new type `Config` which stores the configuration of the readers of the package. This eliminates a long list of parameters in the constructors of `EncodeReader` and `LineReader`.

Closes #5500

### CODE REVIEW

**Comment by kvch** [comment]
jenkins test this

**Comment by kvch** [comment]
jenkins test this

**Comment by kvch** [comment]
jenkins test this

**Comment by kvch** [comment]
jenkins test this

**Comment by kvch** [comment]
It is indeed less dynamic. This PR requires the input file to use one kind of newline. Previously the following input file was readable:
```
hello\n
hello\r\n
```
Also if someone has different files with different newlines, e.g.
```
hello\n
hello\n
```
and
```
hello\r\n
hello\r\n
```
he/she was able to add it to the same input.

By default on Windows the configured newline is `carriage_return_line_feed`, on other OSes the default is `line_feed`.

To make the configuration backward compatible, a new option `auto` (for a lack of a better name) could be added which is basically our current newline handling. WDYT?

**Comment by urso** [comment]
SGTM.

Alternatively we can have 2 patterns. One 'split' pattern and one 'right-trim' pattern. This way we're not limited to newlines anymore, but could support more complex patterns for split based multiline.

**Pull request merged**
