### PR TITLE
[elastic-agent] Rename 'offline' image to 'complete'

### PR DESCRIPTION
**Pull request by andrewvc**
We've discussed internally that 'complete' is more appropriate than 'offline' in terms of naming for the new image. This makes that simple change.

### CODE REVIEW

**Review by vigneshshanmugam — CHANGES_REQUESTED** [review]
Needs changes in this file - https://github.com/andrewvc/beats/blob/3fa0117008079b08c713a29b80c5ed36743fefcb/dev-tools/packaging/templates/docker/Dockerfile.elastic-agent.tmpl#L32

**Comment by andrewvc** [comment]
@elasticmachine merge upstream

**Review by vigneshshanmugam — APPROVED** [review]
LGTM

**Comment by andrewvc** [comment]
@mergifyio update

**Comment by andrewvc** [comment]
@mergifyio update

**Comment by andrewvc** [comment]
@Mergifyio backport 7.x

**Comment by andrewvc** [comment]
@Mergifyio backport 7.x

**Pull request merged**
