### PR TITLE
Backport #29133 to 7.17

### PR DESCRIPTION
**Pull request by MichaelKatsoulis**
Backporting #29133 to 7.17 as per https://github.com/elastic/beats/issues/33108

### CODE REVIEW

**Review by ChrsMark — APPROVED** [review]
lgtm. 

I see the number of lines' diff is different compared to https://github.com/elastic/beats/pull/29133. Consider having a look into the diffs so as to make sure the backport did not miss any  important line from the original PR.

**Comment by MichaelKatsoulis** [comment]
> I see the number of lines' diff is different compared to #29133. 

@ChrsMark that is because this is not a blind backport. Some things added in #29133 where relevant to pre-existing features in 8.1 branch like  the https://github.com/elastic/beats/pull/28521 or the named watchers.

I tried to keep only the bare minimum which is the enrichment with namespace and node labels and annotations.

**Review by gizas — APPROVED** [review]

**Comment by skakauridze-clgx** [comment]
Is this backport for only 7.17.0, or for other patch versions as well? E.g 7.17.6?

**Comment by skakauridze-clgx** [comment]
What is the plan for releasing this merge?

**Pull request merged**
