### PR TITLE
[8.16] Revert "[filebeat][winlog] implement status reporter for winlog input…

### PR DESCRIPTION
**Pull request by cmacknz**
Revert https://github.com/elastic/beats/issues/40543 because of https://github.com/elastic/elastic-agent/issues/5746.

Specifically the status reporting in winlog causes the winlog input to be degraded as when agent is privileged (i.e. the default configuration) when the Sysmon operational channel is missing (also true by default because it is not a core Windows component).

### CODE REVIEW

**Comment by bjmcnic** [comment]
Do we need to revert the accompanying `CHANGELOG.next.asciidoc` in the original PR as well?

**Comment by cmacknz** [comment]
We would if the original PR added one, which it doesn't look like it did.

I don't see any reference to this in https://github.com/elastic/beats/blob/8.16/CHANGELOG.next.asciidoc

**Comment by cmacknz** [comment]
FYI @VihasMakwana, nothing wrong with the code functionally but it is correctly detecting that the sysmon operational channel is missing and causing most windows agents to appear degraded, which we don't want and can't fix prior to the 8.16.0 release.

**Comment by cmacknz** [comment]
https://github.com/elastic/beats/pull/41468/commits/1636258c8ef4218620cc7a1e338247793e98c2ed there was indeed a changelog entry to remove.

**Review by bjmcnic — APPROVED** [review]

**Pull request merged**
