### PR TITLE
Set up logging -> Configure logging

### PR DESCRIPTION
**Pull request by roncohen**
image

### CODE REVIEW

**Comment by dedemorton** [comment]
Sure, looks fine. TBH, I want to do more cleanup on this TOC, but it seems like a low priority. I'm not sure any user will be confused, though maybe you're suggesting "configure" because you think it will be better for SEO?

**Comment by dedemorton** [comment]
Since you are in the files already...I am OK with you fixing the problem everywhere.

**Comment by dedemorton** [comment]
@roncohen Nevermind, I will just merge and fix the consistency later. thanks!

**Comment by roncohen** [comment]
thanks @dedemorton! I agree there are more inconsistencies. I just saw this as i was working to move it into APM docs.

**Pull request merged**
