### PR TITLE
Allow elastic agent in containers to use basic auth to get service token

### LINKED ISSUE #29603: Kibana Fleet setup failed: http POST request to .... fails: Unauthorized
Hi Team,

Today I faced another flaky error while starting the `elastic-package stack up --version 8.0.0-SNAPSHOT`:

```
Attaching to elastic-package-stack_fleet-server_1
[36mfleet-server_1               |[0m Performing setup of Fleet in Kibana
[36mfleet-server_1               |[0m 
[36mfleet-server_1               |[0m Kibana Fleet setup failed: http POST request to http://kibana:5601/api/fleet/setup fails: Unauthorized: <nil>. Response: {"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}
[36mfleet-server_1               |[0m Kibana Fleet setup failed: http POST request to http://kibana:5601/api/fleet/setup fails: Unauthorized: <nil>. Response: {"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}
[36mfleet-server_1               |[0m Kibana Fleet setup failed: http POST request to http://kibana:5601/api/fleet/setup fails: Unauthorized: <nil>. Response: {"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}
[36mfleet-server_1               |[0m Kibana Fleet setup failed: http POST request to http://kibana:5601/api/fleet/setup fails: Unauthorized: <nil>. Response: {"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}
[36mfleet-server_1               |[0m Kibana Fleet setup failed: http POST request to http://kibana:5601/api/fleet/setup fails: Unauthorized: <nil>. Response: {"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}
[36mfleet-server_1               |[0m Kibana Fleet setup failed: http POST request to http://kibana:5601/api/fleet/setup fails: Unauthorized: <nil>. Response: {"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}
[36mfleet-server_1               |[0m Kibana Fleet setup failed: http POST request to http://kibana:5601/api/fleet/setup fails: Unauthorized: <nil>. Response: {"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}
...
[36mfleet-server_1               |[0m Kibana Fleet setup failed: http POST request to http://kibana:5601/api/fleet/setup fails: Unauthorized: <nil>. Response: {"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}
[36mfleet-server_1               |[0m Error: http POST request to http://kibana:5601/api/fleet/setup fails: Unauthorized: <nil>. Response: {"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}
[36mfleet-server_1               |[0m For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.0/fleet-troubleshooting.html
```

```
[36melastic-agent_1              |[0m Kibana fetch policy failed: http GET request to http://kibana:5601/api/fleet/agent_policies fails: Unauthorized: <nil>. Response: {"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}
[36melastic-agent_1              |[0m Kibana fetch policy failed: http GET request to http://kibana:5601/api/fleet/agent_policies fails: Unauthorized: <nil>. Response: {"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}
[36melastic-agent_1              |[0m Kibana fetch policy failed: http GET request to http://kibana:5601/api/fleet/agent_policies fails: Unauthorized: <nil>. Response: {"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}
[36melastic-agent_1              |[0m Kibana fetch policy failed: http GET request to http://kibana:5601/api/fleet/agent_policies fails: Unauthorized: <nil>. Response: {"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}
[36melastic-agent_1              |[0m Error: unable to find policy named ""
[36melastic-agent_1              |[0m For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.0/fleet-troubleshooting.html
```

Failed build is here: https://beats-ci.elastic.co/blue/organizations/jenkins/Ingest-manager%2Felastic-package/detail/PR-633/10/pipeline

### PR DESCRIPTION
**Pull request by michel-laterman**
## What does this PR do?

Allow the agent to use basic auth defined by env vars to retrieve a
service token from Elasticsearch and inject it into the config used for
the agent and fleet.

## Why is it important?

Allow the agent started in a container to use basic auth to contact Elasticsearch and generate a `service_token`.
This should fix the tests which rely on docker-compose.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #29603

### CODE REVIEW

**Comment by michel-laterman** [comment]
Running `elastic-package stack up` with this agent leads to the fleet-server agent starting successfully. However the elastic-agent (without fleet-server) fails to find it's policy. The logs contain:
```
Created service_token named: token-1640912065673
Error: unable to find policy named ""
```

**Comment by simitt** [comment]
Related issue: https://github.com/elastic/fleet-server/issues/1048 where priveleges that are defined on the package level are missing.

**Comment by aleksmaus** [comment]
> It looks like using a `service_token` fails to list policies:

@michel-laterman the fleet service token has full access to the ```.fleet-policies```. In your case you are querying the policies through kibana API, could be a possible defect in Kibana.

**Comment by michel-laterman** [comment]
I can use basic auth to generate a `service_token` via Kibana, and use that token to post to `/api/fleet/setup` and `/api/fleet/agents/setup`.
However the token will return 0 items with `/api/fleet/agent_policies` (no failure status or error messages). And I have confirmed that the token returns items when searching the `.fleet-policies` index in ES.
@joshdover, It looks like this is an issue with the fleet api in Kibana.

**Comment by joshdover** [comment]
@michel-laterman I think I see the problem and I believe it should be addressed by the work in https://github.com/elastic/kibana/pull/121824. Could you confirm that it works against this branch?

If so, I think we'll probably want a more focused PR to fix this for 8.0, which I can prepare.

**Comment by joshdover** [comment]
Went ahead and threw up a focused fix, please test against this one: https://github.com/elastic/kibana/pull/122320

**Comment by michel-laterman** [comment]
Thanks @joshdover, I've confirmed that a service token can now list policies

**Review by blakerouse — APPROVED** [review]
Nicely done! Looks good.

**Pull request merged**
