### PR TITLE
Build Heartbeat for Agent from the OSS directory

### PR DESCRIPTION
**Pull request by jsoriano**
## What does this PR do?

Heartbeat packages both for OSS and X-Pack are built using the magefile in the OSS directory. Use this magefile also when building heartbeat for the Elastic Agent.

It also reverts #20549 as produces [some issues](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fpackaging/detail/PR-20561/2/pipeline/159) when building packages.

## Why is it important?

To use the same magefile when building Heartbeat for Agent, and for the rest of distributions.

## Related issues

- Alternative solution to #20549
- Follows with #20387

### CODE REVIEW

**Comment by ruflin** [comment]
@jsoriano There is an open PR from blake which should fix some tests: https://github.com/elastic/beats/pull/20498 But would this solve the packaging issue?

There is also a PR from @andrewvc to fix things: https://github.com/elastic/beats/pull/20563 Also adding @andrewkroh here.

I think we should have a quick chat today on how to get CI back to green quickly.

**Comment by jsoriano** [comment]
CI should be fixed after https://github.com/elastic/beats/pull/20566, closing this.

**Pull request closed without merging**
