### PR TITLE
Add nightly build for metricbeat

### PR DESCRIPTION
**Pull request by ruflin**
* Update outdated debian dependency links
* Update installing of packer deps to fetch most recent version from remote
* Fix outdated beats config paths

### CODE REVIEW

**Comment by ruflin** [comment]
https://github.com/elastic/beats/pull/1141 should be merged first as it simplifies this PR

**Comment by tsg** [comment]
#1141 is merged now, so this should updated to use the new target.

**Comment by tsg** [comment]
This will fix #1125.

**Comment by ruflin** [comment]
@tsg rebased.

**Pull request merged**
