### PR TITLE
Update go version to 1.16.5

### PR DESCRIPTION
**Pull request by michel-laterman**
## What does this PR do?

Update go version to 1.16.5

## Related issues

- Relates #26182

### CODE REVIEW

**Review by urso — APPROVED** [review]

**Comment by urso** [comment]
the CI failures seem to suggest we don't have the crosscompile containers in place yet.

**Comment by michel-laterman** [comment]
CI failures are because I forgot to change a version number in the golang-crossbuild repo https://github.com/elastic/golang-crossbuild/pull/107

**Review by michalpristas — APPROVED** [review]
approved, tried to rekick build but still failing on the same thing.

**Comment by urso** [comment]
The ARM packaging is currently broken. The failure is to be expected. All other tasks did succeed. Let's force merge, as changes in go mod are an issue as well.

**Pull request merged**
