### PR TITLE
fix packetbeat packaging - exclude darwin/arm64 package

### PR DESCRIPTION
**Pull request by sharbuz**
## What is the problem this PR solves?

Jenkins->Buildkite pipelines migration 

Packetbeat packaging fix

## How does this PR solve the problem?

Exclude darwin/arm64 package from the build because this platform is unsupported

Example of the error:
https://buildkite.com/elastic/beats-packetbeat/builds/1197#018d8e8a-c9cc-4f5f-8e2a-f26fc94ccc7c/421-511

```
>> Building using: cmd='build/mage-linux-amd64 buildGoDaemon', env=[CC=gcc, CXX=g++, GOARCH=amd64, GOARM=, GOOS=linux, PLATFORM_ID=linux-amd64]
--
  | /tmp/ccgSaqPI.o: In function `main':
  | adb73258c8ab: Pull complete
  | Digest: sha256:b28467475b52ee1a5ea108c4bf7041c562b0cea9c065813dac587988a5f36437
  | Status: Downloaded newer image for docker.elastic.co/beats-dev/golang-crossbuild:1.21.7-darwin-debian10
  | >> Building using: cmd='build/mage-linux-amd64 golangCrossBuild', env=[CC=o64-clang, CXX=o64-clang++, GOARCH=amd64, GOARM=, GOOS=darwin, PLATFORM_ID=darwin-amd64]
  | package ran for 1m44.93844247s
  | Error: unsupported cross build platform darwin/arm64
  | 🚨 Error: The command exited with status 1
  | user command error: exit status 1
```

## Related issues

https://github.com/elastic/ingest-dev/issues/1693

### CODE REVIEW

**Review by v1v — CHANGES_REQUESTED** [review]
As far as I see in Jenkins the packaging pipeline for `amd` uses the below platforms:

- https://github.com/elastic/beats/blob/e5000b68245289ddb1404d95c5845bb1a5a39fac/.ci/packaging.groovy#L323-L325

While for arm uses https://github.com/elastic/beats/blob/e5000b68245289ddb1404d95c5845bb1a5a39fac/.ci/packaging.groovy#L259


For instance, this [build](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fpackaging/detail/main/3732/pipeline/131#step-2335-log-209) ran `mage package snapshot packetbeat` with these platforms: `+all linux/amd64 linux/arm64 windows/amd64 darwin/amd64 darwin/arm64`

```
[2024-02-11T09:11:29.919Z] >> Building using: cmd='build/mage-linux-amd64 golangCrossBuild', env=[CC=o64-clang, CXX=o64-clang++, GOARCH=amd64, GOARM=, GOOS=darwin, PLATFORM_ID=darwin-amd64]
[2024-02-11T09:12:40.781Z] >> golangCrossBuild: Building for darwin/arm64
[2024-02-11T09:12:40.781Z] Unable to find image 'docker.elastic.co/beats-dev/golang-crossbuild:1.21.7-darwin-arm64-debian10' locally
[2024-02-11T09:12:41.283Z] 1.21.7-darwin-arm64-debian10: Pulling from beats-dev/golang-crossbuild
```

What's the reason it works in Jenkins but it fails in Buildkite?

**Comment by sharbuz** [comment]
> As far as I see in Jenkins the packaging pipeline for `amd` uses the below platforms:
> 
> * https://github.com/elastic/beats/blob/e5000b68245289ddb1404d95c5845bb1a5a39fac/.ci/packaging.groovy#L323-L325
> 
> While for arm uses
> 
> https://github.com/elastic/beats/blob/e5000b68245289ddb1404d95c5845bb1a5a39fac/.ci/packaging.groovy#L259
> 
> For instance, this [build](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fpackaging/detail/main/3732/pipeline/131#step-2335-log-209) ran `mage package snapshot packetbeat` with these platforms: `+all linux/amd64 linux/arm64 windows/amd64 darwin/amd64 darwin/arm64`
> 
> ```
> [2024-02-11T09:11:29.919Z] >> Building using: cmd='build/mage-linux-amd64 golangCrossBuild', env=[CC=o64-clang, CXX=o64-clang++, GOARCH=amd64, GOARM=, GOOS=darwin, PLATFORM_ID=darwin-amd64]
> [2024-02-11T09:12:40.781Z] >> golangCrossBuild: Building for darwin/arm64
> [2024-02-11T09:12:40.781Z] Unable to find image 'docker.elastic.co/beats-dev/golang-crossbuild:1.21.7-darwin-arm64-debian10' locally
> [2024-02-11T09:12:41.283Z] 1.21.7-darwin-arm64-debian10: Pulling from beats-dev/golang-crossbuild
> ```
> 
> What's the reason it works in Jenkins but it fails in Buildkite?

I'm not sure we mean the same packaging.
In this case, means the `mage package`, and you mentioned the `packaging.groovy` pipeline
Also, I found that the `mage package` returns the mentioned error only in the `7.17` branch.

**Comment by v1v** [comment]
A bit more context about what package means will help with understanding how to review these PRs 🙏 

> In this case, means the mage package, and you mentioned the packaging.groovy pipeline

I don't understand those changes and can not see any errors in any Jenkins pipeline related to the package itself.

Please point out where this particular variable is used in the Jenkins pipeline I cannot find any references about `cross-compile` for `packetbeat` in https://github.com/elastic/beats/blob/main/packetbeat/Jenkinsfile.yml.

In addition, `mage package` should behave similarly in `Jenkinsfile` or `<beat>/Jenkinsfile.yml` and `.ci/packaging.groovy`, this platform [configuration](https://github.com/elastic/beats/blob/e5000b68245289ddb1404d95c5845bb1a5a39fac/Jenkinsfile#L414-L430) and [this other one](https://github.com/elastic/beats/blob/e5000b68245289ddb1404d95c5845bb1a5a39fac/.ci/packaging.groovy#L323-L325) are equally the same and use when running `mage package`

> Also, I found that the mage package returns the mentioned error only in the 7.17 branch.

If the error is only happening in `7.17`, I wonder whether the fix should be done in that branch, as far as I see in https://github.com/elastic/beats/blob/97682f1af1a471efa75aa3913a9d971cf18eb9e9/Jenkinsfile#L413-L431 is not used , that's likely there are no failures in Jenkins for the `7.17`.

**Comment by sharbuz** [comment]
opened another [PR](https://github.com/elastic/beats/pull/37969) to 7.17, @v1v , let's discuss the changes in that PR.

**Pull request closed without merging**
