### PR TITLE
Remove prev-minor testing as not needed anymore

### PR DESCRIPTION
**Pull request by ruflin**
In https://github.com/elastic/beats/issues/26629 the issue around running Filebeat against older version of Elasticsearch was discussed and in https://github.com/elastic/beats/pull/28274 testing against the previous minor was introduced. But since 8.0, Filebeat can only ship data to equal or newer versions of Elasticsearch. Because of this, in the tests `TESTING_FILEBEAT_ALLOW_OLDER=1` had to be introduced.

I'm opening this PR to remove this testing as it is not something we support anymore.

### CODE REVIEW

**Comment by andresrc** [comment]
I understand this would not be backported to 7.x.

**Comment by ruflin** [comment]
No plans to backport at all.

**Review by andrewkroh — APPROVED** [review]
Removing this check seems aligned to the language in the support matrix (though I would have preferred stronger language for a contract such that it was required rather than "highly recommended").

Screen Shot 2022-03-23 at 12 23 02

And then users also would need to set `allow_older_versions: true` (https://www.elastic.co/guide/en/beats/filebeat/8.1/elasticsearch-output.html#_allow_older_versions) to be able to get into a situation where these's test would have caught the problem.

There's a bunch of [code](https://github.com/elastic/beats/blob/0c1b760eea1bd0c77bd029f3e10a320aae87ce88/filebeat/fileset/compatibility.go) that that makes pipeline configs backwards compatible with earlier ES version. That's now eligible for removal.

**Comment by ruflin** [comment]
@nimarezainia I'm also surprised by the phrasing. Can you take a look at this?

@andrewkroh I'll get the PR merged. It is great to hear that it will actually simplify some of our code. As all the checks are for 7.x it seems we can get rid of all? Will you follow up or should the data plane team take care of it?

**Comment by nimarezainia** [comment]
> @nimarezainia I'm also surprised by the phrasing. Can you take a look at this?
> 
> @andrewkroh I'll get the PR merged. It is great to hear that it will actually simplify some of our code. As all the checks are for 7.x it seems we can get rid of all? Will you follow up or should the data plane team take care of it?

sure I can change that. I worded it that way mainly because there is a "public" config that allows the user to over write.  So clearly we are not that strict :-)

**Comment by ruflin** [comment]
The config we have is experimental and we discourage it from using it. "Highly recommended" sounds to me like we would support the config option, but we don't.

**Pull request merged**
