### PR TITLE
Change format of exported fields content

### PR DESCRIPTION
**Pull request by dedemorton**
This PR updates the generate_fields_docs.py to make the layout of the reference content easier to read. It uses definition lists instead of sections to format the options. This makes the content easier to scan, and it makes the "On this page" section more useful.

Here's an example. I'm still not happy with repeated section names, but this PR at least makes the content easier to read.

image

### CODE REVIEW

**Comment by ruflin** [comment]
@dedemorton Thanks for the screenshot. Looks like your PR needs rebased. Will merge as soon as it's green.

For the titles: Let's sync up on what we can / should do here. I have some ideas.

**Comment by dedemorton** [comment]
@ruflin Rebased. Should be ready to merge as soon as tests are done.

**Comment by ruflin** [comment]
@dedemorton Seems like rebase was not enough, you have to run `make fmt` and then probably `make update` again.

**Comment by dedemorton** [comment]
@ruflin I tried `make fmt` followed by `make update` but it didn't result in any changes.

**Comment by ruflin** [comment]
@dedemorton In which directory did you run `make fmt`. I get a diff in libbeat.

**Comment by dedemorton** [comment]
@ruflin I tried *all the directories*. I think my environment is kind of messed up, though, because I've been running into other weird issues. I've given you push access to my fork in case you want to try pushing the fix yourself

**Comment by ruflin** [comment]
@dedemorton I opened https://github.com/elastic/beats/pull/6811

**Comment by ruflin** [comment]
@dedemorton Closing as https://github.com/elastic/beats/pull/6811 was merged.

**Pull request closed without merging**
