### PR TITLE
[MetricBeat] Add up metric for health status

### PR DESCRIPTION
**Pull request by premendrasingh**
Enhancement: This PR adds **up** metric to metrics scraped from host. It will be useful for instance availability monitoring.
Sample metric:
`up{job="prometheus",instance="localhost:8080"} 1`

### CODE REVIEW

**Comment by exekias** [comment]
Thank you so much for contributing :tada: ! This PR looks good to me. Could you please check the lint errors? `mage fmt` would probably fix this.

**Comment by premendrasingh** [comment]
@exekias fixed lint error. Thanks for the suggestion.

**Comment by exekias** [comment]
Tests seem to be failing, we use some golden files to test the output of the module, you can update them with this command:

```
go test github.com/elastic/beats/metricbeat/module/prometheus/collector -data
```

**Comment by exekias** [comment]
sorry, wrong button :innocent:

**Comment by premendrasingh** [comment]
Executed 
   go test github.com/elastic/beats/metricbeat/module/prometheus/collector -data
Thanks for the suggestion.

**Comment by exekias** [comment]
ok to test

**Comment by premendrasingh** [comment]
Thanks a lot @exekias

**Comment by exekias** [comment]
Thank you!!

**Pull request merged**
