### PR TITLE
filebeat returns error if meta.json exists but is empty (no UUID)

### PR DESCRIPTION
**Pull request by JHerget**
In [beat.go](https://github.com/elastic/beats/blob/master/libbeat/cmd/instance/beat.go) line 639 is where the function that handles meta.json and the UUID starts. Everything works perfectly if meta.json doesn't exist on startup because it will just get created. If it already exists then everything gets handled correctly as well. The problem comes if meta.json exists but is empty (no UUID). Instead of creating a UUID and putting it in the empty meta.json file, an error is returned (line 656). This pull request changes one simple thing: it checks if the size of meta.json is 0. If the size is not 0 then it continues like it normally does (checking the UUID). If the size is 0 then it skips checking the UUID and creates a new UUID and adds it to the empty meta.json

This problem was brought to my attention when using filebeat on a raspberry pi. Once the image with filebeat is installed on the pi, it would occasionally create an empty meta.json file on the first startup.

### CODE REVIEW

**Comment by ph** [comment]
> This problem was brought to my attention when using filebeat on a raspberry pi. Once the image with filebeat is installed on the pi, it would occasionally create an empty meta.json file on the first startup.

I would like to understand why we have an empty file on disk, is there any log with an error?  Looking a the code I assume the only way an empty file could be created by  Filebeat is because it was killed before encoding the JSON or there is an error when encoding to json, the later is less likely because there is not a lot of variance on the data.

**Comment by JHerget** [comment]
> I would like to understand why we have an empty file on disk, is there any log with an error? Looking a the code I assume the only way an empty file could be created by Filebeat is because it was killed before encoding the JSON or there is an error when encoding to json, the later is less likely because there is not a lot of variance on the data.

There was not an error logged while encoding the json. I assume it was because Filebeat was killed before encoding the json

**Comment by JHerget** [comment]
I know that this error happens only on the first startup of the newly imaged pi, but I have only been able to recreate the issue a few times. I haven't been able to recreate it since posting this PR. It takes around 5-10 minutes to run one test and I've done about a 15-18 tests with 1 successful recreation of the problem. That was just before posting the PR.

**Comment by ph** [comment]
jenkins test this please

**Comment by elasticcla** [comment]
Hi @JHerget, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/beats/pull/8858.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by JHerget** [comment]
I can't find anything online about the error the CI is returning. Am I missing something?

**Comment by JHerget** [comment]
Today I found this same bug happening on an Ubuntu 16.04 machine. I still have not been able to consistently replicate this error, however, I believe that maybe the code that moves the temp meta file to the actual meta file is not always atomic.

**Pull request closed without merging**
