### PR TITLE
Docs additions & fixes

### PR DESCRIPTION
**Pull request by ruflin**
* Fix broken CHANGELOG links through escaping as asciidocs magically converted ...
* Define Golang Version
* Add note to first publish questions / issues on discuss

### CODE REVIEW

**Comment by tsg** [comment]
This looks broken when I try to build it on my computer:

screen shot 2016-01-04 at 10 30 20

But it works in the 1.0.1 branch, so I think there was a lost cherry pick. I'll look into it.

**Comment by ruflin** [comment]
@tsg Thanks. Let me know if I can help somehow.

**Comment by ruflin** [comment]
This will have to be rebased as soon as #613 was also merged into master.

**Comment by ruflin** [comment]
@tsg Closing this PR as I opened the independent part of the PR here: https://github.com/elastic/beats/pull/669 

For the docs link update I suggest to do it when we merged 1.1 into master to not have any wierd behaviour (which I currently have on rebase ...)

**Pull request closed without merging**
