### PR TITLE
Added example for SSL

### PR DESCRIPTION
**Pull request by robin13**
Clarification exactly where the SSL details should be put in the configuration

### CODE REVIEW

**Comment by exekias** [comment]
Thank you for opening this, I'm afraid that part is autogenerated :/

What would you think about adding SSL parameters to default config? We can put them there, commented out https://github.com/elastic/beats/blob/master/metricbeat/module/kubernetes/_meta/config.yml

**Comment by robin13** [comment]
Yes - that would be a good compromise.

**Comment by ruflin** [comment]
@robin13 Let me know when you find some time to copy over your changes to the file proposed by @exekias and then run `make update`. You will see that the second file has the same changes inside as it's auto generated.

**Comment by ruflin** [comment]
Closing in favor of https://github.com/elastic/beats/pull/6558 . Thanks @robin13 for bringing this up.

**Pull request closed without merging**
