### PR TITLE
Backport of #1375

### LINKED ISSUE #1281: Filebeat 1.1.2 does not record correct inode values of rotated logs on exit
From the discussion at https://discuss.elastic.co/t/filebeat-1-1-2-does-not-record-correct-inode-values-of-rotated-logs-on-exit/45749

I am seeing filebeat re-ship rotated log files when the filebeat service restarts.

We are experiencing the problem on a local ext4 file system on Ubuntu 14.04 running in AWS EC2.

While filebeat remains running, it is correctly processing the files. The problem is that when it persists its state to the registry file, it is persisting the older inode values of the files before they were rotated, not the inodes of the files at those paths at the time filebeat exited.

I have created a basic configuration and bash script which starts filebeat, writes to a log file, rotates it a couple of times (with pauses in between to allow filebeat to notice) and then stops filebeat.

Full repro script, conf, and output log available as a gist:
https://gist.github.com/jstangroome/a1a70306cbd7a9420be15ec2bbe109a0

After filebeat stops, the registry has persisted the wrong inodes for the log files present on disk. As such, when filebeat starts again, an existing log file will appear to be a new file without an existing offset and its contents will be shipped a second time.

My repro script was run on a local ext4 file system on Ubuntu 14.04 running in a Virtualbox VM.

This might be an edge case not handled in https://github.com/elastic/beats/issues/1010

### PR DESCRIPTION
**Pull request by ruflin**
A direct commit backport was not possible as too many things changed in the prospector and harvester

Closes #1281

### CODE REVIEW

**Comment by ruflin** [comment]
@jstangroome Backport of #1281 to 1.2

**Comment by aellisv** [comment]
Was this released in filebeats 1.2?

I am running filebeat 1.2 on centos 6.7.  I have filebeats harvesting logs that are compressed after 1 week and dropped after 1 month.  I am seeing records dropped or cutoff from the front and I'm seeing filebeat log messages that include:

2016-04-25T22:25:42Z INFO Old file with new name found: /opt/openet/FW/data/edr/output/DC1-PCRF-03_20160417222039.edr is no /opt/openet/FW/data/edr/output/DC1-PCRF-03_20160425222041.edr
2016-04-25T22:25:42Z INFO Detected rename of a previously harvested file: /opt/openet/FW/data/edr/output/DC1-PCRF-03_20160417222039.edr -> /opt/openet/FW/data/edr/output/DC1-PCRF-03_20160425222041.edr

I have:
ignore_older: 2h
close_older: 2h

**Comment by ruflin** [comment]
@aellisv which version of 1.2.x are you using?

**Comment by aellisv** [comment]
The package was: filebeat-1.2.1-x86_64.rpm

[andy.ellis@aellis01 ~]$ filebeat --version
filebeat version 1.2.1 (amd64)

**Comment by ruflin** [comment]
@aellisv The backport will be released potentially today in 1.2.2

**Comment by aellisv** [comment]
Thank you.

**Pull request merged**
