### PR TITLE
[Metricbeat] migrate nginx module to ReporterV2 error

### PR DESCRIPTION
**Pull request by berfinsari**
See elastic/beats#11374 and elastic/beats#10727

### CODE REVIEW

**Comment by ruflin** [comment]
jenkins, test this

**Comment by fearful-symmetry** [comment]
@ruflin Do we need to change whatever test harness is using the nginx moule?

**Comment by fearful-symmetry** [comment]
https://github.com/elastic/beats/blob/6bff9a64b4f18101f62842a9885b2c904ce45c6b/metricbeat/tests/system/test_cmd.py#L141

Did we just hard-code expected error values into the testing framework? The error body that's returned also seems completely different, but I could be reading the CI logs wrong.

**Comment by ruflin** [comment]
@fearful-symmetry Yes, we need to adjust these tests. For the hardcoded errors: Yes, they are there :-) I think the issue is that now the errors are on the INFO level and not ERROR level anymore.

**Comment by fearful-symmetry** [comment]
Ah, it looks like it's not a log level problem, just the addition of `errors.Wrap` that conflicts with what the test is looking for? We have the assert looking for:

```
 self.log_contains("ERROR error making http request"), 
```

and our new output from travis is:

```
ERROR error in http fetch: error making http request: Get http://errorhost:80/server-status: lookup errorhost: no such host
```

So the problem is just the `error in http fetch` 

@berfinsari I think the solution is just to update `test_cmd.py` with the new string introduced by `errors.Wrap()`

**Comment by fearful-symmetry** [comment]
@berfinsari Do you still want to work on this?

**Comment by sayden** [comment]
Ping @berfinsari :slightly_smiling_face: 

Don't feel pressed. It's perfectly ok if you don't have time now, anyone else can continue with this :wink:

**Comment by sayden** [comment]
Merged already in https://github.com/elastic/beats/pull/13518

Thanks for the help anyways, @berfinsari :slightly_smiling_face:

**Pull request closed without merging**
