### PR TITLE
Improve close_timeout logging

### PR DESCRIPTION
**Pull request by ruflin**
Closes https://github.com/elastic/beats/issues/4512

### CODE REVIEW

**Comment by andrewkroh** [comment]
There's a data race in two tests ([test report)](https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-windows/518/testReport/). Here's the [log file](https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-windows/518/beat=filebeat,label=windows/artifact/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_harvester.Test.test_close_timeout/filebeat.log/*view*/).

**Comment by ruflin** [comment]
Argh, it's probably the reason I didn't put in the logging in the first place :-( 

@ppf2 Seems like this could be more complex then initially thought.

**Comment by tsg** [comment]
@ruflin what should we do with this PR?

**Comment by ruflin** [comment]
@tsg I still think it would be nice to have this "logging" in but it probably requires some refactoring on a delicate part of filebeat to make it happen without a race condition. I would keep the PR open as a reminder but not set priority on it to get it in.

**Comment by ruflin** [comment]
@tsg @ppf2 Seems like I found a rather simple solution. The only trade off is that the "old" name is reported in case of file rotation but I think that is ok.

Mac CI somehow had a hick up not related to this change.

**Pull request merged**
