### PR TITLE
Add parsing for 434001 and 434003

### PR DESCRIPTION
**Pull request by lukerucks**
## What does this PR do?
This PR adds parsing for Cisco ASA 434001 and 434003 using the precise style currently used for parsing Cisco ASA 434002.

## Why is it important?
We need parsing for ASA 434001, 434002, and 434003; right now only 434002 is supported, despite the others being substantially similar dissections.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~ 
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally
The PR uses the patterns specified here: https://www.cisco.com/c/en/us/td/docs/security/asa/syslog/b_syslog/syslog-messages-400000-to-450001.html#con_7199521.
For testing the actual messages, these are sample logs:
For 434001:
<13>Apr 26 2022 10:24:37: %ASA-4-434001: SFR card not up and fail-close mode used, dropping TCP packet from outside:54.239.28.85/443 to Inside:10.12.128.89/57388

For 434003:
<13>May 30 2019 09:18:59: %ASA-4-434003: SFR requested to reset TCP connection from outside:54.239.28.85/443 to Inside:10.12.128.89/57388

Ideally a test would send these messages through filebeat with the Cisco ASA module enabled, although in this case the change is small enough to be visually inspected and compared with the working 434002 dissection that neighbors the changes and the Cisco specified log patterns from https://www.cisco.com/c/en/us/td/docs/security/asa/syslog/b_syslog/syslog-messages-400000-to-450001.html#con_7199521.

### CODE REVIEW

**Comment by adriansr** [comment]
Hi @lukerucks ,

Thanks for your contribution.

For us to proceed you need to [sign the CLA.](https://www.elastic.co/contributor-agreement)

**Comment by lukerucks** [comment]
Hi @adriansr, I've signed the CLA with DocuSign; do I need to do anything else to show that I've signed it?

**Review by adriansr — COMMENTED** [review]
(mistake)

**Pull request merged**
