### PR TITLE
Update filebeater to not use dot imports — GoLint

### PR DESCRIPTION
**Pull request by kkirsche**
GoLint says not to use dot imports when importing libraries as it makes it harder to easily know where you should be modifying code if you attempt to contribute. For this reason, this removes the dot imports of crawler and input.

https://github.com/golang/lint

X-Ref: #990

### CODE REVIEW

**Comment by ruflin** [comment]
LGTM. Glad you cleaned up the . imports.

**Comment by andrewkroh** [comment]
There are a few compile errors in the Travis output. @kkirsche can you please take a look at those.

**Comment by kkirsche** [comment]
@andrewkroh will do. Was just a quick run on laptop at Elastic{on} — I'll get that fixed up.

**Comment by kkirsche** [comment]
Pushed fix. Test passed on my laptop:
```shell
~/D/b/filebeat ❯❯❯ go test
PASS
ok  	_/Users/<username>/git/beats/filebeat	0.011s
```

**Comment by kkirsche** [comment]
Travis passing :+1:

**Comment by ruflin** [comment]
@kkirsche Could you squash the two commits into one?

**Comment by kkirsche** [comment]
Squashed.

**Comment by ruflin** [comment]
jenkins, test it

**Pull request merged**
