### PR TITLE
Update getting started to include link to apt and yum repositories

### PR DESCRIPTION
**Pull request by dedemorton**
Closes https://github.com/elastic/topbeat/issues/135. Added the link to the getting started topics for Topbeat, Filebeat, and Packetbeat.

### CODE REVIEW

**Comment by ruflin** [comment]
@dedemorton I'm thinking if we perhaps should make this even more obvious in the future and not put it under "others" as people using the packages are also interesting for us as they can easily update the newest versions.

**Comment by dedemorton** [comment]
@ruflin I see your point. I was trying to find a place where the info logically belonged, so I added it to the note and thought a note heading might help set off the info better. But at the end of the day, maybe that's just more text for users to process.  How about something like the following?

Note:
If you use Apt or Yum, you can [install Packetbeat from our repositories] http://www.elastic.co/guide/en/beats/libbeat/1.1/setup-repositories.html to update to the newest version more easily. 

See the [download page] https://www.elastic.co/downloads/beats/packetbeat for other installation options, such as 32-bit images.

**Comment by ruflin** [comment]
I prefer this version as I think the repos are more important than the 32-bit. It would also be interesting to check the analytics on how often these links are actually clicked afterwards.

Doing a quick google search it probably is a good thing to have a sub page for it: https://www.google.ch/webhp?sourceid=chrome-instant&ion=1&espv=2&ie=UTF-8#q=filebeat+apt+package

**Comment by monicasarbu** [comment]
+1 for the Nicolas proposal

@ruflin That's a good point. Let's discuss it in a different thread how we can improve the download page to include apt/yum details.

**Pull request merged**
