### PR TITLE
Feature/improve tests syntax

### PR DESCRIPTION
**Pull request by bgvladedivac**
## What does this PR do?

A small improvement short handing the assignment and incremental.

## Why is it important?

It creates a shorter and more pythonic statement, while maintaining the semantics of it.

## Checklist

- [ x] My code follows the style guidelines of this project
- [ x] I have made corresponding changes to the documentation
- [ x] I have made corresponding change to the default configuration files
- [ x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by bgvladedivac** [comment]
Just signed the Contributor agreement.

**Comment by pierrehilbert** [comment]
Hello,
Thanks for your suggestion.
Could you please change the changelog to add it to `CHANGELOG-developer.next.asciidoc` instead?
This change won't be visible for our users so it would be better to have it only for developers.

**Comment by bgvladedivac** [comment]
@pierrehilbert just added the change to the proper file.

**Review by pierrehilbert — APPROVED** [review]

**Comment by pierrehilbert** [comment]
Thx @bgvladedivac

**Pull request merged**
