### PR TITLE
Forward port 7.12.0 changelog to master

### PR DESCRIPTION
**Pull request by andresrc**

### CODE REVIEW

**Comment by andresrc** [comment]
We are removing a lot fewer lines that I would expect. @urso should we merge this as is and look for a cleanup of the changelog in a follow up?

**Comment by bmorelli25** [comment]
Agh, I messed that up. Give me a few mins to fix

**Review by bmorelli25 — APPROVED** [review]
I think I found them all

**Comment by andresrc** [comment]
@bmorelli25 thank you very much!

**Pull request merged**
