### PR TITLE
Extract the Dissect test suite into an external file

### PR DESCRIPTION
**Pull request by ph**
We currently have three implementations of dissect (LS, Ingest
and beats), moving the common test case to an external file is the first
step to be able to converge to a common specification.

cc @guyboertje @jakelandis

### CODE REVIEW

**Comment by jakelandis** [comment]
LGTM

**Comment by ph** [comment]
jenkins test this please

**Comment by urso** [comment]
With the go test suite its common to put input files into a testdata sub-directory.

According to `go help test`:

> The go tool will ignore a directory named "testdata", making it available
to hold ancillary data needed by the tests.

**Comment by ph** [comment]
@urso I've moved the fixture into `testdata`

**Pull request merged**
