### PR TITLE
Update heartbeat-deployment.yaml

### PR DESCRIPTION
**Pull request by nbarnes22**
Fixed memory in resources.limits.memory so that Kubernetes deployment doesn't break. 
resources:
          limits:
            memory: 1536Mi

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by rdner** [comment]
@nbarnes22 please sign the CLA before we proceed.

**Comment by nbarnes22** [comment]
> @nbarnes22 please sign the CLA before we proceed.

Done!

**Comment by rdner** [comment]
@nbarnes22 there are some generated files that have to be updated after this change.

Please run `make -C deploy/kubernetes all` or change `./deploy/kubernetes/heartbeat-kubernetes.yaml` manually.

**Review by gizas — APPROVED** [review]

**Review by rdner — CHANGES_REQUESTED** [review]
@nbarnes22 there are some generated files that have to be updated after this change.

Please run `make -C deploy/kubernetes all` or change `./deploy/kubernetes/heartbeat-kubernetes.yaml` manually.

**Comment by jlind23** [comment]
Dear contributor, thank you so much for all the energy you put into this PR and we hope that it can be finalized soon.
Until then, as there were no recent updates we will close it in order to keep the repository more manageable for us the maintainers.
Please reopen it as soon as you have time to finish your contribution.

**Pull request closed without merging**
