### PR TITLE
[Metricbeat][Kibana][status] `metrics` is optional

### PR DESCRIPTION
**Pull request by afharo**
## What does this PR do?

Kibana might not return the `metrics` property to the `/api/status` request. This PR makes that property optional in the schema.

## Why is it important?

In https://github.com/elastic/beats/pull/20772, we've noticed some flaky tests. These changes will make Metricbeat more resilient.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have made corresponding change to the default configuration files
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## How to test this PR locally

I'd say we can make it work if in the test environment, Kibana takes longer than 1 minute to start, we've seen than the first `green` `/api/status` response might not contain the metrics data (it can take Kibana up to 5s to populate it after the startup).

## Related issues

- Relates #20772

### CODE REVIEW

**Review by ycombinator — APPROVED** [review]
LGTM.

**Comment by afharo** [comment]
@ycombinator I noticed the team @elastic/kibana-platform is planning to migrate this endpoint to Kibana's New Platform and `metrics` should exist in every response in the next release. Should we still go ahead and merge this PR?
https://github.com/elastic/kibana/pull/76054

**Comment by ycombinator** [comment]
@afharo In that case let's not merge this PR.

**Comment by afharo** [comment]
I'll double confirm with them and will come back.

**Comment by ycombinator** [comment]
> I'll double confirm with them and will come back.

@afharo Any news here?

**Comment by afharo** [comment]
Yes, @joshdover is working on https://github.com/elastic/kibana/pull/76054 (that triggered https://github.com/elastic/kibana/pull/76730). Both PRs should eventually ensure `metrics` are always available.
He mentioned to me he'd close this PR once he's done with the changes and can confirm the expected behaviour 🙂 Sorry I didn't share the news with you.

**Comment by afharo** [comment]
The fix in Kibana has been merged! https://github.com/elastic/kibana/pull/76054

Closing this PR.

**Pull request closed without merging**
