### PR TITLE
Fix links to Beats product pages

### LINKED ISSUE #24776: Beats docs have a broken link to packetbeat on 'what are beats' overview page
for both 7.12 and master, this page on our main elastic site has a broken link, from Beats repo docs:
https://www.elastic.co/guide/en/beats/libbeat/current/beats-reference.html

That URL maps to this:
https://github.com/elastic/beats/blob/master/libbeat/docs/overview.asciidoc

and in this... the link for packetbeat is broken.  The file doesn't exist so it throws a 500 error.  
The link points to:
https://www.elastic.co/products/beats/packetbeat

where I believe want it to resole to:
https://www.elastic.co/downloads/beats/packetbeat

I'm sure it is a short-link or otherwise dynamically controlled so I'm not sure who owns that or where it is etc.

Screen Shot 2021-03-25 at 8 26 56 PM

### PR DESCRIPTION
**Pull request by dedemorton**
# What does this PR do?

Updates base URL used for links to the Beats product pages. 

## Why is it important?

Relying on the redirects is problematic because they can cause issues with SEO if there are multiple redirects in place.

## Checklist

- [x] My code follows the style guidelines of this project

## Related issues

- Closes elastic/beats#24776

### CODE REVIEW

**Review by bmorelli25 — APPROVED** [review]

**Comment by dedemorton** [comment]
jenkins run the tests please

**Comment by dedemorton** [comment]
jenkins run the tests please

**Comment by dedemorton** [comment]
jenkins run the tests please

**Comment by dedemorton** [comment]
jenkins run the tests please

**Comment by dedemorton** [comment]
^ trying to get a clean build. I've been trying for over a week. Very frustrating.

**Pull request merged**
