### PR TITLE
An initial and basic FIX protocol implementation

### PR DESCRIPTION
**Pull request by calston**
A first initial pass at implementing FIX protocol support as per issue #170

This is not at all ready to merge but hopefully, this is a good starting point for people to contribute real-world requirements as the FIX protocol specifications are ridiculously broad. 

**TODO:**
- [ ] Tests
- [ ] Nested FIX packets / array-like fields
- [ ] Support for other FIX versions / bespoke oddities
- [ ] A better output field set for constructing dashboards
- [ ] Example configuration

### CODE REVIEW

**Comment by tsg** [comment]
This is great! I suggest adding some python system tests, those are typically pretty easy to write, if you have some sample PCAP files. Let us know if you have any questions on how that works.

**Comment by calston** [comment]
The current new protocol documentation is exceptionally outdated. I can't make any sense of the new plugin registration without any documentation  :(

**Comment by fkgre** [comment]
+1

**Comment by fkgre** [comment]
anyupdate?

**Comment by mgvazquez** [comment]
+1

**Comment by mostlyjason** [comment]
It looks like there hasn't been any progress on this issue in a while. It looks like it was intended as a starting point and not a complete enhancement. I'm going to close this for now, but feel free to reopen if you'd like to keep working on it.

**Pull request closed without merging**
