### PR TITLE
Fix base64 decode processor

### PR DESCRIPTION
**Pull request by kvch**
Previously, `base64_decode_field` was broken in libbeat. The user was not able to configure the processor correctly, so the configuration would be parsed.

### CODE REVIEW

**Comment by kvch** [comment]
Failing tests are unrelated.

**Comment by guyromb** [comment]
Seems like moving the from/to under field are breaking the functionality - unable to read the specified key in config.
"failed to decode base64 fields in processor: could not fetch value for key: , Error: key not found"

**Comment by guyromb** [comment]
https://github.com/elastic/beats/pull/13144

**Comment by kvch** [comment]
This PR was not released in 7.3. It's going to be released in 7.3.1.

**Pull request merged**
