### PR TITLE
[WIP] Clarify capabilities of the Filebeat auditd module

### PR DESCRIPTION
**Pull request by rwaight**
Update `filebeat/docs/modules/auditd.asciidoc` - Add note regarding capabilities of the Filebeat auditd module

## What does this PR do?

Update Filebeat auditd module documentation

## Why is it important?

Clarify capabilities of the Filebeat auditd module

## Checklist

~~- [ ] My code follows the style guidelines of this project~~
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~

## Author's Checklist

- [ ]

## Related issues
* Closes https://github.com/elastic/beats/issues/17094
* Related to https://github.com/elastic/beats/issues/6484

### CODE REVIEW

**Comment by dedemorton** [comment]
Hope you don't mind me commenting on this draft-level PR. The CI intake job is failing because you've updated a generated file. You need to update this file instead: beats/filebeat/module/auditd/_meta/docs.asciidoc

Then run `make update` in the `beats` directory.

If you don't have your development environment set up, I can always run the update and push it to your branch. (I'm on vacation next week, though, so remind me when I'm back.)

**Comment by rwaight** [comment]
Hey @dedemorton, sorry I forgot about this one and do not have a dev environment.  As mentioned in https://github.com/elastic/beats/pull/17068#issuecomment-601848231, would you be able to update the branch for me?

**Comment by dedemorton** [comment]
So I made a little edit to your text, but it's weird because my second edit didn't get picked up by the update script. Anyhow, I'll figure out what's wrong and push another commit soon.

**Comment by dedemorton** [comment]
jenkins run the tests please

**Pull request merged**
