### PR TITLE
Update state_container to latest kube-state-metrics version

### LINKED ISSUE #6638: metricbeat state_container kube_pod_container_status_restarts -> kube_pod_container_status_restarts_total
Looks like this might have been renamed: https://github.com/kubernetes/kube-state-metrics/blob/release-1.2/Documentation/pod-metrics.md

### PR DESCRIPTION
**Pull request by exekias**
This PR updates state_container metricset to latest kube-state-metrics version:

- Support renamed total restarts field
- Add termination/waiting reason field

Closes #6638 #6639

### CODE REVIEW

**Comment by exekias** [comment]
I kept old fields lowercase, for two reasons: they are mostly 1 word + we avoid a breaking change. The field that keeps case are new with this PR (`kubernetes.container.status.reason`), they have normally more than one word: `ContainerCreating`, `CrashLoopBackoff`, `ErrImagePull`... Lowercase looks really awful there.

I rebased and added a changelog :)

**Comment by ruflin** [comment]
jenkins, test it

**Comment by ruflin** [comment]
jenkins, test this

**Comment by f0** [comment]
@ruflin @exekias   is this in 6.3.2?

**Comment by ruflin** [comment]
This didn't make it into the 6.3 release but it will be in the upcoming 6.4 release.

**Pull request merged**
