### PR TITLE
Add Linux support to make update

### LINKED ISSUE #449: update.sh cannot be run on ubuntu
There is a `sed` difference between linux and bsd ... see http://stackoverflow.com/a/5694430/433662.

I cannot run `make update` because of the `sed` difference.

### PR DESCRIPTION
**Pull request by mrkschan**
Resolve #449

### CODE REVIEW

**Comment by ruflin** [comment]
@mrkschan Tested the version you pushed a few seconds ago on OS X and it seems to work :+1:

**Comment by mrkschan** [comment]
@ruflin could you run it again on OSX? I changed `'` to `"` in the `sed` argument.

**Comment by ruflin** [comment]
@mrkschan That is the version I already tested. With ' it didn't replace the variables. With " it works.

**Comment by ruflin** [comment]
@mrkschan Thanks for the fix.

**Pull request merged**
