### PR TITLE
Remove docker and kubernetes tests and metadata for AIX

### PR DESCRIPTION
**Pull request by Helflym**
## What does this PR do?

This PR disables tests based on docker or kubernetes features for AIX. 
It also forces docker and kubernetes to be disable by mage configuration files. 

## Why is it important?

Docker doesn't work on AIX thus tests or anything else linked to it shouldn't be made on AIX. 

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~~I have made corresponding changes to the documentation~~
- [x] I have made corresponding change to the default configuration files
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~

## Author's Checklist

- [ ]

## How to test this PR locally

This is only aimed to be tested on AIX, but the part disabling the tests can be tried on any OS by changing the uname condition. 

## Related issues

- Related elastic/beats#15785

### CODE REVIEW

**Comment by urso** [comment]
LGTM. Unfortunately you have a merge conflicts. Can you rebase please? Will start an internal CI process once the merge conflict is resolved.

**Comment by kvch** [comment]
jenkins test this

**Comment by rdner** [comment]
@Helflym very sorry for a long wait. Could you please merge/rebase the current `main` branch?

**Comment by rdner** [comment]
@mergifyio update

**Comment by rdner** [comment]
I'll merge this PR without addressing linter issues, since it's a long pending PR.

**Comment by Helflym** [comment]
Thanks for merging it. However, I'm no longer working on AIX thus I cannot test it. But as Docker is still not available on AIX it should be useful anyway.

**Pull request merged**
