### PR TITLE
Add nats dashboard

### PR DESCRIPTION
**Pull request by ChrsMark**
This PR adds an overview dashboard for `nats` module as proposed on  #10071. 

Co-Authored-By: Stamatis Katsaounis <katsaouniss@gmail.com>
Co-Authored-By: Michael Katsoulis <michaelkatsoulis88@gmail.com>

### CODE REVIEW

**Comment by ChrsMark** [comment]
screenshot from 2019-01-21 12-47-24

@ruflin here is something we created. 

TBH I'm not confident enough about the beauty of the dashboard, but this is the overview we find meaningful for our purposes.

**Comment by ruflin** [comment]
Thanks, this is great. I'm good with the dashboards as is but still need to test it on my end.

Some suggestions: 

* Should we use one box per number instead of multiple in one box?
* It seems Kibana does not know it's a byte value. Probably we are missing `format: bytes` somewhere in the `fields.yml`. If we have this in, Kibana would convert the value to MB / KB etc. which would be nicer I think.

**Comment by ChrsMark** [comment]
Nice! Will update it according to the suggestions!

**Comment by sayden** [comment]
Hi @ChrsMark :slightly_smiling_face: Amazing contribution, dashboards are very important for each module.

I think the dashboard wasn't exported correctly. I get this when trying to open it:

image

Also, I cannot open each visualization. It just hangs when I clicked them, first time I see something similar.

Can you tell us how did you export the dashboard? 

Thanks!

**Comment by ChrsMark** [comment]
Finally I made it work smoothly with `MODULE=nats ID=c359a6c0-1e45-11e9-a1b4-79a7ae42ab61 mage exportDashboard`, @sayden

**Comment by ChrsMark** [comment]
I think most comments addressed!

screenshot from 2019-01-23 01-03-04

**Comment by ruflin** [comment]
As https://github.com/elastic/beats/pull/10249 was merged this will require a rename of the dir `6` to `7`.

**Comment by sayden** [comment]
Awesome @ChrsMark The chart can be loaded already.

As a general workflow, a user will load the dashboard by doing the setup with `metricbeat setup`. All dashboards are loaded into Kibana with this command. This is the workflow that must be tested to ensure everything is working when importing the dashboard.

Few minor things left that I didn't see/realized before (sorry):
- A description on the dashboard is missing.
- The names of the visualizations don't follow naming conventions. For example _NATS IO_ should be _IO [Metricbeat NATS]_. _Nats Memory_ should be _Memory [Metricbeat NATS]_. Take a look at the rest of visualization charts to see more examples. You did it correctly with the dashboard :+1: 

Finally, but I'm not fully sure why, some index patterns are missing. I don't have any good suggestion:
- Check that the metricbeat binary was updated before exporting.
- Check that all `fields.yml` files are in sync and updated before exporting.
- The script you used to export is the good one. Just in case there's another script to update here: https://github.com/elastic/beats/blob/master/dev-tools/cmd/dashboards/export_dashboards.go

image


@ruflin do you have any idea of why some of the index pattern fields have not been uploaded?

**Comment by sayden** [comment]
To fix the conflicts you'll need to rebase over master and then push the changes in those files after running `make update`

**Comment by skatsaounis** [comment]
Hi all,

I rebased to today's master branch and also updated some fields and the dashboard as well.

Below, you can see a screenshot with the new changes:
screenshot from 2019-01-24 11-46-41

**Comment by skatsaounis** [comment]
@ruflin Hi Travis is green. Can you trigger Jenkins as well? :)

**Comment by ruflin** [comment]
jenkins, test this

**Comment by ruflin** [comment]
@skatsaounis Any chance you could open a follow up PR to the docs with the above dashboard images so it shows up here? https://www.elastic.co/guide/en/beats/metricbeat/master/metricbeat-module-nats.html Would be nice to show to users in advance what kind of dashboard they get.

**Comment by skatsaounis** [comment]
Hi @ruflin. Thank you for merging this PR. I am going to update the docs; no problem at all :) I will mention you to the new PR when it will be ready.

**Pull request merged**
