### PR TITLE
Add docs for running Beats on ECK

### PR DESCRIPTION
**Pull request by ChrsMark**
This PR adds the docs for https://github.com/elastic/beats/issues/13305

cc: @exekias , @odacremolbap , @pebrc

### CODE REVIEW

**Comment by odacremolbap** [comment]
Hey @ChrsMark 
I have mixed feelings on adding this to the documentation.

Our official docs shouldn't be targeting minikube, although we do at beats repo for testing reference. Consider testing at a cloud provider an avoid minikube or any other kubernetes setup, refer to ECK requirements docs for compatibility.

 All resource docs at the links are pointing to cloud-on-k8s repo. Either we find a way of syncing with them or we will run into stale manifests often. Wouldn't it be more suitable to have this doc somewhere inside ECK's docs?
 The only resource to take care of would be https://raw.githubusercontent.com/elastic/cloud-on-k8s/master/config/recipes/beats/2_filebeat-kubernetes.yaml , which is already stale.

 Would it be worth it to generate an ECK oriented configuration at  https://github.com/elastic/beats/tree/master/deploy/kubernetes just like we do for non ECK clusters? then also add metricbeat and ask ECK team to use those manifests at their reference docs?


If you want to bring the minikube setup to our internal test docs at some readme I have a couple more comments:
- that minikube setup looks very demanding, do we need that much memory/cpu?
- very personal preference: have you tried kind? I think local multinodes would be much appreciated for dev/test setups

**Comment by ChrsMark** [comment]
> Hey @ChrsMark
> I have mixed feelings on adding this to the documentation.
> 
> Our official docs shouldn't be targeting minikube, although we do at beats repo for testing reference. Consider testing at a cloud provider an avoid minikube or any other kubernetes setup, refer to ECK requirements docs for compatibility.
> 

I agree we should point to ECK requirements. Will change it, thank you!

> All resource docs at the links are pointing to cloud-on-k8s repo. Either we find a way of syncing with them or we will run into stale manifests often. Wouldn't it be more suitable to have this doc somewhere inside ECK's docs?
> The only resource to take care of would be https://raw.githubusercontent.com/elastic/cloud-on-k8s/master/config/recipes/beats/2_filebeat-kubernetes.yaml , which is already stale.
> 
> Would it be worth it to generate an ECK oriented configuration at https://github.com/elastic/beats/tree/master/deploy/kubernetes just like we do for non ECK clusters? then also add metricbeat and ask ECK team to use those manifests at their reference docs?
> 

This was the initial plan but we decided to close the PR https://github.com/elastic/beats/pull/14131 and keep the manifests of ECK repo.


> If you want to bring the minikube setup to our internal test docs at some readme I have a couple more comments:
> 
> * that minikube setup looks very demanding, do we need that much memory/cpu?
> * very personal preference: have you tried kind? I think local multinodes would be much appreciated for dev/test setups

**Comment by dedemorton** [comment]
bump. It looks like this PR has been stalled for awhile. Are we still thinking about adding these docs, or can we close this?

**Comment by ChrsMark** [comment]
If I'm not mistaken, the plan was to add them in ECK repo. Maybe @andresrc can confirm.

**Comment by pebrc** [comment]
We are still planning to add some docs to the ECK repo. We are tracking this here https://github.com/elastic/cloud-on-k8s/issues/2143

**Comment by ChrsMark** [comment]
I think we can close it then.

**Pull request closed without merging**
