### PR TITLE
[WIP] Refactor docs_collector.py

### PR DESCRIPTION
**Pull request by palash25**
Fixes: https://github.com/elastic/beats/issues/10316

### CODE REVIEW

**Comment by palash25** [comment]
I had a few questions :point_down: 

> #10232 (comment) Named tuples are pretty handy in these cases, specially when fields of these objects are accessed so many times. https://github.com/elastic/beats/blob/master/metricbeat/scripts/docs_collector.py#L37


does the comment refer to the whole `modules_path` object to be changed into a named tuple or just the value of the metricset field?


Also I don't understand this comment about the asciidocs, can someone tell me what changes are required regarding this :point_down: 

> #10232 (comment) it appears as experimental but the module is beta, in any case I guess this is not related to this PR https://github.com/elastic/beats/blob/master/metricbeat/docs/modules/aws/ec2.asciidoc
#10232 (comment) these metricsets are experimental but the module is beta, is it expected? https://github.com/elastic/beats/blob/master/metricbeat/docs/modules/mssql/performance.asciidoc

**Comment by ruflin** [comment]
@sayden Could you take a look at this as I remember you worked on this script?

**Comment by sayden** [comment]
> does the comment refer to the whole `modules_path` object to be changed into a named tuple or just the value of the metricset field?

The entire `module_path` object, yes.

> Also I don't understand this comment about the asciidocs, can someone tell me what changes are required regarding this

My bad, sorry! This was unrelated. I have updated the issue.

So far, so good with your commited changes :wink:

**Comment by sayden** [comment]
`docs_collector.py` script has been finally replaced for a Go script https://github.com/elastic/beats/commit/f3d8676117eba83d958001ef21362d1631b96b3b. Thanks for your help @palash25 ! :)

**Pull request closed without merging**
