### PR TITLE
Replace `common.Config` and friends with `config.C` from `github.com/elastic/elastic-agent-libs`

### PR DESCRIPTION
**Pull request by kvch**
## What does this PR do?

This PR removes `common.Config` and its helpers and adopts the generic config type from `github.com/elastic/elastic-agent-libs`.

## Why is it important?

We do not want to maintain the same code in multiple repositories.

## Checklist

~~- [ ] My code follows the style guidelines of this project~~
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

### CODE REVIEW

**Review by cmacknz — APPROVED** [review]

**Comment by cmacknz** [comment]
I did not read all 534 changes, but the ones I did look at were uninteresting and LGTM.

**Comment by cmacknz** [comment]
I am not opposed to fixing the lint errors separately from this change, since so many files are touched at once here.

**Review by fearful-symmetry — APPROVED** [review]
Looked over some parts of the code I was familiar with. As craig said, we might have to ignore some of the CI errors here, for obvious reasons.

**Pull request merged**
