### PR TITLE
Add Journalbeat

### PR DESCRIPTION
**Pull request by kvch**
Blocked by #8702

### CODE REVIEW

**Comment by tsg** [comment]
jenkins, retest this please

**Comment by kvch** [comment]
Also needs a docs PR before merging to master: https://github.com/elastic/beats/pull/8735

**Comment by kvch** [comment]
jenkins test this

**Comment by kvch** [comment]
jenkins test this

**Comment by kvch** [comment]
jenkins test this

**Comment by kvch** [comment]
jenkins test this

**Pull request merged**
