### PR TITLE
Revert "[Elastic Agent] Add support for synthetics inputs that run he…

### PR DESCRIPTION
**Pull request by andrewvc**
…artbeat (#20387)"

This was breaking the agent build 

This reverts commit b153044e8e2e4105b3f57447d8b9e2d04309404b.

### CODE REVIEW

**Comment by andrewkroh** [comment]
Packaging job: https://beats-ci.elastic.co/job/Beats/job/packaging/job/PR-20563/

**Comment by ruflin** [comment]
@andrewvc It seems @blakerouse opened a PR here to fix the broken tests? This might fix it. Let me see if I can push the other PR over the line instead: https://github.com/elastic/beats/pull/20498

**Comment by jsoriano** [comment]
I think this can be closed after fix for packaging was merged https://github.com/elastic/beats/pull/20566

**Comment by andrewvc** [comment]
Closing because @jsoriano and @andrewkroh figured it out.

**Pull request closed without merging**
