### PR TITLE
fix: Fix parsing for dimension names from CloudWatch tag identifier values

### PR DESCRIPTION
**Pull request by cjr125**
- Bug fix

## What does this PR do?

Fix parsing for dimension names from CloudWatch tag identifier values

## Why is it important?

This change is necessary for filtering CloudWatch metric tags with dimensions attached to identifier values

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ] Approach to remove dimension names from identifier values is correct

### CODE REVIEW

**Comment by aspacca** [comment]
@cjr125 there's no need to add a new metricset to metrcibeat

you can collect the metrics you need just adding the following to your `modules.d/aws.yml`:
```
- module: aws
  period: 5m
  metricsets:
    - cloudwatch
  metrics:
      - namespace: AWS/CloudFront
        resource_type: cloudfront
        statistic: ["Average"]
        name:
          - 4xxErrorRate
          - 401ErrorRate
          - 403ErrorRate
          - 404ErrorRate
          - 5xxErrorRate
          - 502ErrorRate
          - 503ErrorRate
          - 504ErrorRate
          - CacheHitRate
          - TotalErrorRate
          - ExecutionTime
      - namespace: AWS/CloudFront
        resource_type: cloudfront
        statistic: ["Sum"]
        name:
          - BytesDownloaded
          - BytesUploaded
          - Requests
          - Invocations
          - ValidationErrors
          - ExecutionErrors
          - FunctionThrottles
      - namespace: AWS/CloudFront
        resource_type: cloudfront
        statistic: ["p95"] # or others relevant pNN
        name:
          - OriginLatency
```

**Comment by cjr125** [comment]
> @cjr125 there's no need to add a new metricset to metrcibeat
> 
> you can collect the metrics you need just adding the following to your `modules.d/aws.yml`:
> 
> ```
> - module: aws
>   period: 5m
>   metricsets:
>     - cloudwatch
>   metrics:
>       - namespace: AWS/CloudFront
>         resource_type: cloudfront
>         statistic: ["Average"]
>         name:
>           - 4xxErrorRate
>           - 401ErrorRate
>           - 403ErrorRate
>           - 404ErrorRate
>           - 5xxErrorRate
>           - 502ErrorRate
>           - 503ErrorRate
>           - 504ErrorRate
>           - CacheHitRate
>           - TotalErrorRate
>           - ExecutionTime
>       - namespace: AWS/CloudFront
>         resource_type: cloudfront
>         statistic: ["Sum"]
>         name:
>           - BytesDownloaded
>           - BytesUploaded
>           - Requests
>           - Invocations
>           - ValidationErrors
>           - ExecutionErrors
>           - FunctionThrottles
>       - namespace: AWS/CloudFront
>         resource_type: cloudfront
>         statistic: ["p95"] # or others relevant pNN
>         name:
>           - OriginLatency
> ```

@aspacca I tested this config and it didn't work for me. Can you please confirm that this is supported?

**Comment by cjr125** [comment]
> @cjr125 there's no need to add a new metricset to metrcibeat
> 
> you can collect the metrics you need just adding the following to your `modules.d/aws.yml`:
> 
> ```
> - module: aws
>   period: 5m
>   metricsets:
>     - cloudwatch
>   metrics:
>       - namespace: AWS/CloudFront
>         resource_type: cloudfront
>         statistic: ["Average"]
>         name:
>           - 4xxErrorRate
>           - 401ErrorRate
>           - 403ErrorRate
>           - 404ErrorRate
>           - 5xxErrorRate
>           - 502ErrorRate
>           - 503ErrorRate
>           - 504ErrorRate
>           - CacheHitRate
>           - TotalErrorRate
>           - ExecutionTime
>       - namespace: AWS/CloudFront
>         resource_type: cloudfront
>         statistic: ["Sum"]
>         name:
>           - BytesDownloaded
>           - BytesUploaded
>           - Requests
>           - Invocations
>           - ValidationErrors
>           - ExecutionErrors
>           - FunctionThrottles
>       - namespace: AWS/CloudFront
>         resource_type: cloudfront
>         statistic: ["p95"] # or others relevant pNN
>         name:
>           - OriginLatency
> ```

@aspacca I do actually need part of this code to fix a problem with using tags_filter on CloudFront metrics in CloudWatch. The identifier values include dimension names which break the standard tag filtering logic.  please see the updates (I left the commit history)

**Comment by aspacca** [comment]
> The identifier values include dimension names which break the standard tag filtering logic. please see the updates (I left the commit history)

can you explain your use case with an example?
From what I see it looks like a breaking change, and if so we cannot merge without proper protocol

**Comment by cjr125** [comment]
> > The identifier values include dimension names which break the standard tag filtering logic. please see the updates (I left the commit history)
> 
> can you explain your use case with an example? From what I see it looks like a breaking change, and if so we cannot merge without proper protocol

When loading metrics using the following config, I am able to print the following:

```
  aws.yml: |-
    - module: aws
      period: 1m
      metricsets:
        - cloudwatch
      metrics:
        - namespace: AWS/CloudFront
          resource_type: cloudfront
          statistic: ["Average"]
          name:
            - 4xxErrorRate
            - 401ErrorRate
            - 403ErrorRate
            - 404ErrorRate
            - 5xxErrorRate
            - 502ErrorRate
            - 503ErrorRate
            - 504ErrorRate
            - CacheHitRate
            - TotalErrorRate
            - ExecutionTime
        - namespace: AWS/CloudFront
          resource_type: cloudfront
          statistic: ["Sum"]
          name:
            - BytesDownloaded
            - BytesUploaded
            - Requests
            - Invocations
            - ValidationErrors
            - ExecutionErrors
            - FunctionThrottles
        - namespace: AWS/CloudFront
          resource_type: cloudfront
          statistic: ["p95"] # or others relevant pNN
          name:
            - OriginLatency
      tags_filter:
        - key: "amwell:environment-name"
          value: "dev-next"
``` yaml

```
// remove dimension names from identifier value if applicable
if strings.Contains(identifierValue, dimensionSeparator) {
	fmt.Println("identifierValue:", identifierValue)
	identifierSeparators := strings.Split(identifierValue, dimensionSeparator)
	identifierValue = identifierSeparators[len(identifierSeparators)-1]
}
``` go

identifierValue: Global,E5TGO8HHLKEA8

**Comment by aspacca** [comment]
> identifierValue: Global,E5TGO8HHLKEA8

you should use this full value in the `tags_filter`

with the other PR you've created you can add multiple values for the same tag filter

**Comment by cjr125** [comment]
> > identifierValue: Global,E5TGO8HHLKEA8
> 
> you should use this full value in the `tags_filter`
> 
> with the other PR you've created you can add multiple values for the same tag filter

I'm not sure I follow what you are suggesting. These identifier values are what come back when I try to apply the filter for a specific application environment which we need to monitor. For other namespaces, they do not contain dimension names (Global in this case) and the filtering works properly. In the case of the CloudFront namespace, however, the dimension name must be trimmed off in order to capture the desired identifier value. Is there some other way this problem can be approached?

**Comment by kaiyan-sheng** [comment]
@cjr125 Im trying to fix this issue in https://github.com/elastic/beats/pull/33472, please feel free to test/review it.

**Pull request closed without merging**
