### PR TITLE
Move backwards compatible flag manipulation

### PR DESCRIPTION
**Pull request by leehinman**
## Proposed commit message

libbeat manipulates the command line arguments to support older single dash arguments, for example `-e` vs `--e`.
Currently this is done in an init function.
Doing it there means that if libbeat is imported into another code base with it's own command line parsing it will cause things like `-1s` to be interpreted as `--1s` instead of negative 1 second.

This PR moves the manipulation of the command line arguments to just before the call to `flag.Parse()`.
This allows other code bases to import libbeat and not be affected by the backwards compatibility manipulation.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by blakerouse — APPROVED** [review]
Looks good to me.

**Comment by cmacknz** [comment]
Is there a way for us to add a test for this?

**Review by ycombinator — APPROVED** [review]

**Comment by leehinman** [comment]
> Is there a way for us to add a test for this?

Yes.  I just wanted to the the tests started

**Review by VihasMakwana — APPROVED** [review]

**Comment by leehinman** [comment]
Closing this in favor of reverting changes that caused problems.

https://github.com/elastic/beats/pull/41151
https://github.com/elastic/beats/pull/41152

https://github.com/elastic/beats/issues/41153 tracks effort that will need to happen to move past this.

**Pull request closed without merging**
