### PR TITLE
[libbeat] typo fix for dns timeout configuration option

### PR DESCRIPTION
**Pull request by dddpaul**
Type: Bug

## What does this PR do?

Fix typo in config

## Checklist

- [x ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by dddpaul** [comment]
I've signed contributor agreement two days ago. What should I do next?

**Comment by andrewkroh** [comment]
run tests

**Review by andrewkroh — APPROVED** [review]
LGTM

**Comment by mtojek** [comment]
Let me merge this one.

**Pull request merged**
