### PR TITLE
Packaging: rename arm64 suffix to aarch64 in the tar.gz artifacts ONLY

### PR DESCRIPTION
**Pull request by v1v**
## What does this PR do?

Rename `tar.gz` artifacts with `arm64` to `aarch64`

## Why is it important?

Normalise the package naming to match with the same done in Kibana and Elasticsearch.

## Issue

Closes https://github.com/elastic/beats/issues/28738

## Test

Let's build the tar.gz packages for filebeat in arm64:

```bash
cd filebeat
PACKAGES="targz" PLATFORMS="linux/arm64" mage package
```

then

```
ls -ltra build/distributions/filebeat-oss-8.1.0-*             
-rw-r--r--  1 vmartinez  staff  22386646  5 Nov 14:30 build/distributions/filebeat-oss-8.1.0-linux-aarch64.tar.gz
-rw-r--r--  1 vmartinez  staff       169  5 Nov 14:30 build/distributions/filebeat-oss-8.1.0-linux-aarch64.tar.gz.sha512
```

### GCP

For instance, this PR has been verified in the CI and artifacts have been uploaded to the Google Storage bucket:

image

And the list of files:

```
gsutil ls -r gs://beats-ci-artifacts/pull-requests/pr-28813 | grep -v docker | grep -v 'x86' | grep 'tar.gz' 
gs://beats-ci-artifacts/pull-requests/pr-28813/auditbeat/auditbeat-8.1.0-SNAPSHOT-linux-aarch64.tar.gz
gs://beats-ci-artifacts/pull-requests/pr-28813/auditbeat/auditbeat-8.1.0-SNAPSHOT-linux-aarch64.tar.gz.sha512
gs://beats-ci-artifacts/pull-requests/pr-28813/auditbeat/auditbeat-oss-8.1.0-SNAPSHOT-linux-aarch64.tar.gz
gs://beats-ci-artifacts/pull-requests/pr-28813/auditbeat/auditbeat-oss-8.1.0-SNAPSHOT-linux-aarch64.tar.gz.sha512
gs://beats-ci-artifacts/pull-requests/pr-28813/elastic-agent/elastic-agent-8.1.0-SNAPSHOT-linux-aarch64.tar.gz
gs://beats-ci-artifacts/pull-requests/pr-28813/elastic-agent/elastic-agent-8.1.0-SNAPSHOT-linux-aarch64.tar.gz.sha512
gs://beats-ci-artifacts/pull-requests/pr-28813/filebeat/filebeat-8.1.0-SNAPSHOT-linux-aarch64.tar.gz
gs://beats-ci-artifacts/pull-requests/pr-28813/filebeat/filebeat-8.1.0-SNAPSHOT-linux-aarch64.tar.gz.sha512
gs://beats-ci-artifacts/pull-requests/pr-28813/filebeat/filebeat-oss-8.1.0-SNAPSHOT-linux-aarch64.tar.gz
gs://beats-ci-artifacts/pull-requests/pr-28813/filebeat/filebeat-oss-8.1.0-SNAPSHOT-linux-aarch64.tar.gz.sha512
gs://beats-ci-artifacts/pull-requests/pr-28813/functionbeat/functionbeat-8.1.0-SNAPSHOT-linux-aarch64.tar.gz
gs://beats-ci-artifacts/pull-requests/pr-28813/functionbeat/functionbeat-8.1.0-SNAPSHOT-linux-aarch64.tar.gz.sha512
gs://beats-ci-artifacts/pull-requests/pr-28813/heartbeat/heartbeat-8.1.0-SNAPSHOT-linux-aarch64.tar.gz
gs://beats-ci-artifacts/pull-requests/pr-28813/heartbeat/heartbeat-8.1.0-SNAPSHOT-linux-aarch64.tar.gz.sha512
gs://beats-ci-artifacts/pull-requests/pr-28813/heartbeat/heartbeat-oss-8.1.0-SNAPSHOT-linux-aarch64.tar.gz
gs://beats-ci-artifacts/pull-requests/pr-28813/heartbeat/heartbeat-oss-8.1.0-SNAPSHOT-linux-aarch64.tar.gz.sha512
gs://beats-ci-artifacts/pull-requests/pr-28813/journalbeat/journalbeat-8.1.0-SNAPSHOT-linux-aarch64.tar.gz
gs://beats-ci-artifacts/pull-requests/pr-28813/journalbeat/journalbeat-8.1.0-SNAPSHOT-linux-aarch64.tar.gz.sha512
gs://beats-ci-artifacts/pull-requests/pr-28813/journalbeat/journalbeat-oss-8.1.0-SNAPSHOT-linux-aarch64.tar.gz
gs://beats-ci-artifacts/pull-requests/pr-28813/journalbeat/journalbeat-oss-8.1.0-SNAPSHOT-linux-aarch64.tar.gz.sha512
gs://beats-ci-artifacts/pull-requests/pr-28813/metricbeat/metricbeat-8.1.0-SNAPSHOT-linux-aarch64.tar.gz
gs://beats-ci-artifacts/pull-requests/pr-28813/metricbeat/metricbeat-8.1.0-SNAPSHOT-linux-aarch64.tar.gz.sha512
gs://beats-ci-artifacts/pull-requests/pr-28813/metricbeat/metricbeat-oss-8.1.0-SNAPSHOT-linux-aarch64.tar.gz
gs://beats-ci-artifacts/pull-requests/pr-28813/metricbeat/metricbeat-oss-8.1.0-SNAPSHOT-linux-aarch64.tar.gz.sha512
gs://beats-ci-artifacts/pull-requests/pr-28813/osquerybeat/osquerybeat-8.1.0-SNAPSHOT-linux-aarch64.tar.gz
gs://beats-ci-artifacts/pull-requests/pr-28813/osquerybeat/osquerybeat-8.1.0-SNAPSHOT-linux-aarch64.tar.gz.sha512
gs://beats-ci-artifacts/pull-requests/pr-28813/packetbeat/packetbeat-8.1.0-SNAPSHOT-linux-aarch64.tar.gz
gs://beats-ci-artifacts/pull-requests/pr-28813/packetbeat/packetbeat-8.1.0-SNAPSHOT-linux-aarch64.tar.gz.sha512
gs://beats-ci-artifacts/pull-requests/pr-28813/packetbeat/packetbeat-oss-8.1.0-SNAPSHOT-linux-aarch64.tar.gz
gs://beats-ci-artifacts/pull-requests/pr-28813/packetbeat/packetbeat-oss-8.1.0-SNAPSHOT-linux-aarch64.tar.gz.sha512

```

While currently for `8.0.0` is the below:

```
gs://beats-ci-artifacts/snapshots/auditbeat/auditbeat-8.0.0-SNAPSHOT-linux-arm64.tar.gz
gs://beats-ci-artifacts/snapshots/auditbeat/auditbeat-8.0.0-SNAPSHOT-linux-arm64.tar.gz.sha512
gs://beats-ci-artifacts/snapshots/auditbeat/auditbeat-oss-8.0.0-SNAPSHOT-linux-arm64.tar.gz
gs://beats-ci-artifacts/snapshots/auditbeat/auditbeat-oss-8.0.0-SNAPSHOT-linux-arm64.tar.gz.sha512
gs://beats-ci-artifacts/snapshots/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-linux-arm64.tar.gz
gs://beats-ci-artifacts/snapshots/elastic-agent/elastic-agent-8.0.0-SNAPSHOT-linux-arm64.tar.gz.sha512
gs://beats-ci-artifacts/snapshots/filebeat/filebeat-8.0.0-SNAPSHOT-linux-arm64.tar.gz
gs://beats-ci-artifacts/snapshots/filebeat/filebeat-8.0.0-SNAPSHOT-linux-arm64.tar.gz.sha512
gs://beats-ci-artifacts/snapshots/filebeat/filebeat-oss-8.0.0-SNAPSHOT-linux-arm64.tar.gz
gs://beats-ci-artifacts/snapshots/filebeat/filebeat-oss-8.0.0-SNAPSHOT-linux-arm64.tar.gz.sha512
gs://beats-ci-artifacts/snapshots/functionbeat/functionbeat-8.0.0-SNAPSHOT-linux-arm64.tar.gz
gs://beats-ci-artifacts/snapshots/functionbeat/functionbeat-8.0.0-SNAPSHOT-linux-arm64.tar.gz.sha512
gs://beats-ci-artifacts/snapshots/heartbeat/heartbeat-8.0.0-SNAPSHOT-linux-arm64.tar.gz
gs://beats-ci-artifacts/snapshots/heartbeat/heartbeat-8.0.0-SNAPSHOT-linux-arm64.tar.gz.sha512
gs://beats-ci-artifacts/snapshots/heartbeat/heartbeat-oss-8.0.0-SNAPSHOT-linux-arm64.tar.gz
gs://beats-ci-artifacts/snapshots/heartbeat/heartbeat-oss-8.0.0-SNAPSHOT-linux-arm64.tar.gz.sha512
gs://beats-ci-artifacts/snapshots/journalbeat/journalbeat-8.0.0-SNAPSHOT-linux-arm64.tar.gz
gs://beats-ci-artifacts/snapshots/journalbeat/journalbeat-8.0.0-SNAPSHOT-linux-arm64.tar.gz.sha512
gs://beats-ci-artifacts/snapshots/journalbeat/journalbeat-oss-8.0.0-SNAPSHOT-linux-arm64.tar.gz
gs://beats-ci-artifacts/snapshots/journalbeat/journalbeat-oss-8.0.0-SNAPSHOT-linux-arm64.tar.gz.sha512
gs://beats-ci-artifacts/snapshots/metricbeat/metricbeat-8.0.0-SNAPSHOT-linux-arm64.tar.gz
gs://beats-ci-artifacts/snapshots/metricbeat/metricbeat-8.0.0-SNAPSHOT-linux-arm64.tar.gz.sha512
gs://beats-ci-artifacts/snapshots/metricbeat/metricbeat-oss-8.0.0-SNAPSHOT-linux-arm64.tar.gz
gs://beats-ci-artifacts/snapshots/metricbeat/metricbeat-oss-8.0.0-SNAPSHOT-linux-arm64.tar.gz.sha512
gs://beats-ci-artifacts/snapshots/osquerybeat/osquerybeat-8.0.0-SNAPSHOT-linux-arm64.tar.gz
gs://beats-ci-artifacts/snapshots/osquerybeat/osquerybeat-8.0.0-SNAPSHOT-linux-arm64.tar.gz.sha512
gs://beats-ci-artifacts/snapshots/packetbeat/packetbeat-8.0.0-SNAPSHOT-linux-arm64.tar.gz
gs://beats-ci-artifacts/snapshots/packetbeat/packetbeat-8.0.0-SNAPSHOT-linux-arm64.tar.gz.sha512
gs://beats-ci-artifacts/snapshots/packetbeat/packetbeat-oss-8.0.0-SNAPSHOT-linux-arm64.tar.gz
gs://beats-ci-artifacts/snapshots/packetbeat/packetbeat-oss-8.0.0-SNAPSHOT-linux-arm64.tar.gz.sha512
```

image

### CODE REVIEW

**Comment by mdelapenya** [comment]
We must update the E2E code to support this rename, i.e. here https://github.com/elastic/e2e-testing/blob/87be9250d36ed05a80d211f245eb52794d060478/internal/versions_test.go#L442

**Comment by v1v** [comment]
> We must update the E2E code to support this rename, i.e. here https://github.com/elastic/e2e-testing/blob/87be9250d36ed05a80d211f245eb52794d060478/internal/versions_test.go#L442

Good catch, this will only be needed for `versions >= 8`

**Review by andrewkroh — COMMENTED** [review]
I think this should have a changelog note in the breaking change section. I'm sure there is plenty of automation out there that will require updates. Here's what we have in the download logs (last 90d) for "arm64.tar.gz" artifacts.

I see Elastic Agent in this list. Have you checked if Elastic Agent needs an update or any of Elastic Cloud references this artifact name?

| Top values of agent.raw                                                                                                                                                                                      	| Count of records 	|
|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------	|------------------	|
| curl/7.29.0                                                                                                                                                                                                  	| 82,915           	|
| Cloud-CDN-Google (GFE/2.0)                                                                                                                                                                                   	| 17,492           	|
| curl/7.58.0                                                                                                                                                                                                  	| 3,042            	|
| Mozilla/5.0 (compatible; bingbot/2.0;  http://www.bing.com/bingbot.htm)                                                                                                                                      	| 2,221            	|
| Go-http-client/2.0                                                                                                                                                                                           	| 2,115            	|
| Beat elastic-agent v8.0.0                                                                                                                                                                                    	| 1,398            	|
| Beat elastic-agent v7.16.0                                                                                                                                                                                   	| 660              	|
| curl/7.76.1                                                                                                                                                                                                  	| 584              	|
| curl/7.61.1                                                                                                                                                                                                  	| 579              	|
| Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 (compatible; bingbot/2.0;  http://www.bing.com/bingbot.htm)          	| 545              	|
| Wget/1.14 (linux-gnu)                                                                                                                                                                                        	| 465              	|
| Beat elastic-agent v7.15.2                                                                                                                                                                                   	| 365              	|
| Gradle/7.1 (Linux;5.4.0-1055-aws;aarch64) (Private Build;1.8.0_292;25.292-b10)                                                                                                                               	| 264              	|
| Mozilla/5.0 (compatible; AhrefsSiteAudit/6.1;  http://ahrefs.com/robot/)                                                                                                                                     	| 257              	|
| Mozilla/5.0 (compatible; AhrefsBot/7.0;  http://ahrefs.com/robot/)                                                                                                                                           	| 214              	|
| Gradle/7.2 (Linux;5.4.0-1058-aws;aarch64) (Eclipse Foundation;11.0.12;11.0.12 7)                                                                                                                             	| 210              	|
| Gradle/7.2 (Linux;5.4.0-1057-aws;aarch64) (Eclipse Foundation;11.0.12;11.0.12 7)                                                                                                                             	| 198              	|
| Salt/3003.2 http.query()                                                                                                                                                                                     	| 192              	|
| curl/7.68.0                                                                                                                                                                                                  	| 184              	|
| Gradle/7.2 (Linux;5.11.0-1020-aws;aarch64) (Eclipse Foundation;11.0.12;11.0.12 7)                                                                                                                            	| 168              	|
| Gradle/7.2 (Linux;5.4.0-1057-aws;aarch64) (Private Build;1.8.0_292;25.292-b10)                                                                                                                               	| 168              	|
| Mozilla/5.0 (Linux; Android 7.0;) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; PetalBot; https://webmaster.petalsearch.com/site/petalbot)                                        	| 165              	|
| curl/7.64.1                                                                                                                                                                                                  	| 152              	|
| Mozilla/5.0 (iPhone; CPU iPhone OS 7_0 like Mac OS X) AppleWebKit/537.51.1 (KHTML, like Gecko) Version/7.0 Mobile/11A465 Safari/9537.53 BingPreview/1.0b                                                     	| 151              	|
| Gradle/7.2 (Linux;5.4.0-1056-aws;aarch64) (Private Build;1.8.0_292;25.292-b10)                                                                                                                               	| 144              	|
| Salt/3003.3 http.query()                                                                                                                                                                                     	| 144              	|
| Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/534  (KHTML, like Gecko) BingPreview/1.0b                                                                                                                    	| 117              	|
| ansible-httpget                                                                                                                                                                                              	| 111              	|
| Gradle/7.1 (Linux;5.4.0-1054-aws;aarch64) (Private Build;1.8.0_292;25.292-b10)                                                                                                                               	| 108              	|
| Wget/1.20.3 (linux-gnu)                                                                                                                                                                                      	| 99               	|
| Salt/3003.1 http.query()                                                                                                                                                                                     	| 87               	|
| Gradle/7.1 (Linux;5.4.0-1056-aws;aarch64) (Private Build;1.8.0_292;25.292-b10)                                                                                                                               	| 84               	|
| Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.159 Safari/537.36                                                                                          	| 69               	|
| curl/7.78.0                                                                                                                                                                                                  	| 68               	|
| httpx - Open-source project (github.com/projectdiscovery/httpx)                                                                                                                                              	| 68               	|
| Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36                                                                                          	| 65               	|
| Salt/3004 http.query()                                                                                                                                                                                       	| 62               	|
| Python-urllib/3.7                                                                                                                                                                                            	| 60               	|
| Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/59.0.3071.115 Safari/537.36                                                                                          	| 50               	|
| Beat elastic-agent v7.15.0                                                                                                                                                                                   	| 47               	|
| Screaming Frog SEO Spider/15.2                                                                                                                                                                               	| 47               	|
| Wget/1.19.4 (linux-gnu)                                                                                                                                                                                      	| 42               	|
| Mozilla/5.0 (X11                                                                                                                                                                                             	| 41               	|
| Mozilla/5.0 (Linux; Android 6.0.1; Nexus 5X Build/MMB29P) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.119 Mobile Safari/537.36 (compatible; Googlebot/2.1;  http://www.google.com/bot.html)      	| 40               	|
| Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/93.0.4577.82 Safari/537.36                                                                                           	| 37               	|
| Beat elastic-agent v7.14.1                                                                                                                                                                                   	| 36               	|
| Mozilla/4.0 (compatible; MSIE 7.0; Windows NT 6.2; WOW64; Trident/7.0; .NET4.0C; .NET4.0E; .NET CLR 2.0.50727; .NET CLR 3.0.30729; .NET CLR 3.5.30729; InfoPath.3; wbx 1.0.0; systeccloud 3.5.1; Zoom 3.6.0) 	| 36               	|
| Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:91.0) Gecko/20100101 Firefox/91.0                                                                                                                               	| 34               	|
| Mozilla/5.0 (Linux; Android) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/34.0.1847.131 Safari/537.36                                                                                                       	| 33               	|
| Magic Browser                                                                                                                                                                                                	| 30               	|
| Other                                                                                                                                                                                                        	| 1,604            	|

**Comment by mdelapenya** [comment]
Does it apply to `tar.gz` files only? We see there are `arm64.deb` and `aarch64.rpm` files

**Comment by andrewkroh** [comment]
Debian uses "arm64" as their naming convention for artifacts targeting aarch64 (https://wiki.debian.org/Arm64Port). That's why those files have that name. Does the rest of the stack follow the Debian convention for .deb?

**Comment by mdelapenya** [comment]
@andrewkroh good point. Yes they do: https://artifacts-api.elastic.co/v1/search/8.0.0-SNAPSHOT/elasticsearch?x-elastic-no-kpi=true

> "elasticsearch-8.0.0-SNAPSHOT-arm64.deb"

**Comment by kuisathaverat** [comment]
I'd say that is most common to find `arm64` than `aarch64`

**Review by andrewkroh — APPROVED** [review]
LGTM assume due diligence has been done to update release-manager, download pages, and check with other Elastic teams.

**Comment by v1v** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by v1v** [comment]
>  Have you checked if Elastic Agent needs an update or any of Elastic Cloud references this artifact name?

Changes for `Elastic Agent` are also in this PR:

```
gs://beats-ci-artifacts/pull-requests/pr-28813/elastic-agent/elastic-agent-8.1.0-SNAPSHOT-linux-aarch64.tar.gz
gs://beats-ci-artifacts/pull-requests/pr-28813/elastic-agent/elastic-agent-8.1.0-SNAPSHOT-linux-aarch64.tar.gz.sha512
```

Regarding the Elastic Cloud, I guess they only use docker images from a docker registry.

I didn't change the `docker.tar.gz` generation since IIUC the only requirement was about the `linux-arm64.tar.gz` files.

For the record, this PR changes the above and the `Elastic Agent Cloud` docker tar.gz files contain the `arm64` suffix:

```bash
gsutil ls -r gs://beats-ci-artifacts/pull-requests/pr-28813  | grep 'cloud'
gs://beats-ci-artifacts/pull-requests/pr-28813/elastic-agent/elastic-agent-cloud-8.1.0-SNAPSHOT-linux-amd64.docker.tar.gz
gs://beats-ci-artifacts/pull-requests/pr-28813/elastic-agent/elastic-agent-cloud-8.1.0-SNAPSHOT-linux-amd64.docker.tar.gz.sha512
gs://beats-ci-artifacts/pull-requests/pr-28813/elastic-agent/elastic-agent-cloud-8.1.0-SNAPSHOT-linux-arm64.docker.tar.gz
gs://beats-ci-artifacts/pull-requests/pr-28813/elastic-agent/elastic-agent-cloud-8.1.0-SNAPSHOT-linux-arm64.docker.tar.gz.sha512
```

I'll wait for the Infra Release team to answer if that's also needed.

**Review by cachedout — APPROVED** [review]

**Review by mgreau — APPROVED** [review]
LGTM, thanks Victor 👍

**Comment by v1v** [comment]
Thanks Maxime, as we have agreed, I'll move forward and merge this PR.

The backport to 8.0 will happen after we know all the changes worked as expected.

Thanks agian

**Comment by v1v** [comment]
Heads ups, we have decided to revert this change for the time being as `8.0` is quite closed.

**Pull request merged**
