### PR TITLE
added mysqlbeat

### PR DESCRIPTION
**Pull request by adibendahan**
added mysqlbeat to community beats

### CODE REVIEW

**Comment by ruflin** [comment]
LGTM

@adibendahan Do you mind signing the CLA? https://www.elastic.co/contributor-agreement/

**Comment by ruflin** [comment]
@abdonpijpelink One small correction I just realised: We sorted the beats alphabetically. Could you put mysqlbeat at the right place?

**Comment by adibendahan** [comment]
@ruflin I just signed it

**Comment by ruflin** [comment]
@adibendahan CLA looks good. Could you update the PR with the ordering? Also let me know if I should do it for you in an other PR.

**Comment by adibendahan** [comment]
@ruflin done.

**Comment by ruflin** [comment]
@adibendahan Thanks a lot. Merged.

**Pull request merged**
