### PR TITLE
Instead of blacklisting chars in the resource name for cloudformation use whitelisting.

### PR DESCRIPTION
**Pull request by ph**
Only [a-zA-Z0-9] are permitted as resource name

Fixes: #9420

### CODE REVIEW

**Comment by ph** [comment]
@kvch This should solve the issue with the wrong log group, I haven't been able to reproduce the other bug yet.

**Comment by kvch** [comment]
The failing tests are fixed on master. A rebase should correct the errors.

**Comment by ph** [comment]
rebased and pushed.

**Comment by ph** [comment]
errors are not related to this change.

**Pull request merged**
