### PR TITLE
[Elastic Agent] Fix deb/rpm installation

### LINKED ISSUE #21200: [Fleet] Elastic-Agent doesn't start up with .rpm / .deb usage (with enroll cmd)
I need to put details in... I can grab what logs do exist. But during the weekly sync we realized this wasn't logged so I'm dropping a ticket in. Tested with 8.0

The e2e-testing work is finding this bug:

edavis$ OP_LOG_LEVEL=TRACE DEVELOPER_MODE=true ELASTIC_AGENT_USE_CI_SNAPSHOTS=false ELASTIC_AGENT_VERSION=8.0.0-SNAPSHOT godog -t "endpoint-policy-check"

manual testing finds the same. linux .tar.gz is working fully.

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Fixes the installation of Elastic Agent using the .deb and .rpm.

This fixes the issue of the Elastic Agent .deb not working on Ubuntu because the starting parameters of `--environment systemd` cannot be used on the root cmd, it can only be used on the `run` subcommand.

This fixes the issue of the Elastic Agent .rpm not working on Fedora because SELinux prevents a systemd unit from starting a binary inside of `/usr/share`. This switches the command of the unit to `/usr/bin/elastic-agent` which will already provide the wrapper command args for the paths and not prevent SELinux from starting the binary.

## Why is it important?

Allows Elastic Agent to work from a .deb and .rpm installation.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #21200

### CODE REVIEW

**Review by ruflin — COMMENTED** [review]
It would be good to have some more details in the PR description why this change fixes the current issue. I can see that run with systemd is used. Does this apply to all Linux distros?

**Comment by blakerouse** [comment]
@ruflin Added more information to the PR description.

**Review by ruflin — APPROVED** [review]
Thanks for the details. This is helpful. So we basically fix 2 different issue in one go an even simplify the template! 

Change LGTM but did not test it on any of the systems locally.

**Comment by ruflin** [comment]
@blakerouse As we discussed on the Monday meeting, we should work with @EricDavisX to reenabled the deb/rpm test cases and make sure also this one here is covered.

**Review by michalpristas — APPROVED** [review]
Change lgtm

**Comment by EricDavisX** [comment]
for reference, the e2e feature work for the rpm/deb install is here: https://github.com/elastic/e2e-testing/issues/379

**Pull request merged**
