### PR TITLE
[Filebeat][Salesforce] Added new configuration for initial days interval

### PR DESCRIPTION
**Pull request by kush-elastic**
- Enhancement

## What does this PR do?
- Added configuration parameter for user to configure initial days to collect data from.
- found more details in linked issue.

## Why is it important?
- Current salesforce module collects all the historical data of 180 days. that might necessary for the users.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have made corresponding change to the default configuration files
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues
- Relates #34661

### CODE REVIEW

**Comment by agithomas** [comment]
In the proposed change, the time can be specified in terms of number of days. Is there in SOQL to specify in terms of hours - how many hours the query must have to look back in time ?

**Comment by agithomas** [comment]
@kush-elastic , please update the progress on this . Also, as per https://github.com/elastic/beats/issues/34661#issuecomment-1466067172, LogDate is not accurate. Planning to change the query based on the comment ?

**Comment by kush-elastic** [comment]
> @kush-elastic , please update the progress on this . Also, as per [#34661 (comment)](https://github.com/elastic/beats/issues/34661#issuecomment-1466067172), LogDate is not accurate. Planning to change the query based on the comment ?

As mentioned in the [issue](https://github.com/elastic/beats/issues/34661), we are waiting on the [Pagination fix to be completed](https://github.com/elastic/beats/issues/34839). once it is merged. we will update PR with the newly proposed solution (Use CreatedDate and the initial interval can be configured in hours, minutes, etc.).

**Comment by kush-elastic** [comment]
Closing as this changes are done as part of Salesforce Module and Integration revamping.
https://github.com/elastic/obs-infraobs-team/issues/1248

**Pull request closed without merging**
