### PR TITLE
[winlogbeat] Add Security 4662

### PR DESCRIPTION
**Pull request by jeff-bb**
Basic parsing of event id 4662. Category is explicitly added and existing SubjectUser/Domain function handles user information with the addition of the event id into the table.

https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-10/security/threat-protection/auditing/event-4662

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by marc-gr** [comment]
thanks for the addition! Do you happen to have any sample event we can add to the tests? (anonymize where needed in case you add it)

**Comment by jeff-bb** [comment]
What is the best format for the events? It looks like evtx are present, as well as the post processed json (which I assume are utilized for before/after testing with builds). evtx is problematic since I'd have to setup a test environment since I don't believe they can be post created modified (easily). If xml/txt/csv works, then I can get them exported and sanitized.

Also, does it make more sense for me to continue splitting up minor changes as individual PRs or save them all up and contribute at once?

**Comment by marc-gr** [comment]
XML works if this is what you have available.

Smaller PRs are fine, but for such changes if you bulk them since there is no much code involved it is alright also if it makes your life easier.

**Pull request closed without merging**
