### PR TITLE
[DOCS] Show Npcap in packetbeat installation steps

### PR DESCRIPTION
**Pull request by dedemorton**
Winpcap is no longer maintained and is susceptible to DLL hacking. I've updated the docs to recommend Npcap, but I need dev to confirm that this is now our recommendation.

@adriansr Sounds like you installed this. Can you please confirm that this is the recommendation?

### CODE REVIEW

**Comment by andrewkroh** [comment]
npcap is also recommended in the packetbeat f.a.q. page so maybe there should be a tie in.

**Comment by dedemorton** [comment]
@andrewkroh I've updated the GS and FAQ. I'm sitting on the fence about whether the GS should mention in the config section should mention selecting the LoopBack Driver to capture loopback traffic. WDYT?

**Comment by andrewkroh** [comment]
This LGTM, but I haven't ran the npcap installer recently to see if those options we mention still exist.

**Comment by dedemorton** [comment]
I ran it on Friday and the options do exist. I've used generic language that users should be able to map to the option names, even if they change.

**Comment by dedemorton** [comment]
I'm waiting until the following PR is merged before backporting this PR: https://github.com/elastic/beats/pull/12537

**Pull request merged**
