### PR TITLE
Fix update target to get pkg/errors

### PR DESCRIPTION
**Pull request by jsoref**
https://github.com/elastic/beats/pull/7456#issuecomment-402734994

### CODE REVIEW

**Comment by ruflin** [comment]
jenkins, test this

**Comment by ruflin** [comment]
I opened to revert the change. https://github.com/elastic/beats/pull/7540

**Comment by jsoref** [comment]
@ruflin: after I moved the directory.
If I change the `go get` to `echo go get` and remove `~/go/src/github.com/pkg/errors` then it fails again.

**Comment by andrewkroh** [comment]
I tried to recreate here by deleting github/pkg/errors, but it worked and found it in the `beats/vendor/github.com/pkg/errors`.

Was it the same error as in https://github.com/elastic/beats/pull/7456#issuecomment-402734994?

Did you symlink beats into the GOPATH?

Can you please post your `go env` output?

**Comment by jsoref** [comment]
yes, same error:
```sh
scripts/generate_config.go:31:2: cannot find package "github.com/pkg/errors" in any of:
	/usr/local/Cellar/go/1.10.3/libexec/src/github.com/pkg/errors (from $GOROOT)
	/Users/jsoref/go/src/github.com/pkg/errors (from $GOPATH)
make[1]: *** [collect-docs] Error 1
make: *** [update] Error 1
```

Yes, there's a symlink:
```sh
$ ls -l ~/go/src/
total 0
lrwxr-xr-x  1 jsoref  staff  18 Jul  9 12:29 github.com -> /Users/jsoref/code
```

Note: in `code` there's an `elastic` directory which in turn has `beats` directory.
I tried changing it so that there's a `~/go/src/github.com/` directory with both `elastic` (symlink to `~/code/elastic`) and `beats` (symlink to `~/code/elastic/beats`), and I tried building from both `~/go/src/github.com/beats` and `~/go/src/github.com/elastic/beats` -- none of these variations worked.

Indeed, replacing the symlink with the underlying directory worked.

env:
```sh
$ go env
GOARCH="amd64"
GOBIN=""
GOCACHE="/Users/jsoref/Library/Caches/go-build"
GOEXE=""
GOHOSTARCH="amd64"
GOHOSTOS="darwin"
GOOS="darwin"
GOPATH="/Users/jsoref/go"
GORACE=""
GOROOT="/usr/local/Cellar/go/1.10.3/libexec"
GOTMPDIR=""
GOTOOLDIR="/usr/local/Cellar/go/1.10.3/libexec/pkg/tool/darwin_amd64"
GCCGO="gccgo"
CC="clang"
CXX="clang++"
CGO_ENABLED="1"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fno-caret-diagnostics -Qunused-arguments -fmessage-length=0 -fdebug-prefix-map=/var/folders/r3/n29fz25x72x191fdv6mhhr3m0000gp/T/go-build200265355=/tmp/go-build -gno-record-gcc-switches -fno-common"
```

I'm sorry, I'm not a go developer. I'm just someone who picks up things and tries to contribute to them. Within limits, I'll read documentation, but none of these mention this requirement:
* https://github.com/elastic/beats/blob/master/README.md
* https://github.com/elastic/beats/blob/master/CONTRIBUTING.md

It is mentioned (by reference) here:
* https://www.elastic.co/guide/en/beats/devguide/current/beats-contributing.html
(which was referenced as a "you _can_ ... read..." -- that's not an RFC word, and certainly neither a _should_ nor a _must_)

Personally, I'd suggest (and am willing to try to write) adding a `Makefile` rule which detects this and complains about it, since apparently your build system _sort of_ (but only barely, since really that was the only thing that) cares about where and how it lives.

I tend to start with spelling & documentation fixes, and then may move to more core things. If there are too many hoops, I'll move along to more welcoming projects. I hope that makes sense.

**Comment by ruflin** [comment]
@jsoref We are really happy that you went through all these hoops and appreciate your contributions. The above is unfortunately a thing most people new to Golang stumble over. +1 on having something in the Makefile to can check if the setup of the paths is correct.

Our docs are definitively not following an `RFC` word but we hoped so we covered it with. Perhaps we are a bit too friendly here :-)

> The location where you clone is important. Please clone under the source directory of your GOPATH. If you don’t have GOPATH already set, you can simply set it to the go directory in your home (export GOPATH=$HOME/go).

I also saw that you gave me write permissions on your other PR. I assume that was a message that I can also start pushing commits to it to fix CI?

**Comment by jsoref** [comment]
Yes

**Pull request merged**
