### PR TITLE
add MacOS Arm tests

### PR DESCRIPTION
**Pull request by sharbuz**
## What is the problem this PR solves?

Jenkins->Buildkite pipelines migration 

Add the missed MacOS ARM tests

## Related issues
https://github.com/elastic/ingest-dev/issues/1693

### CODE REVIEW

**Review by dliappis — COMMENTED** [review]
Looks good to me, but as it is, it breaks the [recently migrated](https://github.com/elastic/beats/pull/38783) auditbeat and heartbeat static pipeline for macOS see: 

https://buildkite.com/elastic/auditbeat/builds/3702#018ecbef-4c32-4963-b643-a0f8955cc5ac

can we fix how these two pipelines run the macOS tests, to follow the practices of this PR?

**Comment by oakrizan** [comment]
> Looks good to me, but as it is, it breaks the [recently migrated](https://github.com/elastic/beats/pull/38783) auditbeat and heartbeat static pipeline for macOS see:
> 
> https://buildkite.com/elastic/auditbeat/builds/3702#018ecbef-4c32-4963-b643-a0f8955cc5ac
> 
> can we fix how these two pipelines run the macOS tests, to follow the practices of this PR?

I can fix that in a separate PR and unify 2 env setup scripts which both become annoying to maintain. WDYT?

**Review by oakrizan — COMMENTED** [review]
I'd suggest not to replace the `cd $BEATS_PROJECT_NAME && mage build unitTest` with separate script. Env setup is currently supported in pre-command hook and I think it's logical to store it there.

**Comment by sharbuz** [comment]
And, perhaps it's would be better to refactor that 

> > Looks good to me, but as it is, it breaks the [recently migrated](https://github.com/elastic/beats/pull/38783) auditbeat and heartbeat static pipeline for macOS see:
> > https://buildkite.com/elastic/auditbeat/builds/3702#018ecbef-4c32-4963-b643-a0f8955cc5ac
> > can we fix how these two pipelines run the macOS tests, to follow the practices of this PR?
> 
> I've fixed the Auditbeat and I'm trying to understand if these changes affect the heartbeat, I'm not sure about it.

Look like in the auditbeat a bit different approach,
Let me check what exactly is happening with auditbeat and heartbeat,

**Comment by dliappis** [comment]
As discussed in https://elastic.slack.com/archives/C06RF2SAWMS/p1712939449632559?thread_ts=1712837078.468979&cid=C06RF2SAWMS, I suggest we close this PR.

**Pull request closed without merging**
