### PR TITLE
Docker module

### PR DESCRIPTION
**Pull request by ruflin**
I did run the following commands on top of the repo:

```
make clean-vendor
cd metricbeat
make collect
git add docs/modules/docker.asciidoc etc/kibana/dashboard/ etc/kibana/search/ etc/kibana/visualization/
git commit ...
```

### CODE REVIEW

**Comment by douaejeouit** [comment]
@ruflin Yes, every thing is ok for me . Could you please  check it #2444 ?

**Comment by ruflin** [comment]
@douaejeouit The part that surprises me is that in your diff there are many more files? Did you run all the commands (including the vendor cleanup)?

**Comment by douaejeouit** [comment]
@ruflin sure I did ! 😢 !! 😿

**Comment by ruflin** [comment]
@douaejeouit I cloned again your branch and if I run `make collect` I get a lot of files that changed and were not commited. What do you get if you run `make collect` and then `git status`?

**Comment by douaejeouit** [comment]
@ruflin  when i first runned the make collect, I got the same results, it generate a lot of files that changed, so I commited them. Now, only metricbeat/include/list.go changes, which is normal!

**Comment by ruflin** [comment]
Below is the output I get. Did you perhaps put etc. under ignored or something like that? What happens if you run `git add etc/kibana/dashboard/`?

```
ruflin:metricbeat ruflin$ git status
On branch docker-test-delete
Changes not staged for commit:
  (use "git add/rm <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   docs/fields.asciidoc
        modified:   docs/modules/docker.asciidoc
        modified:   docs/modules/postgresql.asciidoc
        modified:   docs/modules/system.asciidoc
        modified:   etc/beat.full.yml
        modified:   etc/fields.yml
        modified:   etc/kibana/index-pattern/metricbeat.json
        deleted:    etc/kibana/kibana/dashboard/Metricbeat-Apache-HTTPD-server-status.json
        deleted:    etc/kibana/kibana/dashboard/Metricbeat-cpu.json
        deleted:    etc/kibana/kibana/dashboard/Metricbeat-filesystem-per-Host.json
        deleted:    etc/kibana/kibana/dashboard/Metricbeat-filesystem.json
        deleted:    etc/kibana/kibana/dashboard/Metricbeat-memory.json
        deleted:    etc/kibana/kibana/dashboard/Metricbeat-network.json
        deleted:    etc/kibana/kibana/dashboard/Metricbeat-overview.json
        deleted:    etc/kibana/kibana/dashboard/Metricbeat-processes.json
        deleted:    etc/kibana/kibana/dashboard/Metricbeat-system-overview.json
        deleted:    etc/kibana/kibana/index-pattern/metricbeat.json
        deleted:    etc/kibana/kibana/search/Apache-HTTPD.json
        deleted:    etc/kibana/kibana/search/Cpu-Load-stats.json
        deleted:    etc/kibana/kibana/search/Cpu-stats.json
        deleted:    etc/kibana/kibana/search/Filesystem-stats.json
        deleted:    etc/kibana/kibana/search/Fsstats.json
        deleted:    etc/kibana/kibana/search/Load-stats.json
        deleted:    etc/kibana/kibana/search/Memory-stats.json
        deleted:    etc/kibana/kibana/search/Network-data.json
        deleted:    etc/kibana/kibana/search/Process-stats.json
        deleted:    etc/kibana/kibana/search/System-stats.json
        deleted:    etc/kibana/kibana/visualization/Apache-HTTPD-CPU.json
        deleted:    etc/kibana/kibana/visualization/Apache-HTTPD-Hostname-list.json
        deleted:    etc/kibana/kibana/visualization/Apache-HTTPD-Load1-slash-5-slash-15.json
        deleted:    etc/kibana/kibana/visualization/Apache-HTTPD-Scoreboard.json
        deleted:    etc/kibana/kibana/visualization/Apache-HTTPD-Total-accesses-and-kbytes.json
        deleted:    etc/kibana/kibana/visualization/Apache-HTTPD-Uptime.json
        deleted:    etc/kibana/kibana/visualization/Apache-HTTPD-Workers.json
        deleted:    etc/kibana/kibana/visualization/Available-Memory.json
        deleted:    etc/kibana/kibana/visualization/CPU-Usage.json
        deleted:    etc/kibana/kibana/visualization/CPU-usage-over-time.json
        deleted:    etc/kibana/kibana/visualization/CPU-usage-per-process.json
        deleted:    etc/kibana/kibana/visualization/Disk-space-distribution.json
        deleted:    etc/kibana/kibana/visualization/Disk-space-overview.json
        deleted:    etc/kibana/kibana/visualization/Disk-space.json
        deleted:    etc/kibana/kibana/visualization/Disk-utilization-over-time.json
        deleted:    etc/kibana/kibana/visualization/Free-disk-space-over-days.json
        deleted:    etc/kibana/kibana/visualization/In-vs-Out-Network-Bytes.json
        deleted:    etc/kibana/kibana/visualization/Memory-usage-over-time.json
        deleted:    etc/kibana/kibana/visualization/Memory-usage-per-process.json
        deleted:    etc/kibana/kibana/visualization/Memory-usage.json
        deleted:    etc/kibana/kibana/visualization/Network-Bytes.json
        deleted:    etc/kibana/kibana/visualization/Network-Packetloss.json
        deleted:    etc/kibana/kibana/visualization/Number-of-Pids.json
        deleted:    etc/kibana/kibana/visualization/Number-of-processes.json
        deleted:    etc/kibana/kibana/visualization/Packet-loss-on-interfaces.json
        deleted:    etc/kibana/kibana/visualization/Servers-overview.json
        deleted:    etc/kibana/kibana/visualization/Swap-usage-over-time.json
        deleted:    etc/kibana/kibana/visualization/Swap-usage.json
        deleted:    etc/kibana/kibana/visualization/System-Load-over-time.json
        deleted:    etc/kibana/kibana/visualization/System-Navigation.json
        deleted:    etc/kibana/kibana/visualization/System-load.json
        deleted:    etc/kibana/kibana/visualization/System-overview-by-host.json
        deleted:    etc/kibana/kibana/visualization/Top-10-interfaces.json
        deleted:    etc/kibana/kibana/visualization/Top-disks-by-memory-usage.json
        deleted:    etc/kibana/kibana/visualization/Top-hosts-by-CPU-usage.json
        deleted:    etc/kibana/kibana/visualization/Top-hosts-by-disk-size.json
        deleted:    etc/kibana/kibana/visualization/Top-hosts-by-memory-usage.json
        deleted:    etc/kibana/kibana/visualization/Top-processes-by-CPU-usage.json
        deleted:    etc/kibana/kibana/visualization/Top-processes-by-memory-usage.json
        deleted:    etc/kibana/kibana/visualization/Total-Memory.json
        deleted:    etc/kibana/kibana/visualization/Total-files-over-days.json
        modified:   metricbeat.full.yml

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        etc/kibana/dashboard/
        etc/kibana/search/
        etc/kibana/visualization/
```

**Comment by ruflin** [comment]
Closing in favor of https://github.com/elastic/beats/pull/2625

**Pull request closed without merging**
