### PR TITLE
fix --strict.perms option

### PR DESCRIPTION
**Pull request by caub**

### CODE REVIEW

**Comment by ruflin** [comment]
@caub Thanks for the fix
@dedemorton Seems like we have this in all versions up to master. Which other versions should we fix it in?

**Comment by dedemorton** [comment]
@ruflin I believe the command works with either one or two dashes, right? If so, it's good to make this change for the sake of consistency, but I don't think it's worth backporting to all the releases.

**Comment by dedemorton** [comment]
@ruflin Actually, this won't backport very easily because I've refactored the content. I can take this over and make the change in the necessary branches after this PR is merged.

**Comment by ruflin** [comment]
@dedemorton You are of course right and both options work. In this case I think we should only adjust it in master as it doesn't break anything.

@caub Did you hit any issues with the option or is this mainly for consistency?

**Comment by caub** [comment]
@ruflin oh you mean `-strict.perms=false` is also valid? I was a bit struggling to run filebeat in docker, with the permissions checks. I ended up doing `filebeat --help` and noticed it shows `--strict.perms` so I thought it was a typo in the docs. Sorry if not

**Comment by ruflin** [comment]
@caub Yes, both work. But we have `--` in the `-h` part.

**Comment by caub** [comment]
then we could close this PR, sorry again

**Comment by dedemorton** [comment]
I think the change is worth making because other users might be confused by inconsistent info. I have a PR in progress right now and will add this change so it gets into master and the 6.x branches.

**Comment by ruflin** [comment]
Ok, lets close this PR as otherwise we have it in the 5.3 release and not the others. But with the changes from @dedemorton we will have it in all 6.x release.

@caub Thanks for bringing this up.

**Pull request closed without merging**
