### PR TITLE
[Docs] Fixed metricbeat redis exported field CPU descriptions

### PR DESCRIPTION
**Pull request by joostdecock**
## What does this PR do?

Fixed descriptions that were mixed up.

## Why is it important?

The name is pretty self-explanatory, but still. Documentation shouldn't lie.

## Author's Checklist

- [ ] Not sure if this requires a CHANGELOG entry? 

## How to test this PR locally

Docs changes only

## Use cases

People looking up the definition of the exported fields should get correct results.

### CODE REVIEW

**Comment by jsoriano** [comment]
Hey @joostdecock,

This change should be applied in master first, could you please rebase the PR?

Also, the file you changed is autogenerated, these changes should be done in the fields definition in the redis module, [here](https://github.com/elastic/beats/blob/6a84a805142bf4036c350c1c43962cc1e252d40b/metricbeat/module/redis/info/_meta/fields.yml#L65).

Thanks!

**Comment by joostdecock** [comment]
Can't really remember how I ended up selecting a branch :thinking: 

As for updating an auto-generated file: I clicked that **Edit this file on github** link in the docs.
I didn't expect it to be a trap :wink: 

At work now, will let this sit in my inbox for later.

**Comment by jsoriano** [comment]
>  I didn't expect it to be a trap :wink:

Oops, sorry, yes, I think this button should be improved :grimacing: 

@dedemorton do you know if there is something we can do to make this link point to the correct file in the master branch?

**Comment by dedemorton** [comment]
@joostdecock We definitely don't want the documentation to lie, so thank you for submitting this request! 

@jsoriano There used to be a way to override edit links, but I think that went away with some "improvements" we made to the doc build. It might still be possible, but I don't think it's a good idea because in many cases you need to run `make update` after updating the source files anyhow. 

So...whenever a PR comes in from the community through the Edit link, I'm happy to make the changes needed to get the doc build running, then I'll backport and/or forwardport the commit.

I don't want folks to feel discouraged about contributing to the docs, or feel like they need to get up to speed on our build environment just to make a few simple edits.

Feel free to assign PRs like this to me in the future, and I'll take care of them.

**Comment by dedemorton** [comment]
The commit I pushed should fix the build problem. I'll take care of merging and backporting. Thanks!

**Comment by dedemorton** [comment]
jenkins run the tests please

**Comment by jsoriano** [comment]
Thanks @dedemorton!

**Pull request merged**
