### PR TITLE
Output IO counters

### PR DESCRIPTION
**Pull request by urso**
introduce counters (bytes send/received and errors) to elasticsearch, logstash
and redis outputs

### CODE REVIEW

**Comment by ruflin** [comment]
LGTM. Some of the tests fail.

**Comment by zstyblik** [comment]
Hello,

is documentation for this feature planned as well? Or, please, can you provide me with link to documentation related to this feature?

Thank you.

**Comment by urso** [comment]
@zstyblik this is currently for internal use only. We're considering some proper monitoring support for beats, but this is not it.

**Comment by jstangroome** [comment]
Even just in this form, this kind of IO monitoring would be extremely useful.

For the "proper monitoring support" you are considering, is there a thread somewhere we can follow?

**Comment by ruflin** [comment]
Best is to follow this issue here: https://github.com/elastic/beats/issues/463

**Pull request merged**
