### PR TITLE
Merge pull request 773 (adding username to topbeat)

### PR DESCRIPTION
**Pull request by tsg**
This is merging #773 and in addition updating the vendored gosigar.

### CODE REVIEW

**Comment by andrewkroh** [comment]
LGTM. We should really add a system test case for `Username`.

**Comment by tsg** [comment]
@andrewkroh Good point. I think it's easy enough for me to add it in this one, so we're sure we don't forget about it.

**Comment by andrewkroh** [comment]
I implemented a test case for this and opened a PR to this branch. https://github.com/tsg/beats/pull/1

**Comment by tsg** [comment]
Sub-PR merged :)

**Comment by biswajit86** [comment]
Could you please update the field_name that is exposed by this change in the [list of topbeat fields ].(https://github.com/elastic/beats/blob/master/topbeat/docs/fields.asciidoc). 

Is it `username` or `Username`

**Comment by andrewkroh** [comment]
It's `proc.username`. I will be updating fields.asciidoc for this shortly.

**Pull request merged**
