### PR TITLE
Clarify support for Redis output

### PR DESCRIPTION
**Pull request by dedemorton**
@urso Please review. I changed the language a bit from the text that I gave earlier.

### CODE REVIEW

**Comment by monicasarbu** [comment]
LGTM

**Comment by dedemorton** [comment]
@monicasarbu When I rebased, I realized that the language I used here was kind of ambiguous. You should take another look before merging.

**Comment by tsg** [comment]
@dedemorton this one should be cherry-picked to the 1.2 branch, I think.

**Comment by dedemorton** [comment]
@tsg It's on my list. Was just waiting to see if @urso wanted me to add more detail.

**Pull request merged**
