### PR TITLE
[Ingest Manager] Use symlink path for reexecutions

### PR DESCRIPTION
**Pull request by michalpristas**
## What does this PR do?

This PR initiates reexec manager with the path to symlink instead of `os.Executable` which might point to actual executable even if executed using symlink.  This behavior leads to reexecing into same binary/version even after upgrade is done.

Tested on linux/windows.
This happens on some OSes as behavior differs in evaluating symlinks. Some refer to symlink file as a process executable some follow symlink and refer to an actual executable.

This is visible during upgrade when upgrade is successfully finished but after reboot it boots up same process (visible as version unchanged in fleet UI).

## Why is it important?

Upgrade scenario
Fixes: #21935

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by ph** [comment]
Any issue linked to this?

**Comment by EricDavisX** [comment]
Any commentary on when this could potentially happen, sp we can improve test coverage?

**Comment by michalpristas** [comment]
@EricDavisX updated description

**Review by blakerouse — APPROVED** [review]
Looks good.

**Pull request merged**
