### PR TITLE
docs: update docs versions 7.9.1

### PR DESCRIPTION
**Pull request by kuisathaverat**
Updates docs versions to 7.9.1. 
Merge before the final Release build.
Ingest-dev ticket: https://github.com/elastic/ingest-dev/issues/771

### CODE REVIEW

**Comment by kuisathaverat** [comment]
@urso I dunno why the `make update` is changing too many files, it removes imports and some whitespace, is it correct?

**Review by cachedout — APPROVED** [review]

**Review by cachedout — COMMENTED** [review]
This seems like it changes a lot that is unrelated to a docs version bump?

**Comment by kuisathaverat** [comment]
> This seems like it changes a lot that is unrelated to a docs version bump?

yep, https://github.com/elastic/beats/pull/20856#issuecomment-683758612 and it breaks the lint so it is weird

**Comment by kuisathaverat** [comment]
superseded by https://github.com/elastic/beats/pull/20873/files

**Comment by kuisathaverat** [comment]
the culprit is `go mod tidy` for some reason remove dependencies in my local

```
go mod tidy -v
go: finding module for package github.com/cespare/xxhash
go: found github.com/cespare/xxhash in github.com/cespare/xxhash v1.1.0
unused github.com/cespare/xxhash/v2
unused github.com/cloudfoundry-community/go-cfclient
unused github.com/davecgh/go-xdr
unused github.com/elastic/go-perf
unused github.com/elastic/go-seccomp-bpf
unused github.com/hashicorp/go-multierror
unused github.com/hashicorp/go-retryablehttp
unused github.com/hectane/go-acl
```

**Comment by kuisathaverat** [comment]
It happens also in a Docker container so is not my local

```
git clone git@github.com:elastic/beats.git
export GO_VERSION=$(cat .go-version); 
cd beats;
docker run -it \
    -v $(pwd):/tmp/src/github.com/elastic/beats/v7 \
    -u $(id -u):$(id -g) \
    -w /tmp/src/github.com/elastic/beats/v7 \
    -e HOME=/tmp \
    -e GOPATH=/tmp \
    golang:${GO_VERSION} \
    go mod tidy -v
```

**Pull request closed without merging**
