### PR TITLE
fix connection leak in the mongodb module

### LINKED ISSUE #5688: Metricbeat MongoDB Connection Leak
Each of the MongoDB metricsets (status, dbstats) create a new session for each `Fetch` by do not close the session that they open. Each metricset should have a `defer session.Close()` (or similar).

https://github.com/elastic/beats/blob/84e2e0953a4983065c96f240f6e8a6212940565c/metricbeat/module/mongodb/status/status.go#L62

https://github.com/elastic/beats/blob/84e2e0953a4983065c96f240f6e8a6212940565c/metricbeat/module/mongodb/dbstats/dbstats.go#L60

For confirmed bugs, please report:
- Version: 5.x / 6.x
- Operating System: all
- Discuss: https://discuss.elastic.co/t/metricbeat-mongodb-leaks-connections-when-metricbeat-config-modules-reload-enabled-set-to-true/108723?u=andrewkroh
- Steps to Reproduce: Enable the mongodb module.

### PR DESCRIPTION
**Pull request by mountkin**
Fixes #5688

### CODE REVIEW

**Comment by mountkin** [comment]
CLA signed

**Comment by kvch** [comment]
jenkins, test it

**Comment by ruflin** [comment]
Thanks for fixing this. I think we missed that change in https://github.com/elastic/beats/pull/5120 where we moved it from init to fetch. Previously it was just one connection we leaked, now it can be many more.

**Comment by ruflin** [comment]
@mountkin Could you add an entry to the Changelog file?

**Comment by mountkin** [comment]
@ruflin Changelog entry added

**Comment by exekias** [comment]
Thank you so much @mountkin!

**Pull request merged**
