### PR TITLE
[DOC] labels.dedot option for add_kubernetes_metadata processor

### PR DESCRIPTION
**Pull request by Monpoke**
- Docs

## What does this PR do?

Following source code, it seems the `labels.dedot` and `annotations.dedot`options are undocumented. This PR is a documentation improvement.

It was needed for our filebeat migration from 6.6 to 7.16, because their default behavior changed starting 7.0.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Relates #9939
- Relates  #10338

### CODE REVIEW

**Comment by Monpoke** [comment]
run elasticsearch-ci/docs

**Comment by ChrsMark** [comment]
@Monpoke thanks for opening this!
I created https://github.com/elastic/beats/pull/30841 to target against `main` branch cause this PR was against 7.17 and changing the target was almost impossible through Github. I will add you as co-author in the commits.

**Comment by Monpoke** [comment]
> @Monpoke thanks for opening this! I created #30841 to target against `main` branch cause this PR was against 7.17 and changing the target was almost impossible through Github. I will add you as co-author in the commits.

This is not a problem for me, thanks for the merge!
I'm closing this PR.

**Pull request closed without merging**
