### PR TITLE
Revert "[AWS Cloudwatch] Fix Tags for APIGW"

### PR DESCRIPTION
**Pull request by ycombinator**
Reverts elastic/beats#40755 because since that PR was merged, we're seeing the https://buildkite.com/elastic/beats-packaging-pipeline consistently failing like so when it tries to run `mage package` on Agentbeat:

```
# github.com/elastic/beats/v7/x-pack/agentbeat
/usr/local/go/pkg/tool/linux_amd64/link: running aarch64-linux-gnu-gcc failed: exit status 1
/usr/lib/gcc-cross/aarch64-linux-gnu/6/../../../../aarch64-linux-gnu/bin/ld.gold: internal error in maybe_apply_stub, at ../../gold/aarch64.cc:5407
collect2: error: ld returned 1 exit status
Error: running "go build -o build/golang-crossbuild/agentbeat-linux-arm64 -buildmode pie -gcflags=all=-N -l -tags=agentbeat -ldflags -X github.com/elastic/beats/v7/libbeat/version.buildTime=2024-10-03T12:37:52Z -X github.com/elastic/beats/v7/libbeat/version.commit=698951e8c895eff9d03a8d0ececadba3b8b4c6bb" failed with exit code 1
```

### CODE REVIEW

**Comment by ycombinator** [comment]
CI is green on this PR but I don't see the https://buildkite.com/elastic/beats-packaging-pipeline step being run on this PR.  Pinged @rowlandgeoff off-PR to ask why that might be.  Without knowing if this step succeeds on this PR, its hard to say with 100% confidence that merging this PR will make `main` CI green again.

**Review by rowlandgeoff — APPROVED** [review]

**Review by jlind23 — APPROVED** [review]

**Comment by jlind23** [comment]
@axw We might need your review on this to unblock Beats CI

**Review by axw — APPROVED** [review]
Approving to hopefully unblock CI, but there's nothing unusual in this PR, so seems like something more systemic needs addressing.

**Comment by ycombinator** [comment]
> Approving to hopefully unblock CI, but there's nothing unusual in this PR, so seems like something more systemic needs addressing.

Thanks @axw.  Yeah, nothing in the PR jumps out as the cause but this failure is (at least so far) only being observed with #40755.  Since we've merged this revert PR here, we haven't seen the same failure on `main`.  So it's something specific to #40755 that we'll need to dig into.

**Pull request merged**
