### PR TITLE
Enrich events with add_process_metadata

### PR DESCRIPTION
**Pull request by andrewkroh**
Combining the add_process_metadata processor with add_docker_metadata allows you to enrich events when you have a PID.

```
auditbeat.modules:
- module: audit
  metricsets: [kernel]
  kernel.audit_rules: |
    -a always,exit -F arch=b64 -S execve,execveat -k exec
  processors:
  - add_process_metadata:
      metadata_types: [container_id]
      pid_fields: ['audit.kernel.data.pid', 'audit.kernel.data.ppid']
      target.container_id: 'docker.container.id'
  - add_docker_metadata:
      match_fields: ['docker.container.id']
```
  
Download plugin: [add_process_metadata-linux-amd64-6.1.1.so.gz](https://github.com/elastic/beats/files/1604525/add_process_metadata-linux-amd64-6.1.1.so.gz)

Usage: `auditbeat --plugin /path/to/add_process_metadata-linux-amd64-6.1.1.so -e`

Output:

```
2018/01/04 20:03:36.475996 logger.go:29: DBG [add_process_metadata] using cached cgroups for pid=15233
2018/01/04 20:03:36.476171 processor.go:275: DBG [publish] Publish event: {
  "@timestamp": "2018-01-04T20:03:36.472Z",
  "@metadata": {
    "beat": "auditbeat",
    "type": "doc",
    "version": "6.1.1"
  },
  "audit": {
    "kernel": {
      "record_type": "syscall",
      "action": "executed",
      "paths": [
        {
          "nametype": "NORMAL",
          "ouid": "root",
          "rdev": "00:00",
          "dev": "00:2b",
          "inode": "21",
          "name": "/bin/cat",
          "ogid": "root",
          "item": "0",
          "mode": "0100755"
        }
      ],
      "thing": {
        "what": "file",
        "primary": "/bin/cat",
        "secondary": "21"
      },
      "category": "audit-rule",
      "how": "/bin/cat",
      "key": "exec",
      "sequence": 18067,
      "session": "unset",
      "data": {
        "fe": "0",
        "fi": "0000000000000000",
        "fver": "0",
        "a0": "123ef10",
        "a1": "123eec0",
        "a3": "8",
        "argc": "2",
        "exit": "0",
        "proctitle": "cat",
        "tty": "pts2",
        "cwd": "/",
        "new_pp": "00000000a80425fb",
        "old_pe": "00000000a80425fb",
        "pid": "23031",
        "ppid": "15233",
        "new_pi": "00000000a80425fb",
        "old_pi": "00000000a80425fb",
        "old_pp": "00000000a80425fb",
        "arch": "x86_64",
        "comm": "cat",
        "exe": "/bin/cat",
        "fp": "0000000000000000",
        "new_pe": "00000000a80425fb",
        "syscall": "execve",
        "a2": "123eed8",
        "cmdline": "\"cat\" \"/etc/gshadow\""
      },
      "actor": {
        "primary": "unset",
        "secondary": "root",
        "attrs": {
          "auid": "unset",
          "fsgid": "root",
          "fsuid": "root",
          "gid": "root",
          "sgid": "root",
          "egid": "root",
          "euid": "root",
          "suid": "root",
          "uid": "root"
        }
      },
      "result": "success"
    }
  },
  "metricset": {
    "module": "audit",
    "name": "kernel"
  },
  "docker": {
    "container": {
      "id": "5bee224b593f997d856e18615ac100494a75c7e57f092e104e9a79a70daa1748",
      "image": "busybox",
      "name": "pedantic_bardeen"
    }
  },
  "beat": {
    "version": "6.1.1",
    "name": "instance-1",
    "hostname": "instance-1"
  }
}
```

### CODE REVIEW

**Comment by ruflin** [comment]
@andrewkroh Is there a reason you opened this against 6.1?

**Comment by andrewkroh** [comment]
After some discussion with @ruflin I think I will enhance `add_docker_metadata` with the ability to correlate based on PID. We can eventually add an `add_process_metadata` processor as the need arises.

WDYT @exekias?

**Comment by monicasarbu** [comment]
In my opinion, it makes more sense to be part of the `add_docker_metadata`. I like the idea of having the `add_process_metadata`.

**Comment by exekias** [comment]
That sounds great @andrewkroh, this is a great addition!

**Comment by andrewkroh** [comment]
This is being moved to `add_docker_metadata`. See #6100.

**Pull request closed without merging**
