### PR TITLE
Fix source.address not being set for nginx ingress_controller

### PR DESCRIPTION
**Pull request by chendo**
Fixes source.address not being set on the nginx ingress_controller fileset.

This is referencing a variable that doesn't exist, presumably copied from the access pipeline definition.

PS. This is a one word change, happy for a maintainer just to make the change for me to simplify workflow. 
## What does this PR do?

This PR fixes the reference to the correct field for ingress_controller.

## Why is it important?

Source IP is not being populated correctly, thus all the geolocation stuff won't work.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by ChrsMark** [comment]
@chendo thank you for reporting this and for supplying the fix! I opened a PR for this since it requires tests to be tuned accordingly. I would suggest you sign the CLA and provide me your email used in your GH account in order to add you as a co-author of this fix, wdyt?

**Comment by chendo** [comment]
> @chendo thank you for reporting this and for supplying the fix! I opened a PR for this since it requires tests to be tuned accordingly. I would suggest you sign the CLA and provide me your email used in your GH account in order to add you as a co-author of this fix, wdyt?

I've signed the CLA. My GH email is github at chen.do

**Comment by ChrsMark** [comment]
@chendo the fix is already on master https://github.com/elastic/beats/commit/8e29ab772dddb6df40ee9457729b1a621af0e200! Thank you again!

**Comment by chendo** [comment]
@ChrsMark wow, that was fast! Thank you for making it easy :shipit:

**Pull request closed without merging**
