### PR TITLE
[AWS] Fix aws.cloudtrail.request_id parsing

### PR DESCRIPTION
**Pull request by turuncuofke**
## What does this PR do?

This PR fixes a parsing pipeline typo in the AWS Cloudtrail logs.

## Why is it important?

Without this fix, AWS Cloudtrail logs do not have "requestID" field.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
Thank you for your PR! Could you sign the CLA please?

**Comment by kaiyan-sheng** [comment]
Also, could you also run `GENERATE=true TESTING_FILEBEAT_MODULES=aws TESTING_FILEBEAT_FILESETS=cloudtrail mage -v pythonIntegTest` to update all the `-expected.json` files under https://github.com/elastic/beats/tree/main/x-pack/filebeat/module/aws/cloudtrail/test please? Thank you!

**Comment by turuncuofke** [comment]
Thank you for your reply @kaiyan-sheng ! I might need some help. I have already signed the CLA for a few times and when I clicked on Finish it says `You’ll receive an email copy once everyone has signed.` but no email is sent to me. So I don't know what to do about it. 

Screenshot 2022-09-23 at 10 23 49

Secondly, I have tried to run the command you have asked me to run but i couldn't find in which directory to run the command. I tried running it in the https://github.com/elastic/beats/tree/main/filebeat directory but it keeps giving me errors.

**Comment by kaiyan-sheng** [comment]
Looks like we are good on the CLA side! Thank you!!

> Secondly, I have tried to run the command you have asked me to run but i couldn't find in which directory to run the command. I tried running it in the https://github.com/elastic/beats/tree/main/filebeat directory but it keeps giving me errors.

Sorry I should have be more clear, please try run this command under `elastic/beats/x-pack/filebeat` with your change. This command will take a while to complete.

**Comment by turuncuofke** [comment]
Sorry for the late reply but I'm still having errors when i try to run the command:

```
GENERATE=true TESTING_FILEBEAT_MODULES=aws TESTING_FILEBEAT_FILESETS=cloudtrail mage -v pythonIntegTest
Running target: PythonIntegTest
Running dependency: github.com/elastic/beats/v7/dev-tools/mage.BuildSystemTestBinary
Running dependency: Fields
Running dependency: Dashboards
exec: go "test" "-c" "-o" "filebeat.test"
Running dependency: processorsFieldsGo
exec: go "list" "-m"
Running dependency: inputFieldsGo
Running dependency: fieldsYML
Running dependency: moduleFieldsGo
Found Elastic Beats dir at /Users/mac/projects/beats
exec: go "run" "/Users/mac/projects/beats/dev-tools/cmd/module_fields/module_fields.go" "-beat" "filebeat" "-license" "Elastic" "/Users/mac/projects/beats/x-pack/filebeat/input"
exec: go "run" "/Users/mac/projects/beats/dev-tools/cmd/module_fields/module_fields.go" "-beat" "filebeat" "-license" "Elastic" "/Users/mac/projects/beats/x-pack/filebeat/processors"
exec: go "run" "-mod=readonly" "/Users/mac/projects/beats/libbeat/scripts/cmd/global_fields/main.go" "-es_beats_path" "/Users/mac/projects/beats" "-beat_path" "/Users/mac/projects/beats/filebeat" "-out" "fields.yml" "/Users/mac/projects/beats/filebeat/module" "module" "input" "processors"
exec: go "run" "/Users/mac/projects/beats/dev-tools/cmd/module_fields/module_fields.go" "-beat" "filebeat" "-license" "Elastic" "/Users/mac/projects/beats/x-pack/filebeat/module"
No fields files for module azureblobstorage
No fields files for module azureeventhub
No fields files for module cloudfoundry
No fields files for module cometd
No fields files for module default-inputs
No fields files for module gcppubsub
No fields files for module gcs
No fields files for module http_endpoint
No fields files for module httpjson
No fields files for module add_nomad_metadata
No fields files for module o365audit
BuildSystemTestGoBinary (go test -c -o filebeat.test) took 6.028338651s.
Generated fields.yml for filebeat to /Users/mac/projects/beats/x-pack/filebeat/fields.yml
>> Building docker images
exec: git "rev-parse" "HEAD"
exec: docker-compose "-p" "filebeat_8_5_0_c56e17b5e6-snapshot" "build" "--force-rm"
elasticsearch uses an image, skipping
proxy_dep uses an image, skipping
Building cometd
[+] Building 3.1s (8/8) FINISHED                                                                                                                 
 => [internal] load build definition from Dockerfile                                                                                        0.1s
 => => transferring dockerfile: 37B                                                                                                         0.0s
 => [internal] load .dockerignore                                                                                                           0.0s
 => => transferring context: 2B                                                                                                             0.0s
 => [internal] load metadata for docker.elastic.co/observability/stream:v0.6.1                                                              2.8s
 => [internal] load build context                                                                                                           0.0s
 => => transferring context: 63B                                                                                                            0.0s
 => [1/3] FROM docker.elastic.co/observability/stream:v0.6.1@sha256:3468c172014a0acba5af1bd9cc2ecb0b80e287ec832b26e7b47e42241b4197f3        0.0s
 => CACHED [2/3] RUN apt update &&     apt -y install curl                                                                                  0.0s
 => CACHED [3/3] COPY files /files                                                                                                          0.0s
 => exporting to image                                                                                                                      0.0s
 => => exporting layers                                                                                                                     0.0s
 => => writing image sha256:ee64dce167f707d1d67d5005d4b54903080ba255cbbc966f3bcd1852f78a3020                                                0.0s
 => => naming to docker.io/library/filebeat_8_5_0_c56e17b5e6-snapshot_cometd                                                                0.0s
exec: docker-compose "-p" "filebeat_8_5_0_c56e17b5e6-snapshot" "up" "--detach"
WARNING: Found orphan containers (filebeat_8_5_0_c56e17b5e6-snapshot_kibana_1, filebeat_8_5_0_c56e17b5e6-snapshot_redis_1, filebeat_8_5_0_c56e17b5e6-snapshot_mosquitto_1, filebeat_8_5_0_c56e17b5e6-snapshot_kafka_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Creating filebeat_8_5_0_c56e17b5e6-snapshot_elasticsearch_1 ... done
Creating filebeat_8_5_0_c56e17b5e6-snapshot_cometd_1        ... done
Creating filebeat_8_5_0_c56e17b5e6-snapshot_proxy_dep_1     ... done
>> python test: Integration Testing
exec: /Users/mac/projects/beats/build/ve/darwin/bin/pytest "--timeout=90" "--durations=20" "-v" "--junit-xml=build/TEST-python-integration.xml" "tests/system/test_filebeat_xpack.py" "tests/system/test_http_endpoint.py" "tests/system/test_xpack_modules.py"
============================================================== test session starts ==============================================================
platform darwin -- Python 3.10.6, pytest-6.2.4, py-1.10.0, pluggy-0.13.1 -- /Users/mac/projects/beats/build/ve/darwin/bin/python3.10
cachedir: .pytest_cache
rootdir: /Users/mac/projects/beats, configfile: pytest.ini
plugins: rerunfailures-9.1.1, timeout-1.4.2, otel-1.1.1
timeout: 90.0s
timeout method: signal
timeout func_only: True
collected 57 items                                                                                                                              

tests/system/test_filebeat_xpack.py::FilebeatXPackTest::test_export_config FAILED                                                         [  1%]
tests/system/test_filebeat_xpack.py::FilebeatXPackTest::test_export_ilm_policy FAILED                                                     [  3%]
tests/system/test_filebeat_xpack.py::FilebeatXPackTest::test_export_index_pattern FAILED                                                  [  5%]
tests/system/test_filebeat_xpack.py::FilebeatXPackTest::test_export_index_pattern_migration FAILED                                        [  7%]
tests/system/test_filebeat_xpack.py::FilebeatXPackTest::test_export_template FAILED                                                       [  8%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_correct_auth_header FAILED                                                   [ 10%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_empty_body FAILED                                                            [ 12%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_get_request FAILED                                                           [ 14%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_include_headers_empty_value FAILED                                           [ 15%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_include_headers_not_canonical_config FAILED                                  [ 17%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_include_headers_not_canonical_header FAILED                                  [ 19%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_include_headers_single_value FAILED                                          [ 21%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_include_headers_without_header FAILED                                        [ 22%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_invalid_hmac FAILED                                                          [ 24%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_malformed_json FAILED                                                        [ 26%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_missing_auth_value FAILED                                                    [ 28%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_preserve_original_event FAILED                                               [ 29%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_request FAILED                                                               [ 31%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_request_multiple_documents FAILED                                            [ 33%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_request_ndjson FAILED                                                        [ 35%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_valid_hmac FAILED                                                            [ 36%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_wrong_auth_header FAILED                                                     [ 38%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_wrong_auth_value FAILED                                                      [ 40%]
tests/system/test_http_endpoint.py::Test::test_http_endpoint_wrong_content_header FAILED                                                  [ 42%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_00_aws FAILED                                                            [ 43%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_01_aws FAILED                                                            [ 45%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_02_aws FAILED                                                            [ 47%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_03_aws FAILED                                                            [ 49%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_04_aws FAILED                                                            [ 50%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_05_aws FAILED                                                            [ 52%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_06_aws FAILED                                                            [ 54%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_07_aws FAILED                                                            [ 56%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_08_aws FAILED                                                            [ 57%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_09_aws FAILED                                                            [ 59%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_10_aws FAILED                                                            [ 61%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_11_aws FAILED                                                            [ 63%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_12_aws FAILED                                                            [ 64%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_13_aws FAILED                                                            [ 66%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_14_aws FAILED                                                            [ 68%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_15_aws FAILED                                                            [ 70%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_16_aws FAILED                                                            [ 71%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_17_aws FAILED                                                            [ 73%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_18_aws FAILED                                                            [ 75%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_19_aws FAILED                                                            [ 77%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_20_aws FAILED                                                            [ 78%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_21_aws FAILED                                                            [ 80%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_22_aws FAILED                                                            [ 82%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_23_aws FAILED                                                            [ 84%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_24_aws FAILED                                                            [ 85%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_25_aws FAILED                                                            [ 87%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_26_aws FAILED                                                            [ 89%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_27_aws FAILED                                                            [ 91%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_28_aws FAILED                                                            [ 92%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_29_aws FAILED                                                            [ 94%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_30_aws FAILED                                                            [ 96%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_31_aws FAILED                                                            [ 98%]
tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_32_aws FAILED                                                            [100%]Traceback (most recent call last):
  File "/Users/mac/projects/beats/build/ve/darwin/bin/pytest", line 8, in <module>
    sys.exit(console_main())
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/_pytest/config/__init__.py", line 185, in console_main
    code = main()
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/_pytest/config/__init__.py", line 162, in main
    ret: Union[ExitCode, int] = config.hook.pytest_cmdline_main(
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/pluggy/callers.py", line 208, in _multicall
    return outcome.get_result()
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/_pytest/main.py", line 316, in pytest_cmdline_main
    return wrap_session(config, _main)
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/_pytest/main.py", line 304, in wrap_session
    config.hook.pytest_sessionfinish(
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/pluggy/hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/pluggy/manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/pluggy/manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/pluggy/callers.py", line 203, in _multicall
    gen.send(outcome)
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/_pytest/terminal.py", line 803, in pytest_sessionfinish
    outcome.get_result()
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/pluggy/callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/pluggy/callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/pytest_otel/__init__.py", line 266, in pytest_sessionfinish
    end_span(session_name, exitCodeToOutcome(exitstatus))
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/pytest_otel/__init__.py", line 163, in end_span
    spans[span_name].end()
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/opentelemetry/sdk/trace/__init__.py", line 865, in end
    self._span_processor.on_end(self._readable_span())
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/opentelemetry/sdk/trace/__init__.py", line 161, in on_end
    sp.on_end(span)
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/opentelemetry/sdk/trace/export/__init__.py", line 96, in on_end
    token = attach(set_value(_SUPPRESS_INSTRUMENTATION_KEY, True))
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/opentelemetry/context/__init__.py", line 116, in set_value
    context = get_current()
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/opentelemetry/context/__init__.py", line 67, in wrapper
    return func(*args, **kwargs)  # type: ignore[misc]
  File "/Users/mac/projects/beats/build/ve/darwin/lib/python3.10/site-packages/opentelemetry/context/__init__.py", line 131, in get_current
    return _RUNTIME_CONTEXT.get_current()  # type:ignore
AttributeError: 'NoneType' object has no attribute 'get_current'
>> python test: Integration Testing Complete
exec: docker-compose "-p" "filebeat_8_5_0_c56e17b5e6-snapshot" "logs" "--no-color"
exec: docker-compose "-p" "filebeat_8_5_0_c56e17b5e6-snapshot" "rm" "--stop" "--force"
Stopping filebeat_8_5_0_c56e17b5e6-snapshot_elasticsearch_1 ... done
Stopping filebeat_8_5_0_c56e17b5e6-snapshot_cometd_1        ... done
Removing filebeat_8_5_0_c56e17b5e6-snapshot_proxy_dep_1     ... done
Removing filebeat_8_5_0_c56e17b5e6-snapshot_elasticsearch_1 ... done
Removing filebeat_8_5_0_c56e17b5e6-snapshot_cometd_1        ... done
Error: running "/Users/mac/projects/beats/build/ve/darwin/bin/pytest --timeout=90 --durations=20 -v --junit-xml=build/TEST-python-integration.xml tests/system/test_filebeat_xpack.py tests/system/test_http_endpoint.py tests/system/test_xpack_modules.py" failed with exit code 1```

**Comment by kaiyan-sheng** [comment]
@turuncuofke Sorry for the late response! I'm having a different issue when running this command 😂 But my teammate is able to run it still. @girodav Could you push the change here or open a separate PR please? Thank you!!

**Review by kaiyan-sheng — APPROVED** [review]
Thank you for fixing this! We also need a changelog entry for this bug fix :)

**Comment by turuncuofke** [comment]
@kaiyan-sheng Thank you so much for your nice messages and helpful attitude!! I'm glad that I could help. I will be waiting for future updates and releases on beats, good luck. :)

Also, @girodav thanks for the help.

**Comment by kaiyan-sheng** [comment]
Hi @turuncuofke I just merged the PR that will fix the CI. Could you pull the latest main branch and rebase your PR please? Thank you so much!!

**Comment by turuncuofke** [comment]
I think I messed it up due to lack of my knowledge about git but you saved it. Thanks! <3

**Comment by kaiyan-sheng** [comment]
@turuncuofke All good, thanks! I will merge this PR and take care of the backports.

**Pull request merged**
