### PR TITLE
[system/cpu,core] - Disable performance counter by default to unblock agent CI

### PR DESCRIPTION
**Pull request by VihasMakwana**
Alternative to https://github.com/elastic/beats/pull/42042.

This is a temporary fix as CI on elastic-agent's main is broken https://buildkite.com/elastic/elastic-agent-extended-testing/builds/5390#0193c17f-c655-422a-8dc9-ae5a7a40fdbd. 

This most likely happened because user not having enough permissions to read from performance counter. I'll do some more digging and fix the underlying issue.

### CODE REVIEW

**Review by andrzej-stencel — APPROVED** [review]

**Comment by VihasMakwana** [comment]
> I'll do some more digging and fix the underlying issue.

Sadly, the only way to fix it is by add the user to "Performance Monitoring Users" group on Windows.
When I was testing this in unprivileged mode on my VM, the `elastic-agent` user was already a member of the group, so I overlooked this detail.

@leehinman @cmacknz what should be the best way to proceed?
1. Disabling this by default and updating the docs with required info.
    - I tend to prefer this option. 
2. Enabling them and throwing warning, if any error is encountered.

**Comment by cmacknz** [comment]
Whether to use performance counters or not needs to become an explicit configuration exposed in the system integration as well as the module. Because this is configuration, in theory in the agent tests affected by this an agent PR that sets his same configuration to false could be made directly in agent so we don't have to wait for a new DRA build. Since it isn't in the integration yet, the fleet overrides API could be used.

Ideally, we would add ourselves to the Performance Monitor Users group automatically, but this will not help agents that were not already installed, so we need a way to handle that. Maybe just having it be configurable with the default value controlled by whether we are in the right group.

The DataDog agent installer adds itself to the performance monitor users group and some others for example https://docs.datadoghq.com/agent/guide/windows-agent-ddagent-user/

**Review by cmacknz — APPROVED** [review]

**Comment by cmacknz** [comment]
Please create an issue to track this problem so we don't lose the discussion in this PR

**Comment by VihasMakwana** [comment]
> Please create an issue to track this problem so we don't lose the discussion in this PR

Sure.

**Pull request merged**
