### PR TITLE
[Heartbeat] configure permissions for synthetics config

### PR DESCRIPTION
**Pull request by vigneshshanmugam**
+ fix https://github.com/elastic/synthetics/issues/312
+ Provide directory level read,write and execute permissions to `.synthetics` directory inside the heartbeat synthetics image. 
+ `.synthetics` is used by the agent to post process screenshots 
+ Existing `suites` folder was never used and was a dead code.

### CODE REVIEW

**Review by andrewvc — APPROVED** [review]
LGTM, testing locally, manually

**Comment by vigneshshanmugam** [comment]
@Mergifyio update

**Comment by andrewvc** [comment]
@Mergifyio update

**Comment by vigneshshanmugam** [comment]
@mdelapenya E2E tests seem to fail all the time for this PR, Any idea why?

**Comment by mdelapenya** [comment]
> @mdelapenya E2E tests seem to fail all the time for this PR, Any idea why?

@vigneshshanmugam will take a look tomorrow morning. It seems the pipeline is not priority formed. Thanks for pinging me here

**Comment by mdelapenya** [comment]
@vigneshshanmugam we solved an issue when passing the BEAT_VERSION to the e2e tests here: https://github.com/elastic/beats/pull/26469

The existing 3 errors in the e2e are already present in master and 7.x branches, and we are investigating them.

**Comment by andrewvc** [comment]
@Mergifyio update

**Comment by urso** [comment]
Hm, only packaging of the docker image was updated. All these tests that are run here don't depend on packaging at all.

**Comment by urso** [comment]
Packaging went fine and PR can be merged without conflicts. I will merge it now, so we have it in.

**Comment by andrewvc** [comment]
@Mergifyio backport 7.x

**Pull request merged**
