### PR TITLE
Change codeowners for enterprise-search

### PR DESCRIPTION
**Pull request by tutelaris**
### Description
As an initiative to rename teams in the Search org from `ent-search-*` to `search-*`, it's required to change the code owners here.

This PR is dedicated to changing the codeowners file.

### CODE REVIEW

**Comment by tutelaris** [comment]
@elastic/ingest-eng-prod, can you please add @elastic/ent-search-application team to the repo?

**Comment by kderusso** [comment]
@tutelaris - Do we want to use `@elastic/ent-search-application` or should we migrate to some of the newer groups, e.g. `@elastic/search-relevance` , `@elastic/search-experiences` , `@elastic/search-extract-and-transform` , and `@elastic/search-inference-team` ? Alternately should we consider renaming to something like `@elastic/search-team`?

**Comment by rowlandgeoff** [comment]
> @elastic/ingest-eng-prod, can you please add @elastic/ent-search-application team to the repo?

@tutelaris Done. `elastic/ent-search-application` team now have write access. Shall I remove access for `elastic/ent-search-application-backend`? (Probably after you merge?) Or... is this going to change again based on Kathleen's comment?

**Comment by tutelaris** [comment]
> @tutelaris - Do we want to use `@elastic/ent-search-application` or should we migrate to some of the newer groups, e.g. `@elastic/search-relevance` , `@elastic/search-experiences` , `@elastic/search-extract-and-transform` , and `@elastic/search-inference-team` ? Alternately should we consider renaming to something like `@elastic/search-team`?

We decided to keep the `@elastic/ent-search-application` team to match with `@app-search-team` team in Slack

**Comment by tutelaris** [comment]
> > @elastic/ingest-eng-prod, can you please add @elastic/ent-search-application team to the repo?
> 
> @tutelaris Done. `elastic/ent-search-application` team now have write access. Shall I remove access for `elastic/ent-search-application-backend`? (Probably after you merge?) Or... is this going to change again based on Kathleen's comment?

Thank you!
No, you can remove the backend team.

**Comment by tutelaris** [comment]
Hey @rowlandgeoff , can you please re-review this PR? Thank you!

**Review by rowlandgeoff — APPROVED** [review]
Looks good. I have removed access for the `ent-search-application-backend` team.

**Pull request merged**
