### PR TITLE
processors/util: ensure hardware addresses are not duplicated

### PR DESCRIPTION
**Pull request by kortschak**
## What does this PR do?

Bug fix.

When a linux host is using a virtual bridge, the mac address of that interface will be duplicated in the results from net.Interfaces() since a dummy device will have been created to support the virtual bridge device, demonstrated by this example:

On a host with a virtual bridge we can see the virbrN and its associated virbrN-nic interfaces.
```
$ ip addr show | grep -A1 ': virb'
4: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:bf:91:c4 brd ff:ff:ff:ff:ff:ff
--
5: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc fq_codel master virbr0 state DOWN group default qlen 1000
    link/ether 52:54:00:bf:91:c4 brd ff:ff:ff:ff:ff:ff
```
This shows up in the hosts metadata sent by libbeat so
```
"host": {
<snip>
    "containerized": false,
    "ip": [
<snip>
    ],
    "mac": [
<snip>
      "52:54:00:bf:91:c4",
      "52:54:00:bf:91:c4",
<snip>
    ],
```

This change ensures that hardware addresses are unique in the returned mac list.

## Why is it important?

The rationale for the change is that a MAC is unique on a host and the host metadata should reflect this. Downstream search can deduplicate the elements, so there is potential disagreement about the merits of doing the work here rather than later. See [query](https://discuss.elastic.co/t/bug-query-duplication-mac-address-in-hosts-metadata-concern/278370/2) at discuss.elastic.co.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

Please let me know if I should add any text to CHANGELOG.

## Author's Checklist

The change is small so there is no specific reviewer requirement.

## How to test this PR locally

Running `go test` in the changed package will test this change.

## Related issues

No related issue.

## Use cases

N/A

## Screenshots

N/A

## Logs

Sanitised excerpt from beat debug log:
```
"host": {
<snip>
    "containerized": false,
    "ip": [
<snip>
    ],
    "mac": [
<snip>
      "52:54:00:bf:91:c4",
      "52:54:00:bf:91:c4",
<snip>
    ],
```

### CODE REVIEW

**Comment by kortschak** [comment]
:+1:

**Comment by kortschak** [comment]
.

**Comment by kortschak** [comment]
.

**Comment by kortschak** [comment]
.

**Comment by jlind23** [comment]
@efd6 Could you please tell me what to do with this?

**Comment by efd6** [comment]
@jlind23 I don't know. The contributor is me prior to joining Elastic, so it would be unsafe for me to review it. The change is sound, but it needs a review from someone who owns the file. If that can be got, then I can do all the necessary things to get it merged.

**Review by cmacknz — APPROVED** [review]
Change makes sense to me, most people would expect a list of MACs to be unique.

**Comment by efd6** [comment]
@Mergifyio update

**Pull request merged**
