### PR TITLE
[tests][filebeat] fix flaky unit test cases

### PR DESCRIPTION
**Pull request by VihasMakwana**
- Bug fix

## Proposed commit message

- Current behaviour:
   - In unit test case, we use `/logs/*` pattern.
   - This is problematic, because we can also read the `ndjson` file (which we shouldn't, as it's the output file) and this would cause test case failure.
- This PR fixes the behaviour.
   - Use `logs/*.log` as the pattern
   - Use `Runner: 'xyz' has stopped` to determine the stoppage instead of `Stopping runner`. The later would fail if there are transient errors.
## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes https://github.com/elastic/beats/issues/40237

### CODE REVIEW

**Comment by dliappis** [comment]
@VihasMakwana I added the `macOS` (and `:Windows`) labels to trigger the extended tests (see https://github.com/elastic/beats/blob/49f3efeada111d683754c2615b6af0e847a4c998/.buildkite/filebeat/filebeat-pipeline.yml#L161) via https://github.com/elastic/beats/pull/40389#issuecomment-2258565789.
If CI is still green, suggest we run the tests using the [trigger phrase](https://github.com/elastic/beats/blob/main/.buildkite/pull-requests.json#L13) a couple of more times -- since it's a flaky test -- to ensure we are good.

**Comment by VihasMakwana** [comment]
@dliappis looks like it's working.

I've ran CI for the fourth time. Let's see how it goes.

**Comment by dliappis** [comment]
> @dliappis looks like it's working.
> 
> I've ran CI for the fourth time. Let's see how it goes.

Thank you so much @VihasMakwana for testing this thoroughly, much appreciated! FYI @oakrizan

**Review by dliappis — APPROVED** [review]
Based on https://github.com/elastic/beats/pull/40389#issuecomment-2259869251
LGTM from an ingest-eng-prod PoV. Thank you!

**Review by rdner — APPROVED** [review]
The fix makes sense to me, I see it was well-tested too.

**Pull request merged**
