### PR TITLE
Allow the Docker image to be run with a random user id

### PR DESCRIPTION
**Pull request by barkbay**
On secured Kubernetes environments _(not only Openshift)_ the user ID used to run a container can't be known in advance. Consequently the APM server container can't be started on these environments because it expects to run with the user 1000 or 0.

This PR brings some compatibility with such environments, based on the fact that on secured Kubernetes clusters and on Openshift the only thing you know is that the user is always a member of the root group.

You can find more details here: https://docs.openshift.com/container-platform/3.11/creating_images/guidelines.html#openshift-specific-guidelines

See https://github.com/elastic/apm-server/pull/2325 and https://github.com/elastic/beats/issues/12686

### CODE REVIEW

**Comment by exekias** [comment]
It seems we missed this one, sorry about that.

This looks good to me, wdyt @jsoriano?

jenkins, test this please

**Comment by jsoriano** [comment]
Umm, this branch will need an update with master so we can run the packaging tests. I have tried it locally and some checks fail:
```
>> Testing package contents
--- FAIL: TestDocker (3.94s)
    --- FAIL: TestDocker/auditbeat-oss-8.0.0-linux-amd64.docker.tar.gz_config_file_permissions (0.00s)
        package_test.go:206: file usr/share/auditbeat/auditbeat.yml has wrong permissions: expected=-rw-r----- actual=-rw-rw----
```
Is it needed to give write permissions to the group?

**Comment by jsoriano** [comment]
> Is it needed to give write permissions to the group?

Answering myself, this seems to be the recommendation from Openshift, so I am ok with the change, but we should update the checks.

**Comment by barkbay** [comment]
Hi, thanks for the feedback.
I'll update this PR shortly.

**Comment by jsoriano** [comment]
jenkins run packaging tests

**Comment by jsoriano** [comment]
run beats-ci/package

**Comment by jsoriano** [comment]
Packaging tests failed for filebeat, something else seems to be needed.
https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-package-linux/67/console

**Comment by barkbay** [comment]
I will update the PR to fix that.
In the meantime I'm building the APM Server from this branch and I'm doing some tests on Openshift to confirm that it is also fixing the root issue.

**Comment by barkbay** [comment]
`Filebeat oss Linux` failed with following message:

```
[2020-05-18T08:44:50.063Z] ======================================================================
[2020-05-18T08:44:50.063Z] ERROR: Test reload same config with same file but different config. Makes sure reloading also works on conflicts.
[2020-05-18T08:44:50.063Z] ----------------------------------------------------------------------
[2020-05-18T08:44:50.063Z] Traceback (most recent call last):
[2020-05-18T08:44:50.063Z]   File "/go/src/github.com/elastic/beats/filebeat/tests/system/test_reload_inputs.py", line 284, in test_reload_same_config
[2020-05-18T08:44:50.063Z]     max_timeout=15)
[2020-05-18T08:44:50.063Z]   File "/go/src/github.com/elastic/beats/filebeat/tests/system/../../../libbeat/tests/system/beat/beat.py", line 365, in wait_until
[2020-05-18T08:44:50.063Z]     "Waited {} seconds.".format(max_timeout))
[2020-05-18T08:44:50.063Z] beat.beat.TimeoutError: Timeout waiting for 'cond' to be true. Waited 15 seconds.
```

Not sure if it is related to the PR.

**Comment by jsoriano** [comment]
run beats-ci/package

**Comment by jsoriano** [comment]
Thanks @barkbay for doing some additional tests. The failure in Filebeat OSS build is not related.

I have started another packaging build, if this goes well I think this can be merged.

**Comment by barkbay** [comment]
I have run the same tests successfully on my machine, not sure to understand what is happening here:

```
filebeat $mage integTest
>> Building docker images
...
>> go test: Integration Testing
SUMMARY:
  Fail:     0
  Skip:     1
  Pass:     396
  Packages: 19
  Duration: 2m39.9763138s
  JUnit Report: /go/src/github.com/elastic/beats/filebeat/build/TEST-go-integration.xml
  Output File:  /go/src/github.com/elastic/beats/filebeat/build/TEST-go-integration.out
>> go test: Integration Test Passed
...
>> python test: Integration Testing
elasticsearch uses an image, skipping
kibana uses an image, skipping
...
[success] 0.38% test_reload_inputs.Test.test_reload_same_config: 3.7874s
...
[success] 0.02% test_modules.load_fileset_test_cases: 0.2438s
----------------------------------------------------------------------
Ran 314 tests in 996.899s

OK (SKIP=4)
>> python test: Integration Testing Complete
```

**Comment by jsoriano** [comment]
Linux packaging build went blue  https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-package-linux/68/
I think we are good to merge this, we can ignore the other failing test, it might be a flaky test.

**Comment by jsoriano** [comment]
I am merging this and backporting it to 7.x, so it will get released with 7.9.0. I am adding it also to the manual test plan so we do some additional manual checks before releasing.

Thanks @barkbay!

**Pull request merged**
