### PR TITLE
[metricbeat/module/apache] Fix unused constants defaultScheme and autoQueryParam

### PR DESCRIPTION
**Pull request by radoondas**
Defined constants were left unused in code.

### CODE REVIEW

**Comment by karmi** [comment]
Hi @radoondas, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/beats/pull/2612.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by ruflin** [comment]
@radoondas Thanks for the fix. I think I replaced the variables when I was doing some testing on the metricset and forgot to put them back in.

**Comment by ruflin** [comment]
LGTM

**Comment by radoondas** [comment]
I will close this PR, fix my IDE and do new PR instead. Sorry for that. :(

**Pull request closed without merging**
