### PR TITLE
Migrate to elastic-agent-shipper-client

### PR DESCRIPTION
**Pull request by rdner**
## What does this PR do?

So, we stop copying the package to Beats and use a shared package instead.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Related issues

- Depends on https://github.com/elastic/elastic-agent-shipper-client/pull/10 to be merged and tagged.
- Closes https://github.com/elastic/elastic-agent-shipper/issues/64

### CODE REVIEW

**Comment by rdner** [comment]
@mergifyio update

**Comment by rdner** [comment]
@cmacknz I might have to wait until https://github.com/elastic/beats/pull/32161 is merged, I have the same failures after updating elastic-agent-libs to v0.2.7

**Review by cmacknz — APPROVED** [review]

**Comment by cmacknz** [comment]
The tests are passing in https://github.com/elastic/beats/pull/32161, just needs an approval. Feel free to merge it yourself if needed.

**Comment by rdner** [comment]
Packaging errors are not related to the change.

**Pull request merged**
