### PR TITLE
Run make update for packaging in docker container

### PR DESCRIPTION
**Pull request by ruflin**

### CODE REVIEW

**Comment by tsg** [comment]
jenkins, package it

**Comment by tsg** [comment]
The problem is this one is that now we have some makefile commands run in docker and some outside of docker, so that is likely to cause permission issues. If we go this route, we should probably create some sort of a "build" docker image, and run as much as possible inside it.

**Comment by tsg** [comment]
Btw, the virtualenv issue is solved in the stack build, so that's kind of a non-issue at this point.

**Comment by ruflin** [comment]
Closing as solved otherwise.

**Pull request closed without merging**
