### PR TITLE
Update Golang to 1.15.8

### PR DESCRIPTION
**Pull request by michalpristas**
## What does this PR do?

This PR updates golang to 1.15.8

## Why is it important?

.8 fixes some critical bugs

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by michalpristas** [comment]
failing on missing docker images

**Review by kvch — APPROVED** [review]
Please add a changelog entry.

**Pull request merged**
