### PR TITLE
Add `export dashboards` command

### PR DESCRIPTION
**Pull request by exekias**
WIP

This command will allow the user to export any dasbhoard from kibana to
a JSON output

### CODE REVIEW

**Comment by ruflin** [comment]
I wonder if we need this as part of the beat itself as I would assume this is mainly targeted at developer?

**Comment by exekias** [comment]
From my POV It should help others to develop & share dashboards in the future

**Comment by andrewkroh** [comment]
FYI I had this idea #4774 to make exporting dashboards easier.

**Comment by exekias** [comment]
Closing this, we will need to start over as code has changed a lot

**Pull request closed without merging**
