### PR TITLE
Add etcdbeat to the community beats

### PR DESCRIPTION
**Pull request by berfinsari**

### CODE REVIEW

**Comment by tsg** [comment]
@berfinsari Nice! Two things:

* Could you sign our [CLA](http://www.elasticsearch.org/contributor-agreement/), please? It should only take a couple of minutes.
* What do you think about also contributing the etcd support as a module in Metricbeat? I think it fits very well into Metricbeat.

**Comment by berfinsari** [comment]
I signed the CLA. (but I signed after I made a pull request)
I want to contribute the module. My currently aim is contributing the etcd support as a module in Metricbeat and now i'm working on a module for metricbeat.

**Comment by exekias** [comment]
@berfinsari let us know if you find any issue in the process :)

Here you have some useful links:
https://www.elastic.co/guide/en/beats/devguide/current/metricbeat-developer-guide.html
https://discuss.elastic.co/c/beats/libbeat

**Comment by berfinsari** [comment]
Is there anything that I can do for this unsuccessful check?

**Comment by exekias** [comment]
merged it, test errors had nothing to do with this

**Pull request merged**
