### PR TITLE
Fix example description in getting-started step 3

### PR DESCRIPTION
**Pull request by nrousset**
## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by EamonnTP** [comment]
Hi @nrousset Thanks for your contribution. Would you mind signing the [Contributor Agreement](https://www.elastic.co/contributor-agreement)?

**Comment by bmorelli25** [comment]
jenkins test this please

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by EamonnTP** [comment]
Hi @nrousset Would you mind signing the [Contributor Agreement](https://www.elastic.co/contributor-agreement)?

**Comment by EamonnTP** [comment]
H @nrousset thanks for your contribution to Elastic!

Unfortunately, we require a signed contributor agreement to be able to merge a PR. I have made the update in a separate PR, so I'm going to close this one. Thanks again for helping us improve our documentation!

**Pull request closed without merging**
