### PR TITLE
Fix panic when hitting EOF on stdin input

### PR DESCRIPTION
**Pull request by tsg**
The stdin harverster type has no state, so do a nil check before
trying to update it.

### CODE REVIEW

**Comment by ruflin** [comment]
LGTM. Would be nice if we would have a small test to verify the fix.

**Comment by tsg** [comment]
@ruflin I managed to make a test that was failing before and is passing afterwards. I'll open a PR to  do a similar one in master.

**Comment by ruflin** [comment]
LGTM. I restarted appveyor as it didn't start properly.

**Comment by ruflin** [comment]
@tsg Thanks for the fix.

**Pull request merged**
