### PR TITLE
[ILM] Remove beat version from default policy name.

### LINKED ISSUE #14736: Remove versions from ILM policies
Currently a new ILM policy is created for every version, and referenced in the versioned template. Keep the version in the template, but remove from the policy, for a better user experience. This will allow users to keep their customized policies on upgrades.

### PR DESCRIPTION
**Pull request by simitt**
Prevent breaking customized ILM policies on upgrade, by getting rid of
the version in the default policy name. The version can still be
configured.

fixes #14736

### CODE REVIEW

**Comment by urso** [comment]
Change LGTM. Code linter fails on python formatting.

**Comment by simitt** [comment]
Same test failing as in master. @urso please approve when you are fine with the changes so I can merge.

**Comment by urso** [comment]
Approved. Can you please add a changelog entry to breaking changes in Changelog.next.asciidoc before merging? No need to wait for CI. All tests have been green.

**Comment by urso** [comment]
Tested:
- Default ILM policy has no version. OK
- Customizing ILM policy name works. OK
- Add agent version to costum ILM policy name works. OK
- Check documentation does not mention that agent version is set by default. FAIL
- Check reference configuration file does not mention that agent version is set by default. FAIL

The change works as expected, but documentation + reference configuration files still need to be updated. I will create a PR doing so.

**Comment by urso** [comment]
Doc fix available in #15750

**Pull request merged**
