### PR TITLE
Some fixes in Cloud Foundry fields

### PR DESCRIPTION
**Pull request by jsoriano**
## What does this PR do?

* Remove redundant and undocumented `cloudfoundry.*.timestamp` fields.
* Add missing documentation about envelope fields.
* Update `data.json` files in metricbeat module.

## Why is it important?

Avoid unnecessary duplication of data and keep documentation updated.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Review by ChrsMark — COMMENTED** [review]
In general it looks good to me! Does this need to be in sync with https://github.com/elastic/beats/pull/21177 though?

**Comment by jsoriano** [comment]
> In general it looks good to me! Does this need to be in sync with #21177 though?

Thanks! They are independent changes, but I expect conflicts yes :slightly_smiling_face:

**Comment by jsoriano** [comment]
> > In general it looks good to me! Does this need to be in sync with #21177 though?
> 
> Thanks! They are independent changes, but I expect conflicts yes :slightly_smiling_face:

I mean, they can be independently merged, but probably I will need to fix merge conflicts in one after merging the other.

**Comment by ChrsMark** [comment]
> > > In general it looks good to me! Does this need to be in sync with #21177 though?
> > 
> > 
> > Thanks! They are independent changes, but I expect conflicts yes 🙂
> 
> I mean, they can be independently merged, but probably I will need to fix merge conflicts in one after merging the other.

Cool! I mostly thought about `data.json` file which will need to be updated in both.

**Review by ChrsMark — APPROVED** [review]

**Pull request merged**
