### PR TITLE
Add configuration knob for auto-discover default.disable

### PR DESCRIPTION
**Pull request by alakahakai**
Address {issue}10811[10811]

### CODE REVIEW

**Comment by alakahakai** [comment]
jenkins, test this

**Comment by alakahakai** [comment]
jenkins, test this

**Comment by jsoriano** [comment]
@alakahakai thanks for adressing these issues! 

Could you please split this in two PRs, one for the module and another one for the added setting?

**Comment by alakahakai** [comment]
@jsoriano OK, will do.

**Comment by alakahakai** [comment]
I am closing this to do a clean PR - {pull}10911[10911]

**Pull request closed without merging**
