### PR TITLE
Remove tls certificates from heartbeat data

### PR DESCRIPTION
**Pull request by andrewvc**
This was recently added (not yet released) for the 6.5 release. Having lived with it for a bit, I think we
should not include the full PEM certs on each check. Heartbeat checks can be quite frequent, and a cert chain
can be quite large.

I think we should hold off here, and if there's demand from the community add it in later.

### CODE REVIEW

**Comment by ruflin** [comment]
Alternative we could make it a config option that is off by default so users could play around with it? I'm also ok with removing it for now.

**Comment by ruflin** [comment]
This will need a `make update`.

**Comment by andrewvc** [comment]
@ruflin I think it'd be best to not have this feature for now. It's easy to add, and I don't see much use for it at the moment. I think if we get the ask for it then we can add it back in, vs. having to maintain it going forward.

**Comment by ruflin** [comment]
Ok, SGTM. Can you run `make update` and push again?

**Pull request merged**
