### PR TITLE
Cherry-pick #11530 to 6.7: Updated kafka version to 2.1.1

### PR DESCRIPTION
**Pull request by michalpristas**
Cherry-pick of PR #11530 to 6.7 branch. Original message: 

This PR updates kafka version by bumping up patch number.
Version change: `2.1.0` -> `2.1.1`

Reason for this is slow removal of `2.1.0` from download mirrors.

### CODE REVIEW

**Comment by michalpristas** [comment]
with this branch it bumps up minor as well so the change is from 
`2.0.0` to `2.1.1`

**Comment by michalpristas** [comment]
most of the mirrors i checked had 2.1.1 and 2.2.0

**Comment by ruflin** [comment]
@michalpristas This should probably be merged now?

**Comment by michalpristas** [comment]
yes i need to bring this even with branch

**Pull request merged**
