### PR TITLE
Make the Syslog input GA

### PR DESCRIPTION
**Pull request by faec**
## What does this PR do?

Remove the beta warning from syslog RFC 5424 in the code and docs.

## Checklist

- [ ] ~~My code follows the style guidelines of this project~~
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by ph** [comment]
@faec good finding in the unix's socket's status, I don't know if it should still be in beta. @andrewstucki or @andrewkroh is the unix socket still a beta feature or we could remove the warning? see https://github.com/elastic/beats/blob/master/filebeat/input/syslog/config.go#L122

**Comment by andrewkroh** [comment]
We might as well move the unix socket to GA too. I'm not aware of any reasons to hold it back from GA.

**Review by ph — COMMENTED** [review]
Syslog changes LGTM, is there a reason why the modules files was updated?
@faec did you look into the documentation to make sure we removed any beta mention?

**Comment by faec** [comment]
I'm not sure why the modules file updated -- it was an effect of `make update`, but it also seems to be breaking the CI, so maybe there are still module glitches left, I will double check my go setup.

I searched the documentation and removed all the beta warnings I could find. I also removed them from the reference configs, but edited the generated files by mistake, so `make update` removed the changes -- I have fixed that now.

**Comment by faec** [comment]
Module problem was seemingly because my local go was pointing at 1.16.4 instead of 1.16.5 when I ran `make update` -- hopefully fixed now.

**Review by ph — APPROVED** [review]

**Pull request merged**
