### PR TITLE
[Elastic Agent] Fix composed.Verifier so files are removed when invalid

### LINKED ISSUE #30280: [Elastic Agent] Composed Verifier does not always remove files
Elastic Agent uses the `composed.Verifier` to chain multiple verifiers together. The issue in this code is that only the last verify is allowed to remove the files when it fails. If the previous verifiers in the chain fail then they do not remove the files.

The code needs to be changed to ensure that at any point that a verifier fails that the files are removed (when enabled), instead of waiting for the last verifier (which might not be reached).

### PR DESCRIPTION
**Pull request by blakerouse**
## What does this PR do?

Fixes an issue in the `composed.Verifier`. Without this change if any verifier failed before the final verifier it would not remove the files and the last verifier in the chain would never be called to remove the files. This fixes the issue to always have each verifier have the ability to remove the files when it fails to verify.

## Why is it important?

Without this change when a downloaded artifact gets corrupted, the Elastic Agent will keep trying to verify the same file, instead of removing it and re-downloading it from artifacts.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #30280

### CODE REVIEW

**Review by lykkin — APPROVED** [review]
LGTM

**Review by ph — APPROVED** [review]

**Comment by ph** [comment]
@blakerouse I would prefer we don't target 8.1, we are working to stabilize that release and we still don't know the other issue.

**Comment by blakerouse** [comment]
I was able to test this with docker locally to confirm that it fixes the behavior:

1. First ran this once:
```
docker run -it -v $(pwd)/state:/state -e STATE_PATH=/state docker.elastic.co/beats/elastic-agent:8.2.0
# let it run for a bit
^c
```

2. Performed:
```
echo "baddata" >> state/data/downloads/filebeat-8.2.0-linux-x86_64.tar.gz
```

3. Ran it again:
```
docker run -it -v $(pwd)/state:/state -e STATE_PATH=/state docker.elastic.co/beats/elastic-agent:8.2.0
```

4. Resulted in the tar.gz and the .tar.gz.sha512 to be deleted and then it tried to download from the artifacts.

**Comment by ph** [comment]
Added backport to other version, lets see if mergify pick them up.

**Pull request merged**
