### PR TITLE
Update timestamp.asciidoc

### PR DESCRIPTION
**Pull request by Bernhard-Fluehmann**
Add example for better understanding

## Checklist

- [x ] My code follows the style guidelines of this project
- [ x] I have commented my code, particularly in hard-to-understand areas

### CODE REVIEW

**Comment by Bernhard-Fluehmann** [comment]
@bmorelli25 Thank you for your response. As far as I know I already have a signed CLA. Please let me know if there are an issues with it. Regards

**Comment by bmorelli25** [comment]
@elasticmachine retest please

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by bmorelli25** [comment]
I added a small commit to force a recheck of the CLA; we're green! I'll get this merged and backported once all tests are green.

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by Bernhard-Fluehmann** [comment]
Thanks

**Pull request merged**
