### PR TITLE
Use 'python3 -m venv' instead of virtualenv

### PR DESCRIPTION
**Pull request by andrewkroh**
Switch over to `python3 -m venv` instead of `virtualenv`. It's the recommended way to create virtual Python environments in 3.4 and above.

https://docs.python.org/3/library/venv.html

### CODE REVIEW

**Comment by andrewkroh** [comment]
I'll check that out. I found a few more direct calls to `python` that need to be fixed too.

**Comment by jsoriano** [comment]
It seems that we need to install `python3-venv` in travis or somewhere else.

**Comment by andrewkroh** [comment]
Oh yeah..., Debian has split up the python distribution so you need that package to get the venv module.

Will add that.

**Comment by jsoriano** [comment]
Merging this, thanks!

**Pull request merged**
