### PR TITLE
[WIP] Adding logstash pipeline metricset

### PR DESCRIPTION
**Pull request by ycombinator**
This PR adds a new `pipeline` metricset for the `logstash` Metricbeat module. This metricset will collect the shape of a pipeline and some basic pipeline-level metrics.

### TODO
- See `TODO`s in PR code. They can be addressed once https://github.com/elastic/logstash/issues/10119 is resolved.

### CODE REVIEW

**Comment by ycombinator** [comment]
@ruflin This PR is still a WIP, mainly because of TODOs in the code depending on https://github.com/elastic/logstash/issues/10119 being implemented. However, if you get a chance to look at this PR and give any early feedback to know if it's in the right direction, I'd appreciate it. Thanks!

**Comment by ycombinator** [comment]
Also, this PR is currently based on top of https://github.com/elastic/beats/pull/9183 so it contains commits from there as well. Once #9183 is reviewed and merged into `master`, I will rebase this PR on `master` so it only contains its own commits.

**Comment by ruflin** [comment]
Just had a quick look but direction LGTM.

**Comment by ycombinator** [comment]
Replaced by https://github.com/elastic/beats/pull/11506.

**Pull request closed without merging**
