### PR TITLE
[Heartbeat] Allow dup3 and dup syscalls

### PR DESCRIPTION
**Pull request by andrewvc**
This adds support for the dup syscall variants which are sometimes used in browser monitors. Without this browser monitors do not function.

To test this run any browser based monitor and see that it runs successfully

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Review by vigneshshanmugam — APPROVED** [review]
LGTM 

Do we know why it showed up all of a sudden? We haven't changed any deps or introduce any major changes in the Synthetics agent. I feel there could be a learning curve here.

**Comment by andrewvc** [comment]
@Mergifyio update

**Comment by andrewvc** [comment]
@vigneshshanmugam I don't know, and yes, that worries me as well. I don't see us having updated the docker template, synthetics, etc. My best guess is some transitive dependency somehow changed.

**Comment by andrewvc** [comment]
@Mergifyio update

**Comment by andrewvc** [comment]
@Mergifyio backport 8.0

**Pull request merged**
