### PR TITLE
winlogbeat/eventlog: don't attempt to salvage messages for forwarded events

### LINKED ISSUE #34705: [Winlogbeat] Crashes with an exception when shipping Forwarded Events
Winlogbeat crashes with an exception when shipping Forwarded Events

A similar problem has been fixed in **telegraf**: https://github.com/influxdata/telegraf/issues/12328

```
winlogbeat.event_logs:
  - name: ForwardedEvents
    tags: [forwarded]
```

```
Exception 0xc0000005 0x1 0x0 0x7ffea479e254
PC=0x7ffea479e254

runtime.cgocall(0xc2c3e0, 0xc0001812c0)
	runtime/cgocall.go:157 +0x4a fp=0xc000c90dd0 sp=0xc000c90d98 pc=0xbc458a
syscall.SyscallN(0x1e?, {0xc000c90e68?, 0x0?, 0xc000a151a0?})
	runtime/syscall_windows.go:556 +0x109 fp=0xc000c90e48 sp=0xc000c90dd0 pc=0xc27429
syscall.Syscall9(0xc000a151a0?, 0x1?, 0x1?, 0xc000c90f10?, 0x159a26f?, 0xc120c9?, 0x365f620?, 0xc00018e290?, 0xc000c90f28?, 0x0, ...)
	runtime/syscall_windows.go:506 +0x78 fp=0xc000c90ec0 sp=0xc000c90e48 pc=0xc27138
github.com/elastic/beats/v7/winlogbeat/sys/wineventlog._EvtFormatMessage(0xc00018e290?, 0xc000f42778?, 0x0, 0x0, 0x0?, 0x1, 0x0, 0xc000d1c340?, 0x1e?)
	github.com/elastic/beats/v7/winlogbeat/sys/wineventlog/zsyscall_windows.go:132 +0xe5 fp=0xc000c90f58 sp=0xc000c90ec0 pc=0x15aecc5
github.com/elastic/beats/v7/winlogbeat/sys/wineventlog.evtFormatMessage(0xc000b517c0?, 0x1e?, 0x0?, {0x0?, 0x0, 0x1?}, 0x1?)
	github.com/elastic/beats/v7/winlogbeat/sys/wineventlog/format_message.go:82 +0x9e fp=0xc000c91028 sp=0xc000c90f58 pc=0x159f43e
github.com/elastic/beats/v7/winlogbeat/sys/wineventlog.getMessageString(0xc000d1c340?, 0x4000?, 0x4000?, {0x0?, 0xc2703b?, 0x100fea1c9a970?})
	github.com/elastic/beats/v7/winlogbeat/sys/wineventlog/format_message.go:58 +0x45 fp=0xc000c91070 sp=0xc000c91028 pc=0x159f2e5
github.com/elastic/beats/v7/winlogbeat/sys/wineventlog.getMessageStringFromHandle(...)
	github.com/elastic/beats/v7/winlogbeat/sys/wineventlog/format_message.go:34
github.com/elastic/beats/v7/winlogbeat/sys/wineventlog.Message(0x4000?, {0xc0005f8000?, 0x3ef6e40?, 0xc0003e5980?}, 0xc000c91168)
	github.com/elastic/beats/v7/winlogbeat/sys/wineventlog/wineventlog_windows.go:274 +0x12e fp=0xc000c91140 sp=0xc000c91070 pc=0x15ad40e
github.com/elastic/beats/v7/winlogbeat/eventlog.newWinEventLog.func5(0xc0007db6c0?)
	github.com/elastic/beats/v7/winlogbeat/eventlog/wineventlog.go:568 +0x55 fp=0xc000c91188 sp=0xc000c91140 pc=0x22f3635
github.com/elastic/beats/v7/winlogbeat/eventlog.(*winEventLog).Read(0xc0007db6c0)
	github.com/elastic/beats/v7/winlogbeat/eventlog/wineventlog.go:333 +0x792 fp=0xc000c917e8 sp=0xc000c91188 pc=0x22f1592
github.com/elastic/beats/v7/winlogbeat/beater.(*eventLogger).run(0xc0003e15c0, 0xc00020ccc0, {0x3f14170?, 0xc0001bd340}, {{0xc00057d780, 0xf}, 0x18c5e4, {0x35f58810, 0xedb90461e, 0x0}, ...}, ...)
	github.com/elastic/beats/v7/winlogbeat/beater/eventlogger.go:154 +0x9f2 fp=0xc000c91ed8 sp=0xc000c917e8 pc=0x22f7f12
github.com/elastic/beats/v7/winlogbeat/beater.(*Winlogbeat).processEventLog(0x2020200a35313437?, 0x7561666564202020?, 0x646c6569665f746c?, {{0xc00057d780, 0xf}, 0x18c5e4, {0x35f58810, 0xedb90461e, 0x0}, {0xc00007a150, ...}}, ...)
	github.com/elastic/beats/v7/winlogbeat/beater/winlogbeat.go:196 +0xb3 fp=0xc000c91f70 sp=0xc000c91ed8 pc=0x22fa393
github.com/elastic/beats/v7/winlogbeat/beater.(*Winlogbeat).Run.func2()
	github.com/elastic/beats/v7/winlogbeat/beater/winlogbeat.go:164 +0x55 fp=0xc000c91fe0 sp=0xc000c91f70 pc=0x22fa115
runtime.goexit()
	runtime/asm_amd64.s:1571 +0x1 fp=0xc000c91fe8 sp=0xc000c91fe0 pc=0xc2ab21
created by github.com/elastic/beats/v7/winlogbeat/beater.(*Winlogbeat).Run
	github.com/elastic/beats/v7/winlogbeat/beater/winlogbeat.go:164 +0x2df
```

Version: 8.6.2
Operating System: Windows Server 2022 Standard 21H2 20348.1487

### PR DESCRIPTION
**Pull request by efd6**
## What does this PR do?

Avoids attempting to salvage event messages for forwarded logs. These events may not have a provider and so the call to `EvtFormatMessage` may have an invalid handle. This results in a Windows exception.

## Why is it important?

The current behaviour is to crash the program.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Fixes #34705

### CODE REVIEW

**Review by andrewkroh — COMMENTED** [review]
Just checking my understanding here...

So the assumptions we make here are that any forwarded events contain `RenderingInfo` (as we advise in the docs IIRC) and if not Winlogbeat will not attempt to render the messages (SGTM) using local message resources because those are in some way not valid.

From the stack trace in the issue (#34705) we see that the metadata provider handle is non-null. So it was previously passing some metadata provider handle but it just wasn't "good" in some way.

> github.com/elastic/beats/v7/winlogbeat/sys/wineventlog._EvtFormatMessage(0xc00018e290?, ...

**Comment by efd6** [comment]
@andrewkroh The issue that is present appears to be not related to this, so I think we can go ahead with the merge of this if you would approve.

**Review by andrewkroh — APPROVED** [review]

**Comment by efd6** [comment]
@Mike-FUT The backport happened on the 4th of May and 8.7.1 was released on the 2nd. So it is not in 8.7.1. It will be in 8.7.2.

**Comment by Mike-FUT** [comment]
@efd6, FYI, I downloaded today's [Winlogbeat 8.7.2 snapshot](https://snapshots.elastic.co/8.7.2-9848dc50/downloads/beats/winlogbeat/winlogbeat-8.7.2-SNAPSHOT-windows-x86_64.zip) and so far all stable. No crashes, no strange behaviour from what I can see.

**Comment by efd6** [comment]
@Mike-FUT That's great, thank you for confirming.

**Pull request merged**
