### PR TITLE
Update 5.6 testing environment

### PR DESCRIPTION
**Pull request by jsoriano**
Update missing dependency for testing environment on 5.6 branch.

### CODE REVIEW

**Comment by jsoriano** [comment]
Failures in travis are fixed by #7879

**Comment by jsoriano** [comment]
jenkins, test this again

**Comment by ruflin** [comment]
It seems on Jenkins `docker-compose` is not found and on travis virtualenv. I assume for docker-compose on the mac workers we have something special in 6.x to not use docker-compose. We would need this also in 5.x (probably TEST_ENVIRONMENT is disabled). For travis not sure what happened.

**Comment by jsoriano** [comment]
The virtualenv failure is fixed by #7879

**Comment by ruflin** [comment]
Could you rebase this on 5.6 so tests are run with virutalenv fix?

**Comment by jsoriano** [comment]
ceph failure fixed by #8048

**Comment by ruflin** [comment]
@jsoriano I think this PR is empty as change was already applied here: https://github.com/elastic/beats/pull/8025 Going to close this one.

**Pull request closed without merging**
