### PR TITLE
Override Edit URLs in Metricbeat module docs

### PR DESCRIPTION
**Pull request by dedemorton**
Related to https://github.com/elastic/beats/pull/31327.

I need someone familiar with Go and templates to make sure I've done this correctly (though it does work).

@gtback Same questions as #31327: Do we want to provide versioned links?

BTW, I went through the the exercise of trying to set the URL from basePath, but that was fraught with rabbit holes. Just setting the URL conditionally in the template was a lot easier, so I did that.

### CODE REVIEW

**Comment by gtback** [comment]
> @gtback Same questions as #31327: Do we want to provide versioned links?

My comment on https://github.com/elastic/beats/pull/31327#discussion_r853318437 applies here as well:

> I'd probably lean towards just pointing everything to main for the time being, until we're ready to deprecate the master URLs. I suspect most changes will need to be backported anyway. For issues that are only a problem in older versions, I can see it being confusing (the user clicks an edit link for an old version, but it doesn't match what they're seeing in the main branch), but I don't know if how likely that is to be a problem.

**Review by belimawr — COMMENTED** [review]
The Go templates look correct. I treied to build the docs to test, but the edit URL did not work for me, it kept pointing to the generated file. Is there anything special I should do when building the docs for those links to work?

**Comment by dedemorton** [comment]
@belimawr Do you remember which links didn't worK? I did some spot checking in the docs preview, and they seemed OK:

https://beats_31339.docs-preview.app.elstc.co/guide/en/beats/metricbeat/master/metricbeat-metricset-activemq-broker.html

We can send contributors to the correct file, but because of how the asciidoc files are composed, contributors won't be able to change everything they see in the rendered file. :-/ But at least they won't try to update the generated file.

**Comment by belimawr** [comment]
> @belimawr Do you remember which links didn't worK? I did some spot checking in the docs preview, and they seemed OK:
> 
> https://beats_31339.docs-preview.app.elstc.co/guide/en/beats/metricbeat/master/metricbeat-metricset-activemq-broker.html
> 
> We can send contributors to the correct file, but because of how the asciidoc files are composed, contributors won't be able to change everything they see in the rendered file. :-/ But at least they won't try to update the generated file.

It's working in the docs preview. It's very likely there was something wrong with my setup. All good from my side now.

**Review by belimawr — APPROVED** [review]

**Pull request merged**
