### PR TITLE
Combination of #14719 and #14725

### PR DESCRIPTION
**Pull request by ycombinator**
Both #14719 and #14725 need to go in simultaneously. This PR cherry picks commits from both those PRs so we can see if CI will go green when both PRs get merged.

**DO NOT MERGE THIS PR.** Instead, if CI looks good on this PR, close this PR and merge the two individual but interdependent PRs: #14719 and #14725.

### CODE REVIEW

**Comment by ycombinator** [comment]
I believe the reason CI tests are failing on this one is that the `docker.elastic.co/elasticsearch/elasticsearch:7.6.0-SNAPSHOT` image was last successfully built on `2019-10-25T07:36:19.215851Z`, whereas the commit with the GeoIP changes in ES went in just a couple of days ago: https://github.com/elastic/elasticsearch/commit/224374345071211fc16369a548cbafb9917aad32. In other words, the image does not contain the changes from the commit.

**Comment by urso** [comment]
fileset tests are still failing. Could it be due to the user agent parsing chaning? @jsoriano @kaiyan-sheng

**Comment by kaiyan-sheng** [comment]
@urso Yep it is caused by the changes in user agent plugin not geoip data. I just created a PR to rebase that: https://github.com/elastic/beats/pull/14732

**Comment by jsoriano** [comment]
Any reason to merge #14719 and #14725 independently? I think we should merge the change in the snapshot and the related changes in the expected files in the same PR.

**Comment by urso** [comment]
> Any reason to merge #14719 and #14725 independently? 

Backporting multiple PRs at once currently messes with our release notes scripts.

**Comment by jsoriano** [comment]
> > Any reason to merge #14719 and #14725 independently?
> 
> Backporting multiple PRs at once currently messes with our release notes scripts.

In general I agree with that, but  #14719 and #14725 are completely related and dependant the one on the other (tests won't pass if we only merge one of them), and they don't include a changelog.

**Comment by kaiyan-sheng** [comment]
I ended up having to basically create the same PR like this one and rerun test_modules.py for filebeat in order to get a green on travis ci: https://github.com/elastic/beats/pull/14761

**Comment by ycombinator** [comment]
@kaiyan-sheng Thanks. So it sounds like https://github.com/elastic/beats/pull/14761 is the one we should go ahead with instead of this PR here, as https://github.com/elastic/beats/pull/14761 is more complete in terms of all the changes necessary, right? If so, I'm happy to to close this PR unmerged; just want to double check first.

**Comment by kaiyan-sheng** [comment]
> @kaiyan-sheng Thanks. So it sounds like #14761 is the one we should go ahead with instead of this PR here, as #14761 is more complete in terms of all the changes necessary, right? If so, I'm happy to to close this PR unmerged; just want to double check first.

@ycombinator Yes, #14761 included all changes needed for 7.x. Should we merge #14761 now or wait till 7.5 releases?

**Comment by ycombinator** [comment]
> Should we merge #14761 now or wait till 7.5 releases?
I don't think we need to wait till 7.5 release, since the `7.x` branch will still be pointing to `7.6.0` before or after the 7.5 release. So, yes, lets go ahead and merge #14761 now (pending CI looking good). And I'll close this PR here unmerged.

Thanks @kaiyan-sheng!

**Comment by urso** [comment]
> In general I agree with that, but #14719 and #14725 are completely related and dependant the one on the other (tests won't pass if we only merge one of them), and they don't include a changelog.

The scripts do not only look for changelog entries, but they also try to find original PRs building kind of a PR based history, so we know which original PRs made it into which release. This allows us to compare different versions in regards to available backports + we use it to identify possibly missing entries. Even without changelog entries you are messing with our scripts :)

It's not too bad for now, but we have to improve how we detect backports so to not mess with planed automation in the future.

**Pull request closed without merging**
