### PR TITLE
Use more consistent naming in common/net

### PR DESCRIPTION
**Pull request by kkirsche**
Use more consistent variable naming between functions and fix the function name at the beginning of the Godoc comment

### CODE REVIEW

**Comment by ruflin** [comment]
Travis is hanging. Need to check what is going wrong here.

**Comment by kkirsche** [comment]
Wanted to follow up on this and see if one of the maintainers could restart the travis build

**Comment by ruflin** [comment]
@kkirsche I would like to do that but somehow the link to the travis build is completely missing :-( One idea could be that you rebase on master and force push. That should retrigger the build.

**Comment by kkirsche** [comment]
@ruflin rebased and build passed

**Comment by ruflin** [comment]
@kkirsche thx

**Comment by kkirsche** [comment]
Anytime :+1:

**Pull request merged**
