### PR TITLE
Fix build problem with Kafka output section

### PR DESCRIPTION
**Pull request by dedemorton**
@andrewkroh Here's the fix for the Kafka display issue. Made a few minor edits. Still needs a few edits, but it's good enough for now. This topic *really* needs an example.

### CODE REVIEW

**Comment by andrewkroh** [comment]
Excellent, thanks!

**Comment by jianchen2580** [comment]
There any example about how to write .yaml config for kafka output?

**Comment by ruflin** [comment]
@jianchen2580 Best is to follow the docs here: https://www.elastic.co/guide/en/beats/filebeat/master/kafka-output.html But please be aware that this is not released yet and only available in the nightly builds.

**Comment by ruflin** [comment]
To make sure we also add it to the config file: https://github.com/elastic/beats/issues/1168

**Comment by jianchen2580** [comment]
@ruflin 
 ` broker_timeout: "1s"`
I think int is better.
` broker_timeout: 1 `

**Comment by ruflin** [comment]
@jianchen2580 Thanks for the input. We try to always include the unit as it makes it allows people to use different units, for example 500ms, and people don't need to check out the docs what the unit for 1 is.

**Pull request merged**
