### PR TITLE
Add multiline support for zookeeper logs

### PR DESCRIPTION
**Pull request by agithomas**
Please label this PR with one of the following labels, depending on the scope of your change:
- Enhancement

## What does this PR do?

Fixes the issue reported in https://github.com/elastic/sdh-beats/issues/2496
Adding multiline support for the zookeeper logs

## Why is it important?
Fixes the issue reported in https://github.com/elastic/sdh-beats/issues/2496
Adding multiline support for the zookeeper logs

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Relates [sdh-beats-issue-2496](https://github.com/elastic/sdh-beats/issues/2496)

### CODE REVIEW

**Comment by agithomas** [comment]
image

Test output

**Review by muthu-mps — COMMENTED** [review]
Can we add a sample multiline log in the test log file and run the tests against it to generate the expected json file ?

**Comment by agithomas** [comment]
> Can we add a sample multiline log in the test log file and run the tests against it to generate the expected json file ?

Unable to do this as i receive below error

```
../../build/python-env/lib/python3.6/site-packages/elasticsearch/connection/base.py:288: AuthenticationException
=========================================================================================================== warnings summary ============================================================================================================
../../build/python-env/lib/python3.6/site-packages/paramiko/transport.py:33
  /home/agikthomas/go/src/github.com/elastic/beats/build/python-env/lib/python3.6/site-packages/paramiko/transport.py:33: CryptographyDeprecationWarning: Python 3.6 is no longer supported by the Python core team. Therefore, support for it is deprecated in cryptography and will be removed in a future release.
    from cryptography.hazmat.backends import default_backend

-- Docs: https://docs.pytest.org/en/stable/warnings.html
======================================================================================================== short test summary info ========================================================================================================
FAILED tests/system/test_xpack_modules.py::XPackTest::test_fileset_file_0_zookeeper - elasticsearch.exceptions.AuthenticationException: AuthenticationException(401, '')
===================================================================================================== 1 failed, 1 warning in 0.78s ======================================================================================================
```

**Comment by muthu-mps** [comment]
> 

As the document says the sample event generation functionality is currently supported only for packet-beat and metricbeat. We can either update the sample event manually in the json file or create a separate issue to track.

**Pull request closed without merging**
