### PR TITLE
Aws cloudwatch msk

### PR DESCRIPTION
**Pull request by thenom**
Added label seperator and split the labels based on that instead of spaces.  Some dimensions include spaces so was breaking the generation of the event, for example:

This label:
KafkaAppLogsDiskUsed AWS/Kafka Cluster Name,Broker ID test-kafka,1

was generating:
```
    "aws": {
      "cloudwatch": {
        "namespace": "AWS/Kafka",
        "dimensions": {
          "Cluster": "Name"
        },
        "metrics": {
          "ZooKeeperRequestLatencyMsMean": 1.1137819147251762
        }
      }
    },
```

instead of:
```
    "aws": {
      "cloudwatch": {
        "namespace": "AWS/Kafka",
        "dimensions": {
          "Cluster Name": "test-kafka",
          "Broker ID": "1"
        },
        "metrics": {
          "CpuIdle": 98.540024,
          "MemoryCached": 1297193200,
          ...
```

And a side affect of this is it was creating an event for every metric.

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
jenkins, test this please

**Comment by kaiyan-sheng** [comment]
@thenom Thank you for creating this PR and making this great change in cloudwatch metricset! I see that you are making the change based on 7.3 branch. Could you create a PR based on master please? Then we can backport it to 7.3 and 7.4 after it gets merged.

**Comment by thenom** [comment]
Hi @kaiyan-sheng , thanks for taking a look. I have rebased this on master and local tests are passing.

**Comment by kaiyan-sheng** [comment]
jenkins, test this please

**Comment by kaiyan-sheng** [comment]
Thank you! Could you please add a changelog entry in `CHANGELOG.next.asciidoc` under `Bugfixes Metricbeat` for this please?

**Comment by thenom** [comment]
Yep no problem, entry added:

- Fix issue with aws cloudwatch module where dimensions and/or namespaces that contain space are not being parsed correctly {pull}13389[13389]

**Comment by kaiyan-sheng** [comment]
jenkins, test this please

**Comment by thenom** [comment]
Brilliant, @kaiyan-sheng thanks again 👍

**Pull request merged**
