### PR TITLE
Backport to 6.0: Doc changes in #5846 and #6014

### PR DESCRIPTION
**Pull request by dedemorton**
Cherry-picks #5846 and #6014 into the 6.0 branch.

### CODE REVIEW

**Comment by ruflin** [comment]
@dedemorton This one needs a rebase or a Make Update because the Notice file changed to 2018 (yes, CI should not fail because of this :-( ) I could merge it directly but I would like to have CI quickly run on the docs if possible.

**Comment by dedemorton** [comment]
@ruflin Rebasing didn't do anythinig.

Tried running make update, but got errros: 

```
cp: /Users/dedemorton/go/src/github.com/elastic/beats/filebeat/module/kafka/_meta/config.yml: No such file or directory
cp: /Users/dedemorton/go/src/github.com/elastic/beats/filebeat/module/logstash/_meta/config.yml: No such file or directory
cp: /Users/dedemorton/go/src/github.com/elastic/beats/filebeat/module/postgresql/_meta/config.yml: No such file or directory
cp: /Users/dedemorton/go/src/github.com/elastic/beats/filebeat/module/testmodule/_meta/config.yml: No such file or directory
make[1]: *** [configs] Error 1
```

Maybe I shouldn't try to backport these changes all the way to 6.0. It's probably good enough that they are in 6.1 and later. The thing that bugs me, though, is that these changes shouldn't require a make update.

WDYT?

**Comment by ruflin** [comment]
@dedemorton I agree this should not required a make update but the problem is related tot he NOTICE file because of the year change.

Did you run `make update` in the beats directory? Then the NOTICE file should change. If not too much work, I think it would be still good to have it in 6.0 (not critical).

**Comment by dedemorton** [comment]
@ruflin ran `make update` again and didn't see the error I was seeing before. 🤷‍♀️ The notice file is updated now. Hopefully it'll turn green.

**Pull request merged**
