### PR TITLE
libbeat/processors/timestamp: use time/tzdata to embed tzdata

### PR DESCRIPTION
**Pull request by kortschak**
This is a cleanup.

## What does this PR do?

This change replaces 4d63.com/tz [which is no longer maintained](https://github.com/leighmcculloch/go-tz) with the standard library time/tzdata package for embedding the tzdata asset for systems that do not hold their own.

Note that time/tzdata conditionally uses the embedded asset only when there is no timezone database available on the system. This is a difference compared to 4d63.com/tz which is unconditional.

## Why is it important?

4d63.com/tz is no longer maintained and the conditional use of the embedded asset means that users can maintain an up-to-date tz database rather than being pinned to the embedded asset.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

Please let me know if this requires text to be added to the CHANGELOG and whether there should be documentation added (I suspect not).

## Author's Checklist

No new feature is added, and existing tests already cover the change. I have run tests on a platform with tzdata though, so testing on a Windows env is recommended.

## How to test this PR locally

Standard test suite.

## Related issues

No related issues.

## Use cases

N/A

## Screenshots

N/A

## Logs

N/A

### CODE REVIEW

**Review by mtojek — APPROVED** [review]
LGTM

**Comment by kortschak** [comment]
:+1:

**Comment by kortschak** [comment]
Abandoning. This is already fixed by b3497ca8f5d03b5a7d7537559aeac95a37e227f2.

**Pull request closed without merging**
