### PR TITLE
Cherry-pick #10760 to 6.8: Adding Cisco support for the Syslog parser

### PR DESCRIPTION
**Pull request by hrak**
Adding Cisco support for the Syslog parser

* Adding Cisco support for the Syslog parser

Add support for the "sequence" number in the log format send by Cisco switch devices.

Fixes: #10654, #15979

(cherry picked from commit dd92b6f887c18c40932969d9430be9d54d7f6903)

## What does this PR do?

Apart from adding support for the Cisco sequence number in syslog messages, this PR fixes several issues with the hostname parser (f.e. hostnames with dashes, IPv6 addresses in hostname field)

## Why is it important?

The hostname parser in the syslog input in filebeat 6 is currently broken, resulting in everything after the timestamp of a rfc3164 syslog message ending up in the message field (hostname, program name, PID, message)

## Checklist

~~- [ ] My code follows the style guidelines of this project~~
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~

### CODE REVIEW

**Comment by urso** [comment]
Thank you for contributing.

The backport seems to cause some CI failures in some filebeat modules that require the syslog input. @ph any idea if we are missing some other commits?

**Comment by ph** [comment]
sorry @ChrsMark I've missed the ping on this.

This is indeed strange the main PR was indeed green when merged. Looking at the tables failures in the test for **iptable** the expected object doesn't match anymore but we do have a partial document extracted. 

So I think we are missing commit for surricata?

**Comment by ph** [comment]
Going to build the 6.8 branch locally and see what is going on.

**Comment by ph** [comment]
Ok, plain 6.8 branch fails with the same errors.

**Comment by ph** [comment]
@hrak do you mind rebasing this PR on 6.8?

**Comment by hrak** [comment]
@ph done, looking much better now. One unrelated test failure in metricbeat tests:

```
ERROR: Service 'jolokia' failed to build: The command '/bin/sh -c wget http://archive.apache.org/dist/tomcat/tomcat-7/v${TOMCAT_VERSION}/bin/${TC}.tar.gz;    tar xzf ${TC}.tar.gz -C /usr;    rm ${TC}.tar.gz;    sed -i -e 's/Connector port="8080"/Connector port="8778"/g' /usr/${TC}/conf/server.xml;    wget http://central.maven.org/maven2/org/jolokia/jolokia-war/${JOLOKIA_VERSION}/jolokia-war-${JOLOKIA_VERSION}.war -O /usr/${TC}/webapps/jolokia.war' returned a non-zero code: 1
```

**Comment by urso** [comment]
LGTM. Failing test is unrelated.

@ph you want to have a final look?

**Comment by urso** [comment]
Jenkins, test this.

**Comment by ph** [comment]
@hrak thanks it's merged

**Pull request merged**
