### PR TITLE
Cherry-pick to 7.9: Remove redirects page (#19574)

### PR DESCRIPTION
**Pull request by dedemorton**
Backports the following commits to 7.9:
 - Remove redirects page (#19574)

### CODE REVIEW

**Comment by dedemorton** [comment]
The Kibana doc build errors are fixed in https://github.com/elastic/kibana/pull/77840

**Comment by dedemorton** [comment]
@karenzone has graciously agreed to fix the Logstash links.

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by karenzone** [comment]
@elasticmachine run elasticsearch-ci/docs

**Review by karenzone — APPROVED** [review]
LGTM!

**Pull request merged**
