### PR TITLE
Fix location of cockroachdb dashboard

### PR DESCRIPTION
**Pull request by jsoriano**

### CODE REVIEW

**Comment by jsoriano** [comment]
@kaiyan-sheng yes, this is what this PR fixes, cockroachdb module was on `dashboards` and it is moved to `dashboard`.

**Comment by jsoriano** [comment]
I have also lowercased the name of the module for coherence with the rest of dashboards.

**Comment by jsoriano** [comment]
jenkins, test this again please

**Comment by kaiyan-sheng** [comment]
@jsoriano Thanks for pointing that out 😂 I am not used to review pr looks like this I guess 😂

**Pull request merged**
