### PR TITLE
feat: stage execution cache

### PR DESCRIPTION
**Pull request by kuisathaverat**
## What does this PR do?

It implements a persistent status between stages executions for the same commit SHA.

## Why is it important?

This tries to resolve the use of resources and time when we run the same build for the same commit. To do that after the execution of each stage its status is saved, the next time the stage is executed for the same commit will decide if execute the stage based on its last result, so we will execute only once the stage for the same commit SHA. This will speed up the process to retry CI build in case of environmental issues, test failures, or any other flakiness.

## Checklist

- ~~[ ] My code follows the style guidelines of this project~~
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- ~~[ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

### CODE REVIEW

**Comment by kuisathaverat** [comment]
In this first implementation, we will see a step failing on all stages with a warning after, we have to find a way to avoid this error.

Screenshot 2021-03-26 at 12 14 38

**Comment by v1v** [comment]
> In this first implementation, we will see a step failing on all stages with a warning after, we have to find a way to avoid this error.

maybe if `BUILD_ID` == 1

**Review by v1v — APPROVED** [review]
💯

**Review by cachedout — APPROVED** [review]

**Review by urso — APPROVED** [review]

**Comment by kuisathaverat** [comment]
waiting for https://github.com/elastic/apm-pipeline-library/pull/1061

**Pull request merged**
