### PR TITLE
update go.mod to provide github.com/elastic/beats/v8

### LINKED ISSUE #31202: Update `go.mod` to provide github.com/elastic/beats/v8
We need to update our `go.mod` file to reflect our current major version, `v8`.

### PR DESCRIPTION
**Pull request by belimawr**
## What does this PR do?

It updates the `go.mod` file to profide the module github.com/elastic/beats/v8

## Why is it important?

I makes the Go module described by the `go.mod` compatible with our tags

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

~~## Author's Checklist~~
~~## How to test this PR locally~~

## Related issues

- Closes #31202
- Relates #123

~~## Use cases~~
~~## Screenshots~~
~~## Logs~~

### CODE REVIEW

**Review by cmacknz — APPROVED** [review]

**Comment by cmacknz** [comment]
Let's not worry about fixing the lint issues in this one. I assume all the changes are just find/replacing the version. I can barely load the diff :p

We will need to communicate this change to everyone with a dependency on beats, I think we've missed APM and Cloud Posture Security. I'll add them as reviewers.

**Comment by belimawr** [comment]
> Let's not worry about fixing the lint issues in this one. I assume all the changes are just find/replacing the version. I can barely load the diff :p
> 
> We will need to communicate this change to everyone with a dependency on beats, I think we've missed APM and Cloud Posture Security. I'll add someone from those teams as reviewers as an FYI.

Yes, it changed every single Go file and some others, so Lint is never gonna be happy.

That's the first time CI is happy and everything is breaking on my machine (python tests are not happy here because of opentelemetry :man_shrugging: ).

My browser was also not happy creating the PR, I almost could not type the PR description.

@cmacknz we really need to coordinate this because it's a moving target, if any files are added to main, they will have a different version on their imports and everything is gonna break.

**Review by kvch — CHANGES_REQUESTED** [review]
It was intentional. I am open to reconsidering it, but we decided it is not worth the extra hassle to update.

**Comment by cmacknz** [comment]
To summarize the prior reasoning for not changing this: moving to v8 it makes the project more consistent at the expense a lot of work and toil across many of our tools and repositories, and would also affect community uses of beats.

**Comment by axw** [comment]
I don't see any value in going back on the prior decision to stay at v7.

**Comment by belimawr** [comment]
Closing this PR because the decision of not updating had been taken already. Later I'll create an PR adding the note @cmacknz suggested.

**Comment by bleleve** [comment]
Hi there,

I'm sorry to come and put my two cents but this decision is surprising. By convention, the version of the Go package must correspond to the major version of the application.

If the package version is no longer consistent, you might as well delete it completely. This situation is difficult to understand for an external developer who wishes to participate in the development.

There is maybe no breaking changes at the moment, but it could happened.

Take care of you :)

**Comment by ph** [comment]
@bleleve This is a temporary changes, we are making a lot more changes under the hood and we have decided that is not currently work it to move to v8.

**Comment by cmacknz** [comment]
It was decided that v7 essentially means "latest", so keep using v7 pinned pinned to a commit on main or one of the v8.x.x release tags. There is no v8.

**Comment by akumar-evertz** [comment]
Well then why did you need to create tags for v8.#.# ? Why not just keep releasing v7.18.0? I cannot get this to work for my project. How are teams who are building beats using this library supposed to upgrade?. Pointing to commits is not working because `go mod tidy` just replaces it with `7.17.13` as it finds an import for `"github.com/elastic/beats/v7/libbeat/logp"` in my code.
```
go mod tidy -v
go: finding module for package github.com/prometheus/prometheus/pkg/exemplar
go: finding module for package github.com/elastic/beats/libbeat/logp
go: finding module for package github.com/elastic/beats/v7/libbeat/logp
go: found github.com/elastic/beats/v7/libbeat/logp in github.com/elastic/beats/v7 v7.17.13
```
I've tried requiring these

- 	github.com/elastic/beats/v7 v7.17.14-0.20230623162752-92c6b2370e46
- 	github.com/elastic/beats/v7 92c6b2370e46e549acda91b396f665a7e51e249c
- 	github.com/elastic/beats/v7 v7.0.0-alpha2.0.20230928231718-49cc14d35d5e

Some revert it back to 7.17.13 and some just error out.

**Pull request closed without merging**
