### PR TITLE
Fix for kafka log values

### PR DESCRIPTION
**Pull request by anx-mr**

### CODE REVIEW

**Comment by ruflin** [comment]
@anx-mr Can you share some more background on this?

**Comment by anx-mr** [comment]
The arguments are passed as slice (v) instead of a argument list (v...) which results in a wrong output in the log.

`2018/01/19 08:52:06.563449 log.go:36: INFO client/brokers registered new broker #[[3 %!d(string=server03.local:9093)]] at %!s(MISSING)
2018/01/19 08:52:06.563455 log.go:36: INFO client/brokers registered new broker #[[6 %!d(string=server06.local:9093)]] at %!s(MISSING)
2018/01/19 08:52:06.563492 log.go:36: INFO kafka message: [Successfully initialized new client]
2018/01/19 08:52:06.563663 log.go:36: INFO producer/broker/[[6]] starting up
2018/01/19 08:52:06.563679 log.go:36: INFO producer/broker/[[6 %!d(string=topic1) 0]] state change to [open] on %!s(MISSING)/%!d(MISSING)
2018/01/19 08:52:06.666677 log.go:36: INFO Connected to broker at [[server06.local:9093 %!s(int32=6)]] (registered as #%!d(MISSING))
2018/01/19 08:52:11.335943 log.go:36: INFO producer/broker/[[7]] starting up
2018/01/19 08:52:11.335995 log.go:36: INFO producer/broker/[[7 %!d(string=topic1) 1]] state change to [open] on %!s(MISSING)/%!d(MISSING)
2018/01/19 08:52:11.456625 log.go:36: INFO Connected to broker at [[server07.local:9093 %!s(int32=7)]] (registered as #%!d(MISSING))`

**Comment by ruflin** [comment]
jenkins, test it

**Comment by ruflin** [comment]
@urso We should probably forward port to this master and 6.2?

**Comment by urso** [comment]
@ruflin @anx-mr Oh, didn't notice this PR is on 6.1. Can you please open the PR on the master branch? I will take care of backporting the fix to all 6.x branches. Please add a changelog entry to Changelog.asciidoc as well.

**Comment by anx-mr** [comment]
Closed, new pull request for master: #6430

**Pull request closed without merging**
