### PR TITLE
[SM] Elasticsearch Mapping

### PR DESCRIPTION
**Pull request by sayden**
Elasticsearch Module: alpha version of the mappings rework.

### CODE REVIEW

**Comment by chrisronline** [comment]
I need a few more fields added back in:

- `elasticsearch.cluster.stats.license.expiry_date_in_millis`
- `elasticsearch.cluster.stats.indices.docs.total`
- `elasticsearch.cluster.stats.indices.store.size.bytes`
- `elasticsearch.cluster.stats.nodes.fs.total.available.bytes`
- `elasticsearch.cluster.stats.nodes.fs.total.total.bytes`
- `elasticsearch.cluster.stats.version` (The version of ES)

I'm only seeing the following metricsets too:

`cluster_stats`
`node`
`node_stats`

Are others coming soon? Like `index` related stats?

**Comment by chrisronline** [comment]
More missing fields:

- `elasticsearch.node.stats.process.cpu.pct`
- `elasticsearch.node.stats.os.cpu.load_avg.1m`
- `elasticsearch.node.stats.jvm.mem.heap.used.pct`
- `elasticsearch.node.stats.fs.summary.available.bytes`

It looks like there is a lot missing from `elasticsearch.node`. All I see is:

```
{
  "process": {
    "mlockall": false
  },
  "name": "cbr-mbp.lan",
  "id": "UhGiELUqTMi1fpu-VkO1Yw",
  "version": "8.0.0",
  "jvm": {
    "memory": {
      "nonheap": {
        "init": {
          "bytes": 7667712
        },
        "max": {
          "bytes": 0
        }
      },
      "heap": {
        "init": {
          "bytes": 1073741824
        },
        "max": {
          "bytes": 1073741824
        }
      }
    },
    "version": "15.0.1"
  }
}

```

**Comment by sayden** [comment]
> I need a few more fields added back in:
> 
>     * `elasticsearch.cluster.stats.license.expiry_date_in_millis`
> 
>     * `elasticsearch.cluster.stats.indices.docs.total`
> 
>     * `elasticsearch.cluster.stats.indices.store.size.bytes`
> 
>     * `elasticsearch.cluster.stats.nodes.fs.total.available.bytes`
> 
>     * `elasticsearch.cluster.stats.nodes.fs.total.total.bytes`
> 
>     * `elasticsearch.cluster.stats.version` (The version of ES)
> 
> 
> I'm only seeing the following metricsets too:
> 
> `cluster_stats`
> `node`
> `node_stats`
> 
> Are others coming soon? Like `index` related stats?

Now there's a need to activate all metricsets manually instead of just activating `xpack mode` like before, probably that's the cause of missing `index` fields.

I have just pushed the missing fields from cluster.stats in this commit https://github.com/elastic/beats/pull/23901/commits/4bfdf845356fcddfcc8d4b44f0a3b72cd83aade0

And I have pushed the missing fields from `node.stats` here https://github.com/elastic/beats/pull/23901/commits/ae1ff90e259168a84d993dc22e141b8344074de3

**Comment by chrisronline** [comment]
Thanks for the updates!

I have a few more issues:

- `elasticsearch.cluster.stats.license.expiry_date_in_millis` is always 0 for me
- `elasticsearch.version` (for `cluster_stats`) shows a number (`99`) instead of like `8.0.0-SNAPSHOT` like I'd expect
- `elasticsearch.nodes.versions` (for `cluster_stats`)

**Comment by chrisronline** [comment]
Also, I need the `state_uuid` to be present in the `shard` document type.

**Comment by chrisronline** [comment]
I'm going to need the `elasticsearch.node` key to be present for `ml_job` documents too.

I need `elasticsearch.ml.job.forecasts_stats` to be filled out.
I'm also not seeing anything for `elasticsearch.ml.job.model_size` (just an empty object)

**Comment by chrisronline** [comment]
I need

`elasticsearch.ccr.follower.failed_read_requests`
`elasticsearch.ccr.read_exceptions` (or this might go into follower)

**Comment by chrisronline** [comment]
I need:

- `elasticsearch.index.recovery.id` (number)
- `elasticsearch.index.recovery.name` (string)
- `elasticsearch.index.recovery.stage` (string)
- `elasticsearch.index.recovery.type` (string)
- `elasticsearch.index.recovery.primary` (bool)
- `elasticsearch.index.recovery.source.name` (string)
- `elasticsearch.index.recovery.source.transport_address` (string)
- `elasticsearch.index.recovery.target.name` (string)
- `elasticsearch.index.recovery.target.transport_address` (string)
- `elasticsearch.index.recovery.index.files.percent` (string)
- `elasticsearch.index.recovery.index.files.reused` (number)
- `elasticsearch.index.recovery.index.files.recovered` (number)
- `elasticsearch.index.recovery.index.files.total` (number)
- `elasticsearch.index.recovery.index.files.reused` (number)
- `elasticsearch.index.recovery.index.size.recovered_in_bytes` (number)
- `elasticsearch.index.recovery.index.size.reused_in_bytes` (number)
- `elasticsearch.index.recovery.index.size.total_in_bytes` (number)
- `elasticsearch.index.recovery.translog.total` (number)
- `elasticsearch.index.recovery.translog.percent` (string)
- `elasticsearch.index.recovery.translog.total_on_start` (number)

**Comment by chrisronline** [comment]
There is an alias that is wrong too.

`shard.node` should be `elasticsearch.node.id` (instead of `elasticsearch.node.name`)

**Comment by chrisronline** [comment]
I'm still not seeing `elasticsearch.cluster.stats.nodes.versions` which should be an array of the versions of all nodes in the cluster

**Comment by chrisronline** [comment]
How is this going? I'm still seeing some fields missing

**Comment by sayden** [comment]
I pushed all the missing fields I think, at least all the ones in `index_recovery` and `cluster_stats`. Which ones are missing?

**Comment by sayden** [comment]
Sooo, merging this into the feature branch!

**Comment by chrisronline** [comment]
This is the `fields.yml` for Kibana I used to get the UI working:

```
- key: kibana
  title: "Kibana"
  description: >
    Kibana module
  short_config: false
  release: ga
  settings: ["ssl", "http"]
  fields:
    - name: kibana_stats
      type: group
      fields:
        - name: timestamp
          type: alias
          path: "@timestamp"
        - name: kibana.response_time.max
          type: alias
          path: kibana.stats.response_time.max.ms
        - name: kibana.status
          type: alias
          path: kibana.stats.kibana.status
        - name: os.memory.free_in_bytes
          type: alias
          path: kibana.stats.os.memory.free_in_bytes
        - name: process.uptime_in_millis
          type: alias
          path: kibana.stats.process.uptime.ms
        - name: process.memory.heap.size_limit
          type: alias
          path: kibana.stats.process.memory.heap.size_limit.bytes
        - name: concurrent_connections
          type: alias
          path: kibana.stats.concurrent_connections
        - name: process.memory.resident_set_size_in_bytes
          type: alias
          path: kibana.stats.process.memory.resident_set_size.bytes
        - name: os.load.1m
          type: alias
          path: kibana.stats.os.load.1m
        - name: os.load.5m
          type: alias
          path: kibana.stats.os.load.5m
        - name: os.load.15m
          type: alias
          path: kibana.stats.os.load.15m
        - name: process.event_loop_delay
          type: alias
          path: kibana.stats.process.event_loop_delay.ms
        - name: requests.total
          type: alias
          path: kibana.stats.request.total
        - name: requests.disconnects
          type: alias
          path: kibana.stats.request.disconnects
        - name: response_times.max
          type: alias
          path: kibana.stats.response_time.max.ms
        - name: response_times.average
          type: alias
          path: kibana.stats.response_time.avg.ms
        - name: kibana.uuid
          type: alias
          path: kibana.stats.uuid
    - name: kibana
      type: group
      fields:
        - name: stats
          type: group
          fields:
            - name: uuid
              type: keyword
            - name: process
              type: group
              fields:
                - name: event_loop_delay
                  type: group
                  fields:
                    - name: ms
                      type: float
                - name: memory
                  type: group
                  fields:
                    - name: resident_set_size
                      type: group
                      fields:
                        - name: bytes
                          type: long
            - name: os
              type: group
              fields:
                - name: distro
                  type: keyword
                - name: distroRelease
                  type: keyword
                - name: platform
                  type: keyword
                - name: platformRelease
                  type: keyword
                - name: memory
                  type: group
                  fields:
                    - name: free_in_bytes
                      type: long
                    - name: total_in_bytes
                      type: long
                    - name: used_in_bytes
                      type: long
                - name: load
                  type: group
                  fields:
                    - name: 1m
                      type: half_float
                    - name: 5m
                      type: half_float
                    - name: 15m
                      type: half_float


```

**Pull request merged**
