### PR TITLE
Enable/test logstash output type

### PR DESCRIPTION
**Pull request by lykkin**
## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues
- Closes https://github.com/elastic/obs-dc-team/issues/601

### CODE REVIEW

**Comment by ph** [comment]
Ready to review?

**Comment by lykkin** [comment]
@ph there might be some more changes coming down the pipe depending on what changes are required in fleet-server, but might as well review/merge this test in.

**Review by blakerouse — COMMENTED** [review]
It would be great to expand on this to also add a test for a configuration with multiple outputs. 1 elasticsearch and 1 logstash.

**Comment by ph** [comment]
@lykkin This is a transformation test, did you take a look at the complexity to add real test with Logstash with the e2e framework, I don't know if it's possible or not. Note this would be a followup PR.

**Review by ph — CHANGES_REQUESTED** [review]
adding test with multiples outputs would be great ++

**Comment by nchaulet** [comment]
> @lykkin This is a transformation test, did you take a look at the complexity to add real test with Logstash with the e2e framework, I don't know if it's possible or not. Note this would be a followup PR.

It will be really nice to add a e2e test with multiple outputs, using Kibana API to get the logstash api key

**Comment by lykkin** [comment]
closing in lieu of https://github.com/elastic/elastic-agent/pull/199

**Pull request closed without merging**
