### PR TITLE
metricbeat/ci: update metricbeat version to 7.14

### PR DESCRIPTION
**Pull request by endorama**
## What does this PR do?

Update `beats-metricbeat` docker container used for testing to 7.14.0

## Why is it important?

In https://github.com/elastic/beats/pull/27416 the `beats-metricbeat` image has not been update because was producing [a test failure](https://github.com/elastic/beats/pull/27416#issuecomment-900304407). To unblock other work it was decided to postpone that update to a later date.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ] Before this PR can be reviewed and merged the issue presented in https://github.com/elastic/beats/issues/27495 must be addressed and resolved.

## Related issues

- Closes https://github.com/elastic/beats/issues/27495
- Relates https://github.com/elastic/beats/pull/27416

### CODE REVIEW

**Comment by endorama** [comment]
@jsoriano what do you think we should do on this one? As https://github.com/elastic/beats/issues/27495 is still open and we are already behind one version (7.15) I'm not sure this PR is still valid. But the issue is still there and I'd like to address it.

**Comment by jsoriano** [comment]
> @jsoriano what do you think we should do on this one? As #27495 is still open and we are already behind one version (7.15) I'm not sure this PR is still valid. But the issue is still there and I'd like to address it.

Well, someone should take a look to #27495, if you can do it, great :slightly_smiling_face:

**Comment by endorama** [comment]
Waiting on https://github.com/elastic/beats/pull/28782 to land to move this forward. I think is superseded, but in any case at the moment is blocked.

**Comment by jsoriano** [comment]
I think this can be moved forward :slightly_smiling_face: Thanks @endorama and @sayden!

**Pull request closed without merging**
