### PR TITLE
Cherry-pick #24502 to 7.x: Update gosigar package after fix

### PR DESCRIPTION
**Pull request by narph**
Cherry-pick of PR #24502 to 7.x branch. Original message:

## What does this PR do?

Described here https://github.com/elastic/gosigar/pull/159

## Why is it important?

Described here https://github.com/elastic/gosigar/pull/159

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes https://github.com/elastic/beats/issues/22501

### CODE REVIEW

**Review by kaiyan-sheng — APPROVED** [review]

**Comment by kuisathaverat** [comment]
I have relaunched e2e test only is the only thing is failing now

**Comment by kuisathaverat** [comment]
the build https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-24626/9/pipeline is green no changes since that build, the latest only do not run `Build&Test / x-pack/functionbeat-windows-2012-windows-2012-r2` stage everything else is fine. I think is fine to merge it.

**Pull request merged**
