### PR TITLE
chore: update remaining CI pipelines to k8s v1.31.0

### PR DESCRIPTION
**Pull request by mauri870**
## Proposed commit message

This PR fixes some leftovers from https://github.com/elastic/beats/pull/40856.

## Related issues

- Relates https://github.com/elastic/observability-dev/issues/3718
- Relates https://github.com/elastic/beats/pull/40856

### CODE REVIEW

**Review by rowlandgeoff — APPROVED** [review]

**Comment by mauri870** [comment]
This is breaking k8s integration tests for some reason, looking at the build logs I can't spot any meaningful error messages. Leaving this as draft for now.

**Comment by mauri870** [comment]
@elastic/obs-cloudnative-monitoring This PR is failing when running integration tests, but I can't spot any error messages in the logs. Any idea how I can go about debugging this? I can only spot a single error: 

`Error: failed modules: kubernetes`

**Comment by gizas** [comment]
@mauri870 wodnering if this has to do with the fact that you are trying to merge it 9.0 version and we still have some issues with the version of the packages.

For the troubleshooting I would advise to go to your local folder and :

```yaml
cd metricbeat 
mage goIntegTest
```

See also [here](https://github.com/elastic/beats/blob/main/docs/devguide/testing.asciidoc) some more info for how to run go tests for metricbeat

Can you reproduce the issue locally?

**Comment by mauri870** [comment]
> Can you reproduce the issue locally?

Thanks! I tested this locally and it does not seem to fail for me. I pushed a debug log to test it on BK and I got the actual error:

```
Error: failed to run integration tests for module kubernetes:
1 error: kind setup failed: running "kind create cluster --name metricbeat-9-0-0-921fd909f7-snapshot --kubeconfig /opt/buildkite-agent/builds/bk-agent-prod-gcp-1729021037068466664/elastic/beats-metricbeat/metricbeat/build/kind/metricbeat-9-0-0-921fd909f7-snapshot/kubecfg --wait 300s --image kindest/node:v1.31.0" failed with exit code 126

```
https://buildkite.com/elastic/beats-metricbeat/builds/10481#019291a8-1c9d-4180-b768-80e832625d12/191-2135

Trying this command locally works just fine, I'm not sure what exact problem the builder is experiencing.

**Comment by mauri870** [comment]
@gizas Turns out something broke between kind v0.20.0 and v0.24.0 that is causing failures in BK.

**Comment by mauri870** [comment]
Raised https://github.com/elastic/beats/issues/41257 so we can look into the failure in a separate issue.

**Comment by mauri870** [comment]
Enabled auto-merge.

**Review by belimawr — APPROVED** [review]

**Pull request merged**
