### PR TITLE
Rework processors checkContains condition (#3138)

### PR DESCRIPTION
**Pull request by roylee17**
Handle potential string array (only at root level though).

If any entry contains the target string, return true.
Otherwise, continue the search.

When a invalid entry is found, emit a debugging message and
conitinue the search.

### CODE REVIEW

**Comment by roylee17** [comment]
Okay, confirmed the email address of CLA.

**Comment by roylee17** [comment]
Previous revision changes the logics and breaks the test cases.
This one only handles the issue reported by #3138 

Discussion:
Not sure this is the right place to "fix" it.
The Conditions assumes the input are valid (strings, []string), which makes perfect sense. And it's covered by the test as well.

It is the Json parser / processor's responsibility to handle the array.
In that case, either we need another pass to check the unmarshalled map for the array and convert/reject the input, or a modified Json decoder, which convert the array in the first place during the parsing.

Either way seems to be over kill for the corner case. Any thought?

**Comment by andrewkroh** [comment]
@roylee17 Thanks for looking into the issue.

I'm thinking this conversion should take place in the normalization phase. Events that come into the publisher pipeline first go through "normalization" where by the `[]interface{}` passes through [here](https://github.com/elastic/beats/blob/master/libbeat/common/event.go#L168). Probably this code should catch this and fix the type. WDYT?

Another corner case I see is with the new `decode_json_fields` process that was added. The processors run after the normalization (they're the reason for the normalization). And because the `decode_json_fields` processor can add new data to the event, this new data could contain `[]interface{}` (I think, I didn't check the [code](https://github.com/elastic/beats/blob/master/libbeat/processors/actions/decode_json_fields.go)).

**Comment by roylee17** [comment]
@andrewkroh Thanks for the tip. That makes much more sense. I'll get back with another attempt.

**Comment by andrewkroh** [comment]
@roylee17 Could you please add some tests to accompany this change?

**Pull request closed without merging**
