### PR TITLE
add .python-verson file

### PR DESCRIPTION
**Pull request by belimawr**
## What does this PR do?

Add .python-version file with the same version we're using on CI.

## Why is it important?

It documents which Python version should be used an allows for the use of pyenv to manage the Python version automatically.
Currently our system tests are not compatible with Python >= 3.10.0

## Checklist

- ~~[ ] My code follows the style guidelines of this project~~
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

~~## Author's Checklist~~
## How to test this PR locally

Install Pyenv and run
```sh
pyenv version
```

The output should state that the Python version is set by the `.python-version` file on the root of this repository.

~~## Related issues~~

## Use cases

Any engineer trying to run system tests on a system with Python >= 3.10

~~## Screenshots~~
~~## Logs~~

### CODE REVIEW

**Comment by belimawr** [comment]
I've just realised that `pyenv` is breaking with Python 3.6.9:
```
 tiago@millennium-falcon~/devel/kube/devel/beats % pyenv install    
Downloading Python-3.6.9.tar.xz...
-> https://www.python.org/ftp/python/3.6.9/Python-3.6.9.tar.xz
Installing Python-3.6.9...
/home/tiago/.pyenv/plugins/python-build/bin/python-build: line 1710: 1072377 Segmentation fault      (core dumped) "$PYTHON_BIN" -c "import $1" > /dev/null 2>&1
WARNING: The Python ctypes extension was not compiled. Missing the libffi lib?
WARNING: The Python tkinter extension was not compiled and GUI subsystem has been detected. Missing the Tk toolkit?
/home/tiago/.pyenv/plugins/python-build/bin/python-build: line 1921: 1072398 Segmentation fault      (core dumped) "$PYTHON_BIN" -s -m ensurepip ${ensurepip_opts} > /dev/null 2>&1
Installing pip from https://bootstrap.pypa.io/pip/3.6/get-pip.py...
/home/tiago/.pyenv/plugins/python-build/bin/python-build: line 1902: 1072470 Segmentation fault      (core dumped) "${PYTHON_BIN}" -s "${get_pip}" ${GET_PIP_OPTS} 1>&4 2>&1
error: failed to install pip via get-pip.py
```

But it works file with Python 3.9.13
```
tiago@millennium-falcon~/devel/kube/devel/beats % pyenv install
Downloading Python-3.9.13.tar.xz...
-> https://www.python.org/ftp/python/3.9.13/Python-3.9.13.tar.xz
Installing Python-3.9.13...
WARNING: The Python tkinter extension was not compiled and GUI subsystem has been detected. Missing the Tk toolkit?
Installed Python-3.9.13 to /home/tiago/.pyenv/versions/3.9.13

 tiago@millennium-falcon~/devel/kube/devel/beats(filestream-input-id-bookkeeper-fix|✚5…) % python --version
Python 3.9.13
```

Should we set our Python version to 3.9.13? 

@cmacknz Any thoughts here?

I'll update to 3.9.13 and see if it changes anything on CI.

**Comment by cmacknz** [comment]
Because this didn't change any of the source files I don't think it actually triggered any of the tests: https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-32323/4/pipeline

We probably have to do it manually. No opposition to this as long as it doesn't break anything.

**Review by cmacknz — APPROVED** [review]

**Pull request merged**
