### PR TITLE
default bulk sizes

### PR DESCRIPTION
**Pull request by urso**
related to #587 

- set default spooler size in filebeat to 2048, in order to increase number of
  lines to be combined into one bulk request

- set default bulk max size to 2048, to guarantee not to split bigger bulk
  requests into too many small requests.

Tested different spooler and bulk sizes using NASA-HTTP logs:

    spooler          bulk  | cpu(%)   mem-res(MB)  throughput(1k lines/s)
    ---------------------------------------------------------------------
     1024            200   |  26        20              2.1
     1024            1024  |  55        20             15.7
     2048            2048  |  66        25             18.2
     3072            3072  |  66        28             18.5
     4096            4096  |  70        33             18.7

### CODE REVIEW

**Comment by tsg** [comment]
Doesn't this potentially cause memory issues for Packetbeat? It can be 1000 * 2048 transactions stored in memory, right?

**Comment by urso** [comment]
We already have some memory issues in topbeat and packetbeat. I have another PR in the pipeline to address this issue.

**Comment by tsg** [comment]
Ok, then we just need to make sure both changes are merged in all the same branches. If the other change is small, might then make sense to put it in this PR?

**Comment by dedemorton** [comment]
Should we also update the doc to show the new default in the example here? https://www.elastic.co/guide/en/beats/filebeat/1.0.1/filebeat-configuration-details.html#_spool_size

**Comment by urso** [comment]
@dedemorton good point. thanks

**Comment by urso** [comment]
see PR #649 for limiting total number of buffered events

**Comment by ruflin** [comment]
LGTM

**Pull request merged**
