### PR TITLE
[Heartbeat] Revert use of wildcard fields

### PR DESCRIPTION
**Pull request by andrewvc**
In #17687 new x509 fields were added, and the new `wildcard` field type was used. Since wildcard fields have been reverted in Elasticsearch 7.x we should revert them here too, to align the 8.x branch of Heartbeat with the 7.x branch. It wouldn't make sense to have the field mappings go out of alignment with a major version change.The 7.x [backport](https://github.com/elastic/beats/pull/18029) of #17687 has this fix rolled in directly, so no backport is needed.

### CODE REVIEW

**Comment by andrewvc** [comment]
@jenkins retest

**Comment by andrewvc** [comment]
Jenkins retest

**Comment by andrewvc** [comment]
Jenkins, retest this please

**Comment by kuisathaverat** [comment]
jenkins run the test

**Comment by andrewvc** [comment]
jenkins, retest this

docker failed

**Comment by kuisathaverat** [comment]
jenkins run the tests

**Pull request merged**
