### PR TITLE
fix: missing colon in yaml example

### PR DESCRIPTION
**Pull request by Fuco1**
## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by EamonnTP** [comment]
Hi @Fuco1 Thanks for your contribution. Would you mind signing the [Contributor Agreement](https://www.elastic.co/contributor-agreement)?

**Comment by Fuco1** [comment]
Hey @EamonnTP, just signed it.  I suppose you will get notified via some API call, or should I upload the PDF?  Thanks!

**Comment by EamonnTP** [comment]
jenkins run the tests please

**Review by EamonnTP — APPROVED** [review]

**Comment by EamonnTP** [comment]
Thanks @Fuco1

**Comment by EamonnTP** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Pull request merged**
