### PR TITLE
Backport: Fix for errno 1734 when calling EvtNext (#3112)

### LINKED ISSUE #3076: Winlogbeat - Reading large events causes error "The array bounds are invalid."
- Version: 5.0.2 (probably exists in all versions)
- Operating System: Windows 2012 Server R2 (probably affects Vista and newer)
- Steps to Reproduce: 

When reading a batch of large event log records the Windows function [`EvtNext`](https://msdn.microsoft.com/en-us/library/windows/desktop/aa385405%28v=vs.85%29.aspx?f=255&MSPPError=-2147217396) returns errno 1734 (0x6C6) which is [RPC_S_INVALID_BOUND](https://msdn.microsoft.com/en-us/library/windows/desktop/ms681386(v=vs.85).aspx#RPC_S_INVALID_BOUND) ("The array bounds are invalid."). This seems to be a bug in Windows because there is no documentation about this behavior.

It seems that when calling `EvtNext` that internally it is allocating space for the events whose handles it will return. So if the combined size of the events being returned by `EvtNext` reaches some limit the RPC_S_INVALID_BOUND error is returned. In Winlogbeat, if you increase the `batch_read_size` you are more likely to encounter the problem, but even with a `batch_read_size` of 64 (default is 100) I was able to hit the error when reading large events.

Recovering from this problem is not as simple as calling `EvtNext` again with a smaller batch size. The internal read position associated with the event log handle is being updated even when `EvtNext` returns the RPC_S_INVALID_BOUND error. So if we just called it again we would lose events. We will have to close the event log and re-open it from the last read event and decrease the `batch_read_size` until success.

- Workaround: Set a lower value for `batch_read_size`.

### PR DESCRIPTION
**Pull request by andrewkroh**
Backport #3112 to 5.1 branch

> When reading a batch of large event log records the Windows function
EvtNext returns errno 1734 (0x6C6) which is RPC_S_INVALID_BOUND ("The
array bounds are invalid."). This seems to be a bug in Windows because
there is no documentation about this behavior.
>
>This fix handles the error by resetting the event log subscription
handle (so events are not lost) and then retries the EvtNext call
with maxHandles/2.
>
>Fixes #3076

(cherry picked from commit 226eb10ce03042c3259e8055b18ddc8193fde519)

### CODE REVIEW

**Comment by ruflin** [comment]
@andrewkroh This seems to break the the winlogbeat tests

**Comment by tsg** [comment]
Still fails, I'll wait for @andrewkroh then and don't include this one in 5.1.1 since I think it's too late now.

**Comment by maddin2016** [comment]
@andrewkroh, @tsg 
```
const letterBytes = "abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZ"
const (
	letterIdxBits = 6                    // 6 bits to represent a letter index
	letterIdxMask = 1<<letterIdxBits - 1 // All 1-bits, as many as letterIdxBits
	letterIdxMax  = 63 / letterIdxBits   // # of letter indices fitting in 63 bits
)
```
import "math/rand"

and instead `rng.Int63` `rand.Int63` works for me.

**Comment by andrewkroh** [comment]
I added d75667bc28fd44b685d86e6db5f81f5df71ce0c5 which has only the `bench_test.go` file containing the missing helper function.

**Comment by andrewkroh** [comment]
jenkins, test it

**Pull request merged**
