### PR TITLE
Cherry-pick #23858 to 7.x: Panic when using inline SSL certificate or key

### PR DESCRIPTION
**Pull request by ph**
Cherry-pick of PR #23858 to 7.x branch. Original message: 

When the key or certificate was smaller than 256bytes the system was
throwing a panic, the problem was generate by a debug message. Instead
of logging part of the keys or certificate in the log we are just
writing "inline".

Fixes: #23820

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Review by blakerouse — APPROVED** [review]
Backport looks good.

**Comment by ph** [comment]
Jenkins test this please

**Comment by ph** [comment]
Jenkins test this please

**Comment by ph** [comment]
merging this, talked with @urso he will do a PR to improve the udp test.

**Pull request merged**
