### PR TITLE
Update test-audit-800.log

### PR DESCRIPTION
**Pull request by ppf2**
Adding additional examples of audit logging that requires additional handling of `request.body` to our test log.
Ref: https://github.com/elastic/beats/issues/30678#issuecomment-1068659813

### CODE REVIEW

**Comment by matschaffer** [comment]
Thanks @ppf2 ! Not sure how far you want to take this. The "Build&Test / filebeat-pythonIntegTest / test_fileset_file_081_elasticsearch – filebeat.tests.system.test_modules.Test" error is exactly what I'd expect.

I put the issue on the infra monitoring ui board for prioritization at least.

https://www.elastic.co/guide/en/beats/devguide/current/filebeat-modules-devguide.html#_test has instructions on how to run tests and update the expectation files if you or someone wanted to give it a shot before we get to it.

**Comment by matschaffer** [comment]
@ppf2 responded that he'll leave this as-is for @elastic/infra-monitoring-ui to continue, so I've cleared his assignment.

**Comment by rdner** [comment]
@ppf2 apparently this requires the integration tests to be updated too.

**Comment by matschaffer** [comment]
I've removed this from the @elastic/infra-monitoring-ui PR review queue. We'll pick it back up as part of https://github.com/elastic/beats/issues/30678

**Comment by miltonhultgren** [comment]
Maybe we should move this PR back to draft in the meantime?

**Comment by jlind23** [comment]
Closing this for now as it is outdated, but feel free to reopen it if needed.

**Pull request closed without merging**
