### PR TITLE
upgrade mssql driver to v0.12.3

### PR DESCRIPTION
**Pull request by muthu-mps**
Enhancement
What does this PR do?
Updating the go-mssql driver library to latest version 0.12.3

Why is it important?
Fixes https://github.com/elastic/beats/issues/33482

### CODE REVIEW

**Review by rdner — APPROVED** [review]

**Comment by lalit-satapathy** [comment]
@muthu-mps, what all tests we ran with this update, please capture..

**Comment by muthu-mps** [comment]
Testing done manually by upgrading the driver version,

**Test Scenarios:**

- Executed testing by establishing normal database connection with username and password.
- Done testing with domain user setup.
- Configured named instance to collect data.
- Platform specific testing done windows 2019 & 2022
- Verified data is processed for both performance & transaction log datastreams.

**Comment by shmsr** [comment]
Can we rename the title of this PR to (or something similar):

> Bump `github.com/denisenkom/go-mssqldb` to v0.12.3

or

> Upgrade `github.com/denisenkom/go-mssqldb` to v0.12.3

Then commit message would be clear and in proper format when we merge the same.

**Review by shmsr — CHANGES_REQUESTED** [review]
Can we rename the title of this PR to (or something similar):

> Bump `github.com/denisenkom/go-mssqldb` to v0.12.3

or

> Upgrade `github.com/denisenkom/go-mssqldb` to v0.12.3

Then commit message would be clear and in proper format when we merge the same.

cc: @muthu-mps

Other than the PR title the changes LGTM.

**Review by shmsr — APPROVED** [review]

**Pull request merged**
