### PR TITLE
Cherry-pick #23763 to 7.x: [Filebeat] Check if processor is supported by ES version

### PR DESCRIPTION
**Pull request by P1llus**
Cherry-pick of PR #23763 to 7.x branch. Original message: 

## What does this PR do?

A new function to make it easy to set minimum versions for processors. This allows modules to have pipelines that includes newer processors, while having a fallback if the ES version is too old.

Compared to existing functions which checks for specific options inside a processor, this checks for processors as a whole.

This PR is needed to close #22768 .

## Why is it important?

Allows Filebeat modules to use newer ingest pipeline processors while not having to worry about backwards compatibility with the processor itself.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

### CODE REVIEW

**Review by marc-gr — APPROVED** [review]

**Comment by P1llus** [comment]
jenkins run tests please

**Comment by P1llus** [comment]
Needed to add the variable declaration, due to the fact that ML in beats is removed in `master` but not in `7.x`, ref: https://github.com/elastic/beats/commit/b1e53e407514521a04ed5c384be786aa5b5adb37

**Comment by P1llus** [comment]
jenkins run tests please

**Comment by P1llus** [comment]
jenkins run tests please

**Pull request merged**
