### PR TITLE
Merge the Elastic Logging Plugin to master

### PR DESCRIPTION
**Pull request by fearful-symmetry**
See elastic/beats#13990 and  elastic/beats#13761

## What is this?

This is a new beat that takes the form of a docker [plugin](https://docs.docker.com/config/containers/logging/configure/) for logs. The only release artifact takes the form of a plugin (which is basically a runc container) which lives in a docker repo. Aside from the different release artifacts, this operates under the hood as a normal beat. It uses libbeat, and takes many of the same configuration options as any other beat. 

# How to test

Once you have the branch checked out, navigate to `x-pack/dockerlogbeat`. Run `mage package` on a host with docker to generate the plugin.  

You can test like this:

```
docker run --log-driver=elastic/elastic-logging-driver:8.0.0 \
--log-opt output.elasticsearch.hosts="172.18.0.2:9200" \
--log-opt output.elasticsearch.index="dockerbeat-test" \ 
-it debian:jessie /bin/bash`
```

I've never merged a new beat to master, so I'm not entirely sure what needs to happen.

### CODE REVIEW

**Comment by urso** [comment]
@fearful-symmetry @dedemorton Do we have any docs planned for this project?

**Comment by fearful-symmetry** [comment]
@fearful-symmetry @dedemorton Docs are on my list on #13990 honestly have No idea where to start with proper asciidocs.

**Comment by dedemorton** [comment]
I told Alex that I would help them set up some skeleton asciidoc files when I get back from vacation in January. I'm planning some structural changes that I want to make in parallel for some stuff that I've been stalled on for awhile.

**Comment by urso** [comment]
@dedemorton @fearful-symmetry Thanks for the clarification. I guess we can proceed merging the plugin then.

**Pull request merged**
