### PR TITLE
Looks there is a typo in id-compliance .

### PR DESCRIPTION
**Pull request by makwanji**
## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by bmorelli25** [comment]
Thanks, Jignesh! Would you mind signing the [CLA](https://github.com/elastic/beats/pull/30762#issuecomment-1063641840) if you haven't already?

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by dedemorton** [comment]
Replaced by https://github.com/elastic/beats/pull/31136.

**Pull request closed without merging**
