### PR TITLE
Make python tests not executables

### PR DESCRIPTION
**Pull request by tsg**
Turns out that if a `test_*.py` file is executable, nosetests
doesn't pick it up, so the tests are not executed on Linux/Mac.
This was the case with two files in Filebeat.

This adds a `make check` check to look for such files, so this
doesn't happen in the future.

### CODE REVIEW

**Comment by tsg** [comment]
I opened this separately from #5443 so we can backport it immediately to the 6.0 branch.

**Comment by andrewkroh** [comment]
`find: invalid mode ‘+111’` coming from Jenkins

**Comment by andrewkroh** [comment]
man find
> -perm +mode
> This is no longer supported (and has been deprecated since 2005).  Use -perm /mode instead.

These work on Linux but not on macOS. hmm

`-perm /a+x`
`-type f  -executable`

**Comment by andrewkroh** [comment]
`test_prospector.Test.test_harvester_limit` is failing on Travis for both Linux and macOS, but it's passing on Jenkins.

**Comment by tsg** [comment]
That test seems stable on my computer, so I'm pretty clueless on why it might fail on Travis only.

**Comment by tsg** [comment]
No, I spoke to soon. The test is flaky and I could get it to fail on my laptop when running it in a loop.

**Comment by tsg** [comment]
I opened #5458 for the flaky test.

**Comment by tsg** [comment]
I skipped the flaky test, we have #5458 to track that.

**Comment by tsg** [comment]
jenkins, test it

**Pull request merged**
