### PR TITLE
Upgrade kind version used for k8s testing

### PR DESCRIPTION
**Pull request by ChrsMark**
## What does this PR do?
Upgrade `kind` version to the latest one.

### CODE REVIEW

**Review by mdelapenya — APPROVED** [review]

**Review by MichaelKatsoulis — APPROVED** [review]

**Comment by ChrsMark** [comment]
@mdelapenya seems like the backport bot does not really handle the backports 🤔 ? I checked in the history and found some others that backports were not opened like https://github.com/elastic/beats/pull/30631.

**Comment by v1v** [comment]
@ChrsMark, I'm afraid the backport-v8.2.0 is not yet available, and likely it points to `main` since main is 8.2 based. What branch would you need to backport this particular PR to? The backport definitions can be found in https://github.com/elastic/beats/blob/a92e38fe199f99dca2470a99a519166604d63b17/.mergify.yml#L210-L248

**Comment by ChrsMark** [comment]
@v1v my goal is to make sure that this PR will make it to 8.2 and since ff for 8.1 has passed already I would expect that backporting to 8.2/8.x is the way to go now. Does this mean that `master`==`8.2` at the moment?

**Comment by v1v** [comment]
>  Does this mean that master==8.2 at the moment?

I think so, though I'm not part of the release process for Beats. 

As far as I see, you can see those details in:
- https://github.com/elastic/beats/blob/main/libbeat/version/version.go#L21
- `CI=true make get-version`

**Pull request merged**
