### PR TITLE
Fix export dashboards scripts

### PR DESCRIPTION
**Pull request by ChrsMark**
## What does this PR do?
This PR adds `ExportDashboard` target in magefile of Metricbeat and fixes username+password defaults order in `dev-tools/cmd/dashboards/export_dashboards.go`

## Why is it important?
So as to make it possible to export Metricbeat dashboards with a command like `KIBANA_URL=http://elastic:changeme@0.0.0.0:5601 MODULE=kubernetes ID=e0381d10-e4a6-11eb-9d53-3b3d1d47c519 mage ExportDashboard`

Related to https://github.com/elastic/beats/pull/30913

### CODE REVIEW

**Review by kvch — APPROVED** [review]

**Comment by ChrsMark** [comment]
Thanks for the review @kvch . I think we also miss a `dashboards.DecodeExported(result)` for the single dashboard export flow. Added in https://github.com/elastic/beats/pull/30929/files#diff-cbc26b7b9aa708219bc0cff2322887da00a74d84eff73e03c375ba8fdebdb937R137. This is most probably the reason for the failure at https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-30913/1/pipeline/  ([code](https://github.com/elastic/beats/pull/30913/files#diff-c4aedca68489c88cbc4d582d5974482935c4c60ef9fee0344eeb1f50d76aefe9R6))

**Review by jsoriano — COMMENTED** [review]
It LGTM, if we want to add this subcommand.

I think that there should be a single way to export dashboards. With this there will be two: `mage exportDashboards` and `*beat export dashboard`. In my opinion the beats subcommand is a better option because it allows to export dashboards with any beats binary without requiring the development environment. Adding this target is something else to maintain.

If we have documentation refering to this non-existing target, we could fix these docs to use the beats subcommand instead.

If there is something that can be done with the mage target, and not with the beats subcommand, I think we should fix the subcommand.

If both things are kept, but they produce different files, I think this should be reviewed too, it is confusing to have two ways of doing the same thing, but that produce slightly different files.

I will leave the final decision to @elastic/elastic-agent-data-plane, as they will need to maintain this if added.

Note: `elastic-package export dashboard` is another way to export dashboards, we tried to make both formats compatible, but there may be issues. It would be a pity if they are not compatible, but I wouldn't introduce breaking changes at this point on any side to make them compatible, so let's keep this separated.

**Review by cmacknz — APPROVED** [review]

**Comment by cmacknz** [comment]
I agree with @jsoriano, change itself looks good (hence my previous approval) but I'm curious why the metricbeat [export](https://www.elastic.co/guide/en/beats/metricbeat/current/command-line-options.html#export-command) command wouldn't work for this?

**Comment by ChrsMark** [comment]
This is what I get when trying the `export` command
```
./metricbeat export dashboard -yml ./module/kubernetes/module.yml -folder dashboards -E setup.kibana.host="http://elastic:changeme@0.0.0.0:5601/"
Error exporting dashboards from yml: error exporting dashboard: Error fetching objects to export: 1 error: id: AV4RGUqo5NkDleZmzKuZ, message: Saved object [dashboard/AV4RGUqo5NkDleZmzKuZ] not found, code: 400
failed exporting id=AV4RGUqo5NkDleZmzKuZ
```

**Pull request merged**
