### PR TITLE
add percona support to filebeat-module-mysql-slowlog

### PR DESCRIPTION
**Pull request by HagK**
added grok pattern for percona slowlogs, includes optional InnoDB statistics
see #6665

### CODE REVIEW

**Comment by elasticcla** [comment]
Hi @HagK, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/beats/pull/10210.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by jsoriano** [comment]
@HagK thanks for your help here!

I have opened another PR to merge both patterns and support the example file you provided, find it here #10227, I have added you as co-author.

Let me know what you think.

**Comment by HagK** [comment]
@jsoriano the new PR it's fine for me. But as i understand, the gsub-pattern for Time must be extended too, because percona use the ISO 8601 timeformat with alnum characters. As i remember, i had some errors before i changed it.

**Comment by jsoriano** [comment]
@HagK good point, I think this would have been needed before, but not after [this change](https://github.com/elastic/beats/commit/b29ddfcb3480b0707eddbbcbf3f566648d718daf#diff-4a06404e8cd0b6fcefb0772c5720d6b7L11) that removes also the lines starting with `# Time`.

Actually I am going to remove this part of the pipeline.

**Comment by jsoriano** [comment]
#10227 merged, closing this.

**Pull request closed without merging**
