### PR TITLE
Typo in "kube-state-metrics" in modules/kubernetes asciidoc documentation

### PR DESCRIPTION
**Pull request by jdbaldry**

### CODE REVIEW

**Comment by jdbaldry** [comment]
Have now signed CLA.

**Comment by exekias** [comment]
Thank you so much @jdbaldry :tada: ! could you please also update `metricbeat/module/kubernetes/_meta/docs.asciidoc`?

**Comment by jsoriano** [comment]
jenkins, test this please

**Comment by ruflin** [comment]
This PR seems to fail CI because it was opened in 2018 and we had to change some license files in 2019. At the same time I don't see a reason this would fail after merging into master.

@jsoriano WDYT, should we merge as is.
@jdbaldry An alternative would be if you could rebase this PR on top of master?

**Comment by jsoriano** [comment]
I was checking and these typos are already fixed in master and 6.x, I am closing this.

**Pull request closed without merging**
