### PR TITLE
feature - parallelization factor kinesis functionbeat config

### PR DESCRIPTION
**Pull request by ravinaik1312**
## What does this PR do?

This PR adds the ability to add the parallelization factor configuration to functionbeat when reading from Kinesis streams. 
https://aws.amazon.com/about-aws/whats-new/2019/11/aws-lambda-supports-parallelization-factor-for-kinesis-and-dynamodb-event-sources/

## Why is it important?

This configuration allows you to process one shard of a Kinesis or DynamoDB data stream with more than one Lambda invocation simultaneously.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes https://github.com/elastic/beats/issues/16901

### CODE REVIEW

**Comment by ravinaik1312** [comment]
@olksdr @gtback Did the CCLA get added for my Github user?

**Comment by olksdr** [comment]
@ravinaik1312 CLA is in our lists. The message https://github.com/elastic/beats/pull/20727#issuecomment-677949925 points to the commit which is wrong.  When you look [into it](https://github.com/elastic/beats/commit/bbc670eb41a7db244d7f68a33e760ec73f47645b.patch) it was done with completely different email, I assume with wrong gitconfig - because you first commit does not show the github user either. Last merge commit looks good. 
Could you, please, squash the commits and rebase to remove that failed commit from history ?

**Comment by kvch** [comment]
jenkins run tests

**Comment by kvch** [comment]
@ravinaik1312 Awesome PR! Could you please add an entry to the changelog?

**Comment by ravinaik1312** [comment]
> @ravinaik1312 Awesome PR! Could you please add an entry to the changelog?

Thank you! I've updated the `changelog.next.asciidoc`, let me know if there are other changelog files that needs to be updated too.

**Comment by kvch** [comment]
jenkins run tests

**Review by kvch — APPROVED** [review]

**Comment by gtback** [comment]
Thanks @ravinaik1312 !

**Pull request merged**
