### PR TITLE
[Heartbeat] Add certificate tracking fields

### PR DESCRIPTION
**Pull request by sashizu**
We are using heartbeat for monitoring TLS/SSL certificates in our infrastructure.

This request would add the following fields to Heartbeat under the TLS key:

- certificate_root_common_name: Common Name of certificate root certificate authority
- certificate_issuer_common_name: Common Name of certificate issuing certificate authority
- certificate_common_name: Common Name of certificate. Useful in identifying wildcards.

We use this information for a certificate tracking dashboard and thought others may find it useful.

### CODE REVIEW

**Comment by sashizu** [comment]
Travis CI returning the following error: 

ERROR: docker-compose 1.23.2 has requirement PyYAML<4,>=3.10, but you'll have pyyaml 4.2b1 which is incompatible.

**Comment by jsoriano** [comment]
Thanks @sashizu for opening this PR :slightly_smiling_face: 

> Travis CI returning the following error:
> 
> ERROR: docker-compose 1.23.2 has requirement PyYAML<4,>=3.10, but you'll have pyyaml 4.2b1 which is incompatible.

You can ignore this error.

The build seems to be failing because of some formatting issue:
```
./monitors/active/dialchain/tls.go

Code differs from goimports' style ^
```

You can try to automatically fix it with `make update fmt` and committing the results.

**Comment by andrewvc** [comment]
Can you provide a bit more context about this change? I'm a bit on the fence about adding this data since it's not strictly related to a site's being up. Would also like @tbragin 's thoughts. 

@sashizu I'd love to hear more about why it made sense to add this data to heartbeat vs. using a separate cert scanning tool.
Also, uptime records this data with each check, is there value in seeing that data on each check for your use case?

**Comment by andrewvc** [comment]
Thanks for opening this issue  @sashizu !

Given the lack of response/discussion here I'm going to close this. There doesn't seem to be a strong enough case for this to put on our roadmap. If you'd like to revive this discussion please open a new issue.

**Pull request closed without merging**
