### PR TITLE
[docs] Add Elastic Agent doc changes for 7.9

### PR DESCRIPTION
**Pull request by dedemorton**
Adds beats-related ingest management changes for 7.9. Preview: https://beats_20437.docs-preview.app.elstc.co/guide/en/ingest-management/master/elastic-agent-installation-configuration.html (look at Elastic Agent changes only)

Requires https://github.com/elastic/observability-docs/pull/80

REVIEWERS: Our tabbed panels are evolving. We need to inject the HTML directly into the build right now, but that will change in the future. For now, the best way to review the content there is to look at the rendered content in the preview.

Please don't review the javascript or css (that's already been reviewed--I'm just copying it here).

### CODE REVIEW

**Comment by dedemorton** [comment]
@EricDavisX @hbharding This PR needs to be reviewed and merged before elastic/observability-docs#80 will pass. Note my comment in the original description for how to proceed with reviewing the tabbed panel "widgets."

**Comment by EricDavisX** [comment]
@dedemorton hi - I am reviewing.  I have some minor and some more important feedback, but none of it is preventative to merging to get the delta smaller for our discussions.  Not sure if you want to make more changes now or push it in and keep iterating?

Here are the first 2 items I wanted to confirm (first is not a bug maybe, probably process thing I need help on):

1)this page links to 8.0, which is not available as GA (correctly).  is it right that its pointing to 8.0 ? https://beats_20437.docs-preview.app.elstc.co/guide/en/ingest-management/master/elastic-agent-installation.html

2) now that I know more, I can cite we should adjust the Agent 'install' and 'run' steps a bit.  I love seeing it broken by platform, this is a huge clarity enhancement for users.   

might be easier to do a zoom but I'm happy to write out my thoughts to post in-line feedback

**Comment by dedemorton** [comment]
@EricDavisX 

>this page links to 8.0, which is not available as GA (correctly). is it right that its pointing to 8.0 ? https://beats_20437.docs-preview.app.elstc.co/guide/en/ingest-management/master/elastic-agent-installation.html

Yup, it's right. I use a variable to resolve the version. When I port this change to 7.9, it will show the correct version. I've temporarily set the `release-state` attribute to `released` so that you can see the commands for review purposes, but before merging, I'll remove that override so that users looking at the `master` version of docs won't see any installation instructions.

Happy to zoom if that's easier for you. Might be more efficient because I've done some things to work around the current design and should explain those because I expect more changes before GA.

**Comment by dedemorton** [comment]
@EricDavisX Oh heck. I just realized that the override is in the other PR. I'll add it here so you can see the commands properly in the preview without having to look at the diff.

**Comment by EricDavisX** [comment]
For details, I just finished reviewing - here is what I have and it is less impactful than I thought, the docs are in really good shape here, well done!

1) from https://beats_20437.docs-preview.app.elstc.co/guide/en/ingest-management/master/elastic-agent-installation.html

a) the powershell command when run on windows will actually 'start' the agent too.  we could move steps 3-5 to the 'start agent' page?  Its ok to leave them here, but its a little more consistent to have just the 'unzip' step here and move the '.\install-service-elastic-agent.ps1' script to after the enroll command.

b) and in general I'd like to brainstorm on how we can de-emphasize the regular 'Linux' tab and usage, we should encourage them to .deb/.rpm usage if at all possible since it facilitates persistent Agent install and the .tar.gz usage does not.  Can we at least add some language there to this effect on the linux tab?  something like "We recommend to use the .deb or .rpm installation methods if at all possible to support persistent Agent execution' ?  not sure what else you think on this.

2) 
a) The enroll process page:
https://beats_20437.docs-preview.app.elstc.co/guide/en/ingest-management/master/run-elastic-agent.html

a) all enrollments need to be done as Administrator (sudo) level, but Windows is the only one that calls this out.  Can we add a sentence similar to or further enhanced as to what is in the product UI?  That line I wrote (to the best of my ability) is:
"Be sure to run the enrollment steps as a user with Administrator privilege on the system."

2) b) can we change this "to generate an enrollment token." 
to
"to see a current enrollment token."
... its not just a technical specificity here, there is a UI in place to actually create new enrollment tokens, so it may be confusing?  

2) c) under step 4 for Windows, this depends on what you decided in feedback item 1) above.  If you want to leave step 1 alone you could cite that this is optional to 'start Elastic Agent if, needed'.  It should already be running after the .ps1 script is run. This is in regards to the line:
'Start-Service elastic-agent'

2) d) for macOS start up, the Endpoint team was going to confirm some steps to configure it as a service manually, would you want to put those in here, maybe?  

3) on the stop Elastic Agent view, can we tweak this a bit:
"Then kill the process"
to
"Then kill the process with the relating PID from above"
and then also change the kill command to have < > around PID to indicate PID must be replaced with the value they got in the ps command?
kill -9 <PID>

4) we need to remove the citation of the --staging command, it is intended to be for internal use only.
 - I confirmed it is not displayed as part of the agent command line --help status, so that's good.

Happy to zoom to go over this so its more clear, if needed

**Comment by EricDavisX** [comment]
oh my, the numbering and lettering and indenting of my post above got interpreted badly, sorry!

**Comment by dedemorton** [comment]
@EricDavisX OK, I think I've addressed most of your concerns, except the CLI topic, which I plan to update next.

**Comment by dedemorton** [comment]
Approval was received via slack to merge this because it's required to get the overall ingest management PR building in elastic/observability-docs#80. We will iterate over all the content again during that review and follow up with another PR in the beats repo, if necessary.

**Pull request merged**
