### PR TITLE
Remove elastic agent kubernetes templates

### PR DESCRIPTION
**Pull request by narph**
## What does this PR do?

Remove elastic agent kubernetes templates
## Why is it important?

They are already inside the elastic agent repo

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

remove docs https://github.com/elastic/observability-docs/issues/1743

### CODE REVIEW

**Review by jlind23 — APPROVED** [review]
Looks good to me.

**Review by tetianakravchenko — COMMENTED** [review]
those files should be also removed https://github.com/elastic/beats/blob/main/deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, https://github.com/elastic/beats/blob/main/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml?

**Review by ChrsMark — COMMENTED** [review]
> those files should be also removed https://github.com/elastic/beats/blob/main/deploy/kubernetes/elastic-agent-managed-kubernetes.yaml, https://github.com/elastic/beats/blob/main/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml?

Yeap, I think that a `make all` will remove them, otherwise it needs to be done manually.

**Comment by tetianakravchenko** [comment]
@narph are you also going to fix documentation to use the new path to the manifests? 
https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-standalone.html, here is used
```
https://raw.githubusercontent.com/elastic/beats/8.1/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
```
the same here https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-managed-by-fleet.html

**Comment by narph** [comment]
> @narph are you also going to fix documentation to use the new path to the manifests? https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-standalone.html, here is used
> 
> ```
> https://raw.githubusercontent.com/elastic/beats/8.1/deploy/kubernetes/elastic-agent-standalone-kubernetes.yaml
> ```
> 
> the same here https://www.elastic.co/guide/en/fleet/current/running-on-kubernetes-managed-by-fleet.html

I have created an issue in the docs repo for that

**Review by tetianakravchenko — APPROVED** [review]

**Review by tetianakravchenko — APPROVED** [review]

**Pull request merged**
