### PR TITLE
Add test case to reproduce panic on Filebeat shutdown

### PR DESCRIPTION
**Pull request by andrewkroh**
When stopping Filebeat while it is reading logs it will panic. This PR contains a test case to reproduce the behavior.

If someone fixes the panic they can use this test case to validate their changes.

### CODE REVIEW

**Comment by andrewkroh** [comment]
I marked the test case as an expected failure.

**Comment by ruflin** [comment]
LGTM. Will merge when green. 


For reference, related to:
* https://github.com/elastic/beats/pull/964
* https://github.com/elastic/beats/pull/1402

**Comment by ruflin** [comment]
Jenkins reports this error: `....................................................../usr/lib/python2.7/unittest/case.py:342: RuntimeWarning: TestResult has no addExpectedFailure method, reporting as passes`. Is that expected?

Can you rebase on master to fix the "Jenkins build issues"?

**Comment by andrewkroh** [comment]
I replaced the expected failure annotation and with skip. I would have preferred to run the test case and have it fail, but the warning you posted and the fact that there was no indication that there was an "expected failure" caused me to changed it.

It's rebased too.

**Comment by andrewkroh** [comment]
Oops, I didn't intend to close this when I was cleaning up old branches. Reopening.

**Pull request closed without merging**
