### PR TITLE
[Manual backport][Heartbeat] Enable engine strict validation

### PR DESCRIPTION
**Pull request by emilioalvap**
## What does this PR do?

Manual backport of https://github.com/elastic/elastic-agent/pull/2225 and https://github.com/elastic/beats/pull/34470.
Enable engine strict validation when bundling synthetics.

## Why is it important?

https://discuss.elastic.co/t/synthetic-browser-tests-are-failing-in-version-7-x/324440/8

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

Change node installed version to `NODE_VERSION=13.1.0` and build heartbeat docker image locally. It should fail with:
```
#22 2.226 npm verb stack Error: Unsupported engine for @elastic/synthetics@1.0.0-beta.40: wanted: {"node":">14.14.0"} (current: {"node":"13.1.0","npm":"6.12.1"})
```

### CODE REVIEW

**Review by andrewvc — APPROVED** [review]
LGTM

**Comment by emilioalvap** [comment]
Test failures are unrelated, fix coming from https://github.com/elastic/beats/pull/34501.

**Pull request merged**
