### PR TITLE
[Metricbeat] Make integration tests more generic for modules

### PR DESCRIPTION
**Pull request by ruflin**
The goal is that each module on its own has less and less code and is more config based. The basic fetch testing we have for each module is moved into a general integration testing and it uses the configuration to figure out which services to start, ports to talk to etc.

This is still WIP and needs quite a bit of cleanup.

### CODE REVIEW

**Comment by ruflin** [comment]
I would like to get https://github.com/elastic/beats/pull/7957 first merged before moving forward with this as I think it will look even simpler with it (and otherwise conflicts with it).

**Comment by fearful-symmetry** [comment]
I _really_ like this idea.

**Comment by ruflin** [comment]
@jsoriano As discussed, assigning to you.

**Comment by ruflin** [comment]
@jsoriano It would be really nice to have this "unified" but as it went stale for quite some time I suggest I close it for now. Please reopen if you still plan to work on it.

**Comment by jsoriano** [comment]
This (or something similar) was implemented in https://github.com/elastic/beats/pull/11981.

**Pull request closed without merging**
