### PR TITLE
[Ingest Manager] Increase kibana client timeout to 5 minutes

### PR DESCRIPTION
**Pull request by michalpristas**
## What does this PR do?

Increased timeout as per https://github.com/elastic/beats/issues/21025

## Why is it important?

Fixes: https://github.com/elastic/beats/issues/21025

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by ruflin** [comment]
It seems this is related to the timeout set in Kibana. Should agent receive this as a config option from Fleet?

**Comment by nchaulet** [comment]
@michalpristas the related Kibana PR https://github.com/elastic/kibana/pull/76393

**Review by blakerouse — APPROVED** [review]
Code change looks good.

I do agree with @ruflin that we should have Fleet send this timeout information to Agent. That way if Fleet changes the Agent just changes with it. No need for use to keep updating number values.

We should file an issue to track that.

**Comment by nchaulet** [comment]
Yes having it in fleet will be nice, I created that issue https://github.com/elastic/kibana/issues/77106 
In the mean time merging that PR will unlock some failing tests.

**Pull request merged**
