### PR TITLE
Auditbeat: Fixes for system/socket dataset

### PR DESCRIPTION
**Pull request by adriansr**
## What does this PR do?

Fixes two problems with the system/socket dataset:

- A bug in the internal state of the socket dataset that lead to an infinite loop in systems were the kernel aggressively reuses sockets (observed in 2.6 / CentOS/RHEL 6.x).

- Socket expiration wasn't working as expected due to it using an uninitialized timestamp: Flows were expiring at every check.

Also fixes other two minor issues:
- A flow could be terminated twice by different code paths leading to wrong numFlows calculation and duplicated flows indexed.
- Decoupled the status debug log and socket cleanup into separate goroutines so that logging is still performed under high load situations.

## Why is it important?

It has been observed that the dataset would use 100% CPU and stop reporting events. During testing it was discovered that socket expiration, a new feature to prevent excessive memory usage, wasn't working as expected.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- ~~[ ] I have made corresponding changes to the documentation~~
- ~~[ ] I have made corresponding change to the default configuration files~~
- ~~[ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

The infinite loop is easy to trigger in RHEL 6.x by running:
> nmap -n -sT 127.0.0.1 -p 1-65535

### CODE REVIEW

**Comment by adriansr** [comment]
@andrewstucki while adding the test I found yet another problem.

It wasn't dealing with socket timeouts properly, see the new commit.

Can you have another look?

**Comment by adriansr** [comment]
yep, the whole state.go should be rewritten from scratch :D

**Comment by adriansr** [comment]
Fixes two problems with the system/socket dataset:

- A bug in the internal state of the socket dataset that lead to an infinite loop in systems were the kernel aggressively reuses sockets (observed in 2.6 / CentOS/RHEL 6.x).
- Socket expiration wasn't working as expected due to it using an uninitialized timestamp: Flows were expiring at every check.

Also fixes other two minor issues:

- A flow could be terminated twice by different code paths leading to wrong numFlows calculation and duplicated flows indexed.
- Decoupled the status debug log and socket cleanup into separate goroutines so that logging is still performed under high load situations.

**Comment by ssfxx** [comment]
@adriansr auditbeat version 7.17.0 (amd64), libbeat 7.17.0 system/socket Peak CPU Usage 100%+,mean value Cpu Usage 40%+.
Please help! 
Thanks!

**Pull request merged**
