### PR TITLE
Cherry-pick #10946 to 6.5: Ensure kubernetes caches don't expire if they are being read

### LINKED ISSUE #10658: Pod and container usage percentage is not properly calculated
It has been reported that in some cases pod and/or container uage percentages are not being correctly calculated. This seems related to the retrieval or calculation of container limits.

For example:
* https://discuss.elastic.co/t/kubernetes-module-not-getting-resource-limits/167210

There are also reports in which the percentages seem to be calculated during some periods with the container limits, and some periods with the node limits.

Related issues fixed in the past:
* https://github.com/elastic/beats/issues/9221
* https://github.com/elastic/beats/issues/10081

It is not clear how to reproduce these issues.

### PR DESCRIPTION
**Pull request by jsoriano**
Cherry-pick of PR #10946 to 6.5 branch. Original message: 

Some metrics in metricbeat kubernetes module are cached during a time,
if they are not updated they are removed. But it is usual to have pods or
containers that are not updated during more time that the expiration cache.
Current implementation was not renovating expiration times for cache
entries so all were eventually removed if updates for them are not received.
Replace it with the cache implementation available in libbeat, but keeping
the existing interface.

Also, use slashes instead of dashes to generate unique container uids.
Dashes can be used by kubernetes names, what could lead to ambiguous
keys for the caches.

Fix #10658

### CODE REVIEW

**Comment by sayden** [comment]
jenkins, test this please

**Comment by sayden** [comment]
@jsoriano it seems that there's some misconfiguration in Travis / Jenkins in this branch and that's why the tests are not being launched in CI

**Comment by jsoriano** [comment]
Issue in jenkins is not related, the misconfiguration in travis is https://github.com/elastic/beats/pull/11081

**Comment by sayden** [comment]
So I guess it's better to wait until it's merged and then rebase.

**Comment by jsoriano** [comment]
@sayden yes, let's wait, no hurries for this.

**Pull request merged**
