### PR TITLE
[7.15] Add integration links metricbeat docs (#28110)

### PR DESCRIPTION
**Pull request by dedemorton**
Backports #28110 to 7.15 branch.

(Required manual cherrypick to run make update before opening PR.)

### CODE REVIEW

**Comment by dedemorton** [comment]
@elasticmachine run elasticsearch-ci/docs

**Comment by dedemorton** [comment]
jenkins run the tests please

**Comment by dedemorton** [comment]
Doc build passes. There are no errors related to this docs-only PR, so I am merging it.

**Comment by v1v** [comment]
There are some linted errors in this PR for the metricbeats:

> metricbeat-lint - make -C metricbeat check;make -C metricbeat update;make -C x-pack/metricbeat che

https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-28136/runs/4/steps/1572/log/?start=0

> x-pack/metricbeat-lint - make -C x-pack/metricbeat check;make -C x-pack/metricbeat update;make -C

https://beats-ci.elastic.co//blue/rest/organizations/jenkins/pipelines/Beats/pipelines/beats/pipelines/PR-28136/runs/4/steps/1580/log/?start=0

**Comment by v1v** [comment]
I wonder if the comment https://github.com/elastic/beats/pull/28136#issuecomment-928241441 is too verbose or hard to understand.

Any suggestions to make this easier from your point of view?

**Pull request merged**
