### PR TITLE
Improve parsing of syslog messages without hostname

### PR DESCRIPTION
**Pull request by candlerb**
This is for review/discussion.

It is a partial fix for #13270, and for avoidance of merge issues sits on top of PR #13278.

It avoids the misparsing of FreeBSD messages from #13270, but does not yet parse process name and pid from FreeBSD messages.  Making the hostname part fully optional in ragel is not straightforward.

Replacing `timestamp space message` with `timestamp space msg` gives ambiguity problems  - specifically, an IPv6 address is simultaneously captured as hostname and program if the hostname is optional.

### CODE REVIEW

**Comment by candlerb** [comment]
I have made another commit which I believe fixes this, although it's a bit ugly.

Since ragel may be recognising a hostname pattern concurrently with recognising program/pid, both are set in the event.  So at the point where the hostname has been definitely matched, I reset the program/pid to empty (because they might not exist in the remainder of the message).

NOTE: this causes a behaviour change in one of the existing tests:

```
                        log:   []byte("<190>589265: Feb 8 18:55:31.306: %SEC-11-IPACCESSLOGP: list 177 denied udp 10.0.0.1(53640) -> 10.100.0.1(15600), 1 packet"),
                        syslog: event{
                                priority:   190,
-                               message:    "%SEC-11-IPACCESSLOGP: list 177 denied udp 10.0.0.1(53640) -> 10.100.0.1(15600), 1 packet",
+                               message:    "list 177 denied udp 10.0.0.1(53640) -> 10.100.0.1(15600), 1 packet",
                                hostname:   "",
-                               program:    "",
+                               program:    "%SEC-11-IPACCESSLOGP",
```

That is, the Cisco `%SEC` tag is now identified as program.  This is arguably better, because it is now consistent with an existing test which already does this:

```
                        log: []byte("<164>Oct 26 15:19:25 1.2.3.4 %ASA1-120: Deny udp src DRAC:10.1.2.3/43434 dst outside:192.168.0.1/53 by access-group \"acl_drac\" [0x0, 0x0]"),
                        syslog: event{
                                message:  "Deny udp src DRAC:10.1.2.3/43434 dst outside:192.168.0.1/53 by access-group \"acl_drac\" [0x0, 0x0]",
                                hostname: "1.2.3.4",
                                program:  "%ASA1-120",
                                priority: 164,
```

The difference is that this log line contains a hostname (1.2.3.4) whereas the previous log line was missing a hostname.  Making the hostname properly optional has allowed the tag/program to be recognised in both cases.

But on the other hand, this behaviour change may break the [ASA ES ingest pipeline](https://github.com/elastic/beats/blob/master/x-pack/filebeat/module/cisco/asa/ingest/pipeline.yml) - which I've not tested.

Anyway, I am happy to receive feedback on this change.  Depending on which approach you want to take, I can squash the commits as necessary to make the final solution.

**Comment by kvch** [comment]
jenkins test this

**Comment by candlerb** [comment]
I see that the Cisco ASA ingest pipeline was merged with FTD pipeline in 2a6c58f8 and now lives at [x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml](https://github.com/elastic/beats/blob/master/x-pack/filebeat/module/cisco/shared/ingest/asa-ftd-pipeline.yml)

That commit also says:

> As a side effect of this, it improves the existing ASA fileset so that it uses custom syslog message decoding instead of relying on Filebeat's syslog input, which has caused compatibility problems with some ASA devices.

I'm still not sure if that has any impact on this PR.

**Comment by ph** [comment]
@candlerb I think its a good work around with how ragel works here, I would like a input from @adriansr to make sure we don't break anything in the other pipeline.

**Comment by ph** [comment]
@adriansr is this change ok for you too?

**Comment by adriansr** [comment]
Looks good to me @ph. It won't have any impact to the Cisco pipelines as they are currently not using the syslog input, but after this and other syslog improvements currently in review hopefully it'll be able to use it again.

**Pull request closed without merging**
