### PR TITLE
Make the url field of heartbeat aggregatable.

### PR DESCRIPTION
**Pull request by perjahn**

### CODE REVIEW

**Comment by andrewkroh** [comment]
Some people may be relying on the fact that the URL is analyzed for their searching. I suggest we make this a multi-field so that there are `http.url` (text) and `http.url.keyword` (keyword) fields. Here's an example.

https://github.com/elastic/beats/blob/4cbb1dedfe59a6f8f2647c1d21a0340a243d6b81/auditbeat/_meta/fields.common.yml#L23-L31

**Comment by perjahn** [comment]
Sure. Try #2.

**Comment by perjahn** [comment]
Should be done. (there was some strange character on line 2391)

**Comment by ruflin** [comment]
@perjahn Can you run `make update` in the heartbeat directory to update the auto generated files?

**Comment by perjahn** [comment]
Sorry, having some problems with my environment.

**Comment by ruflin** [comment]
Let us know if we can help.

**Comment by kvch** [comment]
jenkins test it

**Comment by tsg** [comment]
@perjahn This is close to being merged, if you want, we can either send you a PR to your branch after running `make update`, or take over the commits in a new PR.

**Comment by perjahn** [comment]
Yes, please take over the commits.

**Comment by ruflin** [comment]
I took the PR over here: https://github.com/elastic/beats/pull/6479

@perjahn Thanks for your work on this one.

**Pull request closed without merging**
