### PR TITLE
Initial spec file for apm-server

### PR DESCRIPTION
**Pull request by jalvz**
## What does this PR do?

Adds a spec for running APM Server under Elastic Agent.

## Checklist

- [X] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Required for #https://github.com/elastic/apm-server/issues/4004

### CODE REVIEW

**Comment by jalvz** [comment]
@ruflin any comments? :)

**Review by ruflin — APPROVED** [review]
LGTM. It basically means, if the input is apm, run apm-server.

@ph Do we need to have the full list of outputs there?

**Comment by ph** [comment]
@ruflin Yes, I would keep it consistent with all the other beats-like processes.

**Comment by jalvz** [comment]
> Do we need to have the full list of outputs there?

You mean in the `when` clause?

I added all that apm-server supports...

**Comment by ruflin** [comment]
Yes, the `when` clause. If it is in line with other Beats, lets keep it.

**Comment by jalvz** [comment]
@ruflin @ph apm-server doesn't support Redis (isn't even documented), wouldn't that be confusing? 
I expect that if apm-server is instructed to use a Redis output; the process wouldn't even start, as it would misbehave.

**Comment by ruflin** [comment]
@jalvz Agree, it should not be there. My initial thinking was that we could even reduce it further to only support ES at first and open it later as in the case of Agent it is a new product and we can start small at first.

**Comment by ph** [comment]
I didn't know that APM-Server didn't support redis, We will need to improve our "When" logic and just move to conditions instead.

**Comment by ph** [comment]
Created this https://github.com/elastic/beats/issues/21417

**Comment by jalvz** [comment]
Thanks both!
I like the idea of starting small, updated!

**Pull request merged**
