### PR TITLE
Add queue.max_events to metrics

### PR DESCRIPTION
**Pull request by michalpristas**
We're missing `monitoring.metrics.libbeat.pipeline.queue`

image

This PR should add it so we can use that with alerting

### CODE REVIEW

**Comment by michalpristas** [comment]
sample event:

Non-zero metrics in the last 30s","component":
{"binary":"metricbeat","dataset":"elastic_agent.metricbeat","id":"beat/metrics-monitoring","type":"beat/metrics"},
"log":{"source":"beat/metrics-monitoring"},"monitoring":{"ecs.version":"1.6.0","metrics":{"beat":{"cpu":
{"system":{"ticks":2,"time":{"ms":2}},"total":{"ticks":6,"time":{"ms":6},"value":6},"user":{"ticks":4,"time":{"ms":4}}},
"info":{"ephemeral_id":"4933aa37-4be6-42ad-8257-a6f5c35c3c82","name":"metricbeat","uptime":{"ms":35310},"version":"8.12.0"},"memstats":{"gc_next":46256392,"memory_alloc":32140128,"memory_sys":54129928,"memory_total":47412288,"rss":103567360},"runtime":{"goroutines":46}},"libbeat":{"config":{"module":{"running":1,"starts":1}},"output":{"events":{"active":0},"type":"elasticsearch"},"pipeline":{"clients":2,"events":{"active":1,"published":1,"retry":3,"total":1},"queue":{**"max_events":3200**}}},"metricbeat":{"beat":{"state":{"events":1,"success":1}}},"system":{"cpu":{"cores":10},"load":{"1":6.7144,"15":6.2344,"5":5.9946,"norm":{"1":0.6714,"15":0.6234,"5":0.5995}}}}},"log.logger":"monitoring","log.origin":{"file.line":187,"file.name":"log/log.go"},"service.name":"metricbeat","ecs.version":"1.6.0"

**Review by miltonhultgren — APPROVED** [review]
This looks fine! 

Do note that you'll also need to introduce this mapping into the X-pack mode mappings found in Elasticsearch as well as the mappings for the Beats integration (which use the Metricbeat module under the hood).

**Comment by michalpristas** [comment]
hey @miltonhultgren could you link it? i could not find use of pipeline anywhere else

**Comment by cmacknz** [comment]
It should probably be mapped in the Elastic Agent integration's Beat metrics data streams as well, example https://github.com/elastic/integrations/tree/main/packages/elastic_agent/data_stream/filebeat_metrics

**Comment by miltonhultgren** [comment]
@michalpristas https://github.com/elastic/elasticsearch/blob/main/x-pack/plugin/core/template-resources/src/main/resources/monitoring-beats-mb.json#L839-L841 is the mapping in Elasticsearch.

It seems the [Beat integration](https://github.com/elastic/integrations/tree/main/packages/beat) no longer has these data streams (but that is different from the internal Elastic Agent integration)

**Pull request merged**
