### PR TITLE
json.add_error_key false value is honored

### LINKED ISSUE #11298: json. add_error_key: false not honored
- Version: `master` / `8.0.0`
- Operating System: Mac OS X
- Discuss Forum URL: https://discuss.elastic.co/t/error-key-populated-even-when-explicitly-disabled/172602
- Steps to Reproduce: 
  1. Setup `filebeat.yml` like so:
     ```yaml
     filebeat.inputs:
     - type: stdin

       enabled: true
       json.add_error_key: false
       json.overwrite_keys: true
       json.keys_under_root: true

     output.console:
       enabled: true
     ```
   2. Run Filebeat:
      ```sh
      ./filebeat -e
      ```
   3. Give it the following input on STDIN:
      ```
      { "type": 12345 }
      ```
   
Filebeat expectedly fails with this error:
```
ERROR   jsontransform/jsonhelper.go:76  JSON: Won't overwrite type because value is not string
```

However, in the event that is generated (see example below), the `error` field is set to an object, despite `json.add_error_key` being set to `false` in the configuration.

```
{"@timestamp":"2019-03-18T21:03:42.045Z","@metadata":{"beat":"filebeat","type":"_doc","version":"8.0.0"},"log":{"offset":0,"file":{"path":""}},"error":{"message":"type not overwritten (not string)","type":"json"},"input":{"type":"stdin"},"agent":{"type":"filebeat","ephemeral_id":"7e40fe2c-8d09-430e-b661-aa9773ae6c87","hostname":"Shaunaks-MBP-2","id":"51a8bb52-16b0-4129-a33b-9fba504fe6e8","version":"8.0.0"},"ecs":{"version":"1.0.0-beta2"},"host":{"name":"Shaunaks-MBP-2"}}
```

### PR DESCRIPTION
**Pull request by olimpias**
add_error_key false value becomes sensible in jsonhelper.go

fixes #11298

### CODE REVIEW

**Comment by kvch** [comment]
jenkins test this

**Comment by olimpias** [comment]
I think `add_error_key` s default value should be true, because before this task people were able to see event errors without setting this option. For backward compatibility, I think we should set as true. What do you think @kvch ?

**Comment by kvch** [comment]
@olimpias Agreed in case of `json.*` settings. But as it is a new option in `decode_json_fields`, I would turn it off by default, so no unexpected keys and values show up if someone uses the processor.

**Comment by kvch** [comment]
jenkins test this

**Comment by kvch** [comment]
jenkins test this

**Comment by kvch** [comment]
Thank you!

**Pull request merged**
