### PR TITLE
clarifies use of beat.name

### PR DESCRIPTION
**Pull request by hilt86**
I wasted a few hours trying to set beat.name in the configuration file, all the time it being "name" under shipper.

### CODE REVIEW

**Comment by ruflin** [comment]
@hilt86 Thanks for adding this to the docs. Could you sign the CLA?

@dedemorton As this changes in 5.0 and is potentially also not that obvious, it is perhaps worth to also document it?

**Comment by hilt86** [comment]
I've signed it. Btw can you explain how this behaviour changes in 5.0? I'm writing an Ansible role for filebeat and would like to know how these changes will affect me please..

**Comment by ruflin** [comment]
@hilt86 `shipper.name` will be replaced by just `name`. See: https://github.com/elastic/beats/blob/master/libbeat/_meta/config.yml#L6

**Comment by hilt86** [comment]
@ruflin thank you! So "name:" be a root attribute rather than under "shipper:" - is that correct?

**Comment by ruflin** [comment]
Exactly. That applies for the config. For the event it will still be under `beat.name`.

**Comment by monicasarbu** [comment]
@hilt86 The asciidoc file is generated from the `fields.yml` file, so it's better to do the change in the `./libbeat/_meta/fields.yml`, and then run `make update` to generate the asciidoc. If you like, we can also take it from here, and update the `fields.yml` in a separate PR based on your input.
cc-ed @dedemorton

**Comment by hilt86** [comment]
Yeah that might be easier if you take it from here so I don't have to clone
the repo and get make working on my workstation.

H

**Comment by dedemorton** [comment]
This PR is replaced by #2398

**Pull request closed without merging**
