### PR TITLE
Changed MySQL active connections viz title to MySQL total connections

### LINKED ISSUE #4812: Mysql connections count off by millions
All other metrics are correct but for some reason, active mysql connections is huge:
image

We currently (according to the AWS RDS panel) have 5 connections open.

**Version**
MySQL 5.6.34 (AWS) -> metricbeat 5.4.1 -> logstash 5.4.2

**Config**
```
metricbeat.modules:
- module: system
  metricsets:
    - cpu
    - filesystem
    - memory
    - network
    - process
  enabled: true
  period: 30s
  processes: ['.*']
  cpu_ticks: false

- module: docker
  metricsets: ["container", "cpu", "diskio", "healthcheck", "info", "memory", "network"]
  hosts: ["unix:///var/run/docker.sock"]
  enabled: true
  period: 30s

- module: mysql
  metricsets: ["status"]
  enabled: true
  period: 30s
  hosts: ["${MYSQL_USER}:${MYSQL_PASS}@tcp(${MYSQL_HOST}:${MYSQL_PORT})/"]

output.logstash:
  hosts: ["127.0.0.1:3005"]

#output.console.pretty: true
```

Let me know if there is anything else you need!

Cheers

### PR DESCRIPTION
**Pull request by danleerunk**
Should resolve #4812

### CODE REVIEW

**Comment by ruflin** [comment]
jenkins, test it

**Comment by danleerunk** [comment]
It looks like the build failed while trying to assemble Kafka for testing - I don't think my changes would've impacted that, it sounds like the maybe the actual testing automation failed?

https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/1784/beat=metricbeat,label=ubuntu/testReport/junit/test_kafka/Test/test_partition/

```kafka.conn: DEBUG: <BrokerConnection node_id=bootstrap host=kafka/kafka port=9092>: creating new socket
kafka.conn: DEBUG: <BrokerConnection node_id=bootstrap host=kafka/172.18.0.4 port=9092>: setting socket option (6, 1, 1)
kafka.conn: INFO: <BrokerConnection node_id=bootstrap host=kafka/172.18.0.4 port=9092>: connecting to 172.18.0.4:9092
kafka.conn: ERROR: Connect attempt to <BrokerConnection node_id=bootstrap host=kafka/172.18.0.4 port=9092> returned error 111. Disconnecting.
kafka.conn: INFO: <BrokerConnection node_id=bootstrap host=kafka/172.18.0.4 port=9092>: Closing connection. ConnectionError: 111
kafka.conn: DEBUG: <BrokerConnection node_id=bootstrap host=kafka/172.18.0.4 port=9092>: reconnect backoff 0.0485859219137 after 1 failures
kafka.client: ERROR: Unable to bootstrap from [('kafka', 9092, 0)]```

**Comment by exekias** [comment]
You can ignore that errors, seems a temporal issue from our CI, could you please add a CHANGELOG.asciidoc entry?

**Comment by danleerunk** [comment]
hey @exekias - I think I updated the changelog properly, but if you could verify I put my entry in the right place I would be grateful!

**Pull request merged**
