### PR TITLE
Dynamical ingest pipeline selection in ES output

### PR DESCRIPTION
**Pull request by urso**
- Add dynamic ingest pipeline selection based on outil.Select
- Add api ingest node integration test
- Update logstash integration tests
- Add output plugin -> ingest node integration tests
- Add default setting to full config

### CODE REVIEW

**Comment by tsg** [comment]
Needs a rebase, I think. Otherwise, LGTM.

**Comment by urso** [comment]
blocked by #2118

**Comment by tsg** [comment]
Also needs docs & changelog. I'm OK to adding that to the meta ticket.

**Comment by urso** [comment]
Blocked by #2119

**Comment by urso** [comment]
The docs will be updated in another PR. Docs depend on #2132
I wonder what to do with config.full.yml in libbeat.

**Pull request merged**
