### PR TITLE
Added serialbeat to the community beats list

### PR DESCRIPTION
**Pull request by benben**

### CODE REVIEW

**Comment by kvch** [comment]
Thank you for your contribution.

**Comment by ruflin** [comment]
@benben Great to see a beat for ingesting data from serial devices. Can you share a bit on what kind of data you used it on so far (just curious :-) ).

**Comment by benben** [comment]
@ruflin I am reading data from a couple of home sensors over 868MHz, namely inside/outside temperature and power consumption of my house from the smart meter.

**Comment by ruflin** [comment]
@benben One thought I had is if this should be available as module in metricbeat as in the end it sounds a lot like metrics. The challenge here would be around how to structure the data you received. Can you share some example of the data you get out?

**Comment by benben** [comment]
My data looks like `K0110009211` or ` SBA6546011E00CDEF520BD6000000277520` which is very specific to the firmware I use to receive the data (slowRF/CUL/FHEM).

**Comment by ph** [comment]
@benben Pretty cool! I will certainly have a go!

**Comment by benben** [comment]
thank you @ph, happy to get feedback.

**Comment by ruflin** [comment]
@benben I see, nothing easy to parse in a generic way.

**Pull request merged**
