### PR TITLE
Added initial support for substring JSON matching of objects and arrays

### PR DESCRIPTION
**Pull request by rickardp**
As reported in issue #12802, it is very useful to parse JSON objects found inside existing strings.

A typical use case for this is that many log frameworks have a shortcut syntax for dumping structured objects as JSON to the log (for example, SeriLog and .NET core has this).

By allowing a "substring" mode, the first JSON object or array will be used if possible.

Limitations:
* Only understands one object
* If there is a rogue '{' before the first object, the rest of the string cannot be parsed

I tried to document intended behavior in the unit tests.

### CODE REVIEW

**Comment by rickardp** [comment]
Test failure seems to be related to #8102 and not to this PR.

**Comment by kvch** [comment]
jenkins test this

**Comment by blakerouse** [comment]
@rickardp Seems this has a conflict, core you rebase on latest master. I also set the Discuss labels so we can have a team discuss on if we want to enable this feature.

I would also expect some what of different behavior then what this PR is currently doing. To me it would make more sense if the log was:

`Log message with {"level": "debug"}`

It would turn into this:

```
{
  "message": "Log message with ",
  "original": "Log message with {"level": "debug"}"
  "level": "debug"
}
```

And if it contained a message field inside of the nested JSON that could replace the message:

`Log message with {"level": "debug", "message": "inside message"}`

It would turn into this:

```
{
  "message": "inside message",
  "original": "Log message with {\"level\": \"debug\", \"message\": \"inside message\"}"
  "level": "debug"
}
```

**Comment by rickardp** [comment]
Thank you! We have been using this in production since the PR was filed, so it would definitely be helpful not to rely on a fork for this

**Pull request closed without merging**
