### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by posquit0**
## What does this PR do?

Fix typo in the docs of Heartbeat

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by andrewvc** [comment]
Thanks for the PR! 

Jenkins, test this please

**Comment by andrewvc** [comment]
jenkins, please test this

**Comment by kaiyan-sheng** [comment]
jenkins run the tests

**Comment by posquit0** [comment]
jenkins please test

**Comment by posquit0** [comment]
jenkins run the tests

**Review by dedemorton — APPROVED** [review]
LGTM.

Please accept my apologies for the delayed review. I will make sure this gets backported to the appropriate versions.

**Pull request merged**
