### PR TITLE
Packetbeat ipv6

### PR DESCRIPTION
**Pull request by raboof**
As discussed in #1995 . The CLA is not yet signed, but expect that Real Soon Now, so code review welcome :)

### CODE REVIEW

**Comment by raboof** [comment]
selection_106

**Comment by tsg** [comment]
@raboof LGTM, great contribution! While we wait for the CLA, can you also add a line in the `CHANGELOG.asciidoc`, please?

**Comment by raboof** [comment]
@karmi the Corporate CLA was 'Signed and Filed' (by Mark Bakker) this morning, are there any further steps I need to take? Do we need to do anything to make the bot aware of this?

**Comment by ruflin** [comment]
@raboof The script can't verify corporate CLA's automatically. I did the manual check and all looks good.

**Comment by tsg** [comment]
jenkins, test it

**Comment by tsg** [comment]
> I added it under 'Breaking changes' as it might break consumers that assume
IP's to be in IPv4 format.

I'm not sure I understand this, on my testing it's still using the IPV4 dotted format for IPs.

Also, the PR add support for matching processes when using IPv6, but the Changelog entry makes it sound like we added support for decoding IPv6 (which we already support).

**Comment by raboof** [comment]
@tsg you're right - I've updated the changelog, does that clarify things?

**Comment by tsg** [comment]
@raboof Wonderful! Thanks a lot for the contribution.

**Comment by raboof** [comment]
:+1: thanks for the great framework & for taking our contribution :)

**Pull request merged**
