### PR TITLE
Beats preference pane for macOS

### PR DESCRIPTION
**Pull request by adriansr**
This preference pane shows up in System Preferences and allows to manage installed beats.

Only works with Beats installed with packages from #6344 

screen shot 2018-04-23 at 18 50 28
screen shot 2018-04-23 at 18 50 47

### CODE REVIEW

**Comment by adriansr** [comment]
Part of #6053

**Comment by adriansr** [comment]
pinging @mattapperson for a review

From your original (pre-PR) review, you suggested a couple of changes:
1. Yaml syntax highlighting and validation using https://github.com/raspu/Highlightr
2. replace deprecated AuthorizationExecuteWithPrivileges with a privileged helper tool (SMJobBless)
3. get rid of globals (this was addressed before submitting this PR)

However, after discussing it in our security area meeting it was decided to have an initial version asap and leave 1 and 2 for future improvements.

WDYT?

**Comment by mattapperson** [comment]
@adriansr I would say I am fine with that, though WWDC might force a quick turn around on 2 in a few days :)

**Comment by andrewkroh** [comment]
screen shot 2018-05-31 at 12 50 31 am

**Pull request merged**
