### PR TITLE
Add Azure VM support for add_cloud_metadata processor

### LINKED ISSUE #3784: Support Azure in add_cloud_metadata Processor
I had a request at ElasticON for support Azure in the [add_cloud_metadata](https://www.elastic.co/guide/en/beats/metricbeat/current/add-cloud-metadata.html) processor. I'm not finding much documentation via Google (maybe I should be trying Live). I'll see about getting an Azure account to spin up and instance and see what's available from http://169.254.169.254/metadata/v1/maintenance.

References:
- https://azure.microsoft.com/en-us/blog/what-just-happened-to-my-vm-in-vm-metadata-service/
- https://azure.microsoft.com/en-us/blog/accessing-and-using-azure-vm-unique-id/

### PR DESCRIPTION
**Pull request by saada**
Closes #3784.
Tests pass locally.
Follows the guidelines here: https://docs.microsoft.com/en-us/azure/virtual-machines/linux/instance-metadata-service

### CODE REVIEW

**Comment by ruflin** [comment]
Thanks a lot for this contribution. Could you adda  CHANGELOG entry?

**Comment by ruflin** [comment]
jenkins, test it

**Comment by saada** [comment]
Thanks @ruflin, where do I add the change log? Under rc1 notes?

**Comment by ruflin** [comment]
@saada Best add it after `- Add support for enabling TLS renegotiation. {issue}4386[4386]`.

**Comment by saada** [comment]
@ruflin I don't see that entry in the [changelog](https://github.com/elastic/beats/blob/master/CHANGELOG.asciidoc).

**Comment by andrewkroh** [comment]
@saada Have a look at the [raw view](https://raw.githubusercontent.com/elastic/beats/master/CHANGELOG.asciidoc) of the CHANGELOG file.

**Comment by saada** [comment]
🎉  Done!

**Comment by andrewkroh** [comment]
I just thought of one more thing we need with this change. Can you update the add_cloud_metadata [docs](https://github.com/elastic/beats/blob/0b104ff0f0fb82e0870fd50e78b07fe3c3d7193a/libbeat/docs/processors-using.asciidoc#add-cloud-metadata) to include Azure.

**Comment by saada** [comment]
@andrewkroh 👍

**Comment by ruflin** [comment]
jenkins, test it

**Pull request merged**
