### PR TITLE
Docs - Fix small typo "promtheus" -> "prometheus"

### PR DESCRIPTION
**Pull request by stephane-deraco**
## What does this PR do?

This PR fixes a small typo on the word "Prometheus".

## Why is it important?

Correctness of documentation

## Checklist

- [ ]  ~~My code follows the style guidelines of this project~~
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [x] I have made corresponding changes to the documentation
- [ ] ~~I have made corresponding change to the default configuration files~~
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [ ] ~~I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

### CODE REVIEW

**Comment by stephane-deraco** [comment]
Yes, it is still relevant 👍

**Comment by kaiyan-sheng** [comment]
Hello @stephane-deraco could you make this change in the master branch please? Then we can backport it to 7.13.

**Comment by stephane-deraco** [comment]
Thanks @kaiyan-sheng for your feedback, I have changed the PR branches to target the master branch.

**Comment by kaiyan-sheng** [comment]
@stephane-deraco Thank you!

**Review by kaiyan-sheng — APPROVED** [review]

**Pull request merged**
