### PR TITLE
x-pack/filebeat/input/httpjson: Fix parseDate location offset

### PR DESCRIPTION
**Pull request by chemamartinez**
## Proposed commit message

We encountered an issue from an SDH due to how the `time.Parse` function in Go handles timezone abbreviations. It interprets them based on the server's local time zone, which can lead to incorrect conversions if the server's local time zone doesn't match the time zone abbreviation in the string.

Since this is a limitation of the `time.Parse` function, we decided to add a new helper `dateParseInTZ` where users can apply the proper timezone when parsing dates. It accepts numeric offsets and IANA time zone names.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Review by efd6 — COMMENTED** [review]
I'm not convinced that this is the right solution. If we cannot parse the timezone because it is incorrectly using a non-IANA tzdb label or absolute fixed timezone, it should be set in the UI config.

**Comment by chemamartinez** [comment]
> I'm not convinced that this is the right solution. If we cannot parse the timezone because it is incorrectly using a non-IANA tzdb label or absolute fixed timezone, it should be set in the UI config.

@efd6 thanks for taking a look!

Since this is fixing a value template, that parses dates that can come from anywhere at any timezone, how would we set the timezone in the UI config? Do you mean forcing users that use this value template to define what's the timezone of the incoming dates?

On the other hand, do you see any particular issue that makes this change undesirable? I agree this may not be the optimal solution, even the Go developers seem to have been debating the issue for quite some time:
https://github.com/golang/go/issues/56528
https://github.com/golang/go/issues/63345
For now, if no native solution is provided, the [`time.Parse`](https://pkg.go.dev/time#Parse) docs suggests using `ParseInLocation` when facing this kind of issues, and it works at least for the most common cases.

 Please let me know your thoughts about this. Thanks!

**Comment by efd6** [comment]
The commentary in go.dev/issue/63345 goes over the issues with this very nicely and explains exactly why this is undesirable. The caveat in the final paragraph of `time.Parse` is also informative about why this is a dangerous action to take (briefly, if the agent is running in a location that does not know the abbreviation, the tzoffset will be zeroed, or worse if it is in another location where the abbreviation means something else it will be definitively incorrect).

In practice any particular instance of HTTPJSON would likely only be collecting data from a single tz, so if this is not parseable, a single configuration location would be enough to specify that time be handled in that singular location. Maybe it would be helpful to have a `parseTimeInLocation` template helper.

If this change here is added, it needs documentation making the sharp edges clear and suggesting that users configure time-offset timezone specs if possible.

**Comment by chemamartinez** [comment]
> In practice any particular instance of HTTPJSON would likely only be collecting data from a single tz, so if this is not parseable, a single configuration location would be enough to specify that time be handled in that singular location. Maybe it would be helpful to have a `parseTimeInLocation` template helper.
> 
> If this change here is added, it needs documentation making the sharp edges clear and suggesting that users configure time-offset timezone specs if possible.

@efd6 I added a new value template `parseDateInTZ` and updated the docs intending to clarify edge cases and this timezone issue. Regarding the implementation of `parseDateInTZ`, I had two different approaches depending on what we would prefer:

1. Using `time.ParseInLocation` gives preference to the implicit timezone in the provided date over the specified timezone.
2. Using `time.Parse` after a manual assignment of the location. That way we prioritize the given one.

I chose the last option, let me know if you have second thoughts on this.

**Comment by efd6** [comment]
> I chose the last option

I agree.

**Review by efd6 — APPROVED** [review]

**Pull request merged**
