### PR TITLE
Modified auditd ingest pipeline to handle the case where name_format …

### PR DESCRIPTION
**Pull request by ipnerds**
…(man 5 auditd.conf) is a value other than none.

## Type of change

- Bug

## What does this PR do?

This change permits auditd logs to be ingested whether or not they begin with a node=.  Previous to this change a type= was expected.
 
## Why is it important?

When running auditd with name_format other than none, the log messages will begin with node= parameter rather than type=.  This behavior caused such audit logs to fail ingestion.   The use case for setting name_format would be with an audit server collecting audit logs from multiple hosts.

## Checklist

- [ X] My code follows the style guidelines of this project
- ~~[ ] I have commented my code, particularly in hard-to-understand areas~~
-~~ [ ] I have made corresponding changes to the documentation~~
-~~ [ ] I have made corresponding change to the default configuration files~~
-~~ [ ] I have added tests that prove my fix is effective or that my feature works~~
-~~ [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

### CODE REVIEW

**Comment by ipnerds** [comment]
Andrew,
I have pushed a sample log file, please let me know how else to assist.
Thanks.
Kenny

**Comment by marc-gr** [comment]
Thanks for the test samples @ipnerds ! I generated the test files and waiting for CI now.

**Comment by marc-gr** [comment]
jenkins run tests

**Comment by marc-gr** [comment]
jenkins run tests

**Pull request merged**
