### PR TITLE
[Filebeat][awss3] Correcting input metrics initialization loophole

### PR DESCRIPTION
**Pull request by kgeller**
## What does this PR do?

Ensures that we only create input metrics associated with the context of the input. We had a loophole that the tests utilized, so this PR removes the loophole and updates the tests. 

## Why is it important?

If the Input Context doesn't exist, the input metrics for S3 should not allow an empty ID.

## Checklist

- [X] My code follows the style guidelines of this project
- [ ] ~I have commented my code, particularly in hard-to-understand areas~
- [ ] ~I have made corresponding changes to the documentation~
- [ ] ~I have made corresponding change to the default configuration files~
- [X] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

Closes https://github.com/elastic/beats/issues/35354

### CODE REVIEW

**Review by P1llus — APPROVED** [review]

**Comment by P1llus** [comment]
LGTM, just was unsure about the removal of the  MaxNumberOfMessages from input.go factory functions, as long as that is intended then its fine by me :+1

**Comment by kgeller** [comment]
> LGTM, just was unsure about the removal of the MaxNumberOfMessages from input.go factory functions, as long as that is intended then its fine by me :+1

It is intended as it was a part of the cleanup 😄

**Comment by andrewkroh** [comment]
I will take a look a today.

**Review by andrewkroh — CHANGES_REQUESTED** [review]
I would like to block this until we can resolve the questions I posed at https://github.com/elastic/beats/issues/35354#issuecomment-1542672665. I don't think this is the way to resolve issues related to an empty ID.

**Pull request closed without merging**
