### PR TITLE
Improve explanation of dsl names in config docs

### PR DESCRIPTION
**Pull request by fearful-symmetry**
## Proposed commit message

closes https://github.com/elastic/beats/issues/36733

This expands the config documentation for DSL, elaborating on the template variables used by the `data_stream_pattern` config value.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by fearful-symmetry** [comment]
heartbeat CI error seems unrelated...

**Review by cmacknz — APPROVED** [review]

**Review by vigneshshanmugam — APPROVED** [review]
HB changes LGTM

**Review by belimawr — APPROVED** [review]

**Review by bhapas — APPROVED** [review]
LGTM

**Comment by fearful-symmetry** [comment]
@Mergifyio backport 8.11

**Pull request merged**
