### PR TITLE
[Docs] Fixes fields documentation for php_fpm metricbeat module

### PR DESCRIPTION
**Pull request by dpavlos**
## What does this PR do?
Corrects the documentation for `process.last_request_cpu` and `process.last_request_memory` fields from `php_fpm` metricbeat module according to the official [docs](https://github.com/php/php-src/blob/master/sapi/fpm/www.conf.in#L205-L212).

## Why is it important?

Wrong documentation.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- I have also noticed that the `php_fpm.process.last_request_cpu` field type is set to `long` although it refers to a percentage. IMHO this should change to `half_float` but I left it as is in order to avoid introducing any breaking changes. If you think this is something that also needs to be corrected, please let me know and I will open a new PR.

### CODE REVIEW

**Comment by EamonnTP** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Comment by jsoriano** [comment]
jenkins run the tests please

**Review by jsoriano — APPROVED** [review]
LGTM, thanks for these fixes! Let's wait for Jenkinks to finish at least the linting jobs.

**Comment by EamonnTP** [comment]
Thanks @dpavlos for these updates! I can merge this PR for you and backport it to the specific branches.

**Comment by dpavlos** [comment]
Thanks @EamonnTP @jsoriano for reviewing this.

**Pull request merged**
