### PR TITLE
Use `mapstr.M` instead of `common.MapStr`

### PR DESCRIPTION
**Pull request by kvch**
## What does this PR do?

This PR adopts `mapstr.M` and gets rid of `common.MapStr` from libbeat.

## Why is it important?

We are removing common parts from libbeat in favour of [elastic-agent-libs](https://github.com/elastic/elastic-agent-libs).

## Checklist

- [x] My code follows the style guidelines of this project
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by rdner** [comment]
There are some failures on the CI (not linting-related).

Screenshot 2022-04-26 at 17 51 16

**Comment by rdner** [comment]
It's not over yet :)

Screenshot 2022-04-27 at 09 16 19

**Comment by kvch** [comment]
To decrease the amount of changes, the documentation fixes will come in a new PR.

**Review by rdner — APPROVED** [review]

**Pull request merged**
