### PR TITLE
Move file rotator out of logp package

### PR DESCRIPTION
**Pull request by andrewkroh**
This moves the file rotator utility to the libbeat/common/file package. This utility is used by more things than the just the logger.

### CODE REVIEW

**Comment by andrewkroh** [comment]
Rebased.

**Comment by ph** [comment]
jenkins test this please

**Comment by andrewkroh** [comment]
Yay. Green on Jenkins.

**Comment by ph** [comment]
@andrewkroh Yeah there was weird error with one of the jenkins node.

**Pull request merged**
