### PR TITLE
Update apm-server spec

### PR DESCRIPTION
**Pull request by jalvz**
## What does this PR do?

Copy fleet to inputs to make Kibana host available to apm-server

## Why is it important?

See above 

## Related issues

https://github.com/elastic/apm-server/pull/4670

### CODE REVIEW

**Comment by blakerouse** [comment]
I don't really like this. Could APM-Server understand the top-level fleet configuration key instead? That is how Fleet Server and Endpoint work. Both read from the top-level fleet configuration key instead of it being nested inside of the input.

@ruflin ^ would like to get your opinion on this

**Comment by jalvz** [comment]
That would mean we need to register 2 reloaders, one to receive apm-server configuration, and another one to receive fleet (kibana) configuration. It would be more unnecessary complications  on our side.
I can remove the `access_api_key` if that is the problem.

**Comment by ruflin** [comment]
With the introduction of fleet-server, Elastic Agent will loose the knowledge of connecting to Kibana. So this seems a very temporary fix. I would rather see for now that we find a way to add the Kibana part to the apm input block instead and Elastic Agent does not have to know about it.

**Comment by jalvz** [comment]
I am fine with a temporary workaround now and look for better long term solution.
With that in mind and given the 7.12 timeline, I think we should go with this for the time being. Unless of course you think that something can be implemented in Kibana very quickly to enrich the apm input. WDYT?

**Comment by blakerouse** [comment]
@ruflin The `fleet` configuration will not go away even with the change away from Kibana. Unless the running processes always come to Agent for the data they need. If they are going to connect directly to the Fleet Server then that information will still need to be presented to the application.

Placing it into the input is not a problem, it just doesn't match what we are doing with the other projects.

**Comment by jalvz** [comment]
We still can align with other projects going forward. For now it is problematic because we restart the HTTP server every time something changes, and there is a certain amount of synchronization needed. With 2 different reloaders that can be called independently, it gets more complex very quickly. 
Once we get around reloading settings on the fly without needing a server restart, we should not need this.

**Comment by jalvz** [comment]
@ruflin @blakerouse is it good enough to go with this for now, and follow up when we have a better implementation in apm-server?

**Comment by blakerouse** [comment]
@jalvz I think it is okay to go with this for now.

There are a few extra keys and information in the `fleet`. You should filter to only send the things you need from Fleet. Like #2386 adds a `fleet.server`, which should not be sent to APM. So lets ensure you only send exactly what you need and nothing more.

**Comment by jalvz** [comment]
@blakerouse can you approve this if there are no more comments?

**Review by blakerouse — APPROVED** [review]
Looks good.

**Pull request merged**
