### PR TITLE
[Metricbeat] Migrate NGINX stubstatus to use ReporterV2 interface

### PR DESCRIPTION
**Pull request by berfinsari**
Refer to #10774 for more info

### CODE REVIEW

**Comment by sayden** [comment]
jenkins, test this

Thank you for contributing with this @berfinsari !

**Comment by ruflin** [comment]
jenkins, test this

**Comment by sayden** [comment]
Sorry, I mean to update the permissions file. System tests for this module will be a bit more laborious and I it's better that it goes in a new PR

**Comment by berfinsari** [comment]
Thanks for the review! I may have overlooked this issue. I updated the permissions file. Is there anything else I need to do?

**Comment by ruflin** [comment]
jenkins, test this

**Comment by kaiyan-sheng** [comment]
jenkins, test this please

**Comment by ruflin** [comment]
jenkins, test this

**Pull request merged**
