### PR TITLE
kubernetes processor use correct os path separator

### PR DESCRIPTION
**Pull request by zentron**
When appending a trailing slash to the log path directory, it needs to use the correct PathSeperator for the given OS.
closes https://github.com/elastic/beats/issues/9196

### CODE REVIEW

**Comment by jsoriano** [comment]
jenkins, test this

**Comment by jsoriano** [comment]
jenkins, test this again

**Comment by eloyekunle** [comment]
@zentron Anyluck with the changelog entry?

**Comment by ruflin** [comment]
@exekias should we take this over?

**Comment by zentron** [comment]
Sorry, i have been sidelined with other work and  we have since moved to linux containers so this change is not such a high priority.

**Comment by exekias** [comment]
Thank you @zentron for opening this! I have created a copy with the needed changes to merge it: #11760, closing this in favor of that one

**Pull request closed without merging**
