### PR TITLE
use event.timezone if defined in haproxy ingest pipeline

### PR DESCRIPTION
**Pull request by TeTeHacko**
Hi,
haproxy ingest pipeline does not use event.timezone, this commit fix it.

Signed-off-by: TeTeHacko <tth@rfa.cz>

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
Could you sign the CLA please? Also a changelog entry would be helpful 👍 Thanks!

**Comment by TeTeHacko** [comment]
CLA signed (its pain to find browser with enabled javascript for this shit ...)
error handling added
huh edit changelog? how? where? its necesary?

**Comment by kaiyan-sheng** [comment]
Hmm it still shows CLA needed on this PR. Sorry for the inconvenience! 
For changelog, yes it is necessary and easy to add. Just add an entry for your PR under filebeat session here: https://github.com/elastic/beats/blame/master/CHANGELOG.next.asciidoc#L354

**Comment by kaiyan-sheng** [comment]
jenkins, test this please

**Comment by jsoriano** [comment]
We should also add the `add_locale` processor to the fileset config (in `filebeat/module/haproxy/log/config/file.yml` and `filebeat/module/haproxy/log/config/syslog.yml`), like this:
```
processors:
- add_locale: ~
```

And then we will probably need to regenerate test files.

And we should also include the configuration notes to the documentation:
```
include::../include/timezone-support.asciidoc[]
```

**Comment by TeTeHacko** [comment]
@jsoriano: thanks for the hint, i have it at global level in my config
@kaiyan-sheng: thanks for your help ;)

**Comment by jsoriano** [comment]
Thanks @TeTeHacko!

Now the [CI is complaining](https://travis-ci.org/elastic/beats/jobs/617128217#L701) because of the format of some file. As the message mentions, run `mage fmt update` from the `filebeat` directory to fix them.

Once this is fixed tests will run, and I think that the ones for the haproxy module will fail, because the timestamps expected will change. If this happens you will need to regenerate the expected files and commit them.

You can run all integration tests with generation enabled (slow but easy):
```
GENERATE=1 mage pythonIntegTest
```

Or you can just run the haproxy tests. For that, follow these instructions:

Start a stack, Elasticsearch is needed for these tests:
```
cd testing/environments
make start
```
Run the test, with generation of files enabled:
```
cd filebeat
make python-env
go test -c
source ./build/python-env/activate
GENERATE=1 INTEGRATION_TESTS=1 BEAT_STRICT_PERMS=false TESTING_FILEBEAT_MODULES=haproxy nosetests tests/system/test_modules.py
```

`make stop` from `testing/environments` can be used to stop the stack previously started when you don't need it anymore.

**Comment by TeTeHacko** [comment]
```
make python-env
    ERROR: Command errored out with exit status 1:
     command: /home/xhercet/beats/filebeat/build/python-env/bin/python -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-5pj8j993/functools32/setup.py'"'"'; __file__='"'"'/tmp/pip-install-5pj8j993/functools32/setup.
py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /tmp/pip-install-5pj8j993/functools32/pip-egg-info
         cwd: /tmp/pip-install-5pj8j993/functools32/
    Complete output (1 lines):
    This backport is for Python 2.7 only.
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
make: *** [../libbeat/scripts/Makefile:240: python-env] Error 1
```
problem with python3?

**Comment by jsoriano** [comment]
Yep, only python 2 is supported by now :slightly_frowning_face:

**Comment by TeTeHacko** [comment]
after some alaborating, installing debian, setuping dev environment i ended up with this:
https://gist.github.com/TeTeHacko/79299bdccc266c2d15ba38d8ccad911a

past vedle pasti ...

**Comment by jsoriano** [comment]
> after some alaborating, installing debian, setuping dev environment i ended up with this:
> https://gist.github.com/TeTeHacko/79299bdccc266c2d15ba38d8ccad911a
> 
> past vedle pasti ...

Oh sorry, I forgot one step `make update fields`.

**Comment by elasticcla** [comment]
Hi @TeTeHacko, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in your Git [commit](https://github.com/elastic/beats/pull/14755.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by TeTeHacko** [comment]
running ```mage fmt update``` also make this change:
```diff --git a/filebeat/docs/modules/haproxy.asciidoc b/filebeat/docs/modules/haproxy.asciidoc
index e9771af84..4d71eeffe 100644
--- a/filebeat/docs/modules/haproxy.asciidoc
+++ b/filebeat/docs/modules/haproxy.asciidoc
@@ -54,8 +54,6 @@ include::../include/config-option-intro.asciidoc[]

 include::../include/var-paths.asciidoc[]

-include::../include/timezone-support.asciidoc[]
-
 :has-dashboards!:

 :fileset_ex!:```

is it ok? or i'm doing something wrong?

**Comment by jsoriano** [comment]
@TeTeHacko you have to add this line (`include::../include/timezone-support.asciidoc[]`) to `filebeat/module/haproxy/_meta/docs.asciidoc`, once added there run `mage fmt update`.

Files under `filebeat/docs` are autogenerated.

**Comment by jsoriano** [comment]
ok to test

**Comment by kaiyan-sheng** [comment]
CI failure is not related, merging this pr.

**Pull request merged**
