### PR TITLE
Update communitybeats.asciidoc

### PR DESCRIPTION
**Pull request by klizhentas**

### CODE REVIEW

**Comment by ruflin** [comment]
@klizhentas Thanks a lot for udpbeat. Would you mind signing the CLA?

**Comment by klizhentas** [comment]
@ruflin done!

**Comment by ruflin** [comment]
@klizhentas I had a quick look at your beat. I would recommend to follow the structure we use in our current beats which is also created by https://github.com/elastic/beat-generator This will make updating your beat easier. More documentation for it should follow soon.

**Comment by klizhentas** [comment]
thanks, will do!

**Comment by ruflin** [comment]
@klizhentas Let us know if you need any help / reviews.

**Pull request merged**
