### PR TITLE
Add tracebeat to the community beats

### PR DESCRIPTION
**Pull request by berfinsari**

### CODE REVIEW

**Comment by ruflin** [comment]
@urso I wonder if this could fit into heartbeat?

**Comment by urso** [comment]
@ruflin [see TODO.md](https://github.com/elastic/beats/blob/master/heartbeat/TODO.md#ideas)

**Comment by ruflin** [comment]
@urso Nice :-)

@berfinsari WDYT about contributing this to heartbeat?

**Comment by berfinsari** [comment]
I want to contributing this to heartbeat. Heartbeat is new to me, I will start to work about this.

**Pull request merged**
