### PR TITLE
Run go mod donwload too when checking for changes

### PR DESCRIPTION
**Pull request by jsoriano**
`go mod download` has to be executed also after `go mod tidy` in `make check-no-changes` to be consistent with `make notice`.

Both commands can result on different `go.sum` since go 1.16 (https://github.com/golang/go/issues/43994#issuecomment-769922808).

Issue found when trying to update govmomi in https://github.com/elastic/beats/pull/26167, `make notice` generated a `go.sum` that made `make check-no-changes` to fail.

### CODE REVIEW

**Comment by urso** [comment]
@michel-laterman Can you have a look? Does this change play well with the update to go 1.16.5 here https://github.com/elastic/beats/pull/26186 (If I understand correctly 1.16.5 does revert some changes on go.sum handling).

**Comment by urso** [comment]
@jsoriano The repo was updated to 1.16.5. Is the change still required?

**Comment by michel-laterman** [comment]
The specific change to the makefile was not part of my update, so this might still be needed

**Comment by jsoriano** [comment]
This change doesn't seem to be needed anymore, `make notice` and `make check-no-changes` generate the same `go.sum` now. Thanks!

**Pull request closed without merging**
