### PR TITLE
update elastic-agent-shipper-client deps

### PR DESCRIPTION
**Pull request by fearful-symmetry**
## What does this PR do?

This updates the `elastic-agent-shipper-client` deps to pull in the recent bugfixes.

## Why is it important?

This upstream change fixes a number of bugs.

### CODE REVIEW

**Review by cmacknz — APPROVED** [review]

**Comment by fearful-symmetry** [comment]
Alright, CI errors appear to be actually related, looking over them...

**Comment by fearful-symmetry** [comment]
Alright, I'm not 100% sure if some of these errors. The `"returns error if failed to convert metadata"` and `"returns error if failed to convert fields"` tests now return an event with the fields `{"field":{}}` and I'm not sure if we need/want that to be an error condition? It looks like a few other tests are also failing because we're expected to error out on empty objects.  Should that be an error condition? @cmacknz

**Comment by fearful-symmetry** [comment]
Yah, that's what I thought, just wanted to make sure.

**Comment by fearful-symmetry** [comment]
Want to update the PR with fixes before the long weekend, but right now we're in a weird state where we're not testing certain things like retries/dropped events, since the marshaling code is much more aggressive with not erring out. Will have to re-do some of the mock shipper server so I can get events to drop.

I also suspect that since the event marshaler is more capable of handling map types, there might be some redundant code. Not sure if we want to deal with that in this PR or do a follow-up.

**Comment by fearful-symmetry** [comment]
E2E failures are unrelated, merging

**Pull request merged**
