### PR TITLE
Fix a small typo in a comment

### PR DESCRIPTION
**Pull request by Cybertinus**

### CODE REVIEW

**Comment by kvch** [comment]
Could you please sign the CLA?

**Comment by Cybertinus** [comment]
@kvch Done!

**Comment by ruflin** [comment]
@Cybertinus As the reference file is auto generated you must edit this in the config file under `_meta` and then run `make update`. This should get the build green.

**Comment by dedemorton** [comment]
I've cherry-picked your commit into the master branch (see #7360) and will make sure it gets into all relevant branches. Thanks for your contribution!

**Pull request closed without merging**
