### PR TITLE
[Filebeat] Fix PANW field spelling "veredict" to "verdict"

### PR DESCRIPTION
**Pull request by dainok**
- Bug

## What does this PR do?

Fix a misspelled word: from "veredict" to "verdict"

## Why is it important?

Fix a misspelled word: from "veredict" to "verdict"

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by andrewkroh** [comment]
jenkins, run tests

**Comment by adriansr** [comment]
@dainok this one needed a complicated merging and rebasing to align with current master, hope you don't mind I pushed some commits myself.

**Comment by dainok** [comment]
Don't worry, do as you wish. I'm closing this one.

**Comment by adriansr** [comment]
jenkins, test this

**Comment by andrewkroh** [comment]
run tests

**Comment by andrewkroh** [comment]
jenkins run the tests

**Pull request merged**
