### PR TITLE
Remove `libbeat/metric` and use `github.com/elastic/elastic-agent-system-metrics` instead

### PR DESCRIPTION
**Pull request by kvch**
## What does this PR do?

This PR removes the folder `libbeat/metric` and imports the same functionality from `github.com/elastic/elastic-agent-system-metrics`.

I am not fixing linter issues.

## Why is it important?

Avoid maintaining the same code in different places.

## Checklist

- [x] My code follows the style guidelines of this project
~~- [ ] I have commented my code, particularly in hard-to-understand areas~~
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
~~- [ ] I have added tests that prove my fix is effective or that my feature works~~
~~- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

### CODE REVIEW

**Comment by fearful-symmetry** [comment]
quick thing: The stuff in `metricbeat/internal` also needs to be removed and migrated to `elastic-agent-system-metrics` as well. It's fundamentally the same as the metrics in `libbeat/`, the code just dates to a time when we weren't sure where system metrics were supposed to live.

**Review by cmacknz — APPROVED** [review]

**Comment by cmacknz** [comment]
As usual I just spot checked this, we'll have to rely on CI to find any unexpected problems.

**Comment by kvch** [comment]
I will fix crosscompiling issues in `elastic-agent-system-metrics`.

**Comment by fearful-symmetry** [comment]
@kvch just to make sure I'm on the same page, is the plan  to migrate + remove the metrics code in `libbeat/internal` in a different set of PRs?

**Comment by kvch** [comment]
> just to make sure I'm on the same page, is the plan to migrate + remove the metrics code in libbeat/internal in a different set of PRs?

Yes. If that works for you.

**Pull request merged**
