### PR TITLE
Add versioned troubleshooting message on non-zero exits.

### LINKED ISSUE #26367: [Elastic Agent] Provide link to troubleshooting guide on fatal errors
Can we please provide a link to the troubleshooting guide when Elastic Agent exits with a fatal error? This will help users identify the cause of the problem and how to fix, as well as links to our github repos and discuss forums. 

The current error says:
```
$ sudo ./elastic-agent install -f --url=https://elasticsearch:8220 --enrollment-token=STRSc2ozWUItWXNuWE5oZzdERFU6anJtY0FIMzhSRGlzeTJYcUF5UklfUQ==
The Elastic Agent is currently in BETA and should not be used in production
...
Error: enroll command failed with exit code: 1
```

Can we add a link here to help people fix their problem?
```
Error: enroll command failed with exit code: 1
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/current/fleet-troubleshooting.html
```

### PR DESCRIPTION
**Pull request by michel-laterman**
## What does this PR do?

Add versioned troubleshooting message on non-zero exits.

## Why is it important?

Gives the user a link to resources to help assist with issues.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [] ~~I have made corresponding changes to the documentation~~
- [] ~~I have made corresponding change to the default configuration files~~
- [] ~~I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes #26367 

## Logs

Tested locally:
```
~|⇒ cd elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64
elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64|⇒ rm elastic-agent.yml
elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64|⇒ ./elastic-agent
Error: could not read configuration file /Users/laterman/elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64/elastic-agent.yml: open /Users/laterman/elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64/elastic-agent.yml: no such file or directory
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.0.0/fleet-troubleshooting.html
```

### CODE REVIEW

**Comment by dedemorton** [comment]
Does the version really resolve to n.n.n? If so, the URL will be wrong because the docs URL uses the branch (n.n) not the full version.

For example, https://www.elastic.co/guide/en/fleet/7.14/fleet-troubleshooting.html

Another thought I have is that we should make sure that the troubleshooting guide provides help for every major error the user might encounter. Up until now, we've just listed common problems as they come up, but I think we need to be more methodical so we don't send users to info that frustrates them.

**Review by nimarezainia — APPROVED** [review]

**Comment by michel-laterman** [comment]
Thanks for the catch @dedemorton, output now looks like:
```
elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64|⇒ ./elastic-agent
Error: could not read configuration file /Users/laterman/elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64/elastic-agent.yml: open /Users/laterman/elastic-agent-8.0.0-SNAPSHOT-darwin-x86_64/elastic-agent.yml: no such file or directory
For help, please see our troubleshooting guide at https://www.elastic.co/guide/en/fleet/8.0/fleet-troubleshooting.html
```

**Comment by dedemorton** [comment]
@michel-laterman That looks right. One small thing to note, though... The 8.0 docs won't be available at that URL until we create an 8.0 branch in GitHub. If that's a problem, we can ask the web team to redirect the URL to master temporarily. That's a bit hacky, though, so I would avoid it.

**Review by dedemorton — APPROVED** [review]
Link change is approved (but see my comment in the PR about 8.0 URLs).

**Review by blakerouse — APPROVED** [review]
Looks good.

**Pull request merged**
