### PR TITLE
Forward port 7.16.0 changelog to master

### PR DESCRIPTION
**Pull request by andresrc**
See #29245 . Part of 7.16.0 release.

### CODE REVIEW

**Comment by ruflin** [comment]
Seems like something broke in the pipeline, triggering tests again.

**Comment by andresrc** [comment]
@ruflin I think we need to get https://github.com/elastic/beats/pull/29288 in before

**Comment by ruflin** [comment]
Got the PR merged and merged in master again. Lets see if it helps.

**Review by ruflin — APPROVED** [review]

**Pull request merged**
