### PR TITLE
[Elastic Agent] Disable obsfucation on disk of the api key

### PR DESCRIPTION
**Pull request by ph**
This no real gain to have this obfuscated on disk we just delay a little
bit what an attacker could do with the credentials. The downside of
obfuscating the file is that we do not have an easy way to debug what is
going on.

Fixes: #17282

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by ph** [comment]
restart ci... workers when out of business.

**Comment by michalpristas** [comment]
Jenkins test this

**Comment by ph** [comment]
CI restarted.

**Comment by ph** [comment]
Rebased.

**Pull request closed without merging**
