### PR TITLE
Allow autodiscover to monitor unexposed ports

### PR DESCRIPTION
**Pull request by vjsamuel**
The metrics hint builder needs a slight change to allow monitoring of endpoints like `${data.host}:9090`. Currently it blocks such cases. For host network containers, there wouldnt be any port on the configuration as well. We would just spin up metricbeat modules, if port is 0 and the host hint has `data.host` on it.

### CODE REVIEW

**Comment by ruflin** [comment]
jenkins, test it

**Comment by ruflin** [comment]
jenkins, test it

**Comment by vjsamuel** [comment]
@ruflin added the documentation. this really only affects Kubernetes autodiscover and not docker.

**Comment by ruflin** [comment]
jenkins, test it

**Pull request merged**
