### PR TITLE
WIP [CI] support ubuntu-1404-i386 in the pipeline

### PR DESCRIPTION
**Pull request by v1v**
WIP

## What

Explore support for ubuntu-14-32 bits

## Tasks

- [ ] Similar requirements when testing w7-32bits?

cc @kuisathaverat 

## Issues

- Docker is installed but broken!

- Tar/Untar steps take ages

image

### CODE REVIEW

**Comment by v1v** [comment]
jenkins run the tests please

**Comment by mikemadden42** [comment]
jenkins run the tests please

**Comment by mikemadden42** [comment]
jenkins run the tests please

**Comment by v1v** [comment]
This particular VM won't be used for building and testing but validating the binaries, therefore this particular PR is not required.

**Pull request closed without merging**
