### PR TITLE
Features/http output plugin filebeat

### PR DESCRIPTION
**Pull request by jpchev**
## What does this PR do?
This is to add a http output plugin to filebeat. I've integrated the code from https://github.com/raboof/beats-output-http/tree/master/http

## Why is it important?
This is important for the following scenario: filebeat is on a private network and logstash is on another network, reachable via Internet. The company infrastructure requires to transfer data to logstash using https and a web proxy. Contacting logstash using the Lumberjack standard TCP port is not allowed.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally
set in your filebeat.yml
```
output:
  http:
    hosts: ["http://yourhost"]
```

### CODE REVIEW

**Comment by jpchev** [comment]
> This pull request does not have a backport label. Could you fix it @jpchev? 🙏
> To fixup this pull request, you need to add the backport labels for the needed
> branches, such as:
> 
> * `backport-v./d./d./d` is the label to automatically backport to the `7./d` branch. `/d` is the digit
> 
> **NOTE**: `backport-skip` has been added to this pull request.

can you please let me know how to add the label? I don't see the button in github UI, probably I don't have the required permissions

**Comment by jpchev** [comment]
hi there, any news about this PR?

**Comment by kvch** [comment]
@jpchev Unfortunately, we are not going to merge this PR because we do not intend to add more outputs to Beats. The goal of the project is to collect data from every source we can and forward those to the Elastic Stack. The existing external outputs like Kafka and Redis are still supported as the documentation suggests. Also, console and files outputs are required for debugging. However, we do not want to add anything else besides the existing outputs at the moment. Thank you for your understanding.

**Comment by jpchev** [comment]
no, I won't bother, since this isn't going to be merged

**Comment by jlind23** [comment]
@jpchev would you please then close this PR?

**Comment by businessbean** [comment]
> @jpchev Unfortunately, we are not going to merge this PR because we do not intend to add more outputs to Beats. The goal of the project is to collect data from every source we can and forward those to the Elastic Stack. The existing external outputs like Kafka and Redis are still supported as the documentation suggests. Also, console and files outputs are required for debugging. However, we do not want to add anything else besides the existing outputs at the moment. Thank you for your understanding.

We have several use cases to forward events to Elasticsearch and https outputs in parallel. Currently we are using Logstash for that and without a beats http-output we have no options to migrate these workloads.

@richardgilm fyi...

**Comment by JAndritsch** [comment]
> The goal of the project is to collect data from every source we can and forward those to the Elastic Stack.

Beats are part of the Elastic Stack. Can we have Beats output to Beats? This functionality would help support more complex network environments where the end goal is to get data into Elasticsearch, but in a less direct way. More info: https://github.com/elastic/beats/issues/33107

**Pull request closed without merging**
