### PR TITLE
[FIlebeat] add strict_date_optional_time_nanos date format to PanOS module

### LINKED ISSUE #26033: Palo Alto | include "strict_date_optional_time_nanos" format for date fields
Logs that are generated from Palo Alto's Cortex Data Lake default to using the date format strict_date_optional_time_nanos, while the panw-panos-pipeline currently defaults to using the following date format:

```
"formats": [
    "yyyy/MM/dd HH:mm:ss"
 ],
```

Adding 'strict_date_optional_time_nanos' as a default date format for the filebeat panw-panos-pipeline will also users to ingest data from  Palo Alto's Cortex Data Lake without manually modifying the pipeline. This format has been tested by a user:

```
"formats": [
        "yyyy/MM/dd HH:mm:ss",
        "strict_date_optional_time_nanos"
      ],
```

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Adds `strict_date_optional_time_nanos` date format to the date processors

## Why is it important?

See #26033

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally
```
cd beats/x-pack/filebeat
TESTING_FILEBEAT_MODULES=panw mage -v pythonIntegTest
```

## Related issues

- Closes #26033

### CODE REVIEW

**Comment by legoguy1000** [comment]
@jamiehynds Do you have sample data I can add to this to validate the changes??

**Comment by jamiehynds** [comment]
> @jamiehynds Do you have sample data I can add to this to validate the changes??

@legoguy1000 working on getting sample data for you. Thanks as always for the contribution!

**Comment by jamiehynds** [comment]
@legoguy1000 sample log below. Adjusted the IP's to ensure they are anonymised. 

```
1,2021-05-26T16:27:07.000000Z,no-serial,TRAFFIC,end,9.1,2021-05-26T16:26:47.000000Z,127.0.0.0,127.0.0.1,127.0.0.2,127.0.0.3,intrazone-default,,,web-browsing,vsys1,untrust,untrust,ethernet1/1,ethernet1/1,Cortex Data Lake,,688290,1,35834,443,35834,20077,0x1400070,tcp,allow,7291,1696,5595,21,2021-05-26T16:26:30.000000Z,1,medium-risk,,620386,0x8800000000000000,US,SG,,14,7,tcp-fin,22,18,0,0,,GP cloud service,from-policy,,,0,,0,1970-01-01T00:00:00.000000Z,N/A,0,0,0,0,6a2f6161-88f2-4afc-8dd5-256bc4505a64,0,0,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,,
```

**Review by P1llus — APPROVED** [review]

**Comment by legoguy1000** [comment]
@Mergifyio refresh

**Comment by legoguy1000** [comment]
@Mergifyio backport 7.x

**Pull request merged**
