### PR TITLE
[Metricbeat] migrate envoyproxy module to ReporterV2 error

### PR DESCRIPTION
**Pull request by berfinsari**
See elastic/beats#11374 and elastic/beats#10727

### CODE REVIEW

**Comment by ruflin** [comment]
jenkins, test this

**Comment by berfinsari** [comment]
Is there anything that I can do for this unsuccessful check?

**Comment by fearful-symmetry** [comment]
Jenkins failure seems unrelated.

**Comment by fearful-symmetry** [comment]
jenkins, test this

**Comment by ruflin** [comment]
jenkins, test this

**Pull request merged**
