### PR TITLE
Backport elastic-agent/pull/255

### PR DESCRIPTION
**Pull request by michel-laterman**
## What does this PR do?

Backport of https://github.com/elastic/elastic-agent/pull/255 to 8.1.x release

## Related issues

- Closes https://github.com/elastic/elastic-agent/issues/275

### CODE REVIEW

**Review by blakerouse — APPROVED** [review]
Backport matches whats in elastic-agent. Looks good.

**Review by AndersonQ — APPROVED** [review]

**Comment by ph** [comment]
@mdelapenya Is there something going on with the e2e suite?

**Comment by jlind23** [comment]
@ph This a credential issue Manu raised a couple of days ago. It is not linked to this PR.

**Comment by eric-ooi** [comment]
Upgrading Windows and Linux agents from 8.1.1/8.1.2 to 8.1.3 continues to fail for me.

**Comment by maggieghamry** [comment]
Upgrading Windows and Linux agents from `8.1.1` and `8.1.2` to later versions is still failing. Was the backport to `8.1.3` only?

**Pull request merged**
