### PR TITLE
Add module for receiving CEF data

### PR DESCRIPTION
**Pull request by andrewkroh**
This is a module for receiving Common Event Format (CEF) data over Syslog. When
messages are received over the syslog protocol the syslog input will parse the
header and set the timestamp value. Then the decode_cef processor is applied to parse
the CEF encoded data. The decoded data is written into a `cef` object field. Lastly any
Elastic Common Schema (ECS) fields that can be populated with the CEF data are
populated.

### CODE REVIEW

**Comment by andrewkroh** [comment]
The module test is failing when comparing the expected JSON to the actual JSON. I don't see the difference between the two and it passes locally for me. 😕

**Comment by webmat** [comment]
I'm flummoxed. Same thing happening for me. Passes locally. I even diff'ed the expected JSON with the actual (really fun to diff flat vs nested 😂), and I cannot see the difference either, other than the keys that are removed from the golden files.

**Comment by webmat** [comment]
Ah I think I found it. `@timestamp` changes between test runs.

**Comment by andrewkroh** [comment]
Thanks for looking. Yes, it's the `@timestamp`. I was looking through the source code for the test and found a list of modules that need to have their `@timestamp`s removed. I have now added `cef.log` to that list.

**Pull request merged**
