### PR TITLE
New protocol support: SIP

### PR DESCRIPTION
**Pull request by tj8000rpm**
Hi all. I implemented a new protocol SIP to packetbeat. #152 
The SIP(Session Initiation Protocol) is a communications protocol for signaling and controlling multimedia communication sessions. SIP is used many VoIP applications at not only enterprise uses but also telecom careers.

SIP is text-base protocol like HTTP. But SIP has various unique features like :
- SIP is server-client model, but it roles may changes call by call.
- SIP is request-response model, but server may (usualy) reply many responses for one request.
- There many requests and responses in one call.
- It is not know when the call will end.

Therefore, I implemented with following plans.
- Published for each SIP message(request or response)
- Additional timestamp to make it possible to keep message order
- Parse and store each header field and SDP body(option)
- Received raw message is stored as text value(option)

More detail is writen in README.md

### CODE REVIEW

**Comment by st1t** [comment]
Hi @tj8000rpm .
Do you have still intention that merge to this pull request.
If you have it, please read follow document.
and, I think that It settle Travis's problem to execute 'make update'.

https://www.elastic.co/guide/en/beats/devguide/current/beats-contributing.html#update-scripts

**Comment by tj8000rpm** [comment]
Hi @st1t , 
Thank you for your advice.  I read the docs and try it.  
Thanks

**Comment by tj8000rpm** [comment]
Hi @adriansr 

How is the code I newly committed to PR?
Should I do anything else or any improve my code elsewhere?

I'm glad if you give me some advice. :smiley:

**Comment by tj8000rpm** [comment]
hi @adriansr 
Thank you for your approval!
I'm looking forward to it is merged into the master branch.

**Comment by adriansr** [comment]
hi @tj8000rpm 
I've pinged the Beats to have someone else have a look at it before merging

**Comment by tj8000rpm** [comment]
I was not changing the any codes, but below error occurred on  jenkins check.

```
make[1]: Leaving directory `/var/lib/jenkins/workspace/Beats_beats-beats-mbp_PR-7181/src/github.com/elastic/beats'
diff --git a/packetbeat/protos/sip/fields.go b/packetbeat/protos/sip/fields.go
index 024025547..7ca1488f7 100644
--- a/packetbeat/protos/sip/fields.go
+++ b/packetbeat/protos/sip/fields.go
@@ -24,12 +24,13 @@ import (
 )
 

 func init() {
-	if err := asset.SetFields("packetbeat", "sip", asset.ModuleFieldsPri, Asset); err != nil {
+	if err := asset.SetFields("packetbeat", "sip", asset.ModuleFieldsPri, AssetSip); err != nil {
 		panic(err)
 	}
 }
 

-// Asset returns asset data
-func Asset() string {
+// AssetSip returns asset data.
+// This is the base64 encoded gzipped contents of protos/sip.
+func AssetSip() string {
 	return "eJys1d9v2jAQB/B3/opTnhfkpEtW0rVCWjcpmrahwvZUaXKTI/GaxMbndOW/nwwE0hrUrvx4iS7c1x8Mvvhwj8sESKgBgBGmwgS8aTrxBgA5UqaFMkI2CUzTiU8KMzEXGeADNgbmAquchgPYXCUDAAAfGl5jF2lfZqkwgULLtqv0P9/vqdGUMt+Wu9Z7XP6Vul9/Qrvq3QALhRtctEgGvj3Pw0deK/sd0++/0tlnB6DXjX6rxekUP2/SfQQSKillgeNNZZjJOolYzC6M5g0pqc1lmyvHSIablvxM5ugYK9kU/wMkJRtCsFnvNsHwLHjrDRk7ZFGl5uRq3rBja9DW4gRvNT++Opi5lvXxhi9a1lAiz1HDA6/avat7tx4JpW49+Gh/Rns9DtjQvoOrC8OLy/AsPpumEzXjBWOB52CNPJ46k6+CtqZzxhGLooiFUTgORuEwiM934CB+fz7qxEHoijNeVb44wen8ZIPS65ftewyEixMAprh4cfXg0Iy4k/nSMci7P5iZXnld+P0q4azEVSrIOZgSV8YaiXiBQ3DPnM6O3ALZ6gwhnQDPc41EwJsc7LzZuw+7P8pqOjmenMxxnmskIxpubx2F6kBtIx6NqLHhjXzyCOpNxwOcrhU4gW0n7PZ6t3QUxMFoFMcxC+IPUcwYG/wLAAD//2we7qA="
 }
packetbeat/protos/sip/fields.go: needs update
make: *** [check] Error 1
```

I was fetch and merge from upstream into my local repository and ran the ``make check``.
After the check,  the error occured on my local enviroment too.
It looks like conflict with other merged commit(#10168).

So I removed the script generated ``fields.go`` and make new ``fields.go`` with ran the ``make update`` that is on the error message indicated and its error was resolved.

This is my new commit(https://github.com/tj8000rpm/beats-1/commit/c9f0cbe86dc4891cbea74538511425c7eb32e90b), but it was not affect this PR.

What I should do? Should I create the new PR? or edit by using online editor?

**Comment by tj8000rpm** [comment]
Oops! I'm sorry! It was affected, it seems to that had some time lag :sweat_smile:

**Comment by tj8000rpm** [comment]
Hi @adriansr , and Beats team.

How have things been after that?
I understand that you are busy to release a new version 7, but I would highly appreciate if you have a any care to this PR.

Thanks.

**Comment by monicasarbu** [comment]
@tj8000rpm Apologies for the delay here. @urso will be looking at this next week.

**Comment by tj8000rpm** [comment]
Thanks @monicasarbu, I appreciate your support.

**Comment by WaaZaa666** [comment]
Hi @adriansr, @monicasarbu, @tj8000rpm  kind of wondering what the status is on this issue. I am working on a project where this would come in handy. Seems it's almost ready...

**Comment by khou** [comment]
Out of curiosity, is this no longer being considered?

**Comment by tj8000rpm** [comment]
hi all.
there are people who are interested this feature, so I'm going to try resolve conflicts and apply to new version.

**Comment by rinderbe** [comment]
Hi @tj8000rpm, i've waited such a long time for someone to take on this task. Looks like you're almost on the finish line here :)
Any plans for taking it to the line and beyond? 

Appreciate your work! 

/Robin

**Comment by vnil1994** [comment]
I've also been waiting for SIP support for a very long time now. Do you have any ETA on when it might be available for version 7?

Thanks!

**Comment by tj8000rpm** [comment]
@vnil1994 and @rinderbe,
Thank you for following this feature. I adapted this feature to Beats new version.
It works in my local environment and almost tests passed my local test. but it seems to that my CLA was expired.

**Comment by adriansr** [comment]
cla/check

**Comment by adriansr** [comment]
Hi @tj8000rpm

I'm trying to get this merged (finally!).

It seems there is a problem with the CLA. I see that the last few commits are not attributed to your user, but to `Hiroshi Tsuji <ho-tsuji@....>` (no github username). This might be caused by you accidentally pushing from an email address that is not associated to your github account. Can you fix this, either by [changing the author on those commits](https://stackoverflow.com/questions/3042437/how-to-change-the-commit-author-for-one-specific-commit) or by adding that email to your github profile?

Also, this needs a changelog entry, in `CHANGELOG.next.asciidoc` under _Added_ > _Packetbeat,_ something in the lines of:

> Added support for decoding SIP protocol. {pull}7181[7181]

But feel free to use your own wording.

**Comment by tj8000rpm** [comment]
@adriansr 
Thank you for your advice. I accidentally worked with the settings for the company.
It is difficult to me all historical email addr change to private one, so I added a work email addr to github setting.

And I also added a CHANGELOG entry.

**Comment by marc-gr** [comment]
jenkins run tests

**Comment by marc-gr** [comment]
@tj8000rpm Let's try to merge this once again 💪 

It would be nice to update the branch, since CHANGELOG is conflicted and probably would be a good idea to run `make fmt update` one more time. Since it is quite behind, LMK if you want to sort it out yourself or want us to take over from this point.

In general it looks fine, if you can would be nice to rename the files to `snake_case` i.e.: `sip_message` instead of `sipMessage`, to follow general conventions.

Thanks for your patience one more time ❤️  hopefully we'll get this through sooner than later 🎉

**Comment by marc-gr** [comment]
Hello @tj8000rpm!

Please let us know if you need any help or want us to do the changes ourselves :)

Thanks! ❤️

**Comment by ebeahan** [comment]
Linking an open issue with some possible SIP mappings that align well with ECS: https://github.com/elastic/ecs/issues/420

@marc-gr Would you mind working with us to adjust the fields from this PR with the ones from the linked issue? We still need to review them a bit, but feel they are pretty good already.

cc @jamiehynds @webmat

**Comment by marc-gr** [comment]
> Linking an open issue with some possible SIP mappings that align well with ECS: [elastic/ecs#420](https://github.com/elastic/ecs/issues/420)
> 
> @marc-gr Would you mind working with us to adjust the fields from this PR with the ones from the linked issue? We still need to review them a bit, but feel they are pretty good already.
> 
> cc @jamiehynds @webmat

That is awesome! 

I have been taking a look at this branch and the merge/rebase of it is quite tricky since is quite old. @tj8000rpm  since it seems that this is something we want to move forward soon, I'll be opening a new PR based on this one to solve the issues and add the new field mappings so you do not lose authorship since you did all the work ❤️ 🙇‍♂️

**Comment by marc-gr** [comment]
@ebeahan @tj8000rpm I opened https://github.com/elastic/beats/pull/21221 to follow with the changes and ECS mappings. I am closing this to avoid confusion.

**Pull request closed without merging**
