### PR TITLE
[WIP] Add Kuberentes tests to pipeline

### PR DESCRIPTION
**Pull request by ruflin**

### CODE REVIEW

**Comment by ruflin** [comment]
Closing for now as it's not as easy as I hoped. One recommendation from @kuisathaverat was to run the service inside a container.

@exekias FYI, tried a quick fix here to migrate this to Jenkins from Travis.

**Comment by kuisathaverat** [comment]
It is a little tricky to run minikube in a docker container but it is possible in two ways one is using the docker server from the Agent by mounting the Docker socket (it use to be insecure but we use a single shot agent so it does not matter too much)

Dockerfile

```
FROM ubuntu:18.04
ARG MINIKUBE_VERSION=v0.32.0
ARG KUBECTL_VERSION=v1.9.4
ENV CHANGE_MINIKUBE_NONE_USER=true
ENV GODEBUG=netdns=go

RUN apt-get -qq update && \
  apt-get -qq -y install docker.io curl sudo
  
RUN curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/${KUBECTL_VERSION}/bin/linux/amd64/kubectl \
  && chmod +x kubectl && mv kubectl /usr/local/bin/
RUN curl -Lo minikube https://storage.googleapis.com/minikube/releases/${MINIKUBE_VERSION}/minikube-linux-amd64 \
  && chmod +x minikube && mv minikube /usr/local/bin/

EXPOSE 2375 8443

ENTRYPOINT minikube start --vm-driver=none --kubernetes-version=v1.9.4 --logtostderr && minikube logs -f

```

command line

```
docker run --rm -it  -v /var/run/docker.sock:/var/run/docker.sock --privileged --ulimit nofile=32000:32000 --name minikube docker-minikube 
```

Or to use the DIND image, it is a little slower but is secure, I found some examples like this one:

https://github.com/moonswitch/minikube-alpine

Command line

```
docker run --rm -it --privileged --name minikube-dind --ulimit nofile=32000:32000 moonswitch/minikube-alpine:latest
```

**Comment by ruflin** [comment]
@kuisathaverat Thanks a lot for the details. Super useful.
@exekias I leave it up to you if you want to move this to pipeline and which approach to take. In general I think it would be good to get this also on Jenkins builds.

**Comment by exekias** [comment]
Thank you for trying! definitely it would be awesome to have it in jenkins, I agree it should be part of https://github.com/elastic/beats/issues/8210, adding a note there

**Pull request closed without merging**
