### PR TITLE
enable netinfo host metadata

### PR DESCRIPTION
**Pull request by DanRoscigno**
The Observability solution expects `netinfo.enabled` to be true:
```
processors:
  - add_host_metadata:
      netinfo.enabled: true
```
When the defaults (false) are set launching from Uptime to Logs or Metrics fails (the filter gets set to `host.ip: <ip addr>` and by default `host.ip` is not set.

### CODE REVIEW

**Comment by kaiyan-sheng** [comment]
Does this consider a breaking change? @exekias @jsoriano WDYT?

**Comment by jsoriano** [comment]
I wouldn't say that this is a breaking change. It would add some extra fields by default, what I think is ok. We should confirm that the added fields don't cause any conflict, but they are ECS fields (`host.ip` and `host.mac`), so I wouldn't expect problems because of that.

But if we do this change, we should do it also in the code, not only in docs and the reference config. We should change the default in https://github.com/elastic/beats/blob/v7.5.2/libbeat/processors/add_host_metadata/config.go#L36

This would also require a changelog entry.

**Comment by DanRoscigno** [comment]
> But if we do this change, we should do it also in the code, not only in docs and the reference config. We should change the default in https://github.com/elastic/beats/blob/v7.5.2/libbeat/processors/add_host_metadata/config.go#L36
> 
> This would also require a changelog entry.

@jsoriano , do you want me to make that change, or are you going to do it?

**Comment by jsoriano** [comment]
> > But if we do this change, we should do it also in the code, not only in docs and the reference config. We should change the default in https://github.com/elastic/beats/blob/v7.5.2/libbeat/processors/add_host_metadata/config.go#L36
> > This would also require a changelog entry.
> 
> @jsoriano , do you want me to make that change, or are you going to do it?

@DanRoscigno as you prefer, the main change would be only to change this `false` to `true` in https://github.com/elastic/beats/blob/v7.5.2/libbeat/processors/add_host_metadata/config.go#L36, but we may also need to update the tests.

Then we will also need to review this value in docs and reference configs and add a changelog entry.

**Comment by DanRoscigno** [comment]
I think it is risky for me to modify the tests, can you do it Jaime?

**Comment by jsoriano** [comment]
Ok, no probl, I'll do it!

**Comment by jsoriano** [comment]
I have opened https://github.com/elastic/beats/pull/16077 to continue with this. Thanks @DanRoscigno!

**Pull request closed without merging**
