### PR TITLE
Skip flaky tests seen in #9194

### PR DESCRIPTION
**Pull request by jsoriano**
Skip flaky tests seen in #9194 (#9213, #9214, #9215, #9216)

### CODE REVIEW

**Comment by jsoriano** [comment]
Umm, same tests failed :man_facepalming: maybe they are not so flaxy, and I should have used `os.name == 'nt'`, I'll try again.

**Comment by ph** [comment]
@jsoriano Not they that aren't flaky, I think it's from the go 1.11.2 upgrade.

**Comment by ruflin** [comment]
@ph I think some of them were flaky before, just not that constant.

**Comment by ph** [comment]
>  I think some of them were flaky before, just not that constant.

Correct, but I would say its more a permanent state now.

**Pull request merged**
