### PR TITLE
add options to configure k8s client qps/burst

### LINKED ISSUE #28149: Autodiscover could reach to k8s client's default rate limit
**Describe the enhancement:**
currently when using autodiscover for `pod` resources, beats adds `deployment.name` if the specific pod owned by `ReplicaSet` that's also owned by `Deployment`, in this function [getRSDeployment](https://github.com/elastic/beats/blob/master/libbeat/common/kubernetes/metadata/pod.go#L140-L159), go client was used directly without leveraging k8s cache/store, however go client has QPS 5 and Burst 10 [by default](https://github.com/kubernetes/client-go/blob/master/rest/config.go#L45-L46), which could be a bottle neck of autodiscover. It may not be a good idea to introduce a replicaset watcher because of memory overhead, which seems the only way to accelerate this function is adding options to configure the client's QPS/Burst.

**Describe a specific use case for the enhancement or feature:**
in k8s clusters that a single beats' pod is responsible for a lot of pods.

### PR DESCRIPTION
**Pull request by newly12**
# Enhancement

## What does this PR do?

add options to configure k8s client qps/burst

## Why is it important?

Accelerate autodiscover pod event processing

## Checklist

- [x] My code follows the style guidelines of this project
- [x] ~~I have commented my code, particularly in hard-to-understand areas~~
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] ~~I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes #28149

### CODE REVIEW

**Comment by newly12** [comment]
@ChrsMark yes I think we still like to have #28521 to allow to disable it as 1) we don't need deployment name to be added 2) API calls overhead.. feel free to let me know your thought on this

**Comment by ChrsMark** [comment]
Cool @newly12 let's discuss about #28521  after this one is merged :) in general it sounds reasonable.

Regarding this PR, could you check the lint errors? Maybe you need some `make update` after the docs' additions :)

**Comment by ChrsMark** [comment]
CI failure is unrelated, I will merge this one. Thank you @newly12 again!

**Pull request merged**
