### PR TITLE
x-pack/winlogbeat: add parent process ID to new process creation events

### PR DESCRIPTION
**Pull request by efd6**
## What does this PR do?

Add parent process ID to new process creation events.

## Why is it important?

Parent process ID is important information for security/threat detection.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
~~- [ ] I have made corresponding changes to the documentation~~
~~- [ ] I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Closes ##29237.

### CODE REVIEW

**Comment by efd6** [comment]
@Mergifyio update

**Comment by andrewkroh** [comment]
Is this a sync of the pipeline from https://github.com/elastic/integrations/pull/2966?

**Comment by efd6** [comment]
Yes, this is the sync. I'll also do the change mentioned [here](https://github.com/elastic/integrations/pull/2966#pullrequestreview-932596966) for this, but it's not without tests. There is a 4688 evtx that is ingested and tested.

**Comment by andrewkroh** [comment]
> but it's not without tests.

What's running that test (if you didn't update that golden file what would fail)? I thought these were without tests due to https://github.com/elastic/beats/issues/30406.

**Comment by efd6** [comment]
No, you are right. I have copied over the expectation from the ingerations package, so when there are test this will be check. Apologies.

**Review by andrewkroh — APPROVED** [review]

**Pull request merged**
