### PR TITLE
Read archived .evtx files with Winlogbeat

### LINKED ISSUE #4450: [Winlogbeat] Add option to read .evt and .evtx files
Would it be possible to have a functionality which would allow to read .evt files directly ? 
Something like : 

winlogbeat:
  prospectors:
    - input_type: winlog
      paths:
        - C:\System32\Winevt\Logs\ *.evt

### PR DESCRIPTION
**Pull request by andrewkroh**
This gives Winlogbeat the ability to read from archived .evtx files. The `name` parameter recognizes that the value is absolute path and then uses the appropriate APIs to open the file and ingest its contents. In order to support the use case of reading from a file and then exiting when there are no more events (`ERROR_NO_MORE_ITEMS`) I added a config option to change the behavior of the reader from waiting for more events to stopping.

I also had to add `shutdown_timeout` option to make Winlogbeat wait for events to finish publishing before exiting.

To keep it simple, globs are not supported. This would have required the introduction of a "prospector" to continuously monitor the glob for new / moved / deleted files.

In the FAQ I [added an example of how to use this feature](https://github.com/elastic/beats/blob/fb8ebb651830d69849f5ac48e066c53e8653d2c3/winlogbeat/docs/faq.asciidoc#can-winlogbeat-read-from-evtx-files).

Closes #4450 

~TODO~

- [x] Update reference docs and reference config with the new options.
- [x] Should it populate `log.file.path` when reading from an .evtx file?

### CODE REVIEW

**Comment by andrewkroh** [comment]
With this enhancement in place it will make it easier to test the development of event processing pipelines since you can playback stored event logs. Aside from that, this has been a much requested feature.

**Comment by meggenberger** [comment]
can no_more_events only be stop?
I have the use case where a storage System (Netapp) is generating Windows Events and writes them to a file on a share in evtx format. Events will be added to that file all day and every they the file will be rotated out (current file keeps the name and older events will be rotated out to a file with a date suffix).

**Comment by andrewkroh** [comment]
See https://www.elastic.co/guide/en/beats/winlogbeat/master/configuration-winlogbeat-options.html#_literal_event_logs_no_more_events_literal.

**Comment by meggenberger** [comment]
Great .... this will solve my problem. Now only 7.1. has to be released soon. Thanks for this feature!

**Pull request merged**
