### PR TITLE
[7.3] Adding docs for beat Metricbeat module (#13087)

### PR DESCRIPTION
**Pull request by ycombinator**
Backports the following commits to 7.3:
 - Adding docs for beat Metricbeat module  (#13087)

### CODE REVIEW

**Comment by ycombinator** [comment]
Heya @dedemorton, could you help me figure out why CI is failing on this backport PR? The changes in this PR are identical to the original PR made to `master`: #13083.

**Comment by dedemorton** [comment]
@ycombinator Try running `make update`. Looks like a couple of the files need to be updated:

```
10:33:46 metricbeat/docs/modules/beat.asciidoc: needs update
10:33:46 metricbeat/docs/modules/beat/state.asciidoc: needs update
10:33:46 make: *** [check] Error 1
10:33:46 metricbeat/docs/modules/beat/stats.asciidoc: needs update
````

**Comment by ycombinator** [comment]
Thanks @dedemorton, I'll do that now.

But I'm curious why I'd need to run this on this **backport** PR. Why would the changes from the `master` PR not apply as-is to `7.3` (the target branch of this PR)?

**Comment by dedemorton** [comment]
@ycombinator Not sure, but try running `make update` and you'll be able to see what's different.

**Comment by ycombinator** [comment]
I ran `make update`. The differences can be seen in 4001b04.  I suspect they exist because there's no `mage update` in `7.3`? At any rate, I don't think they're of consequence.

**Comment by ycombinator** [comment]
So @dedemorton does this PR LGTY?

**Pull request merged**
