### PR TITLE
Remove ID from Runner interface

### PR DESCRIPTION
**Pull request by vjsamuel**
Fixes https://github.com/elastic/beats/issues/5153

### CODE REVIEW

**Comment by exekias** [comment]
ok to test

**Comment by ruflin** [comment]
@exekias SGTM

**Comment by exekias** [comment]
:+1: @vjsamuel can you remove that mentioned method? then this is good to go

**Comment by vjsamuel** [comment]
@exekias @ruflin done.

**Comment by exekias** [comment]
jenkins test it please

**Comment by exekias** [comment]
We get this error at https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/1506/beat=filebeat,label=ubuntu/console:
```
19:40:11 crawler/crawler.go:101: arg p.ID in printf call is a function value, not a function call
```

**Comment by exekias** [comment]
jenkins test it please

**Comment by exekias** [comment]
I've reproduced the issue locally, although it doesn't make sense to me, it's gone on a second run :confused:

**Comment by ruflin** [comment]
Only checked travis and I see the following failure:

```
======================================================================
FAIL: Test if module is properly started and stoppped
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/travis/gopath/src/github.com/elastic/beats/metricbeat/tests/system/test_reload.py", line 87, in test_start_stop
    assert lines == self.output_lines()
AssertionError
```

@exekias Is this related what you saw locally (once)?

**Comment by exekias** [comment]
No, tests are OK, the only weird thing is around `vet`

**Comment by exekias** [comment]
We decided to merge this as the `vet` error seems spurious from some cache in jenkins, will see if it's still happening in master

**Pull request merged**
