### PR TITLE
Support for running the container with an arbitrary UID:GID

### PR DESCRIPTION
**Pull request by mieciu**
## What does this PR do?

This PR has been created primarily with the APM Server in mind. It enables running APM Server Docker container with an arbitrary UID/GID. At this moment it's impossible to run APM Server Docker container like this:
```
docker run --user 31337:1337 -v $HOST_PATH:/container_path -i -t docker.elastic.co/apm/apm-server:8.0.0-SNAPSHOT
/usr/local/bin/docker-entrypoint: line 8: /usr/share/apm-server/apm-server: Permission denied
```

## Why is it important?

Right now in oder to achieve the aforementioned runtime, we have to 
1) Build custom image adding the following
```
USER root
RUN chmod -R +r /usr/share/apm-server/ingest
RUN chmod +rx /usr/share/apm-server/apm-server
```
2) Configure APM to write solely to bind-mounted volume (which is possible`--path.home=/container_path --path.config=/container_path/config --path.data=/container_path/data -path.logs=/container_path/logs`)

The aim of this PR is to remove the need for 1).

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

Related: https://github.com/elastic/beats/issues/24269

### CODE REVIEW

**Review by jsoriano — APPROVED** [review]
LGTM, I don't see any special problem on giving more read or execution permissions for files included in the images.

**Comment by mieciu** [comment]
Just FYSA, those windows tests seem to be flaky, they've passed before.

**Pull request merged**
