### PR TITLE
Fix timezone parsing in Rabbitmq logs

### PR DESCRIPTION
**Pull request by jsoriano**
Similar to https://github.com/elastic/beats/pull/13308, part of https://github.com/elastic/beats/issues/13877.

### CODE REVIEW

**Comment by jsoriano** [comment]
jenkins, test this again please

**Comment by leweafan** [comment]
@jsoriano I see that ingest pipeline is using DATESTAMP which means date format dd-mm-yyyy or mm-dd-yyyy but it's not a case for test.log (2019-04-03 11:13:15.076) also I see that used timestamp format yy-mm-dd which also is not a case for DATESTAMP.
How is it possible that tests passed successful?

**Comment by jsoriano** [comment]
@leweafan good catch. I have tried this pipeline, without removing the `timestamp` field, and I see that it works by chance, it is capturing the datestamp as:
```
"timestamp": "19-04-03 11:13:15.510"
```
Later, the `date` processor is interpreting `19` as `2019`, but this is effectively error prone, and this will start failing at least in 2032. I tried changing the year in a date to 2032 and:
```
unexpected pipeline error: Text '2-04-03 11:13:15.076' could not be parsed at index 0
```
I will open an issue to fix this.

Thanks for reporting!

**Comment by jsoriano** [comment]
Oh, you already opened an issue, I will comment there.

**Pull request merged**
