### PR TITLE
Change type of text fields to keyword

### PR DESCRIPTION
**Pull request by kvch**
As suggested by @ruflin in https://github.com/elastic/beats/pull/10518/files/e229e9f761b8132976e53a35637fbe6e19a999b8#r253442649

### CODE REVIEW

**Comment by kvch** [comment]
jenkins test this

**Comment by ruflin** [comment]
Very good point by @webmat I assume something is wrong with the indentation or naming in the fields.yml which means all the other fields are not part of the template either.

**Comment by kvch** [comment]
@ruflin Indeed. I've fixed the indentation problem.

**Comment by kvch** [comment]
Sure.

**Comment by kvch** [comment]
Opened two backports:
* 6.x: https://github.com/elastic/beats/pull/10555
* 6.6: https://github.com/elastic/beats/pull/10556

**Comment by kvch** [comment]
Rebased

**Comment by kvch** [comment]
Travis refuses to start, so I am waiting for jenkins.

**Comment by kvch** [comment]
All relevant tests are green.

**Pull request merged**
