### PR TITLE
[Filebeat] [Redis] module added ability to collect ACL LOG

### PR DESCRIPTION
**Pull request by Totoshky**
labels: Filebeat Enhancement Team:SIEM

## What does this PR do?

This is implementation of new feature of Redis filebeat module. 

With this PR filebeat has ability to collect [ACL Logs](https://redis.io/commands/acl-log) from Redis.

It is very similar to slowlog submodule.

## Why is it important?

With properly configured ACL on Redis security teams or administrators have ability to monitor ACL Logs to detect attacks or misconfigured behavior. With this change filebeat is becoming very useful in shipping ACL Logs in Elastic SIEM, for example.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

It is very similar to slowlog. You have to build filebeat binary, enable Redis module with proper configuration and run.

Please configure ACL on Redis in order to generate logs. 

A very simple ACL is described [here](https://redis.io/topics/acl)

`ACL SETUSER alice` create acl policy for user alice
 `ACL SETUSER alice on >p1pp0 ~cached:* +get` set password and permissions
`AUTH alice p1pp0` authenticate with user credentials
`SET cached:1234 zap` try to modify values, this generates ACL LOG

Now you have ACL Log, and you can view it in Redis via `ACL LOG` command.

### CODE REVIEW

**Comment by P1llus** [comment]
@Totoshky thanks a lot for the contribution! Are you able to sign the CLA agreement that has been posted on this PR above?

**Comment by Totoshky** [comment]
> @Totoshky thanks a lot for the contribution! Are you able to sign the CLA agreement that has been posted on this PR above?

@P1llus , I have already signed the CLA agreement, just after the bot reminder, please verify.

**Comment by P1llus** [comment]
cla/check

**Comment by jlind23** [comment]
@Totoshky - Closing this one as there were no activity for a while

**Pull request closed without merging**
