### PR TITLE
 The socket.entity_id field was removed in 7.4.0

### PR DESCRIPTION
**Pull request by dharada**
see - https://github.com/elastic/beats/issues/17346

## What does this PR do?

to fix a docs bug.

## Why is it important?

it cause to misunderstand about auditbeat spec.

### CODE REVIEW

**Comment by efd6** [comment]
This change needs to happen in auditbeat/module/system/_meta/fields.yml and then be generated into the asciidoc.

**Comment by dedemorton** [comment]
I'm being optimistic with backport labels. I'll backport this as far as I can, but it can be tricky sometimes to get CI to pass on backports to old branches.

**Comment by dedemorton** [comment]
@efd6 Can you take another look and approve if it looks good to you? Thanks!

**Review by efd6 — APPROVED** [review]
Thank you.

**Pull request merged**
