### PR TITLE
Automatic merge from master to 7.x branch

### PR DESCRIPTION
**Pull request by ruflin**

### CODE REVIEW

**Comment by ruflin** [comment]
jenkins, test this

**Comment by ruflin** [comment]
@urso Looks like this PR is all green except the breaking changes which happened in ML. We could merge as is or update this PR as soon as the fix is merged into 7.0

@simitt How is the urgency on the apm-server side?

**Comment by simitt** [comment]
CI is broken for APM Server 7.x in the mean time, but I wouldn't call it super urgent.

**Comment by ruflin** [comment]
Closing this PR for now as I will not get to merge it in the next days.

@urso @simitt @kvch Could one of you open a new one?

**Pull request closed without merging**
