### PR TITLE
Add link to Elastic support matrix to getting started doc

### PR DESCRIPTION
**Pull request by dedemorton**
Added link to support matrix in response to https://github.com/elastic/beats/issues/135.

### CODE REVIEW

**Comment by ruflin** [comment]
@dedemorton Unfortunately the first option selected when coming to the matrix is "Product and JVM" and beats does not show up here. I couldn't find an option to select the different pages through the url.

**Comment by dedemorton** [comment]
@ruflin I thought the same. I didn't want to provide exact steps for finding the information on the page, though, because the page can change without us realizing that it's changed. 

Should I see if the web folks would consider putting the Product and Operating System page first instead of the JVM page? It seems like the question "What operating systems are supported?" comes before "Which JVM can I use?" anyhow.

**Comment by ruflin** [comment]
@dedemorton Looking at the code of the website I found a direct link (we should always read code first :smile: ): https://www.elastic.co/support/matrix#matrix_os I would expect that it updates the link also if you manually browse the page. 
@sylvie777 Not directly a "bug" but perhaps good to know.

**Comment by sylvie777** [comment]
Thanks, @ruflin! I will change the functionality so bookmarking is possible when switching tabs.

**Comment by dedemorton** [comment]
I know...who needs tables and images, right? I'll put in the direct link...thanks!

**Comment by dedemorton** [comment]
Hmmm....when I use the direct link, though, users don't immediately see the Support Matrix title and  links at the top of the page (they need to page up). This might cause some initial confusion.  

@sylvie777 I'm wondering if there is a link I can provide that will send users to the operating system page, but still show the top of the page (with page title and links for other sections). Or maybe there is a link where they can go directly to the page that I see when I click the "display all" link?

**Comment by sylvie777** [comment]
@dedemorton I swapped the tabs: https://www.elastic.co/support/matrix

**Comment by sylvie777** [comment]
@dedemorton @ruflin FWIW, the URLs now change when you switch tabs:

https://www.elastic.co/support/matrix

**Comment by ruflin** [comment]
@sylvie777 Thanks a lot, works. The behaviour on smaller screens is a little bit confusing as the location it jumps to (probably because of the anker) is on top of the button. That means if you have the buttons on multiple lines, the buttons above disappear which means you have to scroll up to find the other options again. But I don't see it as a big issue.

**Comment by sylvie777** [comment]
@ruflin Ah, I see what you mean...hm, I'll look into how to change this. May need to change the design for smaller screens.

**Pull request merged**
