### PR TITLE
Fix agent download timeout values in yaml files

### LINKED ISSUE #28788: incorrect default value of agent.download.timeout in Elastic Agent reference yaml
As of 7.15.1 the default value of `agent.download.timeout` is 120s ([code](https://github.com/elastic/beats/blob/v7.15.1/x-pack/elastic-agent/pkg/artifact/config.go#L47-L48)), not 30s as shown in the [reference YAML](https://github.com/elastic/beats/blob/v7.15.1/x-pack/elastic-agent/_meta/elastic-agent.yml#L65-L66).
Please update the YAML.

### PR DESCRIPTION
**Pull request by michel-laterman**
## What does this PR do?

Change the `agent.download.timeout` value to `120s` to match the code
https://github.com/elastic/beats/blob/5ae799cb1c3c490c9a27b14cb463dc23696bc7d3/x-pack/elastic-agent/pkg/artifact/config.go#L47-L48

## Checklist

- [] ~~My code follows the style guidelines of this project~~
- [] ~~I have commented my code, particularly in hard-to-understand areas~~
- []~~ I have made corresponding changes to the documentation~~
- [x] I have made corresponding change to the default configuration files
- [] ~~I have added tests that prove my fix is effective or that my feature works~~
- [] ~~I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.~~

## Related issues

- Closes #28788

### CODE REVIEW

**Comment by nimarezainia** [comment]
@michel-laterman thanks for taking this on. I am wondering how the 120s was arrived at?
I don't want to make this complicated but seems to me that this should be a function of the network speed/bandwidth and any number of seconds we pick for time out could be arbitrary. As in 120s may not even be enough of a time out in some scenarios. Also agents (as part of the same fleet) get installed in different environments.

Do we have any other counters at our disposal? like bytes transferred or something like that to allow us to determine the timeout more dynamically? again I don;t want to unnecessarily complicate things. What would happen if the timeout was 10 mins? 

@ruflin @michalpristas your thoughts?

**Comment by ruflin** [comment]
This here is only a fix of the wrong value shown as it is already 120s. But I agree with @nimarezainia we should have a deeper discussion on what we expect when downloading binaries. What is the timeout? What are the retries? What happens on slow / broken downloads? Etc.

@nimarezainia Could we take this a separate issue?

**Review by ruflin — APPROVED** [review]
Change LGTM but seem CI is not happy?

**Pull request merged**
