### PR TITLE
Update Go to 1.13.3

### PR DESCRIPTION
**Pull request by mikemadden42**

### CODE REVIEW

**Comment by urso** [comment]
LGTM. Let's see what CI thinks.

**Comment by andrewkroh** [comment]
run beats-ci/package

**Comment by andrewkroh** [comment]
The auditbeat test failure is also related to initialization of testing flags. Here's the fix:

```diff
diff --git a/auditbeat/module/file_integrity/eventreader_fsevents.go b/auditbeat/module/file_integrity/eventreader_fsevents.go
index e9f5384e7..c22994838 100644
--- a/auditbeat/module/file_integrity/eventreader_fsevents.go
+++ b/auditbeat/module/file_integrity/eventreader_fsevents.go
@@ -20,7 +20,6 @@
 package file_integrity
 
 import (
-       "flag"
        "os"
        "path/filepath"
        "strings"
@@ -34,10 +33,6 @@ import (
 
 var underTest = false
 
-func init() {
-       underTest = flag.Lookup("test.v") != nil
-}
-
 type fsreader struct {
        stream      *fsevents.EventStream
        config      Config
diff --git a/auditbeat/module/file_integrity/eventreader_test.go b/auditbeat/module/file_integrity/eventreader_test.go
index f444aa6ea..6d9b02f78 100644
--- a/auditbeat/module/file_integrity/eventreader_test.go
+++ b/auditbeat/module/file_integrity/eventreader_test.go
@@ -32,6 +32,10 @@ import (
        "github.com/stretchr/testify/assert"
 )
 
+func init() {
+       underTest = true
+}
+
 // ErrorSharingViolation is a Windows ERROR_SHARING_VIOLATION. It means "The
 // process cannot access the file because it is being used by another process."
 const ErrorSharingViolation syscall.Errno = 32
```

**Comment by urso** [comment]
@andrewkroh What is the impact of setting underTest to true, always. Maybe we want to have a lazy call in the module constructor using sync.Once. Like:

```
var (
  underTest bool
  initUnderTest sync.Once
)

func checkUnderTest() bool {
  initUnderTest.Do(func() {
    ...
  })
}
```

**Comment by andrewkroh** [comment]
The `underTest` variable is set once from a `_test.go` file during package initialization. It causes the file monitor to react to events generated by the testing process (normally it ignores events triggered by itself). So I think it should be fine to just set directly during initialization.

**Comment by urso** [comment]
Makes sense. Thanks for the clarification. In this sense I'd say that your proposed change even makes this a little cleaner.

**Pull request merged**
