### PR TITLE
Cherry-pick #9603 to 6.x: Fixes parsing of GC entries in elasticsearch server log

### LINKED ISSUE #9513: [filebeat] Wrong "gc_overhead" parsed by Elasticsearch module
**Version**: 6.5.3

The Elasticsearch Filebeat module will parse the following GC log message:
```
[2018-12-07T16:10:41,612][WARN ][o.e.m.j.JvmGcMonitorService] [node1] [gc][238436] overhead, spent [650ms] collecting in the last [1s]
```
Into a document that has:
```json
{
  "elasticsearch": {
    "server": {
      "component": "o.e.m.j.JvmGcMonitorService",
      "gc_overhead": "238436"
    },
    "node": {
      "name": "node1"
    }
  }
}
```

There are a couple of issues here:
1. The value for field `elasticsearch.server.gc_overhead` is coming from `[gc][238436] overhead`. According to this https://github.com/elastic/elasticsearch/blob/master/server/src/main/java/org/elasticsearch/monitor/jvm/JvmGcMonitorService.java#L309 the number `238436` is just a sequential number that holds no significant meaning in GC timings. This is not the GC overhead
2. It does not collects the two important time components from this log message present in: `spent [650ms] collecting in the last [1s]`

### PR DESCRIPTION
**Pull request by ycombinator**
Cherry-pick of PR #9603 to 6.x branch. Original message: 

Resolves #9513.

This PR:
* removes the incorrectly-parsed `gc_overhead` field. Turns out what we were parsing was actually an insignificant sequential number, not GC overhead,
* parses out a new  `gc.collection_duration` field, e.g. `1.2s`, which is the time spent performing GC, and
* parses out a new `gc.observation_duration` field, e.g. `1.8s`, which is the overall time over which GC collection was performed

It also splits up the long grok expression in the ingest pipeline into smaller patterns and references those patterns, hopefully for easier readability.

### CODE REVIEW

**Comment by ycombinator** [comment]
If you look at the diff of this PR and compare it with the diff of the original PR to `master`, you will notice that this PR's diff has a lot more lines changed. That's misleading because most of these changes are formatting changes which change the whitespace. So best to view this PR's diff while ignoring whitespace, like so: https://github.com/elastic/beats/pull/9810/files?w=1

**Comment by ruflin** [comment]
Should this PR have a changelog? Is this a breaking change?

**Comment by tsouza** [comment]
This is an interesting question Nicholas. It's technically a breaking
change since we are changing the structure of the data being collected, but
I find it hard that anyone was using these messages for anything useful
since the semantics of the collected data was wrong anyway. But yeah, it's
a breaking change.

**Comment by ycombinator** [comment]
Technically this is a breaking change, but as @tsouza pointed out the old field was meaningless. Tangential note: this module is in `beta`, so hopefully its okay to make the breaking change in a minor version?

Regardless, I think this deserves an entry in the CHANGELOG. I missed it in the original PR to `master` (#9603) but will add an entry here.

**Comment by ycombinator** [comment]
@ruflin I added *two* CHANGELOG entries, or rather the same entry under two sections: breaking changes and bug fixes. Do you think this is okay?

**Comment by ruflin** [comment]
@ycombinator I'm also good if we agree that it was a bug :-) Can you add this also the .next Changelog in case you are already touching the PR?

**Comment by ycombinator** [comment]
@ruflin I've updated this PR per your feedback and CI is green now. Mind taking another look at it, when you get a chance? Thanks.

**Pull request merged**
