### PR TITLE
Update docs.asciidoc

### PR DESCRIPTION
**Pull request by metabsd**
I think you have to change core for cpu. Little error.

### CODE REVIEW

**Comment by exekias** [comment]
We will need to forwardport this to master, ok to test

**Comment by exekias** [comment]
Thank you for fixing this @metabsd, could you please sign the contributor agreement? https://www.elastic.co/contributor-agreement

**Comment by metabsd** [comment]
@exekias I just sign it. I will continue to learn Beats.

**Comment by exekias** [comment]
That's awesome, thanks!

**Pull request merged**
