### PR TITLE
Add dedot option to docker and k8s autodiscover

### PR DESCRIPTION
**Pull request by kaiyan-sheng**
Dedot option seems to be missing in docker autodiscover and kubernetes autodiscover. Adding dedot option for both docker and k8s here for https://github.com/elastic/beats/pull/10758 and

### CODE REVIEW

**Comment by ruflin** [comment]
Could you check if we also miss something in k8s autodiscovery?

**Comment by kaiyan-sheng** [comment]
> Could you check if we also miss something in k8s autodiscovery?

Yes! That's on the list! Thanks!

**Comment by kaiyan-sheng** [comment]
Added annotations.dedot for k8s, still need to figure out where to put labels.dedot for k8s.

**Comment by kaiyan-sheng** [comment]
I dont think this is needed. Dedot is done in docker and k8s metricbeat module seems like. I will reopen this PR if this is not the case.

**Comment by ruflin** [comment]
Not sure I can follow your last comment but I'm still catching up. Where will be the data from autodiscovery be dedotted?

**Pull request closed without merging**
