### PR TITLE
Stop running agent container as root by default

### PR DESCRIPTION
**Pull request by jsoriano**
## What does this PR do?

Stop running Elastic Agent as root by default on docker image. When root user or other privileges are required, they will need to be explicitly configured at run time. This already happens now, except for the root user.
Provided Kubernetes manifests already use security context to run as user 0.

## Why is it important?

Using `USER root` in docker images is not a very good practice, and is not allowed in some certification processes (see #20996).

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] ~~I have made corresponding changes to the documentation~~
- [x] ~~I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [x] Confirm that this is not related to https://github.com/elastic/beats/issues/21120. (Confirmed by using a file lock to synchronize check and run methods of the install operations).

## Related issues

* Part of #20996.
* Related to #19600.

### CODE REVIEW

**Comment by michalpristas** [comment]
@blakerouse is this ok from endpoint perspective?

**Comment by jsoriano** [comment]
@michalpristas take into account that after this change is still possible to use `--user 0`, `--privileged` and similar configurations. It is only not made by default now, what is forbidden in some certification processes. With the changes in this PR, the default configuration included in the image works (at least it starts Metricbeat and Filebeat).

When running Endpoint (or Packetbeat, Auditbeat, and some features in other beats), if more privileges are required, these privileges have to be provided on runtime. This already happens now, running a container as root doesn't guarantee full privileges.

**Comment by blakerouse** [comment]
@michalpristas It is not possible to run Endpoint in a container at the moment, so this will change will not affect Endpoint when it comes to Agent inside of a container.

**Comment by jsoriano** [comment]
Failing tests are flaky ones, packaging failure seems to be unrelated to this change as also affects other PRs.

**Comment by jsoriano** [comment]
Packaging builds passing, other failures are flaky tests.

**Review by kvch — APPROVED** [review]

**Pull request merged**
