### PR TITLE
Cherry-pick #23142 to 7.11: Cherry-pick #22076 to 7.x: Cherry-pick to 7.10: packaging backports

### PR DESCRIPTION
**Pull request by jsoriano**
Cherry-pick of PR #23142 to 7.11 branch. Original message: 

Cherry-pick of PR elastic/beats#22076 to 7.x branch. Original message: 

Backports the following commits to 7.10:
 - feat: add a new step to run the e2e tests for certain parts of Beats (#21100)
 - [E2E Tests] fix: set versions ony for PRs (#21608)
 - [CI: Packaging] fix: push ubi8 images too (#21621)
 - fix: remove extra curly brace in script (#21692)
 - fix: update fleet test suite name (#21738)
 - chore: create CI artifacts for DEV usage (#21645)
 - chore: simplify triggering the E2E tests for Beats (#21790)
 - chore: delegate variant pushes to the right method (#21861)
 - feat: package aliases for snapshots (#21960)
 - fix: use proper param name for e2e tests (#22836)

### CODE REVIEW

**Review by mdelapenya — APPROVED** [review]

**Comment by mdelapenya** [comment]
We are in the process of creating 7.11.x in the e2e repo, will trigger the tests once it's created

**Comment by jsoriano** [comment]
@mdelapenya is there something missing for the E2E tests? I don't see they are launched for this PR.

**Comment by mdelapenya** [comment]
Yes, the 7.11.x branch is not already there. I'm about to create it today

**Comment by mdelapenya** [comment]
@jsoriano the PR to 7.11.x updating versions is there. As the packaging job is already finished to this PR, and once that PR is merged, we can trigger the E2E tests manually. I'll ping you back

**Pull request merged**
