### PR TITLE
Slow log examples with extracted fields from message

### PR DESCRIPTION
**Pull request by pgomulka**
Fields which were previously enclosed in a message are now a top level
field in JSON log line. Also array fields are now escaped json, this
will likely be fixed in the future

### CODE REVIEW

**Comment by ycombinator** [comment]
Thanks @pgomulka. I'll add the expected file to this PR and make any ingest pipeline adjustments (if necessary).

**Comment by ycombinator** [comment]
@pgomulka I've updated the PR with the expected file, `slowlogs-json.log-expected.json`. Please check the objects and fields in it and compare it with the lines in the sample log file, `slowlogs-json`.

**Comment by pgomulka** [comment]
@ycombinator it looks good! thank you

**Comment by ycombinator** [comment]
Jenkins CI failure (Windows / X-Pack Metricbeat) is unrelated.

**Pull request merged**
