### PR TITLE
Rename all Kibana directory from 6 to 7

### PR DESCRIPTION
**Pull request by ruflin**
This changes all the Dashboards directory from 6 to 7. The dashboards itself were not touched. This change means all the dashboards under 7 are optimised for Beats and in the future Kibana 7. If a users wants to have the old dashboards without ECS fields inside, he needs to load the dashboards with a version 6 of the Beat. The reasoning here is that compatibility with 6.x dashboards is an opt in feature in 7 so it's expected that users who need this, already have the 6 dashboards. For now all the 7 dashboards could be loaded into a 6 version of Kibana but it is not recommended. I tested it manually with MB 7 and KB 6.5.4.

The directories were renamed with the following command:

```
find . -depth -type d -name '6' -execdir mv {} 7 \;
```

This should rename all the directories. It's important that open dashboard PR's are adjusted for the new directory structure.

Closes https://github.com/elastic/beats/issues/10069

### CODE REVIEW

**Comment by tsg** [comment]
Thanks @ruflin, pinging the whole @elastic/secops on this one for visibility. I think at least Christoph and Adrian have in-progress dashboards.

**Comment by tsg** [comment]
Are we throughing away the `5` directories? Also CC-ing @monicasarbu and @urso for awerness.

**Comment by ruflin** [comment]
@tsg Yes, we did quite some time ago: https://github.com/elastic/beats/pull/8927

**Comment by cachedout** [comment]
This shouldn't affect @elastic/stack-monitoring so we're good here. :)

**Comment by kaiyan-sheng** [comment]
Does this PR need a rebase since https://github.com/elastic/beats/pull/10224 is merged?

**Comment by ruflin** [comment]
@kaiyan-sheng Just did a rebase, would probably have worked without it as we did the exact same changes.

**Pull request merged**
