### PR TITLE
[Heartbeat] Improved redirect support

### PR DESCRIPTION
**Pull request by andrewvc**
This patch better handles redirects in heartbeat. It takes a different tack than what was described in elastic/beats#13146 . This PR is on the whole more pragmatic, accomplishing substantive change with undue complication of the schema and beats codebase. 

Changes in this patch:
* Added `http.response.redirects` field. This is an array of URLs redirected to inclusive of the final destination, exclusive of the original URL.
* Utilize the `host` codepath, rather than the IP codepath for execution of the check, previously only used for proxies in heartbeat, for redirects. This simplifies the code, hides timing data that can be screwy with redirects (things like fine grained DNS resolution). This means that the following fields no longer appear with redirects enabled in the event: `http.rtt.content.us`, `http.rtt.response_header.us`, `http.rtt.total.us`, `http.rtt.validate.us`, `http.rtt.write_request.us`.
* Default `max_redirects: 0` instead of `10`

The new default does make this a breaking change, however, we either need to break that setting and preserve the timing information for the common use case of someone checking a non-redirecting URL, or keeping it at `10` but losing the timing info. The third option would be to invest additional eng. effort here to track those numbers across reqs, but the benefit seems, minimal given that they are not displayed in the UI, only in dashboards.

### CODE REVIEW

**Comment by andrewvc** [comment]
@ruflin Thanks for the review! I've updated the PR description to include the full list of removed fields when HTTP redirects are enabled.

**Comment by ruflin** [comment]
@andrewvc I was actually thinking of documentation for our users, something like https://www.elastic.co/guide/en/beats/libbeat/current/breaking-changes-7.4.html

**Comment by ruflin** [comment]
@andrewvc Not sure if you saw my last comment here: https://github.com/elastic/beats/pull/14125#issuecomment-544831361 I think this is still needed in a follow up PR.

**Comment by andrewvc** [comment]
@ruflin ah, I missed it, will add.

**Pull request merged**
