### PR TITLE
Fix and extend logging of light modules load errors

### PR DESCRIPTION
**Pull request by jsoriano**
Two things are solved here:
* Errors were being logged with `logp.Error` that doesn't actually log anything, use a local logger and its `Errorf` method instead.
* Log errors also when listing modules for string representation.

This was hiding errors, what was specially confusing when permissions are not correct during development and testing, now errors like this one are logged if permissions are not correct:
```
2019-11-22T12:03:51.398+0100	ERROR	mb/lightmodules.go:107	failed to load module config for module 'cockroachdb': failed to load module configuration from '/home/jaime/gocode/src/github.com/elastic/beats/x-pack/metricbeat/module/cockroachdb/module.yml': config file ("/home/jaime/gocode/src/github.com/elastic/beats/x-pack/metricbeat/module/cockroachdb/module.yml") can only be writable by the owner but the permissions are "-rw-rw-r--" (to fix the permissions use: 'chmod go-w /home/jaime/gocode/src/github.com/elastic/beats/x-pack/metricbeat/module/cockroachdb/module.yml')
```

Some errors have been rephrased so logged errors start with uppercase, and "failed to" is not logged in all nested errors.

### CODE REVIEW

**Comment by jsoriano** [comment]
This is making many test to fail because the find errors in logs, I am adding `BEAT_STRICT_PERMS=false` to the beat service in docker-compose as is done in filebeat.

**Comment by exekias** [comment]
what will happen to folks running tests outside docker? we need to think about that case too

**Comment by jsoriano** [comment]
> what will happen to folks running tests outside docker? we need to think about that case too

Logging-wise it would be the same.

Regarding permissions, when running tests outside docker (and in systems with default umask != 0022 as most ubuntu distros) it is usual to require `BEAT_STRICT_PERMS=false` in may tests, specially for filebeat, and now also for metricbeat with light modules. We are setting the environment variable in most tests related to light modules for convenience.

**Comment by kaiyan-sheng** [comment]
@jsoriano Seems like this PR is ready to go besides the conflict 😄 I saw this during triage party time. Could you take a look at this one again when you get a chance please? Thanks!

**Comment by jsoriano** [comment]
@kaiyan-sheng good catch :smile: The original issue was solved in other way, but the fixes in logging may still be needed, I will take a look.

**Comment by jsoriano** [comment]
Revisited, this would be ready for another review.

**Comment by jsoriano** [comment]
There was a bug causing regular files in the `module` directory to be listed as modules with no metricsets. I have fixed this and added a test to cover this case. This would need another review.

**Pull request merged**
