### PR TITLE
[Metricbeat] Migrate ETCD Store to use ReporterV2 interface

### PR DESCRIPTION
**Pull request by sayden**
Refer to https://github.com/elastic/beats/issues/10774 for more info

### CODE REVIEW

**Comment by sayden** [comment]
jenkins, test this again please because `No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.`

**Comment by sayden** [comment]
Error seems unrelated in Elasticsearch module https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/beat=metricbeat,label=linux-immutable/5213/console

I think we have a flaky test there

**Comment by sayden** [comment]
Issue opened describing the flaky https://github.com/elastic/beats/issues/10866

**Comment by jsoriano** [comment]
> Error seems unrelated in Elasticsearch module https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/beat=metricbeat,label=linux-immutable/5213/console
> 
> I think we have a flaky test there

This error looks like if the container died, not sure if we should consider this flaky.

**Comment by sayden** [comment]
Propose the name you want to give it [here](https://github.com/elastic/beats/issues/10866) if you want :wink: https://github.com/elastic/beats/issues/10866 

The point is that it shouldn't fail when unrelated code is pushed and it should be fixed somehow, call it flaky test or task.

**Pull request merged**
