### PR TITLE
Cherry-pick #8014 to 6.x: Add a HAProxy filebeat module.

### PR DESCRIPTION
**Pull request by jsoriano**
Cherry-pick of PR #8014 to 6.x branch. Original message: 

I created a new module for parsing HAProxy http logs via filebeat. Originally developed on version 6.3 of elasticsearch/filebeat.

Feedback would be appreciated, please let me know if there's anything missing.

### CODE REVIEW

**Comment by ruflin** [comment]
Are failures related to the other geoip issue?

**Comment by jsoriano** [comment]
Yes, failures where related to #8204, I have updated the branch

**Comment by jsoriano** [comment]
jenkins, test this again please

**Comment by jsoriano** [comment]
jenkins, test this again

**Pull request merged**
