### PR TITLE
Update communitybeats.asciidoc

### PR DESCRIPTION
**Pull request by maniankara**
Added fileoccurencebeat to the list.
This beat is very handy in queues/pipeline buffers

### CODE REVIEW

**Comment by exekias** [comment]
thank you for submitting! could you please explain what is this beat doing?

**Comment by maniankara** [comment]
In simple words, this can send the count of files under a certain directory. A short demo here: https://youtu.be/UPaJdBv2LjQ and Part 1 details here: https://medium.com/cloudronics/convert-your-code-snippet-to-an-elastic-beat-in-8-simple-steps-54dfa2beb67c (part 2 is yet to be published).

**Comment by maniankara** [comment]
@exekias any updates here?

**Comment by exekias** [comment]
sorry for the delay, thank you so much for explaining it! I just merged it :tada:

**Pull request merged**
