### PR TITLE
Remove extra changelog entries introduced in #29197

### PR DESCRIPTION
**Pull request by kvch**

### CODE REVIEW

**Review by michalpristas — APPROVED** [review]
lgtm

**Comment by kvch** [comment]
jenkins run tests

**Comment by kvch** [comment]
jenkins run tests

**Comment by kvch** [comment]
jenkins run tests

**Comment by andresrc** [comment]
@kvch the changes for this PR are already included in https://github.com/elastic/beats/pull/29250. I think we can close it (it's good to check the build issues we are having though, thanks!)

**Comment by kvch** [comment]
The entries has been fixed.

**Pull request closed without merging**
