### PR TITLE
Cherry-pick to 7.10: Add `add_observer_metadata` `geo.name` to Quickstart (#21501)

### PR DESCRIPTION
**Pull request by EamonnTP**
Backports the following commits to 7.10:
 - Add `add_observer_metadata` `geo.name` to Quickstart (#21501)

### CODE REVIEW

**Review by bmorelli25 — APPROVED** [review]

**Review by dedemorton — APPROVED** [review]
LGTM

**Comment by EamonnTP** [comment]
@elastic/uptime, I can't merge until one from the team approves this. When you have time, can someone take a look?

For some reason, I could merge the other backports, but not this one.

**Comment by bmorelli25** [comment]
> For some reason, I could merge the other backports, but not this one.

Hmmm. I ran into the same problem on another PR with 7.10 and the Uptime team.

**Comment by EamonnTP** [comment]
Hi @andrewvc. If you have time today, could you take a look at this PR? Thanks!

**Comment by andresrc** [comment]
@EamonnTP [this build](https://beats-ci.elastic.co/job/Beats/job/beats/view/change-requests/job/PR-21640/2/) went ok, so I think we are good to go

**Comment by EamonnTP** [comment]
Thanks @andresrc

**Pull request merged**
