### PR TITLE
Fix http status phrase parsing not allow spaces (#4795)

### LINKED ISSUE #4795: Wrong phrase in the http.response.phrase field
- Version: Packetbeat 5.5.0
- OS: Red Hat Enterprise Linux Server release 6.7 (Santiago) (Linux 2.6.32-504.8.1.el6.x86_64 #1 SMP Wed Jan 28 21:11:36 UTC 2015)
- Steps to reproduce: parse an HTTP 500 or HTTP 404 response with Packetbeat and inspect the http.response.phrase field in the produced event.

It appears that Packetbeat 5.5.0 (the HTTP module) only gets the last word from HTTP status line when searching for the response phrase (i.e. `HTTP/1.1 404 Not Found` turns into "Found" in the `http.response.phrase` field). More details are available in [this forum post](https://discuss.elastic.co/t/wrong-phrase-in-the-http-response-phrase-field/95182).

Examples of HTTP response headers and status lines that produce wrong http.response.phrase values:
```
HTTP/1.1 404 Not Found
Server: Apache-Coyote/1.1
Content-Type: text/html;charset=utf-8
Content-Length: 949
Date: Mon, 31 Jul 2017 11:31:53 GMT

HTTP/1.1 500 Internal Server Error
Server: Apache-Coyote/1.1
Content-Type: text/html;charset=utf-8
Content-Length: 3739
Date: Mon, 31 Jul 2017 11:33:28 GMT
Connection: close
```

### PR DESCRIPTION
**Pull request by liketic**
Closes #4795

### CODE REVIEW

**Comment by exekias** [comment]
jenkins test this please

**Comment by exekias** [comment]
jenkins retest this please

**Comment by urso** [comment]
LGTM. Can you add an entry to Changelog.asciidoc?

**Comment by liketic** [comment]
@urso Updated. Thanks for reviewing this one.

**Comment by exekias** [comment]
jenkins test it, please

**Comment by urso** [comment]
Merged. Thank you for taking the time to fix the parsing.

**Pull request merged**
