### PR TITLE
Update Beats to elastic-agent-libs v0.2.7

### PR DESCRIPTION
**Pull request by cmacknz**
The changes this picks up per https://github.com/elastic/elastic-agent-libs/releases are:

1. https://github.com/elastic/elastic-agent-libs/pull/59
2. https://github.com/elastic/elastic-agent-libs/pull/62
3. https://github.com/elastic/elastic-agent-libs/pull/64

I don't think any of these are user facing so I haven't updated the changelog. Probably we should automate this update to happen once a week or so, but we'd always need to watch for changelog updates.

### CODE REVIEW

**Comment by cmacknz** [comment]
Authors of the changes being picked up added as reviewers.

**Review by rdner — APPROVED** [review]

**Comment by cmacknz** [comment]
Packaging failures seem unrelated:

```

[2022-07-05T19:22:17.694Z] Status: Downloaded newer image for docker.elastic.co/beats-dev/golang-crossbuild:1.17.11-darwin-arm64-debian10

[2022-07-05T19:22:23.026Z] >> Building using: cmd='build/mage-linux-amd64 golangCrossBuild', env=[CC=oa64-clang, CXX=oa64-clang++, GOARCH=arm64, GOARM=, GOOS=darwin, PLATFORM_ID=darwin-arm64]

[2022-07-05T19:25:47.787Z] # github.com/elastic/beats/v7/metricbeat

[2022-07-05T19:25:47.787Z] /usr/local/go/pkg/tool/linux_amd64/link: /usr/local/go/pkg/tool/linux_amd64/link: running dsymutil failed: exit status 1

[2022-07-05T19:25:47.787Z] osxcross: error: xcrun: cannot find 'dsymutil' executable
```

**Review by rdner — APPROVED** [review]

**Pull request merged**
