### PR TITLE
Added hsnburrowbeat to Community Beats

### PR DESCRIPTION
**Pull request by hsngerami**
Features:

Updated to Beats 6.2.1
Updated to Golang 1.9.4
Burrow V1.0.0(API V3) Support
Docker Support

### CODE REVIEW

**Comment by karmi** [comment]
Hi @hsngerami, we have found your signature in our records, but it seems like you have signed with a different e-mail than the one used in yout Git [commit](https://github.com/elastic/beats/pull/6478.patch). Can you please add both of these e-mails into your Github profile (they can be hidden), so we can match your e-mails to your Github profile?

**Comment by hsngerami** [comment]
@karmi Done

**Comment by ruflin** [comment]
@hsngerami No need from your side to do the backport as @dedemorton does frequent bulk updates to the list. Also it there went something wrong during the cherry picking. If ok for you I suggest to close this PR.

**Comment by hsngerami** [comment]
ok. thanks

**Pull request closed without merging**
