### PR TITLE
[Filebeat] Add Base64 encoded HMAC & UUID template functions to httpjson input

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Add Base64 encoded HMAC & UUID template functions to httpjson input

## Why is it important?

In order to create an Akamai Agent integration.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have made corresponding change to the default configuration files
- [X] I have added tests that prove my fix is effective or that my feature works
- [X] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

- Relates elastic/integrations#1304

### CODE REVIEW

**Comment by P1llus** [comment]
Hi @legoguy1000 , thanks for your awesome PR's as always! I will discuss this one, as we might not want to use any additional libraries for this, and rather add in the functionality it requires to httpjson itself, it might be that our recent changes we made would work with this actually

**Comment by legoguy1000** [comment]
I think the alternative to adding the EdgeGrid Library is to add another HMAC function that returns Base64 encoded signatures instead of Hex.  See https://github.com/elastic/beats/pull/27873/commits/f746b13e970332d960b98a97c9c5178f682afa88

Then do below to implement EdgeGrid 
```
- type: httpjson
  enabled: true
  config_version: 2
  interval: 1m
  request.url: XXXXXX
  request.transforms:
    - set:
        target: url.params.from
        value: '[[.cursor.timestamp]]'
        default: '[[ (now (parseDuration "-24h")).Unix ]]'
    - set:
        target: header.XTimestamp
        value: '[[ formatDate (now) "20060102T15:04:05-0700" ]]'
    - set:
        target: header.XSignatureBase
        value: '[[ sprintf "EG1-HMAC-SHA256 client_token=%s;access_token=%s;timestamp=%s;nonce=%d;" "a" "b" (.header.Get "XTimestamp") now.UnixNano  ]]'
    - set:
        target: header.XSignatureKey
        value: '[[ hmacBase64 "sha256" "c" (.header.Get "XTimestamp") ]]'
    - set:
        target: header.XSignature
        value: '[[ hmacBase64 "sha256" (.header.Get "XSignatureKey") "GET\t" .url.Host "\t" .url.Path "?" .url.RawQuery "\t\t\t" (.header.Get "XSignatureBase") ]]'
    - set:
        target: header.Authorization
        value: 'EG1-HMAC-SHA256 [[ sprintf "%ssignature=%s" (.header.Get "XSignatureBase") (.header.Get "XSignature") ]]'
```
It appears to work and generates the below headers
```
xtimestamp	20210914T18:33:08+0000
xsignaturekey	L/1kX9gfY7GIFly7G3z3vkj3YUzFWpCHqqDR7HimwpM=
xsignaturebase	EG1-HMAC-SHA256 client_token=a;access_token=b;timestamp=20210914T18:33:08+0000;nonce=1631644388219193225;
xsignature	i4Ln1LOulRMhwJ8v8vAa5s+XfqcQ2fCkirJYHuGzLSQ=
authorization	EG1-HMAC-SHA256 EG1-HMAC-SHA256 client_token=a;access_token=b;timestamp=20210914T18:33:08+0000;nonce=1631644388219193225;signature=i4Ln1LOulRMhwJ8v8vAa5s+XfqcQ2fCkirJYHuGzLSQ=
```

**Comment by legoguy1000** [comment]
I think I'm going to also add a UUID template function for the `nonce` field as there is no way currently to generate randomness.

**Comment by legoguy1000** [comment]
@marc-gr @P1llus I think  we're good to go now.

**Review by marc-gr — APPROVED** [review]
LGTM 👍 thanks for taking the time to change it with our feedback 😄 !

**Pull request merged**
