### PR TITLE
[Logging] Include Logstash host info in debug messages #5198

### LINKED ISSUE #5198: Logging:  Include Logstash host info in debug messages
Related to https://github.com/elastic/beats/issues/5175

Even when connections are working, it will be helpful to include the Logstash host information as part of the debug logging so we can tell which Logstash host the beat is attempting to send events to.

Currently our debugging logging only specifies the number of events and window size.

```
Try to publish N events to logstash with window size M
```

```
N events out of M events sent to logstash. Continue sending
```

### PR DESCRIPTION
**Pull request by liketic**
Resolves #5198 . I have to expose the `host` of client.

### CODE REVIEW

**Comment by ruflin** [comment]
jenkins, test it

**Comment by ruflin** [comment]
@liketic Thanks for the contribution. Could you run `make fmt` in the libbeat directory? There seems to be something off with the golang code formatting.

**Comment by liketic** [comment]
@ruflin Thanks! However, I executed `make fmt` under libbeat directory, nothing happened, no any file is not formatted. 😃

**Comment by ruflin** [comment]
Strange. Which Golang version do you have?

I see the following in CI:
```
07:02:57 ./outputs/transport/client.go
07:02:57 Code differs from goimports' style ^
```

**Comment by liketic** [comment]
Thanks @ruflin It's my bad. I have fixed it.

**Comment by ruflin** [comment]
jenkins, test it

**Comment by ruflin** [comment]
@liketic Thanks a lot for the contribution.

**Pull request merged**
