### PR TITLE
Rename migration.enabled to migration_67.enabled

### PR DESCRIPTION
**Pull request by ruflin**
This is to make it more clear this is for the migration from 6.7 to 7.0.

### CODE REVIEW

**Comment by ruflin** [comment]
This will need a rebase and update as soon as https://github.com/elastic/beats/pull/11284 is merged.

**Comment by jsoriano** [comment]
I'd keep `migration` as a group, so we can add more migration options at any point and we can disable all of them with `migration.enabled: false`.

This option could be called `migration.from_6_to_7.enabled`, or `migration.from_6_to_7`. It is not clear to me if  `migration_67` refers to 6.7 or to  "from 6 to 7".

**Comment by webmat** [comment]
I agree with @jsoriano. If his proposal is too verbose, perhaps `migration.6_to_7` ?

**Comment by ruflin** [comment]
No strong opinions on naming. I'm going with `migration.6_to_7.enabled`.

**Comment by jsoriano** [comment]
Failing test seems related to migration.

**Comment by ruflin** [comment]
Yes, already fixed, missed one renaming.

**Comment by ruflin** [comment]
@dedemorton FYI, the config name changed.

**Pull request merged**
