### PR TITLE
Fix k8s metadata issue

### PR DESCRIPTION
**Pull request by ChrsMark**
## What does this PR do?
This PR fixes labels in k8s metadata.  Issues found in 7.6 version: https://discuss.elastic.co/t/how-to-get-kubernetes-node-labels-with-metricbeat/220667/6

~~The proposed solution is to add `kubernetes.labels.*` in all resources (`node`, `namespace` etc) so as to cover cases like `node` metricset. Also when `node`, `namespace`, are part of other resources like `pod` then their labels are part of the sub-resource and not the main resource.~~
 
The proposed solution is to add `kubernetes.labels.*` in `node` resources  so as to cover cases like `node` metricset. Also when `node`, is part of other resources like `pod` then their labels are part of the sub-resource and not the main resource.

Example with `node` as main resource :

```json
{
    "node": {
        "name": "testnode",
        "uid":  "uid",
    },
    "labels": {
        "nodekey": "nodevalue",
    }
}
```

Example with sub-resources:
```json
{
    "pod": {
        "name": "obj",
        "uid":  "uid",
    },
    "namespace": "default",
    "namespace_uid": "uid",
    "namespace_labels": {
            "nskey": "nsvalue",
    },
    "node": {
        "name": "testnode",
        "uid":  "uid",
        "labels": {
            "nodekey": "nodevalue",
        },
    },
    "labels": {
        "foo": "bar",
    },
    "annotations": {
        "app": "production",
    }
}
```

## Why is it important?

Currently the metadata are not populated properly.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works

## How to test this PR locally
TBA

## Related issues

- Relates https://github.com/elastic/beats/pull/16480, #16554, elastic/beats#16558

### CODE REVIEW

**Comment by josharrington** [comment]
Has there been any update on this issue? This is a significant breaking change moving to 7.6.x and it makes it impossible for us to group nodes or pods by kubernetes cluster.

**Comment by ChrsMark** [comment]
@jsoriano @exekias I did some tests with this approach and seems to fix the issue with labels in general while preserving `namespace` schema for now until we decide on a final schema along with a breaking change. Let me know what you think!

**Comment by exekias** [comment]
LGTM!

**Comment by exekias** [comment]
> I am fine with this change for 8.0, but I am not sure of seeing the advantages of backporting this to 7.x versions.

I understand that after the latest updates we are fine with backporting this, right @jsoriano?

**Comment by jsoriano** [comment]
> > I am fine with this change for 8.0, but I am not sure of seeing the advantages of backporting this to 7.x versions.
> 
> I understand that after the latest updates we are fine with backporting this, right @jsoriano?

Looks good now, yes. Thanks!

**Pull request merged**
