### PR TITLE
Cherry-pick #23629 to 7.x: [libbeat] Expose the new Sarama flag 'DisablePAFXFAST' in the Kafka output

### PR DESCRIPTION
**Pull request by faec**
Cherry-pick of PR #23629 to 7.x branch. Original message: 

## What does this PR do?

This PR adds the new flag `enable_krb5_fast` to the Kafka output, which (un)sets the `DisablePAFXFAST` flag added in Sarama 1.27.0. FAST authentication via Sarama can conflict with Active Directory, so this flag is off by default.

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] ~~I have commented my code, particularly in hard-to-understand areas~~
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [ ] ~~I have added tests that prove my fix is effective or that my feature works~~
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Review by urso — APPROVED** [review]

**Comment by faec** [comment]
...the automation thinks this is "most likely a genuine test failure," but it's definitely not related to this change ([failure link](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-23665/1/pipeline)). Not sure yet if the failure is consistent.

**Comment by faec** [comment]
After retrying with no changes to the PR or base branch, the failing test passes, but now a [different test fails](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-23665/2/pipeline).

**Comment by faec** [comment]
After syncing to the latest 7.x branch (albeit with no obviously relevant changes), the preceding tests all pass, but now a new one fails.

[full run](https://beats-ci.elastic.co/blue/organizations/jenkins/Beats%2Fbeats/detail/PR-23665/3/pipeline)
[specific failure](https://beats-ci.elastic.co/job/Beats/job/beats/job/PR-23665/3/)

auditbeat-windows-windows-2019
auditbeat/module/file_integrity.TestActions

```
=== RUN   TestActions
    metricset_test.go:164: 
        	Error Trace:	metricset_test.go:164
        	Error:      	[]string{"deleted"} does not contain "updated"
        	Test:       	TestActions
--- FAIL: TestActions (0.05s)
```

**Comment by faec** [comment]
Hopefully final update: after running the tests again, with no further changes to the PR or base branch, they finally all passed.

**Pull request merged**
