### PR TITLE
Update Go to version 1.7.4

### PR DESCRIPTION
**Pull request by tsg**
This updates:
 * Docker files for tests
 * Travis & appveyor configs
 * packer images

Keeping the "in progress" label until I see the packaging tests green.

### CODE REVIEW

**Comment by tsg** [comment]
jenkins, package it

**Comment by tsg** [comment]
jenkins, package it

**Comment by tsg** [comment]
Packaging tests are failing but looks like due to a Jenkins error: http://build-eu-00.elastic.co/job/beats-package-PR/

I tried packaging locally and seems to work.

**Comment by dliappis** [comment]
jenkins, package it

**Comment by ruflin** [comment]
jenkins, package it

**Pull request merged**
