### PR TITLE
[updatecli][githubrelease] Bump version to 1.19.5

### PR DESCRIPTION
**Pull request by v1v**
# [updatecli][githubrelease] Bump version to 1.19.5

It requires the version to be bumped first in golang-crossbuild project, then a new release will be added to:
https://github.com/elastic/golang-crossbuild/releases/tag/v1.19.5.
Otherwise it will fail until the docker images are available.

## Report

	Source:
		✔ [gomod] Get version in go.mod format(shell)
		✔ [latestGoVersion] Get Latest Go Release(githubrelease)
		✔ [minor] Get minor version in .go-version(shell)

	Condition:
		✔ [dockerTag] Is docker image golang:1.19.5 published(dockerimage)
		✔ [goDefaultVersion-check] Check if defined golang version differs(shell)

	Target:
		⚠ [update-dockerfiles] Update from dockerfiles(file)
		⚠ [update-go-version] Update .go-version(file)
		⚠ [update-golang.ci] Update .golangci.yml(file)
		⚠ [update-gomod] Update go.mod(file)
		⚠ [update-version.asciidoc] Update version.asciidoc(file)

## Changelog

<details><summary>Click to expand</summary>

````
no GitHub Release found for go1.19.5 on "https://github.com/golang/go"


````

</details>

## Remark

This pull request was automatically created using [Updatecli](https://www.updatecli.io).

Please report any issues with this tool [here](https://github.com/updatecli/updatecli/issues/)

### CODE REVIEW

**Comment by gsantoro** [comment]
I know that I am not the chosen reviewer of this PR from the cloud native team but I'll provide my feedback nonetheless.

I think this PR should not be merged in this state. Most of the changes are related to formatting. That means that either the formatting applied by the updatecli tool is different from what we used before or the previous person didn't apply proper formatting. I would like to clarify what's the case before merging this. Either way we should fix the formatting in another Pr and leave this one only for the version upgrade.

**Comment by rdner** [comment]
@belimawr I've looked at the test failures and everything I've seen is about the incorrect Python environment on Windows. I don't now how it's related to the Go version update though.

**Comment by belimawr** [comment]
> @belimawr I've looked at the test failures and everything I've seen is about the incorrect Python environment on Windows. I don't now how it's related to the Go version update though.

It's likely related to a change on how Go looks for executables: https://pkg.go.dev/os/exec#hdr-Executables_in_the_current_directory

From my tests it works well on Linux, I'm finishing my Windows development setup to test/fix it.

**Comment by belimawr** [comment]
Rebase onto `main`, force push.

I believe I fixed the issue with integration tests on ab392696de, it was some Python dependency issue on Windows, installing the requirements when creating the virtualenv fails silently, hence the `pytest` binary was missing. I updated the problematic dependencies and it is working fine on my machine, let's see on CI.

**Comment by v1v** [comment]
https://github.com/elastic/beats/pull/34728 is the PR i just put in place to:
1) Run only for `Auditbeat` with verbose output on Windows
2) Add a few traces to the pytest.go.

Other than that, I'm not an expert on the build system and what's the historical reasons for using `pytest` within the `magefiles` using the `virtualenv`. Please feel free to contribute to the above mentioned PR if needed

**Comment by belimawr** [comment]
My latest findings:
 - There is still a problem to find/execute the `pytest` binary
 - Some path resolution issues seem to be happening
 - I did not manage to reproduce exactly the same issues on my Windows installation.
 - The logs I added on my last commit (https://github.com/elastic/beats/pull/34497/commits/88fc68c21c19c64f895814662f3fbbc1aed37bd3) did not appear on CI.

Some of the errors:
```
[2023-03-02T17:08:43.112Z] ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'C:\\Users\\jenkins\\AppData\\Local\\Temp\\pip-uninstall-9tdzrd_4\\pip.exe'

[2023-03-02T17:08:43.112Z] Consider using the `--user` option or check the permissions.
```

I tried to add the `--user` option, but it broke some GitHub actions

```
[2023-03-02T17:09:23.175Z] warn: failed to upgrade pip (ignoring): running "null\build\ve\windows\Scripts\pip install -U pip" failed with exit code 1Error: exec: "pytest": cannot run executable found relative to current directory
```

The `null` at the beginning of the path is puzzling me.


@v1v Thanks a lot for the help! I believe accessing the the workers, as you mentioned on your PR, is the best course of action . That will allow us to quickly iterate and find/fix the issue. Unfortunately I'm going on PTO and won't be able to look into it. But someone on the team will take over this PR.

**Review by cmacknz — APPROVED** [review]

**Comment by cmacknz** [comment]
Yes, the linter failure is expected here because some of the files edited have pre-existing warnings in them. Merging, not going to wait for the E2E tests to complete.

**Pull request merged**
