### PR TITLE
Disable default prospector and adjust short configs

### LINKED ISSUE #3442: default filebeat.prospectors.paths to be commented out
Currently in filebeat, a fresh out of the box distribution has a default path of `/var/log/*.log` enabled:

```
filebeat.prospectors:

# Each - is a prospector. Most options can be set at the prospector level, so
# you can use different prospectors for various configurations.
# Below are the prospector specific configurations.

- input_type: log

  # Paths that should be crawled and fetched. Glob based paths.
  paths:
    - /var/log/*.log
    #- c:\programdata\elasticsearch\logs\*
```

While this has the benefit/intention of helping making an out-of-the-box good experience for some logs, I would say the any benefits of this are outweighed by the negatives and would instead like to advocate for paths being all commented out by default. The rationale behind this is as follows:

* Folks new to filebeat that want to try it out and start indexing data are likely to have tons of logs from their laptop indexed into Elasticsearch (hopefully their local instance only); the affect is greater if the user starts filebeat as root.
* If a user is required to pick a location to read logs from, it helps make sure they actively think about where to read logs from

### PR DESCRIPTION
**Pull request by tsg**
This does two changes:

* Adds `enabled: false` in the default prospector in the short and long configs.
  (which fixes #3442)
* Updates the short config files of the modules to include the path definitions.
  I think this is better for a "module first" experience, where it gives a bit of
  context on how they work.

This means that the default configuration starts and gives no errors, but also doesn't
publish anything. IMO, this behaviour is fine considering configuration reloading.

### CODE REVIEW

**Comment by tsg** [comment]
We could perhaps check if no prosectors are defined && configuration reloading is disabled, and print an error in that case. But that seems like a nice to have and we don't currently do that.

**Comment by ruflin** [comment]
Good point about the reloading. We actually do this in metricbeat but not in filebeat.

**Comment by tsg** [comment]
I pushed another commit that prints an error if all modules & prospectors are disable and config reloading is disabled (the code was there, was just not looking at the enabled flag).

[This](https://github.com/tsg/beats/blob/41900fd0f5a65a7114338894c2af1a998d75e2d1/filebeat/beater/filebeat.go#L69) is the error message. I think it's clear enough for now, later we can make it link to the docs or a FAQ, but for the moment I worry about adding other suggestions to it.

**Comment by dedemorton** [comment]
@tsg Shouldn't the filebeat prospector reference doc also be updated to show the `enabled` option?

**Comment by ruflin** [comment]
@dedemorton Yes, I probably missed that when I introduced Enabled :-(

**Pull request merged**
