### PR TITLE
Add float tags to fix broken topic structure

### PR DESCRIPTION
**Pull request by dedemorton**
Fixes broken structure reported in the discussion here: https://github.com/elastic/cloud/issues/103125#issuecomment-1150467643

### CODE REVIEW

**Comment by dedemorton** [comment]
@matschaffer Here's the fix.

**Review by matschaffer — APPROVED** [review]
Not sure where to check the docs preview, but figured good to ✅ for now

**Comment by dedemorton** [comment]
|Not sure where to check the docs preview

For future reference...you'll find the preview link in the PR after the build completes:
image

From there, you can navigate to the topics that have changed.

**Comment by matschaffer** [comment]
Ha! Thanks. What's funny is a did a cmd+f on the checks list thinking it would be there. But since the badge is an image I glossed over it 🤦🏻

**Pull request merged**
