### PR TITLE
Backport config env var replacement, topbeat username/cmdline

### PR DESCRIPTION
**Pull request by andrewkroh**
Backport features to v1.2

- Add ability to override configuration settings using environment variables #114
- Add the command line used to start processes #533
- Add username to processes #845

### CODE REVIEW

**Comment by monicasarbu** [comment]
waiting to be green

**Comment by monicasarbu** [comment]
@andrewkroh Ready for review?

**Comment by andrewkroh** [comment]
I manually re-ran the Jenkins build. Sucess - http://build-eu-00.elastic.co/job/Beats-PR/825/

This PR is ready for review.

**Comment by ruflin** [comment]
LGTM. @monicasarbu Do you also want to have a look?

**Pull request merged**
