### PR TITLE
[Packetbeat] [HTTP] Option to use binary datatype for bodies 

### PR DESCRIPTION
**Pull request by olimpias**
Solves #12963

With the `store_raw_with_blob` configuration, raw data is going to stored to ES in base64 and as binary.

### CODE REVIEW

**Comment by blakerouse** [comment]
@olimpias We are in the process of cleanup some old PR's, noticed this hasn't had any activity in a while. Are you still interested in getting this merged? Would you be able to rebase with latest master?

**Comment by olimpias** [comment]
@blakerouse I updated my MR with the master branch.

**Comment by blakerouse** [comment]
ok to test

**Comment by olimpias** [comment]
@blakerouse , I guess this fails are not due to my changes. Am I right?

**Comment by blakerouse** [comment]
@olimpias They do seem unrelated.

**Pull request closed without merging**
