### PR TITLE
fix(docs): Undocumented ssl.key_passphrase option

### PR DESCRIPTION
**Pull request by joostdecock**
Added documentation for an undocumented option: Use of an encrypted client certificate key

If you're using an encrypted certificate for X509 authentication in the Kafka module, the kafka module in metricbeat throws a `no PEM blocks` error.
Obviously, we need to configure the key's passphrase somewhere, but there's no obvious way to do that.

I dug around a little in the libbeat source code to figure out how it's configuring TLS, and sure enough, you can just set the `tls.key_passphrase` option.

So I've updated the docs to add this parameter, and save others the trouble of figuring this out on their own.

Hope this helps.

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by bmorelli25** [comment]
@elasticmachine, run elasticsearch-ci/docs

**Review by bmorelli25 — APPROVED** [review]
Thanks, @joostdecock!

LGTM, but I'll let @dedemorton chime in just to be sure.

**Comment by bmorelli25** [comment]
jenkins, test this please

**Comment by dedemorton** [comment]
@joostdecock Updating this is a bit more difficult than it appears on the surface. I'll make the fix and push it to you PR (if I'm able).

**Comment by dedemorton** [comment]
Ok, that should do the trick. The gist is that you need to update the config file in the _meta directory under the module then run `make update` or `mage update` to update the generated files.

But it's totally OK for external folks to do what you did. Thanks again for the contribution!

**Comment by joostdecock** [comment]
Thank you, golang is totally alien to me, so I kept it to docs changes 🙈

I bought a golang course the other day because I felt so inept 😂 since I have more PR plans (I need SSL support in the metricbeat zookeeper module) this advice will come in handy 👍

**Comment by kvch** [comment]
jenkins run tests

**Comment by kvch** [comment]
This PR is correct. For the record, if we add this to the Kafka module configuration, we should update all module configuration to stay consistent. I am not saying we should address it in this PR. We should take the time to address it in a later PR.

**Review by kvch — APPROVED** [review]

**Comment by dedemorton** [comment]
jenkins, test this please

**Comment by dedemorton** [comment]
Sorry this got lost in my backlog. I will merge if CI passes and open an issue to get the other modules updated.

**Comment by dedemorton** [comment]
jenkins, test this please

**Comment by dedemorton** [comment]
Replaced by https://github.com/elastic/beats/pull/23826.

**Pull request closed without merging**
