### PR TITLE
[Ingest Manager] Prevent closing closed reader

### PR DESCRIPTION
**Pull request by michalpristas**
## What does this PR do?

With #20127 config reader is closed on read. no need to do that in code. removes all occurences of close

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by mdelapenya** [comment]
I thing this change is causing the e2e tests to fail: https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/91/pipeline#step-240-log-144

>[2020-07-24T06:04:44.021Z] fail to enroll: acquiring metadata failed: close /elastic-agent-8.0.0-SNAPSHOT-linux-x86_64/fleet.yml: file already closed
[2020-07-24T06:04:44.283Z] time="2020-07-24T06:04:44Z" level=error msg="Could not execute command in container" command="[elastic-agent enroll http://kibana:5601 dm5oc2YzTUJTdTFjYTVBYWRRZm46dkxScTQ2ODJTR2V6RzRJRUN0MC1vUQ== -f --insecure]" error="Could not run compose file: [/var/lib/jenkins/workspace/e2e-tests_e2e-testing-mbp_master/.op/compose/profiles/ingest-manager/docker-compose.yml /var/lib/jenkins/workspace/e2e-tests_e2e-testing-mbp_master/.op/compose/services/centos/docker-compose.yml] - Local Docker compose exited abnormally whilst running docker-compose: [exec -T centos elastic-agent enroll http://kibana:5601 dm5oc2YzTUJTdTFjYTVBYWRRZm46dkxScTQ2ODJTR2V6RzRJRUN0MC1vUQ== -f --insecure]. exit status 1" service=centos

We download the elastic-agent TAR file and mount a volume in the container so that we can untar it in the running Centos container.

And for the stand-alone mode, the elastic-agent docker image fails too: https://beats-ci.elastic.co/blue/organizations/jenkins/e2e-tests%2Fe2e-testing-mbp/detail/master/91/pipeline/207#step-240-log-144

**Comment by michalpristas** [comment]
@mdelapenya the error you're describing is cause by https://github.com/elastic/beats/pull/20127 this one should fix it.

**Comment by mdelapenya** [comment]
Cool then! Do you know when the build artifacts will be generated?

**Comment by ph** [comment]
The release manager build the artifact daily, but we have a ci job that build beats and elastic-agent on every commit.

**Comment by mdelapenya** [comment]
This URL hasn't changed for days: https://artifacts-api.elastic.co/v1/search/8.0.0-SNAPSHOT/elastic-agent

Do you know where are we pushing those commit-based artifacts (docker image and binaries)?

**Comment by ph** [comment]
@mdelapenya Yes, you are right, looking at CI it's been [failing for a few days](https://internal-ci.elastic.co/job/elastic+release-manager+master+unified-snapshot/). There a build going on.

**Comment by ph** [comment]
@mdelapenya It was failing because of beats 04:50:47 org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':buildBeatsSnapshot'. Next build should fix the issue it include 59ddf55bf4ad27ac249d5e4940de20df28bf6312

**Pull request merged**
