### PR TITLE
Include selector in DEBUG log

### LINKED ISSUE #5042: Include selector name in debug output
It would be useful if the debug output included the selector name so you the selector for each log line and you can more easily update your `-d` filter to include/exclude them:

This:
```
2017/08/29 09:13:28.898295 server.go:85: DBG Request: URI=/v1/errors, method=POST, content-length=156
```
would be
```
2017/08/29 09:13:28.898295 server.go:85: DBG handler Request: URI=/v1/errors, method=POST, content-length=156
```

if the call was
```
logp.Debug("handler", "Request...")
```

Potential alternatives are:
```
2017/08/29 09:13:28.898295 server.go:85: DBG/handler Request: URI=/v1/errors, method=POST, content-length=156
```

```
2017/08/29 09:13:28.898295 server.go:85: DBG:handler Request: URI=/v1/errors, method=POST, content-length=156
```

### PR DESCRIPTION
**Pull request by liketic**
Closes #5042

### CODE REVIEW

**Comment by ruflin** [comment]
LGTM. I'm kind of surprised it does not break our system tests as quite a few of these depend on log line messages.

**Comment by ruflin** [comment]
jenkins, test it

**Comment by roncohen** [comment]
Looks good. 
@andrewkroh suggested a variation, which I like, here: https://github.com/elastic/beats/issues/5042#issuecomment-336131598

**Comment by liketic** [comment]
@roncohen I updated the PR, thanks for your reviewing.

**Comment by ruflin** [comment]
jenkins, test it

**Comment by andrewkroh** [comment]
Looks like there is a [test failure](https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-linux/1765/beat=libbeat,label=ubuntu/artifact/src/github.com/elastic/beats/libbeat/build/system-tests/run/test_cmd.TestCommands.test_setup_template/mockbeat.log/*view*/). Don't have time to investigate now.

@ruflin The generator test failed too. But that can't be related to this change, can it?

**Comment by liketic** [comment]
@andrewkroh Thanks. I cannot fun testsuite on my local environment. Everytime when I run:
`make testsuite` always got a lot of errors.

**Comment by ruflin** [comment]
@andrewkroh All seems green now. Ok for me to merge.

**Pull request merged**
