### PR TITLE
[Ingest Manager] PGP check pypass docs

### PR DESCRIPTION
**Pull request by michalpristas**
## What does this PR do?

Introduces Development FAQ section in config describing basic problems user might run into

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by ph** [comment]
@dedemorton is this in the right place?

**Comment by dedemorton** [comment]
> @dedemorton is this in the right place?

No, I don't think. Is this something that end users will ever need to do? It sounds like this information is intended for people who are developing code and contributing to the project. I would expect to see this sort of information in a contributing guide, not the user guide.

**Comment by dedemorton** [comment]
@michalpristas Are you planning to move this content? Can we close this PR?

**Comment by dedemorton** [comment]
I'm going to remove myself as a reviewer from this PR so it doesn't show up on my list. Feel free to mention me if you need further input from me. Thanks!

**Comment by michalpristas** [comment]
we have troubleshooting section, closing

**Pull request closed without merging**
