### PR TITLE
Fix changelog and add documentation for containers.paths

### PR DESCRIPTION
**Pull request by jsoriano**
Follow up of #10687

### CODE REVIEW

**Comment by jsoriano** [comment]
jenkins test this again please

**Comment by jsoriano** [comment]
jenkins, test this

**Comment by vjsamuel** [comment]
@jsoriano thanks much for this :)

**Comment by AntonioMeireles** [comment]
hi all!

is there any hope of having this and #10687 backported to 6.x beats stream ?

thanks in advance!

**Comment by jsoriano** [comment]
@AntonioMeireles in principle these changes will only be available in 7.X, there are still some more things to better support CRI-O.

**Comment by AntonioMeireles** [comment]
@jsoref many thanks for your quick reply. 

FWIW, IMHO, support for cri-o (and perhaps containerd, and in general being agnostic to CRI runtimes in use) is absolutely critical in order for beats to be truly relevant and successful in the k8s space, as docker is less used every day, so the sooner it gets GA the better ;-)

**Comment by jsoref** [comment]
@AntonioMeireles: did you reference the wrong account?

**Pull request merged**
