### PR TITLE
Update golang/x/net to release-branch.go1.9

### PR DESCRIPTION
**Pull request by cyrilleverrier**

### CODE REVIEW

**Comment by ruflin** [comment]
jenkins, test it

**Comment by ruflin** [comment]
I will need to do some more investigation on why this does not work on Windows.

**Comment by cyrilleverrier** [comment]
Probably a different behaviour with end of line?
Maybe the python tests needs \r\n on Windows ?

**Comment by cyrilleverrier** [comment]
I merged PR#6340 in this PR. It fails on Windows because of this.

**Comment by ruflin** [comment]
@cyrilleverrier What is the reason you merged the two PR's? Are they related / coupled to each other?

**Comment by cyrilleverrier** [comment]
@ruflin Yes. the new version of golang/x/net  does not compile with the old version of golang/x/text

**Comment by ruflin** [comment]
@cyrilleverrier https://github.com/elastic/beats/pull/6340 is merged. Can you rebase?

**Comment by cyrilleverrier** [comment]
@ruflin done!

**Comment by ruflin** [comment]
jenkins, test it

**Comment by cyrilleverrier** [comment]
@ruflin One of the test failed on Darwin platform.

The callstack suggests that a `race detected during execution of test`
https://beats-ci.elastic.co/job/elastic+beats+pull-request+multijob-darwin/653/beat=filebeat,label=macosx/artifact/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_harvester.Test.test_close_timeout/filebeat.log

**Comment by ruflin** [comment]
I would be kind of surprised if it's related to the lib change at the same time don't want to take any chances here. It seems to be an issue related to the shutdown. I'm aware we had issues around this in the past but thought we fixed them.

Post the stacktrace here in case the jenkins data is removed:

```
==================
2018-02-16T01:43:34.294-0800	DEBUG	[harvester]	_obj/harvester.go:517	Stopping harvester for file: /private/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-darwin/beat/filebeat/label/macosx/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_harvester.Test.test_close_timeout/log/test.log
WARNING: DATA RACE
Write at 0x00c420250bdc by goroutine 61:
  internal/race.Write()
      /var/lib/jenkins/.gvm/versions/go1.9.4.darwin.amd64/src/internal/race/race.go:41 +0x38
  sync.(*WaitGroup).Wait()
      /var/lib/jenkins/.gvm/versions/go1.9.4.darwin.amd64/src/sync/waitgroup.go:129 +0xf4
  github.com/elastic/beats/filebeat/input/log.(*Harvester).Stop()
      github.com/elastic/beats/filebeat/input/log/_obj/harvester.go:353 +0x7a
  github.com/elastic/beats/filebeat/harvester.(*Registry).Stop.func2()
      github.com/elastic/beats/filebeat/harvester/_obj/registry.go:59 +0x56

Previous read at 0x00c420250bdc by goroutine 59:
  internal/race.Read()
      /var/lib/jenkins/.gvm/versions/go1.9.4.darwin.amd64/src/internal/race/race.go:37 +0x38
  sync.(*WaitGroup).Add()
      /var/lib/jenkins/.gvm/versions/go1.9.4.darwin.amd64/src/sync/waitgroup.go:71 +0x16f
  github.com/elastic/beats/filebeat/input/log.(*Harvester).Run()
      github.com/elastic/beats/filebeat/input/log/_obj/harvester.go:169 +0x15f
  github.com/elastic/beats/filebeat/harvester.(*Registry).Start.func1()
      github.com/elastic/beats/filebeat/harvester/_obj/registry.go:92 +0xd2

Goroutine 61 (running) created at:
  github.com/elastic/beats/filebeat/harvester.(*Registry).Stop()
      github.com/elastic/beats/filebeat/harvester/_obj/registry.go:57 +0x1c3
  github.com/elastic/beats/filebeat/input/log.(*Input).Stop()
      github.com/elastic/beats/filebeat/input/log/_obj/input.go:765 +0x70
  github.com/elastic/beats/filebeat/input.(*Runner).stop()
      github.com/elastic/beats/filebeat/input/_obj/input.go:163 +0x193
2018-02-16T01:43:34.295-0800	DEBUG	[harvester]	_obj/harvester.go:525	Closing file: /private/var/lib/jenkins/workspace/elastic+beats+pull-request+multijob-darwin/beat/filebeat/label/macosx/src/github.com/elastic/beats/filebeat/build/system-tests/run/test_harvester.Test.test_close_timeout/log/test.log
  github.com/elastic/beats/filebeat/input.(*Runner).Start.func1.1()
      github.com/elastic/beats/filebeat/input/_obj/input.go:112 +0x62
  github.com/elastic/beats/filebeat/input.(*Runner).Start.func1()
      github.com/elastic/beats/filebeat/input/_obj/input.go:118 +0x9d

Goroutine 59 (running) created at:
  github.com/elastic/beats/filebeat/harvester.(*Registry).Start()
      github.com/elastic/beats/filebeat/harvester/_obj/registry.go:82 +0x1b7
  github.com/elastic/beats/filebeat/input/log.(*Input).startHarvester()
      github.com/elastic/beats/filebeat/input/log/_obj/input.go:724 +0x3e4
  github.com/elastic/beats/filebeat/input/log.(*Input).harvestExistingFile()
      github.com/elastic/beats/filebeat/input/log/_obj/input.go:533 +0x1019
  github.com/elastic/beats/filebeat/input/log.(*Input).scan()
      github.com/elastic/beats/filebeat/input/log/_obj/input.go:520 +0x9c4
  github.com/elastic/beats/filebeat/input/log.(*Input).Run()
      github.com/elastic/beats/filebeat/input/log/_obj/input.go:171 +0x119
  github.com/elastic/beats/filebeat/input.(*Runner).Run()
      github.com/elastic/beats/filebeat/input/_obj/input.go:142 +0x160
  github.com/elastic/beats/filebeat/input.(*Runner).Start.func1()
      github.com/elastic/beats/filebeat/input/_obj/input.go:117 +0x9c
==================
```

@adriansr @ph Any idea as you guys touched most of this code recently?

**Comment by adriansr** [comment]
I've been inspecting the data race and seems a trivial issue (although hard to reproduce). A sync.WaitGroup is used incorrectly in filebeat's log/Harvester.

It is not related at all with this PR so go ahead and merge it. I will open a separate PR to fix the race condition.

**Comment by cyrilleverrier** [comment]
@ruflin : I just rebased the branch against the latest commit on master branch

**Comment by ruflin** [comment]
jenkins, test it

**Comment by ruflin** [comment]
@cyrilleverrier Thanks a lot for making this happen. Sorry that it took a bit longer on our side.

**Comment by cyrilleverrier** [comment]
@ruflin thank you for merging this PR, and I am glad that the system tests revealed https://github.com/elastic/beats/pull/6563

**Pull request merged**
