### PR TITLE
IIS and MYSQL  expected json logfile update

### PR DESCRIPTION
**Pull request by ishleenk17**
- Bug

## What does this PR do?

This PR updates the expected json files for mysql and iis as there was a change in the way grok processing is done by ES.

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

- Closes https://github.com/elastic/beats/issues/35133
- Relates https://github.com/elastic/elasticsearch/issues/92092

### CODE REVIEW

**Comment by ishleenk17** [comment]
> Our team is investigating the metricbeat failures, they are due the old Debian version. The repository was archived and the tests cannot install cockroachdb.
> 
> cc @michalpristas

@rdner : Since, this is unrelated issue, can we bypass the CI/CD and commit the change once we get approval from integrations.

**Comment by rdner** [comment]
@ishleenk17 Michal merged his fix and merged the `main` into your PR, the CI should pass now. Let's wait.

**Comment by ishleenk17** [comment]
The snapshot.yml has been updated to trigger the appropriate CI/CD (https://github.com/elastic/beats/pull/34589) .
It's not related to the IIS/MYSQL-specific changes

**Review by rdner — APPROVED** [review]

**Comment by rdner** [comment]
> The snapshot.yml has been updated to trigger the appropriate CI/CD (https://github.com/elastic/beats/pull/34589) .
> It's not related to the IIS/MYSQL-specific changes

@ishleenk17 Please read the comments above. There was an issue unrelated to your changes. Then it was fixed and fix was merged to your branch (this PR). That's why the tests are green now. No need to by pass anything now.

**Pull request merged**
