### PR TITLE
[Azure] [Billing] Switch to Consumption API 1.1.0 with patches

### PR DESCRIPTION
**Pull request by zmoog**
## Proposed commit message

Bump the following package versions to patch the Consumption SDK 1.1.0:

- Bump `armconsumption` package version from 1.0.0+patch to 1.1.0+patch
- Bump `azcore` package version from 1.4.0 to 1.9.0 to use the URL encoder helper used in the Azure SDK

The Consumption SDK does not correctly handle query parameters in the 'next link' when the dataset in Azure requires pagination. See https://github.com/elastic/integrations/issues/7478#issuecomment-1819391736 for more details.

We manage the [patches](https://github.com/elastic/azure-sdk-for-go/commits/sdk/resourcemanager/consumption/armconsumption/v1.1.0-elastic) to the Azure SDK for Go in the repository fork. To learn more about the patches and the fork, see https://github.com/elastic/beats/issues/37151

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] ~~I have made corresponding changes to the documentation~~
- [ ] ~~I have made corresponding change to the default configuration files~~
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## How to test this PR locally

Our Azure accounts does not have enough usage details items to trigger pagination; the default page size is 1000 items.

You can trigger the pagination by setting the `top` parameter to a low value (for example, 10 items) when in the pager at https://github.com/elastic/beats/blob/a9ac1d13a94be34fab1b5c3cce0dced41113a047/x-pack/metricbeat/module/azure/billing/service.go#L178-L184

## Related issues

- Closes https://github.com/elastic/integrations/issues/7478
- Relates https://github.com/elastic/beats/issues/37151

### CODE REVIEW

**Comment by shmsr** [comment]
The changes here look good. I'll take a look at the patches. Can you please add the changelog entry?

**Comment by gpop63** [comment]
I did replicate this by setting `Top` param in `UsageDetailsClientListOptions` to 10 or 100 to enable pagination (the way @zmoog told me to). Used modern account which I believe uses MCA agreement.

```json
{"log.level":"error","@timestamp":"2023-11-28T00:32:41.751+0200","log.origin":{"file.name":"module/wrapper.go","file.line":256},"message":"Error fetching data for metricset azure.billing: error retrieving usage information: retrieving usage details failed in client: GET https://management.azure.com/subscriptions/REDACTED/providers/Microsoft.Consumption/usageDetails\n--------------------------------------------------------------------------------\nRESPONSE 400: 400 Bad Request\nERROR CODE: MissingApiVersionParameter\n--------------------------------------------------------------------------------\n{\n  \"error\": {\n    \"code\": \"MissingApiVersionParameter\",\n    \"message\": \"The api-version query parameter (?api-version=) is required for all requests.\"\n  }\n}\n--------------------------------------------------------------------------------\n","service.name":"metricbeat","ecs.version":"1.6.0"}
```

I tried setting the `Skiptoken` parameter by parsing `nextPage.NextLink` to see if this is a viable solution, but this does nothing.

**Comment by muthu-mps** [comment]
> I did replicate this by setting `Top` param in `UsageDetailsClientListOptions` to 10 or 100 to enable pagination (the way @zmoog told me to). Used modern account which I believe uses MCA agreement.
> 
> ```json
> {"log.level":"error","@timestamp":"2023-11-28T00:32:41.751+0200","log.origin":{"file.name":"module/wrapper.go","file.line":256},"message":"Error fetching data for metricset azure.billing: error retrieving usage information: retrieving usage details failed in client: GET https://management.azure.com/subscriptions/REDACTED/providers/Microsoft.Consumption/usageDetails\n--------------------------------------------------------------------------------\nRESPONSE 400: 400 Bad Request\nERROR CODE: MissingApiVersionParameter\n--------------------------------------------------------------------------------\n{\n  \"error\": {\n    \"code\": \"MissingApiVersionParameter\",\n    \"message\": \"The api-version query parameter (?api-version=) is required for all requests.\"\n  }\n}\n--------------------------------------------------------------------------------\n","service.name":"metricbeat","ecs.version":"1.6.0"}
> ```
> 
> I tried setting the `Skiptoken` parameter by parsing `nextPage.NextLink` to see if this is a viable solution, but this does nothing.

@gpop63 - Thanks for verifying the changes.
- I have tried with multiple scenarios to verify the expected behaviour and it works as mentioned above.
- I am getting the error you have mentioned only when I run the pagination scenario against the main branch.
- Can you please double check the code which you have been using to test is from this PR?

**Comment by muthu-mps** [comment]
> @muthu-mps this fix is great, I was saying I was able to replicate this issue (using the main branch). So the changes here fix it.

Thanks @gpop63

**Comment by muthu-mps** [comment]
### Azure Billing Metrics
#### Verified the following scenarios
- Pulled the latest code from this PR.
- Configured the `EA account` in the Azure(billing) metricbeat module.
- Verified the metrics collection for billing account with default settings. It works fine.
- configured the `Top parameter` as suggested to test the pagination use-case and verified the metrics collection and it works as expected.
- Checked whether the data is pulled for the previous date.
- The same has been verified against the `MCA account` and working as expected.
#### Issue Replication
- The issue is reproducible when doing the same against the main branch.

**Review by muthu-mps — APPROVED** [review]
LGTM!

**Comment by zmoog** [comment]
Hey friends at @elastic/beats-tech-leads, we need your review on this change because it affects  `go.mod` ^^

**Comment by zmoog** [comment]
We're tageting the upcoming 8.12.0 and 8.11.2.

**Comment by zmoog** [comment]
> i would like to tidy up the tag on the fork so the version is a little better defined in the go.mod here.

On it!

**Comment by zmoog** [comment]
@tommyers-elastic, I made the following changes:

- Created a PR to merge the patches into our `sdk/.../v1.1.0-elastic` branch (I kept the commits with the two patches intact).
- Added a `v1.1.0-elastic` tag on the last commit.
- Updated the `go.mod` file to target the `v1.1.0-elastic` tag.

You now can:

- Review the PR https://github.com/elastic/azure-sdk-for-go/pull/1 on the Azure SDK fork.
- Review this PR

**Review by tommyers-elastic — APPROVED** [review]
LGTM

**Comment by JuddDeaver** [comment]
@zmoog I don't see any actual version tags applied to this PR. I have support case 01523048 where they are hitting [this known issue](https://support.elastic.dev/knowledge/view/fb1a3337). Has his fix made it into the product, and what version?

**Comment by zmoog** [comment]
The fix has been released in Beats and Elastic Agent version [8.11.2](https://www.elastic.co/guide/en/beats/libbeat/current/release-notes-8.11.2.html).

**Comment by zmoog** [comment]
@JuddDeaver, which tags should I apply to the PR to properly communicate this info?

**Comment by JuddDeaver** [comment]
In that case I think adding the `v8.11.2` label would typically be used to indicate the version it was merged. I thought this was usually added by automation, but that might not be an accurate assumption for this repo.

**Comment by zmoog** [comment]
Yeah, it's not a common practice for this repo, but conveying this information with tags/labels or a last comment with a recap makes sense. 

I'll do one or the other in current and future PRs.

Thanks for the heads up.

**Pull request merged**
