### PR TITLE
[Elastic-Agent] Use data subfolder as default for process logs

### PR DESCRIPTION
**Pull request by michalpristas**
## What does this PR do?

This PR changes default path for process logs from /var/log to {path.data}/logs

this will conflict with paths CLI PR will need to rebase then

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by michalpristas** [comment]
Jenkins test this

**Comment by ruflin** [comment]
Will this have any effect on where the logs from the processes go? Would be nice if it does as currently it is hard to find the logs for metricbeat for example.

**Comment by michalpristas** [comment]
@ruflin yes this changes the location and logs will go to `{where_agent_is_installed}/data/logs/{pipeline_name}`

e.g: `/Users/me/agent/data/logs/default`

**Comment by ph** [comment]
Is there any reason why we do not use `{where_agent_is_installed}/data/{pipeline_name}/logs` ?

**Comment by michalpristas** [comment]
@ph i can change it like this. i did it in this way so we end up with data containing
`download` `install` `logs`
instead of
`download` `install` `default` `something-pretty` `something-else`

**Comment by ruflin** [comment]
pipeline = output name? If yes, sounds confusing to me that we talk in the config about outputs but here about pipline?

**Comment by michalpristas** [comment]
we call it still PipelineID internally in the code, but what it is it is just and output type out of config e.g default/monitoring/elasticsearch/

**Comment by ruflin** [comment]
Is it `type` or the name of the output? https://github.com/elastic/beats/blob/master/x-pack/elastic-agent/elastic-agent.yml#L10 The part that is here `default` or `elasticsearch`

**Comment by michalpristas** [comment]
in the config you posted it would be default. it is the same value you use when specifying output using `use_output` in streams. 
my bad, sorry for confusion i need to slow down window switching

**Comment by ph** [comment]
Its is the `output name` that create an internal pipeline, we ccould do some renaming internally so it's more consistant. but I don't think its a priority now.

**Comment by ph** [comment]
> @ph i can change it like this. i did it in this way so we end up with data containing
> download install logs
> instead of
> download install default something-pretty something-else


I see your point and I think it's valid, @ruflin wdyt?

**Comment by ruflin** [comment]
On your last comment, no preference as long as the logs are easy accessible.

**Comment by ph** [comment]
@michalpristas let's keep it your way :)

**Pull request merged**
