### PR TITLE
Feature panw endreason

### PR DESCRIPTION
**Pull request by dainok**
## What does this PR do?

PANW firewalls expone why a session is ended (endreason). Currenlty it's not tracked.

## Why is it important?

End reason is important to track down why a specific session is ended (timeout, rst from client/server...)

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

### CODE REVIEW

**Comment by dainok** [comment]
Done, thank you @andrewkroh 
Anything I can do regarding 7.7.1 update?

**Comment by adriansr** [comment]
Thanks for your contribution!

This PR needs a rebase on master and re-generation of the _-expected.json_ files.

**Comment by andrewkroh** [comment]
jenkins run tests

**Comment by webmat** [comment]
Perhaps this could be migrated to the new ECS field `event.reason`?

**Comment by dainok** [comment]
Totally agree. Should I rewrite the PR? Or can you notify the PANW team?

**Comment by webmat** [comment]
Simplest approach here would be to open a new PR that now also populates `event.reason`.

Since this PR was already merged, I would not remove the `panw.panos.endreason` field in the new PR, but I'd bring this up in the PR description. If this is not yet released, perhaps we can remove it, and we'll discuss on the new PR :-)

Thanks @dainok

**Pull request merged**
