### PR TITLE
Validate Source IP "LOCAL" or "Unknown" in Windows Security Logs

### PR DESCRIPTION
**Pull request by MakoWish**
## What does this PR do?

Some security events contain a source IP address of "LOCAL" or "Unknown" which are not valid IP addresses. This PR will correct the processing of events containing one of those values. 

## Why is it important?

This bug causes mapping exceptions and prevents these events from being ingested. 

## Checklist

- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Related issues

-fixes [#19627](https://github.com/elastic/beats/issues/19627)

### CODE REVIEW

**Comment by MakoWish** [comment]
Can we backport this as a bug fix?

**Comment by efd6** [comment]
@MakoWish Please sign the CLA so that we can take a look at this.

**Comment by MakoWish** [comment]
> @MakoWish Please sign the CLA so that we can take a look at this.

Hi @efd6 , I have already done that.

**Comment by efd6** [comment]
Your GitHub handle is recognised as having signed the CLA but this PR does not appear to be signed. Would you please check that the email address in the commits that you authored matches the email address that you used when you signed the CLA; there are two identities in these commits and I suspect that the second may not be a CLA-known identity.

**Comment by MakoWish** [comment]
I signed the CLA with my personal email, but I would prefer not to use that on commits. The commits should be configured with the GH "no reply" account. Is there a way to add th "no reply" account "26614684+MakoWish@users.noreply.github.com" to the CLA?

**Comment by efd6** [comment]
Can you try resigning with that email address?

**Comment by MakoWish** [comment]
Having a hard time changing [this one](https://github.com/elastic/beats/commit/d87ec5b2f6526bc0e3448264f38c1f4d8c69d8c8). Have any tips on how to do that?

**Comment by efd6** [comment]
Thanks for fixing the CLA signing. This has brought in many changes that are unrelated to the fix here; are you able to reduce it down to just the changes that you are needing to make please.

**Comment by MakoWish** [comment]
Wasn't sure how to remove the changes I inadvertently added, and accidentally removed everything. I will open a new PR with just the changes for the source IP issue.

**Pull request closed without merging**
