### PR TITLE
[Filebeat] Enable dynamic inputs (TCP) for Cisco syslog modules

### LINKED ISSUE #26118: [Filebeat][Cisco] Allow for TCP syslog input
**Describe the enhancement:**
Allow the Filebeat Cisco syslog modules to use TCP

**Describe a specific use case for the enhancement or feature:**
Currently the Filebeat Cisco syslog modules are hard-coded to using UDP, however most Cisco equipment that can do syslog output, can be configured to use TCP. It would be ideal if you could switch between UDP and TCP input for the Cisco Filebeat syslog modules.

### LINKED ISSUE #28821: Update Filebeat's Cisco > ASA config to reflect UDP
In https://github.com/elastic/beats/pull/13286 we switched Filebeat's Cisco ASA dataset to use a regular `udp` input instead of a `syslog` input, however, the `cisco.yml` still makes it look like we're using `syslog`:

```YAML
  asa:
    enabled: true

    # Set which input to use between syslog (default) or file.
    var.input: syslog

    # The interface to listen to UDP based syslog traffic. Defaults to
    # localhost. Set to 0.0.0.0 to bind to all available interfaces.
    var.syslog_host: localhost

    # The UDP port to listen for syslog traffic. Defaults to 9001.
    var.syslog_port: 9001
```
`.../module/cisco/asa/config/input.yml`
```YAML
{{ if eq .input "syslog" }}

type: udp
udp:
host: "{{.syslog_host}}:{{.syslog_port}}"
```

This may cause some confusion and it'd be helpful to adjust settings/comments to reflect the use of a `type: udp` input.

### PR DESCRIPTION
**Pull request by legoguy1000**
## What does this PR do?

Enables the Cisco filesets to use TCP or UDP for syslog input.

## Why is it important?

TCP is more reliable than UDP and cisco devices can use both and shouldn't be limited to UDP.

## Checklist

- [X] My code follows the style guidelines of this project
- [X] I have commented my code, particularly in hard-to-understand areas
- [X] I have made corresponding changes to the documentation
- [X] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [x] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- tested cisco asa with both udp & tcp using https://github.com/leehinman/spigot to generate traffic

## How to test this PR locally
```
cd beats/x-pack/filebeat
TESTING_FILEBEAT_MODULES=cisco mage -v pythonIntegTest
```

## Related issues

- Closes #26118 
- Closes #28821

### CODE REVIEW

**Comment by legoguy1000** [comment]
@andrewkroh could u take a look at this when you get a chance.  I think this is the best way to enable backwards compatibility with the existing syslog inputs but if there are other thoughts, let me know.

**Comment by legoguy1000** [comment]
I also think IDK if i need additional sample data to account for the syslog vs tcp/udp inputs??

**Review by leehinman — APPROVED** [review]

**Comment by legoguy1000** [comment]
@leehinman Anything more need to be done with this PR?

**Comment by leehinman** [comment]
> @leehinman Anything more need to be done with this PR?

nope.  Thanks for the reminder.

**Comment by andrewkroh** [comment]
This causes an issue for users with existing ASA and FTD configs that upgrade. The existing config contains `var.input: syslog`, but this fails under the new templates that are specific to the udp and tcp input types. I think to keep compatibility that the Go template needs to retain an `{{ if eq .input "syslog" }}`.

```
- module: cisco
  asa:
    enabled: true
    var.input: syslog
    var.syslog_host: 0.0.0.0
    var.syslog_port: 5144
    var.log_level: 7
  ftd:
    enabled: true
    var.input: syslog
    var.syslog_host: 0.0.0.0
    var.syslog_port: 5145
    var.log_level: 7
```

**Comment by legoguy1000** [comment]
If I recall the thought process, since syslog was the default for `var.input` if they didn't actually set the setting, when they upgraded it would use the new default of udp which is what it was already using. That being said, I see your point.

**Comment by andrewkroh** [comment]
I've added back an `if` in https://github.com/elastic/beats/pull/30072.

**Pull request merged**
