### PR TITLE
Add more progress logging to the packer

### PR DESCRIPTION
**Pull request by tsg**
This makes it easier for external runners (like gradle) to report
progress on our builds.

### CODE REVIEW

**Comment by tsg** [comment]
jenkins, package it

**Comment by ruflin** [comment]
LGTM

**Comment by tsg** [comment]
Packaging tests are green: http://build-eu-00.elastic.co/view/Beats/job/beats-package-PR/12/

**Comment by ruflin** [comment]
Merging as changes or only related to packaging. There is a redis metricset test failing. Flaky?

**Pull request merged**
