### PR TITLE
Fix packaging dynamic step upload

### PR DESCRIPTION
**Pull request by oakrizan**
## Proposed commit message
Migration of beats to Buildkite - fixed dynamic step upload for packaging step

Links to BK builds:
Filebeat: https://buildkite.com/elastic/filebeat/builds?branch=oakrizan%3Apackaging-step-fix
Heartbeat: https://buildkite.com/elastic/heartbeat/builds?branch=oakrizan%3Apackaging-step-fix
Auditbeat: https://buildkite.com/elastic/auditbeat/builds?branch=oakrizan%3Apackaging-step-fix

## Checklist

- [x] My code follows the style guidelines of this project
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] I have made corresponding change to the default configuration files
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] I have added an entry in `CHANGELOG.next.asciidoc` or `CHANGELOG-developer.next.asciidoc`.

## Author's Checklist

- [ ]

## Related issues

-

### CODE REVIEW

**Comment by oakrizan** [comment]
@dliappis PTAL

**Comment by dliappis** [comment]
@oakrizan can you provide a link showing a buildkite run with this PR?

**Comment by oakrizan** [comment]
> @oakrizan can you provide a link showing a buildkite run with this PR?

Sorry, forgot about them. Added.

**Review by dliappis — APPROVED** [review]
LGTM

**Pull request merged**
